### PR TITLE
SPATIALITE: fix insert incompatible geometry types

### LINKED ISSUE #54662: Geometry Error SpatiaLite Database
### What is the bug or the crash?

QGIS 3.28 (Firenze). In a multipolygon SpatiaLite vector layer (created in a SpatiaLite database) we used the Fill Ring tool to carve and fill a hole in a polygon. When we hit the save button to save the changes in the multipolygon layer, the filled ring disappears, but it creates a record with NULL geometry in the attribute table. Even if you delete the hole (not filled) created, the record remains in the Attribute Table.
In the DB manager, if we explore the database and the multipolygon layer created, in the Preview the hole is present, and in Table the geometry type will be MULTIPOLYGON for the existing polygon and NULL for the empty ring.
This issue was not present in the previous long-term release.

### Steps to reproduce the issue

- Create a new SpatiaLite database by right-clicking on the Spatialite entry in the Browser tree and selecting Create Database
- Create a New SpatiaLite Layer (Layer - Create Layer - New SpatiaLite Layer) in the SpatiaLite database just created with Geometry type: MultiPolygon (the Fields list apparently does not make any difference in replicating the issue, so just an integer ID field will suffice but we did not use an "autoincrementing primary key"). In the Advanced Options of the layer, we kept the specified "geometry" in Geometry column, and we removed the option to Create an autoincrementing primary key
- Edit the new layer (Toggle Editing, yellow pencil icon) and create a polygon (any shape will replicate the error). Give it any ID number
- Click on the Fill Ring tool in the Advanced digitalizing toolbar and carve a hole in the polygon. Give the filled hole a new ID number
-  Click on the floppy disk icon (Save Layer Edits) near the Toggle Editing to save the changes to the layer
- The polygon created in the ring should disappear leaving an empty hole. Its record in the Attribute Table should still be there.

### Versions

QGIS version
3.28.10-Firenze
QGIS code revision
e2edb9c468
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
pdokservicesplugin
4.1.1
quick_map_services
0.19.29
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Fix #54662

Logic shamelessly copied from potgres provider.

### CODE REVIEW

File: src/providers/spatialite/qgsspatialiteprovider.cpp [hunk 1]
```diff
@@ -127,6 +131,125 @@ bool QgsSpatiaLiteProvider::convertField( QgsField &field )
   return true;
 }
 
+QgsGeometry QgsSpatiaLiteProvider::convertToProviderType( const QgsGeometry &geom ) const
```
Comment (rouault) [inline src/providers/spatialite/qgsspatialiteprovider.cpp:134]: Why defining this whereas QgsVectorDataProvider::convertToProviderType() already exists  with apparently the same content ?

File: src/providers/spatialite/qgsspatialiteprovider.cpp [hunk 2]
```diff
@@ -4230,7 +4353,8 @@ bool QgsSpatiaLiteProvider::addFeatures( QgsFeatureList &flist, Flags flags )
           {
             unsigned char *wkb = nullptr;
             int wkb_size;
-            QByteArray featureWkb = feature->geometry().asWkb();
+            const QgsGeometry convertedGeom( convertToProviderType( feature->geometry() ) );
```
Comment (rouault) [inline src/providers/spatialite/qgsspatialiteprovider.cpp:4356]: shouldn't that be called too in QgsSpatiaLiteProvider::changeGeometryValues() ?

File: src/providers/spatialite/qgsspatialiteprovider.cpp (hunk 1 above)
Comment (elpaso) [reply src/providers/spatialite/qgsspatialiteprovider.cpp:134]: My bad, I thought it was from postgres provider. I'll use the base implementation.

File: src/providers/spatialite/qgsspatialiteprovider.cpp (hunk 2 above)
Comment (elpaso) [reply src/providers/spatialite/qgsspatialiteprovider.cpp:4356]: yes, I'll make the changes.

**Comment by elpaso** [comment]
@rouault all changes done

**Review by rouault — APPROVED** [review]

**Comment by elpaso** [comment]
@rouault the oapif and wfs providers are using spatialite in a separate thread, which was hitting the thread check here https://github.com/qgis/QGIS/blob/master/src/core/vector/qgsvectordataprovider.cpp#L899

Now, the only instance method called is a read-only wkbType(), wkb type is not supposed to be changed by the provider so the implementation should be thread safe but for extra safety I decided to create a new static version of the method and proxy the instance method to the static call.

Can you please please review my last changes?
