### PR TITLE
fix georeferencer sticky move gcp button

### LINKED ISSUE #37248: Georeferencer sticky Move GCP point button
**Describe the bug**
In the georeferencer, if one clicks the *Move GCP point* button and moves a GCP, then clicks *Add point*, after each new GCP is added the *Move GCP point* button gets pressed. 

**How to Reproduce**
- Open a raster in the georeferencer
- Add a few GCPs
- Click the *Move GCP point* button and move a GCP
- Click *Add point* button and add a new GCP
- The *Add point* button becomes visually un-pressed and the *Move GCP point* button becomes visually pressed. The actual action when clicking on the canvas remain that of *Add point* though.

**QGIS and OS versions**
b2da49b7 on Debian testing

**Additional context**
*Move GCP Point* actually means *Move Ground Control Point Point*

### PR DESCRIPTION
**Pull request by uclaros**
## Description
Store a pointer to the active map tool so the georeferencer does not stick with the move GCP tool

Fixes #37248

### CODE REVIEW

**Comment by Saijin-Naib** [comment]
These fixes are so great for UX. Thank you!

**Comment by uclaros** [comment]
This PR is ready for a review

File: src/app/georeferencer/qgsgeorefmainwindow.cpp [hunk 1]
```diff
@@ -401,16 +401,22 @@ void QgsGeoreferencerMainWindow::generateGDALScript()
 void QgsGeoreferencerMainWindow::setAddPointTool()
 {
   mCanvas->setMapTool( mToolAddPoint );
+  QgisApp::instance()->mapCanvas()->setMapTool( mPrevQgisMapTool );
```
Comment (nyalldawson) [inline src/app/georeferencer/qgsgeorefmainwindow.cpp:404]: I think we should check here that mPrevQgisMapTool is not nullptr. Otherwise I believe that on creation QgsGeoreferencerMainWindow will call setAddPointTool with mPrevQgisMapTool as null, and cause the qgis window to lose its current map tool immediately

**Review by nyalldawson — APPROVED** [review]
