### PR TITLE
Fix slow topological editing when avoid intersection

### LINKED ISSUE #44198: Topological Vertex editing has become slow
**Describe the bug**
When moving vertices on big geometries while having *topological editing* enabled and overlap avoidance on *Follow advanced configuration*, even with no layers enabled to snap or avoid overlaps, then each vertex move takes seconds to complete.

This was introduced by #41658
(pinging @lbartoletti )

**How to Reproduce**
1. Add a polygon layer
2. Enable topological editing
3. Set overlap avoidance to Follow advanced configuration
4. Start editing
5. Use the vertex tool to move a vertex on a large polygon
6. wait 4 seconds for each 2000 vertices in the polygon (on my machine)

**QGIS and OS versions**
02266ef8e6 on Debian bullseye

### LINKED ISSUE #47595: Vertex tool triggers layer.geometryChanged three times
### What is the bug or the crash?

Any edit done with the vertex tool causes the underlying vector layer to emit the `geometryChanged` signal three times instead of one.
@lbartoletti could be related to  #44198 since it is also caused by your changes in #41658

### Steps to reproduce the issue

1. add a vector layer
2. connect its `geometryChanged` signal to some function
3. use the vertex tool to edit a single vertex
4. the function is called three times (instead of one)

### Versions

bcdb670, all versions since #41658

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### LINKED ISSUE #49311: Snapping on segment with vertex tool does not create topological points if geometry precision is enabled
### What is the bug or the crash?

If geometry precision option is enabled for the currently edited layer, using vertex tool and snapping to a segment of another layers feature does not create a topological point on the other layers feature.

### Steps to reproduce the issue

- Open [vertextool.zip](https://github.com/qgis/QGIS/files/11673802/vertextool.zip) project file (open from - geopackage) 
- Enabled editing on all vector layers
- Use vertex tool on first layer, and snap a vertex on the segment of a feature on the second layer, observe that a topological vertex is created on the second layer
  - image
- Use vertex tool on first-mm-grid layer, and snap a vertex on the segment of a feature on the second-mm-grid layer, observe that a topological vertex is not created on the second-mm-grid layer (and the created vertex was snapped to specified precision)
  - image

### Versions

QGIS version
3.22.8-Białowieża
QGIS code revision
8d5e9761df
Qt version
5.15.3
Python version
3.9.5
Compiled against GDAL/OGR
3.5.0
Running against GDAL/OGR
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Snapping to a segment of another feature on the same layer creates a topological point on the other feature.

### PR DESCRIPTION
**Pull request by troopa81**
This PR supersedes #50431 and so fixes #44198

It registers all the new modified points when editing so we can add ALL those points as topological points.

When avoid intersection is involved (and only in this case contrary to #50431), we compute the new points with a point difference with the original geometry.

This PR also fixes #47595 and fire only ONE geometry changed signal when we avoid intersection.

It also fixes #49311

**Funded by Lille Metropole**

### CODE REVIEW

**Comment by troopa81** [comment]
@uclaros If possible, I would like to have your eyes on this.

**Comment by uclaros** [comment]
Sorry @troopa81 , I've been a little busy lately. I'll try to have a look this week.

**Comment by troopa81** [comment]
> Sorry @troopa81 , I've been a little busy lately. I'll try to have a look this week.

Thanks, I'm looking forward to see your review

**Comment by ismogis** [comment]
@troopa81 This PR fixes also #49311.

Additionally, it fixes partly #49312. See my comments in that issue.

**Comment by troopa81** [comment]
> @troopa81 This PR fixes also https://github.com/qgis/QGIS/issues/49311.

Thanks for testing, I added your test into this PR [ed4cdd6](https://github.com/qgis/QGIS/pull/53632/commits/ed4cdd605417d7b685a261cafb2004eb5693fc38)

> Additionally, it fixes partly https://github.com/qgis/QGIS/issues/49312. See my comments in that issue.

I'm gonna take a look about what is the remaining issue

**Comment by troopa81** [comment]
@uclaros Gentle reminder, do you think you'll have the time to review this soon? I would like to see it merge before feature freeze (even if there are fixes only, there is many modifications)

File: tests/src/app/testqgsvertextool.cpp [hunk 1]
```diff
@@ -1465,6 +1578,44 @@ void TestQgsVertexTool::testSelectVerticesByPolygon()
...
+  mLayerMultiPolygon->geometryOptions()->setGeometryPrecision( 0.1 );
+  const double geomPrecPolygon = mLayerPolygon->geometryOptions()->geometryPrecision();
+  mLayerPolygon->geometryOptions()->setGeometryPrecision( 0.1 );
+
+  // move a corner of the multipolygon near to the polygon
+  mouseClick( 4, 5, Qt::LeftButton, Qt::KeyboardModifiers(), true );
+  mouseClick( 4.95, 4.05, Qt::LeftButton, Qt::KeyboardModifiers(), true );
+
+  // a snapped vertex increases the number of vertices in polygon by one
+  QCOMPARE( mLayerPolygon->getFeature( mFidPolygonF1 ).geometry().constGet()->vertexCount(), 6 );
```
Comment (lbartoletti) [inline tests/src/app/testqgsvertextool.cpp:1604]:
```suggestion
  QCOMPARE( mLayerPolygon->getFeature( mFidPolygonF1 ).geometry().constGet()->vertexCount(), 5 );
```

File: tests/src/app/testqgsvertextool.cpp [hunk 2]
```diff
@@ -434,6 +449,59 @@ void TestQgsVertexTool::testTopologicalEditingMoveVertexOnIntersectionZ()
...
+
+  // Verifies than the temp line has been moved and topological vertices added.
+  QCOMPARE( mLayerLineZ->getFeature( linez.id() ).geometry().asWkt(), QString( "LineStringZ (5.5 7 6.25, 6.5 7 10)" ) );
+  QCOMPARE( mLayerLineZ->getFeature( mFidLineZF2 ).geometry().asWkt(), QString( "LineStringZ (5 7 5, 5.5 7 6.25, 6.5 7 10, 7 7 10)" ) );
+
+  // Undo changes
+  mLayerLineZ->deleteFeature( linez.id() );
+
+  QgsProject::instance()->setTopologicalEditing( topologicalEditing );
+  mLayerLineZ->undoStack()->undo();
```
Comment (lbartoletti) [inline tests/src/app/testqgsvertextool.cpp:494]: Not your fault, but a note for us for later. I always hated this kind of tests. All tests must be unique and idempotent.

**Comment by lbartoletti** [comment]
About #47595 do you have a comparison time before and with your MR? Maybe @uclaros can test on it's dataset?

**Review by lbartoletti — COMMENTED** [review]
Seems ok, but have to be tested. It should not be backported without advanced user testing.

File: tests/src/app/testqgsvertextool.cpp [hunk 3]
```diff
@@ -1601,7 +1601,7 @@ void TestQgsVertexTool::testTopologicalEditingMoveVertexCreateTopoPoint()
   mouseClick( 4.95, 4.05, Qt::LeftButton, Qt::KeyboardModifiers(), true );
 
   // a snapped vertex increases the number of vertices in polygon by one
-  QCOMPARE( mLayerPolygon->getFeature( mFidPolygonF1 ).geometry().constGet()->vertexCount(), 6 );
+  QCOMPARE( mLayerPolygon->getFeature( mFidPolygonF1 ).geometry().constGet()->vertexCount(), 5 );
```
Comment (ismogis) [inline tests/src/app/testqgsvertextool.cpp:1604]: @lbartoletti I'd say that the count should be six. There were five vertices in mFidPolygonF1 and this should test if a topological point were added as sixth vertex.

**Comment by troopa81** [comment]
> About https://github.com/qgis/QGIS/issues/47595 do you have a comparison time before and with your MR? Maybe @uclaros can test on it's dataset?

Thanks for reviewing @lbartoletti 

Regarding https://github.com/qgis/QGIS/issues/47595 it just cuts down the number of signal fired from 3 to only one, so time would depend on what you are actually doing in your slot.

The slowliness is more related to https://github.com/qgis/QGIS/issues/44198. I tried to edit a 40000 points polygon with avoid overlap and topological editing enabled. Without this PR, it blocks for a long time (didn't have the patience to wait but more than 5 minutes), with the PR, it is instantaneous.

> Seems ok, but have to be tested. It should not be backported without advanced user testing.

There will be no backport, too dangerous

File: tests/src/app/testqgsvertextool.cpp (hunk 3 above)
Comment (troopa81) [reply tests/src/app/testqgsvertextool.cpp:1604]: It was working on my machine because geometry precision was compatible with the snapped point, but CI precision difference would make it fail.

Anyway, see my comment [here](https://github.com/qgis/QGIS/issues/49311#issuecomment-1715992001) but I think this test is not relevant. I'm gonna remove it if you agree

**Review by uclaros — COMMENTED** [review]
Thanks @troopa81 and sorry for taking that long to look at this...

This has improved speed _a lot_. Picking up vertices is still a little sluggish for big geometries when topological editing is enabled (for example picking up points in USA/Canada from the `world` easter egg dataset takes a couple of seconds). I will test on a release build tomorrow morning and come back to you.

Update: The picking up vertices delay is not there on the release build! \o/ (it is still slow to pick up _many vertices_ at once, but this is not a regression)

File: src/core/geometry/qgsgeometryeditutils.cpp [hunk 4]
```diff
@@ -346,5 +346,12 @@ std::unique_ptr<QgsAbstractGeometry> QgsGeometryEditUtils::avoidIntersections( c
     return nullptr;
   }
 
+  if ( QgsWkbTypes::isMultiType( geomTypeBeforeModification ) && QgsWkbTypes::isSingleType( diffGeom->wkbType() ) )
```
[the remark this answers is not in the document]
Comment (troopa81) [reply src/core/geometry/qgsgeometryeditutils.cpp:349]: Fixed in [c7528e2](https://github.com/qgis/QGIS/pull/53632/commits/c7528e28759303bf6fb4cbacb7dcf7bbe95921b6)

**Comment by troopa81** [comment]
@uclaros Thank you for testing and reviewing. I treated your comment.

**Comment by troopa81** [comment]
@uclaros are you ok to approve this PR ?

**Review by uclaros — APPROVED** [review]

**Review by lbartoletti — APPROVED** [review]

**Comment by lbartoletti** [comment]
Thanks @troopa81
