### PR TITLE
Correctly move layout legend nodes when they are filtered

### LINKED ISSUE #60383: Rule based symbology sorting with all fields in legend when only linked maps is ticked
### What is the bug or the crash?

The issue occurs when using rule based symbologies with a greater number of classes then displayed on a map. When you go to the legend in a print layout, and tick 'Only show items in linked maps' the legend will hide any rule based classes that are not shown in the map. However, when trying to rearrange the order of any remaining legend items you must click the arrows extra times before they reorganise, I believe that this is due to them rearranging based on all labels, rather than only the labels shown in the map.

### Steps to reproduce the issue

Open a the project 'Broken Legend'
Open Print Layout 'map1'
In the 'Item Properties' for the legend try moving SC down to the bottom. It will take several clicks of the down arrow.
If you untick the 'Only show inside linked maps' button you will see that it has reordered the whole list of possible symbologies.

[BrokenLegend.zip](https://github.com/user-attachments/files/18621257/BrokenLegend.zip)

### Versions

QGIS version
3.40.3-Bratislava
QGIS code revision
2a274ab7
 
Libraries
Qt version
5.15.13
Python version
3.12.8
GDAL/OGR version
3.10.1
PROJ version
9.5.1
EPSG Registry database version
v11.022 (2024-11-05)
GEOS version
3.13.0-CAPI-1.19.0
SQLite version
3.46.1
PDAL version
2.8.3
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.3.0
QScintilla2 version
2.14.1
OS version
Windows 11 Version 2009
 
Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Djedouas**
## Description

Fixes #60383.

In a layout, when moving a legend node on a filtered legend, the computed offset was wrong if some nodes were hidden between the node to move and its destination.

The offset is now computed with the next/previous visible index.

### CODE REVIEW

**Comment by Djedouas** [comment]
I don't see why clang-tidy fails here...  locally I don't get the moc file missing error, only the warnings.

By the way, I did not change anything in the includes.

**Comment by troopa81** [comment]
#60592 Should fix the cland-tidy issue but it's not related at all to this PR

**Comment by troopa81** [comment]
You have to fix the warning in clang-tidy, an anonymous namespace may fix it

File: src/gui/layout/qgslayoutlegendwidget.cpp [hunk 1]
```diff
@@ -770,8 +772,17 @@ void QgsLayoutLegendWidget::mMoveDownToolButton_clicked()
...
   else // legend node
   {
-    _moveLegendNode( legendNode->layerNode(), _unfilteredLegendNodeIndex( legendNode ), 1 );
-    mItemTreeView->layerTreeModel()->refreshLayerLegend( legendNode->layerNode() );
+    // get the next index, the one that will have to be above our index,
+    const QModelIndex nextIndex = index.siblingAtRow( index.row() + 1 );
+    if ( nextIndex.isValid() )
+    {
+      QgsLayerTreeModelLegendNode *nextLegendNode = mItemTreeView->index2legendNode( nextIndex );
+      if ( nextLegendNode )
```
Comment (troopa81) [inline src/gui/layout/qgslayoutlegendwidget.cpp:780]:
```suggestion
      QgsLayerTreeModelLegendNode *nextLegendNode = nextIndex.isValid() ? mItemTreeView->index2legendNode( nextIndex ) : nullptr;
      if ( nextLegendNode )
```

Just an esthetic proposal

**Review by troopa81 — COMMENTED** [review]
just a cosmetic proposal, the rest looks good

File: src/gui/layout/qgslayoutlegendwidget.cpp [hunk 2]
```diff
@@ -808,8 +816,17 @@ void QgsLayoutLegendWidget::mMoveUpToolButton_clicked()
   }
   else // legend node
   {
-    _moveLegendNode( legendNode->layerNode(), _unfilteredLegendNodeIndex( legendNode ), -1 );
-    mItemTreeView->layerTreeModel()->refreshLayerLegend( legendNode->layerNode() );
+    // get the previous index, the one that will have to be below our index,
+    const QModelIndex prevIndex = index.siblingAtRow( index.row() - 1 );
+    if ( prevIndex.isValid() )
```
Comment (troopa81) [inline src/gui/layout/qgslayoutlegendwidget.cpp:821]: Could you the same as above ?

Comment (Djedouas) [reply src/gui/layout/qgslayoutlegendwidget.cpp]: Oh yes, 😄 

Done, and rebased onto master.

**Comment by troopa81** [comment]
unrelated test failure
