### PR TITLE
Fix legend icon geom generator is involved

### LINKED ISSUE #33755: Wrong size of legend symbols when using Geometry generator symbology
Hello, 
I get really big symbols in the legend on a point layer with surface or line geometry generator when I choose categorized symbols.

For example : 
- I create a new point memory layer 
- I add a column "type"  (integer)
- For style, I choose categorized symbols on "type" column
- For symbols, I choose surface geometry generator (`buffer ($ geometry, 2)`)
- Then in legend I get really big symbols for each type.

I am working with QGIS 3.4.14 LTR on Windows 7 or 10.
I try with QGIS 3.10.1, I have the same behaviour.
Qgis_issue_categorized_symbols

### PR DESCRIPTION
**Pull request by troopa81**
Fixes #33755

When geometry generator is involved we cannot get a valid *restrictedSymbolSize*, and so when the generated geometry is too big the displayed icon has a 512x512 size (largeIconSize maximum). 

I propose to have a special case when geometry generator is involved and to limit the total size of the icon to the settings legendsymbolMaximumSize. 

The result gives this for instance with a buffer($geometry,200) on point
withscaleFalse

Note that the generated buffered circle exceed bounds and is not scaled to the icon size. But it seems to be the [intented behavior](https://github.com/qgis/QGIS/blob/master/src/core/symbology/qgsgeometrygeneratorsymbollayer.cpp#L262) 

**Sponsored by Metropole de Lille** cc @Jean-Roc

### CODE REVIEW

File: src/core/layertree/qgslayertreemodellegendnode.cpp [hunk 1]
```diff
@@ -343,25 +344,36 @@ QSize QgsSymbolLegendNode::minimumIconSize( QgsRenderContext *context ) const
...
-              true ).size();
-  }
-  else if ( mItem.symbol() && mItem.symbol()->type() == Qgis::SymbolType::Line )
-  {
-    double width = 0.0;
-    double height = 0.0;
-    const std::unique_ptr<QgsSymbol> symbol( QgsSymbolLayerUtils::restrictedSizeSymbol( mItem.symbol(), MINIMUM_SIZE, MAXIMUM_SIZE, context, width, height ) );
+
+    bool hasRestrictedSizeSymbol = true;
+    for ( QgsSymbolLayer *sl : mItem.symbol()->symbolLayers() )
```
Comment (elpaso) [inline src/core/layertree/qgslayertreemodellegendnode.cpp:352]: const iterate if this detaches

File: src/core/layertree/qgslayertreemodellegendnode.cpp [hunk 2]
```diff
@@ -343,25 +344,36 @@ QSize QgsSymbolLegendNode::minimumIconSize( QgsRenderContext *context ) const
...
+      if ( dynamic_cast<QgsGeometryGeneratorSymbolLayer *>( sl ) )
+        hasRestrictedSizeSymbol = false;
+
+    int maxSize = largeIconSize;
+    std::unique_ptr<QgsSymbol> symbol;
+    if ( hasRestrictedSizeSymbol )
+    {
+      // unusued width, height variables
+      double width = 0.0;
```
Comment (elpaso) [inline src/core/layertree/qgslayertreemodellegendnode.cpp:361]:
```suggestion
      const double width = 0.0;
```

File: src/core/layertree/qgslayertreemodellegendnode.cpp [hunk 3]
```diff
@@ -343,25 +344,36 @@ QSize QgsSymbolLegendNode::minimumIconSize( QgsRenderContext *context ) const
...
+      double height = 0.0;
```
Comment (elpaso) [inline src/core/layertree/qgslayertreemodellegendnode.cpp:362]:
```suggestion
      const double height = 0.0;
```

**Review by elpaso — APPROVED** [review]
LGTM

File: src/core/layertree/qgslayertreemodellegendnode.cpp [hunk 4]
```diff
@@ -343,25 +344,36 @@ QSize QgsSymbolLegendNode::minimumIconSize( QgsRenderContext *context ) const
...
-              minSz,
-              true ).size();
-  }
-  else if ( mItem.symbol() && mItem.symbol()->type() == Qgis::SymbolType::Line )
-  {
-    double width = 0.0;
-    double height = 0.0;
-    const std::unique_ptr<QgsSymbol> symbol( QgsSymbolLayerUtils::restrictedSizeSymbol( mItem.symbol(), MINIMUM_SIZE, MAXIMUM_SIZE, context, width, height ) );
+
+    bool hasRestrictedSizeSymbol = true;
```
Comment (nyalldawson) [inline src/core/layertree/qgslayertreemodellegendnode.cpp:351]: why not have all this logic in QgsSymbolLayerUtils::restrictedSizeSymbol ?

Comment (troopa81) [reply src/core/layertree/qgslayertreemodellegendnode.cpp]: Done, but I have to rely on height/width value to make the difference between the case when it's not possible to compute the restricted size symbol and the case when you don't need it because size is just fine

File: src/core/layertree/qgslayertreemodellegendnode.cpp (hunk 1 above)
Comment (troopa81) [reply src/core/layertree/qgslayertreemodellegendnode.cpp]: done
