### PR TITLE
Fix building on MinGW-w64/UCRT

### LINKED ISSUE #51767: qgis segfaults on MINGW-UCRT
### What is the bug or the crash?

After a successful building of qgis on MinGW-w64/UCRT with both GCC and Clang. It segfaults/crash.
It starts and runs on MinGW/MSVCRT.

### Steps to reproduce the issue

- Install MSYS2.
- Install qgis on UCRT64 or CLANG64.
- run qgis from shell.

### Versions

3.28.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

downstream issue https://github.com/msys2/MINGW-packages/issues/15466

### PR DESCRIPTION
**Pull request by MehdiChinoune**
## Description

qgis was crashing on mingw-w64/ucrt, It was discovered that
wcstok was not declared correctly on mingw-w64 which was fixed in
https://github.com/mingw-w64/mingw-w64/commit/40134887

Fixes #51767

### CODE REVIEW

**Comment by lbartoletti** [comment]
Thanks @MehdiChinoune 

For the context, maybe you can add a description for this PR. I think, it's related to previous works on msys2/mingw package you've merged recently?

**Review by lbartoletti — APPROVED** [review]

File: src/app/mainwin.cpp [hunk 1]
```diff
@@ -144,7 +144,11 @@ int CALLBACK WinMain( HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdL
 
     wchar_t *path = wcsdup( _wgetenv( L"PATH" ) );
 
+#ifdef _UCRT
```
Comment (rouault) [inline src/app/mainwin.cpp:147]: According to https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/strtok-strtok-l-wcstok-wcstok-l-mbstok-mbstok-l?view=msvc-170, the 2 parameter wcstok() is non standard and there's the standard 3 parameters wcstok(), which is also the C++ std::wcstok (https://en.cppreference.com/w/cpp/string/wide/wcstok)
So you could just remove the #ifdef and use unconditionally the 3 parameter wcstok()

Comment (MehdiChinoune) [reply src/app/mainwin.cpp:147]: It won't build with mingw-w64/msvcrt

Comment (rouault) [reply src/app/mainwin.cpp:147]: > It won't build with mingw-w64/msvcrt

and what if you use ``std::wcstok`` instead ? (with ``#include <cwchar>``)

Comment (MehdiChinoune) [reply src/app/mainwin.cpp:147]: I don't know!

Comment (rouault) [reply src/app/mainwin.cpp:147]: > I don't know!

just try :-)

Comment (MehdiChinoune) [reply src/app/mainwin.cpp:147]: I won't.

Comment (MehdiChinoune) [reply src/app/mainwin.cpp:147]: I hate when people start suggesting things they don't know if they work or not, just to block fixing a bug!
Try it yourself and see if It works or not!

**Comment by rouault** [comment]
@MehdiChinoune I don't want bad feelings to be instated or to block anything (I didn't change the approval status of the PR). I was just suggesting a tiny improvement to potentially avoid a #ifdef that can complicate long term maintenance. Re-opening and enabling auto-merge.

**Comment by lbartoletti** [comment]
@MehdiChinoune This is no way to talk to the contributors who are there to help you nicely.

Thanks to you @rouault ! When I will have some time on windows/mingw, I will test your suggestion.
