### PR TITLE
fix crash when exporting check geometries gaps

### LINKED ISSUE #34661: QGIS crashes when exporting check geometries results
**Describe the bug**
QGIS crashes when trying to export the results of *Check Geometries*, specifically when the results contain Gaps.

**How to Reproduce**
-Run check geometries on a polygon layer with gaps, selecting *check for gaps smaller than...*
-Click export on the results tab

**QGIS and OS versions**
Master on Debian

### PR DESCRIPTION
**Pull request by uclaros**
## Description
Check geometries Gaps results do not belong to a layer, so `error->layerId()` returns an empty string. `mChecker->featurePools()[error->layerId()]->layer()` then crashes QGIS.

I guess it should be backported too.

Fixes #34661

### CODE REVIEW

File: src/plugins/geometry_checker/qgsgeometrycheckerresulttab.cpp [hunk 1]
```diff
@@ -278,9 +278,16 @@ bool QgsGeometryCheckerResultTab::exportErrorsDo( const QString &file )
   for ( int row = 0, nRows = ui.tableWidgetErrors->rowCount(); row < nRows; ++row )
   {
     QgsGeometryCheckError *error = ui.tableWidgetErrors->item( row, 0 )->data( Qt::UserRole ).value<QgsGeometryCheckError *>();
-    QgsVectorLayer *srcLayer = mChecker->featurePools()[error->layerId()]->layer();
+    QString layerName = QString( "" );
```
Comment (m-kuhn) [inline src/plugins/geometry_checker/qgsgeometrycheckerresulttab.cpp]:
```suggestion
    QString layerName = QString();
```

**Review by m-kuhn — APPROVED** [review]
