### PR TITLE
[ogr] fix JSON array interpreted as QVariantMap

### LINKED ISSUE #61728: Not support JSON attribute fields.
### What is the bug or the crash?

This results in gaps when performing geospatial operations (buffering, merging, parsing, etc.) on layers containing JSON fields, even if these fields are not involved in processing.

### Steps to reproduce the issue

-

### Versions

<table width='100%' align='center'><tr><td>Версия QGIS</td><td>3.40.6-Bratislava</td></tr><tr><td>Ревизия</td><td><a href="https://github.com/qgis/QGIS/commit/5d7f6a3e26">5d7f6a3e26</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Библиотеки</b></td></tr><tr><td>Версия Qt</td><td>5.15.13</td></tr><tr><td>Версия Python</td><td>3.12.10</td></tr><tr><td>GDAL version</td><td>3.10.3</td></tr><tr><td>Версия PROJ</td><td>9.6.0</td></tr><tr><td>Версия базы данных реестра EPSG</td><td>v12.004 (2025-03-02)</td></tr><tr><td>Версия GEOS</td><td>3.13.1-CAPI-1.19.2</td></tr><tr><td>Версия SQLite</td><td>3.46.1</td></tr><tr><td>Версия PDAL</td><td>2.8.3</td></tr><tr><td>Версия PostgreSQL</td><td>unknown</td></tr><tr><td>Версия SpatiaLite</td><td>5.1.0</td></td></tr><tr><td>Версия QWT</td><td>6.3.0</td></tr><tr><td>Версия QScintilla2</td><td>2.14.1</td></tr><tr><td>Версия ОС</td><td>Windows 10 Version 2009</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Включённые модули Python</b></td></tr><tr><td>debug_vs</td><td>0.8</td></tr><tr><td>DigitizingTools</td><td>1.5.3</td></tr><tr><td>FreehandRasterGeoreferencer</td><td>0.8.3</td></tr><tr><td>plugin_reloader</td><td>0.17</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Fix #61728

### CODE REVIEW

File: src/core/providers/ogr/qgsogrprovider.cpp [hunk 1]
```diff
@@ -886,16 +886,90 @@ void QgsOgrProvider::loadFields()
...
+              {
+                if ( !item.is_string() )
+                {
+                  allStrings = false;
+                }
+                if ( !item.is_number_integer() )
+                {
+                  allInts = false;
+                }
+                if ( !item.is_number_float() )
```
Comment (rouault) [inline src/core/providers/ogr/qgsogrprovider.cpp:932]: perhaps add a test case for this:
```suggestion
                // We accept integers in mixed list of integer and double, represented as a list of double
                else if ( !item.is_number_float() )
```

**Review by rouault — APPROVED** [review]
LGTM (just a little comment)

**Comment by rouault** [comment]
I'm wondering how safe this is for backporting though. Tradeoff risk vs benefit is not obvious to me

**Comment by elpaso** [comment]
> I'm wondering how safe this is for backporting though. Tradeoff risk vs benefit is not obvious to me

It scares me too. I would say not to backport.

File: src/core/providers/ogr/qgsogrprovider.cpp (hunk 1 above)
Comment (elpaso) [reply src/core/providers/ogr/qgsogrprovider.cpp]: I have added a test and found out that this code is never reached: homogeneous arrays of numbers and strings are already correctly identified by OGR.

The only cases we need to handle here is when it's an array of mixed types (numbers and strings) or if it contains objects with not  homogeneous values.

I have moved the above logic to the objects identification to make sure we fall back to string when a complex object is found.
