### PR TITLE
qgscoordinatetransform_p.cpp: avoid issues when opening projects using PROJ < 7 grid names (fixes #45470)

### LINKED ISSUE #45470: QGIS 3.21.0: preset transform required "nehpgn.gsb" but downloads "nehpgn.tif" which does not work
### What is the bug or the crash?

When opening an existing project from QGIS 3.20.3 I get the following error message:
-----
This project specifies a preset transform between EPSG:3437 - NAD83 / New Hampshire (ftUS) and EPSG:4326 - WGS 84, which is not available for use on the system.
This transformation requires the grid file “nehpgn.gsb”, which is not available for use on the system.
The operation specified for use in the project is:
+proj=pipeline +step +proj=unitconvert +xy_in=us-ft +xy_out=m +step +inv +proj=tmerc +lat_0=42.5 +lon_0=-71.6666666666667 +k=0.999966667 +x_0=300000 +y_0=0 +ellps=GRS80 +step +proj=hgridshift +grids=nehpgn.gsb +step +proj=unitconvert +xy_in=rad +xy_out=deg

This grid is available for download from https://cdn.proj.org/us_noaa_nehpgn.tif.
  [ Install nehpgn.gsb from Folder... ]
-----
The download link does download us_noaa_nehpgn.tif, 
however, the "Install nehpgn.gsb from Folder..." button goes to a dialog looking for a .gsb file
Selecting in that dialog "...,TIF,.." does allow me to select the .tif file, but results in
"Could not copy nehpgn.gsb to /Users/garth/Library/Application Support/QGIS/QGIS3/profiles/default/proj/us_noaa_nehpgn.tif. Please check folder permissions and retry."

after changing extension from .tif to .gsb, the same dialog does accept the .gsb file and reports:
"The nehpgn.gsb grid shift file has been successfully installed. Please restart QGIS for this change to take effect."

However, same error occurs after restarting QGIS...

By the way, the entry at https://cdn.proj.org/ is described as:
"us_noaa_nehpgn.tif - USA - New England (CT,MA,NH,RI,VT) - NAD83 (EPSG:4269) to NAD83(HARN) (EPSG:4152). Last modified: 2020-01-24"

-------------------------------
Environment per About QGIS:
-------------------------------
QGIS version	3.21.0-Master
QGIS code revision	8498c5549f
Qt version	5.15.2
Python version	3.9.5
GDAL/OGR version	3.3.2
PROJ version	8.1.1
EPSG Registry database version	v10.028 (2021-07-07)
GEOS version	3.9.1-CAPI-1.14.2
SQLite version	3.35.2
PDAL version	2.3.0
PostgreSQL client version	12.3
SpatiaLite version	5.0.1
QWT version	6.1.6
QScintilla2 version	2.11.5
OS version	macOS High Sierra (10.13)

Active Python plugins
FreehandRasterGeoreferencer	0.8.3
VectorBender	0.2.1
AzimuthMeasurement	0.2.2
rectanglify	1.0.3
MagneticDeclination	2.3.1
GarminCustomMap	3.3
TerrainShading	0.9
MemoryLayerSaver	4.0.4
parcel_plugin	3.6
valuetool	3.0.13
mapswipetool_plugin	1.2
coordinate_capture	0.2
processing	2.12.99
sagaprovider	2.12.99
grassprovider	2.12.99
db_manager	0.1.20
MetaSearch	0.3.5

### Steps to reproduce the issue

Open the QGIS 3.20.3 project, get error message, click on Details

### Versions

QGIS version	3.21.0-Master
QGIS code revision	8498c5549f
Qt version	5.15.2
Python version	3.9.5
GDAL/OGR version	3.3.2
PROJ version	8.1.1
EPSG Registry database version	v10.028 (2021-07-07)
GEOS version	3.9.1-CAPI-1.14.2
SQLite version	3.35.2
PDAL version	2.3.0
PostgreSQL client version	12.3
SpatiaLite version	5.0.1
QWT version	6.1.6
QScintilla2 version	2.11.5
OS version	macOS High Sierra (10.13)

Active Python plugins
FreehandRasterGeoreferencer	0.8.3
VectorBender	0.2.1
AzimuthMeasurement	0.2.2
rectanglify	1.0.3
MagneticDeclination	2.3.1
GarminCustomMap	3.3
TerrainShading	0.9
MemoryLayerSaver	4.0.4
parcel_plugin	3.6
valuetool	3.0.13
mapswipetool_plugin	1.2
coordinate_capture	0.2
processing	2.12.99
sagaprovider	2.12.99
grassprovider	2.12.99
db_manager	0.1.20
MetaSearch	0.3.5

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rouault**
Only use proj_coordoperation_is_instantiable() if PROJ networking is enabled.
The reason is that proj_coordoperation_is_instantiable() in PROJ < 9.0
does not work properly when a coordinate operation refers to a PROJ < 7 grid name (gtx/gsb)
but the user has installed PROJ >= 7 GeoTIFF grids.
Cf https://github.com/OSGeo/PROJ/pull/3025.
When networking is not enabled, proj_create() will check that all grids are
present, so proj_coordoperation_is_instantiable() is not necessary.

One of that fix or https://github.com/OSGeo/PROJ/pull/3025 are sufficient to fix the issue

### CODE REVIEW

**Comment by agiudiceandrea** [comment]
@rouault does this also fix https://github.com/qgis/QGIS/issues/44061, as well as https://github.com/qgis/QGIS/issues/45470?

**Comment by rouault** [comment]
> does this also fix #44061,

this looks to be a duplicate of #45470

File: src/core/proj/qgscoordinatetransform_p.cpp [hunk 1]
```diff
@@ -288,7 +288,20 @@ ProjData QgsCoordinateTransformPrivate::threadLocalProjData()
   if ( !mProjCoordinateOperation.isEmpty() )
   {
     transform.reset( proj_create( context, mProjCoordinateOperation.toUtf8().constData() ) );
-    if ( !transform || !proj_coordoperation_is_instantiable( context, transform.get() ) )
+    // Only use proj_coordoperation_is_instantiable() if PROJ networking is enabled.
+    // The reason is that proj_coordoperation_is_instantiable() in PROJ < 9.0
+    // does not work properly when a coordinate operation refers to a PROJ < 7 grid name (gtx/gsb)
+    // but the user has installed PROJ >= 7 GeoTIFF grids.
+    // Cf https://github.com/OSGeo/PROJ/pull/3025.
```
Comment (nyalldawson) [inline src/core/proj/qgscoordinatetransform_p.cpp:295]: I'm a little confused here -- did this behaviour change somewhere after proj 6? Does proj_create return a nullptr now if the networking is disabled and the grids are not available? 

I can't recall the exact circumstances for this check when it was originally written, but it predated the proj networking so at that stage at least proj_create was returning a non-nullptr for proj_create, yet was returning a non-instantiable operation...

Comment (rouault) [reply src/core/proj/qgscoordinatetransform_p.cpp:295]: > Does proj_create return a nullptr now if the networking is disabled and the grids are not available?

yes

> at least proj_create was returning a non-nullptr for proj_create, yet was returning a non-instantiable operation...

I can't reproduce that with

```
#include <proj.h>
#include <stdio.h>

int main()
{
    printf("is_null=%d\n", proj_create(NULL, "+proj=hgridshift +grids=i_dont_exist") == NULL);
    return 0;
}
```
It returns is_null=1 with PROJ 6.3.1 and master

Comment (nyalldawson) [reply src/core/proj/qgscoordinatetransform_p.cpp:295]: Ahhh.... I suspect it was probably a result of copy-and-paste from the code at line 356 or 418 which uses proj_list_get over all candidate operations and then tests instantiability for each in turn. 

I'm guessing QgsDatumTransform::transformDetailsFromPj will also need updating, since that also uses proj_coordoperation_is_instantiable ?

Comment (nyalldawson) [reply src/core/proj/qgscoordinatetransform_p.cpp:295]: > I'm guessing QgsDatumTransform::transformDetailsFromPj will also need updating, since that also uses proj_coordoperation_is_instantiable ?

Actually no, that seems fine.

**Review by nyalldawson — APPROVED** [review]
