### PR TITLE
Fix missing stats after raster calc output

### LINKED ISSUE #42835: Raster calculator does not create/store statistics for output rasters
Apparent bug in QGIS raster calculator: The raster calculator produces incorrect results.

Steps to reproduce:
Context - I'm trying to normalise a population density map - e.g. to get the range of values to go between 0 and 255.
Step 1 - Import https://data.worldpop.org/GIS/Population_Density/Global_2000_2020_1km/2020/GBR/gbr_pd_2020_1km.tif
Step 2 - Note that it has a maximum value of 27500.1
Step 3 - Do literally any calculation. E.g. just do "gbr_pd_2020_1km@1" * 1 and it changes the maximum to 21367.
Step 4 - As another example, try "gbr_pd_2020_1km@1" / 27500.1. It should give a range up to 1 - but instead it only goes up to 0.8
Step 5 - If you want to try and actually normalise the map (as I want to) try ("gbr_pd_2020_1km@1" * 255) / 27500.1 - instead of values up to 255, it only goes to 198.

I can't seem to attach a screenshot, but you can see it here https://gis.stackexchange.com/questions/394114/bug-in-qgis-raster-calculator (Note I linked an incorrect file there - the screenshot refers to the file linked above. But it makes no difference to the point I'm making).

I've also tried doing the same via 'Processing Toolbox' then GDAL Raster Calculator, but it gives the same incorrect results.

Many thanks.

**QGIS and OS versions**

I've tried this in QGIS 3.16.5 and 3.18 (the latest LTR and beta releases available), and am running it on the latest version of Mac OS (Big Sur 11.2.3).

Fuller details pasted as requested:

QGIS version | 3.16.5-Hannover | QGIS code revision | 58ba7c1ed6
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.2.1 | Running against GDAL/OGR | 3.2.1
Compiled against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | macOS 10.16
Active python plugins | oneclickrasterstacking; HeightmapExport; processing; db_manager; MetaSearch

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #42835

Also on raster calc:

- fix unreported issue with nodata float opencl
- papercut: set progress dialog window title

### CODE REVIEW

File: src/analysis/raster/qgsrastercalculator.cpp [hunk 1]
```diff
@@ -36,6 +36,41 @@
...
 #endif
 
+
+//
+// global callback function
+//
+int CPL_STDCALL GdalProgressCallback( double dfComplete,
+                                      const char *pszMessage,
+                                      void *pProgressArg )
+{
```
Comment (pblottiere) [inline src/analysis/raster/qgsrastercalculator.cpp:46]: I didn't find a lot of documentation about the `dfComplete` parameter in `GDALProgressFunc`. Can you enlighten me a little here please :)?

Comment (elpaso) [reply src/analysis/raster/qgsrastercalculator.cpp:46]: Sorry, I can't :) I just copy/pasted the implementation from https://github.com/qgis/QGIS/blob/master/src/core/providers/gdal/qgsgdalprovider.cpp#L103

Comment (pblottiere) [reply src/analysis/raster/qgsrastercalculator.cpp:46]: Ok :)

**Review by pblottiere — APPROVED** [review]
