### PR TITLE
Ensure quadrant segments are always at least 8 when doing offset curve

### LINKED ISSUE #53165: QGIS offset line shows perpendicular tags issue
### What is the bug or the crash?

I'm adding data to a road network using LRS. I am offsetting the data to show different lanes of the road. In the example below I only have data for 1 lane.

However, some of the data shows an additional perpendicular "tag" towards the original network line. At some scales the "tag" disappears if I change the dimension to "meters at scale". If there is data for multiple lanes, then the tag is showing for the data for each lane. I have checked the network line (using Vector > Geometry Tools > Extract Vertices) and there are no additional vertices which could be responsible for this.

I tried turning off the layer's rendering properties simplify geometry setting

I'm using 3.28.2 but it also occurs on 3.30.1. HOWEVER, I have just discovered that if I load the project into 3.18.3, then issue does not occur (see 2nd image).
Offset Data showing perpendicular lines
Offset Data showing perpendicular lines 3 18 3 no Tags

### Steps to reproduce the issue

1. Use LRS "events" to plot data onto a network line.
2. Set styling so that the data is offset to the left (negative offset) of the network line. (note. if a positive offset is used, the issue still occurs but at other locations along the line)

### Versions

Issue occurs on 3.28.2 and 3.30.1. 
HOWEVER, I have just discovered that if I load the project into 3.18.3, the issue does not occur

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by strk**
Works around a GEOS bug artifacts when using GEOS 3.11.{0,1,2}

Closes GH-53165

### CODE REVIEW

File: src/core/geometry/qgsgeos.cpp [hunk 1]
```diff
@@ -2421,6 +2421,9 @@ QgsAbstractGeometry *QgsGeos::offsetCurve( double distance, int segments, Qgis::
   geos::unique_ptr offset;
   try
   {
+    // Force quadrant segments to be at least 8, see
+    // https://github.com/qgis/QGIS/issues/53165#issuecomment-1563470832
+    if ( segments < 8 ) segments = 8;
```
Comment (nyalldawson) [inline src/core/geometry/qgsgeos.cpp:2426]:
```suggestion
    if ( segments < 8 )
      segments = 8;
```

**Review by nyalldawson — APPROVED** [review]

**Comment by agiudiceandrea** [comment]
The issue also occurs in QGIS 3.28. Shouldn't this fix be backported to the release-3_28 branch?

**Comment by strk** [comment]
@agiudiceandrea good idea, see #53308
