### PR TITLE
Close vertex for line when editing. fixes #32359 [needs-docs]

### LINKED ISSUE #32359: Impossible to draw a closed line as snap to first vertex is not working
Is impossible to draw a closed line (in one go) as even with snapping on, is not possible to snap to the first vertex. Line must be finished as not closed, then with the node tool the last vertex must be manually snapped to the first one.

### PR DESCRIPTION
**Pull request by lbartoletti**
## Description

This PR can be considered as a bugfix (by a workaround) or as a feature.

It is not possible to simply fix this problem, @troopa81 will be able to give the details.

However, as a draftsman, not being able to close a line is one of the most annoying things in QGIS. I suggest to close the line by pressing the "C" (close) key as proposed in many drawing tools to fix this problem.

I let you comment if for you it should be merged in master and backported to 3.10 if it's bugfix or not.

Thanks.

### CODE REVIEW

**Comment by troopa81** [comment]
> It is not possible to simply fix this problem, @troopa81 will be able to give the details.

The thing is that the snapping cache is updated only when a feature is added/removed. 

After a second thought, I'm not sure this is too complicated. Maybe, we could just connect `QgsVectorLayerEditBuffer::geometryChanged` to `QgsPointLocator::onGeometryChanged` and it will work. It's just an idea, I cannot confirm this will surely work.

File: src/gui/qgsmaptooldigitizefeature.cpp [hunk 1]
```diff
@@ -92,6 +92,40 @@ void QgsMapToolDigitizeFeature::setCheckGeometryType( bool checkGeometryType )
   mCheckGeometryType = checkGeometryType;
 }
 
+void QgsMapToolDigitizeFeature::keyPressEvent( QKeyEvent *e )
+{
+  QgsVectorLayer *vlayer = qobject_cast<QgsVectorLayer *>( mLayer );
```
Comment (nyalldawson) [inline src/gui/qgsmaptooldigitizefeature.cpp]: This whole block should be inside the `e->key() == Qt::Key_C` condition, and if the key isn't 'c' then you need to delegate to QgsMapToolCapture::keyPressEvent (or pressing escape/backspace will be broken)

File: src/gui/qgsmaptooldigitizefeature.cpp [hunk 2]
```diff
@@ -92,6 +92,40 @@ void QgsMapToolDigitizeFeature::setCheckGeometryType( bool checkGeometryType )
...
+    return;
+  }
+
+  if ( !vlayer->isEditable() )
+  {
+    notifyNotEditableLayer();
+    return;
+  }
+
+  if ( e && e->key() == Qt::Key_C && mode() == CaptureLine && vlayer->geometryType() == QgsWkbTypes::LineGeometry && mCheckGeometryType )
```
Comment (nyalldawson) [inline src/gui/qgsmaptooldigitizefeature.cpp]: shouldn't this include support for CapturePolygon mode? I realise that a right click will auto-close a polygon, but for consistency across the tools I think 'c' should also close and end polygon digitization.

**Review by nyalldawson — COMMENTED** [review]
Nice improvement. I'm +1 to classing this as a bug fix and merging for 3.12

File: src/gui/qgsmaptooldigitizefeature.cpp (hunk 1 above)
Comment (lbartoletti) [reply src/gui/qgsmaptooldigitizefeature.cpp]: Right. Done.

File: src/gui/qgsmaptooldigitizefeature.cpp (hunk 2 above)
Comment (lbartoletti) [reply src/gui/qgsmaptooldigitizefeature.cpp]: I hesitated, but indeed, it is consistent like that.

**Review by nyalldawson — APPROVED** [review]

**Comment by uclaros** [comment]
Hardcoding such a feature to a key is not a good idea. Isn't the key C already hardcoded to *construction mode* in advanced digitizing? This will break advanced digitizing! A better solution would be to close the line with a modifier to the right click pressed to end digitizing like Ctrl+right click, or enabling snapping to the digitized line as @troopa81 suggested, or both.
