### PR TITLE
Don't override atlas expression context when rendering map item overview frame as a temporary layer

### LINKED ISSUE #48963: Expressions doesn't have the atlas scope even if the expression builder shows the proper values.
### What is the bug or the crash?

 When trying to respond to https://gis.stackexchange.com/questions/433306/define-color-and-transparency-by-expression?noredirect=1#comment707002_433306

I noticed that there was a discrepancie between what is showed by the expression builder and the actual evaluation of the expression. I'm not sure if this was a one of or simply missing as it was deeped in the GUI but still in the layout.

### Steps to reproduce the issue

1. Make a layout with a map controlled by the atlas and a map with an overview
2. In the overview symbol, change the color parameter to use a field from the atlas layer
3. Cycle through the atlas features and to see issues with the overlay symbol

### Versions

Tested on 3.22.1 on win 10 but I'm pretty sure the issue is still present in current versions. 

Will test with a more recent master later this week.

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nyalldawson**
Fixes https://github.com/qgis/QGIS/issues/48963

### CODE REVIEW

File: src/core/layout/qgslayoutitemmapoverview.cpp [hunk 1]
```diff
@@ -478,6 +478,8 @@ QList<QgsMapLayer *> QgsLayoutItemMapOverviewStack::modifyMapLayerList( const QL
     if ( !l )
       continue;
 
+    l->setCustomProperty( QStringLiteral( "_noset_layer_expression_context" ), true );
```
Comment (nirvn) [inline src/core/layout/qgslayoutitemmapoverview.cpp:481]: I guess the chances of somebody ever using this exact property name is super low to begin with :)

**Review by nirvn — APPROVED** [review]

File: src/core/layout/qgslayoutitemmapoverview.cpp (hunk 1 above)
Comment (nyalldawson) [reply src/core/layout/qgslayoutitemmapoverview.cpp:481]: heh. Elsewhere we use '_' prefix for internal keys like this too -- I think that's a fair enough convention to stick with :)

**Comment by roya0045** [comment]
Thank you Nyall, this is appreciated!
