### PR TITLE
Accept also "true" for queryable/opaque/noSubsets attributes

### LINKED ISSUE #45591: WMS service 1.3.0 layer queryable attribute parsing should accept `true/false` values
### What is the bug or the crash?

We've found that some of the services returns ie this in GetCapabilities layer properties:

```XML
<Layer queryable="true">
  <Name>ED5D8D3A</Name>
  <Title>Ulice</Title>
  <MinScaleDenominator>101</MinScaleDenominator>
  <MaxScaleDenominator>25001</MaxScaleDenominator>
</Layer>
```

But then identification tool is not enabled and it seems that it's due to [this](https://github.com/qgis/QGIS/blob/89a4f0b94cc03489aa14d603b061db84826bf928/src/providers/wms/qgswmscapabilities.cpp#L1108) line.

According to WMS 1.3.0 attribute is of type [xsd:boolean](https://www.w3.org/TR/xmlschema-2/#boolean) so it should accept `0`/`1`/`true`/`false`.

Same is in 'Table 6 - Layer attributes' in cl. 7.2.4.7.1 of "OpenGIS® Web Map Server Implementation Specification"

| attribute | allowed values | meaning |
|-------------|----------------------|-------------|
| queryable | 0, false, 1, true | 0, false: layer is not queryable.
| | | 1, true: layer is queryable. |

### Steps to reproduce the issue

* Add WMS 1.3.0 layer that marks queryable layers with `queryable="true"` instead of `queryable="1"`
* Try to use identification tool in it

### Versions

QGis 3.18.3 but it doesn't matter much as the relevant code is still used as linked in description.

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pathmapper**
Fixes #45591 and same issue for `opaque`/`noSubsets` attributes.

### CODE REVIEW

File: src/providers/wms/qgswmscapabilities.cpp [hunk 1]
```diff
@@ -1105,10 +1105,18 @@ void QgsWmsCapabilities::parseLayer( const QDomElement &element, QgsWmsLayerProp
 #endif
 
   layerProperty.orderId     = ++mLayerCount;
-  layerProperty.queryable   = element.attribute( QStringLiteral( "queryable" ) ).toUInt();
+
+  QString queryableAttribute = element.attribute( QStringLiteral( "queryable" ) );
+  layerProperty.queryable = ( queryableAttribute == QLatin1String( "1" ) || queryableAttribute == QLatin1String( "true" ) );
```
Comment (nyalldawson) [inline src/providers/wms/qgswmscapabilities.cpp:1110]:
```suggestion
  layerProperty.queryable = queryableAttribute == QLatin1String( "1" ) || queryableAttribute.compare( QLatin1String( "true" ), Qt::CaseInsensitive ) == 0;
```

... just in case! :wink:

File: src/providers/wms/qgswmscapabilities.cpp [hunk 2]
```diff
@@ -1105,10 +1105,18 @@ void QgsWmsCapabilities::parseLayer( const QDomElement &element, QgsWmsLayerProp
...
+
   layerProperty.cascaded    = element.attribute( QStringLiteral( "cascaded" ) ).toUInt();
-  layerProperty.opaque      = element.attribute( QStringLiteral( "opaque" ) ).toUInt();
-  layerProperty.noSubsets   = element.attribute( QStringLiteral( "noSubsets" ) ).toUInt();
+
+  QString opaqueAttribute = element.attribute( QStringLiteral( "opaque" ) );
+  layerProperty.opaque = ( opaqueAttribute == QLatin1String( "1" ) || opaqueAttribute == QLatin1String( "true" ) );
```
Comment (nyalldawson) [inline src/providers/wms/qgswmscapabilities.cpp:1115]:
```suggestion
  layerProperty.opaque = opaqueAttribute == QLatin1String( "1" ) || opaqueAttribute.compare( QLatin1String( "true" ), Qt::CaseInsensitive ) == 0;
```

File: src/providers/wms/qgswmscapabilities.cpp [hunk 3]
```diff
@@ -1105,10 +1105,18 @@ void QgsWmsCapabilities::parseLayer( const QDomElement &element, QgsWmsLayerProp
...
+
+  QString noSubsetsAttribute = element.attribute( QStringLiteral( "noSubsets" ) );
+  layerProperty.noSubsets = ( noSubsetsAttribute == QLatin1String( "1" ) || noSubsetsAttribute == QLatin1String( "true" ) );
```
Comment (nyalldawson) [inline src/providers/wms/qgswmscapabilities.cpp:1118]:
```suggestion
  layerProperty.noSubsets = noSubsetsAttribute == QLatin1String( "1" ) || noSubsetsAttribute.compare( QLatin1String( "true" ), Qt::CaseInsensitive ) == 0;
```

**Review by nyalldawson — APPROVED** [review]

File: src/providers/wms/qgswmscapabilities.cpp (hunk 1 above)
Comment (pathmapper) [reply src/providers/wms/qgswmscapabilities.cpp]: :+1:
