### PR TITLE
[attributetable] Fix "Move selection to top" for 3.x regression fixes #15803

### LINKED ISSUE #15803: Preview in expression builder not always showing
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [6616](https://issues.qgis.org/issues/6616)
Affected QGIS version: 3.0.0
Redmine category:gui

---
The preview in the field calculator expression builder is often missing. This happens because the expression text is evaluated against the first feature in the layer. If the expression doesn't evaluate for the first feature there will be no text. 

Thanks Nathan for the explanation.

### PR DESCRIPTION
**Pull request by luipir**
fix for https://hub.qgis.org/issues/15803
port to 3.0 for PR https://github.com/qgis/QGIS/pull/4306

## Description
Fix "Move selection to top" in attribute table. The origin of the problem is due the fact that sortOrder is undefined enetring in selectionOnTop. I wasn't able to find why it is undefined albeit the base class constructor set it as Ascending. 

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by elpaso** [comment]
I cannot reproduce this on current master.

**Comment by gioman** [comment]
confirmed, on master seems ok (now?).

**Comment by luipir** [comment]
I can confirm that SortOnTop wasn't working with master 29dd519, now updating master and check what commit can influence sorting and check if it make sense a backport for a more general solution

**Comment by luipir** [comment]
still having the same issue with recently build master bfb62c4. Trying a build from scratch to avoid local effect

**Comment by luipir** [comment]
confirmed with a clean build! I've the issue on master. Could depend on some setting or previous order step executed before to check the issue?

**Comment by luipir** [comment]
the problem remained also running qgis with --configpath /tmp/ --configpath /tmp/

**Comment by luipir** [comment]
discovered that the problem is still available on master if the layer has been loaded from a project with wrong setting values:
The proposed patch force the sortOrder value to be in the correct range value eg:
- Qt::AscendingOrder = 0
- QtDescendingOrder = 1
but the default value is loaded from the project in the tag:
<attributetableconfig ... sortOrder="<value>" >
that is loaded through code:
https://github.com/qgis/QGIS/blob/master/src/core/qgsattributetableconfig.cpp#L200

if for some reason (and seems many project can be affected) the value is not 0 or 1 => the sortOrder is skipped during sort => not applied

**Comment by luipir** [comment]
@nyalldawson any idea if I've to leave https://github.com/qgis/QGIS/blob/master/src/core/qgsattributetableconfig.cpp#L200 as is or to strictly cast it to enum values?

**Comment by nyalldawson** [comment]
@luipir I think you mean @m-kuhn 
https://github.com/qgis/QGIS/commit/b83aab7d74be273724f94e2a734eb7b6397cb9a6
My commit was just general string optimisations. 

https://github.com/blog/2304-navigate-file-history-faster-with-improved-blame-view is really handy for tracking down stuff like this

**Comment by luipir** [comment]
tnx @nyalldawson sorry I posted a request to you also on dev list.

File: src/core/qgsattributetableconfig.cpp [hunk 1]
```diff
@@ -198,6 +198,14 @@ void QgsAttributeTableConfig::readXml( const QDomNode &node )
 
   mSortExpression = configNode.toElement().attribute( QStringLiteral( "sortExpression" ) );
   mSortOrder = static_cast<Qt::SortOrder>( configNode.toElement().attribute( QStringLiteral( "sortOrder" ) ).toInt() );
+  switch ( mSortOrder )
```
Comment (m-kuhn) [inline src/core/qgsattributetableconfig.cpp]: I'd simply write the following. Same effect, easier to read and shorter :)

    if ( mSortOrder != Qt::AscendingOrder && mSortOrder != Qt::DescendingOrder )

File: src/gui/attributetable/qgsattributetablefiltermodel.cpp [hunk 2]
```diff
@@ -226,11 +226,18 @@ void QgsAttributeTableFilterModel::setSelectedOnTop( bool selectedOnTop )
...
   {
     mSelectedOnTop = selectedOnTop;
+    int column = sortColumn();
+    Qt::SortOrder order = sortOrder();
 
-    if ( sortColumn() == -1 )
-    {
-      sort( 0 );
-    }
+    // set default sort values if they are not correctly set
```
Comment (m-kuhn) [inline src/gui/attributetable/qgsattributetablefiltermodel.cpp]: Is this the right place to deal with this?
If this is sometimes setup the wrong way, it's probably not only sortOnTop that suffers from this?

File: src/core/qgsattributetableconfig.cpp (hunk 1 above)
Comment (luipir) [inline src/core/qgsattributetableconfig.cpp]: ok, was just a way to simplify  in case to add new enum values... but it s a improbable case.

File: src/gui/attributetable/qgsattributetablefiltermodel.cpp (hunk 2 above)
Comment (luipir) [inline src/gui/attributetable/qgsattributetablefiltermodel.cpp]: I agree

Comment (luipir) [inline src/gui/attributetable/qgsattributetablefiltermodel.cpp]: I leaved there to have more control on input data, as we saw that this methods can be called outside the qgis workflow (eg. in plugins).
E.g. in may part of QgsComposerAttributeTableModel the setSortOrder is set passing a value (EditRole) duing static_cast. That part of code it's not related with this one, but can explain how a user or qgis dev can wrongly setup sortOrder
Btw I'll move the input value control to QgsAttributeTableConfig::setSortOrder.

**Comment by luipir** [comment]
@m-kuhn leaved input control and added value check in QgsAttributeTableConfig

File: src/core/qgsattributetableconfig.cpp [hunk 3]
```diff
@@ -198,6 +198,12 @@ void QgsAttributeTableConfig::readXml( const QDomNode &node )
 
   mSortExpression = configNode.toElement().attribute( QStringLiteral( "sortExpression" ) );
   mSortOrder = static_cast<Qt::SortOrder>( configNode.toElement().attribute( QStringLiteral( "sortOrder" ) ).toInt() );
+  // fix https://hub.qgis.org/issues/15803
+  // because static_cast give umpredictable value if value is not in the enum range
+  if ( mSortOrder != Qt::AscendingOrder && mSortOrder != Qt::DescendingOrder )
+  {
+    mSortOrder = Qt::AscendingOrder;
+  }
```
Comment (m-kuhn) [inline src/core/qgsattributetableconfig.cpp]: Maybe just call setSortOrder here to have the handling in one place?

File: src/core/qgsattributetableconfig.cpp [hunk 4]
```diff
@@ -242,6 +248,12 @@ Qt::SortOrder QgsAttributeTableConfig::sortOrder() const
 
 void QgsAttributeTableConfig::setSortOrder( Qt::SortOrder sortOrder )
 {
+  // fix https://hub.qgis.org/issues/15803
+  if ( sortOrder != Qt::AscendingOrder && sortOrder != Qt::DescendingOrder )
```
Comment (m-kuhn) [inline src/core/qgsattributetableconfig.cpp]: If an invalid value is specified, does it make more sense to force the value to ascending or to keep the current one?

i.e. what do you think about

```
if ( sortOrder != Qt::AscendingOrder && sortOrder != Qt::DescendingOrder )
    return;
```

**Comment by m-kuhn** [comment]
It looks good to me in general.

Sorry for nitpicking, please tell me if you dislike the inputs, it's really no big deal.

File: src/core/qgsattributetableconfig.cpp (hunk 3 above)
Comment (luipir) [inline src/core/qgsattributetableconfig.cpp]: good catch

File: src/core/qgsattributetableconfig.cpp (hunk 4 above)
Comment (luipir) [inline src/core/qgsattributetableconfig.cpp]: ok

Comment (luipir) [inline src/core/qgsattributetableconfig.cpp]: I would log this anomalies... but I didn't because seems there is a general behavior to leave container classes silent. IMHO reading a wrong value from the project would be notified, at list in the log. What do you think @m-kuhn ?

**Comment by luipir** [comment]
osx processing tests fails I suppose due to some pythonpath travis configuration problems

**Comment by luipir** [comment]
osx processing tests fails I suppose due to some pythonpath travis configuration problems
