### PR TITLE
[Fix] Remove unnecessary geometryChanged calls

### LINKED ISSUE #47595: Vertex tool triggers layer.geometryChanged three times
### What is the bug or the crash?

Any edit done with the vertex tool causes the underlying vector layer to emit the `geometryChanged` signal three times instead of one.
@lbartoletti could be related to  #44198 since it is also caused by your changes in #41658

### Steps to reproduce the issue

1. add a vector layer
2. connect its `geometryChanged` signal to some function
3. use the vertex tool to edit a single vertex
4. the function is called three times (instead of one)

### Versions

bcdb670, all versions since #41658

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Koyaani**
## Description

Before this PR, when a vertex is modified, `layer.geometryChanged` has been call three times.

With this PR, when "avoid intersections" does nothing (either it is disable or no geometry intersect the edited geometry), there is only one emitted `geometryChanged` signal. And when  "avoid intersections" modifies the geometry, 2 `geometryChanged` signal is emitted.

The reasons to keep 2 signals when "avoid intersections" modifies the geometry are:
 - Keep the ability to redo only the "avoid intersections" modifications.
 - The "avoid intersections" process can transform the geometry to an invalid one. A plugin can go back  before the "avoid intersections" modifications.

Fixes #47595

Founded by: Métropole Européenne de Lille, cc @Jean-Roc

### CODE REVIEW

**Comment by uclaros** [comment]
I'm not sure about this one... I mean, two signals is definitely better than three, still I would expect one user action to generate a single geometryChanged signal with a single undo stack entry.

I know *Avoid Intersections* is a tricky beast that can mess your data in no time and I see the need for some measures to prevent that. My suggestion would be to introduce a new signal that fires when avoid intersections has modified a geometry, passing both the modified and unmodified geometries as a parameters. We could then display a warning with an oops button to revert the change of let plugins handle that.

For me it's also crucial to have all tools that implement avoid intersections behave in the same way so create feature/paste/not sure what else, should have the same signals and undo steps.

**Comment by Koyaani** [comment]
@uclaros on rechecking, I realized that my assertion about "you could revert only changes made by the `avoidIntersection` tool" is wrong. We can undo the modifications made by topological editing, but not separately the `moveVertex` action and the `avoidIntersection` action.

There were some discussions made, no simple solution emerged without the need to break everything. I'm not a fan of creating a new signal and creating a new button, we need to keep the process simple for the user. Furthermore, topological editing emits signals and adds an entry in the undo stack. I see some kind of continuity in this.

There would be a solution to emit only one signal. When there are two, block the first one. However, I am really afraid of side effects and breaking user scripts.

If you have an idea (that doesn't involve adding too much new stuff), I can try it!

**Comment by uclaros** [comment]
Hey @Koyaani , sorry for the late reply.

I consider the topological points entries in the undo stack a bug. The entries have no name in the undo/redo panel and there can be lots of entries for a single action, one for each topological point that was added. They are confusing to the user who just wants to undo his last action and keeps pressing undo until it eventually happens after going through the invisible changes of the topo points. Imho, this should be fixed and definitely not be used as a guide for the avoid overlaps logic!

The way I see it is that when the user performs an action (add/modify feature) the following should happen:
1. decide what the final geometries will be after applying overlap avoidance
2. fire a signal if geom was modified by overlap avoidance. QGIS will only use this to show a warning to the user so that he is aware that his geom is no longer what he has digitized, but a plugin could potentially use this signal to revert this.
3. decide what are the candidate vertices for topo points
4. add the final geometry/apply the changes to the modified geometries, fire one vlayer.featureAdded / vlayer.geometryChanged
5. add topo points to same layer, fire one vlayer.geometryChanged for each modified feature, group those edits in the undo buffer with the one from previous step
6. add topo points to the other editable layers, firing one vlayer.geometryChanged for each modified feature, 
7. now the user should be able to completely undo his last action with a single undo step on each of the modified layers
(ideally, there should be a mechanism to link undo entries across layers so that changes from all other layers could be undone when undoing the master user action, but that is too far fetched)

With your current two signal approach there is no way to know that one of them was caused by avoid overlaps so a plugin cannot use it to revert the change as you suggest.
Your proposed solution to block the signals and fire a single geometryChanged at the end could work. I wouldn't worry too much about breaking user scripts as the current 3 signal functionality is a regression bug introduced last year.

I hope some of the above make sense!

**Comment by Koyaani** [comment]
@uclaros There are a lot of things that need to be changed in digitizing to make it clearer for developers and users, I totally agree with you. Refactoring according to your proposal would require a lot of time that I don't have.

For blocking the signal, I can't anticipate the side effects. This signal can be used in many places, I prefer not to do that. 

In your opinion, does this PR improve the situation (even partially)? Or is it useless, or even worse? If you want we leave the issue open by indicating that this PR is only a partial fix (only 1 signal if `avoidIntersection` doesn't change anything, 2 if it changes a geometry). And someone (when he can) will completely correct this issue.

File: src/app/vertextool/qgsvertextool.cpp [hunk 1]
```diff
@@ -2416,12 +2413,19 @@ void QgsVertexTool::applyEditsToLayers( QgsVertexTool::VertexEdits &edits )
           case 3:
             emit messageEmitted( tr( "At least one geometry intersected is invalid. These geometries must be manually repaired." ), Qgis::MessageLevel::Warning );
             break;
+
           default:
             break;
         }
+        // if the geometry has been changed
+        if ( avoidIntersectionsReturn != 4 )
```
Comment (troopa81) [inline src/app/vertextool/qgsvertextool.cpp:2421]:
```suggestion
        if ( avoidIntersectionsReturn != 1 && avoidIntersectionsReturn != 4)
```

File: src/core/geometry/qgsgeometryeditutils.cpp [hunk 2]
```diff
@@ -343,6 +343,10 @@ std::unique_ptr<QgsAbstractGeometry> QgsGeometryEditUtils::avoidIntersections( c
   }
 
   std::unique_ptr< QgsAbstractGeometry > diffGeom( geomEngine->difference( combinedGeometries.get() ) );
+  if ( geomEngine->isEqual( diffGeom.get() ) )
```
Comment (troopa81) [inline src/core/geometry/qgsgeometryeditutils.cpp:346]: Can we not doing this test in QgsGeometry::avoidIntersections to avoid changing API of this method (one can expect to have a non-null feature even if there were no modification on the geometry)

**Review by troopa81 — CHANGES_REQUESTED** [review]
I'm ok about the overall content of this PR. 

I'm ok with adding a new return code in the QgsGeometry::avoidIntersection. IMHO it doesn't break the API because it was already broken, meaning that we state we return 3 when there is invalid geometry while it returns 4 actually.

File: src/core/geometry/qgsgeometryeditutils.cpp (hunk 2 above)
Comment (troopa81) [reply src/core/geometry/qgsgeometryeditutils.cpp]: Sorry, but could you revert this? I didn't see that actually the file is not part of the python API and it's a shame to recreate a geomEngine just to do this operation while we have it in the QgsGeometryEditUtils method.

Could you comment the returned geom in the method documentation to say when a nullptr is returned?

**Review by troopa81 — APPROVED** [review]

**Comment by uclaros** [comment]
> In your opinion, does this PR improve the situation (even partially)? Or is it useless, or even worse?

It does indeed improve the situation, as I already mentioned 2 signals is better than 3! :)
Only thing that worries me is that this is a partial fix, even if it is a sponsored fix for a regression introduced by a sponsored feature, so I'm not sure who would properly fix it after all.

Let's keep the bug report open with a description of the new behavior.

**Comment by Jean-Roc** [comment]
@uclaros I'm keeping your proposal in mind and will contribute toward it if we have enough budget left or in our potential next year funding.
