### PR TITLE
Fix save style api, crash when saving styles

### LINKED ISSUE #46914: New extract labels algorithm crashes under windows
### What is the bug or the crash?

When using the extract labels algorithm it crashes under windows

### Steps to reproduce the issue

1. Open the project saved in the attached GPKG
2. Use the extract labels algorithm using all the defaults and mapcanvas
3. Crash happens

Sample GPKG

[bze_labels.zip](https://github.com/qgis/QGIS/files/7906018/bze_labels.zip)

Video of the situation

https://user-images.githubusercontent.com/4627073/150359209-99712506-2384-488a-a2ea-f924e7f53cea.mp4

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x0000307c (most recent call first):
  File "C:\OSGeo4W/apps/qgis-dev/./python/plugins\processing\ProcessingPlugin.py", line 395 in executeAlgorithm
    dlg.exec_()
  File "C:\OSGeo4W/apps/qgis-dev/./python/plugins\processing\gui\ProcessingToolbox.py", line 234 in executeAlgorithm
    self.executeWithGui.emit(alg.id(), self, self.in_place_mode, False)
```

**Stack Trace**
No stack trace is available.

**QGIS Info**
QGIS Version: 3.23.0-Master
QGIS code revision: c5a56d6f83
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22533

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Not using a supported version on purpose

### LINKED ISSUE #46954: Save layer style API is not thread safe
### What is the bug or the crash?

This API has code in the providers which checks whether a style already exists and shows a messagebox if it does. This results in crashes when the api is used on non-main threads, e.g. https://github.com/qgis/QGIS/issues/46914

### Steps to reproduce the issue

...

### Versions

all

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nyalldawson**
This PR reworks the API for saving styles to database to remove the unsafe use of widgets (a confirmation QMessageBox) from the provider code. This was shown when a matching style already exists in the database, and causes a crash if this method is ever called from a non-main thread.

Now determining if a matching style already exists is a separate method, and the messagebox questions are only present in the client (app) code. 

Fixes #46954
Fixes #46914

### CODE REVIEW

File: src/app/qgisapp.cpp [hunk 1]
```diff
@@ -9192,6 +9192,22 @@ void QgisApp::saveStyleFile( QgsMapLayer *layer )
 
             QgsVectorLayerSaveStyleDialog::SaveToDbSettings dbSettings = dlg.saveToDbSettings();
 
+            QString errorMessage;
+            if ( QgsProviderRegistry::instance()->styleExists( vlayer->providerType(), vlayer->source(), dbSettings.name, errorMessage ) )
+            {
+              if ( QMessageBox::question( nullptr, QObject::tr( "Save style in database" ),
```
Comment (nirvn) [inline src/app/qgisapp.cpp:9198]: You could get rid of QObject::tr() in favor of tr() here. I think it'll also result in better classification of the string to translate in transifex et cie.

File: src/gui/qgsmaplayerstylemanagerwidget.cpp [hunk 2]
```diff
@@ -210,12 +211,31 @@ void QgsMapLayerStyleManagerWidget::saveAsDefault()
         case 0:
           return;
         case 2:
+        {
+          QString errorMessage;
+          if ( QgsProviderRegistry::instance()->styleExists( layer->providerType(), layer->source(), QString(), errorMessage ) )
+          {
+            if ( QMessageBox::question( nullptr, QObject::tr( "Save style in database" ),
```
Comment (nirvn) [inline src/gui/qgsmaplayerstylemanagerwidget.cpp:218]: Same as previous comment QObject::tr() -> tr()

File: src/providers/postgres/qgspostgresprovider.cpp [hunk 3]
```diff
@@ -4883,7 +4882,7 @@ QString QgsPostgresProvider::getNextString( const QString &txt, int &i, const QS
     }
     i += match.captured( 1 ).length() + 2;
     jumpSpace( txt, i );
-    if ( !QStringView{txt}.mid( i ).startsWith( sep ) && i < txt.length() )
+    if ( !QStringView{txt} .mid( i ).startsWith( sep ) && i < txt.length() )
```
Comment (nirvn) [inline src/providers/postgres/qgspostgresprovider.cpp:4885]: That extra space is out of auto-formatting or a mistake? It shows up in a couple of places here.

**Review by nirvn — APPROVED** [review]
Nice, glad you're able to address this prior to 3.24 release. Just a couple of suggestions here and there.
