### PR TITLE
[Elevation profile] Add ability to render point cloud data as continuous elevation line  

### LINKED ISSUE #64761: Elevation profile shows no results for Virtual Point Clouds if no points are fetched from any single sub index
### What is the bug or the crash?

Current logic in point cloud profile generator for VPCs queries the sub indexes that intersect the bounding box of the drawn profile curve.

However, while iterating the indexes, if we reach an index that is covered by the curve's bounding box but not the actual curve itself, the code returns early and shows no results as it gets no nodes from it. So, if we fail to get any points from an index, we scrap all the other points as well and return an empty profile.

(iteration starts at line 514)
https://github.com/qgis/QGIS/blob/de30659865a24d0855eed8850675ab0181ee19c0/src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp#L541

Here is an example curve that covers 3 sub indexes, but its extent covers all 4.

Image

### Steps to reproduce the issue

1.) Load a multi tile VPC.
2.) Draw a curve that intersects several tiles, but its bounding box (extent) covers additional tile(s).
3.) Notice no results in the elevation profile.

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.99.0-Master</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/dbec9d148e8">dbec9d148e8</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>6.10.1</td></tr><tr><td>Python version</td><td>3.14.2</td></tr><tr><td>GDAL version</td><td>3.11.5 — <i>Eganville</i></td></tr><tr><td>PROJ version</td><td>9.6.2</td></tr><tr><td>EPSG Registry database version</td><td>v12.013 (2025-05-26)</td></tr><tr><td>GEOS version</td><td>3.14.1-CAPI-1.20.5</td></tr><tr><td>SFCGAL version</td><td>No support</td></tr><tr><td>GeographicLib version</td><td>No support</td></tr><tr><td>SQLite version</td><td>3.50.2</td></tr><tr><td>PDAL version</td><td>2.9.3</td></tr><tr><td>PostgreSQL client version</td><td>18.1</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.2.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Fedora Linux 43 (KDE Plasma Desktop Edition)</td></tr><tr><td colspan="2"><i>This copy of QGIS writes debugging output.</i></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>processing</td><td>2.12.99</td></tr><tr><td>qgis-layer-tree-tools</td><td>1.4.0</td></tr></table>

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ViperMiniQ**
This PR adds the ability for the elevation profile of a point cloud layer to display a continuous elevation line (like vector or raster layers) instead of individual points.

Z values for the elevation line are derived from triangles - Delaunay triangulation is performed on the points within the selection zone (selection curve + tolerance buffer), and Z values are interpolated from the triangles that intersect the midpoint of the selection curve.

An option to extract the height from the triangulated surface has been added to the Elevation section of the layer properties. Here, users can choose to extract elevation data either directly from individual point cloud points or from the triangulated surface. 
The quality of the elevation line depends on the user’s selection: if a small number of points is included (for example, when a low tolerance setting is used), the resulting triangles may be of low quality and thus the elevation line won’t be as good. Users can adjust the tolerance setting to improve results. Triangulating the whole layer, especially considering the size of some datasets, can be too much, so this was chosen for the method.

The file delaunator.hpp had to be modified to make all functions inline - otherwise, the linker would complain. Is modifying 3rd party library acceptable, or would it be better to create a wrapper instead?

When experimenting with the elevation profile, you can configure a layer to use all or a subset of points within the selection zone (adjusted in symbology). 

You can also duplicate the layer, apply different symbology to it, and set it to render a subset of points. For example, it’s possible to use the same dataset twice in the elevation profile—one layer displaying all attributes and another showing only ground points. Doing that, you end up with something that looks like this:

Screenshot_20260204_123700

Screenshot_20260204_123931

Edit: fixes #64761

### CODE REVIEW

File: src/core/pointcloud/qgspointcloudlayerelevationproperties.h [hunk 1]
```diff
@@ -207,17 +211,174 @@ class CORE_EXPORT QgsPointCloudLayerElevationProperties : public QgsMapLayerElev
      */
     void setRespectLayerColors( bool enabled );
 
+    /**
+     * Sets the profile \a type used when generating elevation profile plots.
+     *
+     * \see renderType()
+     * \since QGIS 4.0
+     */
+    void setRenderType( Qgis::PointCloudProfileType type ) { mRenderType = type; }
```
Comment (wonder-sk) [inline src/core/pointcloud/qgspointcloudlayerelevationproperties.h]: For consistency, I would suggest to rename to setType() + type() + mType as `QgsVectorLayerElevationProperties` uses that naming for the same thing...

File: src/core/pointcloud/qgspointcloudlayerelevationproperties.h [hunk 2]
```diff
@@ -207,17 +211,174 @@ class CORE_EXPORT QgsPointCloudLayerElevationProperties : public QgsMapLayerElev
...
+     * Returns the profile type used when generating elevation profile plots.
+     *
+     * \see setRenderType()
+     * \since QGIS 4.0
+     */
+    Qgis::PointCloudProfileType renderType() const { return mRenderType; }
+
+    /**
+     * Returns the symbol used to render lines for the layer in elevation profile plots.
+     *
```
Comment (wonder-sk) [inline src/core/pointcloud/qgspointcloudlayerelevationproperties.h:232]: worth adding here a note this is only valid for triangulated surface + when profileSymbology() is Line.

Similarly for all the other added getters/setters that depend on triangulated surface and type of profileSymbology()

File: src/core/pointcloud/qgspointcloudlayerelevationproperties.h [hunk 3]
```diff
@@ -207,17 +211,174 @@ class CORE_EXPORT QgsPointCloudLayerElevationProperties : public QgsMapLayerElev
...
+
+    /**
+     * Returns the symbol used to render points for the layer in elevation profile plots.
+     *
+     * \note This setting is only used when type() is Qgis::PointCloudProfileType::TriangulatedSurface.
+     *
+     * \see setProfileMarkerSymbol()
+     * \since QGIS 4.0
+     */
+    QgsMarkerSymbol *profileMarkerSymbol() const;
```
Comment (wonder-sk) [inline src/core/pointcloud/qgspointcloudlayerelevationproperties.h]: I wonder if it makes sense at all to have support for marker symbols when using triangulated surface...?

File: src/core/pointcloud/qgspointcloudlayerelevationproperties.cpp [hunk 4]
```diff
@@ -105,8 +260,13 @@ QgsPointCloudLayerElevationProperties *QgsPointCloudLayerElevationProperties::cl
   res->mPointSymbol = mPointSymbol;
   res->mPointColor = mPointColor;
   res->mRespectLayerColors = mRespectLayerColors;
+  res->mRenderType = mRenderType;
```
Comment (wonder-sk) [inline src/core/pointcloud/qgspointcloudlayerelevationproperties.cpp]: it seems some member variables are not being copied (e.g. mSymbology, mElevationLimit)

File: src/core/pointcloud/qgspointcloudlayerelevationproperties.cpp [hunk 5]
```diff
@@ -58,6 +172,22 @@ QDomElement QgsPointCloudLayerElevationProperties::writeXml( QDomElement &parent
   element.setAttribute( u"point_color"_s, QgsColorUtils::colorToString( mPointColor ) );
   element.setAttribute( u"respect_layer_colors"_s, mRespectLayerColors ? u"1"_s : u"0"_s );
   element.setAttribute( u"opacity_by_distance"_s, mApplyOpacityByDistanceEffect ? u"1"_s : u"0"_s );
+  element.setAttribute( u"render_type"_s, qgsEnumValueToKey( mRenderType ) );
```
Comment (wonder-sk) [inline src/core/pointcloud/qgspointcloudlayerelevationproperties.cpp]: it seems mSymbology is not being written to and read from xml

File: src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp [hunk 6]
```diff
@@ -794,4 +799,574 @@ void QgsPointCloudLayerProfileGenerator::visitBlock( const QgsPointCloudBlock *b
...
+  }
+  else
+  {
+    mPreparedRendererData.reset();
+  }
+
+  request.setAttributes( attributes );
+
+  mResults = std::make_unique< QgsTriangulatedPointCloudLayerProfileResults >();
+  mResults->copyPropertiesFromGenerator( this );  // TODO: this fails because mLineSymbol doesn't exist in the generator, uncomment when you fix this
```
Comment (wonder-sk) [inline src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp]: unresolved TODO?

File: src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp [hunk 7]
```diff
@@ -794,4 +799,574 @@ void QgsPointCloudLayerProfileGenerator::visitBlock( const QgsPointCloudBlock *b
...
+
+  if ( mGatheredPoints.size() < 3 )
+  {
+    mResults = nullptr;
+    return false;
+  }
+
+  std::unique_ptr<delaunator::Delaunator> triangulator;
+  std::vector<double> vertices;
+  std::vector<double> zValues;
```
Comment (wonder-sk) [inline src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp:960]: it is a good practice to reserve capacity in `vertices` and `zValues` arrays when we know the expected size in advance, to avoid needless reallocations of arrays as they grow

File: src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp [hunk 8]
```diff
@@ -794,4 +799,574 @@ void QgsPointCloudLayerProfileGenerator::visitBlock( const QgsPointCloudBlock *b
...
+
+  for ( QgsPoint point : mGatheredPoints )
+  {
+    vertices.push_back( point.x() );
+    vertices.push_back( -point.y() ); // flipping y to have correctly oriented triangles from delaunator
```
Comment (wonder-sk) [inline src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp]: flipping y here, but then we're flipping y again in the for loop below? can't we skip both?

File: src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp [hunk 9]
```diff
@@ -794,4 +799,574 @@ void QgsPointCloudLayerProfileGenerator::visitBlock( const QgsPointCloudBlock *b
...
+    const QgsTriangle triangle( pt0, pt1, pt2 );
+
+    QgsGeos geosPoly( &triangle );
+    geosPoly.prepareGeometry();
+
+    std::unique_ptr<QgsAbstractGeometry> intersectingGeom( geosPoly.intersection( sourceCurve ) );
+    if ( !intersectingGeom )
+      continue;
+
+    // probably not needed, but we may end up with something else, better to check
```
Comment (wonder-sk) [inline src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp:996]: this check is certainly needed... we could end up with a point, or multi-linestring, multi-point, even a geometry collection 😄

File: src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp [hunk 10]
```diff
@@ -794,4 +799,574 @@ void QgsPointCloudLayerProfileGenerator::visitBlock( const QgsPointCloudBlock *b
...
+        catch ( QgsCsException & )
+        {
+          continue;
+        }
+      }
+
+      mGatheredPoints.append( res );
+    }
+  }
+}
```
Comment (wonder-sk) [inline src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp:904]: I think we have a problem with code duplication here - it's 300-400 lines of code that's the same for both point cloud profile generators.

My suggestion:

- introduce "base" point cloud generator that will have a function (e.g. collectData()) with all the common functionality to traverse the point cloud data within a tolerance of a curve, and will have a pure virtual function visitBlock() to process a block. The base class will also have many members that are the same for both derived profile generators. (We would not use QgsAbstractProfileSurfaceGenerator as base class for triangulated surface option anymore)
- then, derived classes for "individual points" and "triangulated surface" will have simplified generateProfile() implementation: it will call collectData() from the base class and using their own visitBlock() implementation, they will store whatever is needed for the profile results.

File: src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp [hunk 11]
```diff
@@ -794,4 +799,574 @@ void QgsPointCloudLayerProfileGenerator::visitBlock( const QgsPointCloudBlock *b
...
+
+  for ( auto pointIt = mDistanceToHeightMap.constBegin(); pointIt != mDistanceToHeightMap.constEnd(); ++pointIt )
+  {
+    if ( std::isnan( pointIt.value() ) )
+      continue;
+
+    mMarkerSymbol->renderPoint( context.worldTransform().map( QPointF( pointIt.key(), pointIt.value() ) ), nullptr, context.renderContext() );
+  }
+  mMarkerSymbol->stopRender( context.renderContext() );
+}
```
Comment (wonder-sk) [inline src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp:1090]: I think we should not support markers for the triangulated surface of point clouds, because those points which would be marked are simply some points at the edges of triangles of the triangulation. I would suggest to remove `mShowMarkerSymbolInSurfacePlots` and `mMarkerSymbol` altogether

**Review by wonder-sk — COMMENTED** [review]
There are some minor GUI issues:
- initially when the elevation properties get open with traingulated surface:
  - when using line symbology -> GUI also shows fill marker, limit
  - when using fill below symbology -> still shows line marker
- the limit - should say "not set" instead of 0 (like for vector layers GUI)

File: src/core/pointcloud/qgspointcloudlayerelevationproperties.h (hunk 3 above)
Comment (ViperMiniQ) [reply src/core/pointcloud/qgspointcloudlayerelevationproperties.h]: Removed.

File: src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp (hunk 6 above)
Comment (ViperMiniQ) [reply src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp]: Resolved TODO, unresolved removal of the comment :facepalm:

File: src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp (hunk 11 above)
Comment (ViperMiniQ) [reply src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp:1090]: Removed.

File: src/core/pointcloud/qgspointcloudlayerelevationproperties.h [hunk 12]
```diff
@@ -207,17 +211,133 @@ class CORE_EXPORT QgsPointCloudLayerElevationProperties : public QgsMapLayerElev
...
+     */
+    void setType( Qgis::PointCloudProfileType type ) { mType = type; }
+
+    /**
+     * Returns the profile type used when generating elevation profile plots.
+     *
+     * \see setRenderType()
+     * \since QGIS 4.0
+     */
+    Qgis::PointCloudProfileType renderType() const { return mType; }
```
Comment (wonder-sk) [inline src/core/pointcloud/qgspointcloudlayerelevationproperties.h]: let's rename to `type()` for consistency

File: src/core/pointcloud/qgspointcloudlayerelevationproperties.h [hunk 13]
```diff
@@ -207,17 +211,133 @@ class CORE_EXPORT QgsPointCloudLayerElevationProperties : public QgsMapLayerElev
...
+     *
+     * \see renderType()
+     * \since QGIS 4.0
+     */
+    void setType( Qgis::PointCloudProfileType type ) { mType = type; }
+
+    /**
+     * Returns the profile type used when generating elevation profile plots.
+     *
+     * \see setRenderType()
```
Comment (wonder-sk) [inline src/core/pointcloud/qgspointcloudlayerelevationproperties.h]: let's fix the docstring references (also for setType())

File: src/core/pointcloud/qgspointcloudlayerelevationproperties.h [hunk 14]
```diff
@@ -207,17 +211,133 @@ class CORE_EXPORT QgsPointCloudLayerElevationProperties : public QgsMapLayerElev
...
 
     double mMaximumScreenError = 0.3;
     Qgis::RenderUnit mMaximumScreenErrorUnit = Qgis::RenderUnit::Millimeters;
 
     double mPointSize = 0.6;
     Qgis::RenderUnit mPointSizeUnit = Qgis::RenderUnit::Millimeters;
     Qgis::PointCloudSymbol mPointSymbol = Qgis::PointCloudSymbol::Square;
+    std::unique_ptr< QgsLineSymbol > mProfileLineSymbol;
+    std::unique_ptr< QgsFillSymbol > mProfileFillSymbol;
+    Qgis::ProfileSurfaceSymbology mSymbology = Qgis::ProfileSurfaceSymbology::FillBelow;
```
Comment (wonder-sk) [inline src/core/pointcloud/qgspointcloudlayerelevationproperties.h]: I would prefer to default to `Line`  (also default for raster, vector, mesh layers)

File: src/core/pointcloud/qgspointcloudlayerelevationproperties.h [hunk 15]
```diff
@@ -207,17 +211,133 @@ class CORE_EXPORT QgsPointCloudLayerElevationProperties : public QgsMapLayerElev
...
+     * \note This setting is only used when type() is Qgis::PointCloudProfileType::TriangulatedSurface.
+     *
+     * \see elevationLimit()
+     * \since QGIS 4.0
+     */
+    void setElevationLimit( double limit );
+
   private:
+    void setDefaultProfileLineSymbol( const QColor &color );
+    void setDefaultProfileMarkerSymbol( const QColor &color );
```
Comment (wonder-sk) [inline src/core/pointcloud/qgspointcloudlayerelevationproperties.h]: I think this method does not exist anymore

File: src/core/pointcloud/qgspointcloudlayerelevationproperties.h [hunk 16]
```diff
@@ -19,9 +19,13 @@
 #ifndef QGSPOINTCLOUDLAYERELEVATIONPROPERTIES_H
 #define QGSPOINTCLOUDLAYERELEVATIONPROPERTIES_H
 
+#include "qgis.h"
 #include "qgis_core.h"
 #include "qgis_sip.h"
+#include "qgsfillsymbol.h"
+#include "qgslinesymbol.h"
 #include "qgsmaplayerelevationproperties.h"
+#include "qgsmarkersymbol.h"
```
Comment (wonder-sk) [inline src/core/pointcloud/qgspointcloudlayerelevationproperties.h:28]: this #include can be removed now

File: src/app/pointcloud/qgspointcloudelevationpropertieswidget.cpp [hunk 17]
```diff
@@ -108,6 +152,20 @@ void QgsPointCloudElevationPropertiesWidget::syncToLayer( QgsMapLayer *layer )
...
+
+  switch ( properties->renderType() )
+  {
+    case Qgis::PointCloudProfileType::IndividualPoints:
+      mInterpretationStackedWidget->setCurrentWidget( pageIndividualPoints );
+      break;
+    case Qgis::PointCloudProfileType::TriangulatedSurface:
+      mInterpretationStackedWidget->setCurrentWidget( pageTriangulatedSurface );
+      break;
+  }
```
Comment (wonder-sk) [inline src/app/pointcloud/qgspointcloudelevationpropertieswidget.cpp:167]: it looks like elevation limit value is not set in the widget?

File: src/core/pointcloud/qgspointcloudlayerprofilegenerator.h [hunk 18]
```diff
@@ -17,17 +17,20 @@
...
 #include "qgis_core.h"
 #include "qgis_sip.h"
 #include "qgsabstractprofilegenerator.h"
+#include "qgsabstractprofilesurfacegenerator.h"
 #include "qgscoordinatereferencesystem.h"
 #include "qgscoordinatetransform.h"
 #include "qgscoordinatetransformcontext.h"
 #include "qgsgeos.h"
 #include "qgslinesymbol.h"
+#include "qgsmarkersymbol.h"
```
Comment (wonder-sk) [inline src/core/pointcloud/qgspointcloudlayerprofilegenerator.h]: can be removed now

File: src/core/pointcloud/qgspointcloudlayerprofilegenerator.h [hunk 19]
```diff
@@ -45,6 +48,7 @@ class QgsPointCloudRequest;
 class QgsPointCloudBlock;
 class QgsGeos;
 class QgsPreparedPointCloudRendererData;
+class QgsTriangle;
```
Comment (wonder-sk) [inline src/core/pointcloud/qgspointcloudlayerprofilegenerator.h]: seems not needed here

File: src/core/pointcloud/qgspointcloudlayerprofilegenerator.h [hunk 20]
```diff
@@ -144,58 +196,121 @@ class CORE_EXPORT QgsPointCloudLayerProfileGenerator : public QgsAbstractProfile
...
+
+    double elevationLimit() const
+    {
+      return mElevationLimit;
+    }
+
+  private:
+    QVector<QgsPointCloudNodeId> traverseTree( const QgsPointCloudIndex &pc, QgsPointCloudNodeId n, double maxErrorPixels, double nodeErrorPixels, const QgsDoubleRange &zRange );
+    int visitNodesSync( const QVector<QgsPointCloudNodeId> &nodes, QgsPointCloudIndex &pc, QgsPointCloudRequest &request, const QgsDoubleRange &zRange );
+    int visitNodesAsync( const QVector<QgsPointCloudNodeId> &nodes, QgsPointCloudIndex &pc,  QgsPointCloudRequest &request, const QgsDoubleRange &zRange );
```
Comment (wonder-sk) [inline src/core/pointcloud/qgspointcloudlayerprofilegenerator.h]: these functions do not really exist...

File: src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp [hunk 21]
```diff
@@ -725,6 +610,160 @@ int QgsPointCloudLayerProfileGenerator::visitNodesAsync( const QVector<QgsPointC
   return nodesDrawn;
 }
 
+void QgsPointCloudLayerProfileGeneratorBase::visitBlock( const QgsPointCloudBlock *block, const QgsDoubleRange &zRange )
+{
+  Q_UNUSED( block );
+  Q_UNUSED( zRange );
+}
```
Comment (wonder-sk) [inline src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp]: I would declare visitBlock() as pure virtual function, and we can get rid of this empty function body - it should be mandatory that every derived class implements visitBlock() anyway...

File: src/core/pointcloud/qgspointcloudlayerprofilegenerator.h [hunk 22]
```diff
@@ -144,58 +196,121 @@ class CORE_EXPORT QgsPointCloudLayerProfileGenerator : public QgsAbstractProfile
...
 
+    QgsFillSymbol *fillSymbol() const
+    {
+      return mFillSymbol.get();
+    }
+
+    double elevationLimit() const
+    {
+      return mElevationLimit;
+    }
```
Comment (wonder-sk) [inline src/core/pointcloud/qgspointcloudlayerprofilegenerator.h]: do we need these getters? I can see that QgsTriangulatedPointCloudLayerProfileResults is using that to copy that data, but it is already a friend class, which does direct access to other private members - so I would suggest to remove these getters and just use direct access...

**Comment by ViperMiniQ** [comment]
@wonder-sk 

The reason for the existing test change was that the previous logic was not correct and it was "accidentally" fixed during the refactor

mResults is reset to a nullptr if no points are found, so in Python we get None.
Before the refactor, it would be initialized as an empty list, but if we failed to get any nodes from an index, the code would return early and while we would still not be getting any points, mResults would remain initialized, but empty, in that case. 
After the refactor, we only care about actual points, we skip indexes that contain no data relevant for the elevation profile.

For more details, see bug report #64761

**Review by wonder-sk — APPROVED** [review]

**Comment by ptitjano** [comment]
@ViperMiniQ Thank you for working on this. Could` you please add a unit test to `QgsGeometryUtils::interpolateZ`?
