### PR TITLE
Initialize plugin path (initQgis) before QgsNetworkAccessManager

### LINKED ISSUE #61043: Using authentication configuration for a network proxy leads to disabling the authentication system since QGIS 3.40
### What is the bug or the crash?

Since QGIS 3.40.4 ltr it is not possible to use an authentication configuration within the HttpProxy configuration.
If a proxy is configured for web access and a stored authentication configuration is used, starting QGIS leads to the error message:
```
Authentication System: DISABLED. Resources authenticating via the system can not be accessed.
```
AS the authentication system is disabled it is not possible to load any data from data base, where the authentication is needed.

It works fine with QGIS 3.34.15 ltr.

### Steps to reproduce the issue

1. Setting proxy configuration within QGIS or directly in the `QGIS3.ini` file like
```
[proxy]
proxyEnabled=true
proxyHost=my.proxy.host
proxyPort=1234
proxyUser=
proxyPassword=
proxyType=HttpProxy
noProxyUrls=@Invalid()
authcfg=conf_id
```
2. (re)start QGIS
3. The error message appears and the authentication system is disabled

### Versions

QGIS-Version | 3.40.4-Bratislava
-- | --
QGIS-Codeversion | 4dd7d7e969
 
Bibliotheken
Qt-Version | 5.15.13
Python-Version | 3.12.9
GDAL version | 3.10.2
PROJ-Version | 9.5.1
EPSG-Registraturdatenbankversion | v11.022 (2024-11-05)
GEOS-Version | 3.13.0-CAPI-1.19.0 (kompiliert)3.13.1-CAPI-1.19.2 (laufend)
SQLite-Version | 3.46.1
PDAL-Version | 2.8.3
PostgreSQL-Client-Version | unknown
SpatiaLite-Version | 5.1.0
QWT-Version | 6.3.0
QScintilla2-Version | 2.14.1
BS-Version | Windows 10 Version 1809
 
Aktive Python-Erweiterungen
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by m-kuhn**
An authentication config can be used for the network proxy. When this is approach is taken, the auth system will be initialized when the QgsNetworkAccessManager is used first, which is "early" according to the comment in the code. The auth system initialization requires the plugin path to be set. The plugin path is initialized in initQgis, we therefore move the call to `initQgis` to even earlier.

Fixes https://github.com/qgis/QGIS/issues/61043

### CODE REVIEW

File: src/app/qgisapp.cpp [hunk 1]
```diff
@@ -997,6 +997,8 @@ QgisApp::QgisApp( QSplashScreen *splash, AppOptions options, const QString &root
   connect( mUserProfileManager, &QgsUserProfileManager::profilesChanged, this, &QgisApp::refreshProfileMenu );
   endProfile();
 
+  QgsApplication::initQgis();
```
Comment (m-kuhn) [inline src/app/qgisapp.cpp:1001]:
```suggestion
  // Initialize QGIS (and the plugins) before the network
  QgsApplication::initQgis();
```

**Review by alexbruy — APPROVED** [review]
