### PR TITLE
Untwine upstream updates - unicode path fixes on windows

### LINKED ISSUE #41833: Failed to run untwine.exe if path contain accented character
**Describe the bug**

I tried to import a laz file using qgis 3.18.
I noticed that if the path contain an accented character, it silently fails.

> 2021-02-25T18:50:38     INFO    Created output directory T:/blablabla/Données_MNT_lidar/LAS12/ept_405000_6260000
> 2021-02-25T18:50:38     INFO    Using executable C:/OSGEO4~2/apps/qgis/./untwine.exe
> 2021-02-25T18:50:39     INFO    Removing temporary files in temp

It also raises a critical error if you try to import twice the file.

> 2021-02-25T18:51:09     CRITICAL    Folder :/blablabla/Données_MNT_lidar/LAS12/ept_405000_6260000 is non-empty, but there isn't ept.json present.

But it's normal I think.

If I remove the accented character

> 2021-02-25T18:51:39     INFO    Created output directory T:/blablabla/Donnees_MNT_lidar/LAS12/ept_405000_6260000
> 2021-02-25T18:51:39     INFO    Using executable C:/OSGEO4~2/apps/qgis/./untwine.exe
> 2021-02-25T18:51:40     INFO    Processed 100000 points
> 2021-02-25T18:51:40     INFO    Processed 200000 points
> ...
> 2021-02-25T18:52:06     INFO    Sample complete for 1-1-1-0
> 2021-02-25T18:52:06     INFO    Sample complete for 0-0-0-0
> 2021-02-25T18:52:06     INFO    Removing temporary files in temp

image

**How to Reproduce**

1. Create a folder with an accented character and copy a laz file inside
2. Import the laz file in qgis
3. See messages: no error, only the extent is computed

**QGIS and OS versions**
3.18.0 OSGEO4W testing Win10

### PR DESCRIPTION
**Pull request by wonder-sk**
Fixes #41833

### CODE REVIEW

**Review by uclaros — APPROVED** [review]

File: external/untwine/bu/BuPyramid.cpp [hunk 1]
```diff
@@ -13,6 +14,36 @@
...
+// version here so that we can still use older PDAL releases.
+std::vector<std::string> directoryList(const std::string& dir)
+{
+    namespace fs = std::filesystem;
+
+    std::vector<std::string> files;
+
+    try
+    {
+        fs::directory_iterator it(untwine::toNative(dir));
```
Comment (3nids) [inline external/untwine/bu/BuPyramid.cpp:30]: this breaks build on macos when the target is less than 10.15 which is not realistic for now.
Any chance to bring a code which would compile on 10.13?
see https://github.com/qgis/QGIS-Mac-Packager/pull/150

Comment (wonder-sk) [reply external/untwine/bu/BuPyramid.cpp:30]: @hobu @abellgithub Unfortunately it looks like the recent untwine update breaks QGIS macOS build. Would it be possible to update untwine code so that it compiles on macos 10.13 as well?

Comment (wonder-sk) [reply external/untwine/bu/BuPyramid.cpp:30]: Hopefully this fix from @hobu should help https://github.com/qgis/QGIS/pull/48697

**Comment by agiudiceandrea** [comment]
Hi @wonder-sk, it looks like the same issue (or a similar one) allegedly fixed by this PR is occurring again: please see https://github.com/qgis/QGIS/issues/57913.

**Comment by hobu** [comment]
Indeed this was a regression due to a pull request that attempted to make MinGW work for Untwine. See https://github.com/hobuinc/untwine/issues/167 for more details.

**Comment by agiudiceandrea** [comment]
Thanks @hobu. Anyway I've tested QGIS 3.38.0, 3.34.8, 3.28.15, 3.26.3 and 3.22.16 and it seems to me the issue occurs in all that versions as it was never actually been fixed.
