### PR TITLE
[raster][opencl] Fix raster calc Uint16

### LINKED ISSUE #60077: Enabling OpenCL acceleration generates erratic behavior in raster operations
### What is the bug or the crash?

Using the raster calculation to perform simple tasks gives bad results, changing the aspect ratio of the calculated rasters
error qgis

### Steps to reproduce the issue

1. Go to configuration, options, Aceleration and click Enable OpenCL Acceleration
2. Perfom a simple raster operation using raster calculator
3. The result of the operation is in the wrong aspect ratio. 

### Versions

Versión de QGIS
3.34.14-Prizren
Revisión del código de QGIS
0cdaf6d9
Versión Qt
5.15.13
Versión de Python
3.12.8
Versión de GDAL/OGR
3.9.3
Versión de PROJ
9.5.0
Versión del registro de base de datos EPSG
v11.016 (2024-08-31)
Versión de GEOS
3.13.0-CAPI-1.19.0
Versión de SQLite
3.46.1
Versión de PDAL
2.8.1
Versión del cliente de PostgreSQL
16.2
Versión de SpatiaLite
5.1.0
Versión de QWT
6.3.0
Versión de QScintilla2
2.14.1
Versión del SO
Windows 11 Version 2009

Complementos activos de Python
agriculture_precision
0.1
BreederMap
0.3.1
clipper
1.2
coordinates_converter
1.0
coordinator
0.4
coord_attributable
0.1
copy_coords
0.4.0
DataPlotly
4.2.0
DEMto3D
3.6
dzetsaka
3.70
FreehandRasterGeoreferencer
0.8.3
GeometryShapes
0.7
ImportPhotos
3.0.6
kmltools
3.2.2
latlontools
3.7.2
layer2kmz
1.5.3
pointsamplingtool
0.5.4
processing_r
4.1.0
QRectangleCreator
0.3
quick_map_services
0.19.36
SaveAllScript
1.0
Serval
3.32.0
shp_buddy
1.1.2
Smart_Map
1.4.2
SRTM-Downloader
3.2.3
STL_Generator
1.1.0
valuetool
3.0.19
wbt_for_qgis
1.0.9
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #60077

### CODE REVIEW

File: src/analysis/raster/qgsrastercalculator.cpp [hunk 1]
```diff
@@ -544,7 +544,7 @@ QgsRasterCalculator::Result QgsRasterCalculator::processCalculationGPU( std::uni
     programTemplate = programTemplate.replace( QLatin1String( "##EXPRESSION##" ), cExpression );
     programTemplate = programTemplate.replace( QLatin1String( "##EXPRESSION_ORIGINAL##" ), calcNode->toString() );
 
-    //qDebug() << programTemplate;
+    // qDebug() << programTemplate;
```
Comment (nirvn) [inline src/analysis/raster/qgsrastercalculator.cpp:547]: Should we get rid of this altogether or transform it into a proper QGIS debug log with some elevated level value?

Comment (elpaso) [reply src/analysis/raster/qgsrastercalculator.cpp:547]: you can remove it.

Comment (elpaso) [inline src/analysis/raster/qgsrastercalculator.cpp:547]:
```suggestion
    // qDebug() << programTemplate;
```
