### PR TITLE
QgsFeaturePool: back to a write locker type

### LINKED ISSUE #61087: Qgis crashed from plugin Vector/Check geom
### What is the bug or the crash?

I just launched the built-in plugin from menu :  Vector/Check Geometry to check a Lines layer.
After a few minutes, Qgis froze then ended prematurely.
This happens each time.

Message from the crash-reporter :
Python Stack Trace
Windows fatal exception: access violation
Thread 0x000046e0 (most recent call first):
  File "C:\Users/Olivier/AppData/Roaming/QGIS/QGIS3\profiles\default/python\expressions\default.py"Windows fatal exception: access violation

Stack Trace
PyUnstable_InterpreterFrame_GetLine :
Py_DumpTracebackThreads :
Py_DumpTracebackThreads :
Py_DumpTracebackThreads :
Py_AtExit :
Py_AtExit :
RtlpCallVectoredHandlers :
RtlDispatchException :
KiUserExceptionDispatch :
QgsProcessingUtils::indicesToFields :
QgsAbstractFeatureSource::iteratorOpened :
QgsVectorLayerFeatureIterator::QgsVectorLayerFeatureIterator :
QgsVectorLayerFeatureSource::getFeatures :
QgsFeaturePool::getFeature :
QgsGeometryCheckerUtils::lineIntersections :
QgsGeometryCheckerUtils::LayerFeature::operator!= :
QgsGeometryDuplicateCheck::collectErrors :
QgsGeometryChecker::runCheck :
QgsGeometryChecker::runCheck :
QgsGeometrySnapper::qt_static_metacall :
QgsGeometrySnapper::featureSnapped :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.42.0-M�nster
QGIS code revision: feb8023300
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.10.2
Running against GDAL: 3.10.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22631
Win 11 (23H2)
File infos / source : auvergne-latest.osm.pbf (2024-12, from geofabrik) --> imported into a PostGIS database (v. 17) with osm2pgsql (v. 2.0, flex mode, generic.lua), no customization.

### Steps to reproduce the issue

1. Open my project-file
2. Launch built-in plugin from Vector/Check geometry

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Version de QGIS | 3.42.0-Münster
-- | --
Révision du code | feb8023300
 
Bibliothèques
Version de Qt | 5.15.13
Version de Python | 3.12.9
GDAL version | 3.10.2
Version de Proj | 9.5.1
Version de la base de données du registre EPSG | v11.022 (2024-11-05)
Version de GEOS | 3.13.0-CAPI-1.19.0
Version de SQLite | 3.46.1
Version de PDAL | 2.8.3
Version du client PostgreSQL | 17.3
Version de SpatiaLite | 5.1.0
Version de QWT | 6.3.0
Version de QScintilla2 | 2.14.1
Version de l'OS | Windows 11 Version 2009
 
Extensions Python actives
ArcheoCAD | 3.2.2
cartography_tools | 1.2.1
DsgTools | 4.16.0
kmltools | 3.2.2
latlontools | 3.7.3
MemoryLayerSaver | 5.0.2
multiple_layers_tools | 1.2
networks | 2.8.0
orfeoToolbox_provider | 3.0.3
postgis_toolbox | 1.2
qgis-maptiler-plugin | 3.4.1
qgis2web | 3.25.1
QuickOSM | 2.3.2
quick_map_services | 0.20.0
shapetools | 3.5.1
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>Version de QGIS
3.42.0-Münster
Révision du code
[feb8023300](https://github.com/qgis/QGIS/commit/feb8023300)
 
Bibliothèques
Version de Qt
5.15.13
Version de Python
3.12.9
GDAL version
3.10.2
Version de Proj
9.5.1
Version de la base de données du registre EPSG
v11.022 (2024-11-05)
Version de GEOS
3.13.0-CAPI-1.19.0
Version de SQLite
3.46.1
Version de PDAL
2.8.3
Version du client PostgreSQL
17.3
Version de SpatiaLite
5.1.0
Version de QWT
6.3.0
Version de QScintilla2
2.14.1
Version de l'OS
Windows 11 Version 2009
 
Extensions Python actives
ArcheoCAD
3.2.2
cartography_tools
1.2.1
DsgTools
4.16.0
kmltools
3.2.2
latlontools
3.7.3
MemoryLayerSaver
5.0.2
multiple_layers_tools
1.2
networks
2.8.0
orfeoToolbox_provider
3.0.3
postgis_toolbox
1.2
qgis-maptiler-plugin
3.4.1
qgis2web
3.25.1
QuickOSM
2.3.2
quick_map_services
0.20.0
shapetools
3.5.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Djedouas**
## Description

The comment in the code clearly explains why we need to get a Write locker. I just run into this gotcha and set a Read locker...

Now back to a Write locker.

Fixes #61087

### CODE REVIEW

File: src/analysis/vector/geometry_checker/qgsfeaturepool.cpp [hunk 1]
```diff
@@ -59,7 +51,15 @@ bool QgsFeaturePool::getFeature( QgsFeatureId id, QgsFeature &feature )
...
 
-  QgsReadWriteLocker locker( mCacheLock, QgsReadWriteLocker::Read );
+  // Why is there a write lock acquired here? Weird, we only want to read a feature from the cache, right?
+  // A method like `QCache::object(const Key &key) const` certainly would not modify its internals.
+  // Mmmh. What if reality was different?
+  // If one reads the docs very, very carefully one will find the term "reentrant" in the
+  // small print of the QCache docs. This is the hint that reality is different.
+  //
+  // https://bugreports.qt.io/browse/QTBUG-19794
+  QgsReadWriteLocker locker( mCacheLock, QgsReadWriteLocker::Write );
```
Comment (nyalldawson) [inline src/analysis/vector/geometry_checker/qgsfeaturepool.cpp:61]: Evidently the giant warning comment wasn't sufficient already, so...

```suggestion
  /* DO NOT CHANGE */ QgsReadWriteLocker locker( mCacheLock, QgsReadWriteLocker::Write ); // DO NOT CHANGE!!!!!
```

**Comment by nyalldawson** [comment]
As penance for not reading the giant warning comment you need to add a unit test preventing this breaking again :stuck_out_tongue_closed_eyes:

**Comment by Djedouas** [comment]
> As penance for not reading the giant warning comment you need to add a unit test preventing this breaking again 😝

Haha, right... :P  I added a commit with a test.

In fact, this multithreaded way of launching geometry checks was not tested at all.

I had to add a new test layer however, and took the one from the issue, because I couldn't reproduce the crash with the current test layers available in the geometry checker test data. I guess that the concurrent access does not occur due to the small amount of features.

I can reproduce the crash with this test every time (locally) with the new test layer and the ::Read lock type.

**Comment by nyalldawson** [comment]
Hmm that's a fairly large reference file to add to the repo. Does zipping it help at all?

**Comment by Djedouas** [comment]
Zipping helped a bit, ~25% smaller.

Thanks for the hint :)

**Comment by Djedouas** [comment]
@nyalldawson Is it ok to merge?

**Review by troopa81 — APPROVED** [review]
This looks good to me!
