### PR TITLE
Delete equality operator from QgsMapLayerRef

### LINKED ISSUE #51291: Layer order change does not update the 3d view
### What is the bug or the crash?

Changing the layer order in the _Layers_ panel does not cause the 3d views to update and reflect the change.
This applies to layers without a 3d renderer, that are displayed on the terrain texture.

### Steps to reproduce the issue

1. load two raster layers, eg `tests/testdata/3d/rgb.tif` and `tests/testdata/3d/dtm.tif`
2. open a 3d view
3. flip the order of the two layers in _Layers_ panel
4. 3d view does not change (it should)
5. toggle a layer's visibility to trigger a 3d view update
6. 3d view now displays the order correctly

### Versions

cfbf5ef5 on Debian testing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by uclaros**
## Description
Without an equality operator, `QgsMapLayerRef` was implicitly using its `bool()` operator when compared. This resulted in all unresolved or resolved refs pointing to different layers appear as equal, for example when `QList<QgsMapLayerRef>`s were compared in https://github.com/qgis/QGIS/blob/756083c293201d50d7ddf1b4cc26b560bf0e6df9/src/3d/qgs3dmapsettings.cpp#L642-L658

Fixes #51291

### CODE REVIEW

**Comment by 3nids** [comment]
It sounds this would be worth writing a test, could you add one?

**Comment by nyalldawson** [comment]
Out of interest, is it enough to declare the bool operator as explicit? I believe that was added in C++11 to fix this kind of issue.

I do agree with @troopa81 that an equality operator which considers resolved/non resolved refs as equal should be introduced.

Another question (which I'm struggling to find because internet searching in 2024 is completely broken): do we need to also define inequality operator? Or does the default inequality operator rely on the equality operator? (Ping @rouault ? )

**Comment by uclaros** [comment]
> I fail to understand how it that possible. QList comparison should call the operator== for every of its element. AFAIK Your proposal is the default generated operator==, why would it change something to explicitly write it?

`QList` comparison does a `this == other` for every element. Since there is no `operator==` defined for the sctruct, the compiler actually does `(bool) this == (bool) other`, since the struct has a `operator bool()` defined.





> Out of interest, is it enough to declare the bool operator as explicit? I believe that was added in C++11 to fix this kind of issue.

Good point, will try this out to check if bool operator is implicitly used elsewhere too, which is quite unlikely.




> I do agree with @troopa81 that an equality operator which considers resolved/non resolved refs as equal should be introduced.

I was not sure about that, so I opted for a complete match.
Should it be a strong match, based on `layerId` only? Should it be weak based on `name`, `provider` and `source`? What about two unresolved refs?
What is the use case for it? The more I think about it, the more sense it makes to delete `operator==` and let devs explicitly compare what they need for each case.

**Comment by uclaros** [comment]
OK, I tried both declaring the bool operator as explicit and deleting the operator== and both fix the issue.
The build fails on that specific QList comparison only, so it is not used anywhere else, which is good.
I suggest to actually do both to be on the safe side. If we eventually need a QgsMapLayerRef comparison we can implement it as a named method with a _descriptive_ name about what it compares.

**Comment by nyalldawson** [comment]
Thanks @uclaros ! 

Out of interest, do we get errors elsewhere by declaring our other bool operators as explicit?

**Comment by nyalldawson** [comment]
@uclaros 
> I suggest to actually do both to be on the safe side. If we eventually need a QgsMapLayerRef comparison we can implement it as a named method with a descriptive name about what it compares.

+1

**Comment by uclaros** [comment]
> Out of interest, do we get errors elsewhere by declaring our other bool operators as explicit?

From a quick test, yes, though the first error looked like a false positive, ie the bool conversion was expected. I didn't try further as the `explicit` change required almost a full rebuild.

File: src/3d/qgs3dmapsettings.cpp [hunk 1]
```diff
@@ -643,16 +644,12 @@ void Qgs3DMapSettings::setLayers( const QList<QgsMapLayer *> &layers )
...
-  {
-    lst.append( layer );
-  }
+  const QList<QgsMapLayer *> raw = _qgis_listRefToRaw( mLayers );
 
-  if ( mLayers == lst )
+  if ( layers == raw )
     return;
 
+  const QList<QgsMapLayerRef> lst = _qgis_listRawToRef( layers );
```
Comment (nyalldawson) [inline src/3d/qgs3dmapsettings.cpp:652]: Why not just mLayers direct here?

Comment (uclaros) [reply src/3d/qgs3dmapsettings.cpp]: D'oh!

**Review by nyalldawson — APPROVED** [review]

**Comment by lbartoletti** [comment]
> It sounds this would be worth writing a test, could you add one?

@uclaros why this comment has been ignored(forgotten)?

Please add a test.

**Comment by uclaros** [comment]
The test comment no longer applies: Operator== is now deleted and operator bool is now marked explicit, so the compiler will return an error if any of those is attempted.
If you still think there's something to be tested let me know and I'll happily add it!

**Comment by nyalldawson** [comment]
@uclaros 
> 
> From a quick test, yes, though the first error looked like a false positive, ie the bool conversion was expected. I didn't try further as the `explicit` change required almost a full rebuild.

Ok, fixed here: https://github.com/qgis/QGIS/pull/59086
