### PR TITLE
Fix compound CRSs axis order and orientation info

### LINKED ISSUE #55458: Compound CRSs have invalid axis order information
### What is the bug or the crash?

Compound CRSs have invalid axis order information:

[EPSG:3903](https://epsg.io/3903) (EPSG:5048 + EPSG:3900) has N/E, but QGIS says `.axisOrderInverted() = False` and `.axisOrdering()` is empty. Same empty ordering occurs with all other compound crs's I tested (EPSG:7423/3901/3902 etc), but the info is valid for the compound crs components (ie. 5048 reports north/east, 3900 reports up).

This causes for example OAPIF layers with `storageSrid = <a compound crs>` to fail: by default features are requested with the storage CRS (and bbox given with the same crs). With restrict-to-bbox enabled, features are requested with `bbox` having wrong axis order (and no features are found), and with restrict-to-bbox disabled data is parsed with reversed axis order (and resulting features xy-coordinates are in wrong order).

### Steps to reproduce the issue

Run in Python console:

`QgsCoordinateReferenceSystem("EPSG:3903").axisOrdering()` returns an empty list (should proably contain North/East/Up?)

 `QgsCoordinateReferenceSystem("EPSG:3903").hasAxisInverted()` returns `False` (should be true).

### Versions

QGIS 3.34.1 on Windows 10 downloaded by network installer.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Possibly related to changes made in https://github.com/qgis/QGIS/pull/53790

### PR DESCRIPTION
**Pull request by Djedouas**
## Description

Fixes #55458 where OAPIF provider has wrong CRS information on a compound CRS (`axisOrdering` is empty, and `hasAxisInverted` is always false).

2 options to fix the issue:
- option 1 (in this PR): fix CRSs information directly in `QgsCoordinateReferenceSystem` class
- option 2: fix in OAPIF provider to check if the CRS is a compound CRS and work with calls on `verticalCrs` and `horizontalCrs`? but need to fix other providers as well?

Discussion welcome, tests will be made accordingly.

### CODE REVIEW

File: src/core/proj/qgscoordinatereferencesystem.cpp [hunk 1]
```diff
@@ -824,7 +824,11 @@ bool QgsCoordinateReferenceSystem::hasAxisInverted() const
 {
   if ( d->mAxisInvertedDirty )
   {
-    d->mAxisInverted = QgsProjUtils::axisOrderIsSwapped( d->threadLocalProjObject() );
+    QgsProjUtils::proj_pj_unique_ptr crs( QgsProjUtils::crsToHorizontalCrs( d->threadLocalProjObject() ) );
+    if ( !crs )
+      crs = QgsProjUtils::unboundCrs( d->threadLocalProjObject() );
```
Comment (nyalldawson) [inline src/core/proj/qgscoordinatereferencesystem.cpp:829]: I'd move this logic to sit directly in QgsProjUtils::axisOrderIsSwapped instead

File: src/core/proj/qgscoordinatereferencesystem.cpp [hunk 2]
```diff
@@ -833,6 +837,9 @@ bool QgsCoordinateReferenceSystem::hasAxisInverted() const
 
 QList<Qgis::CrsAxisDirection> QgsCoordinateReferenceSystem::axisOrdering() const
 {
+  if ( type() == Qgis::CrsType::Compound )
+    return horizontalCrs().axisOrdering() + verticalCrs().axisOrdering();
```
Comment (nyalldawson) [inline src/core/proj/qgscoordinatereferencesystem.cpp:841]: This looks fine to me. @rouault I'm interested in your insights though -- do you think there's any risk of a compound CRS ever needing Z / X / Y or Z / Y / X ordering? :thinking:

**Comment by nyalldawson** [comment]
@Djedouas 

> fix CRSs information directly in QgsCoordinateReferenceSystem class

This option looks best to me

**Comment by Djedouas** [comment]
Added tests and moved axis swapped logic into QgsProjUtils

File: src/core/proj/qgscoordinatereferencesystem.cpp (hunk 2 above)
Comment (rouault) [reply src/core/proj/qgscoordinatereferencesystem.cpp:837]: There might be compound CRS that are horizontal + temporal, or horizontal + vertical + temporal, but those are super esoteric. The proposed code should be fine for now

**Comment by Djedouas** [comment]
@nyalldawson tests added, thanks for the review. Should we backport in LTR?

**Review by nyalldawson — APPROVED** [review]
