### PR TITLE
Set up cache geometry if HTML widget needs it

### LINKED ISSUE #34791: Form fails to initialize $geometry
Evaluating expressions involving $geometry inside an HTML widget in a form fails when displaying the attribute table, unless something else forces its evaluation for each feature already.

Minimal replicable failure case attached; see picture and zip.

image

The HTML field contains (in both layers) 
```
My geometry is '<script>document.write(expression.evaluate("geom_to_wkt($geometry)"));</script>'
```

In the first layer, it fails to evaluate property. (Testing on my real project shows $geometry is NULL). In the second layer, it evaluates fine, and the only difference is that I have added to that layer (but not on the form itself!) a virtual field with expression `geom_to_wkt($geometry)`. I assume that is forcing `$geometry` to be evaluated and stored somewhere, where it is then available for the form to use in the HTML field too.

The same happens in a QML widget.

Note however there is no problem - `$geometry` is not null - when testing with the preview in the `Configure HTML widget` window in the Form settings tab. It's only when you open the form in the attribute table that `$geometry` becomes null.

QGIS 3.12, OSGeo4W.

[geomnullerror.zip](https://github.com/qgis/QGIS/files/4270339/geomnullerror.zip)

### PR DESCRIPTION
**Pull request by troopa81**
Supersedes #39041 and fixes #34791

It's possible to define a geometry based expression in HTML widget, but if the vector layer cache doesn't require geometry the expression will fail. This PR propose to run an html rendering to guess if the expression needs the geometry and then set up the cache geometry option on the vector layer cache.

### CODE REVIEW

File: src/gui/qgsattributeform.h [hunk 1]
```diff
@@ -331,6 +331,11 @@ class GUI_EXPORT QgsAttributeForm : public QWidget
      */
     void parentFormValueChanged( const QString &attribute, const QVariant &newValue );
 
+    /**
+     * Returns true if one of the form widgets needs feature geometry
```
Comment (elpaso) [inline src/gui/qgsattributeform.h:335]:
```suggestion
     * Returns true if any of the form widgets need feature geometry
```

File: src/gui/editorwidgets/qgshtmlwidgetwrapper.cpp [hunk 2]
```diff
@@ -128,4 +156,15 @@ QString HtmlExpression::evaluate( const QString &expression ) const
   exp.prepare( &mExpressionContext );
   return exp.evaluate( &mExpressionContext ).toString();
 }
+
+QString NeedsGeometryEvaluator::evaluate( const QString &expression )
```
Comment (elpaso) [inline src/gui/editorwidgets/qgshtmlwidgetwrapper.cpp:160]: Why returning a (constant empty) string here? Shouldnìt it be `void` ?

File: src/gui/editorwidgets/qgshtmlwidgetwrapper.cpp [hunk 3]
```diff
@@ -52,12 +52,14 @@ void QgsHtmlWidgetWrapper::initWidget( QWidget *editor )
   mWidget->setZoomFactor( horizontalDpi / 96.0 );
 
   QWebPage *page = mWidget->page();
+  page->settings()->setAttribute( QWebSettings::DeveloperExtrasEnabled, true );
```
Comment (elpaso) [inline src/gui/editorwidgets/qgshtmlwidgetwrapper.cpp:55]: Is this required by `javaScriptWindowObjectCleared` below?

File: src/gui/attributetable/qgsdualview.cpp [hunk 4]
```diff
@@ -129,7 +129,14 @@ void QgsDualView::init( QgsVectorLayer *layer, QgsMapCanvas *mapCanvas, const Qg
   mLayer = layer;
   mEditorContext = context;
 
-  initLayerCache( !( request.flags() & QgsFeatureRequest::NoGeometry ) || !request.filterRect().isNull() );
+  // create an empty form to find out if it needs geometry or not
+  QgsAttributeForm emptyForm( mLayer, QgsFeature(), mEditorContext );
+
+  bool needsGeometry = !( request.flags() & QgsFeatureRequest::NoGeometry )
```
Comment (pblottiere) [inline src/gui/attributetable/qgsdualview.cpp:135]:
```suggestion
  const bool needsGeometry = !( request.flags() & QgsFeatureRequest::NoGeometry )
```

File: src/gui/editorwidgets/qgshtmlwidgetwrapper.h [hunk 5]
```diff
@@ -53,6 +53,12 @@ class GUI_EXPORT QgsHtmlWidgetWrapper : public QgsWidgetWrapper
     //! Sets the HTML code to \a htmlCode
     void setHtmlCode( const QString &htmlCode );
 
+    /**
+     * Returns true if the widget needs feature geometry
+     * \since QGIS 3.16
```
Comment (pblottiere) [inline src/gui/editorwidgets/qgshtmlwidgetwrapper.h:58]: 3.20?

Comment (troopa81) [reply src/gui/editorwidgets/qgshtmlwidgetwrapper.h:58]: I intended to backport to 3.16, so not sure what the policy is here.

File: src/gui/editorwidgets/qgshtmlwidgetwrapper.h [hunk 6]
```diff
@@ -94,6 +107,32 @@ class HtmlExpression : public QObject
...
+    Q_OBJECT
+
+  public:
+
+    //! Returns true if the widget needs feature geometry
+    bool needsGeometry() const { return mNeedsGeometry; }
+
+  public:
+
+    //! evaluates the value regarding the \a expression and the context
```
[the remark this answers is not in the document]
Comment (troopa81) [reply src/gui/editorwidgets/qgshtmlwidgetwrapper.h:129]: True. I reworked my PR to take the context in consideration

File: src/gui/editorwidgets/qgshtmlwidgetwrapper.cpp (hunk 2 above)
Comment (troopa81) [reply src/gui/editorwidgets/qgshtmlwidgetwrapper.cpp]: Yes. Fixed

File: src/gui/attributetable/qgsdualview.cpp (hunk 4 above)
Comment (troopa81) [reply src/gui/attributetable/qgsdualview.cpp]: Done

File: src/gui/editorwidgets/qgshtmlwidgetwrapper.cpp (hunk 3 above)
Comment (troopa81) [reply src/gui/editorwidgets/qgshtmlwidgetwrapper.cpp:55]: No, the fix works without it. I moved it because I thought it was better to do it when initializing widget, instead of doing it when setting the feature.

According to the documentation, I think we could remove it 

> Enables extra tools for Web developers. Currently this enables the "Inspect" element in the context menu as well as the use of QWebInspector which controls the web inspector for web site debugging. This is disabled by default.

I can remove it, I'm just afraid about some potential side effect I'm not aware of.

**Comment by troopa81** [comment]
> Can you please test these changes on top of #43606 and report the time to load a 1 million record table before/after your changes (I'm going to ask this for ANY changes people make to vector layer cache/any of the attribute table/form classes from now on! joy)

@nyalldawson It takes less than 3 minutes for 3 million features, so it's quite the same order of magnitude than 20s for 500k

File: src/gui/editorwidgets/qgshtmlwidgetwrapper.cpp (hunk 3 above)
Comment (troopa81) [reply src/gui/editorwidgets/qgshtmlwidgetwrapper.cpp]: I removed it because I do think its useless :crossed_fingers:

File: src/gui/editorwidgets/qgshtmlwidgetwrapper.h (hunk 5 above)
Comment (troopa81) [reply src/gui/editorwidgets/qgshtmlwidgetwrapper.h]: After second thoughts, I think it's better to write 3.20 even if I backport. I changed it

**Comment by nyalldawson** [comment]
@troopa81 

> It takes less than 3 minutes for 3 million features, so it's quite the same order of magnitude than 20s for 500k

I need more assurance than that 😂 (it's nothing personal, but history has proven that any changes to attribute table code has unintended side effects, and we constantly keep screwing this up).

Please rebase off master and time the 3 million feature load with and without your changes, and report both figures back here.

**Comment by troopa81** [comment]
@nyalldawson No problem, I do understand your concerns. I just tested it on QGIS master 409b22101c (which contains #43606):
- with my modification: 3 minutes and 1 seconds
- without my modifications : 3 minutes and 2 seconds

**Comment by nyalldawson** [comment]
Thanks @troopa81 !

File: src/gui/qgsattributeform.h [hunk 7]
```diff
@@ -331,6 +331,11 @@ class GUI_EXPORT QgsAttributeForm : public QWidget
      */
     void parentFormValueChanged( const QString &attribute, const QVariant &newValue );
 
+    /**
+     * Returns true if any of the form widgets need feature geometry
```
Comment (pblottiere) [inline src/gui/qgsattributeform.h:335]:
```suggestion
     * Returns TRUE if any of the form widgets need feature geometry
```

**Comment by troopa81** [comment]
Everything is green. Is it OK to merge?

**Comment by troopa81** [comment]
gentle ping @elpaso, is there anything that need to be fixed ?

**Review by elpaso — APPROVED** [review]

**Comment by troopa81** [comment]
Thanks @elpaso

**Comment by elpaso** [comment]
I think there is a problem building without WebKit, can you have a look?

**Comment by troopa81** [comment]
> I think there is a problem building without WebKit, can you have a look?

Yes
