### PR TITLE
Don't open filter from indicator when layer is edited

### LINKED ISSUE #51816: Filter dialog for vector layers in edit state can still be opened via the filter icon in the layers menu
### What is the bug or the crash?

When a vector layer is in edit state, the filter expression is not editable, as the corresponding action in the context menu is disabled.

However, it is still possible to open the filter dialog through the little filter icon which is displayed right next to the layer in the table of contents (layers panel). Trying to edit the filter expression will result in an error and the error message does not indicate that the filter cannot be changed because the layer is in edit state.

### Steps to reproduce the issue

1. Set a filter for a vector layer
2. Toggle editiing for the vector layer
3. In the table of contents, right click the layer --> see that the _filter_ option is disabled
4. Click on the filter icon on the right in the table of contents --> the filter dialog opens
5. Change the filter expression and hit OK --> Error message: "_Error in query. The subset string could not be set_"

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.28.3-Firenze | QGIS code revision | c12bcb2f76c
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

https://user-images.githubusercontent.com/78353871/218270463-0290cb17-5325-4684-aeed-a2e19610fbdb.mp4

### PR DESCRIPTION
**Pull request by troopa81**
Fixes #51816

### CODE REVIEW

File: src/app/qgslayertreeviewfilterindicator.cpp [hunk 1]
```diff
@@ -37,8 +37,12 @@ void QgsLayerTreeViewFilterIndicatorProvider::onIndicatorClicked( const QModelIn
   if ( !QgsLayerTree::isLayer( node ) )
     return;
 
-  QgisApp::instance()->layerSubsetString( QgsLayerTree::toLayer( node )->layer() );
+  QgsMapLayer *layer = QgsLayerTree::toLayer( node )->layer();
+  QgsVectorLayer *vl = qobject_cast<QgsVectorLayer *>( layer );
+  if ( vl && vl->isEditable() )
+    return;
```
Comment (nyalldawson) [inline src/app/qgslayertreeviewfilterindicator.cpp:43]: Instead of silently returning (which gives users no idea why this operation doesn't work when it usually does), could we show an informative message in the message bar?

**Comment by uclaros** [comment]
I know it's way more complicated than this, but how about opening the query builder but disallowing modifications?
This would allow the user to:
- review the filter query of an editable layer in a more readable format than the tooltip.
- check the list of available values for a field
- save the filter to a file without stopping editing

File: src/app/qgslayertreeviewfilterindicator.cpp (hunk 1 above)
Comment (troopa81) [reply src/app/qgslayertreeviewfilterindicator.cpp:46]: Done

**Comment by troopa81** [comment]
Regarding your comment @uclaros , I have no strong opinion on whether it would be better or not. But for now, I prefer to stay consistent with the menu item and the properties source tab. It's beyond the scope of this PR.

**Comment by uclaros** [comment]
In that case you should also close #44055, as the referenced issue is a recent duplicate

**Comment by troopa81** [comment]
> In that case you should also close https://github.com/qgis/QGIS/issues/44055, as the referenced issue is a recent duplicate

Done, thanks for pointing that out

**Review by nyalldawson — APPROVED** [review]
