### PR TITLE
RelationReference save edits on embedded form

### LINKED ISSUE #60806: Relation Reference Embedded Form not updated
### What is the bug or the crash?

When having a parent linked to a child and using the Relation Reference Widget with the option "Embedded Form"...

Image

... changes in this embedded form (where the the parent feature is) are only updated, when something changes on the main form (where the child feature is).

*While this scenario works with joined fields*

### Steps to reproduce the issue

- In the attached project I open a form from an "addresse" feature (child feature).
- I change something in the embedded form (means the "gebaeude" (parent feature)).
  Image
- Pressing okay - nothing is saved...

- In the attached project I open a form from an "addresse" feature (child feature).
- I change something in the embedded form (means the "gebaeude" (parent feature)).
- **and** I change something in the main form
  Image
- Pressing okay - changes are saved on both features.

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.43.0-Master</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/4de10b9d4cd">4de10b9d4cd</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.3</td></tr><tr><td>Python version</td><td>3.10.12</td></tr><tr><td>GDAL version</td><td>3.9.0dev-365401613a</td></tr><tr><td>PROJ version</td><td>8.2.1</td></tr><tr><td>EPSG Registry database version</td><td>v10.041 (2021-12-03)</td></tr><tr><td>GEOS version</td><td>3.10.2-CAPI-1.16.0</td></tr><tr><td>SQLite version</td><td>3.37.2</td></tr><tr><td>PDAL version</td><td>2.3.0</td></tr><tr><td>PostgreSQL client version</td><td>17.0</td></tr><tr><td>SpatiaLite version</td><td>5.0.1</td></td></tr><tr><td>QWT version</td><td>6.1.4</td></tr><tr><td>QScintilla2 version</td><td>2.11.6</td></tr><tr><td>OS version</td><td>Ubuntu 22.04.5 LTS</td></tr><tr><td colspan="2"><i>This copy of QGIS writes debugging output.</i></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>processing</td><td>2.12.99</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr></table>

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

[relrefwidgetembed.zip](https://github.com/user-attachments/files/19030661/relrefwidgetembed.zip) <- in the zip is a gpkg and in the gpkg is a project...

### PR DESCRIPTION
**Pull request by signedav**
You have been able to change values in the embedded form of the relation reference widget, but they were not stored. Only when changing something in the main form the save has been triggered (via vector layer modified).

Now it triggers the save of the embedded form whenever the "OK" button of t he main form is pressed or the index in the attribute table form view is changed.

This fixes #60806

### CODE REVIEW

File: src/gui/editorwidgets/qgsrelationreferencewidget.h [hunk 1]
```diff
@@ -269,6 +268,9 @@ class GUI_EXPORT QgsRelationReferenceWidget : public QWidget
     //! unset the currently related feature
     void deleteForeignKeys();
 
+    //! trigger save of the embedded referenced attribute form
+    bool saveReferencedAttributeForm();
```
Comment (nyalldawson) [inline src/gui/editorwidgets/qgsrelationreferencewidget.h:272]:
```suggestion
    /**
      * Trigger save of the embedded referenced attribute form.
      *
      * \since QGIS 3.44
      */
    bool saveReferencedAttributeForm();
```

**Comment by signedav** [comment]
Since this leads to data-loss of newly entered data an LTR backport should be considered. I'm not yet fully convinced. It seems quite unrisky but every save-function triggers signals, that might be a risk still. 

I could imagine an extended test period of an additional month could help to get confidence. Any opinion?

File: src/gui/editorwidgets/qgsrelationreferencewidget.h [hunk 2]
```diff
@@ -269,6 +268,13 @@ class GUI_EXPORT QgsRelationReferenceWidget : public QWidget
     //! unset the currently related feature
     void deleteForeignKeys();
 
+    /**
+      * Trigger save of the embedded referenced attribute form.
+      *
+      * \since QGIS 3.42
+      */
+    bool saveReferencedAttributeForm();
```
Comment (3nids) [inline src/gui/editorwidgets/qgsrelationreferencewidget.h:276]: can you specify the return value, and state that it will return TRUE if no embed form is present

File: src/gui/editorwidgets/qgsrelationreferencewidgetwrapper.h [hunk 3]
```diff
@@ -63,6 +63,7 @@ class GUI_EXPORT QgsRelationReferenceWidgetWrapper : public QgsEditorWidgetWrapp
     void updateConstraintWidgetStatus() override;
 
   private:
+    void aboutToSave() override;
```
Comment (3nids) [inline src/gui/editorwidgets/qgsrelationreferencewidgetwrapper.h:66]: make it virtual too?

Comment (signedav) [reply src/gui/editorwidgets/qgsrelationreferencewidgetwrapper.h:66]: I could. But why?

Comment (3nids) [reply src/gui/editorwidgets/qgsrelationreferencewidgetwrapper.h:66]: I was thinking at a sub-implementation in Python, but it would require SIP_FORCE and I'm not sure it makes a lot of sense after all.

File: src/gui/editorwidgets/qgsrelationreferencewidget.h [hunk 4]
```diff
@@ -269,6 +268,14 @@ class GUI_EXPORT QgsRelationReferenceWidget : public QWidget
     //! unset the currently related feature
     void deleteForeignKeys();
 
+    /**
+      * Trigger save of the embedded referenced attribute form.
+      * Returns true on success or if no embedded form is present.
```
Comment (3nids) [inline src/gui/editorwidgets/qgsrelationreferencewidget.h:273]:
```suggestion
      * Returns TRUE on success or if no embedded form is present.
```
so it's correctly parsed

**Review by 3nids — APPROVED** [review]
