### PR TITLE
Fix Random Extract duplicates features

### LINKED ISSUE #52114: Random Extract duplicates features
### What is the bug or the crash?

I've got a vector layer with 2705 features from which I want to randonmly extract 1000 of them. Using the `Random Extract` tool, it returns a set of 1000 features but some of them are duplicated (up to four times). I've checked the `id` attribute and it is correctly set. 
For being on the safe side, I've also used the `Random selection` tool to verify if it returns a correct set of features and it has worked well.

### Steps to reproduce the issue

1. Go to Toolbox
2. Click on `Random extract`
3. Select vector layer
4. Set 1000 features

### Versions

Versión de QGIS
3.22.16-Białowieża
Revisión del código de QGIS
6f08e4d7
Versión Qt
5.15.3
Versión de Python
3.9.5
Versión de GDAL/OGR
3.6.2
Versión de PROJ
9.1.1
Versión del registro de base de datos EPSG
v10.076 (2022-08-31)
Versión GEOS
3.11.1-CAPI-1.17.1
Versión de SQLite
3.39.4
Versión de PDAL
2.4.3
Versión del cliente de PostgreSQL
14.3
Versión de SpatiaLite
5.0.1
Versión de QWT
6.1.6
Versión de QScintilla2
2.13.1
Versión del SO
Windows 10 Version 2009

Complementos activos de Python
active_fire
0.3
DataPlotly
3.9.2
DEMto3D
3.51
HCMGIS
23.2.1
latlontools
3.6.7
OSMDownloader
1.0.3
pg_raster_import
3.1.0
pointsamplingtool
0.5.4
ProjectPackager
0.5.1
qdraw
3.0.2
qgisnetworklogger
0.2.0
QuickOSM
2.1.1
quick_map_services
0.19.32
sigpac_downloader
0.3
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by YoannQDQ**
- Fixes #52114

## Description

The Random Extract algorithm randomly selects n integers from 0 to featureCount, and uses these as a list of feature ids. However, feature ids are not guaranteed to be in this range (it will notably not be the case if some feature were deleted in the current session). Besides, id 0 will typicaly be an invalid feature (this PR set the range to 1->featureCount). 

With this PR, the algorithm builds the list of the actual ids before selecting them to fix this issue. It then performs a modified [Fisher–Yates shuffle](https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle) to select the ids. This performs the C++ equivalent of Python's `random.sample`

### CODE REVIEW

File: src/analysis/processing/qgsalgorithmrandomextract.cpp [hunk 1]
```diff
@@ -104,37 +109,106 @@ QVariantMap QgsRandomExtractAlgorithm::processAlgorithm( const QVariantMap &para
...
-  const std::mt19937 mersenneTwister( randomDevice() );
-  const std::uniform_int_distribution<int> fidsDistribution( 0, count );
-
-  QVector< QgsFeatureId > fids( number );
-  std::generate( fids.begin(), fids.end(), bind( fidsDistribution, mersenneTwister ) );
+  std::mt19937 mersenneTwister( randomDevice() );
 
-  QHash< QgsFeatureId, int > idsCount;
-  for ( const QgsFeatureId id : fids )
+  if ( !noDuplicates )
```
Comment (nyalldawson) [inline src/analysis/processing/qgsalgorithmrandomextract.cpp:114]: Hmm, this branch is quite broken too -- it assumes that feature ids begin at 0 or 1 and have no gaps. That's not a valid assumption! It'd be safer to ALWAYS use the "build list of all feature ids" logic regardless of whether or not we are selecting duplicates...

File: src/analysis/processing/qgsalgorithmrandomextract.cpp [hunk 2]
```diff
@@ -104,37 +109,106 @@ QVariantMap QgsRandomExtractAlgorithm::processAlgorithm( const QVariantMap &para
...
+    // Shuffle <number> features at the start of the iterator
+    auto cursor = allFeats.begin();
+    while ( number-- )
     {
-      break;
+      if ( feedback->isCanceled() )
+        return QVariantMap();
+
+      // Update the distribution to match the number of unshuffled features
+      fidsDistribution.param( std::uniform_int_distribution<int>::param_type( 0, nb - 1 ) );
```
Comment (nyalldawson) [inline src/analysis/processing/qgsalgorithmrandomextract.cpp:187]: on qt 6 builds this would need to be <std::size_t> -- we'll need a conditional #if here to pick the type based on qt version.

File: src/analysis/processing/qgsalgorithmrandomextract.cpp [hunk 3]
```diff
@@ -67,6 +67,10 @@ void QgsRandomExtractAlgorithm::initAlgorithm( const QVariantMap & )
   addParameter( new QgsProcessingParameterNumber( QStringLiteral( "NUMBER" ), QObject::tr( "Number/percentage of features" ),
                 QgsProcessingParameterNumber::Integer, 10, false, 0 ) );
 
+  std::unique_ptr< QgsProcessingParameterBoolean > noDuplicates = std::make_unique< QgsProcessingParameterBoolean >( QStringLiteral( "NO_DUPLICATES" ), QObject::tr( "No duplicates" ), false );
```
Comment (nyalldawson) [inline src/analysis/processing/qgsalgorithmrandomextract.cpp:70]:
```suggestion
  std::unique_ptr< QgsProcessingParameterBoolean > noDuplicates = std::make_unique< QgsProcessingParameterBoolean >( QStringLiteral( "NO_DUPLICATES" ), QObject::tr( "Avoid duplicates" ), false );
```

File: src/analysis/processing/qgsalgorithmrandomextract.cpp (hunk 1 above)
Comment (YoannQDQ) [reply src/analysis/processing/qgsalgorithmrandomextract.cpp:130]: Ok

File: src/analysis/processing/qgsalgorithmrandomextract.cpp (hunk 3 above)
Comment (YoannQDQ) [reply src/analysis/processing/qgsalgorithmrandomextract.cpp]: Ok

**Comment by agiudiceandrea** [comment]
@YoannQDQ @nyalldawson as already described at https://github.com/qgis/QGIS/issues/52114#issuecomment-1458642031, It seems to me the current behaviour of the "Random extract" algorithm is inconsistent with the behaviour of the other 3 similar algorithms and it is incorrect and not documented.

In particular, the output layer of the "Random extract" algorithm:
- doesn't always contain the number of feature requested by the user
- can contain duplicate features

Instead, the output layer of the "Random extract within subsets", "Random selection" and "Random selection within subsets" algorithms (which have the same description in the short help and in the documentation of the "Random extract" algorithm):
- always contains the number of feature requested by the user
- doesn't contain duplicate features

@YoannQDQ, as I understand correctly your PR, with the new behaviour of the algorithm, the output layer:
- will always contain the number of feature requested by the user
- may contain duplicate features by default with an option to avoid duplicate features

I think it would be better that the output of the algorithm doesn't contain duplicate features by default. An option could be added to allow duplicate features (although I don't see the use of it).

I also think that, if an option to allow or avoid duplicates is added to this algorithm then the same logic should be added at least to the twin algorithm "Random extract within subsets".

**Comment by YoannQDQ** [comment]
If we don't need to keep the behavior somewhat consistent with previous versions, the simplest solution would indeed be to drop the "random selection with duplicates", and only keep the "random selection, no duplicates" that is consistent with the 3 other algorithm. I did not see why one would want duplicated features either, and with the fix to the id list, it is not even that faster to run. Anyway, I second your suggestion to make "avoid duplicates" the default behavior, but I'd like a third opinion. @nyalldawson, what do you think?

File: src/analysis/processing/qgsalgorithmrandomextract.cpp [hunk 4]
```diff
@@ -102,42 +101,74 @@ QVariantMap QgsRandomExtractAlgorithm::processAlgorithm( const QVariantMap &para
...
-  for ( const QgsFeatureId id : fids )
+  std::mt19937 mersenneTwister( randomDevice() );
+  std::uniform_int_distribution<size_t> fidsDistribution;
+
+  // If the number of features to select is greater than half the total number of features
+  // we will instead randomly select features to *exclude* from the output layer
+  size_t shuffledFeatureCount = number;
+  bool invertSelection = number > count / 2;
+  if ( invertSelection )
+    shuffledFeatureCount = count - number;
```
Comment (nyalldawson) [inline src/analysis/processing/qgsalgorithmrandomextract.cpp:130]: There's a chance that the featureCount retrieved earlier is only an estimate, so let's use the actual count here instead:

```suggestion
  size_t actualFeatureCount = allFeats.size();
  size_t shuffledFeatureCount = number;
  bool invertSelection = number > actualFeatureCount / 2;
  if ( invertSelection )
    shuffledFeatureCount = actualFeatureCount - number;
```

File: src/analysis/processing/qgsalgorithmrandomextract.cpp [hunk 5]
```diff
@@ -102,42 +101,74 @@ QVariantMap QgsRandomExtractAlgorithm::processAlgorithm( const QVariantMap &para
...
+
+  size_t nb = count;
```
Comment (nyalldawson) [inline src/analysis/processing/qgsalgorithmrandomextract.cpp:132]:
```suggestion
  size_t nb = actualFeatureCount;
```

**Review by nyalldawson — APPROVED** [review]
