### PR TITLE
Fix "default layout templates" button

### LINKED ISSUE #30064: Default layout manager templates not working
In the layout manager, there is a button "Open template directory -> Default".

This button points to a system directory (`pkgDataPath/composer_templates`) that is not created by the QGIS installation. If the button is clicked, an error message appears, that the directory does not exist and cannot be created.

I am not sure if this is a leftover (and nowhere used) or if it is intended to deploy organization-wide templates.

* In the first case, it would be better to remove the button
* In the second case, it would be better to
  * improve the error message and point to the documentation section on how to setup things properly
  * and/or move this to a different folder which is managed by the sysadmin (and not the application installation)

@nyalldawson I think you originally implemented this behavior, I'd be glad if you could shed some light

### PR DESCRIPTION
**Pull request by m-kuhn**
This changes the behavior of the open default layout templates folder to fall back to the configured layout templates if there is no composer_template folder in the pkgData path or completely deactivate the button if there is no such folder present and no layout template paths are configured.

The previous behavior was to always try to create and open a composer_template folder in pkgData, where pkgData is the application installation folder which in almost every case is a system directory, not writable by the user and therefore the button was in almost every case ending up in an error message.

Fixes https://github.com/qgis/QGIS/issues/30064

### CODE REVIEW

File: src/app/layout/qgslayoutmanagerdialog.cpp [hunk 1]
```diff
@@ -286,7 +288,14 @@ void QgsLayoutManagerDialog::mTemplate_currentIndexChanged( int indx )
 
 void QgsLayoutManagerDialog::mTemplatesDefaultDirBtn_pressed()
 {
-  openLocalDirectory( mDefaultTemplatesDir );
+  if ( QDir( mDefaultTemplatesDir ).exists() )
```
Comment (nyalldawson) [inline src/app/layout/qgslayoutmanagerdialog.cpp]: I think this logic should be flipped - use the user-defined path first, and fallback to the (useless?) bundled path after.

Comment (m-kuhn) [reply src/app/layout/qgslayoutmanagerdialog.cpp]: Since the current (pre 3.8) behaviour is the bundled path but that will not exist in 98.943% [*] of all cases, it's safe to keep it as default, because where it exists it does on purpose. And where it does not exist users will not even be notified about the legacy behaviour.

In short: it doesn't hurt anyone but protects systems which build on this functionality.

[*] All numbers have officially been verified by the FNPA (Fake News Protection Agency)

**Comment by nyalldawson** [comment]
Ok, merge away

**Comment by m-kuhn** [comment]
Thanks.
I'll tag it for backporting too, looks safe to me, but feel free to reject.
