### PR TITLE
Do not set initial attr values for default clause

### LINKED ISSUE #42909: "Reuse last entered attribute values" slows creation of new features on large vector
**Describe the bug**

Good morning,
working on vector layers (tested with polygons) with a lot of features (millions), I noticed that the digitising setting "Reuse last entered attribute values" slows the creation of new features.
I tried on my data and also on OSM data.
After the creation of the first polygon, when I create another one and finalise the editing with the right-click of the mouse, it takes a long time before showing up the Feature Attributes dialog (tents of seconds), QGIS hangs, and I also noticed a burst use of RAM by QGIS (jumping from around 700 MB to more than 2.5 GB).
If I turn off "Reuse last entered attribute values", the polygons are created instantly, with no delay.
Here’s the link for data test and RAM screenshots first, during and after the creation of a feature with "Reuse last entered attribute values" turned on: https://drive.google.com/drive/folders/1fw0vrzLoak8aU5Hv7uJZAGIPIvKiO0Z3?usp=sharing

**QGIS and OS versions**

QGIS 3.16.5 - WIN 10 PRO 20H2

Versione di QGIS | 3.16.5-Hannover | Revisione codice QGIS | 58ba7c1ed6
-- | -- | -- | --
Compilato con Qt | 5.11.2 | Esecuzione con Qt | 5.11.2
Compilato con GDAL/OGR | 3.1.4 | Esecuzione con GDAL/OGR | 3.1.4
Compilato con GEOS | 3.8.1-CAPI-1.13.3 | Esecuzione con GEOS | 3.8.1-CAPI-1.13.3
Compilato su SQLite | 3.29.0 | In esecuzione su SQLite | 3.29.0
Versione client PostgreSQL | 11.5 | Versione SpatiaLite | 4.3.0
Versione QWT | 6.1.3 | Versione QScintilla2 | 2.10.8
Compilato con PROJ | 6.3.2 | Esecuzione con PROJ | Rel. 6.3.2, May 1st, 2020
Versione SO | Windows 10 (10.0)
Attiva python plugin | Go2NextFeature3; plugin_reloader; qgis2web; QMetaTiles; QuickMultiAttributeEdit3; QuickWKT; quick_map_services; StreetView; db_manager; MetaSearch; processing

**Additional context**

Thanks

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #42909

Setting intial values from previously entered values when
they are equal to the default was pointless anyway because
QgsVectorLayerUtils::createFeature will do that a few lines
below.

Setting the default value for unique constraints
was triggering unique checks for no reason and slowing down
the feature creation up to the point that for large layers
QGIS froze.

### CODE REVIEW

File: src/app/qgsfeatureaction.cpp [hunk 1]
```diff
@@ -187,7 +187,10 @@ bool QgsFeatureAction::addFeature( const QgsAttributeMap &defaultAttributes, boo
     }
     else if ( ( reuseAllLastValues || mLayer->editFormConfig().reuseLastValue( idx ) ) && sLastUsedValues()->contains( mLayer ) && ( *sLastUsedValues() )[ mLayer ].contains( idx ) )
     {
-      initialAttributeValues.insert( idx, ( *sLastUsedValues() )[ mLayer ][idx] );
+      // Only set initial attribute value if it's different from the default clause or we may trigger
+      // unique constraint checks for no reason, see https://github.com/qgis/QGIS/issues/42909
+      if ( mLayer->dataProvider()->defaultValueClause( idx ) != ( *sLastUsedValues() )[ mLayer ][idx] )
```
Comment (m-kuhn) [inline src/app/qgsfeatureaction.cpp:192]:
```suggestion
      if ( mLayer->dataProvider() && mLayer->dataProvider()->defaultValueClause( idx ) != ( *sLastUsedValues() )[ mLayer ][idx] )
```

Comment (elpaso) [reply src/app/qgsfeatureaction.cpp:192]: better safe than sorry :)

**Review by nyalldawson — APPROVED** [review]
