### PR TITLE
[geometry snapper] Fix wrong point-to-segment distance within maths

### LINKED ISSUE #56424: QGIS: Snap geometries to layer - not all points are snapping
### What is the bug or the crash?

I am trying to snap sample collection points to the nearest location on a path, however, not all points are snapping correctly.

I use the tool snap geometries to layer and choose the option prefer closest point, insert new vertices to get snapped points that are now somewhere along the path. I set the tolerance limit to 10 metres.

The output shows some points are correctly snapping, but there are many which do not, despite being within the tolerance limit.

### Steps to reproduce the issue

Here is an example. I'm showing my line and a 10 m buffer so you can see which points should be snapped and and which shouldn't.
I also symbolised them by distance to the line. Only the stars should be snapped.
image

If i run the tool Snap geometries to layer (vector processing), with 10m tolerance my output will look exactly the same as the input. Nothing gets snapped.
If i ramp up the distance, only at 100m all my points will get snapped. Some additional points get snapped too, a bit randomly which ones...
image

if i overlay my input and output dataset (output indicated with blue shade) with ID as label, you can see it's a bit random which points get projected and which don't!
image

EPSG of both shapefiles is  28992 , the projected system RD new. Input files are added.
[input files.zip](https://github.com/qgis/QGIS/files/14344003/input.files.zip)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.0-Prizren | QGIS code revision | ffbdd67881
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.2
PROJ version | 9.3.0
EPSG Registry database version | v10.094 (2023-08-08)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.41.1
PDAL version | 2.5.5
PostgreSQL client version | 15.2
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.4
OS version | Windows Server 2016 Version 2009
  |   |   |  
Active Python plugins
BGTImport | 3.18
color_attribute | 0.2.1
DataPlotly | 4.1.0
pdokservicesplugin | 4.2.0
profiletool | 4.2.6
timemanager | 3.6
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.34.0-Prizren
QGIS code revision
[ffbdd67881](https://github.com/qgis/QGIS/commit/ffbdd67881)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.2
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows Server 2016 Version 2009

Active Python plugins
BGTImport
3.18
color_attribute
0.2.1
DataPlotly
4.1.0
pdokservicesplugin
4.2.0
profiletool
4.2.6
timemanager
3.6
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This PR fixes a pretty serious issue with our QgsGeometrySnapper class whereas snapping of point geometry to line  segments would often fail due to a bogus distance to line calculation. 

We were checking whether a given tolerance/distance was within a _squared distance_ value, leading to failures :scream:

Fixes #56424 , #50121 , and likely other issues. A test has been added.

### CODE REVIEW

File: src/analysis/vector/qgsgeometrysnapper.cpp [hunk 1]
```diff
@@ -102,7 +102,7 @@ bool QgsSnapIndex::SegmentSnapItem::getProjection( const QgsPoint &p, QgsPoint &
 bool QgsSnapIndex::SegmentSnapItem::withinDistance( const QgsPoint &p, const double tolerance )
 {
   double minDistX, minDistY;
-  const double distance = QgsGeometryUtilsBase::sqrDistToLine( p.x(), p.y(), idxFrom->point().x(), idxFrom->point().y(), idxTo->point().x(), idxTo->point().y(), minDistX, minDistY, 4 * std::numeric_limits<double>::epsilon() );
+  const double distance = std::sqrt( QgsGeometryUtilsBase::sqrDistToLine( p.x(), p.y(), idxFrom->point().x(), idxFrom->point().y(), idxTo->point().x(), idxTo->point().y(), minDistX, minDistY, 4 * std::numeric_limits<double>::epsilon() ) );
```
Comment (lbartoletti) [inline src/analysis/vector/qgsgeometrysnapper.cpp:105]: If you want to use the distance, use the dedicated method:

```suggestion
  const double distance = QgsGeometryUtilsBase::distance2D( p.x(), p.y(), idxFrom->point().x(), idxFrom->point().y(), idxTo->point().x(), idxTo->point().y(), minDistX, minDistY, 4 * std::numeric_limits<double>::epsilon() );
```
I also seem to have seen this in the geometry checker, maybe; I thought it was deliberate (to avoid using square root) and to compare double the distance; this doesn't seem to be the case in processing. Have you checked to be certain?

**Comment by blacktesta** [comment]
Hi, @nirvn and thank you again for your inpressive work! I will test it as soon as i can and i will inform you about the results.

File: src/analysis/vector/qgsgeometrysnapper.cpp (hunk 1 above)
Comment (rouault) [reply src/analysis/vector/qgsgeometrysnapper.cpp:105]: At the very least if this was deliberate, ``tolerance`` should be renamed to ``toleranceSquared``

Comment (agiudiceandrea) [reply src/analysis/vector/qgsgeometrysnapper.cpp:105]: I would also prefer to compare the distance squared to the tolerance squared rater then adding a root square calculation.

Comment (agiudiceandrea) [reply src/analysis/vector/qgsgeometrysnapper.cpp:105]: I think that was an oversight in https://github.com/qgis/QGIS/commit/c8179c36c59f3d8058d80efeaab3c2ff02d92118.

Comment (nirvn) [reply src/analysis/vector/qgsgeometrysnapper.cpp]: @agiudiceandrea , adjusted.

File: src/analysis/vector/qgsgeometrysnapper.h [hunk 2]
```diff
@@ -209,7 +209,7 @@ class QgsSnapIndex
         QgsPoint getSnapPoint( const QgsPoint &p ) const override;
         bool getIntersection( const QgsPoint &p1, const QgsPoint &p2, QgsPoint &inter ) const;
         bool getProjection( const QgsPoint &p, QgsPoint &pProj ) const;
-        bool withinDistance( const QgsPoint &p, const double distance );
+        bool withinSqrDistance( const QgsPoint &p, const double distance );
```
Comment (nyalldawson) [inline src/analysis/vector/qgsgeometrysnapper.h:212]: Shouldn't this still be:

```suggestion
        bool withinDistance( const QgsPoint &p, const double distance );
```

since distance is the actual distance, not squared distance

Comment (nirvn) [reply src/analysis/vector/qgsgeometrysnapper.h:212]: @nyalldawson , no, I'm passing on a squared tolerance value here (https://github.com/qgis/QGIS/pull/56426/commits/b1d22b9e0a6e8a2fe6c393817fb1319de44d9a21#diff-85f582115e6e43bb3410dea47308187c69ddece5c0621adf3f3aef770ef3cb60R268)

Comment (nyalldawson) [reply src/analysis/vector/qgsgeometrysnapper.h:212]: Oh right, the diff was a little confusing there.

Could we go explicit with "bool withinSquaredDistance( const QgsPoint &p, const double squaredDistance );" ?

Comment (nirvn) [reply src/analysis/vector/qgsgeometrysnapper.h:212]: @nyalldawson , yep, that's reasonable :wink:

**Comment by nirvn** [comment]
@nyalldawson , addressed.

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
Unrelated test failures
