### PR TITLE
row_number variable description update

### LINKED ISSUE #53536: Expression @row_number does not work as expected
### What is the bug or the crash?

If I use the expression `@row_number` in the attribute table of a vector layer it does not return the actual row number like expected when sorted on an other field. Instead it has the same behaviour like `@id`.

QGIS_Bug_@row_number

### Steps to reproduce the issue

1. Create a new vector layer.
2. Add a string attribute to the layer.
3. Add multiple features to the layer with unsorted strings (also NULL strings).
4. Sort table by the string attribute.
5. Add an integer attribute for the id to the layer and fill it with the expression `@id`.
6. Add an integer attribute for the row number to the layer and fill it with the expression `@row_number`.
7. The columns of the two integer attributes are exactly the same!

### Versions

QGIS-Version
3.28.6-Firenze
QGIS-Codeversion
868c9fa03b
Qt-Version
5.15.3
Python-Version
3.9.5
GDAL-Version
3.6.4
PROJ-Version
9.2.0
EPSG-Registraturdatenbankversion
v10.082 (2023-02-06)
GEOS-Version
3.11.2-CAPI-1.17.2
SQLite-Version
3.41.1
PDAL-Version
2.5.2
PostgreSQL-Client-Version
unknown
SpatiaLite-Version
5.0.1
QWT-Version
6.1.6
QScintilla2-Version
2.13.1
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
AnotherDXF2Shape
1.2.7
BezierEditing
version 1.3.6
bgs_basin_tools
0.2.0
bgs_connect
1.3.2
bgs_map_tiles
0.1.2
bgs_radolan
0.1
cigeoe_feature_nodes_z_tag
1.0
crayfish
3.6.0
custom_titlebar
1.0.0
extractor
1.0
flowTrace
1.1.1
LandXml
2.4
linking_relation_editor
v1.1.4
mapswipetool_plugin
1.2
Mergin
2023.1
mmqgis
2021.9.10
ntv2_transformations
0.20
ORStools
1.5.3
pluginbuilder3
3.2.1
plugin_reloader
0.9.3
processing_saga_nextgen
0.0.7
profiletool
4.2.6
pyqgis_resource_browser
0.3.0
qfieldsync
v4.5.0
qgis2rasterlite
0.5
Qgis2threejs
2.7.1
qgis2web
3.16.0
QgisModelBaker
v7.4.2
QuickOSM
2.2.2
QuickPrint
3.6.1
quick_map_services
0.19.33
radolan2map
1.7
SpreadsheetLayers
2.1.0
stationlines
0.2.0
StreetView
3.2
TerrainShading
0.9.3
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### LINKED ISSUE #54509: model designer, field calculator algorithm: unexpected behaviour using @row_number variable?
### What is the bug or the crash?

"field calculator" algorithm available in the model designer:

trying to create a new field just using the expression @row_number, the result field starts numbering the rows by 0 instead of 1.

### Steps to reproduce the issue

screens2

### Versions

Versión de QGIS
3.30.0-'s-Hertogenbosch
Revisión del código de QGIS
f186b8efe0e
Versión Qt
5.15.3
Versión de Python
3.9.5
Versión de GDAL/OGR
3.6.2
Versión de PROJ
9.1.1
Versión del registro de base de datos EPSG
v10.076 (2022-08-31)
Versión de GEOS
3.11.1-CAPI-1.17.1
Versión de SQLite
3.39.4
Versión de PDAL
2.4.3
Versión del cliente de PostgreSQL
unknown
Versión de SpatiaLite
5.0.1
Versión de QWT
6.1.6
Versión de QScintilla2
2.13.1
Versión del SO
Windows 10 Version 2009

Complementos activos de Python
DissolveWithStats
0.6
geometry_paster
0.2
mmqgis
2021.9.10
NNJoin
3.1.3
processing_saga_nextgen
0.0.7
QCopycanvas
0.7
QuickWKT
3.1
scriptrunner3
3.0.5
SemiAutomaticClassificationPlugin
7.10.11
Serval
3.10.5
shapetools
3.4.14
sigpac_downloader
0.4
SpreadsheetLayers
2.1.0
valuetool
3.0.17
db_manager
0.1.20
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by phidrho**
some users expect that `@row_number` variable respects what they currently see in attribute table so I'm proposing a better explanation for variable to make it clear

fix: #53536
fix: #54509

### CODE REVIEW

**Comment by mblesius** [comment]
Refs https://github.com/qgis/QGIS/issues/53536#issuecomment-2827002614

There are other places in QGIS where the `@row_number` variable is also available. It can be used when calculating param values and adding rows by expression. Here, `@row_number` actually returns the (internal) row number of the entries in the input table starting from 0. Thus, I would suggest to change the variable description, to make clear that (only?) for attribute tables, it will respect the order of features from the data source and not the current sort order in the attribute table.

row_number_batch_processing

**Comment by phidrho** [comment]
> Refs [#53536 (comment)](https://github.com/qgis/QGIS/issues/53536#issuecomment-2827002614)
> 
> There are other places in QGIS where the `@row_number` variable is also available. It can be used when calculating param values and adding rows by expression. Here, `@row_number` actually returns the (internal) row number of the entries in the input table starting from 0. Thus, I would suggest to change the variable description, to make clear that (only?) for attribute tables, it will respect the order of features from the data source and not the current sort order in the attribute table.


@mblesius
Thank you for your comment. Please check if new version is good.

**Comment by phidrho** [comment]
unstale

File: src/core/expression/qgsexpression.cpp [hunk 1]
```diff
@@ -851,7 +851,7 @@ void QgsExpression::initVariableHelp()
   sVariableHelpTexts()->insert( QStringLiteral( "zoom_level" ), QCoreApplication::translate( "variable_help", "Vector tile zoom level of the map that is being rendered (derived from the current map scale). Normally in interval [0, 20]." ) );
   sVariableHelpTexts()->insert( QStringLiteral( "vector_tile_zoom" ), QCoreApplication::translate( "variable_help", "Exact vector tile zoom level of the map that is being rendered (derived from the current map scale). Normally in interval [0, 20]. Unlike @zoom_level, this variable is a floating point value which can be used to interpolate values between two integer zoom levels." ) );
 
-  sVariableHelpTexts()->insert( QStringLiteral( "row_number" ), QCoreApplication::translate( "variable_help", "Stores the number of the current row." ) );
+  sVariableHelpTexts()->insert( QStringLiteral( "row_number" ), QCoreApplication::translate( "variable_help", "Stores the number of the current row. For attribute table data it's respecting order of features from data source. If used from attribute table field calculator index starts at 1, otherwise (e.g. from processing tools) index starts from 0." ) );
```
Comment (nyalldawson) [inline src/core/expression/qgsexpression.cpp]:
```suggestion
  sVariableHelpTexts()->insert( QStringLiteral( "row_number" ), QCoreApplication::translate( "variable_help", "Stores the number of the current row." ) + QStringLiteral( "\n\n" ) + QCoreApplication::translate( "variable_help", "When used for calculations within the attribute table the row number will respect the original order of features from the underlying data source." ) + QStringLiteral( "\n\n" ) + QCoreApplication::translate( "variable_help", "When used from the field calculator the row numbering starts at 1, otherwise (e.g. from Processing tools) the row numbering starts from 0." ) );
```

**Review by nyalldawson — APPROVED** [review]
