### PR TITLE
App: fix performance issues with projects with big number of layers

### LINKED ISSUE #49439: Loading and displaying CADRG/NITF data is slower than it used to be
### What is the bug or the crash?

Dragging and dropping a large number of CADRG frame files (basically NITF images) into QGIS 3.22.8 takes longer to load than in QGIS 2.18.16. For a very large number of images (~1000+), it takes far longer, to the point where it's uncertain whether QGIS will ever become responsive. I understand CADRG may not get much attention because it is a very outdated format, but it is still used heavily by certain, large organizations. And while there are better CADRG viewers such as FalconView, sometimes throwing frames into QGIS is much more convenient.

Side note in case this is related: QGIS 3.22.8 automatically expands many of the image entries in the layers panel when they are first loaded, showing an entry for each of the 216 colors of each image. I find this to be unnecessary; QGIS 2.18.16 does not automatically expand these layer entries.

### Steps to reproduce the issue

1. Unzip the attached cwdz02.zip which contains 186 CADRG frame files comprising US coverage.
2. Select all .wd2 files (frame files).
3. Drag and drop the files into QGIS.
4. Observe the difference in load time between QGIS 2.18.6 (~7 seconds for me) and QGIS 3.22.8 (~57 seconds for me).
5. Doing the above for a much larger dataset (which I cannot provide) scales up the time, causing a very long, unknown wait time.

### Versions

QGIS version
3.22.8-Białowieża
QGIS code revision
8d5e9761df
Qt version
6.15.3
Python version
3.9.5
GDAL/OGR version
3.5.0
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
7.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 1909

Active Python plugins
db_manager
0.1.20
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response
[cwdz02.zip](https://github.com/qgis/QGIS/files/9285310/cwdz02.zip)
_

### PR DESCRIPTION
**Pull request by rouault**
- fix performance issue when drag-dropping a lot of layers at once (fixes #49439)
- fix performance issue when closing a project with a lot of layer

### CODE REVIEW

File: src/app/qgisapp.cpp [hunk 1]
```diff
@@ -2106,6 +2106,13 @@ void QgisApp::dropEvent( QDropEvent *event )
   connect( timer, &QTimer::timeout, this, [this, timer, files, lst]
   {
     QgsCanvasRefreshBlocker refreshBlocker;
+    QgsTemporaryCursorOverride cursorOverride( Qt::WaitCursor );
+    qApp->processEvents();
```
Comment (nyalldawson) [inline src/app/qgisapp.cpp:2110]: Is this explicitly needed? There's a high risk of issues introduced by this.

Comment (rouault) [reply src/app/qgisapp.cpp:2110]: > Is this explicitly needed? There's a high risk of issues introduced by this.

not strictly needed but nice to have the busy cursor as dropping can be quite long. I'll remove it if it isn't safe (I believe I've seen that pattern else where in that file)
It would be nice to have a reliable way of setting the busy cursor and make sure it is well taken into account.

Comment (rouault) [reply src/app/qgisapp.cpp]: removed

Comment (nyalldawson) [reply src/app/qgisapp.cpp]: I was referring to the processEvents, not the cursor override. Did that require the processEvents to take effect?

Comment (rouault) [reply src/app/qgisapp.cpp]: > Did that require the processEvents to take effect?

yes, I tried without, but it had no effect

Comment (nyalldawson) [reply src/app/qgisapp.cpp]: Darn... still, better safe than sorry!

**Review by nyalldawson — APPROVED** [review]
