### PR TITLE
Fix merge features default value clause used as value

### LINKED ISSUE #50518: Button "Merge attributes of selected features" not working with gpkg-layers
### What is the bug or the crash?

QGIS seems not to handle the fid-fields in gpkg-files correctly when using the merge attributes button. QGIS merges the fid-field too althrough a unique fid / id of every row is required and should better be untouched by changing / merging the attribute values.

The warning "  Provider errors:  Changing feature id of feature .... is not allowed. " occurs when you try to save the changes of a gpkg-layer

### Steps to reproduce the issue

1) empty project -> create a new gpkg-layer (i.e. point layer) with some fields
2) digitize some points with (different) attributes
3) click "save layer edits"
4) select some features
5) click "Merge attributes of selected features"
6) select a row in feature-values-list of merge-attribues-dialog
7) click "Take attributes from selected feature"
8) click "save layer edits"
9) see warning

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.3-Buenos Aires | QGIS code revision | 65e4edfdada
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.1
PROJ version | 9.1.0
EPSG Registry database version | v10.074 (2022-08-01)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.38.1
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.26.3-Buenos Aires
QGIS code revision
[65e4edfdada](https://github.com/qgis/QGIS/commit/65e4edfdada)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### LINKED ISSUE #52726: Merge selected features fails if primary key column is generated always identity
### What is the bug or the crash?

Trying to merge lines in a Postgres table fails, if the table has a generated always identity as primary key.

With a table schema like this:
```
create table test(
    fid bigint generated always as identity primary key,
    geom geometry(LineString, 3877)
);
```

Merging two separate lines results in an error:
```
Ei voitu vahvistaa muutoksia tasolle test

Virheet: ERROR: 1 attributes and 1 geometries not changed.
  
Virheet tietolähteessä:
      PostGIS-virhe kun muutettiin attribuutteja: ERROR:  column "fid" can only be updated to DEFAULT
      DETAIL:  Column "fid" is an identity column defined as GENERATED ALWAYS.
```

This happens because QGIS tries to write into a column that can't be written into.
Generated always columns should never be modified in a query.

### Steps to reproduce the issue

1. Create table with a schema like mentioned above.
2. Create two separate lines and save modifications.
3. Select the two lines.
4. Use 'Merge selected features' tool, from the advanced digitizing tools.
5. Saving now fails, as QGIS tries to write a value to the `fid` column.

### Versions

QGIS version | 3.28.5-Firenze | QGIS code revision | 50adba36f2
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.3
PROJ version | 9.2.0
EPSG Registry database version | v10.082 (2023-02-06)
GEOS version | 3.11.2-CAPI-1.17.2
SQLite version | 3.41.1
PDAL version | 2.5.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
profiletool | 4.2.2
simplewcs | 0.2
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### LINKED ISSUE #52738: Merge selected features is broken and corrupts geometries
### What is the bug or the crash?

Merging selected features when using data coming from GeoPackages or PostGIS is broken with QGIS 3.28 and 3.30. This is probably also happening for other formats using a unique id field. Moreover it looks like the tool is corrupting the geometry of the "non-merged" features.

This works correctly with QGIS 3.22, hence a regression. This is also working correctly with shapefiles...

Probably related to https://github.com/qgis/QGIS/issues/50518

### Steps to reproduce the issue

1. Digitize 2 overlapping polygons, save everything and exit edit mode (or use the following GeoPackage: [testmerge.zip](https://github.com/qgis/QGIS/files/11250845/testmerge.zip)).
2. Activate edit mode, select the 2 polygons and merge them (Advanced Digitizing Toolbar -> Merge Selected Features).
3. Try to save the edits and get the following error message:
> Could not commit changes to layer testmerge
> 
> Errors: SUCCESS: 1 geometry was changed.
>   ERROR: 1 attribute value change not applied.
>   
>   Provider errors:
>       Changing feature id of feature 1 is not allowed.
5. Exit editing mode by discarding the changes.
6. The geometries seem to be corrupted. For example you can't select the second polygon by clicking on it (using the map tool). This will select the first polygon. However the selection is correct when using the attribute table.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.5-Firenze | QGIS code revision | 50adba36f2
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.3
PROJ version | 9.2.0
EPSG Registry database version | v10.082 (2023-02-06)
GEOS version | 3.11.2-CAPI-1.17.2
SQLite version | 3.41.1
PDAL version | 2.5.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
geometry_paster | 0.2
GroupStats | 2.2.7
kart | 1.0.10
qfieldsync | v4.4.9
qgis_geonode | 1.0.1
qgis_stac | 1.1.1
quick_map_services | 0.19.33
RasterAttributeTable | 1.2
swissgeodownloader | 2.0.1
swiss_locator | 2.0.6
VowaConservation | 1.1
VowaSwisstopoBasemapLV95 | 1.0.7
VowaSynthese | 1.1.12
VowaTmoFilter | 1.0.1
db_manager | 0.1.20
processing | 2.12.99

</body></html>QGIS version
3.28.5-Firenze
QGIS code revision
[50adba36f2](https://github.com/qgis/QGIS/commit/50adba36f2)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.3
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
geometry_paster
0.2
GroupStats
2.2.7
kart
1.0.10
qfieldsync
v4.4.9
qgis_geonode
1.0.1
qgis_stac
1.1.1
quick_map_services
0.19.33
RasterAttributeTable
1.2
swissgeodownloader
2.0.1
swiss_locator
2.0.6
VowaConservation
1.1
VowaSwisstopoBasemapLV95
1.0.7
VowaSynthese
1.1.12
VowaTmoFilter
1.0.1
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by domi4484**
During the move of merge logic to QgsVectorLayerEditUtils I changed the merge behavior so that the merge feature where always merged into an existing one.
This is causing problems for fields with default value clause, which is not calculated when the feature is already existing.
So would bring back the old behavior. When merging, create a new feature if no target feature was explicitly set with the buttons "Take attributes from selected feature" or "Take attributes from feature with the largest area/longest line".

Fix #52738
Fix #52726
Fix #50518

### CODE REVIEW

File: src/app/qgsmergeattributesdialog.cpp [hunk 1]
```diff
@@ -233,7 +233,13 @@ void QgsMergeAttributesDialog::createTableWidgetContents()
   {
     int idx = mTableWidget->horizontalHeaderItem( j )->data( FieldIndex ).toInt();
     bool setToManual = false;
-    if ( !mVectorLayer->dataProvider()->defaultValueClause( idx ).isEmpty() )
+
+    // For the Id use the target feature
+    if ( j == 0 )
```
Comment (m-kuhn) [inline src/app/qgsmergeattributesdialog.cpp:238]: Should this be based on the pk attribute indexes instead? https://github.com/domi4484/QGIS/blob/fixmergeid/src/app/qgsmergeattributesdialog.cpp#L183-L184

**Review by m-kuhn — APPROVED** [review]
Thank you, that looks cleaner than before and has been heavily tested by @andreasneumann for various cases

**Comment by jguelat** [comment]
Thanks a lot! Would it be possible to backport this fix to version 3.28?
