### PR TITLE
Fix layout raster renderer when statistics extent set to "Updated Canvas"

### LINKED ISSUE #52743: Raster legend in the print layout does not update its range of values when the map canvas extent is changed
### What is the bug or the crash?

Right after loading a new raster layer with default "Single band gray" symbology, when I change the "statistics extent" setting from the default "Whole raster" to "Updated canvas", the raster legend on the print layout correctly updates the dynamic range of raster values as the map canvas extent changes. 
However, when I choose a raster symbology with a "Single band pseudocolor" palette and change the "statistics extent" setting from the default "Whole raster" to "Updated canvas", the raster legend on the print layout no longer updates the range of raster values as the map canvas extent changes. Subsequently changing the symbology back to "Single band gray" does not resolve this issue.

The similar error has been described on [gis.stackexchange](https://gis.stackexchange.com/questions/456979/qgis-atlas-dynamic-classification-legend-for-raster-values-based-on-extent-of)

https://user-images.githubusercontent.com/28803643/232594139-1abe776b-89ff-4089-8009-8a2053960484.mp4

### Steps to reproduce the issue

1. Download a sample DEM raster from https://srtm.csi.cgiar.org/wp-content/uploads/files/srtm_5x5/TIFF/srtm_39_03.zip.  [37 MB]
2. In QGIS, change its symbology to "Single band pseudocolor" and set the "statistics extent" from the default "Whole raster" to "Updated canvas". 
3. Create a print layout, insert a map frame and its legend. 
4. Move the map canvas extent using the "move item content" option. You will notice that the range of raster values in the legend does not change as the map canvas extent changes.

### Versions

QGIS version
3.28.5-Firenze
QGIS code revision
50adba36f2
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.3
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JanCaha**
## Description

Fixes issue where if raster layer has renderer with statistics extent set to "Updated Canvas" its legend in layout does not get updated according the extent of linked layout map (instead it was updated only on changes of extent in main canvas).

The fix also includes the same changes for mesh layers.

Fixes #52743 

Peek 2025-11-05 16-23

Funded by: Ocean Winds

### CODE REVIEW

**Comment by JanCaha** [comment]
@nyalldawson Would mind taking a look if this is the right way to fix this? 

I will add some tests for this, once the approach is considered fine.

**Comment by elpaso** [comment]
@JanCaha would you please use more descriptive titles for your PRs? Something like `Fix layout raster renderer when statistics extent set to "Updated Canvas"` would do. 
This will help reviewers.

File: src/core/layout/qgslayoutitemlegend.cpp [hunk 1]
```diff
@@ -1484,6 +1493,85 @@ bool QgsLayoutItemLegend::isRefreshing() const
 }
 
 
+void QgsLayoutItemLegend::syncLayersWithUpdatedCanvasMinimumMaximum()
+{
+
+  if ( mCustomLayerTree )
```
Comment (nyalldawson) [inline src/core/layout/qgslayoutitemlegend.cpp]: I think we also want to handle this situation - if a user has modified the layers shown they'll still want the legends for those layers to be accurately reflected.

File: src/core/layout/qgslayoutitemlegend.cpp [hunk 2]
```diff
@@ -1484,6 +1493,85 @@ bool QgsLayoutItemLegend::isRefreshing() const
...
+
+  QgsLayerTreeGroup *root = model->rootGroup();
+  if ( !root )
+    return;
+
+  const QList<QgsLayerTreeLayer *> layers = root->findLayers();
+
+  for ( QgsLayerTreeLayer *layerTreeLayer : layers )
+  {
+    QgsMapLayer *mapLayer = layerTreeLayer->layer();
```
Comment (nyalldawson) [inline src/core/layout/qgslayoutitemlegend.cpp:1499]:
```suggestion
    QgsMapLayer *mapLayer = layerTreeLayer->layer();
    if ( !mapLayer || !mapLayer->isValid() )
       continue;
```

File: src/core/layout/qgslayoutitemlegend.cpp [hunk 3]
```diff
@@ -1484,6 +1493,85 @@ bool QgsLayoutItemLegend::isRefreshing() const
...
+      {
+        rasterLayer->computeMinMax( renderer->inputBand(), minMaxOrigin, minMaxOrigin.limits(),
+                                    mMap->extent(), static_cast<int>( QgsRasterLayer::SAMPLE_SIZE ),
+                                    min, max );
+
+        found = !( std::isnan( min ) && std::isnan( max ) );
+      }
+    }
+
+    if ( QgsMeshLayer *meshLayer = qobject_cast<QgsMeshLayer *>( mapLayer ) )
```
Comment (nyalldawson) [inline src/core/layout/qgslayoutitemlegend.cpp]:
```suggestion
    else if ( QgsMeshLayer *meshLayer = qobject_cast<QgsMeshLayer *>( mapLayer ) )
```

File: src/core/layout/qgslayoutitemlegend.cpp [hunk 4]
```diff
@@ -1484,6 +1493,85 @@ bool QgsLayoutItemLegend::isRefreshing() const
...
+    {
+      QgsRenderContext renderContext = QgsLayoutUtils::createRenderContextForMap( mMap, nullptr );
```
Comment (nyalldawson) [inline src/core/layout/qgslayoutitemlegend.cpp]: This is an expensive operation, we should only do it once, outside of the layer loop

File: src/core/layout/qgslayoutitemlegend.cpp [hunk 5]
```diff
@@ -1484,6 +1493,85 @@ bool QgsLayoutItemLegend::isRefreshing() const
...
+    double max = std::numeric_limits<double>::quiet_NaN();
+    bool found = false;
+
+    if ( QgsRasterLayer *rasterLayer = qobject_cast<QgsRasterLayer *>( mapLayer ) )
+    {
+      QgsRasterRenderer *renderer = rasterLayer->renderer();
+
+      QgsRasterMinMaxOrigin minMaxOrigin = renderer->minMaxOrigin();
+
+      if ( minMaxOrigin.extent() == Qgis::RasterRangeExtent::UpdatedCanvas )
```
Comment (nyalldawson) [inline src/core/layout/qgslayoutitemlegend.cpp]: use switch here, so we get a warning if new extent types are added which we need to handle

File: src/core/layout/qgslayoutitemlegend.cpp [hunk 6]
```diff
@@ -1484,6 +1493,85 @@ bool QgsLayoutItemLegend::isRefreshing() const
...
+    {
+      QgsRenderContext renderContext = QgsLayoutUtils::createRenderContextForMap( mMap, nullptr );
+
+      const QgsMeshDatasetIndex activeDatasetIndex = meshLayer->activeScalarDatasetIndex( renderContext );
+
+      if ( activeDatasetIndex.isValid() )
+      {
+        QgsMeshRendererScalarSettings scalarRendererSettings = meshLayer->rendererSettings().scalarSettings( activeDatasetIndex.group() );
+
+        if ( scalarRendererSettings.extent() == Qgis::MeshRangeExtent::UpdatedCanvas &&
```
Comment (nyalldawson) [inline src/core/layout/qgslayoutitemlegend.cpp]: use switch here, so we get a warning if new extent types are added which we need to handle

File: src/core/layout/qgslayoutitemlegend.cpp [hunk 7]
```diff
@@ -1484,6 +1493,85 @@ bool QgsLayoutItemLegend::isRefreshing() const
...
+
+  QgsLegendModel *model = this->model();
+  if ( !model )
+    return;
+
+  QgsLayerTreeGroup *root = model->rootGroup();
+  if ( !root )
+    return;
+
+  const QList<QgsLayerTreeLayer *> layers = root->findLayers();
```
Comment (nyalldawson) [inline src/core/layout/qgslayoutitemlegend.cpp]: Can you move all this logic to a function in QgsLayerTreeUtils ? I think it potentially has use outside of the layout items.

**Comment by nyalldawson** [comment]
@JanCaha what's the performance on this like? It's running on the main thread in a blocking way, so does it cause hangs when interacting with the layout in the designer? (eg zoom in/out, changing the map scale).

**Comment by nyalldawson** [comment]
Actually - on second thoughts, I think this logic belongs in QgsMapHitTest, so that we never run it on the main thread and the existing background-thread handling used by QgsMapHitTest can be taken advantage of.

**Comment by uclaros** [comment]
> Actually - on second thoughts, I think this logic belongs in QgsMapHitTest, so that we never run it on the main thread and the existing background-thread handling used by QgsMapHitTest can be taken advantage of.

@nyalldawson I am wondering if we really do need to re-calculate those min/maxes. Is there any good reason not to store them in the `QgsLayoutItemMap` when the rendering job finishes, so that the `QgsLayoutItemLegend` can read them from it?
This would be kind of the equivalent of how the main map canvas/main legend works.

**Comment by nyalldawson** [comment]
@uclaros 
> I am wondering if we really do need to re-calculate those min/maxes. Is there any good reason not to store them in the QgsLayoutItemMap when the rendering job finishes, so that the QgsLayoutItemLegend can read them from it?
This would be kind of the equivalent of how the main map canvas/main legend works.

We don't have any control over the rendering order of layout items -- that's dictated by the z order of the items (for exports), and some internal qt logic when in the graphics view. It'd take a fairly large chunk of re-plumbing to handle this.

**Comment by uclaros** [comment]
@nyalldawson 

> We don't have any control over the rendering order of layout items -- that's dictated by the z order of the items (for exports), and some internal qt logic when in the graphics view. It'd take a fairly large chunk of re-plumbing to handle this.

So the problem would be when exporting? Because for preview rendering the legend could be notified by some `mapFinishedRendering` signal and refresh itself.

**Comment by JanCaha** [comment]
@nyalldawson I looked into the suggested **QgsMapHitTest** class. It focuses on the vector data and it is quite focused on symbols and other rendering stuff. I do not think adding the logic related to rasters and rasters min max values would be a good idea. 

Would it be ok to create new class and new QgsTask (based roughly of **QgsMapHitTest**) to handle the process that we have here?

**Comment by nyalldawson** [comment]
@JanCaha 
> I looked into the suggested QgsMapHitTest class. It focuses on the vector data and it is quite focused on symbols and other rendering stuff. I do not think adding the logic related to rasters and rasters min max values would be a good idea.
> Would it be ok to create new class and new QgsTask (based roughly of QgsMapHitTest) to handle the process that we have here?

I don't think there's any reason why that class needs to remain vector specific, and there's LOTS of reasons why we'd want to do very similar hit tests for non-vector legend items. I'm thinking things like a land use raster set to paletted renderer, hiding pixel classes which aren't actually visible on within the map extent. (Or similar for classified point clouds). 

The big benefit of putting the new logic in QgsMapHitTest is that we don't need to add additional complexity with threading -- all the existing logic in the layout legend which handles non-main thread updates would just work. I think trying to add additional tasks/background threaded operations to the layout legend class would result in a considerable chunk of added complexity, and that would only grow exponentially in future if we had to add even more map->legend filtering/statistical operations.

**Comment by JanCaha** [comment]
@wonder-sk Could you take a look at the **QgsMapHitTest**, it should follow the logic that we discussed. The only slightly problematic part might be that there is a need to recreate Mesh Layers when running from different thread, as quite a lot of MeshLayer logic is marked to be only run from main thread and the calculation cannot be simply moved from layer to the datasource like in Raster Layer case.

File: src/core/layout/qgslayoutitemlegend.cpp [hunk 8]
```diff
@@ -1573,3 +1576,39 @@ void QgsLegendModel::forceRefresh()
...
+
+  for ( QgsLayerTreeLayer *layerTreeLayer : layers )
+  {
+    QgsMapLayer *mapLayer = layerTreeLayer->layer();
+
+    if ( !mapLayer || !mapLayer->isValid() )
+      continue;
+    if ( QgsRasterLayer *rl = qobject_cast<QgsRasterLayer *>( mapLayer ) )
+    {
+      if ( rl->renderer()->minMaxOrigin().extent() == Qgis::RasterRangeExtent::UpdatedCanvas )
```
Comment (nyalldawson) [inline src/core/layout/qgslayoutitemlegend.cpp]: Let's play it safe:

```suggestion
      if ( rl->renderer() && rl->renderer()->minMaxOrigin().extent() == Qgis::RasterRangeExtent::UpdatedCanvas )
```

File: src/core/layout/qgslayoutitemlegend.h [hunk 9]
```diff
@@ -71,6 +71,13 @@ class CORE_EXPORT QgsLegendModel : public QgsLayerTreeModel
      */
     void clearCachedData( QgsLayerTreeNode *node ) const;
 
+    /**
+     * Determines whether the legend requires filtering because of renderer settings (UpdatedCanvas on raster or mesh layers).
+     *
+     * \since QGIS 4.0
+     */
+    bool requiresFilteringBecauseOfRendererSetting();
```
Comment (nyalldawson) [inline src/core/layout/qgslayoutitemlegend.h]: Can we make this method private?

File: src/core/qgsmaphittest.h [hunk 10]
```diff
@@ -88,6 +93,38 @@ class CORE_EXPORT QgsMapHitTest
...
+
+
+#ifdef SIP_RUN
+    /**
+     * Returns the hit test results, for layers with UpdatedCanvas renderers (raster/mesh layers).
+     * Results are given as QMap of layer IDs to pairs of (min, max) values.
+     *
+     * \since QGIS 4.0
+     */
+    SIP_PYOBJECT resultsRenderersUpdatedCanvasPy() const SIP_PYNAME( resultsRenderersUpdatedCanvas );
```
Comment (nyalldawson) [inline src/core/qgsmaphittest.h]: Can you add SIP_TYPEHINT here too, so that the PyQGIS docs get the proper return type?

File: src/core/raster/qgsrasterlayerutils.cpp [hunk 11]
```diff
@@ -169,3 +171,106 @@ int QgsRasterLayerUtils::renderedBandForElevationAndTemporalRange(
   }
   BUILTIN_UNREACHABLE;
 }
+
+void QgsRasterLayerUtils::computeMinMax( QgsRasterDataProvider *provider,
```
Comment (nyalldawson) [inline src/core/raster/qgsrasterlayerutils.cpp:177]: For review purposes, is this just a 1:1 move of the existing function?

File: src/core/raster/qgsrasterlayerutils.cpp [hunk 12]
```diff
@@ -169,3 +171,106 @@ int QgsRasterLayerUtils::renderedBandForElevationAndTemporalRange(
...
+    int sampleSize,
+    double &min SIP_OUT,
+    double &max SIP_OUT )
+{
+  min = std::numeric_limits<double>::quiet_NaN();
+  max = std::numeric_limits<double>::quiet_NaN();
+  if ( !provider )
+    return;
+
+  if ( limits == Qgis::RasterRangeLimit::MinimumMaximum )
```
Comment (nyalldawson) [inline src/core/raster/qgsrasterlayerutils.cpp:194]: a switch would be preferable here

File: src/core/qgsmaphittest.cpp [hunk 13]
```diff
@@ -60,40 +63,71 @@ void QgsMapHitTest::run()
   QgsRenderContext context = QgsRenderContext::fromMapSettings( mapSettings );
   context.setPainter( &painter ); // we are not going to draw anything, but we still need a working painter
 
+  QgsRenderContext contextVectorLayers = context;
```
Comment (nyalldawson) [inline src/core/qgsmaphittest.cpp]: Why do we need this copy here?

File: src/core/qgsmaphittest.cpp [hunk 14]
```diff
@@ -60,40 +63,71 @@ void QgsMapHitTest::run()
...
-      context.setExtent( extent.boundingBox() );
+      auto source = std::make_unique< QgsVectorLayerFeatureSource >( vl );
+      runHitTestFeatureSource( source.get(),
+                               vl->id(), vl->fields(), vl->renderer(),
+                               usedSymbols, usedSymbolsRuleKey, contextVectorLayers,
+                               nullptr, extent );
     }
+    else if ( QgsRasterLayer *rl = qobject_cast<QgsRasterLayer *>( layer ) )
+    {
+      if ( !rl || !rl->renderer() )
```
Comment (nyalldawson) [inline src/core/qgsmaphittest.cpp]:
```suggestion
      if ( !rl || !rl->renderer() || !rl->dataProvider() )
```

File: src/core/qgsmaphittest.cpp [hunk 15]
```diff
@@ -286,6 +320,93 @@ void QgsMapHitTest::runHitTestFeatureSource( QgsAbstractFeatureSource *source,
...
+
+  double min = std::numeric_limits<double>::quiet_NaN();
+  double max = std::numeric_limits<double>::quiet_NaN();
+  bool found = false;
+
+  switch ( minMaxOrigin.extent() )
+  {
+    case Qgis::RasterRangeExtent::UpdatedCanvas:
+    {
+      QgsRectangle transformedExtent = transform.transform( context.extent() );
```
Comment (nyalldawson) [inline src/core/qgsmaphittest.cpp]:
```suggestion
      QgsRectangle transformedExtent = transform.transformBoundingBox( context.extent() );
```

Comment (nyalldawson) [inline src/core/qgsmaphittest.cpp]: catch QgsCsException too!

File: src/core/qgsmaphittest.cpp [hunk 16]
```diff
@@ -286,6 +320,93 @@ void QgsMapHitTest::runHitTestFeatureSource( QgsAbstractFeatureSource *source,
...
+  {
+    switch ( rangeExtent )
+    {
+      case Qgis::MeshRangeExtent::UpdatedCanvas:
+      {
+        switch ( rangeLimit )
+        {
+          case Qgis::MeshRangeLimit::MinimumMaximum:
+          {
+            QgsRectangle transformedExtent = transform.transform( context.extent() );
```
Comment (nyalldawson) [inline src/core/qgsmaphittest.cpp]: as above

**Comment by nyalldawson** [comment]
@JanCaha the new approach is looking great to me!

Can you also add a unit test for the layout legend rendering when the updated canvas setting is in effect too?

File: src/core/raster/qgsrasterlayerutils.cpp (hunk 11 above)
Comment (JanCaha) [reply src/core/raster/qgsrasterlayerutils.cpp:177]: Yes. This is just move of the function to avoid **QGIS_PROTECT_QOBJECT_THREAD_ACCESS** that exist in **QgsRasterLayer** .

File: src/core/raster/qgsrasterlayerutils.cpp (hunk 12 above)
Comment (JanCaha) [reply src/core/raster/qgsrasterlayerutils.cpp:194]: Since this was just a move of code I did not want to change things, do we want to update the code? No problem in doing so.

File: src/core/layout/qgslayoutitemlegend.h (hunk 9 above)
Comment (JanCaha) [reply src/core/layout/qgslayoutitemlegend.h]: Had to move the implementation to another class, but no problem, can be private.

File: src/core/qgsmaphittest.cpp (hunk 13 above)
Comment (JanCaha) [reply src/core/qgsmaphittest.cpp]: few lines below that the extent is modified for vector layers by visible extent of `vl` (code below). But for raster and mesh layers the original context extent is need. I could save just the context extent and reapply it for raster and mesh layers if the `QgsRenderContext` is too heavy for a copy here.

```
 extent = mSettings.combinedVisibleExtentForLayer( vl );
 contextVectorLayers.setCoordinateTransform( mapSettings.layerTransform( vl ) );
 contextVectorLayers.setExtent( extent.boundingBox() );
```

**Comment by JanCaha** [comment]
@nyalldawson  updated, test added. Some minorities to discuss.

Looking at the amount of new code, this probably does not qualify as bug fix right? Even though originally started as one ...

File: src/core/raster/qgsrasterlayerutils.cpp (hunk 11 above)
Comment (nyalldawson) [reply src/core/raster/qgsrasterlayerutils.cpp:177]: Hmm.... why is that getting tripped? Removing it seems like we're hiding an issue rather then fixing it.

Comment (JanCaha) [reply src/core/raster/qgsrasterlayerutils.cpp:177]: Well most of the layer's function will trip that. The move is so that the `minMax()` can be called on cloned data provider from another thread.

Comment (nyalldawson) [reply src/core/raster/qgsrasterlayerutils.cpp:177]: Ah, if that's getting tripped on a clone made to run explicitly in a different thread then you're probably missing some logic. From the prepare step in the main thread you need to call `moveToThread( nullptr )` on the clone, then from the worker thread call `moveToThread( QThread:: currentThread() )`

(Qt logic is you can't "pull" an object from another thread unless you've first detached the object from all threads)

Comment (JanCaha) [reply src/core/raster/qgsrasterlayerutils.cpp:177]: Ok, that would be another possible solution. 

We discuss this with @wonder-sk  and he suggested that since that logic only uses `RasterDataProvider` it should be ok to clone the `RasterDataProvider` and call the `minMax() ` function without accessing the layer directly.

If what you suggest is preferable, I can use that logic. In fact I probably will for `MeshLayer` as it will simplify the code by a lot.

Comment (nyalldawson) [reply src/core/raster/qgsrasterlayerutils.cpp:177]: I'm ok to leave it using the data provider alone.

Can you add:

   QGIS_CHECK_QOBJECT_THREAD_EQUALITY( provider );

here then? That'll re-introduce the thread safety check and assert that the current thread matches the data provider's thread.

Comment (JanCaha) [reply src/core/raster/qgsrasterlayerutils.cpp:177]: I can quite put that here, this a static function and it does not work with the QGIS_CHECK_QOBJECT_THREAD_EQUALITY. This check could be placed in `QgsMapHitTestTask` to verify that we have same thread for `RasterDataProvider` and `QgsTask`

**Comment by JanCaha** [comment]
@nyalldawson Would you have any idea, why the tests might fail? Locally it runs just fine. I would not expect them to run for that long (it kind of looks like they fail due to long run time).

File: src/core/qgsmaphittest.cpp [hunk 17]
```diff
@@ -411,10 +588,70 @@ bool QgsMapHitTestTask::run()
...
 
+  // data moved to the task thread above need to explicitly emptied here
+  // otherwise destructors run in the main thread may comply
+  // raster data
+  for ( auto &rasterData : mPreparedRasterData )
+  {
+    rasterData.provider.reset();
+  }
+  // mesh data
+  for ( auto &meshData : mPreparedMeshData )
```
Comment (uclaros) [inline src/core/qgsmaphittest.cpp]:
```suggestion
  for ( PreparedRasterData &rasterData : mPreparedRasterData )
  {
    rasterData.provider.reset();
  }
  // mesh data
  for ( PreparedMeshData &meshData : mPreparedMeshData )
```

Or maybe actually, do we need to keep these entries?
Couldn't we just:
```cpp
mPreparedMeshData.clear();
mPreparedRasterData.clear();
```
?

File: src/core/qgsmaphittest.cpp [hunk 18]
```diff
@@ -411,10 +588,70 @@ bool QgsMapHitTestTask::run()
...
+                                     rasterData.minMaxOrigin,
+                                     rasterData.rangeLimit,
+                                     context,
+                                     mFeedback.get(),
+                                     rasterData.extent );
+    layerIdx++;
+  }
+
+  layerIdx = 0;
+  for ( auto &meshData : mPreparedMeshData )
```
Comment (uclaros) [inline src/core/qgsmaphittest.cpp]:
```suggestion
  for ( PreparedMeshData &meshData : mPreparedMeshData )
```

File: src/core/qgsmaphittest.cpp [hunk 19]
```diff
@@ -411,10 +588,70 @@ bool QgsMapHitTestTask::run()
     layerIdx++;
   }
 
+  layerIdx = 0;
+  for ( auto &rasterData : mPreparedRasterData )
```
Comment (uclaros) [inline src/core/qgsmaphittest.cpp]:
```suggestion
  for ( PreparedRasterData &rasterData : mPreparedRasterData )
```

File: src/core/qgsmaphittest.cpp [hunk 20]
```diff
@@ -321,37 +456,78 @@ void QgsMapHitTestTask::prepare()
...
+      rasterData.transform = mapSettings.layerTransform( rl );
+      rasterData.extent = extent;
 
-    mPreparedData.emplace_back( std::move( layerData ) );
+      mPreparedRasterData.emplace_back( std::move( rasterData ) );
+    }
+    else if ( QgsMeshLayer *ml = qobject_cast<QgsMeshLayer *>( layer ) )
+    {
+      if ( !ml )
+        continue;
```
Comment (uclaros) [inline src/core/qgsmaphittest.cpp]: This is redundant, same as `!rl` and `!vl` above.
```suggestion
```

File: src/core/qgsmaphittest.cpp [hunk 21]
```diff
@@ -64,37 +67,64 @@ void QgsMapHitTest::run()
...
+
+      QgsCoordinateTransform transform = QgsCoordinateTransform( mapSettings.destinationCrs(), rl->crs(), mapSettings.transformContext() );
+
+      runHitTestRasterSource( rl->dataProvider(), rl->id(), rl->renderer()->inputBand(), minMaxOrigin, minMaxOrigin.limits(),
+                              context, nullptr, extent );
+    }
+    else if ( QgsMeshLayer *ml = qobject_cast<QgsMeshLayer *>( layer ) )
+    {
+      if ( !ml )
+        continue;
```
Comment (uclaros) [inline src/core/qgsmaphittest.cpp]:
```suggestion
```
This is redundant, same as `!rl` and `!vl` checks above

File: src/core/qgsmaphittest.h [hunk 22]
```diff
@@ -135,6 +172,43 @@ class CORE_EXPORT QgsMapHitTest
...
+     * \param feedback optional feedback argument for cancel support
+     * \param visibleExtent total visible area of layer
+     * \note not available in Python bindings
+     */
+    void runHitTestRasterSource( QgsRasterDataProvider *provider,
+                                 const QString &layerId,
+                                 const int band,
+                                 const QgsRasterMinMaxOrigin minMaxOrigin,
+                                 const Qgis::RasterRangeLimit rangeLimit,
+                                 QgsRenderContext &context,
```
Comment (uclaros) [inline src/core/qgsmaphittest.h]:
```suggestion
                                 const QgsRenderContext &context,
```
Can we use const ref here?

File: src/core/qgsmaphittest.h [hunk 23]
```diff
@@ -135,6 +172,43 @@ class CORE_EXPORT QgsMapHitTest
...
+     * \param datasetIndex dataset index within the mesh layer
+     * \param context render context
+     * \param feedback optional feedback argument for cancel support
+     * \param visibleExtent total visible area of layer
+     * \note not available in Python bindings
+     */
+    void runHitTestMeshSource( QgsMeshLayer *layer,
+                               const QString &layerId,
+                               const QgsMeshDatasetIndex datasetIndex,
+                               QgsRenderContext &context,
```
Comment (uclaros) [inline src/core/qgsmaphittest.h]:
```suggestion
                               const QgsRenderContext &context,
```
and here?

**Review by uclaros — COMMENTED** [review]
Some last minor comments.

File: src/core/qgsmaphittest.h [hunk 24]
```diff
@@ -135,6 +172,43 @@ class CORE_EXPORT QgsMapHitTest
...
+    /**
+     * Runs test for minimum and maximum value for a raster data provider
+     * \param provider raster data provider
+     * \param layerId associated layer id
+     * \param band raster band to calculate min/max on
+     * \param minMaxOrigin min/max origin settings
+     * \param rangeLimit range limit settings
+     * \param context render context
+     * \param feedback optional feedback argument for cancel support
+     * \param visibleExtent total visible area of layer
```
Comment (uclaros) [inline src/core/qgsmaphittest.h]: This is in layer CRS, right? It's worth adding here

File: src/core/qgsmaphittest.h [hunk 25]
```diff
@@ -135,6 +172,43 @@ class CORE_EXPORT QgsMapHitTest
...
+                                 const QgsGeometry &visibleExtent );
+
+    /**
+     * Runs test for visible symbols from a mesh layer
+     * \param layer mesh layer
+     * \param layerId associated layer id
+     * \param datasetIndex dataset index within the mesh layer
+     * \param context render context
+     * \param feedback optional feedback argument for cancel support
+     * \param visibleExtent total visible area of layer
```
Comment (uclaros) [inline src/core/qgsmaphittest.h]: same

File: src/core/qgsmaphittest.cpp [hunk 26]
```diff
@@ -64,37 +67,64 @@ void QgsMapHitTest::run()
...
+                               nullptr, extent );
+    }
+    else if ( QgsRasterLayer *rl = qobject_cast<QgsRasterLayer *>( layer ) )
+    {
+      if ( !rl || !rl->renderer() || !rl->dataProvider() )
+        continue;
+
+      QgsRasterMinMaxOrigin minMaxOrigin = rl->renderer()->minMaxOrigin();
+
+      QgsCoordinateTransform transform = QgsCoordinateTransform( mapSettings.destinationCrs(), rl->crs(), mapSettings.transformContext() );
```
Comment (uclaros) [inline src/core/qgsmaphittest.cpp]: This looks unused, is it a leftover?

File: src/core/qgsmaphittest.cpp [hunk 27]
```diff
@@ -64,37 +67,64 @@ void QgsMapHitTest::run()
...
+
+      runHitTestRasterSource( rl->dataProvider(), rl->id(), rl->renderer()->inputBand(), minMaxOrigin, minMaxOrigin.limits(),
+                              context, nullptr, extent );
+    }
+    else if ( QgsMeshLayer *ml = qobject_cast<QgsMeshLayer *>( layer ) )
+    {
+      if ( !ml )
+        continue;
+
+      QgsCoordinateTransform transform = QgsCoordinateTransform( mapSettings.destinationCrs(), ml->crs(), mapSettings.transformContext() );
```
Comment (uclaros) [inline src/core/qgsmaphittest.cpp]: Same here

File: src/core/qgsmaphittest.cpp (hunk 17 above)
Comment (JanCaha) [reply src/core/qgsmaphittest.cpp]: Actually we can do that...good point, I was so focused on getting to the bottom of the error, that I did not realize that it is not necessary to manually reset those pointers ... :smile:

File: src/core/raster/qgsrasterlayerutils.cpp [hunk 28]
```diff
@@ -170,3 +173,106 @@ int QgsRasterLayerUtils::renderedBandForElevationAndTemporalRange(
...
+    const QgsRectangle &extent,
+    int sampleSize,
+    double &min SIP_OUT,
+    double &max SIP_OUT )
+{
+  min = std::numeric_limits<double>::quiet_NaN();
+  max = std::numeric_limits<double>::quiet_NaN();
+  if ( !provider )
+    return;
+
```
Comment (nyalldawson) [inline src/core/raster/qgsrasterlayerutils.cpp]: Does this work?

```suggestion
  QGIS_CHECK_OTHER_QOBJECT_THREAD_ACCESS( provider );
```

**Comment by nyalldawson** [comment]
Just one remaining change from me, and then this branch will need to be rebased and the current version of pre-commit run over it again.

**Comment by JanCaha** [comment]
@nyalldawson Included the line and rebased. Once the tests run, it is should be finally all good for merge :smile:

**Review by uclaros — APPROVED** [review]
🎉

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
Thanks @JanCaha !
