### PR TITLE
Prevent calling findLayers when there is no legend->rootGroup (fix #57595)

### LINKED ISSUE #57595: GetPrint segmentation fault with map following map theme and legend
### What is the bug or the crash?

If there is a print composition with a map following a map theme and its legend, qgis_mapserv.fcgi aborts with Segmentation fault.

[getprint.zip](https://github.com/qgis/QGIS/files/15475718/getprint.zip)

### Steps to reproduce the issue

1. Create a map theme
1. Create a print composition
1. Add a map and map follow map theme
1. Add legend and select the previous map
1. Make a GetPrint request

With the attached project `legend` (stored inside the `getprint.gpkg`), the `GetPrint` can be called with:

Set environment variables:

```bash
export QGIS_PROJECT_FILE="geopackage:/tmp/getprint.gpkg?projectName=legend"
export QUERY_STRING="SERVICE=WMS&VERSION=1.3.0&REQUEST=GetPrint&FORMAT=pdf&TRANSPARENT=true&TEMPLATE=White layout&DPI=400&CRS=EPSG:3763&map0:extent=-38717,121347,-38356,121559"
```

Run QGIS Server using current master:
```bash
/usr/local/bin/qgis_mapserv.fcgi
```

Run QGIS Server using development version:
```bash
./output/bin/qgis_mapserv.fcgi
```

### Versions

Current master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

The backtrace, from `gdb` is:

```gdb
Thread 1 "qgis_mapserv.fc" received signal SIGSEGV, Segmentation fault.
0x00007ffff7e2628e in QListData::begin (this=0x20) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h:118
118         inline void **begin() const noexcept { return d->array + d->begin; }
(gdb) backtrace 
#0  0x00007ffff7e2628e in QListData::begin() const (this=0x20) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h:118
#1  0x00007ffff4bc1a8e in QList<QgsLayerTreeNode*>::begin() const (this=0x20) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h:339
#2  0x00007ffff4bbdc57 in QgsLayerTreeGroup::findLayers() const (this=0x0) at /home/jgr/dev/cpp/QGIS/src/core/layertree/qgslayertreegroup.cpp:253
#3  0x00007ffff588d96e in QgsLayoutItemLegend::setModelStyleOverrides(QMap<QString, QString> const&) (this=0x555556fafc20, overrides=...)
    at /home/jgr/dev/cpp/QGIS/src/core/layout/qgslayoutitemlegend.cpp:1019
#4  0x00007ffff588dcd1 in QgsLayoutItemLegend::mapLayerStyleOverridesChanged() (this=0x555556fafc20) at /home/jgr/dev/cpp/QGIS/src/core/layout/qgslayoutitemlegend.cpp:1062
#5  0x00007ffff5896977 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (QgsLayoutItemLegend::*)()>::call(void (QgsLayoutItemLegend::*)(), QgsLayoutItemLegend*, void**) (f=(void (QgsLayoutItemLegend::*)(QgsLayoutItemLegend * const)) 0x7ffff588dc4e <QgsLayoutItemLegend::mapLayerStyleOverridesChanged()>, o=0x555556fafc20, arg=0x7fffffffc980)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:152
#6  0x00007ffff589636e in QtPrivate::FunctionPointer<void (QgsLayoutItemLegend::*)()>::call<QtPrivate::List<>, void>(void (QgsLayoutItemLegend::*)(), QgsLayoutItemLegend*, void**)
    (f=(void (QgsLayoutItemLegend::*)(QgsLayoutItemLegend * const)) 0x7ffff588dc4e <QgsLayoutItemLegend::mapLayerStyleOverridesChanged()>, o=0x555556fafc20, arg=0x7fffffffc980)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:185
#7  0x00007ffff58958af in QtPrivate::QSlotObject<void (QgsLayoutItemLegend::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*)
    (which=1, this_=0x555556bdbfb0, r=0x555556fafc20, a=0x7fffffffc980, ret=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:418
#8  0x00007ffff3af1793 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007ffff47d09c5 in QgsLayoutItemMap::layerStyleOverridesChanged() (this=0x555556d3fa20) at /home/jgr/dev/cpp/build-qgis/src/core/qgis_core_autogen/TMD3PGXO7W/moc_qgslayoutitemmap.cpp:540
#10 0x00007ffff589fed0 in QgsLayoutItemMap::setLayerStyleOverrides(QMap<QString, QString> const&) (this=0x555556d3fa20, overrides=...)
    at /home/jgr/dev/cpp/QGIS/src/core/layout/qgslayoutitemmap.cpp:373
#11 0x00007fffcad612b0 in QgsWms::QgsRenderer::configurePrintLayout(QgsPrintLayout*, QgsMapSettings const&, QgsLayoutAtlas*) (this=0x7fffffffd2a0, c=0x555556ee22c0, mapSettings=..., atlas=0x0)
    at /home/jgr/dev/cpp/QGIS/src/server/services/wms/qgswmsrenderer.cpp:892
#12 0x00007fffcad5e921 in QgsWms::QgsRenderer::getPrint() (this=0x7fffffffd2a0) at /home/jgr/dev/cpp/QGIS/src/server/services/wms/qgswmsrenderer.cpp:523
#13 0x00007fffcad507e8 in QgsWms::writeGetPrint(QgsServerInterface*, QgsProject const*, QgsWms::QgsWmsRequest const&, QgsServerResponse&)
--Type <RET> for more, q to quit, c to continue without paging--c
    st=..., response=...) at /home/jgr/dev/cpp/QGIS/src/server/services/wms/qgswmsgetprint.cpp:74
#14 0x00007fffcad0f55f in QgsWms::Service::executeRequest(QgsServerRequest const&, QgsServerResponse&, QgsProject const*) (this=0x555555a90cb0, request=..., response=..., project=0x555556a25650) at /home/jgr/dev/cpp/QGIS/src/server/services/wms/qgswms.cpp:137
#15 0x00007ffff7e3c978 in QgsServer::handleRequest(QgsServerRequest&, QgsServerResponse&, QgsProject const*) (this=0x7fffffffd718, request=..., response=..., project=0x555556a25650) at /home/jgr/dev/cpp/QGIS/src/server/qgsserver.cpp:530
#16 0x00005555555579fa in main(int, char**) (argc=1, argv=0x7fffffffd978) at /home/jgr/dev/cpp/QGIS/src/server/qgis_map_serv.cpp:93
```

### PR DESCRIPTION
**Pull request by jgrocha**
## Description

This PR adds a if condition to prevent a null pointer being used to call a method.

This prevents the crash mentioned in #57595.

### CODE REVIEW

File: src/core/layout/qgslayoutitemlegend.cpp [hunk 1]
```diff
@@ -1016,10 +1016,12 @@ void QgsLayoutItemLegend::updateFilterByMapAndRedraw()
...
 {
   mLegendModel->setLayerStyleOverrides( overrides );
-  const QList< QgsLayerTreeLayer * > layers =  mLegendModel->rootGroup()->findLayers();
-  for ( QgsLayerTreeLayer *nodeLayer : layers )
-    mLegendModel->refreshLayerLegend( nodeLayer );
-
+  if ( QgsLayerTree *rootGroup = mLegendModel->rootGroup() )
+  {
+    const QList< QgsLayerTreeLayer * > layers =  rootGroup->findLayers();
+    for ( QgsLayerTreeLayer *nodeLayer : layers )
```
Comment (elpaso) [inline src/core/layout/qgslayoutitemlegend.cpp:1022]:
```suggestion
    for ( QgsLayerTreeLayer *nodeLayer : std::as_const( layers ) )
```

**Review by elpaso — APPROVED** [review]
