### PR TITLE
1st fix for broken GetFeatureInfo URLs in REST WMTS layers

### LINKED ISSUE #39002: GetFeatureInfo URL doesn't respect the ignore value in GetCapabilities check box with WMTS tiles
**Describe the bug**

If a WMTS service requires a user to ignore the GetTile and GetFeatureInfo URLs in the WMTS configuration, QGIS ignores this for GetFeatureInfo requests while honouring it for GetTile requests. Note, this works for WMS layers.

**How to Reproduce**

1. Install a local GeoServer and break the capabilities file by adding a non existent url in the proxy url under global settings.
2. Add the WMTS getCapabilities link from the GeoServer front page to QGIS, checking the ignore url for gettile and getfeatureinfo boxes
3. Install QGIS Network logger
4. add a layer from the GeoServer install
5. Try to do an identify operation - instead of generating a correct URL from the base of the getCapabilities request it will attempt to use the incorrect one from the capabilities document.

**QGIS and OS versions**

QGIS version
3.14.16-Pi
QGIS code revision
a235a149f0
Compiled against Qt
5.12.8
Running against Qt
5.12.8
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.31.1
Running against SQLite
3.31.1
PostgreSQL Client Version
12.4 (Ubuntu 12.4-0ubuntu0.20.04.1)
SpatiaLite Version
4.3.0a
QWT Version
6.1.4
QScintilla2 Version
2.11.2
Compiled against PROJ
6.3.1
Running against PROJ
Rel. 6.3.1, February 10th, 2020
OS Version
Ubuntu 20.04.1 LTS
Active python plugins
vrtbuilderplugin; 
autoSaver; 
Projestions; 
QGISSortAndNumber-master; 
QGIS3-getWKT; 
qgis_hats; 
MemoryLayerSaver; 
isochrones; 
firstaid; 
OSMDownloader; 
qchainage; 
plugin_reloader; 
Beeline; 
profiletool; 
polystrip; 
TerrainShading; 
cartogram3; 
Hqgis; 
pluginbuilder3; 
quick_map_services; 
osgb-plugin; 
pointsamplingtool; 
DataPlotly; 
QuickWKT; 
timemanager; 
processing; 
MetaSearch; 
db_manager; 
qgis_resource_sharing; 
qgisnetworklogger

**Additional context**

### PR DESCRIPTION
**Pull request by ianturton**
## Description

This makes a first attempt to fix broken links for GetFeatureInfo requests when the ignore getFeatureInfo URL checkbox is set when using a REST WMTS layer. 

Currently, this will only work for the "Well Known" layer URLs of a GeoServer install, but other people may know of a better way of fixing this for other systems and we could try some sort of heuristic. 

If there is an easy way to unit test this then please let me know and I'll see about adding tests, but I have tested against a locally broken GeoServer install as described in #39002. 

Fixes #39002

### CODE REVIEW

File: src/providers/wms/qgswmsprovider.cpp [hunk 1]
```diff
@@ -3018,8 +3018,31 @@ QgsRasterIdentifyResult QgsWmsProvider::identify( const QgsPointXY &point, QgsRa
...
+
       QString url = mTileLayer->getFeatureInfoURLs[ formatStr ];
 
+      if (mSettings.mIgnoreGetFeatureInfoUrl)
+      {
+        // rewrite the URL if the one in the capabilities document is incorrect
+        QString base = mSettings.mBaseUrl;
+        QgsDebugMsgLevel( QStringLiteral( "1 base=%1" ).arg( base ), 2 );
+        // strip every thing after the ? from the base url
+        base = base.split(QRegExp("\\?"))[0];
```
Comment (elpaso) [inline src/providers/wms/qgswmsprovider.cpp:3031]: Use QRegularExpression please (QRegExp is deprecated or it will be soon).

File: src/providers/wms/qgswmsprovider.cpp [hunk 2]
```diff
@@ -3018,8 +3018,31 @@ QgsRasterIdentifyResult QgsWmsProvider::identify( const QgsPointXY &point, QgsRa
...
       // REST
+      
+
       QString url = mTileLayer->getFeatureInfoURLs[ formatStr ];
 
+      if (mSettings.mIgnoreGetFeatureInfoUrl)
+      {
+        // rewrite the URL if the one in the capabilities document is incorrect
+        QString base = mSettings.mBaseUrl;
+        QgsDebugMsgLevel( QStringLiteral( "1 base=%1" ).arg( base ), 2 );
```
Comment (elpaso) [inline src/providers/wms/qgswmsprovider.cpp:3029]: Please increase the level (probably 4 or 5) or remove the messages altogether.

File: src/providers/wms/qgswmsprovider.cpp [hunk 3]
```diff
@@ -3018,8 +3018,31 @@ QgsRasterIdentifyResult QgsWmsProvider::identify( const QgsPointXY &point, QgsRa
...
     {
       // REST
+      
+
       QString url = mTileLayer->getFeatureInfoURLs[ formatStr ];
 
+      if (mSettings.mIgnoreGetFeatureInfoUrl)
+      {
+        // rewrite the URL if the one in the capabilities document is incorrect
+        QString base = mSettings.mBaseUrl;
```
Comment (elpaso) [inline src/providers/wms/qgswmsprovider.cpp:3028]: const?

File: src/providers/wms/qgswmsprovider.cpp [hunk 4]
```diff
@@ -3018,8 +3018,31 @@ QgsRasterIdentifyResult QgsWmsProvider::identify( const QgsPointXY &point, QgsRa
...
+        QgsDebugMsgLevel( QStringLiteral( "1 base=%1" ).arg( base ), 2 );
+        // strip every thing after the ? from the base url
+        base = base.split(QRegExp("\\?"))[0];
+        QgsDebugMsgLevel( QStringLiteral( "2 base=%1" ).arg( base ), 2 );
+        // and strip everything before the `rest` element (at least for GeoServer)
+        QgsDebugMsgLevel( QStringLiteral( "url=%1" ).arg( url ), 2 );
+        int index = url.length() - url.lastIndexOf("rest") + 1; // +1 for the /
```
Comment (elpaso) [inline src/providers/wms/qgswmsprovider.cpp:3035]:
```suggestion
        const int index = url.length() - url.lastIndexOf( QStringLiteral( "rest" ) ) + 1; // +1 for the /
```

**Comment by ianturton** [comment]
Is anything else needed to get this merged?

File: src/providers/wms/qgswmsprovider.cpp [hunk 5]
```diff
@@ -3018,8 +3018,22 @@ QgsRasterIdentifyResult QgsWmsProvider::identify( const QgsPointXY &point, QgsRa
...
       // REST
+
+
       QString url = mTileLayer->getFeatureInfoURLs[ formatStr ];
 
+      if ( mSettings.mIgnoreGetFeatureInfoUrl )
+      {
+        // rewrite the URL if the one in the capabilities document is incorrect
+        // strip every thing after the ? from the base url
+        const QString base = mSettings.mBaseUrl.split( QRegularExpression( "\\?" ) )[0];
```
Comment (elpaso) [inline src/providers/wms/qgswmsprovider.cpp:3029]: Sorry I missed this before: accessing a string list without checking its size is dangerous (it can segfault). Can you check the size of the result of split before accessing the first element for example you can use https://doc.qt.io/qt-5/qlist.html#isEmpty ? For clarity you can also use https://doc.qt.io/qt-5/qlist.html#first to get the first element.

File: src/providers/wms/qgswmsprovider.cpp [hunk 6]
```diff
@@ -3040,6 +3054,7 @@ QgsRasterIdentifyResult QgsWmsProvider::identify( const QgsPointXY &point, QgsRa
     else if ( !getFeatureInfoUrl().isNull() )
     {
       // KVP
+      QgsDebugMsg( QStringLiteral( "KVP ignore GetFeatureURL %1" ).arg( mSettings.mIgnoreGetFeatureInfoUrl ) );
```
Comment (elpaso) [inline src/providers/wms/qgswmsprovider.cpp:3057]: If this is an error/warning level condition it's ok to use QgsDebugMsg better use QgsDebugMsgLevel otherwise.

**Review by elpaso — CHANGES_REQUESTED** [review]
Some more small changes and we can merge.

**Review by elpaso — APPROVED** [review]

File: src/providers/wms/qgswmsprovider.cpp [hunk 7]
```diff
@@ -3026,7 +3026,8 @@ QgsRasterIdentifyResult QgsWmsProvider::identify( const QgsPointXY &point, QgsRa
       {
         // rewrite the URL if the one in the capabilities document is incorrect
         // strip every thing after the ? from the base url
-        const QString base = mSettings.mBaseUrl.split( QRegularExpression( "\\?" ) )[0];
+        const QList parts = mSettings.mBaseUrl.split( QRegularExpression( "\\?" ) );
```
Comment (elpaso) [inline src/providers/wms/qgswmsprovider.cpp]: I think it's a QStringList
```suggestion
        const QStringList parts = mSettings.mBaseUrl.split( QRegularExpression( "\\?" ) );
```
