### PR TITLE
An attempt to fix oid overflow in regclass

### LINKED ISSUE #30041: Unable to add new features in QGIS for PostGIS table using sequence for gid. Data type serial: 'integer overflow'
PostGIS 2.2 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
Postgres PostgreSQL 9.5.4, compiled by Visual C++ build 1800, 64-bit
QGIS 2.18 Las Palmas

```
CREATE TABLE myschema.mytable
(
  gid serial NOT NULL,
  the_geom geometry(Point,25832),
  CONSTRAINT mytable_pkey PRIMARY KEY (gid)
)
WITH (
  OIDS=TRUE
);
```

In QGIS I added the PostGIS - layer "myschema.mytable" and tried to save a new object.
Following message appears:

"Konnte Änderungen am Layer mytable nicht festschreiben

Fehler: FEHLER: Ein Objekt nicht hinzugefügt.
  
Datenanbieterfehler:
      PostGIS-Fehler beim Attributhinzufügen: FEHLER:  NULL-Wert in Spalte »gid« 
      verletzt Not-Null-Constraint
    DETAIL:  Fehlgeschlagene Zeile enthält (null, 
    0102000020E8640000020000004DAC4DB4A84918414C986446399155416E8719...)."

"Could not commit changes on layer mytable

Error: ERROR: One object is not added.
  
Data provider error:
      PostGIS-Error on add attribute: ERROR:  NULL- value in column »gid« 
      is not permitted as an input because of Not-Null-Constraint
    DETAIL:  Failed row contains (null, 
    0102000020E8640000020000004DAC4DB4A84918414C986446399155416E8719...)."

In QGIS should be the default for column 'gid':
nextval('myschema.mytable_gid_seq'::regclass)

Instead the default for column 'gid' is 'NULL'.

To reproduce the error select on PostGIS:

`SELECT 'myschema.mytable'::regclass::oid;`

If the result is bigger than the maximum integer - value 2147483647
it is not possible to use data type 'serial' in QGIS to add a new object.
But in PostGIS I can add objects if the value of column "gid" is of data type 'serial' 
and the result is bigger than 2147483647 because PostGIS has no "integer overflow".

(Please refer to https://github.com/qgis/QGIS/issues/29489, https://issues.qgis.org/issues/21673)

I think QGIS can't handle sequences after integer overflow.

Is it possible to change the data type of regclass::oid from 'integer' into 'biginteger'
in QGIS??

### PR DESCRIPTION
**Pull request by elpaso**
QGIS was using int to store oids, but oids are 4 byte unsigned ints.

This is an attempt to partially fix #30041

### CODE REVIEW

**Comment by elpaso** [comment]
@jef-n what do you think?

File: src/providers/postgres/qgspostgresconn.cpp [hunk 1]
```diff
@@ -110,7 +110,7 @@ QString QgsPostgresResult::PQfname( int col )
   return QString::fromUtf8( ::PQfname( mRes, col ) );
 }
 
-int QgsPostgresResult::PQftable( int col )
+unsigned int QgsPostgresResult::PQftable( int col )
```
Comment (luipir) [inline src/providers/postgres/qgspostgresconn.cpp]: in some part of the master PR you used unsigned int instead of Oid... what's the reason?
