### PR TITLE
Fix PostGIS geography extent computation

### LINKED ISSUE #30294: Extent of data fetched from GEOGRAPHY PostGIS column can not be changed
**Describe the bug**
When layer data is fetched from geography postgis column extent is always -180,180,-90,90 and can not be updated. In case of geometry column extent behave correctly.

**How to Reproduce**
1. Create layer with postgis source
2. Use data from GEOGRAPHY columnt
3. Zoom to the layer /whole world appears/
4. Go to the layer settings
5. Update extent /no action/

**QGIS and OS versions**

Wersja QGIS | 3.6.3-Noosa | Gałąź kodu QGIS | Release 3.6
-- | -- | -- | --
Skompilowane z Qt | 5.12.3 | Uruchomione z Qt | 5.12.3
Skompilowane z GDAL/OGR | 2.3.2 | Uruchomione z GDAL/OGR | 2.4.1
Skompilowane z GEOS | 3.7.1-CAPI-1.11.1 | Uruchomione z GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Wersja klienta PostgreSQL | 11.2 | Wersja SpatiaLite | 4.3.0a
Wersja QWT | 6.1.4 | Wersja QScintilla2 | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018

### PR DESCRIPTION
**Pull request by strk**
Closes GH-30294

### CODE REVIEW

**Review by benoitdm-oslandia — APPROVED** [review]
LGTM!

**Comment by strk** [comment]
It's actually not good as it returns an extent of `0.8130174279212951,-0.1733461171388630 : 0.9706265926361080,0.2985342144966130` but it seems to be a PostGIS issue with estimated extent, which I've filed as https://trac.osgeo.org/postgis/ticket/5734

**Comment by benoitdm-oslandia** [comment]
strange behavior! That is really strange no one has ever noticed this issue....

**Comment by strk** [comment]
With 69fffa03cfe2bfefdb043ba8a8bb9e5c7c27af58 we never estimate but always compute, as if stats were never gathered. It works correctly for me

File: src/providers/postgres/qgspostgresprovider.cpp [hunk 1]
```diff
@@ -3957,7 +3954,7 @@ QgsBox3D QgsPostgresProvider::extent3D() const
       sql = QStringLiteral( "SELECT %1(%2%3) FROM %4%5" )
             .arg( connectionRO()->majorVersion() < 2 ? "extent" : "ST_3DExtent",
                   quotedIdentifier( mBoundingBoxColumn ),
-                  mSpatialColType == SctPcPatch ? "::geometry" : "",
+                  ( mSpatialColType == SctPcPatch || mSpatialColType == SctGeography ) ? "::geometry" : "",
```
Comment (benoitdm-oslandia) [inline src/providers/postgres/qgspostgresprovider.cpp:3957]: cannot be equals here and diff line 3900

Comment (strk) [reply src/providers/postgres/qgspostgresprovider.cpp:3957]: Line 3957 is not inside the branch entered by line 3900.
The code goes: 
   - line 3900: if we estimate, fetch extent by estimating
   - line 3957: if ext is empty (we were unable to estimate, or we decided not to estimate), compute extent

Comment (benoitdm-oslandia) [reply src/providers/postgres/qgspostgresprovider.cpp:3957]: my bad!

**Review by benoitdm-oslandia — APPROVED** [review]
LGTM!

File: src/providers/postgres/qgspostgresprovider.cpp [hunk 2]
```diff
@@ -3895,117 +3895,92 @@ QgsBox3D QgsPostgresProvider::extent3D() const
...
-      if ( result.PQresultStatus() != PGRES_TUPLES_OK )
-        connectionRO()->LoggedPQexecNR( "QgsPostgresProvider", QStringLiteral( "ROLLBACK" ) );
-      else if ( result.PQntuples() == 1 && !result.PQgetisnull( 0, 0 ) )
-        ext = result.PQgetvalue( 0, 0 );
+      if ( result.PQresultStatus() != PGRES_TUPLES_OK ) break;
+      if ( result.PQntuples() != 1 ) break;
+      if ( result.PQgetisnull( 0, 0 ) ) break;
+      ext = result.PQgetvalue( 0, 0 );
     }
+    while ( 0 );
```
Comment (benoitdm-oslandia) [inline src/providers/postgres/qgspostgresprovider.cpp:3951]: Why are you using do/while? here and in the block above?

File: src/providers/postgres/qgspostgresprovider.cpp [hunk 3]
```diff
@@ -3895,117 +3895,92 @@ QgsBox3D QgsPostgresProvider::extent3D() const
...
-        mLayerExtent.setZMinimum( match.captured( 3 ).toDouble() );
-        mLayerExtent.setXMaximum( match.captured( 4 ).toDouble() );
-        mLayerExtent.setYMaximum( match.captured( 5 ).toDouble() );
-        mLayerExtent.setZMaximum( match.captured( 6 ).toDouble() );
-
-        if ( !elevationProperties()->containsElevationData() )
-        {
-          mLayerExtent.setZMinimum( std::numeric_limits<double>::quiet_NaN() );
-          mLayerExtent.setZMaximum( std::numeric_limits<double>::quiet_NaN() );
-        }
```
Comment (benoitdm-oslandia) [inline src/providers/postgres/qgspostgresprovider.cpp:3995]: I should have let a comment on this part to explain the reason. As I remember that was necessary: sometimes the layer is viewed as a 2D layer even if it has 3D values in the extent request. This is why I set the Z coordinates to NaN.

File: src/providers/postgres/qgspostgresprovider.cpp (hunk 2 above)
Comment (strk) [reply src/providers/postgres/qgspostgresprovider.cpp:3951]: I find it more readable when there are a lot of reasons to skip a block.
More readable than a lot of nested conditions

File: src/providers/postgres/qgspostgresprovider.cpp (hunk 3 above)
Comment (strk) [reply src/providers/postgres/qgspostgresprovider.cpp:3995]: I just moved it outside the conditional, we're still setting it to NaN.
What it isn't clear is what the function should do when the extent could not be computed. Right now only Z min/max are set but all other dimensions are left untouched. Would it make more sense to setNull as the first thing ?

File: src/providers/postgres/qgspostgresprovider.cpp (hunk 2 above)
Comment (nyalldawson) [reply src/providers/postgres/qgspostgresprovider.cpp:3957]: I'm personally -0 to this coding style. I can see the logical benefit in it, but it's so rarely used that i find there's always difficulty in reading it and comprehending why something which runs once is using a loop statement...

Comment (strk) [reply src/providers/postgres/qgspostgresprovider.cpp:3957]: Would you prefer goto statements ? Or some macro to make it more clear it's about to run ONCE ?

Comment (nyalldawson) [reply src/providers/postgres/qgspostgresprovider.cpp:3957]: Extracting to a function, or even to a lambda function?

Comment (strk) [reply src/providers/postgres/qgspostgresprovider.cpp:3957]: Ok I'll see about a function, maybe we could just throw an exception if estimation cannot be performed, trying different heuristics aimed at estimating

File: src/providers/postgres/qgspostgresprovider.cpp (hunk 3 above)
Comment (strk) [reply src/providers/postgres/qgspostgresprovider.cpp:3995]: With commit aa5e200d254a6acc4627d568d765f6bb1e333b84 I hopefully made it more clear too

File: src/providers/postgres/qgspostgresprovider.cpp (hunk 2 above)
Comment (strk) [reply src/providers/postgres/qgspostgresprovider.cpp]: Extraction to functions done with aa5e200d254a6acc4627d568d765f6bb1e333b84

**Comment by elpaso** [comment]
This PR is flagged with require tests. I agree that a test would be nice.

**Comment by strk** [comment]
Test added

File: src/providers/postgres/qgspostgresprovider.cpp [hunk 4]
```diff
@@ -3890,144 +3885,189 @@ QgsRectangle QgsPostgresProvider::extent() const
...
 
-QgsBox3D QgsPostgresProvider::extent3D() const
+bool QgsPostgresProvider::estimateExtent() const
 {
-  if ( !isValid() || mGeometryColumn.isNull() )
-    return QgsBox3D();
+  // Cannot estimate extent of a query
+  if ( mIsQuery )
+  {
+    QgsDebugMsgLevel( tr( "Estimating extent of queries is not supported" ), 2 );
```
Comment (m-kuhn) [inline src/providers/postgres/qgspostgresprovider.cpp:3893]:
```suggestion
    QgsDebugMsgLevel( "Estimating extent of queries is not supported", 2 );
```

Debug messages are not translated

**Review by m-kuhn — APPROVED** [review]
One minor change requested, then it's good to go

File: src/providers/postgres/qgspostgresprovider.cpp (hunk 4 above)
Comment (strk) [reply src/providers/postgres/qgspostgresprovider.cpp]: Pushed a commit dropping the translations, thanks for the review!

**Comment by strk** [comment]
I confirm the new test is effective at catching the bug as I tried it against 3.34 and got this:
> AssertionError: <QgsRectangle: -180 -90, 180 90> != <QgsRectangle: -10 -60, 10 60>

File: src/providers/postgres/qgspostgresprovider.h [hunk 5]
```diff
@@ -485,6 +486,9 @@ class QgsPostgresProvider final: public QgsVectorDataProvider
     static int crsToSrid( const QgsCoordinateReferenceSystem &crs,  QgsPostgresConn *conn );
     static QgsCoordinateReferenceSystem sridToCrs( int srsId, QgsPostgresConn *conn );
 
+    bool estimateExtent() const;
+    bool computeExtent3D() const;
```
Comment (benoitdm-oslandia) [inline src/providers/postgres/qgspostgresprovider.h:490]: Can we have a comment on theses functions as the code is becoming more and more complex? Just to remember why you have done this fix ;)

**Review by benoitdm-oslandia — APPROVED** [review]

File: src/providers/postgres/qgspostgresprovider.h (hunk 5 above)
Comment (strk) [reply src/providers/postgres/qgspostgresprovider.h]: I've pushed comments
