### PR TITLE
Fix GPKG FID issues when running in-place mode

### LINKED ISSUE #33816: "duplicate key value violates unique constraint" error when using "Edit Feature in Place" with PostGIS Layer
in our postgis database for line(road) layer we have defined primary key field and have applied unique not null constraint when i save split line segements manually by editing toolbar it works fine, but when i split lines with "split with lines" tool by turning on edit feature in place it gives me postgis error
"""
Could not commit changes to layer pk_roads

Errors: ERROR: 4 feature(s) not added.
  
  Provider errors:
      PostGIS error while adding features: ERROR:  duplicate key value violates unique constraint "pk_roads"
    CONTEXT:  SQL statement "INSERT INTO pk_roads SELECT(pk_roads '(,,,,,,,,,,,,0102000020110F000002000000A00ABFB828A35F411E7335C4B9484D41C9CA687C3CA35F41405E7DA3BD484D41,103564332,"digi1,",,,,,,,,,,,,,,,,,,,,,,,,)').* RETURNING id;"
    PL/pgSQL function fn_rd_partition() line 9 at EXECUTE
    
"""
but from my point of view it must have to work fine for "split with lines" tool if same splitting works from "Advance Digitizing Toolbar"

### LINKED ISSUE #37761: Split with lines causes data loss
**Describe the bug**
I have a memory line layer and with this layer I want to split geoms of gpkg-file by using the edit in place mode. After finsihing the job there is not the expect result but aduplication of geoms in the gpk-file

**How to Reproduce**

1. load a poly-layer of gpkg-file
2. creaete a memory line line
3. active edit in place mode
4. start the processing tool split with lines
5. no split but a duplication of geoms

**QGIS and OS versions**

QGIS version | 3.14.0-Pi | QGIS code revision | 9f7028fd
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 12.2 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | KDE Flatpak runtime
Active python plugins | VectorBender; QuickMultiAttributeEdit3; polystrip; qfieldsync; MetaSearch; db_manager; processing

**Additional context**

### PR DESCRIPTION
**Pull request by nyalldawson**
Correctly discard fid field values when running algorithms with the RegeneratePrimaryKey flag in in-place mode

Fixes #37761, fixes #33816

### CODE REVIEW

File: src/core/qgsvectorlayerutils.cpp [hunk 1]
```diff
@@ -734,13 +734,22 @@ void QgsVectorLayerUtils::matchAttributesToFields( QgsFeature &feature, const Qg
...
   QgsWkbTypes::Type inputWkbType( layer->wkbType( ) );
   QgsFeatureList resultFeatures;
   QgsFeature newF( feature );
   // Fix attributes
   QgsVectorLayerUtils::matchAttributesToFields( newF, layer->fields( ) );
+
+  if ( sinkFlags & QgsFeatureSink::RegeneratePrimaryKey && layer->storageType() == QLatin1String( "GPKG" ) )
+  {
+    // drop incoming fid value, let it be regenerated
+    const int fidIndex = layer->fields().lookupField( QStringLiteral( "fid" ) );
```
Comment (rouault) [inline src/core/qgsvectorlayerutils.cpp:748]: you should probably use the name of the first field returned by the provider instead of the hard coded "fid", in case it would have been named differently than the default.

Question (related to my last email): why do we need that hack for GPKG, but not with the Postgres provider when it exposes a integer primary key column ?

Comment (nyalldawson) [reply src/core/qgsvectorlayerutils.cpp:748]: Hmm - I'll need to dig deeper. My first guess at the difference proved wrong...

Comment (nyalldawson) [reply src/core/qgsvectorlayerutils.cpp]: Ok, fixed. I've made this method compatible with non-ogr/non-gpkg providers too.

File: tests/src/python/test_qgsprocessinginplace.py [hunk 2]
```diff
@@ -912,6 +913,26 @@ def test_unique_constraints(self):
 
         self.assertTrue(gpkg_layer.commitChanges())
 
+    def test_regenerate_fid(self):
+        """Test RegeneratePrimaryKey flag"""
+        temp_dir = QTemporaryDir()
```
Comment (elpaso) [inline tests/src/python/test_qgsprocessinginplace.py:918]:
```suggestion

        temp_dir = QTemporaryDir()
```

Comment (nyalldawson) [reply tests/src/python/test_qgsprocessinginplace.py:918]: what am I missing? an extra line?

Comment (elpaso) [reply tests/src/python/test_qgsprocessinginplace.py:918]: yes, I though all our nice pre commit would have taken care of that but apparently not.
