### PR TITLE
ConcaveHull - Expression: Adds an ifdef GEOS 3.11

### LINKED ISSUE #50723: concave_hull error prevents user from closing QGIS
### What is the bug or the crash?

When testing the new `concave_hull` function within a geometry generator in QGIS 3.28, I get an error "Calculating concaveHull requires a QGIS build based on GEOS 3.11 or later":
image

I'm running QGIS 3.28.0 on Windows, so maybe this function won't be available until a later release?  That's fine, I don't mind waiting.

But when I try to change the layer style back to "Simple Fill" or even just change the color, I get the same error.  I also cannot close QGIS -- the error pops up again and the program will not close.

### Steps to reproduce the issue

https://user-images.githubusercontent.com/3355358/198396275-57c2f3a6-f2d2-4430-a305-0402e9700ef2.mp4

I also tested with a new QGIS profile, and the same error occurs.

### Versions

QGIS version
3.28.0-Firenze
QGIS code revision
ed3ad0430f3
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.2
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
Discovery
2.5.7
ee_plugin
0.0.5
latlontools
3.6.4
LayerBoard
1.0.1
mask
1.10.2
mmqgis
2021.9.10
nominatim
1.4.2
nys-geocoder
0.1
plugin_reloader
0.9.1
processing_wbt
1.3.1
qgis2web
3.16.0-color-svg
QGIS3-getWKT
1.4
qgis_preview_mode_plugin
0.1.0
qgis_stac
1.1.1
QNEAT3
1.0.4
QuickOSM
2.1.1
quick_map_services
0.19.29
RasterAttributeTable
1.1
SRTM-Downloader
3.1.17
StreetView
3.2
ThRasE
22.3.3a
timemanager
3.6
valuetool
3.0.15
zoom_level
0.2.0
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lbartoletti**
## Description
Fixes #50723

### CODE REVIEW

File: src/core/expression/qgsexpressionfunction.cpp [hunk 1]
```diff
@@ -2612,8 +2612,7 @@ static QVariant fcnGeomMakeValid( const QVariantList &values, const QgsExpressio
   }
   catch ( QgsNotSupportedException & )
   {
-    parent->setEvalErrorString( QObject::tr( "The make_valid parameters require a newer GEOS library version" ) );
-    return QVariant();
+    parent->setEvalErrorString( QObject::tr( "The make_valid parameters require a newer GEOS library version" ) ); return QVariant();
```
Comment (rouault) [inline src/core/expression/qgsexpressionfunction.cpp:2615]: why this change ? The original 2 line one is more readable

Comment (lbartoletti) [reply src/core/expression/qgsexpressionfunction.cpp:2615]: If it's me, it was unintentional.

**Review by rouault — APPROVED** [review]
