### PR TITLE
[backport release-3_22][processing] save NULL and empty values into different files in Split Vector Layer algorithm (fix #38105)

### LINKED ISSUE #38105: Split Vector Layer algorithm does not export both null and empty values
**Describe the bug**
The Split Vector Layer algorithm exports both null and empty values to the same filename silently overwriting the former with the later.
This was unintentionally fixed in the couple of last versions when ported to c++ and added a regression by replacing the filename with an numeric id.
By fixing this regression, the empty/null bug was reintroduced, so this is technically a regression too

**How to Reproduce**
Use the Split vector layer algorithm and use a field that contains both null and empty string values.
A single file is created containing only null or empty values.

### PR DESCRIPTION
**Pull request by alexbruy**
## Description
Manual backport of the Split Vector Layer algorithm fix from #46997.

The Split Vector Layer algorithm exports both NULL and empty attribute values to the same filename, as a result one file overwrites another and some results are lost. Proposed PR assigns different suffixes for such files (_EMPTY and _NULL).

Fixes #38105.

Also fix unreported bug with displaying incorrect number of features written to each output file.

### CODE REVIEW

File: tests/src/analysis/testqgsprocessingalgs.cpp [hunk 1]
```diff
@@ -7074,6 +7076,47 @@ void TestQgsProcessingAlgs::exportMeshTimeSeries()
...
+void TestQgsProcessingAlgs::splitVectorLayer()
+{
+  QgsVectorLayer *layer = new QgsVectorLayer( QStringLiteral( "Point?crs=epsg:4326&field=pk:int&field=col1:string" ), QStringLiteral( "vl" ), QStringLiteral( "memory" ) );
+  QVERIFY( layer->isValid() );
+
+  QgsFeature f;
+  f.setAttributes( QgsAttributes() << 1 << QVariant() );
+  f.setGeometry( QgsGeometry::fromWkt( QStringLiteral( "Point (0 0)" ) ) );
+  layer->dataProvider()->addFeature( f );
+  f.setAttributes( QgsAttributes() << 2 << QStringLiteral( "" ) );
```
Comment (nyalldawson) [inline tests/src/analysis/testqgsprocessingalgs.cpp:7088]:
```suggestion
  f.setAttributes( QgsAttributes() << 2 << QString( "" ) );
```

QStringLiteral( "" ) causes warnings on MSVC builds

**Review by nyalldawson — APPROVED** [review]

File: tests/src/analysis/testqgsprocessingalgs.cpp (hunk 1 above)
Comment (alexbruy) [reply tests/src/analysis/testqgsprocessingalgs.cpp]: Fixed
