### PR TITLE
Fix parsing 2-byte LAS scan angle (fix #58451)

### LINKED ISSUE #58451: Issue with decoding  ScanAngleRank in LAZ files
### What is the bug or the crash?

QGIS  shows Values form -128 to 127 for the ScanAngleRank for my Lidarpoint-Datasets. There is a bug in QGIS  laz decoder code, which always treats ScanAngleRank data as a single byte char for both point data record formats 1-5 and 6-10.

### Steps to reproduce the issue

@uclaros has already reproduced the issue!

### Versions

3.38

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dvdkon**
## Description

Currently in QGIS the `ScanAngleRank` LAS(/LAZ) field is typed as a short and is read as a single signed byte. The LAS 1.4 specification introduced a new field, `ScanAngle`, which is logically a two-byte fixed-point number, to replace `ScanAngleRank` in new formats. Right now QGIS tries to read this field as `ScanAngleRank`, so the result is an incorrect integer value.

This PR changes the type of `ScanAngleRank` to `float` and fixes parsing the new LAS 1.4 formats, unifying `ScanAngleRank` and `ScanAngle` into one general property, just as PDAL does.

Will fix #58451.

### CODE REVIEW

File: src/core/pointcloud/qgslazdecoder.cpp [hunk 1]
```diff
@@ -397,7 +399,7 @@ void decodePoint( char *buf, int lasPointFormat, char *dataBuffer, std::size_t &
         lazStoreToStream_<unsigned char>( dataBuffer, outputOffset, requestedAttribute.type, isLas14 ? p14.eofFlag() : p10.edge_of_flight_line );
         break;
       case QgsLazDecoder::LazAttribute::ScanAngleRank:
-        lazStoreToStream_<char>( dataBuffer, outputOffset, requestedAttribute.type, char( isLas14 ? p14.scanAngle() : p10.scan_angle_rank ) );
+        lazStoreToStream_<float>( dataBuffer, outputOffset, requestedAttribute.type, isLas14 ? p14.scanAngle() * 0.006f : p10.scan_angle_rank );
```
Comment (uclaros) [inline src/core/pointcloud/qgslazdecoder.cpp:402]: Can you add a comment like `according to laz spec, scan angle is stored in 0.006 degrees increments` to justify the magic number?

File: src/core/pointcloud/qgslazdecoder.cpp [hunk 2]
```diff
@@ -315,7 +315,9 @@ void decodePoint( char *buf, int lasPointFormat, char *dataBuffer, std::size_t &
   lazperf::las::nir14 nir;
   lazperf::las::point14 p14;
 
-  bool isLas14 = ( lasPointFormat == 6 || lasPointFormat == 7 || lasPointFormat == 8 );
+  // Does the point record start with the common fields for formats introduced
+  // in the LAS 1.4 spec?
+  bool isLas14 = ( lasPointFormat == 6 || lasPointFormat == 7 || lasPointFormat == 8 || lasPointFormat == 9 || lasPointFormat == 10 );
```
Comment (uclaros) [inline src/core/pointcloud/qgslazdecoder.cpp:320]: pdrf 9 and 10 are not supported so this is kind of redundant. You could also `const` it while there :)

**Review by uclaros — COMMENTED** [review]
Nice!
Tests were built with the buggy behavior and will need tweaking

Also, adding `fix #58451` to the description text, rather than the title, will link and auto close the issue!

File: src/core/pointcloud/qgslazdecoder.cpp (hunk 2 above)
Comment (rouault) [reply src/core/pointcloud/qgslazdecoder.cpp:320]: side remark from someone ignorant about the LAS spec. Using named constant to explain the semantics of 6, 7, etc. would be better for readability (assuming there's some semantic behind those numbers...)

**Comment by dvdkon** [comment]
> Nice! Tests were built with the buggy behavior and will need tweaking
> 
> Also, adding `fix #58451` to the description text, rather than the title, will link and auto close the issue!

Thanks for the review! I admit I (ab)use GitHub's CI to show me which tests need attention, since I get too many false positives on my machine. They should all be fixed now.

File: src/core/pointcloud/qgslazdecoder.cpp (hunk 1 above)
Comment (dvdkon) [reply src/core/pointcloud/qgslazdecoder.cpp]: Added.

File: src/core/pointcloud/qgslazdecoder.cpp (hunk 2 above)
Comment (dvdkon) [reply src/core/pointcloud/qgslazdecoder.cpp]: > pdrf 9 and 10 are not supported so this is kind of redundant. You could also `const` it while there :)

Const added :)

I kept formats 9 and 10, since I think the variable is less confusing this way, actually checking for format commonalities and not for (common format && supported format).



> side remark from someone ignorant about the LAS spec. Using named constant to explain the semantics of 6, 7, etc. would be better for readability (assuming there's some semantic behind those numbers...)

The spec just numbers the possible formats, so I don't think adding enums would gain us much here. Besides, this is just a bugfix PR, and refactoring this everywhere would increase its scope too much.

**Review by uclaros — APPROVED** [review]
