### PR TITLE
fixes for Processing geometry checker algorithms

### LINKED ISSUE #61398: Check geometry (angle) does not check whether feature ID is unique
### What is the bug or the crash?

In the "Check geometry (angle)" algorithm, provide a layer and, for the "Unique feature identifier" parameter, provide a field that contains duplicate values.
The algorithm will run successfully and generate expected output layers.
Now try to use the "Fix geometry (angle)" algorithm on your data, filling the same field as unique identifier.
It may fail because of duplicate values.

We probably should check at the start that the field is really a unique identifier.

### Steps to reproduce the issue

See above

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.43.0-Master</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/d3a8b799681">d3a8b799681</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.8</td></tr><tr><td>Python version</td><td>3.11.2</td></tr><tr><td>GDAL version</td><td>3.9.3</td></tr><tr><td>PROJ version</td><td>9.1.1</td></tr><tr><td>EPSG Registry database version</td><td>v10.076 (2022-08-31)</td></tr><tr><td>GEOS version</td><td>3.11.1-CAPI-1.17.1</td></tr><tr><td>SQLite version</td><td>3.40.1</td></tr><tr><td>PDAL version</td><td>2.8.3</td></tr><tr><td>PostgreSQL client version</td><td>15.12</td></tr><tr><td>SpatiaLite version</td><td>5.0.1</td></td></tr><tr><td>QWT version</td><td>6.1.4</td></tr><tr><td>QScintilla2 version</td><td>2.13.3</td></tr><tr><td>OS version</td><td>Debian GNU/Linux 12 (bookworm)</td></tr><tr><td colspan="2"><i>This copy of QGIS writes debugging output.</i></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>MemoryLayerSaver</td><td>5.0.2</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alexbruy**
## Description

Various fixes for Processing check/fix geometry algorithms:

- raise an exception in geometry checker algorithms if selected unique ID field contains duplicated values to prevent failures at the geometry repair step (fixes #61398)
- avoid use of `QgsProject::instance()` in algorithms
- correctly mark algorithms which require project with the corresponding flag
- added cancellation support in geometry checks

### CODE REVIEW

**Comment by alexbruy** [comment]
@Djedouas what do you think?

**Review by Djedouas — APPROVED** [review]
Looks good to me, thanks!

File: src/analysis/processing/qgsalgorithmcheckgeometryangle.cpp [hunk 1]
```diff
@@ -136,6 +136,12 @@ QVariantMap QgsGeometryCheckAngleAlgorithm::processAlgorithm( const QVariantMap
   if ( uniqueIdFieldIdx == -1 )
     throw QgsProcessingException( QObject::tr( "Missing field %1 in input layer" ).arg( uniqueIdFieldName ) );
 
+  // ensure that unique ID field is indeed unique
+  if ( input->featureCount() != input->uniqueValues( uniqueIdFieldIdx ).count() )
```
Comment (nyalldawson) [inline src/analysis/processing/qgsalgorithmcheckgeometryangle.cpp]: We need to guard against negative featureCount results, which are used for unknown/uncounted:

```suggestion
  const long long featureCount = input->featureCount();
  if ( featureCount >= 0 && featureCount != input->uniqueValues( uniqueIdFieldIdx ).count() )
```

Comment (nyalldawson) [reply src/analysis/processing/qgsalgorithmcheckgeometryangle.cpp]: That said -- this is potentially quite an expensive check to run. Could we instead build a set of processed feature IDs as we iterate instead?

Comment (alexbruy) [reply src/analysis/processing/qgsalgorithmcheckgeometryangle.cpp]: Probably yes, from the quick look at the code this can be done either when building a feature pool or when running a check itself. Probably @Djedouas can provide more feedback on this matter.

Comment (Djedouas) [reply src/analysis/processing/qgsalgorithmcheckgeometryangle.cpp]: The iteration on the features is done inside the geometry checker API, and not in the processing itself.

In my opinion, trying to give the feature pool awareness of a unique field, to verify inside, breaks some abstraction. It is the processing that requires a unique field to be truly unique, not the geometry checker or the feature pool.

That's why I originally chose to check the unique field in the fix algorithms, which iterates on the errors to fix.

I would say that the method in this PR is the correct method, but it is a compromise with performance on very big layers. And big layers are what we expect to have with these check algorithms.

Not sure what to recommend here.

Comment (nyalldawson) [reply src/analysis/processing/qgsalgorithmcheckgeometryangle.cpp]: I'd add an optional flag to the geometry checker API then to perform the check for uniqueness, and make it opt-in only.

**Comment by alexbruy** [comment]
@nyalldawson, @Djedouas I have updated PR with another approach. Now check for duplicated IDs is performed in the geometry checker when unique ID field index is set in the geometry checker context.

I also added support for cancellation as most of the checks do not have it.

@Djedouas may I ask why are you using `QgsProject::instance()` in the algorithms and not project from the context? Also I noticed that all algorithms are marked with `NoThreading` flag. According to you

>  And big layers are what we expect to have with these check algorithms.

But with checks/fixes running in the main thread they seem not very usable with large datasets.

**Comment by Djedouas** [comment]
Thank you for the support of the algorithm cancellation :)

I think that you are right to throw an exception if the processing is cancelled. But we need to homogenize with the cancellation check that is in most check algorithms during the for loop on check errors (i.e. https://github.com/qgis/QGIS/blob/master/src/analysis/processing/qgsalgorithmcheckgeometryarea.cpp#L195), and throw an exception as well.

Going through a rapid verification of check algorithms, there are some that are missing this cancellation check (i.e. https://github.com/qgis/QGIS/blob/master/src/analysis/processing/qgsalgorithmcheckgeometryselfintersection.cpp#L186 maybe it's the only one?).

Thank you as well for the unique field ID verification inside the geometry checker 👍🏼  looks good to me. That's a huge improvement.

> @Djedouas may I ask why are you using QgsProject::instance() in the algorithms and not project from the context? Also I noticed that all algorithms are marked with NoThreading flag.

Good question :)  At the beginning of this work to implement these algorithms, I surely chose the multithreaded option. But then there were a lot of segmentation faults that I was unsure where they were coming from. So to be sure they were not coming from the processing themselves, I put the NoThreading flag.

Your question makes me think that it could be because the processings are using QgsProject::instance() instead of the context project.

We **have** to end up with multithreaded algorithms to handle large datasets. If you manage to achieve this, It would be great!! (and I suggest adapting the PR title then 😉 )

File: src/analysis/processing/qgsalgorithmcheckgeometryarea.cpp [hunk 2]
```diff
@@ -63,7 +63,7 @@ QString QgsGeometryCheckAreaAlgorithm::shortHelpString() const
 
 Qgis::ProcessingAlgorithmFlags QgsGeometryCheckAreaAlgorithm::flags() const
 {
-  return QgsProcessingAlgorithm::flags() | Qgis::ProcessingAlgorithmFlag::NoThreading;
+  return QgsProcessingAlgorithm::flags() | Qgis::ProcessingAlgorithmFlag::RequiresProject;
```
Comment (nyalldawson) [inline src/analysis/processing/qgsalgorithmcheckgeometryarea.cpp]: I don't think these algorithms ARE thread safe -- at least, there's access to the project from the process step, which hints that there's at least some logic which would need to be moved to the prepare stage. Can we leave the no thread flag for now and then address that in a follow up?

File: src/analysis/vector/geometry_checker/qgsgeometrycheckcontext.h [hunk 3]
```diff
@@ -34,7 +34,7 @@ class ANALYSIS_EXPORT QgsGeometryCheckContext
     /**
      * Creates a new QgsGeometryCheckContext.
      */
-    QgsGeometryCheckContext( int precision, const QgsCoordinateReferenceSystem &mapCrs, const QgsCoordinateTransformContext &transformContext, const QgsProject *mProject );
+    QgsGeometryCheckContext( int precision, const QgsCoordinateReferenceSystem &mapCrs, const QgsCoordinateTransformContext &transformContext, const QgsProject *mProject = nullptr, const int uniqueIdFieldIndex = -1 );
```
Comment (nyalldawson) [inline src/analysis/vector/geometry_checker/qgsgeometrycheckcontext.h:44]: Can you add a documentation note that uniqueIdFieldIndex was added in 4.0?

File: src/analysis/vector/geometry_checker/qgsgeometrycheck.cpp [hunk 4]
```diff
@@ -175,3 +187,26 @@ double QgsGeometryCheck::scaleFactor( const QPointer<QgsVectorLayer> &layer ) co
...
+  {
+    uniqueIds.insert( layerFeature.layerId(), QSet<QVariant>() );
+  }
+
+  const QVariant uniqueIdValue = layerFeature.feature().attribute( uniqueIdFieldIndex );
+  if ( uniqueIds[layerFeature.layerId()].contains( uniqueIdValue ) )
+  {
+    return QgsGeometryCheck::Result::DuplicatedUniqueId;
+  }
+  uniqueIds[layerFeature.layerId()].insert( uniqueIdValue );
```
Comment (nyalldawson) [inline src/analysis/vector/geometry_checker/qgsgeometrycheck.cpp]: Let's avoid some duplicate lookups, since this will potentially be called thousands of times:

```suggestion
  auto uniqueIdIt = uniqueIds.find( layerFeature.layerId() );
  if ( uniqueIdIt == uniqueIds.end() )
  {
    uniqueIdIt = uniqueIds.insert( layerFeature.layerId(), QSet<QVariant>() );
  }

  const QVariant uniqueIdValue = layerFeature.feature().attribute( uniqueIdFieldIndex );
  if ( uniqueIdIt.value().contains( uniqueIdValue ) )
  {
    return QgsGeometryCheck::Result::DuplicatedUniqueId;
  }
  uniqueIdIt.value().insert( uniqueIdValue );
```

**Review by Djedouas — APPROVED** [review]
