### PR TITLE
[Backport 3.10] QgsExpression::referencedAttributeIndexes(): only report valid indices

### LINKED ISSUE #33878: Crash when applying wrong filter to OAFeat layer
QGIS master on Windows.

Create a WFS / OGC API  connection to https://pta.spatineo-devops.com/sofp/?f=json

Connect to the service

Choose a layer and double click to open a dialog that allows to create a filter with an expression

Enter a filter/expression that is based on a column name that does not actually exist in the layer, i.e. "test"=1

Click "test" or "ok" > crash

### PR DESCRIPTION
**Pull request by rouault**
Backport of https://github.com/qgis/QGIS/pull/33927

If the expression was referencing a non-existing field, -1 was returned in the
result set, which caused later crashed in various providers, including the
Spatialite, Postgres, etc..., due to tried to dereference mFields.at(-1)

Discarding invalid indices is what is also done in
QgsFeatureRequest::OrderBy::usedAttributeIndices()

Fixes #33878

### CODE REVIEW

File: src/providers/oracle/qgsoraclefeatureiterator.cpp [hunk 1]
```diff
@@ -70,23 +70,22 @@ QgsOracleFeatureIterator::QgsOracleFeatureIterator( QgsOracleFeatureSource *sour
...
-        int attrIdx = mSource->mFields.lookupField( field );
         if ( !mAttributeList.contains( attrIdx ) )
           mAttributeList << attrIdx;
       }
     }
 
     // ensure that all attributes required for order by are fetched
-    const QSet< QString > orderByAttributes = mRequest.orderBy().usedAttributes();
-    for ( const QString &attr : orderByAttributes )
+    const auto orderByAttributes = mRequest.orderBy().usedAttributeIndices( mSource->mFields );
```
Comment (m-kuhn) [inline src/providers/oracle/qgsoraclefeatureiterator.cpp]: Interesting choice to switch from auto to explicit on line 73 and from explicit to auto here.

**Review by m-kuhn — APPROVED** [review]
