### PR TITLE
Only use threaded legend hit test for preview renders

### LINKED ISSUE #58496: Layout Legend Not Syncing with Atlas in QGIS 3.34 LTR and 3.38 Using PyQGIS
### What is the bug or the crash?

I've encountered an issue when using PyQGIS where the layout legend does not sync correctly with the atlas when iterating through the features using the QGIS Layout Atlas in version 3.34 LTR and the latest 3.38 release. The same procedure works flawlessly in QGIS 3.28.12.

### Steps to reproduce the issue

1. Create a print layout with an atlas enabled using PyQGIS.
2. Set up a custom legend linked to the atlas map through PyQGIS scripting.
3. Apply an atlas filter with the expression is_selected() to focus on selected features.
4. Iterate through the atlas features using PyQGIS to generate output PDFs or images.
5. Observe the legend; it does not update to reflect the current atlas feature.

### Versions

Versione di QGIS
3.38.2-Grenoble
Revisione codice QGIS
130c432394
Versione Qt
5.15.13
Versione Python
3.12.5
Versione GDAL/OGR
3.9.2
Versione PROJ
9.4.0
Versione database del Registro EPSG
v11.004 (2024-02-24)
Versione GEOS
3.12.2-CAPI-1.18.2
Versione SQLite
3.45.1
Versione PDAL
2.6.3
Versione client PostgreSQL
16.2
Versione SpatiaLite
5.1.0
Versione QWT
6.2.0
Versione QScintilla2
2.14.1
Versione SO
Windows 11 Version 2009

Plugins Python attivi
DigitizingTools
1.5.2
Hqgis
1.2.3
MemoryLayerSaver
5.0.2
pluginbuilder3
3.2.1
plugin_reloader
0.10
profiletool
4.2.6
quick_map_services
0.19.34
rectanglify
1.0.3
sit_plugin
0.1
StreetView
3.2
utility_tools
0.1
VectorBender
0.2.1
ViewshedAnalysis
1.9
web2qgis
0.2.0
db_manager
0.1.20
processing
2.12.99
lizmap
4.3.21

Versione di QGIS
3.34.10-Prizren
Revisione codice QGIS
113de9e1
Versione Qt
5.15.13
Versione Python
3.12.5
Versione GDAL/OGR
3.9.2
Versione PROJ
9.4.0
Versione database del Registro EPSG
v11.004 (2024-02-24)
Versione GEOS
3.12.2-CAPI-1.18.2
Versione SQLite
3.45.1
Versione PDAL
2.6.3
Versione client PostgreSQL
16.2
Versione SpatiaLite
5.1.0
Versione QWT
6.2.0
Versione QScintilla2
2.14.1
Versione SO
Windows 11 Version 2009

Plugins Python attivi
DigitizingTools
1.5.2
lizmap
4.3.21
MemoryLayerSaver
5.0.2
pluginbuilder3
3.2.1
plugin_reloader
0.10
profiletool
4.2.6
quick_map_services
0.19.34
rectanglify
1.0.3
sit_plugin
0.1
StreetView
3.2
utility_tools
0.1
VectorBender
0.2.1
ViewshedAnalysis
1.9
web2qgis
0.2.0
db_manager
0.1.20
otbprovider
2.12.99
processing
2.12.99
Hqgis
1.2.3

Versione di QGIS
3.28.12-Firenze
Revisione codice QGIS
dcc633b2de
Versione Qt
5.15.3
Versione Python
3.9.5
Versione GDAL/OGR
3.7.2
Versione PROJ
9.3.0
Versione database del Registro EPSG
v10.094 (2023-08-08)
Versione GEOS
3.12.0-CAPI-1.18.0
Versione SQLite
3.41.1
Versione PDAL
2.5.5
Versione client PostgreSQL
unknown
Versione SpatiaLite
5.1.0
Versione QWT
6.1.6
Versione QScintilla2
2.13.4
Versione SO
Windows 10 Version 2009

Plugins Python attivi
DigitizingTools
1.5.2
Hqgis
1.2.3
lizmap
4.3.21
MemoryLayerSaver
5.0.2
pluginbuilder3
3.2.1
plugin_reloader
0.10
profiletool
4.2.6
quick_map_services
0.19.34
rectanglify
1.0.3
sit_plugin
0.1
StreetView
3.2
utility_tools
0.1
VectorBender
0.2.1
ViewshedAnalysis
1.9
web2qgis
0.2.0
db_manager
0.1.20
otbprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Expected Behavior:
The legend should update to reflect the visible layers and features in the current atlas page as it did in QGIS 3.28.12.

Actual Behavior:
In QGIS 3.34 LTR and 3.38, when using PyQGIS, the legend does not update according to the current atlas feature. This issue breaks the expected workflow when generating atlas outputs with custom legends via scripting.

### PR DESCRIPTION
**Pull request by nyalldawson**
In other cases we'll need a blocking hit test anyway, and we run a risk of deadlocks if a non-preview render is then started on the main thread.

Fixes #58496

### CODE REVIEW

**Review by troopa81 — COMMENTED** [review]
Is this [logic](https://github.com/qgis/QGIS/blob/49017f7a431df8992f285ada692ccdaa86f49391/src/core/layout/qgslayoutitemlegend.cpp#L119) still needed ?

If this is preview,we don't wait, and if this is not, there is no thread anymore to wait with your proposal

**Comment by nyalldawson** [comment]
@troopa81 
> Is this [logic](https://github.com/qgis/QGIS/blob/49017f7a431df8992f285ada692ccdaa86f49391/src/core/layout/qgslayoutitemlegend.cpp#L119) still needed ?
> If this is preview,we don't wait, and if this is not, there is no thread anymore to wait with your proposal

Indeed it's not -- I've revised it now to what should be a safe alternative

File: src/core/layout/qgslayoutitemlegend.cpp [hunk 1]
```diff
@@ -116,7 +116,7 @@ void QgsLayoutItemLegend::paint( QPainter *painter, const QStyleOptionGraphicsIt
 
   if ( mLayout )
   {
-    if ( !mLayout->renderContext().isPreviewRender() && mLegendModel->hitTestInProgress() )
+    if ( mLegendModel->hitTestInProgress() )
     {
       mLegendModel->waitForHitTestBlocking();
     }
```
Comment (troopa81) [inline src/core/layout/qgslayoutitemlegend.cpp:122]: Shall we not remove the whole block.

My understanding is that we want to:
- in preview, use thread and don't wait at all to not block UI (the legend/paint would be refreshed when the hit test task is completed)
- on any other "mode", we don't use thread, and so there is no need to wait!

Prior to this modification, we were using thread for non-preview mode, so we needed to wait, but that's not the case anymore. Am I right?

Comment (nyalldawson) [reply src/core/layout/qgslayoutitemlegend.cpp:122]: Hm good catch -- I accidentally inverted the logic here!

Comment (nyalldawson) [reply src/core/layout/qgslayoutitemlegend.cpp]: Fixed
