### PR TITLE
fix output items placement when they are added after addition of the algorithm item (fix #48132)

### LINKED ISSUE #48132: Algorithm output node is placed half outsize model canvas
### What is the bug or the crash?

When adding a "final" Model Output to an algorithm, a new green node will be placed on the model canvas. This node gets placed in the top left corner, half outside the visible model canvas.

I use "asd" as name here:
image

# master (dd6e83b2fa6)
image

# In 3.16 and 3.24 this is fine
image

### Steps to reproduce the issue

1. Add a Model Output to a model algorithm
2. Look at where the resulting node is placed

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.1-Tisler | QGIS code branch | Release 3.24
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.4
Compiled against GDAL/OGR | 3.4.0 | Running against GDAL/OGR | 3.5.0dev-673993b9f3-dirty
PROJ version | 8.2.0
EPSG Registry database version | v10.038 (2021-10-21)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.38.2
PDAL version | 2.4.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.2.0
QScintilla2 version | 2.13.2
OS version | Arch Linux

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

I compiled master myself. 3.16 is from conda-forge. 3.24 is https://archlinux.org/packages/community/x86_64/qgis/. 
The same profile was used for all of them.

Version information for the 3.24 one:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.1-Tisler | QGIS code branch | Release 3.24
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.4
Compiled against GDAL/OGR | 3.4.0 | Running against GDAL/OGR | 3.5.0dev-673993b9f3-dirty
PROJ version | 8.2.0
EPSG Registry database version | v10.038 (2021-10-21)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.38.2
PDAL version | 2.4.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.2.0
QScintilla2 version | 2.13.2
OS version | Arch Linux

</body></html>

### PR DESCRIPTION
**Pull request by alexbruy**
## Description
When algorithm item added to a model and output is defined as well, then output item placed near the corresponding algorithm as in the image below
зображення

However, if output is not defined at this stage but added later by editing algorithm item, output item is placed at the (0,0) position.
зображення

This happens because in that case output item does not have a valid position assigned.

Fixes #48132.

### CODE REVIEW

File: src/gui/processing/models/qgsmodelgraphicsscene.cpp [hunk 1]
```diff
@@ -224,6 +224,11 @@ void QgsModelGraphicsScene::createItems( QgsProcessingModelAlgorithm *model, Qgs
     const QMap<QString, QgsProcessingModelOutput> outputs = it.value().modelOutputs();
     QMap< QString, QgsModelComponentGraphicItem * > outputItems;
 
+    // offsets from algorithm item needed to correctly place output items
+    // which does not have valid position assigned (https://github.com/qgis/QGIS/issues/48132)
+    double output_offset_x = mChildAlgorithmItems[it.value().childId()]->component()->size().width();
```
Comment (nyalldawson) [inline src/gui/processing/models/qgsmodelgraphicsscene.cpp:229]: Would be good to retrieve `mChildAlgorithmItems[it.value().childId()]` once upfront and store in a variable for access elsewhere in this block (avoiding multiple map lookups)

Comment (nyalldawson) [inline src/gui/processing/models/qgsmodelgraphicsscene.cpp:229]:
```suggestion
    const double outputOffsetX = mChildAlgorithmItems[it.value().childId()]->component()->size().width();
```

File: src/gui/processing/models/qgsmodelgraphicsscene.cpp [hunk 2]
```diff
@@ -224,6 +224,11 @@ void QgsModelGraphicsScene::createItems( QgsProcessingModelAlgorithm *model, Qgs
...
+    double output_offset_y = 1.5 * mChildAlgorithmItems[it.value().childId()]->component()->size().height();
```
Comment (nyalldawson) [inline src/gui/processing/models/qgsmodelgraphicsscene.cpp:230]:
```suggestion
    const double outputOffsetY = 1.5 * mChildAlgorithmItems[it.value().childId()]->component()->size().height();
```

Comment (alexbruy) [reply src/gui/processing/models/qgsmodelgraphicsscene.cpp]: We can't mark `outputOffsetY` as `const` as it will be modified later in line 248 to allow correct placement of multiple outputs (if algorithm has more than one).

File: src/gui/processing/models/qgsmodelgraphicsscene.cpp [hunk 3]
```diff
@@ -224,6 +224,12 @@ void QgsModelGraphicsScene::createItems( QgsProcessingModelAlgorithm *model, Qgs
     const QMap<QString, QgsProcessingModelOutput> outputs = it.value().modelOutputs();
     QMap< QString, QgsModelComponentGraphicItem * > outputItems;
 
+    // offsets from algorithm item needed to correctly place output items
+    // which does not have valid position assigned (https://github.com/qgis/QGIS/issues/48132)
+    QgsProcessingModelComponent *algItem = mChildAlgorithmItems[it.value().childId()]->component();
+    const double output_offset_x = algItem->size().width();
```
Comment (nyalldawson) [inline src/gui/processing/models/qgsmodelgraphicsscene.cpp:230]:
```suggestion
    const double outputOffsetX = algItem->size().width();
```

File: src/gui/processing/models/qgsmodelgraphicsscene.cpp [hunk 4]
```diff
@@ -224,6 +224,12 @@ void QgsModelGraphicsScene::createItems( QgsProcessingModelAlgorithm *model, Qgs
...
+    double output_offset_y = 1.5 * algItem->size().height();
```
Comment (nyalldawson) [inline src/gui/processing/models/qgsmodelgraphicsscene.cpp:231]:
```suggestion
    double outputOffsetY = 1.5 * algItem->size().height();
```

File: src/gui/processing/models/qgsmodelgraphicsscene.cpp [hunk 5]
```diff
@@ -232,7 +238,15 @@ void QgsModelGraphicsScene::createItems( QgsProcessingModelAlgorithm *model, Qgs
...
       connect( item, &QgsModelComponentGraphicItem::aboutToChange, this, &QgsModelGraphicsScene::componentAboutToChange );
 
-      const QPointF pos = outputIt.value().position();
+      // if output added not at the same time as algorithm then it does not have
+      // valid position and will be placed at (0,0). We need to calculate better position.
+      // See https://github.com/qgis/QGIS/issues/48132.
+      QPointF pos = outputIt.value().position();
+      if ( pos.isNull() )
+      {
+        pos = algItem->position() + QPointF( output_offset_x, output_offset_y );
```
Comment (nyalldawson) [inline src/gui/processing/models/qgsmodelgraphicsscene.cpp:247]:
```suggestion
        pos = algItem->position() + QPointF( outputOffsetX, outputOffsetY );
```

File: src/gui/processing/models/qgsmodelgraphicsscene.cpp [hunk 6]
```diff
@@ -232,7 +238,15 @@ void QgsModelGraphicsScene::createItems( QgsProcessingModelAlgorithm *model, Qgs
...
+        output_offset_y += 1.5 * outputIt.value().size().height();
```
Comment (nyalldawson) [inline src/gui/processing/models/qgsmodelgraphicsscene.cpp:248]:
```suggestion
```

Comment (nyalldawson) [inline src/gui/processing/models/qgsmodelgraphicsscene.cpp:248]:
```suggestion
        outputOffsetY += 1.5 * outputIt.value().size().height();
```

**Review by nyalldawson — APPROVED** [review]

**Comment by kannes** [comment]
Thank you @alexbruy!
