### PR TITLE
Use a `QgsScrollArea` when adding or inserting pages to `QgsOptionsDialogBase` 

### LINKED ISSUE #32021: Dialog windows are too tall for some screens, rendering them unusable
**Describe the bug**
An almost fatal UX problem just occurred in a QGIS workshop I was helping with.
The machines had a resolution of 1366x768.
This made several windows (I remember the Options and IIRC the CRS dialog) unusable for the participants as the "OK", "Cancel" control buttons were outside the visible display area.

The workaround was to resize the window from the top and then dragging it up until the buttons were visible. This is not what a user should have to do (and it took me a while to even think of as a workaround).

**How to Reproduce**

1. Set your monitor resolution to have a maximum of 768 pixels of height
2. Start QGIS with a clean profile
3. Enter the options
4. Notice that you cannot see the "OK" and "Cancel" buttons.

Please make sure that  by default no dialogs are set to a vertical height that is leading to this problem on a fresh start with a default QGIS installation.

**Additional context**
QGIS 3.8 on Windows

There was a report for the Layer Properties dialog at https://github.com/qgis/QGIS/issues/28153 but the user decided it was a non-issue. I disagree! >:)

A vertical resolution of 768 pixels is still very widespread. The Steam hardware survey (for gamers!) shows almost 12% of their users with 1366x768.

### PR DESCRIPTION
**Pull request by uclaros**
## Description
Most pages in `QgsOptions` encapsulate their contents within a hard coded `QgsScrollArea` to allow for scrollbars when shrinking.
However, many pages in options and other subclasses use the `QgsOptionsDialogBase::insertPage` or `QgsOptionsDialogBase::addPage` and force a minimum height to the parent dialog which is often quite big. This can also happen by plugins that add a page to the project properties or options dialog.
With this PR, all pages added with those methods are wrapped around a `QgsScrollArea` and now all `QgsOptionsDialogBase` derived dialogs can be resized to fit in smaller screens.

Peek 2024-01-24 18-07

Properly fixes the already closed #32021

### CODE REVIEW

File: src/gui/qgsoptionsdialogbase.cpp [hunk 1]
```diff
@@ -396,10 +397,15 @@ void QgsOptionsDialogBase::addPage( const QString &title, const QString &tooltip
       mOptTreeModel->appendRow( item );
   }
 
+  QgsScrollArea *scrollArea = new QgsScrollArea();
+  scrollArea->setWidgetResizable( true );
+  scrollArea->setFrameShape( QFrame::NoFrame );
+  scrollArea->setWidget( widget );
```
Comment (nyalldawson) [inline src/gui/qgsoptionsdialogbase.cpp:403]: Should we first check if widget isn't a QScrollArea or is a widget with a layout which directly contains a QScrollArea first? I'm not sure what happens when you place a scrollarea directly inside a scroll area, but I'm sure it's not pretty...

Comment (uclaros) [reply src/gui/qgsoptionsdialogbase.cpp:403]: It actually works fine. No visual nor behavioral artifact for me. I'd suggest we just remove the scrollareas from existing pages for cleaner code and not sweat about the odd nested scroll area left over or added by a plugin.

Comment (nyalldawson) [reply src/gui/qgsoptionsdialogbase.cpp:403]: ok, fair enough!

**Review by nyalldawson — APPROVED** [review]

**Comment by agiudiceandrea** [comment]
Hi @uclaros, please see https://github.com/qgis/QGIS/issues/56381. I think that issue may be related to this PR.

**Comment by uclaros** [comment]
Good catch!
#56384 should fix this

**Comment by agiudiceandrea** [comment]
Thank you for your super fast fix!
