### PR TITLE
fix classification of singleband pseudocolor (#43346)

### LINKED ISSUE #43346: Automatic classification of singleband pseudocolor uses wrong class breaks/range
**Describe the bug**
The automatic classification of a singleband pseudocolor style gives different results depending on which band was styled beforehand. It seems like the class breaks are kept from the previous band or something.

**How to Reproduce**

1. Load the grib file from https://www.dwd.de/DE/leistungen/gribdaten/grib_beispiel_01.zip?__blob=publicationFile&v=2 (I noticed the bug before on a multiband TIFF, it is probably format agnostic)
2. Switch to a singleband pseudocolor style
3. Iterate through the bands using the dropdown going band 1 -> 2
4. Band 2 will be displayed with a range of about -3 to 16
5. Iterate through the bands using the dropdown going band 3 -> 2
6. Band 2 will be displayed with a range of about -99800 to 123000

It does not matter if the min/max value settings are set to "estimate" or "actual".

I made a video where I scrolled the mousewheel on the dropdown. You can see the resulting class breaks and visualisation depends on from which directing I select band 2.

https://user-images.githubusercontent.com/7661092/119225749-08fe1800-bb06-11eb-978a-36217d567d35.mp4

**QGIS and OS versions**

QGIS version | 3.19.0-Master | QGIS code revision | 9da78ed2e4a
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.0dev-9f57a8d3c5-dirty
PROJ version | 8.0.1
EPSG Registry database version | v10.018 (2021-04-02)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.5
PostgreSQL client version | 13.2
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.12.1
OS version | Arch Linux

### PR DESCRIPTION
**Pull request by vcloarec**
fix #43346 that was introduced by #36376
Also fix the color ramp shader that was not filled when the Singleband pseudocolor renderer became the active renderer.

### CODE REVIEW

File: src/gui/raster/qgssinglebandpseudocolorrendererwidget.cpp [hunk 1]
```diff
@@ -190,6 +190,9 @@ void QgsSingleBandPseudoColorRendererWidget::loadMinMax( int bandNo, double min,
 {
   QgsDebugMsg( QStringLiteral( "theBandNo = %1 min = %2 max = %3" ).arg( bandNo ).arg( min ).arg( max ) );
 
+  QString oldMinTextvalue = mMinLineEdit->text();
+  QString oldMaxTextvalue = mMaxLineEdit->text();
```
Comment (nyalldawson) [inline src/gui/raster/qgssinglebandpseudocolorrendererwidget.cpp:194]:
```suggestion
  const QString oldMinTextvalue = mMinLineEdit->text();
  const QString oldMaxTextvalue = mMaxLineEdit->text();
```

**Review by nyalldawson — APPROVED** [review]

**Review by troopa81 — APPROVED** [review]
