### PR TITLE
Fix refactor fields : "Load from layer" did not load source expression in the model designer context (fix #62687)

### LINKED ISSUE #62687: Model Designer Refactor Fields algorithm issue in 3.44
### What is the bug or the crash?

Model Designer Refactor Fields algorithm does not fill Source Expression (v 3.44) from loaded Template layer as it did in previous versions (eg 3.42) - have to fill them manually. Refactor Fields in Toolbox is not affected.

### Steps to reproduce the issue

1. Have a layer open in Map window
2. Open Model Designer
3. Drag Refactor Fields into designer area
4. Load map window layer as template layer

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.44.1-Solothurn</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/c8b94a2061d">c8b94a2061d</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.13</td></tr><tr><td>Python version</td><td>3.12.11</td></tr><tr><td>GDAL version</td><td>3.11.3 — <i>Eganville</i></td></tr><tr><td>PROJ version</td><td>9.6.2</td></tr><tr><td>EPSG Registry database version</td><td>v12.013 (2025-05-26)</td></tr><tr><td>GEOS version</td><td>3.13.1-CAPI-1.19.2</td></tr><tr><td>SQLite version</td><td>3.46.1</td></tr><tr><td>PDAL version</td><td>2.9.0</td></tr><tr><td>PostgreSQL client version</td><td>17.3</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.3.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Windows 10 Version 2009</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>CalculateGeometry</td><td>0.6.10</td></tr><tr><td>easy_print_menu</td><td>1.3.0</td></tr><tr><td>gazetteer_creator</td><td>0.1.1</td></tr><tr><td>MapsPrinter</td><td>1.0</td></tr><tr><td>qfieldsync</td><td>v4.14.1</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ValentinBuira**
## Description

See title and fix #62687

### CODE REVIEW

File: src/gui/processing/qgsprocessingfieldmapwidgetwrapper.h [hunk 1]
```diff
@@ -48,6 +48,14 @@ class GUI_EXPORT QgsProcessingFieldMapPanelWidget : public QgsPanelWidget, priva
      */
     void registerExpressionContextGenerator( const QgsExpressionContextGenerator *generator );
 
+    /**
+     * Set the processing mode type for the widget
+     * Used to change the behavior of the widget when set to Qgis::ProcessingMode::Modeler.
+     *
+     * \since QGIS 3.44.8
```
Comment (CeliaBuira) [inline src/gui/processing/qgsprocessingfieldmapwidgetwrapper.h:55]: the bug is also in the 3.44 branch and I'd like to backport it, so I put the \since tag to 3.44.8 let me know if it's wrong

**Comment by CeliaBuira** [comment]
Hi @elpaso, you might be interested to review this one since it was introduced while fixing #62019

**Review by nyalldawson — APPROVED** [review]
