### PR TITLE
Fix wkbType cast from OGR 25D Type.

### LINKED ISSUE #50218: wkbType of geometries is not same as the layer with z and with geopackage
### What is the bug or the crash?

When geometries are fetch from a Geopackage table with Z, the `wkbType` of geometries are 25D type (`0x80000001`) while the `wkbType` of the layer is Z (`10XX`). The problem is not present with other providers like shapefile or PostGis, nor when there is no Z or when there is ZM.

### Steps to reproduce the issue

1. Create a new table in a Geopackage with Z (but without M)
2. Create a new geometry, but without save the layer
3. Open the python console and execute `[f.geometry().wkbType() for f in iface.activeLayer().getFeatures()]`
   -> The print displays : `[1003]`
5. Save the layer
6. Execute `[f.geometry().wkbType() for f in iface.activeLayer().getFeatures()]`
   -> The print displays : `[-2147483645]`
7. Execute `iface.activeLayer().wkbType()`
   -> The print displays : `1003`

[Peek 15-09-2022 15-11.webm](https://user-images.githubusercontent.com/37629967/190412979-74d1cb2b-ede5-4e13-9c2c-e769c8c9c056.webm)

### Versions

3.22, 3.26 and master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lbartoletti**
## Description

As mentionned by @Koyaani a PolygonZ is opened as a Polygon25D and can cause problems.

This fix use the QgsOgrUtils method to return the true QGIS wkbType.

Fixes https://github.com/qgis/QGIS/issues/50218

### CODE REVIEW

**Review by rouault — APPROVED** [review]

**Comment by rouault** [comment]
failed tests:
```
 FAIL!  : TestQgsOgrUtils::ogrGeometryToQgsGeometry2(linestringz) Compared values are not the same
   Actual   (static_cast< int >( geom.wkbType() )): 1002
   Expected (type)                                : -2147483646
   Loc: [/root/QGIS/tests/src/core/testqgsogrutils.cpp(243)]
PASS   : TestQgsOgrUtils::ogrGeometryToQgsGeometry2(linestringm)
PASS   : TestQgsOgrUtils::ogrGeometryToQgsGeometry2(linestringzm)
FAIL!  : TestQgsOgrUtils::ogrGeometryToQgsGeometry2(linestring25d) Compared values are not the same
   Actual   (static_cast< int >( geom.wkbType() )): 1002
   Expected (type)                                : -2147483646
   Loc: [/root/QGIS/tests/src/core/testqgsogrutils.cpp(243)]
```

File: tests/src/core/testqgsogrutils.cpp [hunk 1]
```diff
@@ -212,10 +212,10 @@ void TestQgsOgrUtils::ogrGeometryToQgsGeometry2_data()
   QTest::newRow( "point25d" ) << QStringLiteral( "Point25D (1.1 2.2 3.3)" ) <<  static_cast< int >( QgsWkbTypes::Point25D );
 
   QTest::newRow( "linestring" ) << QStringLiteral( "LineString (1.1 2.2, 3.3 4.4)" ) << static_cast< int >( QgsWkbTypes::LineString );
-  QTest::newRow( "linestringz" ) << QStringLiteral( "LineStringZ (1.1 2.2 3.3, 4.4 5.5 6.6)" ) <<  static_cast< int >( QgsWkbTypes::LineString25D ); // ogr uses 25d for z
+  QTest::newRow( "linestringz" ) << QStringLiteral( "LineStringZ (1.1 2.2 3.3, 4.4 5.5 6.6)" ) <<  static_cast< int >( QgsWkbTypes::LineStringZ ); // ogr uses 25d for z
```
Comment (agiudiceandrea) [inline tests/src/core/testqgsogrutils.cpp:215]: The comment is now obsolete, isn't it?

Comment (lbartoletti) [reply tests/src/core/testqgsogrutils.cpp:215]: Oh, yes! I forgot to remove this one. Thanks.
