### PR TITLE
Point cloud LAS extra bytes infos reading

### LINKED ISSUE #46234: Extra bytes attributes get loaded but QGIS parses values as zeros
### What is the bug or the crash?

The following file contains a couple of "extra bytes" attributes - Amplitude, Reflectance, Deviance. The file gets correctly indexed by untwine and the extra attributes can be selected for rendering, but all values from those attributes are read as zero (I have verified in CloudCompare they are not zeros):
https://filkassen.statens-it.dk/u/zUxXZINMV3_fTFdm/1km_6210_527.laz?l

This happens for both identify tool and rendering - looks like we are not parsing the values correctly.

### Steps to reproduce the issue

1. load the test file in QGIS
2. set attribute by ramp rendering e.g. to Reflectance
3. all points get the same color (as if the all values were zero)

### Versions

3.22

### PR DESCRIPTION
**Pull request by NEDJIMAbelgacem**
## Description
Fixes https://github.com/qgis/QGIS/issues/46234 by adding necessary code to read LAS extrabytes.

### CODE REVIEW

File: src/core/pointcloud/qgseptdecoder.cpp [hunk 1]
```diff
@@ -404,8 +455,21 @@ QgsPointCloudBlock *__decompressLaz( FileType &file, const QgsPointCloudAttribut
     }
     else
     {
-      // this can possibly happen -- e.g. if a style built using a different point cloud format references an attribute which isn't available from the laz file
-      requestedAttributeDetails.emplace_back( RequestedAttributeDetails( LazAttribute::MissingOrUnknown, requestedAttribute.type(), requestedAttribute.size() ) );
+      bool foundAttr = false;
+      for ( QgsEptDecoder::ExtraBytesAttributeDetails &eba : extrabytesAttr )
+      {
+        if ( requestedAttribute.name().compare( eba.attribute.trimmed() ) == 0 )
```
Comment (uclaros) [inline src/core/pointcloud/qgseptdecoder.cpp:461]: Are extra byte attributes case sensitive / should we handle them as such?

File: src/core/pointcloud/qgseptdecoder.h [hunk 2]
```diff
@@ -24,19 +24,173 @@
...
   QgsPointCloudBlock *decompressZStandard( const QString &filename, const QgsPointCloudAttributeCollection &attributes, const QgsPointCloudAttributeCollection &requestedAttributes, const QgsVector3D &scale, const QgsVector3D &offset );
   QgsPointCloudBlock *decompressZStandard( const QByteArray &data, const QgsPointCloudAttributeCollection &attributes, const QgsPointCloudAttributeCollection &requestedAttributes, const QgsVector3D &scale, const QgsVector3D &offset );
   QgsPointCloudBlock *decompressLaz( const QString &filename, const QgsPointCloudAttributeCollection &attributes, const QgsPointCloudAttributeCollection &requestedAttributes, const QgsVector3D &scale, const QgsVector3D &offset );
   QgsPointCloudBlock *decompressLaz( const QByteArray &data, const QgsPointCloudAttributeCollection &attributes, const QgsPointCloudAttributeCollection &requestedAttributes, const QgsVector3D &scale, const QgsVector3D &offset );
+
+  //! Returns the list of extrabytes attributes with their type, size and offsets represented in the LAS file
+  template<typename FileType>
+  QVector<QgsEptDecoder::ExtraBytesAttributeDetails> readExtraByteAttributes( FileType &file )
```
Comment (uclaros) [inline src/core/pointcloud/qgseptdecoder.h:54]: Do we need this as a separate function? There's already a `laszip::io::reader::basic_file<FileType>` which could be used when this function is called.

If yes, can the code be moved to the cpp file instead?

**Review by uclaros — COMMENTED** [review]
I feel like the extra byte attribute extraction should have been handled by lazperf, like it's done for normal attributes. Do we know if they plan on implementing the handling on their side any time soon?

File: src/core/pointcloud/qgseptdecoder.h (hunk 2 above)
Comment (NEDJIMAbelgacem) [reply src/core/pointcloud/qgseptdecoder.h:54]: I wanted to do this in a seperate function to test it properly and make it modular.
As for reusing laszip::io::reader::basic_file<FileType>, I prefer not to use the internals of the laszip library since it doesn't give us the freedom of management that std file streams does.

**Comment by NEDJIMAbelgacem** [comment]
> I feel like the extra byte attribute extraction should have been handled by lazperf, like it's done for normal attributes. Do we know if they plan on implementing the handling on their side any time soon?

I already asked about that and it is a PITA to try to extract the extrabytes using lazperf. The library just decodes the point records and doesn't give the extra bytes attribute details. Hobu guys suggested that I read the data myself since it is not encoded.

File: src/core/pointcloud/qgseptdecoder.h (hunk 2 above)
Comment (NEDJIMAbelgacem) [reply src/core/pointcloud/qgseptdecoder.h:54]: That function is a template and I can't put its definition inside the .cpp file.

**Review by uclaros — APPROVED** [review]
