### PR TITLE
Server WMS fix case sensistive REQUEST

### LINKED ISSUE #32354: QGIS Server understands only UpperCamelCase for URL parameters
**Describe the bug**

QGIS Server understands only UpperCamelCase for parameters.

`http://qgis.server/ltr?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities` is working.

`http://qgis.server/ltr?SERVICE=WMS&VERSION=1.3.0&REQUEST=GETCAPABILITIES` is not working.

```
<ServiceExceptionReport version="1.3.0"><ServiceException code="OperationNotSupported">Request GETCAPABILITIES is not supported</ServiceException></ServiceExceptionReport>
```

**QGIS and OS versions**

It's compiled version of 3.4.12 that I'm using, this is the version from the Desktop app

Version de QGIS | 3.4.12-Madeira | Révision du code | Révision du code
-- | -- | -- | --
Compilé avec Qt | 5.12.2 | Utilisant Qt | 5.12.2
Compilé avec GDAL/OGR | 2.4.0 | Utilisé avec GDAL/OGR | 2.4.0
Compilé avec GEOS | 3.7.1-CAPI-1.11.1 | Utilisé avec GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Version du client PostgreSQL | 12.0 (Ubuntu 12.0-1.pgdg19.04+1) | SpatiaLite Version | 4.3.0a
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.10.4
Compilé avec PROJ | 5.2.0 | Fonctionne avec PROJ | Rel. 5.2.0, September 15th, 2018
Active python plugins | qgis-analyse-itv-rerau-plugin; raepa; go2mapillary; plugin_reloader; french_locator_filter; firstaid; Qgis-Plugin-Builder; lizmap; QgisLayerBoardPlugin; qgis_drain_sewer_visual_inspection; QuickOSM; processing; db_manager

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #32354

### CODE REVIEW

**Review by sbrunner — APPROVED** [review]
Thanks :-)

File: src/server/services/wms/qgswms.cpp [hunk 1]
```diff
@@ -34,7 +34,7 @@
 #include "qgswmsparameters.h"
 
 #define QSTR_COMPARE( str, lit )\
-  (str.compare( QLatin1String( lit ), Qt::CaseInsensitive ) == 0)
+  (str.compare( QStringLiteral( lit ), Qt::CaseInsensitive ) == 0)
```
Comment (m-kuhn) [inline src/server/services/wms/qgswms.cpp]: I see you are changing these all recently. I remember having read that `QLatin1String` is preferable where overloads for it exist. Has that changed or was that never true?

Comment (elpaso) [reply src/server/services/wms/qgswms.cpp]: I'm not sure, I've read this: https://www.qt.io/blog/2014/06/13/qt-weekly-13-qstringliteral apparently it's more efficient whenever it must be converted to QString, but you are right, it's probably be more efficient in case of overloads.

**Review by rldhont — APPROVED** [review]

**Comment by Gustry** [comment]
Thanks @elpaso for the quick fix.

File: src/server/services/wms/qgswms.cpp (hunk 1 above)
Comment (elpaso) [reply src/server/services/wms/qgswms.cpp]: reverted

**Comment by rldhont** [comment]
Merge after thaw with manually backport or merge now with auto backport ?

**Comment by elpaso** [comment]
@rldhont would you take care of the backport please?

**Comment by rldhont** [comment]
@elpaso yes I will do it.

**Comment by elpaso** [comment]
@rldhont thank you :+1:

**Comment by rldhont** [comment]
@elpaso backport done
