### PR TITLE
Fix SQL expression compiler plus operator with strings

### LINKED ISSUE #58875: Deleting "all other values" breaks categorise symbology
### What is the bug or the crash?

A video to explain 
2024-09-26_08-37-52_qgis-ltr-bin_579

It's like this issue https://github.com/qgis/QGIS/issues/43651but it's not related to datetime attribute 

### Steps to reproduce the issue

    Create layer with 2 fields
    Create few features 
    Create a categorised symbology using expressions: "field1" + "field2"
    Uncheck "all other values" in symbologie

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Version de QGIS | 3.34.10-Prizren | Révision du code | 113de9e1
-- | -- | -- | --
Version de Qt | 5.15.13
Version de Python | 3.12.5
Version de GDAL/OGR | 3.9.2
Version de Proj | 9.4.0
Version de la base de données du registre EPSG | v11.004 (2024-02-24)
Version de GEOS | 3.12.2-CAPI-1.18.2
Version de SQLite | 3.45.1
Version de PDAL | 2.6.3
Version du client PostgreSQL | 16.2
Version de SpatiaLite | 5.1.0
Version de QWT | 6.2.0
Version de QScintilla2 | 2.14.1
Version de l'OS | Windows 10 Version 2009
  |   |   |  
Extensions Python actives
clipper | 1.2
DigitizingTools | 1.5.2
LienBDDico | version 1.0
LinearReferencing | 1.0.2
linking_relation_editor | v1.4.0
LocatePoints | 0.3.4
lrs | 1.2.3
lrseditor | 1.3.1
qchainage | 3.0.1
QlrBrowser | 3.0.0
segment_reshape_plugin | 0.1.6
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>Version de QGIS
3.34.10-Prizren
Révision du code
[113de9e1](https://github.com/qgis/QGIS/commit/113de9e1)
Version de Qt
5.15.13
Version de Python
3.12.5
Version de GDAL/OGR
3.9.2
Version de Proj
9.4.0
Version de la base de données du registre EPSG
v11.004 (2024-02-24)
Version de GEOS
3.12.2-CAPI-1.18.2
Version de SQLite
3.45.1
Version de PDAL
2.6.3
Version du client PostgreSQL
16.2
Version de SpatiaLite
5.1.0
Version de QWT
6.2.0
Version de QScintilla2
2.14.1
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
clipper
1.2
DigitizingTools
1.5.2
LienBDDico
version 1.0
LinearReferencing
1.0.2
linking_relation_editor
v1.4.0
LocatePoints
0.3.4
lrs
1.2.3
lrseditor
1.3.1
qchainage
3.0.1
QlrBrowser
3.0.0
segment_reshape_plugin
0.1.6
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Fix #58875

### CODE REVIEW

File: src/core/qgssqlexpressioncompiler.cpp [hunk 1]
```diff
@@ -93,6 +93,42 @@ QgsSqlExpressionCompiler::Result QgsSqlExpressionCompiler::compileNode( const Qg
...
+      case QgsExpressionNode::ntColumnRef:
+      {
+        const QgsExpressionNodeColumnRef *col = static_cast<const QgsExpressionNodeColumnRef *>( node );
+        const int idx = mFields.indexFromName( col->name() );
+        return idx >= 0 && mFields[idx].isNumeric();
+      }
+      case QgsExpressionNode::ntLiteral:
+      {
+        const QgsExpressionNodeLiteral *lit = static_cast<const QgsExpressionNodeLiteral *>( node );
+        return lit->value().type() == QVariant::Double || lit->value().type() == QVariant::Int;
```
Comment (nyalldawson) [inline src/core/qgssqlexpressioncompiler.cpp:113]: How about moving the variant type comparison logic from QgsField::isNumeric to something like QgsVariantUtils::isNumericType and using here? Otherwise you'll also need to add checks manually here for LongLong, ULongLong & Uint

Comment (elpaso) [reply src/core/qgssqlexpressioncompiler.cpp]: I have opted for QgsVariantUtils::isNumericType but I am not sure about how to handle bool an Char, can you please give me an advice? See https://github.com/qgis/QGIS/pull/58916/commits/61935ad591d7cf34ba1b7791536f1a434d8e30b2#diff-ce9de7392278448888de27a62f580122579719433636c7e0aed544a0c7004549R485 and the test.

Comment (nyalldawson) [reply src/core/qgssqlexpressioncompiler.cpp]: I'd lean toward false there (my gut feeling is that the more common use case would be storing a single text character rather than a number), but don't have a strong opinion.

Comment (nyalldawson) [reply src/core/qgssqlexpressioncompiler.cpp]: I'll approve as is

**Review by nyalldawson — APPROVED** [review]
