### PR TITLE
[ux] Fix and harmonize drag and drop in Graduated, Categorized and Point Cloud classification symbol lists

### LINKED ISSUE #50823: Drag and drop of symbology classes is buggy
### What is the bug or the crash?

When one drag'n'drops classes in a symbology list of classes, they often do not end up where one dropped them. Instead they often get appended to the very bottom of the list.

https://user-images.githubusercontent.com/7661092/200544966-0fcde20d-1a2f-4155-b97c-6f80e960fda3.mp4

This happens both in the Layer Styling Panel or in the Layer Properties -> Style dialog tab.
This happens for at least the Graduated and Categorized styling. It does not happen for Rule-Based styling.

I tried to find the exact indicator positions that cause this but it was not 100% deterministic. It seems to depend also on the location of the item receiving the drop relative to the dragged item. And it is probably pixel-perfect dropping.

### Steps to reproduce the issue

1. Load "world" dataset or any other vector layer
1. Style by categories or graduated
1. Drag a class to a different position in the list of classes
1. The class might be dropped to the bottom of the list of classes instead at the indicated position, try again if not

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.0-Firenze | QGIS code revision | ed3ad0430f
-- | -- | -- | --
Qt version | 5.15.3

</body></html>QGIS version
3.28.0-Firenze
QGIS code revision
[ed3ad0430f](https://github.com/qgis/QGIS/commit/ed3ad0430f)
Qt version
5.15.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

This might be about a bad handling of https://doc.qt.io/qt-5/qabstractitemview.html#DropIndicatorPosition-enum I think. I found no relevant matches (e. g. for "AboveItem" or "BelowItem") in the sources though, maybe it is handled differently.

### LINKED ISSUE #55267: Cannot move legend items when classifying
### What is the bug or the crash?

When trying to rearrange items in the 'classify' list, they refuse to move or be rearranged, sometimes instead moving to the end of the list:

image

Since the items cannot be sorted directly, as they include a unit, they must be manually drag-dropped to the correct location, and this does not work.

### Steps to reproduce the issue

1. Add a layer
2. Select 'Properties', 'Symbology', and use 'Classified' to add data to the layer colour
3. Click 'Classify' and try to manually rearrange the items

### Versions

QGIS version | 3.32.3-Lima | QGIS code revision | 67d46100b5b
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 13.4

Active Python plugins
processing | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### LINKED ISSUE #60559: [ux] Drag and drop in Point cloud classification is confusing
### What is the bug or the crash?

Sometimes, when dropping an item in between of other items, the dropped item ends up being appended, i.e., in the end of the list.

https://github.com/user-attachments/assets/6efe5b03-9980-4d5e-9765-66ba499cd57f

### Steps to reproduce the issue

1. Load a Point Cloud dataset.
2.  Go to Layer styling panel (or page in Vector properties dialog).
3. If needed, choose Classification and click on Classify.
4. Attempt to move items via drag and drop.
5. Sooner or later an item will be appended when it's supposed to be placed in between of other items.

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.41.0-Master</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/a2c702ab5e4">a2c702ab5e4</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.13</td></tr><tr><td>Python version</td><td>3.12.3</td></tr><tr><td>GDAL/OGR version</td><td>3.8.4</td></tr><tr><td>PROJ version</td><td>9.4.0</td></tr><tr><td>EPSG Registry database version</td><td>v11.004 (2024-02-24)</td></tr><tr><td>GEOS version</td><td>3.12.1-CAPI-1.18.1</td></tr><tr><td>SQLite version</td><td>3.45.1</td></tr><tr><td>PostgreSQL client version</td><td>unknown</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.1.4</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Ubuntu 24.04.1 LTS</td></tr><tr><td colspan="2"><i>This copy of QGIS writes debugging output.</i></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>loadthemall</td><td>3.4</td></tr><tr><td>mapswipetool_plugin</td><td>1.3</td></tr><tr><td>AppendFeaturesToLayer</td><td>2.0.0</td></tr><tr><td>linking_relation_editor</td><td>v1.4.0</td></tr><tr><td>QgisModelBaker</td><td>v7.10.6</td></tr><tr><td>quick_map_services</td><td>0.19.36</td></tr><tr><td>qfieldsync</td><td>v4.12.0</td></tr><tr><td>french_locator_filter</td><td>1.1.1</td></tr><tr><td>pzp</td><td>0.0.3</td></tr><tr><td>swiss_locator</td><td>4.0.0</td></tr><tr><td>pg_service_parser</td><td>0.6.0</td></tr><tr><td>firstaid</td><td>3.2.0</td></tr><tr><td>InvisibleLayersAndGroups</td><td>2.2</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>processing</td><td>2.12.99</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gacarrillor**
This PR fixes an annoying and longstanding issue with drag and drop in Graduated and Categorized symbol lists.
Namely, when attempting to move an item and realizing it would end up in the last position (i.e., being appended).

BEFORE:

https://github.com/user-attachments/assets/c0ec9a68-56aa-4173-8ae8-3f82c8f7848d

AFTER:

https://github.com/user-attachments/assets/936a81f1-0d5b-462c-bf57-5d307da13cec

BONUS:
It also happens in Point Clouds --> Layer Styling --> Classification. This PR also fixes that one.

Fix #50823
Fix #55267 
Fix #60559 

EXTRA BONUS:
 + Harmonize drag and drop of multiple items: sort them because they may come unsorted due to selection order, which then makes it lose the order after the drop. (Unreported so far).
 + Harmonize selection after drag and drop: Clear selection in Point Clouds classification list.

### CODE REVIEW

**Comment by gacarrillor** [comment]
I took the opportunity to add two more changes to finish the harmonization work on drag'n'drops of flat symbol lists.
This PR is ready now :)

File: src/gui/pointcloud/qgspointcloudclassifiedrendererwidget.h [hunk 1]
```diff
@@ -70,6 +70,9 @@ class GUI_EXPORT QgsPointCloudClassifiedRendererModel : public QAbstractItemMode
   signals:
     void categoriesChanged();
 
+    //! Informs views that categories were moved (e.g., via mCategories.move()) in the model.
+    void categoriesMoved();
```
Comment (signedav) [inline src/gui/pointcloud/qgspointcloudclassifiedrendererwidget.h:74]: I think in the categorysymbolrenderer this is called rowsMoved. As far as I understand this is doing the same, right? So why don't keep the same name?

Comment (gacarrillor) [reply src/gui/pointcloud/qgspointcloudclassifiedrendererwidget.h:74]: Right, I was trying to avoid a [clazy warning](https://github.com/KDE/clazy/blob/1.11/docs/checks/README-overloaded-signal.md) on overloaded signals from `QAbstractItemModel::rowsMoved()`. But I think it makes sense to change it to `rowsMoved()` to keep consistency and live with the warning as the other 2 classes that you mentioned do. What do you think? Are you OK if I force a push to amend it?

Comment (signedav) [reply src/gui/pointcloud/qgspointcloudclassifiedrendererwidget.h:74]: Well I find it very confusing when similar classes have signals doing exactly the same but are named different. So I would prefer the consequent naming over clazy. But I'm not sure how it should be handled so I ping @m-kuhn whether he knows...

Comment (m-kuhn) [reply src/gui/pointcloud/qgspointcloudclassifiedrendererwidget.h:74]: I don't know if there's an official rule. Slight tendance for following existing patterns and silencing the warning

Comment (gacarrillor) [reply src/gui/pointcloud/qgspointcloudclassifiedrendererwidget.h]: I did `push -f` replacing `categoriesMoved()` by `rowsMoved()`, thanks!

**Review by signedav — APPROVED** [review]
