### PR TITLE
Amend sprite retrieval (qgis#43925)

### LINKED ISSUE #43925: Vector Tile sprite URL is incorrectly interpreted when query parameters are present
Where the sprite URL provided by a Vector Tile style file contains query parameters, QGIS does not add the resolution or file extension to it correctly.  This results in HTTP 404 responses when QGIS attempts to retrieve the sprite.

For example, where access to a vector tile service is secured via API key, a sprite URL provided in the style may include a query parameter, e.g.:
`"sprite": "https://remote.server.address/vector/tile/service/styles?key=0123456789"`

QGIS treats this as a string and blindly appends a resolution and file extension, resulting in an incorrect URL:
`https://remote.server.address/vector/tile/service/styles?key=0123456789@2x.json`

The correct behaviour would be for QGIS to append these values to the path:
`https://remote.server.address/vector/tile/service/styles@2x.json?key=0123456789`

|  |  |
------|------
| QGIS version | 3.20.0-Odense |
| QGIS code revision | decaadbb31 |
| Qt version | 5.15.2 |
| Python version | 3.9.5 |
| GDAL/OGR version | 3.3.0 |
| PROJ version | 8.0.1 |
| EPSG Registry database version | v10.018 (2021-04-02) |
| GEOS version | 3.9.1-CAPI-1.14.2 |
| SQLite version | 3.35.2 |
| PDAL version | 2.3.0 |
| PostgreSQL client version | 13 |
| SpatiaLite version | 5.0.1 |
| QWT version | 6.1.3 |
| QScintilla2 version | 2.11.5 |
| OS version | Windows 10 Version 2009 |

### PR DESCRIPTION
**Pull request by wrass**
Update sprite url path with resolution and extension rather than simply appending to string

Fixes #43925

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]

File: src/core/vectortile/qgsvectortilelayer.cpp [hunk 1]
```diff
@@ -424,7 +424,10 @@ bool QgsVectorTileLayer::loadDefaultStyle( QString &error, QStringList &warnings
 
       for ( int resolution = 2; resolution > 0; resolution-- )
       {
-        QNetworkRequest request = QNetworkRequest( QUrl( spriteUriBase + QStringLiteral( "%1.json" ).arg( resolution > 1 ? QStringLiteral( "@%1x" ).arg( resolution ) : QString() ) ) );
+        QUrl spriteUrl = QUrl( spriteUriBase );
+        spriteUrl.setPath( spriteUrl.path() + QStringLiteral( "%1.json" ).arg( resolution > 1 ? QStringLiteral( "@%1x" ).arg( resolution ) : QString() ) );
+        QNetworkRequest request = QNetworkRequest( spriteUrl );
+
```
Comment (nyalldawson) [inline src/core/vectortile/qgsvectortilelayer.cpp:430]:
```suggestion

```

File: src/core/vectortile/qgsvectortilelayer.cpp [hunk 2]
```diff
@@ -435,10 +438,11 @@ bool QgsVectorTileLayer::loadDefaultStyle( QString &error, QStringList &warnings
             const QVariantMap spriteDefinition = QgsJsonUtils::parseJson( content.content() ).toMap();
 
             // retrieve sprite images
-            QNetworkRequest request = QNetworkRequest( QUrl( spriteUriBase + QStringLiteral( "%1.png" ).arg( resolution > 1 ? QStringLiteral( "@%1x" ).arg( resolution ) : QString() ) ) );
-
+            QUrl spriteUrl = QUrl( spriteUriBase );
+            spriteUrl.setPath( spriteUrl.path() + QStringLiteral( "%1.png" ).arg( resolution > 1 ? QStringLiteral( "@%1x" ).arg( resolution ) : QString() ) );
+            QNetworkRequest request = QNetworkRequest( spriteUrl );
+
```
Comment (nyalldawson) [inline src/core/vectortile/qgsvectortilelayer.cpp:444]:
```suggestion

```
