### PR TITLE
Don't consider polygon bounding box in point-in-polygon geometry check

### LINKED ISSUE #63424: Unexpected result from Points Outside Polygons check algorithm
### What is the bug or the crash?

Red points represent points outside polygons and blue points are inside polygons. I made polygons with holes. As shown in my testing result, a point indicated by the arrow actually lies inside the polygon. I was assuming it should be in blue. I have no idea whether it is a bug or that's just how it is.

Image

### Steps to reproduce the issue

In the processing toolbox --> Check geometry --> Points outside polygons --> Running the alg

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.99.0-Master</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/9881defa987">9881defa987</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>6.8.1</td></tr><tr><td>Python version</td><td>3.12.11</td></tr><tr><td>GDAL version</td><td>3.12.0dev-33922498c8 (Compiled)<br/>3.12.0dev-fa69f606a4 (Running)</td></tr><tr><td>PROJ version</td><td>9.6.2</td></tr><tr><td>EPSG Registry database version</td><td>v12.013 (2025-05-26)</td></tr><tr><td>GEOS version</td><td>3.13.1-CAPI-1.19.2</td></tr><tr><td>SQLite version</td><td>3.50.4</td></tr><tr><td>PDAL version</td><td>2.9.0</td></tr><tr><td>PostgreSQL client version</td><td>17.3</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.3.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Windows 11 Version 24H2</td></tr><tr><td colspan="2"><i>This copy of QGIS writes debugging output.</i></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Djedouas**
## Description

Fixes #63424

Adapted the test.

This point has been added in the test dataset to reproduce the issue dataset:

image

It is inside 2 polygon bounding boxes: polygon 1 and 2.

The bug was that the "inside polygon" check was then performed on those 2 polygons and eventually fails because it is not inside polygon 1.

---

## Data from the issue

The color code follows the algorithm results, showing errors from the "Points outside polygons" check.

### Before the fix

image

### CODE REVIEW

File: src/analysis/vector/geometry_checker/qgsgeometrypointinpolygoncheck.cpp [hunk 1]
```diff
@@ -69,6 +69,12 @@ QgsGeometryCheck::Result QgsGeometryPointInPolygonCheck::collectErrors( const QM
           messages.append( tr( "Point in polygon check failed for (%1): the geometry is invalid" ).arg( checkFeature.id() ) );
           continue;
         }
+        if ( !testGeomEngine->intersects( point ) )
```
Comment (nyalldawson) [inline src/analysis/vector/geometry_checker/qgsgeometrypointinpolygoncheck.cpp]: This doesn't make sense to me -- "contains" implies intersection, so this looks like a redundant check. (On a similar note the following contains test implies the !touches condition anyway. A polygon cannot both contain and touch a point)

Comment (Djedouas) [reply src/analysis/vector/geometry_checker/qgsgeometrypointinpolygoncheck.cpp]: Here, the point can be
1. outside the polygon (we don't want to count this polygon as tested)
2. inside the polygon (we want to increment nInside)
3. on the edge of the polygon (we want to register an error)

It's true that this is a redundant check, but it seemed to me very minor, and it avoids changing the existing code below.

But you are right, we could do this instead and keep only 2 geometry computations.

And replace the intersection check and the original contain + !touches check with:

```
        // if the point is inside the polygon, it's ok, we incremented nInside to match nTested
        // and we go the the next polygon.
        if ( testGeomEngine->contains( point ) )
        {
          ++nInside;
        }
        // else, if the point and the polygon do not touch each other, then this polygon is not meant
        // to be tested here.
        else if ( !testGeomEngine->touches( point ) )
        {
          --nTested;
        }
        // else, the point and the polygon do touch each other on the edge. This is an error,
        // do nothing and nTested will not match nInside
```
or this as well

```
        if ( testGeomEngine->touches( point ) )
          continue;

        if ( testGeomEngine->contains( point ) )
          ++nInside;
        else
          --nTested;
```

Does it make more sense?

Comment (nyalldawson) [reply src/analysis/vector/geometry_checker/qgsgeometrypointinpolygoncheck.cpp]: Yes, thanks for the extra clarification!

I think we could still condense this all down to a single GEOS DE-9IM check (and since GEOS 3.13 we could use GEOSPreparedRelatePattern_r to take advantage of prepared geometries for this)

Comment (Djedouas) [reply src/analysis/vector/geometry_checker/qgsgeometrypointinpolygoncheck.cpp]: Yes this is a third way to do :)

And talking about DE-9IM, it could be used in other geometry checks as well...

But in our case here, would it really optimize this 2-checks block?

**Review by benoitdm-oslandia — APPROVED** [review]

**Comment by benoitdm-oslandia** [comment]
@nyalldawson gentle ping! Are you ok with the answers? Can we merge?
