### PR TITLE
Preserve attribute type in dialog update

### LINKED ISSUE #46158: Populating a column of type PostgreSQL array and list widget with an expression fails if "Apply default value on update" is enabled
### What is the bug or the crash?

The setup contains a PostgreSQL table where one or more columns are of type array (array of int4 or array of string).

```
CREATE TABLE test.test (
	t_id serial,
	geometrie geometry(multipolygon, 2056) NOT NULL,
	bfs_nr int4[],
	gb_nr varchar[],
	flurname varchar(255)
);
```
The associated widget should be a "list widget" and the list should be populated with an "overlay_intersects()" expression function as a default value:

image

image

The problem is that I cannot populate the list widget with the QGIS expression. The list always stays empty, even if I can see a correct preview that shows that the expression works.

I tried the following three expressions:

```
overlay_intersects(layer:='hoheitsgrenzen_gemeindegrenze', expression:=bfs_gemeindenummer)
```
```
'[' ||
array_to_string(
overlay_intersects(layer:='hoheitsgrenzen_gemeindegrenze', expression:=bfs_gemeindenummer),
',')
|| ']'
```
```
'{' ||
array_to_string(
overlay_intersects(layer:='hoheitsgrenzen_gemeindegrenze', expression:=bfs_gemeindenummer),
',')
|| '}'
```

Neither of the three expressions was able to populate the list widget, even if the preview always contained correct data.

Note: PostgreSQL arrays use curly brackets ( {} ) while QGIS arrays use square brackets  ( [] ).

### Steps to reproduce the issue

Dataset to test against (Geopackage) - for the overlay_intersects() expression:

[hoheitsgrenzen_gemeindegrenze.gpkg.zip](https://github.com/qgis/QGIS/files/7581653/hoheitsgrenzen_gemeindegrenze.gpkg.zip)
.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.23.0-Master | QGIS code revision | 1d1d59d7fb
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.3.1
PROJ version | 8.1.0
EPSG Registry database version | v10.027 (2021-06-17)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.31.1
Compiled against PDAL | 2.0.1 | Running against PDAL | 2.3.0
PostgreSQL client version | 13.3
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.3 LTS
  |   |   |  
Active Python plugins
changeDataSource | 3.1
trackable_project_files | v1.2.2
QgisModelBaker | v6.6.7
QuickWKT | 3.1
DataPlotly | 3.8.1
sagaprovider | 2.12.99
processing | 2.12.99
db_manager | 0.1.20
grassprovider | 2.12.99
solocator | 1.4.1

</body></html>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by m-kuhn**
If an attribute is set to "apply on update" and has a complex type (anything that's not losslessly convertible to string and back), QGIS will up to now replace it with an empty value in the attribute form.

This patch simply removes the string conversion.

Fixes #46158

### CODE REVIEW

**Comment by m-kuhn** [comment]
@signedav this has been introduced in https://github.com/qgis/QGIS/pull/31167
was there a requirement for this I didn't see?

**Review by nirvn — APPROVED** [review]
Good catch.

**Comment by nirvn** [comment]
@m-kuhn , a test covering that would be good.

**Comment by m-kuhn** [comment]
> @m-kuhn , a test covering that would be good.

The easier the patch, the likelier this request :laughing:

**Comment by signedav** [comment]
It is quite possible that it was unintentional.

File: src/gui/qgsattributeform.cpp [hunk 1]
```diff
@@ -551,8 +551,9 @@ void QgsAttributeForm::updateValuesDependenciesDefaultValues( const int originId
           continue;
 
         QgsExpressionContext context = createExpressionContext( updatedFeature );
-        QString value = mLayer->defaultValue( eww->fieldIdx(), updatedFeature, &context ).toString();
+        const QVariant value = mLayer->defaultValue( eww->fieldIdx(), updatedFeature, &context );
         eww->setValue( value );
+        mCurrentFormFeature.setAttribute( eww->field().name(), value );
```
Comment (m-kuhn) [inline src/gui/qgsattributeform.cpp:556]: For reference, this is another unreported issue, live default values were not stored into the current form feature and hence taken into account by any related functionality.
