### PR TITLE
Fix labels flip upside down when allowing upside down labels and a large negative curved offset distance is set

### LINKED ISSUE #49234: curved line label placement behaviour
### What is the bug or the crash?

while changing the the distance value - depending on scale - from the guideline the labes are switching from 
normal to upside down on a certain value (see screenshots attached). This behaviour started with Version 3.20 and is persistant in 3.22 up to 3.26.; 3.18 shows the "normal" behaviour
qgis_line_label
2022-07-04 10_31_09-_testproject — QGIS  English
2022-07-04 10_32_15-Element  2  _ WG Freiburg

### Steps to reproduce the issue

The labels (street labels) are placed as follows:
- Mode: curved
- line depended position
- distance to a guideline. The guidelines are only for the position on the different street types. the distance differs depending on the type.
Rendering options:
- Show upside down labels: always
- while lowering the distance value (at scale 1:2500) from -4.9 to -5 the labels are switching to upside down position
geopackage with data, project and style is attached:
[testdata.zip](https://github.com/qgis/QGIS/files/9037996/testdata.zip)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.2-Tisler | QGIS code revision | 13c1a028
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.2
PROJ version | 9.0.0
EPSG Registry database version | v10.054 (2022-02-13)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.38.1
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
QNEAT3 | 1.0.4
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.24.2-Tisler
QGIS code revision
[13c1a028](https://github.com/qgis/QGIS/commit/13c1a028)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.2
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
QNEAT3
1.0.4
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

may be related to bug: https://github.com/qgis/QGIS/issues/45051

### PR DESCRIPTION
**Pull request by nyalldawson**
Fixes #49234

### CODE REVIEW

File: tests/src/core/testqgslabelingengine.cpp [hunk 1]
```diff
@@ -2155,6 +2161,423 @@ void TestQgsLabelingEngine::testCurvedLabelAllowUpsideDownBelow()
...
+  mapSettings.setDestinationCrs( vl2->crs() );
+
+  mapSettings.setOutputSize( size );
+  mapSettings.setExtent( QgsRectangle( 190080, 5000000, 190130, 5000030 ) );
+  mapSettings.setLayers( QList<QgsMapLayer *>() << vl2.get() );
+  mapSettings.setOutputDpi( 96 );
+
+  QgsLabelingEngineSettings engineSettings = mapSettings.labelingEngineSettings();
+  engineSettings.setFlag( QgsLabelingEngineSettings::UsePartialCandidates, false );
+  // engineSettings.setFlag( QgsLabelingEngineSettings::DrawLabelRectOnly, true );
```
Comment (nirvn) [inline tests/src/core/testqgslabelingengine.cpp:2209]: Do you want to clean those up or keep it for debugging in the future?

**Review by nirvn — APPROVED** [review]
