### PR TITLE
[app] Use _wputenv_s on Windows to avoid issues with non ASCII chars when setting custom environment variables

### LINKED ISSUE #65151: Environment variables defined in QGIS fail when value contains non-ASCII characters
### What is the bug or the crash?

When setting the PGSERVICEFILE environment variable inside QGIS (Settings → Options → System → Environment) to a path containing non-ASCII characters (e.g. C:\ää\pg_service.conf), QGIS fails to locate the PostgreSQL service file.

When attempting to connect to the database, the following error is raised: `Service file C:\ää\pg_service.conf not found`

However, if the same PGSERVICEFILE environment variable is set globally in Windows system environment settings, PostgreSQL works as expected. Running: `psql service=testservice` successfully locates and uses the service file.

Additionally, when PGSERVICEFILE is set globally and QGIS is started normally, the error message shown by QGIS contains corrupted characters: `Service file C:\��\pg_service.conf not found`

### Steps to reproduce the issue

1. Create a directory with non-ASCII characters in its name, for example: `C:\ää\`
2. Create a valid `pg_service.conf` file in that directory, containing a service definition, for example:  
```
[testservice]
host=localhost
port=5432
dbname=postgres
user=postgres
```
3. Start QGIS.
4. Go to Settings → Options → System → Environment.
5. Add a new environment variable PGSERVICEFILE: C:\ää\pg_service.conf
6. Restart QGIS.
7. In QGIS, create a new PostgreSQL connection and set Service: `testservice`
8. Attempt to connect.
9. The connection fails with: `Service file C:\ää\pg_service.conf not found`

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.99.0-Master</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/1efce453ca8">1efce453ca8</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>6.8.1</td></tr><tr><td>Python version</td><td>3.12.12</td></tr><tr><td>GDAL version</td><td>3.13.0dev-598b2cec09</td></tr><tr><td>PROJ version</td><td>9.7.1</td></tr><tr><td>EPSG Registry database version</td><td>v12.029 (2025-10-03)</td></tr><tr><td>GEOS version</td><td>3.14.1-CAPI-1.20.5</td></tr><tr><td>SFCGAL version</td><td>No support</td></tr><tr><td>GeographicLib version</td><td>2.7.0</td></tr><tr><td>SQLite version</td><td>3.50.4</td></tr><tr><td>PDAL version</td><td>2.10.0</td></tr><tr><td>PostgreSQL client version</td><td>17.3</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.3.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Windows 11 Version 25H2</td></tr><tr><td colspan="2"><i>This copy of QGIS writes debugging output.</i></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by agiudiceandrea**
## Description

Fixes #65151 replacing the `putenv` function with the corresponding wide-character version `_wputenv_s` which is needed on Windows systems to correctly handle non ASCII characters in environment variable's name and value for Overwrite, Append, Prepend, Unset modes in Settings → Options → System → Environment.

Before:

image
image
image

After:
image
image
image

## AI tool usage

 - [ ] AI tool(s) (Copilot, Claude, or something similar) supported my development of this PR. See our [policy about AI tool use](https://github.com/qgis/QGIS-Enhancement-Proposals/blob/master/qep-408-ai-tool-policy.md). Use of AI tools *must* be indicated. Failure to be honest might result in banning.

### CODE REVIEW

File: src/app/main.cpp [hunk 1]
```diff
@@ -1464,7 +1464,7 @@ int main( int argc, char *argv[] )
         if ( systemEnvVars.contains( envVarName ) && envVarApply == "unset"_L1 )
         {
 #ifdef Q_OS_WIN
-          putenv( QString( "%1=" ).arg( envVarName ).toUtf8().constData() );
+          _wputenv( envVarName.toStdWString().c_str() );
```
Comment (nyalldawson) [inline src/app/main.cpp]: Shouldn't this be _wputenv_s ?

Comment (agiudiceandrea) [reply src/app/main.cpp]: Oops! It was an oversight... Thanks for carefully reviewing! I were sure to have also tested unsetting a variable...
Actually I prefer to just replace putenv with _wputenv maintaining the same construct: `_wputenv( QString( "%1=" ).arg( envVarName ).toStdWString().c_str() );`

Comment (nyalldawson) [reply src/app/main.cpp]: I think it should still be _wputenv_s. From the MS docs for _wputenv: "More secure versions of these functions are available; see [_putenv_s, _wputenv_s](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/putenv-s-wputenv-s?view=msvc-170)."

Comment (agiudiceandrea) [reply src/app/main.cpp]: Done.

**Review by nyalldawson — APPROVED** [review]
