### PR TITLE
Oracle field generated always as identity

### LINKED ISSUE #33681: Oracle, impossible to add feature with an identity field
**Describe the bug**
In Oracle, there is a type of field that generated values as serial type in postgresql. This type is called identity and values are generated by default or always.

It's not possible to add feature with digitize maptool nor table attribute when the identity field is always generated because oracle does not allow a insert request where a value (even the default value with the sequential) is given for this field.

oracle_always_identity

For example in the image above, a table with a `pk` field (identity generated always) will not allow : 

`INSERT INTO test( "pk", "cnt", "name", "name2", "num_char", "geom" ) VALUES ( ?, ?, ?, ?, ?, ? )`

the request should be : 

`INSERT INTO test("cnt", "name", "name2", "num_char", "geom") VALUES ( ?, ?, ?, ?, ? )`

without the `pk` field.

Futhermore, default value like "ISEQ$$_75967".nextval (sequential for identity field) is not interpreted with the digitize maptool for both mode : 

oracle_always_identity2

when the identity value is generated by default and not always, it is possible to customize the value to do it work.

**How to Reproduce**

1. create a table with a identity field : 
`CREATE TABLE QGIS.POINT_DATA_IDENTITY ( "pk" NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, GEOM SDO_GEOMETRY);`
2. add the layer to your qgis project
2. Try to add a new feature with digitize maptool or attribute table
3. It's not possible to commit the result

**QGIS and OS versions**

QGIS version | 3.10.1-A Coruña | QGIS code revision | 1d221185e1
-- | -- | -- | --
Compiled against Qt | 5.12.2 | Running against Qt | 5.12.2
Compiled against GDAL/OGR | 2.4.0 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.27.2 | Running against SQLite | 3.27.2
PostgreSQL Client Version | 11.5 (Ubuntu 11.5-0ubuntu0.19.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Ubuntu 19.04 | This copy of QGIS writes debugging output.
Active python plugins | thyrsis

**Additional context**

### PR DESCRIPTION
**Pull request by SebastienPeillet**
## Description
Fix #33681 

It add functions (defaultValueClause and skipConstraintCheck) to evaluate default value for identity field (like "ISEQ$$_75967".nextval).

And in addFeatures function, always generated identity field are listed to be avoid in the insert request.

I add a test to check if the commit passes with an always generated identity field. 

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `Fixes #11111` at the bottom of the commit message
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit
- [x] I have evaluated whether it is appropriate for this PR to be backported, backport requests are left as label or comment

### CODE REVIEW

**Comment by SebastienPeillet** [comment]
@troopa81 ping

File: src/providers/oracle/qgsoracleprovider.cpp [hunk 1]
```diff
@@ -1184,7 +1184,43 @@ bool QgsOracleProvider::isValid() const
...
+  Q_UNUSED( constraint );
+  if ( providerProperty( EvaluateDefaultValues, false ).toBool() )
+  {
+    return !mDefaultValues.value( fieldIndex ).toString().isEmpty();
+  }
+  else
+  {
+    // stricter check - if we are evaluating default values only on commit then we can only bypass the check
+    // if the attribute values matches the original default clause
+    return mDefaultValues.value( fieldIndex ) == value.toString() && !value.isNull();
```
Comment (troopa81) [inline src/providers/oracle/qgsoracleprovider.cpp]: Should be better to ckeck in fieldIndex is not outside `mDefaultValues` bounds

File: src/providers/oracle/qgsoracleprovider.cpp [hunk 2]
```diff
@@ -1246,13 +1282,31 @@ bool QgsOracleProvider::addFeatures( QgsFeatureList &flist, QgsFeatureSink::Flag
...
       delim = ',';
     }
+    QString sql = QStringLiteral( "SELECT a.column_name "
+                                  "FROM all_tab_identity_cols a "
+                                  "WHERE a.owner = '%1' "
+                                  "AND a.table_name = '%2' "
+                                  "AND a.generation_type = 'ALWAYS'" ).arg( mOwnerName ).arg( mTableName );
+    identitytype.prepare( sql );
+
+    if ( identitytype.exec() )
```
Comment (troopa81) [inline src/providers/oracle/qgsoracleprovider.cpp]: Is there a reason for not using `QgsOracleProvider::exec` method ? and maybe print an error message if the request failed.

File: tests/testdata/provider/testdata_oracle.sql [hunk 3]
```diff
@@ -65,5 +65,16 @@ CREATE TABLE QGIS.DATE_TIMES ( "id" INTEGER PRIMARY KEY, "date_field" DATE, "dat
 
 INSERT INTO QGIS.DATE_TIMES ("id", "date_field", "datetime_field" ) VALUES (1, DATE '2004-03-04', TIMESTAMP '2004-03-04 13:41:52' );
 
+CREATE TABLE QGIS.POINT_DATA_IDENTITY ( "pk" NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, GEOM SDO_GEOMETRY);
+INSERT INTO QGIS.POINT_DATA_IDENTITY (GEOM)
+ SELECT SDO_GEOMETRY( 2001,4326,SDO_POINT_TYPE(1, 2, NULL), NULL, NULL) from dual
```
Comment (troopa81) [inline tests/testdata/provider/testdata_oracle.sql]: Is there a specific reason to add so much elements. It's no big deal anyway, I'm just wondering

**Review by troopa81 — COMMENTED** [review]
Looks good to me, just a few comments to deal with

File: tests/testdata/provider/testdata_oracle.sql (hunk 3 above)
Comment (SebastienPeillet) [reply tests/testdata/provider/testdata_oracle.sql]: No, it's true, one is enough. I changed it !

File: src/providers/oracle/qgsoracleprovider.cpp (hunk 2 above)
Comment (SebastienPeillet) [reply src/providers/oracle/qgsoracleprovider.cpp]: No, I didn't pay attention to it. I changed this and add a else condition.

File: src/providers/oracle/qgsoracleprovider.cpp (hunk 1 above)
Comment (SebastienPeillet) [reply src/providers/oracle/qgsoracleprovider.cpp]: Done ! ;)

Comment (troopa81) [reply src/providers/oracle/qgsoracleprovider.cpp]: the way you fix it, you didn't check if fieldIndex is > 0 and < mDefaultAttributes.size() but you check if fieldIndex exist in list which is not what we are looking for.

Actually, the value method return a default contructed value (QVariant here) in case fieldIndex is out of bounds so your first version was OK. You can revert your change on this one, sorry for the noise.

**Review by troopa81 — APPROVED** [review]
looks ok for me

File: src/providers/oracle/qgsoracleprovider.cpp [hunk 4]
```diff
@@ -1246,13 +1282,35 @@ bool QgsOracleProvider::addFeatures( QgsFeatureList &flist, QgsFeatureSink::Flag
...
     QList<int> fieldId;
+    QList<int> alwaysGenerated;
 
     if ( !mGeometryColumn.isNull() )
     {
       insert += quotedIdentifier( mGeometryColumn );
       values += '?';
       delim = ',';
     }
+    QString sql = QStringLiteral( "SELECT a.column_name "
```
Comment (nyalldawson) [inline src/providers/oracle/qgsoracleprovider.cpp]: This looks very expensive to calculate on every feature insert. I think it should be retrieved once at provider initialization and remembered

Comment (SebastienPeillet) [reply src/providers/oracle/qgsoracleprovider.cpp]: Indeed, good idea, it could be a class attribute ! Thanks, I will do that

**Comment by nyalldawson** [comment]
@troopa81 are you happy to the revised version?

**Comment by troopa81** [comment]
@nyalldawson yes I am, looks ok for me
