### PR TITLE
Fix auth basic encoding (no auth system)

### LINKED ISSUE #42405: Passwords with non-ascii chars are wrongly base64 encoded for HTTP Basic auth
**Describe the bug**

QGIS supports HTTP basic authentification, and that works great .. until one uses a password containing a non-ascii character.

I've tested various combinations with curl, and the `Authorization: Basic` header sent by QGIS 3.18 doesnt match the base64 encoded string that curl sends.

eg say with `landry.breuil:testtesté`, curl sends: `Authorization: Basic bGFuZHJ5LmJyZXVpbDp0ZXN0dGVzdMOp` and the server authenticated me okay.

with the same l/p, qgis network logger shows the header sent as `Authorization: Basic bGFuZHJ5LmJyZXVpbDp0ZXN0dGVzd0k=` which, once base64-decoded, reads `landry.breuil:testteswI` which doesn't match what was typed by the user, and the server rejects the authentication. Testing with tcpdump on the server, it receives the header qgis network logger says is sent.

That feels similar to #39243, unless this time its not about url-encoding, rather charset tables ?

**QGIS and OS versions**

QGIS 3.18.0 on OpenBSD

**Additional context**

remote server is nginx with auth-ldap module, which works fine against curl authenticated requests.

### PR DESCRIPTION
**Pull request by elpaso**
Followup #42410 (which fixed the auth system stored configuration part, this fixes the plain unencrypted storage)

Fixes #42405

### CODE REVIEW

File: tests/src/core/testqgsdatasourceuri.cpp [hunk 1]
```diff
@@ -299,6 +299,19 @@ void TestQgsDataSourceUri::checkAuthParams()
...
+  uri4.setEncodedUri( QStringLiteral( "dpiMode=7&url=http://localhost:8000/ows/?MAP%3D/home/bug.qgs&username=username&password=qgis%C3%A8%C3%A9" ) );
+  QCOMPARE( uri4.param( QStringLiteral( "username" ) ), QStringLiteral( "username" ) );
+  QCOMPARE( uri4.username(), QStringLiteral( "username" ) );
+  QCOMPARE( uri4.param( QStringLiteral( "password" ) ), QStringLiteral( "qgisèé" ) );
+  QCOMPARE( uri4.password(), QStringLiteral( "qgisèé" ) );
+
+  uri4.setEncodedUri( QStringLiteral( "dpiMode=7&url=http://localhost:8000/&username=username&password=%1" ).arg( QString( QUrl::toPercentEncoding( QStringLiteral( "😁😂😍" ) ) ) ) );
+  QCOMPARE( uri4.param( QStringLiteral( "username" ) ), QStringLiteral( "username" ) );
+  QCOMPARE( uri4.username(), QStringLiteral( "username" ) );
+  QCOMPARE( uri4.param( QStringLiteral( "password" ) ), QStringLiteral( "😁😂😍" ) );
```
Comment (nirvn) [inline tests/src/core/testqgsdatasourceuri.cpp:312]: @elpaso , great password! :wink:

**Comment by elpaso** [comment]
Actually this isn't the right fix.
