### PR TITLE
Recalculate layout when legend item size changes

### LINKED ISSUE #38881: AMS legend overlapping existing legend entries
When adding a new AMS layer, the legend is rendered on top of existing layers below in the layer tree.
As soon as the window is switched or the user clicks on the legend, the nodes are moved down and things are corrected.

Peek 2020-09-19 22-39

Steps to reproduce:

1. Add some layers
2. Add an AMS layer on top of the legend (e.g. from https://sampleserver1.arcgisonline.com/arcgis/rest/services)

### PR DESCRIPTION
**Pull request by m-kuhn**
This triggers an `update()` of the legend viewport when the size of the legend item changes.

The solution is only partially satisfying. This should be done automatically by the model / view themselves. And it seems to work correctly for WMS. I couldn't find out why.

This patch works without any side effects. Happy to dump it in favor of an alternative approach.

Fixes #38881

### CODE REVIEW

**Comment by nyalldawson** [comment]
Could you test with a project involving 1000s of layers and confirm there's no regressions in project handling speed here? I've previously seen that legend update code like this can cause temporary qgis hangs on large projects (that's an ongoing issue, but I don't want it to get any worse then it currently is!)

**Comment by m-kuhn** [comment]
What is the requirement exactly? Can I duplicate a vector layer 1000 times and add an AMS layer and test with that?

File: src/gui/layertree/qgslayertreeview.cpp [hunk 1]
```diff
@@ -586,3 +589,16 @@ void QgsLayerTreeView::onHorizontalScroll( int value )
   Q_UNUSED( value )
   viewport()->update();
 }
+
+void QgsLayerTreeView::onDataChanged( const QModelIndex &topLeft, const QModelIndex &bottomRight, const QVector<int> &roles )
+{
+  Q_UNUSED( topLeft )
+  Q_UNUSED( bottomRight )
+
+  // If an item is resized asynchroneously (e.g. wms legend)
```
Comment (m-kuhn) [inline src/gui/layertree/qgslayertreeview.cpp:598]:
```suggestion
  // If an item is resized asynchronously (e.g. wms legend)
```

**Comment by nyalldawson** [comment]
That'd be a good test. Also throw a vector layer with rule based renderer or categorised renderer and 10000 categories in there.

**Comment by m-kuhn** [comment]
I'm confident this doesn't introduce any noticeable performance impact. It triggers a (deferred) repaint like any user interface interaction does (clicking somewhere, hitting a random button, scrolling, ...) and only does this under a specific condition.

I'll try to create meaningful results. It fear it won't be easy.

_Talking about... Debugging the legend code I've seen code paths triggered repeatedly without any good reason, so if you say you've observed bad performance ... I'm not surprised._

**Comment by m-kuhn** [comment]
Confirmed with 10000 categories legend, 34 seconds to add the layer with and without the patch.

**Comment by m-kuhn** [comment]
Followup issue https://github.com/qgis/QGIS/issues/38890

**Review by nyalldawson — APPROVED** [review]
Thanks, proceed at will!
