### PR TITLE
Fix PG trust metadata layer loading

### LINKED ISSUE #38809: Can't read PG data sources when saved in version 3.10 and using service / auth combo
**Describe the bug**
QGIS projects saved in version 3.10 and having the following data source can't be loaded in current QGIS master.

```
<datasource>service='servicename' authcfg=authcfgid key='t_id' srid=2056 type=Point checkPrimaryKeyUnicity='1' table="schema"."table" (geometrie) sql=</datasource>
```

All layers with the aforementioned data source scheme can't be loaded anymore.

However, newly created data sources within QGIS master can be saved and loaded without a problem. When comparing the data sources when saved in QGIS master, here is what I get:

```
<datasource>service='servicename' authcfg=authcfgid key='t_id' srid=2056 type=Point checkPrimaryKeyUnicity='0' table="schema"."table" (geometrie)</datasource>
```
There are basically two differences:

- checkPrimaryKeyUnicity once set to 1, now 0
- the "sql=" part at the end

I bisected previous versions and it seems like it worked until this commit: https://github.com/qgis/QGIS/commit/760347c3b6a95129db677a1915d90190779eaad5
This is the first failing commit. The previous commit https://github.com/qgis/QGIS/commit/45e9ecb1c250cd19aa335c600a6208a76ea03567 was still working.

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #38809

Followup 760347c3b6a95129db677a1915d90190779eaad5

### CODE REVIEW

**Comment by andreasneumann** [comment]
Perfect - I confirm that it fixes my issue! 

Thanks a lot, 

Andreas 

On 2020-09-17 13:04, Alessandro Pasotti wrote:

> Fixes #38809 [1] 
> 
> Followup 760347c [2] 
> -------------------------
> 
> YOU CAN VIEW, COMMENT ON, OR MERGE THIS PULL REQUEST ONLINE AT:
> 
> https://github.com/qgis/QGIS/pull/38833 
> 
> COMMIT SUMMARY
> 
> * Fix PG trust metadata layer loading
> 
> FILE CHANGES
> 
> * M src/core/qgsvectorlayer.cpp [3] (2)
> * M src/providers/postgres/qgspostgresprovider.cpp [4] (4)
> * M tests/src/python/test_provider_postgres.py [5] (37)
> 
> PATCH LINKS:
> 
> * https://github.com/qgis/QGIS/pull/38833.patch
> * https://github.com/qgis/QGIS/pull/38833.diff
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [6], or unsubscribe [7].

 

Links:
------
[1] https://github.com/qgis/QGIS/issues/38809
[2]
https://github.com/qgis/QGIS/commit/760347c3b6a95129db677a1915d90190779eaad5
[3]
https://github.com/qgis/QGIS/pull/38833/files#diff-106be592650b55ccae79c83eecd15ceb
[4]
https://github.com/qgis/QGIS/pull/38833/files#diff-374a3d3ebe5430cec252d7f2c7d5f457
[5]
https://github.com/qgis/QGIS/pull/38833/files#diff-99b101819133a316786604243f3abf6e
[6] https://github.com/qgis/QGIS/pull/38833
[7]

File: src/core/qgsvectorlayer.cpp [hunk 1]
```diff
@@ -1544,7 +1544,7 @@ bool QgsVectorLayer::readXml( const QDomNode &layer_node, QgsReadWriteContext &c
   }
 
   QgsDataProvider::ProviderOptions options { context.transformContext() };
-  QgsDataProvider::ReadFlags flags = QgsDataProvider::ReadFlags();
+  QgsDataProvider::ReadFlags flags;
```
Comment (rldhont) [inline src/core/qgsvectorlayer.cpp:1547]: Hi @elpaso, if this line has to be updated, It has to be fixed in other files. Will you do it or do you want that I create a PR just for this ?

This line has been introduced with this PR #38464

Comment (elpaso) [reply src/core/qgsvectorlayer.cpp:1547]: The generated code is totally equivalent, I just find redundant call the default ctor explicitly. It's more a style matter, nothing important.

Comment (rldhont) [reply src/core/qgsvectorlayer.cpp:1547]: thanks

Comment (elpaso) [reply src/core/qgsvectorlayer.cpp:1547]: @rldhont np. 

On another topic I did not check if the same `quotedIdentifier` / `quotedValue` mistake was done elsewhere with your original PR or any followup. Can you please check that it only affected PG?

**Review by nyalldawson — APPROVED** [review]
