### PR TITLE
Remove locale formatting in numeric value on default filter widget

### LINKED ISSUE #63712: Filter fails in the attribute table when number has local formatting
### What is the bug or the crash?

When one enters a locale formatted numeric value (like 10'000 or 10,000 or 10.000,50) in a filter input, it cannot evaluate the filter.

### Steps to reproduce the issue

In the locale settings I can activate locale specific number formatting:

Image

Image

When entering raw values in the field filter, it works (with double):

Image

with int values with "Apply" it creates me the filter expression:

Image

And with the filter using the form it creates the expressions as well.

Image

**But** when I enter values with the locale formatting (e.g. user do that by copy paste the values), the field-filter does not work:

Image

And the form filter pushes an error:

Image

### Versions

Master

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.99.0-Master</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/230ceea495d">230ceea495d</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>6.9.2</td></tr><tr><td>Python version</td><td>3.13.7</td></tr><tr><td>GDAL version</td><td>3.10.3</td></tr><tr><td>PROJ version</td><td>9.6.0</td></tr><tr><td>EPSG Registry database version</td><td>v12.004 (2025-03-02)</td></tr><tr><td>GEOS version</td><td>3.13.1-CAPI-1.19.2</td></tr><tr><td>SFCGAL version</td><td>No support</td></tr><tr><td>SQLite version</td><td>3.46.1</td></tr><tr><td>PostgreSQL client version</td><td>17.6</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.3.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Ubuntu 25.10</td></tr><tr><td colspan="2"><i>This copy of QGIS writes debugging output.</i></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>swiss_locator</td><td>4.0.1</td></tr><tr><td>QgisModelBaker</td><td>dev</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>processing</td><td>2.12.99</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr></table>

and 3.44.3

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.44.3-Solothurn</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/1d1d67e9edd">1d1d67e9edd</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.17</td></tr><tr><td>Python version</td><td>3.13.7</td></tr><tr><td>GDAL version</td><td>3.10.3</td></tr><tr><td>PROJ version</td><td>9.6.0</td></tr><tr><td>EPSG Registry database version</td><td>v12.004 (2025-03-02)</td></tr><tr><td>GEOS version</td><td>3.13.1-CAPI-1.19.2</td></tr><tr><td>SQLite version</td><td>3.46.1</td></tr><tr><td>PostgreSQL client version</td><td>17.6</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.1.4</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Ubuntu 25.10</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>swiss_locator</td><td>4.0.1</td></tr><tr><td>QgisModelBaker</td><td>dev</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>processing</td><td>2.12.99</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr></table>

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by signedav**
When pasting a formatted numeric value from the current locale setting into a filter input like form filter or field filter in the attribute table, it converts the value in the expression to a proper numeric value without formatting.

This fixes #63712

### CODE REVIEW

File: src/gui/editorwidgets/qgsdefaultsearchwidgetwrapper.cpp [hunk 1]
```diff
@@ -296,6 +296,52 @@ QCheckBox *QgsDefaultSearchWidgetWrapper::caseSensitiveCheckBox()
   return mCheckbox;
 }
 
+QString QgsDefaultSearchWidgetWrapper::validExpressionString( const QString &exp, const QMetaType::Type &fldType ) const
```
Comment (elpaso) [inline src/gui/editorwidgets/qgsdefaultsearchwidgetwrapper.cpp]: Have you considered using the static `double QgsDoubleValidator::toDouble( const QString &input, bool *ok )` ?

Comment (signedav) [reply src/gui/editorwidgets/qgsdefaultsearchwidgetwrapper.cpp]: Thanks for the input. Yes, this could be used for double, but not for the other types. And since there is not an equivalent for the other types already existing I suggest to do it the way I proposed. Or do you disagree?

Comment (elpaso) [reply src/gui/editorwidgets/qgsdefaultsearchwidgetwrapper.cpp]: Well, it can be used for any numeric type (it just always returns a double), the difference seems to be that it implements a fallback mechanism that allows to use the locale thousand separator and decimal separator first and falls back to C locale if that fails. 
How would your code behave with an italian locale  (which uses `,` as decimal separator and `.` for thousands) when the user enters `field_1 < 12.34` ?

As an italian user I normally use the numeric keypad to enter numbers and even if italian convention is to use a comma to separate decimals my numeric keypad types a `.` . The point is that many non-C locale users still prefer to enter numbers the `C` locale way.

For example, using the italian locale:

```python
QgsDoubleValidator.toDouble('12.34')
Out[27]: 12.34
QLocale().toDouble('12.34')
Out[28]: (0.0, False)
```

The system isn't perfect because there might be ambiguity when the decimals are multiples of three but this is the best we can do to make user's life easier.

Comment (signedav) [reply src/gui/editorwidgets/qgsdefaultsearchwidgetwrapper.cpp]: Well I see the point of the c-locale fallback. Thanks. I will double check the QgsDoubleValidator way and come back with another commit...

Comment (signedav) [reply src/gui/editorwidgets/qgsdefaultsearchwidgetwrapper.cpp]: I did it now with QgsDoubleValidator::toDouble` and decided against having a method for this (it's very few duplicate code). Would be cool when you can have another look @elpaso

File: src/gui/editorwidgets/qgsdefaultsearchwidgetwrapper.cpp [hunk 2]
```diff
@@ -55,19 +56,29 @@ void QgsDefaultSearchWidgetWrapper::setCaseString( int caseSensitiveCheckState )
...
   QString str;
-  if ( exp == nullValue )
+  if ( expression == nullValue )
   {
     str = QStringLiteral( "%1 IS NULL" ).arg( QgsExpression::quotedColumnRef( fieldName ) );
   }
   else
   {
+    QString exp = expression;
+    const QMetaType::Type fldType = layer()->fields().at( mFieldIdx ).type();
```
Comment (elpaso) [inline src/gui/editorwidgets/qgsdefaultsearchwidgetwrapper.cpp:69]: Have you considered using `QgsVariantUtils::isNumericType(QMetaType::Type metaType )` ?

File: src/gui/editorwidgets/qgsdefaultsearchwidgetwrapper.cpp [hunk 3]
```diff
@@ -55,19 +56,29 @@ void QgsDefaultSearchWidgetWrapper::setCaseString( int caseSensitiveCheckState )
...
+    const bool numeric = ( fldType == QMetaType::Type::Int || fldType == QMetaType::Type::Double || fldType == QMetaType::Type::LongLong || fldType == QMetaType::Type::UInt || fldType == QMetaType::Type::ULongLong );
+
+    if ( numeric )
+    {
+      bool ok = false;
+      const QString rawExp = QString::number( QgsDoubleValidator::toDouble( exp, &ok ) );
```
Comment (elpaso) [inline src/gui/editorwidgets/qgsdefaultsearchwidgetwrapper.cpp]: You should first convert to double , then check `ok` and then convert to string only if `ok` is true.

File: src/gui/editorwidgets/qgsdefaultsearchwidgetwrapper.cpp [hunk 4]
```diff
@@ -152,6 +163,21 @@ QString QgsDefaultSearchWidgetWrapper::createExpression( QgsSearchWidgetWrapper:
   if ( flags & IsNotNull )
     return fieldName + " IS NOT NULL";
 
+  const bool numeric = ( fldType == QMetaType::Type::Int || fldType == QMetaType::Type::Double || fldType == QMetaType::Type::LongLong || fldType == QMetaType::Type::UInt || fldType == QMetaType::Type::ULongLong );
+
+  QString text = mLineEdit->text();
```
Comment (elpaso) [inline src/gui/editorwidgets/qgsdefaultsearchwidgetwrapper.cpp:165]: maybe
```suggestion
  const QString text = mLineEdit->text();
```

File: src/gui/editorwidgets/qgsdefaultsearchwidgetwrapper.cpp [hunk 5]
```diff
@@ -55,19 +56,29 @@ void QgsDefaultSearchWidgetWrapper::setCaseString( int caseSensitiveCheckState )
...
-  if ( exp == nullValue )
+  if ( expression == nullValue )
   {
     str = QStringLiteral( "%1 IS NULL" ).arg( QgsExpression::quotedColumnRef( fieldName ) );
   }
   else
   {
+    QString exp = expression;
+    const QMetaType::Type fldType = layer()->fields().at( mFieldIdx ).type();
+    const bool numeric = ( fldType == QMetaType::Type::Int || fldType == QMetaType::Type::Double || fldType == QMetaType::Type::LongLong || fldType == QMetaType::Type::UInt || fldType == QMetaType::Type::ULongLong );
```
Comment (elpaso) [inline src/gui/editorwidgets/qgsdefaultsearchwidgetwrapper.cpp]: just for readability
```suggestion
    const bool isNumeric = ( fldType == QMetaType::Type::Int || fldType == QMetaType::Type::Double || fldType == QMetaType::Type::LongLong || fldType == QMetaType::Type::UInt || fldType == QMetaType::Type::ULongLong );
```

File: src/gui/editorwidgets/qgsdefaultsearchwidgetwrapper.cpp (hunk 2 above)
Comment (signedav) [reply src/gui/editorwidgets/qgsdefaultsearchwidgetwrapper.cpp:69]: No. Because it was solved this way before I didn't wanted to change to much on existing code. But since I added other types I think isNumericType would be appropriate. Thanks.

File: src/gui/editorwidgets/qgsdefaultsearchwidgetwrapper.cpp (hunk 3 above)
Comment (signedav) [reply src/gui/editorwidgets/qgsdefaultsearchwidgetwrapper.cpp]: Hm... I did that on purpose to make it less complex. On not ok rawExp would just become "0.0" and won't be used anymore. But yes. No strong opinion.

File: src/gui/editorwidgets/qgsdefaultsearchwidgetwrapper.cpp (hunk 4 above)
Comment (signedav) [reply src/gui/editorwidgets/qgsdefaultsearchwidgetwrapper.cpp:165]: I don't think so because we might later assign the value of rawText to it...

File: src/gui/editorwidgets/qgsdefaultsearchwidgetwrapper.cpp (hunk 3 above)
Comment (signedav) [reply src/gui/editorwidgets/qgsdefaultsearchwidgetwrapper.cpp]: okay, i could remove rawExp and just have the doubleValue. So I will consider your proposal.

**Comment by signedav** [comment]
Thanks @elpaso I considered your inputs (except the one with the const text)

**Review by elpaso — APPROVED** [review]
LGTM, just one last thing: in the test you might want to explicitly set the english locale just to be sure that if anyone runs the test locally and she is using a different locale the test will behave consistently.

**Comment by signedav** [comment]
Thanks @elpaso

**Comment by agiudiceandrea** [comment]
Please have a look at the regression reported at https://github.com/qgis/QGIS/pull/63713.

File: src/gui/editorwidgets/qgsdefaultsearchwidgetwrapper.cpp [hunk 6]
```diff
@@ -55,21 +56,30 @@ void QgsDefaultSearchWidgetWrapper::setCaseString( int caseSensitiveCheckState )
...
+    const QMetaType::Type fldType = layer()->fields().at( mFieldIdx ).type();
+    const bool isNumeric = QgsVariantUtils::isNumericType( fldType );
+
+    if ( isNumeric )
+    {
+      bool ok = false;
+      const double doubleValue = QgsDoubleValidator::toDouble( exp, &ok );
+      if ( ok )
+      {
+        exp = QString::number( doubleValue );
```
Comment (elpaso) [inline src/gui/editorwidgets/qgsdefaultsearchwidgetwrapper.cpp:78]: you can try to specify a format to avoid scientific notation https://doc.qt.io/qt-6/qstring.html#number-1

Comment (signedav) [reply src/gui/editorwidgets/qgsdefaultsearchwidgetwrapper.cpp:78]: Yes, thanks. It could be QString::number( doubleValue, 'f');

Comment (signedav) [reply src/gui/editorwidgets/qgsdefaultsearchwidgetwrapper.cpp:78]: But I'm a little bit confused about the following line (unchanged in this pr):
```
    str = QStringLiteral( "%1 %2 '%3'" )
            .arg( QgsExpression::quotedColumnRef( fieldName ), isNumeric ? QStringLiteral( "=" ) : mCaseString, isNumeric ? exp.replace( '\'', QLatin1String( "''" ) ) : '%' + exp.replace( '\'', QLatin1String( "''" ) ) + '%' ); // escape quotes
```
Why it replaces ' when it's numeric? :thinking:

Comment (signedav) [reply src/gui/editorwidgets/qgsdefaultsearchwidgetwrapper.cpp:78]: > Yes, thanks. It could be QString::number( doubleValue, 'f');

Or better `exp = QLocale().toString( doubleValue, 'f', QLocale::FloatingPointShortest);` to be valid for all kind of types.

(edit: not good idea because of the locale formattings / or QLocale( QLocale::C ) - I'll check...)
