### PR TITLE
disable "Editable" and "Reuse last value" checkboxes for JsonView editor widget (fix #47755)

### LINKED ISSUE #47755: "editable" property do not make sense (and is misleading) for the "json view" edit widget
### What is the bug or the crash?

The "json view" edit widget is read only

https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/vector_properties.html#edit-widgets

so some property like "editable" (and possibly others) should be disabled, as it gives the impression that with that widget some json code can be entered/edited manually

image

### Steps to reproduce the issue

See above.

### Versions

3.22.4
3.24.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alexbruy**
## Description

JsonView editor widget is a read-only widget, however the "Editable" and "Reuse last entered value" checkboxes are enabled for it confusing users and making a false impression that this widgets allows editing.

Also fixes enabled data-defined override button for "Editable" property when target field is a read-only field.

Fixes #47755.

### CODE REVIEW

**Comment by nyalldawson** [comment]
There are other widget wrappers which are read-only -- specifically "uuid generator" and "hidden". I think this property/flag should be moved up to something like `virtual bool isReadOnly` in the edit widget wrapper (or the edit widget registry)

File: src/gui/editorwidgets/qgsjsoneditwidgetfactory.cpp [hunk 1]
```diff
@@ -55,3 +55,8 @@ unsigned int QgsJsonEditWidgetFactory::fieldScore( const QgsVectorLayer *vl, int
       break;
   }
 }
+
+bool QgsJsonEditWidgetFactory::isReadOnly() const
+{
+  return true;
```
Comment (nyalldawson) [inline src/gui/editorwidgets/qgsjsoneditwidgetfactory.cpp:61]: Hmm - looking into this now, the json editor IS editable if it's not set to the "Tree" view mode. And users can switch that view at any time... so this one SHOULD return false, and remain non-read only.

Which means #47755 was invalid in the first place :upside_down_face: 

At least this fix still applies to the uuid/hidden wrappers!

Comment (nyalldawson) [reply src/gui/editorwidgets/qgsjsoneditwidgetfactory.cpp:61]: Actually ignore that... even in non-tree mode I see it's still read only. I'm not sure why that is!

**Review by nyalldawson — APPROVED** [review]
