### PR TITLE
[attribute form] Implement an optional null state representation to the checkbox editor widget to allow for UI reflection of failing constraint

### LINKED ISSUE #55390: The check result of constraints sometimes differs in the form and attribute table view
### What is the bug or the crash?

I am referring to the relatively new, great feature "Show Features with Failing Constraints" to filter features in the attribute table.

I observe cases here where after activating the "Show Features with Failing Constraints" function, features are filtered and certain columns are marked as failing in the table view, but the same fields are marked with a green checkmark in the form view.

In my opinion, the check results displayed in the form view should be correct in the corresponding cases.

### Steps to reproduce the issue

Unfortunately, this is a customer project which I cannot post here for illustrative purposes. As it only seems to affect very specific cases, I have not yet managed to recreate the case in an MWE.

For example, the constraint expression of one case in question is

```
if(
"kontrolle_rahmen" =  'Pflege- und Funktionskontrolle',
CASE
WHEN "funktion_umsetzungsstand" in ( 'umgesetzt' , 'tlw. umgesetzt' ) 
 and  "pflege_status" IS NOT NULL THEN True
WHEN "funktion_umsetzungsstand" in ( 'nicht umgesetzt' ,  'unklar, ob umgesetzt' ) 
 and  "pflege_status" IS NULL THEN True 
WHEN "pflege_beschreibung" <> '' and "pflege_status" = 'in Planung' THEN True
WHEN "pflege_dauerhaft" = '0' and "pflege_status" = 'in Planung' THEN True
ELSE False
END,
True)
```

Any idea what the problem could be? Is the constraint expression "problematic" in some way or is it a bug in the "Show Features with Failing Constraints" function?

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS-Version | 3.34.0-Prizren | QGIS-Codeversion | ffbdd67881
-- | -- | -- | --
Qt-Version | 5.15.3
Python-Version | 3.9.5
Kompiliert mit GDAL/OGR | 3.7.2 | Läuft mit GDAL/OGR | 3.7.3
PROJ-Version | 9.3.0
EPSG-Registraturdatenbankversion | v10.094 (2023-08-08)
GEOS-Version | 3.12.0-CAPI-1.18.0
SQLite-Version | 3.41.1
PDAL-Version | 2.5.5
PostgreSQL-Client-Version | 15.2
SpatiaLite-Version | 5.1.0
QWT-Version | 6.1.6
QScintilla2-Version | 2.13.4
BS-Version | Windows 10 Version 2009
  |   |   |  
Aktive Python-Erweiterungen
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

It looks like the query of the operating system in the QGIS Help menu -> About is not working properly. I am actually using Windows 10 Pro, 22H2.

grafik

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This PR adds a new [x] allow null representation option for the attribute form's checkbox editor widget. When toggled on, the checkbox will reflect a feature attribute's null value by using the Qt::PartiallyChecked checkbox state. 

This allows for the attribute form's non-null constraint to be properly reflected in the checkbox editor widget by returning a null value() when the widget was passed on a feature attribute's null value.

image

image

@nyalldawson , as discussed on Google Chat, this is an alternative to the (now closed) PR https://github.com/qgis/QGIS/pull/56002 .

This fixes #55390.

_As a nice side bonus, this change allows for the use of a blocking null constraint a given checkbox editor widget to insure that people filling the attribute form makes a **deliberate** false/true value decision (instead of not touching it which, without this new option, would automatically set the value to false._

### CODE REVIEW

File: src/gui/editorwidgets/qgscheckboxwidgetwrapper.cpp [hunk 1]
```diff
@@ -25,21 +25,32 @@ QgsCheckboxWidgetWrapper::QgsCheckboxWidgetWrapper( QgsVectorLayer *layer, int f
 QVariant QgsCheckboxWidgetWrapper::value() const
 {
   QVariant v;
+  if ( config( QStringLiteral( "AllowNullState" ) ).toBool() && mCheckBox && mCheckBox->checkState() == Qt::PartiallyChecked )
+  {
+    return v;
```
Comment (nyalldawson) [inline src/gui/editorwidgets/qgscheckboxwidgetwrapper.cpp:30]: how do you feel above removing "v" here entirely, and always just directly returning the value? It'd be a bit cleaner IMO vs the current mix of return direct vs set and later return.

File: src/gui/editorwidgets/qgscheckboxwidgetwrapper.cpp [hunk 2]
```diff
@@ -64,12 +76,16 @@ void QgsCheckboxWidgetWrapper::initWidget( QWidget *editor )
   mGroupBox = qobject_cast<QGroupBox *>( editor );
 
   if ( mCheckBox )
-    connect( mCheckBox, &QAbstractButton::toggled, this, [ = ]( bool state )
+    connect( mCheckBox, &QCheckBox::stateChanged, this, [ = ]( int state )
   {
+    if ( !mIndeterminateStateEnabled && mCheckBox->checkState() != Qt::PartiallyChecked )
+    {
+      mCheckBox->setTristate( false );
```
Comment (nyalldawson) [inline src/gui/editorwidgets/qgscheckboxwidgetwrapper.cpp:83]: this prevents "undoing" a null -> not null change, right? Do you think we should just leave it as tristate so a user can undo this?

Comment (nyalldawson) [reply src/gui/editorwidgets/qgscheckboxwidgetwrapper.cpp:83]: (if so, then the valueChanged signal logic below needs to handle null values too)

**Comment by nyalldawson** [comment]
I'm looking, and I can't see ANY existing tests for checkbox widget wrapper. Am I missing something?

File: src/gui/editorwidgets/qgscheckboxwidgetwrapper.cpp (hunk 2 above)
Comment (nirvn) [reply src/gui/editorwidgets/qgscheckboxwidgetwrapper.cpp:83]: @nyalldawson , I'm -1 to introduce a _settable_ null state via tristate. For one, it'll interfere with multi-editing, where the PartiallyChecked state is used to say "don't change anything". If we want a settable null value in the future, we can implement a separate set-to-null button. But that's beyond my scope of interest with this PR (i.e. fixing the constraint issue).

File: src/gui/editorwidgets/qgscheckboxwidgetwrapper.cpp (hunk 1 above)
Comment (nirvn) [reply src/gui/editorwidgets/qgscheckboxwidgetwrapper.cpp:30]: @nyalldawson , by that you mean only having one return v; at the very end of the function? Sure, no strong feelings either way.

Comment (nyalldawson) [reply src/gui/editorwidgets/qgscheckboxwidgetwrapper.cpp:30]: I'd lean toward the other way, and just always returning straight away

**Comment by nirvn** [comment]
@nyalldawson , review addressed.

**Review by nyalldawson — APPROVED** [review]
