### PR TITLE
Make it clear when feature count is estimated

### LINKED ISSUE #46790: If "estimated metadata" option is checked, feature count for tables/postgis do not work
### What is the bug or the crash?

In a PostGIS connection enable the "estimated metadata" option.

Add a geometryless table to a project.

Try enable "feature count" (this should be renamed "record count" for this type of tables) > nothing happen

If the option is unchecked than "feature count" works, but curiously the count is wrong (in my case geometryless tables, not views or MT, with a PK).

### Steps to reproduce the issue

See above.

### Versions

3.22.2 on Windows 10.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by troopa81**
Fixes #46790 : This PR proposes to add informations when feature count is estimated

A **≈** character to indicate that the count is approximatively X
estcount

A comment in tooltip to inform user about updating statistics
estcounttt

I would finish the PR when we agree those informations are relevant and enough to avoid misunderstandings

@m-kuhn @elpaso I would be glad to have your opinion on this

### CODE REVIEW

File: src/core/layertree/qgslayertreemodel.cpp [hunk 1]
```diff
@@ -316,6 +320,14 @@ QVariant QgsLayerTreeModel::data( const QModelIndex &index, int role ) const
 
         parts << "<i>" + source.toHtmlEscaped() + "</i>";
 
+        QgsLayerTreeLayer *nodeLayer = QgsLayerTree::toLayer( node );
+        const bool showFeatureCount = nodeLayer->customProperty( QStringLiteral( "showFeatureCount" ), 0 ).toBool();
+        const bool estimatedCount = QgsDataSourceUri( layer->dataProvider()->dataSourceUri() ).useEstimatedMetadata();
+        if ( showFeatureCount && estimatedCount )
+        {
+          parts << "<b>Feature Count is estimated</b> : Please consider keeping database statistics up to date";
```
Comment (m-kuhn) [inline src/core/layertree/qgslayertreemodel.cpp:328]: This sentence should inform the user that "the feature count is determined by the database statistics".
"Please consider ..." sounds like a suggestion, but actually it's well possible the statistics are up to date already.

**Comment by elpaso** [comment]
I like the idea. 
Are there any other places where (possibly estimated) feature count is shown? They should be updated as well.

File: src/core/layertree/qgslayertreemodel.cpp (hunk 1 above)
Comment (troopa81) [reply src/core/layertree/qgslayertreemodel.cpp]: Agreed

**Comment by troopa81** [comment]
This is now ready for review, I changed the message according to @m-kuhn comment and homogenize the way we display feature count between legend layer item and categorized item

File: src/core/layertree/qgslayertreemodel.cpp [hunk 2]
```diff
@@ -325,7 +326,8 @@ QVariant QgsLayerTreeModel::data( const QModelIndex &index, int role ) const
         const bool estimatedCount = QgsDataSourceUri( layer->dataProvider()->dataSourceUri() ).useEstimatedMetadata();
         if ( showFeatureCount && estimatedCount )
         {
-          parts << "<b>Feature Count is estimated</b> : Please consider keeping database statistics up to date";
+          parts << QStringLiteral( "<b>%1</b> %2" ).arg(
+                  tr( "Feature Count is estimated" ), tr( ": the feature count is determined by the database statistics" ) );
```
Comment (m-kuhn) [inline src/core/layertree/qgslayertreemodel.cpp:330]:
```suggestion
                  tr( "Feature count is estimated" ), tr( ": the feature count is determined by the database statistics" ) );
```

Comment (troopa81) [reply src/core/layertree/qgslayertreemodel.cpp:330]: Are you sure the `:` exists in all language, like Japanese or Arabic ? I'm gonna make it one single transable string if ot's better this way.

Comment (m-kuhn) [reply src/core/layertree/qgslayertreemodel.cpp:330]: I'm not an expert on this matter. But basically, that's the reason for proposing a single translatable string (also gives more context to the translators).

**Comment by m-kuhn** [comment]
LGTM

**Review by m-kuhn — APPROVED** [review]

**Comment by m-kuhn** [comment]
Test restarted

**Comment by troopa81** [comment]
still an unrelated failure on testnetworkmanager...
