### PR TITLE
Fix raster reprojection with world extent from EPSG:4326 to EPSG:3857

### LINKED ISSUE #34518: Raster layer misaligns when bbox bigger than projected raster layer
**Projected raster layer misaligns in QGIS**
qgis-wms-landuse
A raster layer (source srs EPSG:4326) misaligns with a vector layer when projected AND zooming out beyond the bounding box of the raster layer.

**How to Reproduce**
1. download the 267MB zipped project and data from [my cloud drive](https://drive.google.com/file/d/1D9X8twzOSLrDW7cd-1L_el9S4Duq0QWC/view?usp=sharing). The raster is a TIFF file, EPSG:4326. I do not know how to reproduce a world covering raster with less data.
2. unzip the project and data (directory 'rastervector', project 'project.qgs') and open in  QGIS. 
3. load the project into QGIS. The raster and vector layers align nicely. 
4. change the OTF projection to EPSG:3857 and zoom to layer 'landcover2'

This should produce the image showing the misaligned raster layer. If you zoom in on the map, the raster and vector suddenly align properly.

**QGIS and OS versions**
I got exactly the same results with QGIS versions 2.18.20 and 3.03 and 3.2

### PR DESCRIPTION
**Pull request by rouault**
Fixes #34518

### CODE REVIEW

File: src/core/proj/qgscoordinatetransform_p.cpp [hunk 1]
```diff
@@ -158,6 +159,10 @@ bool QgsCoordinateTransformPrivate::initialize()
     return true;
   }
 
+  mGeographicToWebMercator =
+    mSourceCRS.authid() == QLatin1String( "EPSG:4326" ) &&
```
Comment (nyalldawson) [inline src/core/proj/qgscoordinatetransform_p.cpp:163]: I'm guessing this fix also applies to non-wgs84 geographic source CRS?

```suggestion
    mSourceCRS.isGeographic() &&
```

Comment (rouault) [reply src/core/proj/qgscoordinatetransform_p.cpp:163]: > I'm guessing this fix also applies to non-wgs84 geographic source CRS?

yes for what we do here with this flag, that should be OK

**Review by nyalldawson — APPROVED** [review]
