### PR TITLE
Open and load --code file and --py-args arguments in C++

### LINKED ISSUE #60120: Windows: `--code` flag cannot accept paths with single quote (')
### What is the bug or the crash?

The `--code` flag, passed to `qgis.exe`, is meant to make QGIS execute a Python script after starting up.  However, if the argument of `--code` has the `'` character, QGIS isn't able to open the script.  It seems that QGIS doesn't properly escape the filename.

### Steps to reproduce the issue

1. Create a Python script containing a `'` character, for example `hawai'i.py`.
2. Open Command Prompt.
3. Run QGIS with the script passed in the `--code` argument, .e.g `"C:\\Program Files\\QGIS 3.40.2\\bin\\qgis-bin.exe" --code "hawai'i.py"`.
4. QGIS opens an error window containing the following error:
```
An error occurred during execution of following code:
with open('E:/tmp/hawai'i.py','r') as f: exec(f.read())


  File "", line 1
    with open('E:/tmp/hawai'i.py','r') as f: exec(f.read())
                                   ^
SyntaxError: unterminated string literal (detected at line 1)


Python version:
3.12.8 (main, Dec 20 2024, 15:21:15) [MSC v.1938 64 bit (AMD64)]

QGIS version:
3.40.2-Bratislava 'Bratislava', 14826ca1
```

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.40.2-Bratislava</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/14826ca1">14826ca1</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.13</td></tr><tr><td>Python version</td><td>3.12.8</td></tr><tr><td>GDAL/OGR version</td><td>3.9.3</td></tr><tr><td>PROJ version</td><td>9.5.0</td></tr><tr><td>EPSG Registry database version</td><td>v11.016 (2024-08-31)</td></tr><tr><td>GEOS version</td><td>3.13.0-CAPI-1.19.0</td></tr><tr><td>SQLite version</td><td>3.46.1</td></tr><tr><td>PDAL version</td><td>2.8.1</td></tr><tr><td>PostgreSQL client version</td><td>16.2</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.3.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Windows 10 Version 2009</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

QGIS ought to correctly escape the filename before plonking it into Python code.

### PR DESCRIPTION
**Pull request by btzy**
## Description

I took a stab at #60120 to see if we can design a better alternative to #60121.

Instead of doing string substitution into Python code, we use the proper Python C API functions to assign to `sys.argv` and execute a Python script from a file.  This avoids the issues that arise due to improper escaping of strings (e.g. `'` and `\`).  Unix file names in particular may contain any non-null character (including non-printable characters), and trying to escape such characters manually would otherwise be difficult to get right.  String substitution is also possibly vulnerable to code injection attacks, as it is possible to carefully craft a string containing code that will be executed.

There was a hack that converts Windows-style directory separators to Unix-style directory separators.  This is no longer necessary, and therefore has been removed.

Fixes #60120.

### CODE REVIEW

**Comment by domi4484** [comment]
@btzy when we introduced `--py-args` we decided on purpose to make the args available for each python execution in QGIS independently from the `--code` argument.
But I can't remember exactly what's the use case thought, maybe @m-kuhn do you remember more?

@btzy If you need arguments valid only in the context of the `--code` script I would suggest to add a new parameter `--code-args`. But then arise the question what to do if they are both set?

**Comment by m-kuhn** [comment]
No strong opinion. What would be the reason to not make it also available for other python code than `--code`?

**Comment by btzy** [comment]
@domi4484 I misunderstood the help string of `--py-args`. I'll modify this PR.  Likely we'll need another function in QgsPythonUtils to set the `sys.argv` variable.

**Comment by btzy** [comment]
I'm not sure how to trigger the automatic Windows build that other PRs have; can someone help me get the GitHub Action to run?

**Comment by btzy** [comment]
Separately, I made #60183 to fix the grammar error in the help, which was what originally misled me to think that `--py-args` is only used with `--code`.

**Comment by btzy** [comment]
@agiudiceandrea @domi4484 I've tested that the Windows build works:
 - Passing `--code` runs the Python code
 - Passing `--code` with `--py-args` make the extra args available in the Python code in `sys.argv`
 - Passing `--py-args`, and then later opening the Python console and running `sys.argv` shows the arguments

There is an unrelated test failing, but I see that it is marked as "unstable": https://cdash.orfeo-toolbox.org/viewTest.php?buildid=28319

**Comment by btzy** [comment]
@m-kuhn Can I get a review for this?

File: src/core/qgspythonrunner.h [hunk 1]
```diff
@@ -42,9 +42,15 @@ class CORE_EXPORT QgsPythonRunner
     //! Execute a Python statement
     static bool run( const QString &command, const QString &messageOnError = QString() );
 
+    //! Execute a Python file
```
Comment (m-kuhn) [inline src/core/qgspythonrunner.h:45]: Could you add a description of the parameters?

File: src/python/qgspythonutilsimpl.cpp [hunk 2]
```diff
@@ -454,6 +454,134 @@ bool QgsPythonUtilsImpl::runString( const QString &command, QString msgOnError,
...
+  gstate = PyGILState_Ensure();
+  QString ret;
+
+  PyObject *obj, *errobj;
+
+  QFile file( filename );
+  if ( !file.open( QIODevice::ReadOnly | QIODevice::Text ) )
+  {
+    ret = "Cannot open file";
+    goto error;
```
Comment (m-kuhn) [inline src/python/qgspythonutilsimpl.cpp:470]: Please avoid goto

File: src/python/qgspythonutilsimpl.cpp [hunk 3]
```diff
@@ -454,6 +454,134 @@ bool QgsPythonUtilsImpl::runString( const QString &command, QString msgOnError,
...
+  evalString( QStringLiteral( "str(sys.path)" ), path );
+  evalString( QStringLiteral( "sys.version" ), version );
+
+  QString str = "<font color=\"red\">" + errMsg + "</font><br><pre>\n" + traceback + "\n</pre>"
+                + QObject::tr( "Python version:" ) + "<br>" + version + "<br><br>"
+                + QObject::tr( "QGIS version:" ) + "<br>" + QStringLiteral( "%1 '%2', %3" ).arg( Qgis::version(), Qgis::releaseName(), Qgis::devVersion() ) + "<br><br>"
+                + QObject::tr( "Python path:" ) + "<br>" + path;
+  str.replace( '\n', QLatin1String( "<br>" ) ).replace( QLatin1String( "  " ), QLatin1String( "&nbsp; " ) );
+
+  qDebug() << str;
```
Comment (m-kuhn) [inline src/python/qgspythonutilsimpl.cpp:507]: If this should stay, please use `QgsDebugMsgLevel`

File: src/python/qgspythonutilsimpl.cpp [hunk 4]
```diff
@@ -454,6 +454,134 @@ bool QgsPythonUtilsImpl::runString( const QString &command, QString msgOnError,
...
+      ret = QString( "SetArgvTraceback" ) + getTraceback();
+    else
+      ret = "Error occurred in PyImport_ImportModule";
+    goto error;
+  }
+  argsobj = PyList_New( arguments.size() );
+  if ( !argsobj )
+  {
+    ret = "Error occurred in PyList_New";
+    goto error;
```
Comment (m-kuhn) [inline src/python/qgspythonutilsimpl.cpp:538]: Same

File: src/python/qgspythonutilsimpl.cpp [hunk 5]
```diff
@@ -454,6 +454,134 @@ bool QgsPythonUtilsImpl::runString( const QString &command, QString msgOnError,
...
+  PyObject *sysobj = nullptr, *errobj = nullptr, *argsobj = nullptr;
+  sysobj = PyImport_ImportModule( "sys" );
+  if ( !sysobj )
+  {
+    errobj = PyErr_Occurred();
+    if ( errobj )
+      ret = QString( "SetArgvTraceback" ) + getTraceback();
+    else
+      ret = "Error occurred in PyImport_ImportModule";
+    goto error;
```
Comment (m-kuhn) [inline src/python/qgspythonutilsimpl.cpp:532]: Same

**Comment by m-kuhn** [comment]
Thanks, using sys.argv does look like the correct approach!

File: src/python/qgspythonutilsimpl.cpp (hunk 5 above)
Comment (btzy) [reply src/python/qgspythonutilsimpl.cpp:531]: How would you like me to rewrite this code?  We need to execute the cleanup code at the end whether or not this function succeeds.

The most C++-ic way to do this is to write an RAII wrapper class around PyGILState_Ensure/PyGILState_Release and PyObject/Py_XDECREF.  Or for a more ad-hoc mechanism, I might have used the equivalent of [`std::experimental::scope_exit`](https://en.cppreference.com/w/cpp/experimental/scope_exit)] (both Folly and Abseil have this in some form, but QGIS uses neither of them).  I would have written code in one of the above two ways if this was for my own project, but I do not see existing code in QGIS that leverages either of them.

If the above solutions are unacceptable, we would have to either invert the guard clauses into nested if-statements, which is generally considered to be bad practice.  We are thus left with goto statements, which seem to be an idiom for writing cleanup code in C.

What would be most appropriate for the QGIS codebase?  Writing my own scope guard?

**Comment by btzy** [comment]
This PR is ready for review.

File: src/python/qgspythonutilsimpl.cpp (hunk 5 above)
Comment (m-kuhn) [reply src/python/qgspythonutilsimpl.cpp:531]: Sorry for the slow feedback, time is very limited recently!

I realize that we still do have some `goto:`  in this file, so you are building on precendence in which case I do think this is acceptable.

What I did in the past was introducing a custom deleter for `std::unique_ptr`

https://github.com/qgis/QGIS/blob/41d5fc2c30a0c6e86f37e09d77f65427a948ff4f/src/core/qgssqliteutils.h#L67

https://github.com/qgis/QGIS/blob/41d5fc2c30a0c6e86f37e09d77f65427a948ff4f/src/core/qgssqliteutils.cpp#L37-L40

Something along these lines would be great to have (something similar to https://pythonextensionpatterns.readthedocs.io/en/latest/cpp_and_cpython.html ) but is of bigger scope.

So, this is good to merge, but I would love to hear your thoughts about this.

**Comment by btzy** [comment]
Ready for review

**Comment by m-kuhn** [comment]
it's on my list ...

File: src/python/qgspythonutilsimpl.cpp [hunk 6]
```diff
@@ -454,6 +454,132 @@ bool QgsPythonUtilsImpl::runString( const QString &command, QString msgOnError,
...
+  PyGILState_STATE gstate;
+  gstate = PyGILState_Ensure();
+  QString ret;
+
+  PyObject *obj, *errobj;
+
+  QFile file( filename );
+  if ( !file.open( QIODevice::ReadOnly | QIODevice::Text ) )
+  {
+    ret = "Cannot open file";
```
Comment (m-kuhn) [inline src/python/qgspythonutilsimpl.cpp:469]:
```suggestion
    ret = QStringLiteral( "Cannot open file" );
```

File: src/python/qgspythonutilsimpl.cpp [hunk 7]
```diff
@@ -454,6 +454,132 @@ bool QgsPythonUtilsImpl::runString( const QString &command, QString msgOnError,
...
+error:
+  // we are done calling python API, release global interpreter lock
+  PyGILState_Release( gstate );
+
+  return ret;
+}
+
+bool QgsPythonUtilsImpl::runFile( const QString &filename, const QString &messageOnError )
+{
+  const QString &traceback = runFileUnsafe( filename );
```
Comment (m-kuhn) [inline src/python/qgspythonutilsimpl.cpp:490]:
```suggestion
  const QString traceback = runFileUnsafe( filename );
```

File: src/python/qgspythonutilsimpl.cpp [hunk 8]
```diff
@@ -454,6 +454,132 @@ bool QgsPythonUtilsImpl::runString( const QString &command, QString msgOnError,
...
+  if ( traceback.isEmpty() )
+    return true;
+
+  // use some default message if custom hasn't been specified
+  const QString &errMsg = !messageOnError.isEmpty() ? messageOnError : QObject::tr( "An error occurred during execution of following file:" ) + "\n<tt>" + filename + "</tt>";
```
Comment (m-kuhn) [inline src/python/qgspythonutilsimpl.cpp:495]:
```suggestion
  const QString errMsg = !messageOnError.isEmpty() ? messageOnError : QObject::tr( "An error occurred during execution of following file:" ) + "\n<tt>" + filename + "</tt>";
```

File: tests/code_layout/acceptable_missing_doc.py [hunk 9]
```diff
@@ -235,7 +235,9 @@
     "QgsScopeLogger": ["QgsScopeLogger(const char *file, const char *func, int line)"],
     "QgsPythonRunner": [
         "evalCommand(QString command, QString &result)=0",
+        "runFileCommand(const QString &filename, const QString &messageOnError=QString())=0",
```
Comment (m-kuhn) [inline tests/code_layout/acceptable_missing_doc.py:238]: better than adding this here would be to add a docstring

https://github.com/qgis/QGIS/pull/60134/files#diff-ec71c7c8b64a4c4e6178b09f34319bc0f3278de4d3e7b5df5b7fa22456898820R71

**Review by m-kuhn — COMMENTED** [review]
This is much cleaner than the previous approach with string manipulation, so I am in favor of merging this.

Things to sort out before:

- There are a few potential references to temporary QString's. Copying a QString is a cheap operation, so we always take copies in such scenarios throughout the codebase (and as far as I know the current code results is unsafe).
- There are also two missing doc strings to handle

Once that's in place, we should proceed to merge this and prepare for something more RAII friendly in the future.

**Comment by btzy** [comment]
Anyway, I've made all the changes as requested.

**Comment by m-kuhn** [comment]
> > the current code results is unsafe
> 
> This is not true. All the instances that you flagged out were instances of [lifetime extension](https://en.cppreference.com/w/cpp/language/reference_initialization#Lifetime_of_a_temporary). Writing `const auto& x = f();` allows one to avoid a copy if `f()` returns a reference, but yet persist the value if `f()` returns an object type.

I must admit the exact rule of this was always a bit unclear to me, so I have to assume you are technically correct, for the sake of coherence with the rest of the codebase, the adjustment is welcome nonetheless.

**Review by m-kuhn — APPROVED** [review]

**Comment by btzy** [comment]
There's a problem with the sip check, but I can't figure out how to fix it:
```
 *** Python addition file not up to date: python/core/auto_generated/qgspythonrunner.sip
 9c9
<     QgsPythonRunner.__abstract_methods__ = ['runCommand', 'evalCommand']
---
>     QgsPythonRunner.__abstract_methods__ = ['runCommand', 'runFileCommand', 'evalCommand', 'setArgvCommand'] 
 *** Python addition file not up to date: python/PyQt6/core/auto_generated/qgspythonrunner.sip
 9c9
<     QgsPythonRunner.__abstract_methods__ = ['runCommand', 'evalCommand']
---
>     QgsPythonRunner.__abstract_methods__ = ['runCommand', 'runFileCommand', 'evalCommand', 'setArgvCommand'] 
```

**Comment by m-kuhn** [comment]
Can you run scripts/sipify_all.sh

**Comment by btzy** [comment]
Turns out other stuff had changed from then till now and it needed a rebase.

**Comment by m-kuhn** [comment]
Thanks for the patience
