### PR TITLE
[Vector file writer] Save source field domains to output file (fixes #56184)

### LINKED ISSUE #56184: Export Save features to gpkg does not keep Field Domains, but using Convert Format does
### What is the bug or the crash?

I have a geopackage with Field Domains set. When I want to export a selection of the data into a new geopackage, I want to have all existing field domains in the new geopackage as well. Simply use Export > Save features as does not transfer the field domain settings to the new gpkg.
Using the Convert Format tool without any additional settings, does actually copy the gpkg_data_columns and gpkg_data_column_constraints from the original gpkg into the new gpkg and thus transferring the field domains into the new gpkg.

### Steps to reproduce the issue

Use the attached gpkg.
[domaintesting.zip](https://github.com/qgis/QGIS/files/14164755/domaintesting.zip)

It has a field domain: values_for_codes 
The values_for_codes is applied to the field codes

Add the layer to a new project
Export > Save features as gpkg
The new gpkg will not have the Field Domain.

Use the Convert format tool from the processing toolbox to save the original layer, do not change any settings, so no additional creation options.
The resulting gpkg will have the Field Domain.

I find it weird that the Convert Format tool, which is actually just calling ogr2ogr without any additional visible options set does copy the Field Domain, whereas the Export > Save feature menu-item does not. Doesn't it call the same ogr2ogr command?

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.3-Prizren | QGIS code revision | 47373234ac
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.18
GDAL/OGR version | 3.8.3
PROJ version | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.41.1
PDAL version | 2.6.0
PostgreSQL client version | 15.2
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.4
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
batchvectorlayersaver | 0.9
geocatbridge | 4.4
GroupStats | 2.2.7
inspireatomclient | 0.8.1
latlontools | 3.6.18
maplibrary | 1.3
pdokbaggeocoder | 0.6.7
pdokservicesplugin | 4.2.0
pdok_locatieserver_locator_filter | 0.2.1
PluginLoadTimes | 4.0.2
qfieldsync | v4.7.0
qgis2web | 3.17.3
QNEAT3 | 1.0.5
QuickWKT | 3.1
quick_map_services | 0.19.34
refFunctions | 1.6
RuimtelijkePlannen | 3.5.2
SpreadsheetLayers | 2.1.0
wfsclient | 0.9.11
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99

</body></html>QGIS version
3.34.3-Prizren
QGIS code revision
[47373234ac](https://github.com/qgis/QGIS/commit/47373234ac)
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.3
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
batchvectorlayersaver
0.9
geocatbridge
4.4
GroupStats
2.2.7
inspireatomclient
0.8.1
latlontools
3.6.18
maplibrary
1.3
pdokbaggeocoder
0.6.7
pdokservicesplugin
4.2.0
pdok_locatieserver_locator_filter
0.2.1
PluginLoadTimes
4.0.2
qfieldsync
v4.7.0
qgis2web
3.17.3
QNEAT3
1.0.5
QuickWKT
3.1
quick_map_services
0.19.34
refFunctions
1.6
RuimtelijkePlannen
3.5.2
SpreadsheetLayers
2.1.0
wfsclient
0.9.11
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rouault**
Not totally sure if this is appropriate for backport to 3.34 ?

### CODE REVIEW

File: src/core/qgsvectorfilewriter.h [hunk 1]
```diff
@@ -555,6 +556,25 @@ class CORE_EXPORT QgsVectorFileWriter : public QgsFeatureSink
...
+
+        /**
+         * Source database provider connection, for field domains.
+         *
+         * Ownership is not transferred and callers must ensure that the lifetime of srcDatabaseProviderConn
+         * exceeds the lifetime of the QgsVectorFileWriter object.
+         *
+         * \since QGIS 3.36
+         */
+        const QgsAbstractDatabaseProviderConnection *srcDatabaseProviderConn = nullptr;
```
Comment (nyalldawson) [inline src/core/qgsvectorfilewriter.h:577]: We should try to avoid abbreviations in the public APIs, they make the API less "guessable":

```suggestion
        const QgsAbstractDatabaseProviderConnection *sourceDatabaseProviderConnection = nullptr;
```

File: src/core/qgsvectorfilewriter.h [hunk 2]
```diff
@@ -656,7 +678,9 @@ class CORE_EXPORT QgsVectorFileWriter : public QgsFeatureSink
                                            const QgsCoordinateTransformContext &transformContext = QgsCoordinateTransformContext(),
                                            QgsFeatureSink::SinkFlags sinkFlags = QgsFeatureSink::SinkFlags(),
                                            FieldNameSource fieldNameSource = Original,
-                                           bool includeConstraints = false
+                                           bool includeConstraints = false,
+                                           bool setFieldDomains = true,
+                                           const QgsAbstractDatabaseProviderConnection *srcDatabaseProviderConn = nullptr
```
Comment (nyalldawson) [inline src/core/qgsvectorfilewriter.h:683]:
```suggestion
                                           const QgsAbstractDatabaseProviderConnection *sourceDatabaseProviderConnection = nullptr
```

File: src/core/qgsvectorfilewriter.h [hunk 3]
```diff
@@ -555,6 +556,25 @@ class CORE_EXPORT QgsVectorFileWriter : public QgsFeatureSink
          * \since QGIS 3.34
          */
         bool includeConstraints = false;
+
+        /**
+         * Set to TRUE to transfer field domains to the exported vector file.
+         *
+         * Support for field domains depends on the output file format.
```
Comment (nyalldawson) [inline src/core/qgsvectorfilewriter.h:563]: "\note Only available in builds based on GDAL 3.5 or later"

File: src/core/qgsvectorfilewriter.cpp [hunk 4]
```diff
@@ -884,6 +907,55 @@ void QgsVectorFileWriter::init( QString vectorFileName,
...
+            {
+              // If the target dataset already knows this field domain,
+              // we can directly assign its name to the new field.
+              canSetFieldDomainName = true;
+            }
+            else  if ( GDALDatasetTestCapability( mDS.get(), ODsCAddFieldDomain ) )
+            {
+              // Otherwise, if the output dataset can create field domains,
+              // - convert the QGIS field domain to a GDAL one
+              // - regiter it to the GDAL dataset
```
Comment (nyalldawson) [inline src/core/qgsvectorfilewriter.cpp:927]:
```suggestion
              // - register it to the GDAL dataset
```

File: src/core/qgsvectorfilewriter.cpp [hunk 5]
```diff
@@ -884,6 +907,55 @@ void QgsVectorFileWriter::init( QString vectorFileName,
...
+                {
+                  char *pszFailureReason = nullptr;
+                  if ( GDALDatasetAddFieldDomain( mDS.get(), hFieldDomain, &pszFailureReason ) )
+                  {
+                    existingDestDomainNames.insert( domainName );
+                    canSetFieldDomainName = true;
+                  }
+                  else
+                  {
+                    QgsDebugMsgLevel( QStringLiteral( "cannot create field domain: %1" ).arg( pszFailureReason ), 2 );
```
Comment (nyalldawson) [inline src/core/qgsvectorfilewriter.cpp:945]: Should we append this to mErrorMessage ?

File: src/core/qgsvectorfilewriter.h (hunk 1 above)
Comment (rouault) [reply src/core/qgsvectorfilewriter.h]: done

File: src/core/qgsvectorfilewriter.h (hunk 2 above)
Comment (rouault) [reply src/core/qgsvectorfilewriter.h]: done

File: src/core/qgsvectorfilewriter.h (hunk 3 above)
Comment (rouault) [reply src/core/qgsvectorfilewriter.h:563]: done

File: src/core/qgsvectorfilewriter.cpp (hunk 4 above)
Comment (rouault) [reply src/core/qgsvectorfilewriter.cpp]: done

File: src/core/qgsvectorfilewriter.cpp (hunk 5 above)
Comment (rouault) [reply src/core/qgsvectorfilewriter.cpp:945]: as far as I can see, mErrorMessage and mError are set only in the case of a fatal error. Here I was more in the mood that failure to create a field domain shouldn't prevent conversion of the layer. Otherwise we should have a GUI setting "Convert field domains" where the user could uncheck to bypass the error, but that's probably overkill.

Comment (nyalldawson) [reply src/core/qgsvectorfilewriter.cpp:945]: Right, lets leave for now then

**Review by nyalldawson — APPROVED** [review]

**Comment by rouault** [comment]
@nyalldawson Do you feel it is appropriate for backport to 3.34?

**Comment by nyalldawson** [comment]
@rouault I'd say we don't -- it's sneaking into new feature territory as is
