### PR TITLE
[Bugfix] Fix table sorting

### LINKED ISSUE #35427: [print layouts ] table, field sorting does not work
I have a table with over **4k rows**, I add the table in the print composer and I sort it according to the `data` field (datetime), the sorting does not work.

I notice that to work I have to write a number greater than **4k** in the main properties of the table (default is 30)

- first (30 lines)

image

- after (5k lines)

image

I attach vrt files:

[dpc-covid19-ita-province.zip](https://github.com/qgis/QGIS/files/4397674/dpc-covid19-ita-province.zip)

## how to replicate it:

1. download .zip file;
2. unzip it;
3. dragAndDrop vrt file in the TOC;
4. start the composer and add table;
5. sort the table using the date field;

## OSGeo4W64 Win 10

image

### PR DESCRIPTION
**Pull request by roya0045**
## Description
Fixes #35427 

I'll add the comment when I'll squash my commit, if I don't forget.

PR was tested, all is fine. Artefact is available as usual.

### CODE REVIEW

File: src/core/layout/qgslayoutitemattributetable.cpp [hunk 1]
```diff
@@ -518,6 +518,12 @@ bool QgsLayoutItemAttributeTable::getTableContents( QgsLayoutTableContents &cont
     QgsFeature atlasFeature = mLayout->reportContext().feature();
     req.setFilterFid( atlasFeature.id() );
   }
+  
+  QVector< QPair<int, bool> > sortColumns = sortAttributes();
+  for ( int i = sortColumns.size() - 1; i >= 0; --i )
+  {
+     req = req.addOrderBy( mColumns.at( sortColumns.at( i ).first )->heading(), sortColumns.at( i ).second );
```
Comment (nyalldawson) [inline src/core/layout/qgslayoutitemattributetable.cpp]: `heading` isn't appropriate here -- that's a free text field, unrelated to the column's content

Comment (roya0045) [reply src/core/layout/qgslayoutitemattributetable.cpp]: Ah right, I see what you mean, I'll get this sorted out tomorrow with the indentation and the commit comment. Thanks!

Comment (nyalldawson) [reply src/core/layout/qgslayoutitemattributetable.cpp]: Thanks! and yes, a test would be valuable for this too (better do a range of tests -- one with a attribute only column, with with expression based column, and one with descending sort order)

Comment (roya0045) [reply src/core/layout/qgslayoutitemattributetable.cpp]: I'm looking at the code and they way to set sort columns in QgsLayoutItemAttributeTable seem to be done in the GUI side of things as there are no ways to set this in the base class. The columns to handle sorting is in qgslayoutattributeselectiondialog.cpp I would think that implementing functional test would require a revisit of the current handling or a new suite of test relying on gui elements. I think that this is out of the scope of a simple bugfix. Let me know what you think.

**Comment by roya0045** [comment]
Test failure is in qgs font maker test, 100% unrelated.

**Comment by roya0045** [comment]
I guess a backport would be needed.

File: src/core/layout/qgslayoutitemattributetable.cpp (hunk 1 above)
Comment (roya0045) [reply src/core/layout/qgslayoutitemattributetable.cpp]: Maybe I'm bad at this but classes are so convoluted I can't even find a way to make an new column with an expression with the exposed api. Sorting might be doable but I can't access the columns to perform sorting, again an api rework would be needed. Currently my changes work with minimal impact. I think we'll have to leave it at that until tests are easier to perform. :/

Comment (nyalldawson) [reply src/core/layout/qgslayoutitemattributetable.cpp]: It's not that hard. No API work necessary full stop. Look at TestQgsLayoutTable::attributeTableSetAttributes() and do something like

    table->columns().at( 0 )->setAttribute( "some expression which messes with a sort order like taking 0 - an int column value" );

Comment (roya0045) [reply src/core/layout/qgslayoutitemattributetable.cpp]: Ah right, I was expecting a function to expose things and create a new column, instead of replacing a column but this will do.

Comment (roya0045) [reply src/core/layout/qgslayoutitemattributetable.cpp]: Tests are done

**Comment by roya0045** [comment]
Test failure is postgres raster, unrelated.

**Comment by roya0045** [comment]
Still confused as to why  PyQgsPostgresRasterProvider failed.

File: src/core/layout/qgslayoutitemattributetable.cpp [hunk 2]
```diff
@@ -628,16 +634,6 @@ bool QgsLayoutItemAttributeTable::getTableContents( QgsLayoutTableContents &cont
     ++counter;
   }
 
-  //sort the list, starting with the last attribute
-  QgsLayoutAttributeTableCompare c;
```
Comment (nyalldawson) [inline src/core/layout/qgslayoutitemattributetable.cpp:632]: You can completely remove QgsLayoutAttributeTableCompare now -- it's private and unused.

**Review by nyalldawson — COMMENTED** [review]
LGTM! Can you just remove the QgsLayoutAttributeTableCompare class as a final cleanup?

File: src/core/layout/qgslayoutitemattributetable.cpp (hunk 2 above)
Comment (roya0045) [reply src/core/layout/qgslayoutitemattributetable.cpp:632]: The full class?

Comment (roya0045) [reply src/core/layout/qgslayoutitemattributetable.cpp:632]: Done

**Comment by nyalldawson** [comment]
Great work, thanks!
