### PR TITLE
Pg oid backport

### LINKED ISSUE #30041: Unable to add new features in QGIS for PostGIS table using sequence for gid. Data type serial: 'integer overflow'
PostGIS 2.2 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
Postgres PostgreSQL 9.5.4, compiled by Visual C++ build 1800, 64-bit
QGIS 2.18 Las Palmas

```
CREATE TABLE myschema.mytable
(
  gid serial NOT NULL,
  the_geom geometry(Point,25832),
  CONSTRAINT mytable_pkey PRIMARY KEY (gid)
)
WITH (
  OIDS=TRUE
);
```

In QGIS I added the PostGIS - layer "myschema.mytable" and tried to save a new object.
Following message appears:

"Konnte Änderungen am Layer mytable nicht festschreiben

Fehler: FEHLER: Ein Objekt nicht hinzugefügt.
  
Datenanbieterfehler:
      PostGIS-Fehler beim Attributhinzufügen: FEHLER:  NULL-Wert in Spalte »gid« 
      verletzt Not-Null-Constraint
    DETAIL:  Fehlgeschlagene Zeile enthält (null, 
    0102000020E8640000020000004DAC4DB4A84918414C986446399155416E8719...)."

"Could not commit changes on layer mytable

Error: ERROR: One object is not added.
  
Data provider error:
      PostGIS-Error on add attribute: ERROR:  NULL- value in column »gid« 
      is not permitted as an input because of Not-Null-Constraint
    DETAIL:  Failed row contains (null, 
    0102000020E8640000020000004DAC4DB4A84918414C986446399155416E8719...)."

In QGIS should be the default for column 'gid':
nextval('myschema.mytable_gid_seq'::regclass)

Instead the default for column 'gid' is 'NULL'.

To reproduce the error select on PostGIS:

`SELECT 'myschema.mytable'::regclass::oid;`

If the result is bigger than the maximum integer - value 2147483647
it is not possible to use data type 'serial' in QGIS to add a new object.
But in PostGIS I can add objects if the value of column "gid" is of data type 'serial' 
and the result is bigger than 2147483647 because PostGIS has no "integer overflow".

(Please refer to https://github.com/qgis/QGIS/issues/29489, https://issues.qgis.org/issues/21673)

I think QGIS can't handle sequences after integer overflow.

Is it possible to change the data type of regclass::oid from 'integer' into 'biginteger'
in QGIS??

### PR DESCRIPTION
**Pull request by elpaso**
Backport of #30184 AND #30192 , fixes #30041

### CODE REVIEW

**Comment by luipir** [comment]
ci failing due timeout... restarted job

File: src/providers/postgres/qgspostgresprovider.cpp [hunk 1]
```diff
@@ -830,12 +831,12 @@ bool QgsPostgresProvider::loadFields()
     if ( fieldName == mGeometryColumn )
       continue;
 
-    int fldtyp = result.PQftype( i );
+    Oid fldtyp = result.PQftype( i );
     int fldMod = result.PQfmod( i );
     int fieldPrec = -1;
-    int tableoid = result.PQftable( i );
+    Oid tableoid = result.PQftable( i );
```
Comment (luipir) [inline src/providers/postgres/qgspostgresprovider.cpp]: in some part of the master PR you used unsigned int instead of Oid... what's the reason?

File: src/providers/postgres/qgspostgresconn.cpp [hunk 2]
```diff
@@ -107,7 +107,7 @@ QString QgsPostgresResult::PQfname( int col )
   return QString::fromUtf8( ::PQfname( mRes, col ) );
 }
 
-int QgsPostgresResult::PQftable( int col )
+Oid QgsPostgresResult::PQftable( int col )
```
Comment (luipir) [inline src/providers/postgres/qgspostgresconn.cpp]: in some part of the master PR you used unsigned int instead of Oid... what's the reason?

**Comment by elpaso** [comment]
Oid Is an alias for unsigned int

File: src/providers/postgres/qgspostgresconn.cpp (hunk 2 above)
Comment (luipir) [reply src/providers/postgres/qgspostgresconn.cpp]: now its' clear abuut https://github.com/qgis/QGIS/pull/30192

**Review by luipir — APPROVED** [review]

**Comment by sylviaobk** [comment]
Are these changes in download link https://www.qgis.org/de/site/forusers/download.html
"Eigenständige QGIS-Installation Version 3.4 (64bit)" ?
I downloaded 3.4 yesterday and the problem https://github.com/qgis/qgis/issues/30041 still exists

**Comment by jef-n** [comment]
@sylviaobk no, but the next 3.4 point release is today.  Between releases you have to use the nightlies of the LTR branch (eg. qgis-ltr-dev on OSGeo4W).
