### PR TITLE
Ensure symbols using map unit sizing work correctly in elevation profile plots

### LINKED ISSUE #52833: Elevation profile - Map units are not properly supported in point markers
### What is the bug or the crash?

When defining point symbols on line geometries for the profile view the map units are not respected and they act very strangely in the marker preview when selected and combined with anchor points.

image

image

In the interactive profile, the map units are not respected. I would expect that when I zoom in into the profile that the point SVG symbols would also be displayer larger because of the map units.

image

### Steps to reproduce the issue

1. Load any 3D line layer
2. In the elevation tab define a marker with map units on the marker symbols
3. Zoom in and out in the profile and notice that the symbol is displayed with the same size always, regardless of the map units definition

For symbols that have a certain size in m in reality it would be really nice if the map units would work properly in the profile view.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.31.0-Master | QGIS code revision | 0ce567bd306
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.6
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.2 LTS
  |   |   |  
Active Python plugins
changeDataSource | 3.1
solocator | 1.6.0
pg_raster_import | 3.2.0
trackable_project_files | v1.2.2
linking_relation_editor | v1.1.9
QgisModelBaker | v7.5.0
AtlasExportFunction | 1.1
processing | 2.12.99
db_manager | 0.1.20

</body></html>QGIS version
3.31.0-Master
QGIS code revision
[0ce567bd306](https://github.com/qgis/QGIS/commit/0ce567bd306)
Qt version
5.15.3
Python version
3.10.6
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.2 LTS

Active Python plugins
changeDataSource
3.1
solocator
1.6.0
pg_raster_import
3.2.0
trackable_project_files
v1.2.2
linking_relation_editor
v1.1.9
QgisModelBaker
v7.5.0
AtlasExportFunction
1.1
processing
2.12.99
db_manager
0.1.20

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nyalldawson**
Fixes #52833

### CODE REVIEW

File: src/core/layout/qgslayoutitemelevationprofile.cpp [hunk 1]
```diff
@@ -641,6 +641,9 @@ void QgsLayoutItemElevationProfile::paint( QPainter *painter, const QStyleOption
       layoutSize *= dotsPerMM; // output size will be in dots (pixels)
       painter->scale( 1 / dotsPerMM, 1 / dotsPerMM ); // scale painter from mm to dots
 
+      const double mapUnitsPerPixel = static_cast<double>( mPlot->xMaximum() - mPlot->xMinimum() ) / layoutSize.width();
+      rc.setMapToPixel( QgsMapToPixel( mapUnitsPerPixel ) );
```
Comment (nirvn) [inline src/core/layout/qgslayoutitemelevationprofile.cpp:645]: That will need to be added into the qgsquickelevtionprofillecanvas too I imagine?

**Review by nirvn — APPROVED** [review]

File: src/core/layout/qgslayoutitemelevationprofile.cpp (hunk 1 above)
Comment (nyalldawson) [reply src/core/layout/qgslayoutitemelevationprofile.cpp:645]: Done

Comment (nirvn) [reply src/core/layout/qgslayoutitemelevationprofile.cpp:645]: @nyalldawson , thanks.
