### PR TITLE
Fix split parts tool

### LINKED ISSUE #50348: Invalid geometry after 'split parts" in a multipolygon using QGIS 3.26.3
### What is the bug or the crash?

After making 'split parts' to a multipolygon, the result has been a multipolygon with invalid geometries.
A message appears that says:
"No part division has been done: The geometry is invalid. Please fix it before trying to split it."

### Steps to reproduce the issue

1. Select a polygon (I have a layer with only one polygon).
2. switch edition
3. Press the split parts icon
4. select two points that intersect the polygon to split it
5. do the same on one of the resulting parts
6. a yellow bar appears at the top of the screen with the mentioned error

### Versions

Versión de QGIS
3.26.3-Buenos Aires
Revisión del código de QGIS
65e4edfdada
Versión Qt
5.15.3
Versión de Python
3.9.5
Compilado contra GDAL/OGR
3.5.1
Ejecutándose contra GDAL/OGR
3.5.2
Versión de PROJ
9.1.0
Versión del registro de base de datos EPSG
v10.074 (2022-08-01)
Versión de GEOS
3.10.3-CAPI-1.16.1
Versión de SQLite
3.38.1
Versión de PDAL
2.4.3
Versión del cliente de PostgreSQL
unknown
Versión de SpatiaLite
5.0.1
Versión de QWT
6.1.6
Versión de QScintilla2
2.13.1
Versión del SO
Windows 10 Version 2009

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I don't know if this also happens in previous versions

Can I only use the Split Parts tool on a polygon once? Yes
The second time throws an error of:
"Geometry is invalid"

I don't think the "2 parts" works either although I'm a bit surprised it does produce a polygon that can be saved. The polygon has a self-intersection geometry error, however, and while self intersection errors can often be ignored, many tools won't run on them and that's probably why you can't do a third "split". If you run a fix geometries on it you'll get back your original polygon. If you run multipart to single part you get a split like a split features would do. So there's no gain, just pain

### LINKED ISSUE #51321: Data loss when using the "split parts" tool
### What is the bug or the crash?

When using the "split parts" tool on a part of a multipart polygon, another untouched part disappears completely.

The layer/polygon has no errors.

https://user-images.githubusercontent.com/1951107/209822246-c6336925-1073-4685-b9fa-dea63d0300b4.mp4

### Steps to reproduce the issue

Load the attached layer

Toggle editing and try split one of the parts.

### Versions

Latest 3.22 and 3.28 on Windows (untested other platforms but I will).

This is a regression as in older versions (i.e. 3.10) the bug is not present.

[teste.zip](https://github.com/qgis/QGIS/files/10314514/teste.zip)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by YoannQDQ**
## Description

Fixes #51321
Fixes #50348

When splitting a part of a MultiPolygon or MultiLinestring layer, the split part tools randomly drops some parts of the split feature.

This PR also fix a previous bug which prevented split geometries to be further split, since they were considered invalid by GEOS. The split parts tool calls `splitGeometry` individually on each part, which solves the problem. 

split

⚠️ Resulting multi geometries are still considered invalid though, so may not play well with other algorithms/processing tools.

### CODE REVIEW

**Comment by YoannQDQ** [comment]
The Windows build is failing, but I can't parse the logs to figure out why... If anyone can take a quick look, I'd appreciate it greatly!

**Comment by YoannQDQ** [comment]
When we split a Polygon with a line, we get a multipolygon that contains two polygons with a shared boundary, i.e. an invalid geometry, so we have no way around that. Fixing the geometry does not solve the issue, as it remove the split, so we get our polygon back with two added vertex (entry and out point of the splitline).

**Comment by gioman** [comment]
@YoannQDQ thanks, much appreciated!

**Comment by roya0045** [comment]
> When we split a Polygon with a line, we get a multipolygon that contains two polygons with a shared boundary, i.e. an invalid geometry, so we have no way around that. Fixing the geometry does not solve the issue, as it remove the split, so we get our polygon back with two added vertex (entry and out point of the splitline).

Ah right, I assume it was another issue, didn't think that two part of a multigeometry sharing vertices would be considered as invalid, seems strange.

**Comment by YoannQDQ** [comment]
If I understand correctly, they **can** share vertices, but they **cannot** share edges (at least two shared vertices in a row).

- [Shapely multipolygon](https://shapely.readthedocs.io/en/stable/manual.html#MultiPolygon)
- [PostGIS on validity](https://postgis.net/workshops/postgis-intro/validity.html#what-is-validity)

File: src/core/vector/qgsvectorlayereditutils.cpp [hunk 1]
```diff
@@ -542,41 +542,52 @@ Qgis::GeometryOperationResult QgsVectorLayerEditUtils::splitParts( const QgsPoin
...
 
-      if ( topologicalEditing )
-      {
-        QgsPointSequence::const_iterator topol_it = topologyTestPoints.constBegin();
-        for ( ; topol_it != topologyTestPoints.constEnd(); ++topol_it )
+        if ( topologicalEditing )
         {
-          addTopologicalPoints( *topol_it );
+          QgsPointSequence::const_iterator topol_it = topologyTestPoints.constBegin();
+          for ( ; topol_it != topologyTestPoints.constEnd(); ++topol_it )
```
Comment (troopa81) [inline src/core/vector/qgsvectorlayereditutils.cpp:565]: I think it would be better to add the topology points after we call changeGeometry, especially if we return in the middle of the splitting operation (we could have topology points althought the split has not been effective

File: src/core/vector/qgsvectorlayereditutils.cpp [hunk 2]
```diff
@@ -542,41 +542,52 @@ Qgis::GeometryOperationResult QgsVectorLayerEditUtils::splitParts( const QgsPoin
...
-    if ( splitFunctionReturn == Qgis::GeometryOperationResult::Success && !newGeometries.isEmpty() )
+    const QVector<QgsGeometry> geomCollection = featureGeom.asGeometryCollection();
+    QVector<QgsGeometry> resultCollection;
+    for ( QgsGeometry part : geomCollection )
     {
-      QgsGeometry newGeom( newGeometries.at( 0 ) );
-      newGeom.convertToMultiType();
+      QVector<QgsGeometry> newGeometries;
+      QgsPointSequence topologyTestPoints;
+      splitFunctionReturn = part.splitGeometry( splitLine, newGeometries, topologicalEditing, topologyTestPoints, false );
```
Comment (troopa81) [inline src/core/vector/qgsvectorlayereditutils.cpp:553]: Do you mind moving the declaration of splitFunctionReturn just here and make it const for the sake of clarity

**Review by troopa81 — COMMENTED** [review]
Thank you for tackling this! 

Could you add some unit tests [here](https://github.com/qgis/QGIS/blob/master/tests/src/python/test_qgsvectorlayereditutils.py#L54) for the different use cases (with multi part, sith single part, with invalid...) ?

File: src/core/vector/qgsvectorlayereditutils.cpp (hunk 2 above)
Comment (YoannQDQ) [reply src/core/vector/qgsvectorlayereditutils.cpp]: Ok

File: src/core/vector/qgsvectorlayereditutils.cpp (hunk 1 above)
Comment (YoannQDQ) [reply src/core/vector/qgsvectorlayereditutils.cpp]: Ok

**Review by troopa81 — APPROVED** [review]
LGTM!
