### PR TITLE
[Bugfix] geometry engine::main_angle : promote longer box in case of tie

### LINKED ISSUE #41022: main_angle() function calculates wrong angles in some cases
**Describe the bug**
The new `main_angle()` function calculates wrong angles in some cases. In the following screenshot the top row has "linear" rectangles rotated manually at about 10° per step. The two rows below have a duplicated rectangle rotated at exact steps of 10°. The CRS is EPSG:32618.

image

[style.qml.gz](https://github.com/qgis/QGIS/files/5816953/style.qml.gz)
The blue line points to the North, the red arrow goes from the centroid to a point in the direction of `main_angle($geometry)`, the label shows `main_angle($geometry)`, the line pattern is rotated `90-main_angle` degrees (as rotation 0 is in the East).

The arrow line is drawn with this Geometry Generator:
```
with_variable(
  'centroid',
  centroid($geometry),
  make_line(
    @centroid,
    project(@centroid, 1, radians(main_angle($geometry)))
  )
)
```

You can see that at some rotations of the rectangles, the calculated `main_angle` is 90° off.
- For the 5th rectangle in the top row, the angle should be ~40° but is ~130°.
- For the 8th it should be ~70° but is ~160°.
- In the bottom row the angle for the 2nd rectangle should be 70° but is 160°.
- In the bottom row the angle for the last rectangle should be 90° but is 0°.

**How to Reproduce**
I attached the data and the style to reproduce this.
[rectangles.wkt.txt](https://github.com/qgis/QGIS/files/5816936/rectangles.wkt.txt)

**QGIS and OS versions**
Master from today:

QGIS version | 3.17.0-Master | QGIS code revision | 24aa545754
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.3.0dev-762a261f32-dirty | Running against GDAL/OGR | 3.3.0dev-762a261f32-dirty
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.34.0 | Running against SQLite | 3.34.0
PostgreSQL Client Version | 13.1 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.6 | QScintilla2 Version | 2.11.6
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Arch Linux

### PR DESCRIPTION
**Pull request by roya0045**
## Description

Fixes #41022 

Takes into account the length of the bounding box when comparing results of similar area. A minimal relative epsilon was used, below that comparisong doesn't work. Could be upped if needed.

The 'bug' occured since it went from the first vertex, and if the result was optimal, it kept the same, resulting in the inconsistent results presented in the issue ticket.

### CODE REVIEW

**Comment by roya0045** [comment]
@kannes this is what I suggested in our exchanges and results are fine now if you want to test on your end.
image

The two in red were the wonky ones.

**Comment by nyalldawson** [comment]
Just to clarify my understanding -- couldn't an alternative tie breaker be "pick the orientation which has smallest area, and in the case of ties pick the one which has **smallest** rotation from the original geometry"?

**Comment by roya0045** [comment]
> Just to clarify my understanding -- couldn't an alternative tie breaker be "pick the orientation which has smallest area, and in the case of ties pick the one which has **smallest** rotation from the original geometry"?

Rotation doesn't matter in the current implementation as only the final result gets coerced between 0 and 180. During iteration rotation has no limit and in some instances starts in the 300+ and goes up to 600+. This would simply pick the first match ( which is what caused the error here) as the first point has the most incidence in the order of operation.

**Comment by kannes** [comment]
Thank you so much!

No time for testing but I am sure it works perfectly well :) Have a nice weekend!

**Comment by uclaros** [comment]
I think the bug here is the actual range of `main_angle` return values.
The description states:
> Returns the main angle of a geometry (clockwise, in degrees from North), which represents the angle of the oriented minimal bounding rectangle which completely covers the geometry.

There is no *de facto correct orientation* for any geometry, only minimal area envelopes. That's why I believe that `main_angle` should return values in the range `0 <= angle < 90` degrees. A value of 90 means it is already at a minimum envelope so it should be a 0, a 91 is one degree off from a 90 so only 1 degree off from a minimum envelope etc.

**Comment by kannes** [comment]
I don't understand your reasoning. By restricting to 0-90 a geometry like the "160.0" in the screenshot would get a main angle of 40, which would be the short distance. Why should that be the logical choice?

**Comment by uclaros** [comment]
> I don't understand your reasoning. By restricting to 0-90 a geometry like the "160.0" in the screenshot would get a main angle of 40, which would be the short distance. Why should that be the logical choice?

You are thinking in terms of "rotation from an initial orientation". The thing is that for any arbitrary shape there is no "correct, north-up orientation", only a rotation value that will cause a minimal area envelope.
In other words, what's the difference between 0 and 90 or 10 and 100?

**Comment by roya0045** [comment]
@uclaros I agreed that by default there are no preference in terms of width or height. Though most people would assume that the bounding box indicate the most elongated bounding box instead of the widest one. The importance of the starting node can make the result strange and this would also mean that even constrained between 0 and 180, you always have at least to possible result as the result can be rotated by 90 degree randomly. Constraining between 0 and 90 is bound to provide a viable bounding-box also.

**Comment by kannes** [comment]
Sorry, that 40 vs 70 was a typo.

I still don't understand your point, sorry. :( This is about the _main_ angle, so the "trend" or "general direction" of a polygon.

The difference between 10 and 100 is clear to me, in one case the polygon is "pointing" in the 10/190 direction, NE/SW, in the other case it "points" 100/280, SE/NW?

Example, this polygon's main angle is something in a SE/NW direction to me.
image

**Comment by uclaros** [comment]
So your definition of main angle is
> the angle of the oriented minimal bounding rectangle which completely covers the geometry and has the largest y dimension.

If I understand correctly

**Comment by roya0045** [comment]
@uclaros using the long axis to indicate the 'direction' of a minimal bounding square is the standard, yes.

**Comment by uclaros** [comment]
In that case this constraint should be taken into account when picking the correct MBR.
The logic can be changed to:
```c
    if ( currentArea  < area && bounds.width() <= bounds.height() )
```

The description should also be updated to properly describe how the algorithm works.

**Comment by roya0045** [comment]
> In that case this constraint should be taken into account when picking the correct MBR.
> The logic can be changed to:
> 
> ```c
>     if ( currentArea  < area && bounds.width() <= bounds.height() )
> ```
> 
> The description should also be updated to properly describe how the algorithm works.

I didn't want to go with && as I was not sure if it was impossible that a bounding box could not be repeated. This is why I went with or.

But another approach could be used also, find the minimalest box, then offset by 90 degree if width>height. This should rule out unique box issues. As all is wrapped by %180 it won't matter.

**Comment by uclaros** [comment]
@roya0045 I didn't test it, but it looks like it should handle all cases correctly!

The description of `main_angle()` should also be updated to clearly describe what the main angle is.

**Comment by roya0045** [comment]
@uclaros is the change in dox not ok with you?

**Comment by uclaros** [comment]
It's ok-ish as a non native speaker.
My point is to also update:
https://github.com/qgis/QGIS/blob/cefd4edbb056f0cafbd526c6929794850d33d5ae/resources/function_help/json/main_angle#L1-L8
which is what users see.

**Comment by roya0045** [comment]
@uclaros ah yes, always forget the json. But I'm curious to know which would be the better term, main axis, long axis, major axis, ??

**Comment by uclaros** [comment]
*Longest* I believe, since it implies that it is longer than the other one!

**Comment by roya0045** [comment]
@uclaros I'll go with long, the -est is not needed when you have only two choices.

**Comment by roya0045** [comment]
For the main_angle function I'm thinking of changing the text to "Returns the angle of the long axis (clockwise, in degrees from North) of the oriented minimal bounding rectangle, which completely covers the geometry."
@DelazJ any opinion on this?

File: resources/function_help/json/main_angle [hunk 1]
```diff
@@ -2,7 +2,7 @@
   "name": "main_angle",
   "type": "function",
   "groups": ["GeometryGroup"],
-  "description":"Returns the main angle of a geometry (clockwise, in degrees from North), which represents the angle of the oriented minimal bounding rectangle which completely covers the geometry.",
+  "description":"Returns the angle of the long axis (clockwise, in degrees from North) of the oriented minimal bounding rectangle, which completely covers the geometry.",
```
Comment (DelazJ) [inline resources/function_help/json/main_angle:5]: Looks clearer to me indeed. Thanks @roya0045 
Question: is the comma needed? The _which_ stands for _rectangle_, isn't it? Should they then be separated? That said, I'm not a native speaker/writer

Comment (roya0045) [reply resources/function_help/json/main_angle:5]: Since 'which completely covers the geometry' is additionnal information regarding the rectangle I added a comma to separate this. That rule exists in both french and english. I also felt that the phrase was too long otherwise.

**Comment by roya0045** [comment]
Fixes are done. Awaiting further comments

**Comment by roya0045** [comment]
it's fine.

**Comment by roya0045** [comment]
Not stale

**Comment by roya0045** [comment]
not stale

File: src/core/geometry/qgsinternalgeometryengine.cpp [hunk 2]
```diff
@@ -1503,6 +1503,13 @@ QgsGeometry QgsInternalGeometryEngine::orientedMinimumBoundingBox( double &area,
     pt1 = hull->vertexAt( vertexId );
   }
 
+  if ( width > height )
```
Comment (lbartoletti) [inline src/core/geometry/qgsinternalgeometryengine.cpp:1506]: Can you add a test for this case?

Comment (roya0045) [reply src/core/geometry/qgsinternalgeometryengine.cpp:1506]: Sure thing, I'll have one done as soon as I can!

**Comment by roya0045** [comment]
Still need to generate good test data.

**Comment by roya0045** [comment]
test is done, is ok.

File: tests/src/core/testqgsexpression.cpp [hunk 3]
```diff
@@ -1295,6 +1295,7 @@ class TestQgsExpression: public QObject
       QTest::newRow( "m_min line M NaN" ) << "m_min(make_line(geom_from_wkt('PointZM (0 0 0 nan)'),geom_from_wkt('PointZM (1 1 1 2)')))" << false << QVariant( );
       QTest::newRow( "m_min line" ) << "m_min(make_line(make_point_m(0,0,1),make_point_m(-1,-1,2),make_point_m(-2,-2,0)))" << false << QVariant( 0.0 );
       QTest::newRow( "main angle polygon" ) << "round(main_angle( geom_from_wkt('POLYGON((0 0,2 9,9 2,0 0))')))" << false << QVariant( 77 );
+      QTest::newRow( "main angle polygon edge case" ) << "round(main_angle( geom_from_wkt('POLYGON((353542.63843526 378974.92373469, 353544.95808017 378975.73690545, 353545.27173175 378974.84218528, 353542.95208684 378974.02901451, 353542.63843526 378974.92373469))')))" << false << QVariant( 71 );
```
Comment (olivierdalang) [inline tests/src/core/testqgsexpression.cpp:1298]: Arguably it would be better to also test QgsGeometry::orientedMinimumBoundingBox directly (so you don't only test for the angle, which doesn't necessarily mean width/height are right too).

It could easily be added here :
https://github.com/qgis/QGIS/blob/45c5a91d5f17126293f6addb86a412256bcd6cba/tests/src/core/geometry/testqgsgeometry.cpp#L2158

But IMO even without this it's already a valuable bugfix and already partially covered by test, so could also be merged as is if you don't manage to add that before next release

**Review by olivierdalang — APPROVED** [review]

File: tests/src/core/testqgsexpression.cpp (hunk 3 above)
Comment (roya0045) [reply tests/src/core/testqgsexpression.cpp:1298]: Honestly, I'm not even sure how the bug occurs. When reprojecting the data it fails to bug. This seems to be a very edge case that is being fixed. I just assume that if the test is fine, so should the rest. I can look into it if needed.

Comment (roya0045) [reply tests/src/core/testqgsexpression.cpp:1298]: Thanks for the review also :)

Comment (kannes) [reply tests/src/core/testqgsexpression.cpp:1298]: Maybe it would be nice to construct a test case with small integer numbers instead? That might make it more clear.

Comment (roya0045) [reply tests/src/core/testqgsexpression.cpp:1298]: @kannes if you have any way to reproduce the bug with integer coordinates I'll take your test, otherwise I won't waste a second more of my time on fiddling with this.

Comment (kannes) [reply tests/src/core/testqgsexpression.cpp:1298]: You are right! Sorry, that comment of mine was unnecessary without providing a test case myself. Perfect is the enemy of good and I don't even know enough about QGIS' development and testing protocol. Thank you so much for working on this!

Comment (roya0045) [reply tests/src/core/testqgsexpression.cpp:1298]: @kannes Didn't mean to sound harsh, I just tried many things and this bug is quite hard to replicate, just moving the coordinates, changing projection or anything just reset something and make it behaves 'ok'. I tried many things and I just gave up.

**Comment by roya0045** [comment]
staying alive

File: src/core/geometry/qgsinternalgeometryengine.cpp [hunk 4]
```diff
@@ -1503,6 +1503,13 @@ QgsGeometry QgsInternalGeometryEngine::orientedMinimumBoundingBox( double &area,
...
+  {
+    width = minRect.height();
+    height = minRect.width();
+    angle = angle + 90;
```
Comment (lbartoletti) [inline src/core/geometry/qgsinternalgeometryengine.cpp:1510]:
```suggestion
    angle = angle + 90.0;
```

**Review by lbartoletti — APPROVED** [review]

**Comment by agiudiceandrea** [comment]
@roya0045 maybe this PR introduced the https://github.com/qgis/QGIS/issues/47726 regression.

**Comment by roya0045** [comment]
> @roya0045 maybe this PR introduced the #47726 regression.

I don't mind if it gets reverted to fix the bounding box, maybe there's a better way to handle things.

**Comment by agiudiceandrea** [comment]
@roya0045 I think I have a very simple fix: please see https://github.com/qgis/QGIS/pull/47849
