### PR TITLE
Fix expression description HTML

### LINKED ISSUE #36191: Line breaks are ignored in the user expression help panel
As shown in the following image, in the help panel, the expression does not take into account line breaks, leading to comments and code being merged, less readable
image

### PR DESCRIPTION
**Pull request by troopa81**
## Description

Fixes #36191

When mixed with other html content, expression description HTML makes the rendering of carriage return in `<pre>` fails because of the following line in HTML

```html
<meta name="qrichtext" content="1" />
```
This PR proposes to remove this line from the returned HTML.

### CODE REVIEW

File: src/gui/qgsexpressionstoredialog.h [hunk 1]
```diff
@@ -55,7 +55,7 @@ class GUI_EXPORT QgsExpressionStoreDialog : public QDialog, private Ui::QgsExpre
     /**
      * Returns the help text
      */
-    QString helpText() { return  mHelpText->toHtml(); }
+    QString helpText();
```
Comment (m-kuhn) [inline src/gui/qgsexpressionstoredialog.h:58]:
```suggestion
    QString helpText() const;
```

File: src/gui/qgsexpressionstoredialog.cpp [hunk 2]
```diff
@@ -59,3 +59,10 @@ QgsExpressionStoreDialog::QgsExpressionStoreDialog( const QString &label, const
   mLabel->setText( labelFixed );
 }
 
+QString QgsExpressionStoreDialog::helpText()
```
Comment (m-kuhn) [inline src/gui/qgsexpressionstoredialog.cpp:62]:
```suggestion
QString QgsExpressionStoreDialog::helpText() const
```
