### PR TITLE
Skip moving faces validity checks if a single vertex is selected

### LINKED ISSUE #56897: Slow editing of single mesh vertex
### What is the bug or the crash?

When editing a large SERAFIN mesh, UI becomes very slow if user trie to move a single vertex while it is fine when moving several vertices.
See animation
Animation7

### Steps to reproduce the issue

Can't provide this specific mesh

### Versions

3.36.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nicogodet**
## AI disclosure

Claude helps me to write debug output in order to diagnose the issue and identify where the bottleneck occurred. I'm not very familiar with C++, debug output, etc.
The fix is quite trivial in the end.

## What's the issue ?

Closes https://github.com/qgis/QGIS/issues/56897

When a single vertex is selected, `movingFacesGeometry` is empty and `mCurrentLayer->triangularMesh()->nativeFaceIndexForRectangle()` returns ALL faces. This causes a huge slowdown in the case of big meshes.
Furthermore, checks on moving faces are useless if a single vertex is selected; `canBeTransformed` already performs all necessary checks.

Before:

> moveSelection: vertices= 1 borderFaces= 6 edges= 0 ms canBeTransformed= 0 ms postChecks= 688 ms total= 689 ms allowed= true

After:

> moveSelection: vertices= 1 borderFaces= 6 edges= 0 ms canBeTransformed= 0 ms postChecks= 0 ms total= 0 ms allowed= true	

postChecks involved 380 000 faces to be checked for nothing

### CODE REVIEW

**Comment by uclaros** [comment]
Sounds like `nativeFaceIndexForRectangle()` with a null rectangle  returning _ALL_ faces is not the right thing to do.
Would it not make sense for it to return empty list?
That would mean you could move the `movingFacesGeometry.isEmpty()` check to the second check for free vertices a few lines down.

**Comment by nicogodet** [comment]
> Sounds like `nativeFaceIndexForRectangle()` with a null rectangle returning ALL faces is not the right thing to do.

I agree. But I didn't look deeper as checks on "moving faces" are irrelevant for a single moving vertex (there is no moving faces in this case). And I don't use mesh with "free vertex", I don't understand the topology behind it (but that's not the question).

The rectangle is never check for a null value. I don't know where a null check should be added: in QgsTriangularMesh?, in QgsMeshSpatialIndex?

**Comment by uclaros** [comment]
I'd say `QgsMeshSpatialIndex` is probably the best place to check and exit early if the rectangle is null

**Comment by nicogodet** [comment]
@uclaros OK to add an early return in `QgsMeshSpatialIndex.intersect()`. I choose `isEmpty`.
This modif is enough to fix the issue I reported.

If `movingFacesGeometry` is empty, both checks `the polygons formed by the moving faces contains something else` and `last check, the free vertices...` are useless even if `freeVerticesIndexes` is not empty: `mIsMovingAllowed &= !movingFacesGeometry.contains( &pointInMap );` <-- a null geometry can not contain a point.
Keeping the edit in my first commit wouldn't hurt.

File: src/core/mesh/qgsmeshspatialindex.cpp [hunk 1]
```diff
@@ -389,6 +389,9 @@ QgsMeshSpatialIndex &QgsMeshSpatialIndex::operator=( QgsMeshSpatialIndex &&other
 QList<int> QgsMeshSpatialIndex::intersects( const QgsRectangle &rect ) const
 {
   QList<int> list;
+  if ( rect.isEmpty() )
```
Comment (uclaros) [inline src/core/mesh/qgsmeshspatialindex.cpp]: I think `isNull()` should be checked here instead.
An empty rectangle can be the bounding box of a point, and it should still return a valid intersection with the spatial index.

**Comment by nicogodet** [comment]
Wow. All these failures are not a good sign.

File: src/core/mesh/qgsmeshspatialindex.cpp (hunk 1 above)
Comment (nicogodet) [reply src/core/mesh/qgsmeshspatialindex.cpp]: I may solve all failures switching to isNull. 

Other methods use intersect with a QgsRectangle made from 2 identical points which result in an empty rectangle

**Comment by nicogodet** [comment]
@uclaros All green!

If someone could remove previous automatic comments about test failures

**Review by nyalldawson — APPROVED** [review]
