### PR TITLE
Avoid styleChanged() signals being raised before new labeling configuration is set when changing a vector layer's style preset

### LINKED ISSUE #42310: Layer Styling Labelling panel does not update when the current layer style is switched
**Describe the bug**
The Layer Styling Labelling panel does not update when the current layer style is switched, breaking the style switch to and the relationship of undo/redo operations.

**How to Reproduce**

1. Have a map and have the layer styling panel open (e. g. "world" layer in default styling, no labels)
2. Rename the current style to "1"
3. Add a style, name it "2", style it differently (e. g. "world" layer categorized by fid)
4. You can switch between them, change style, undo styling. Everything is fine.
5. Switch to style "2"
6. Switch to labelling in the Layer Styling panel
7. Set a label (e. g. by NAME)
8. Switch back to style "1"
9. ->

- The Layer Styling panel stays on the label options of style "2".
- Undo/redo buttons now apply the operations of style "2" to style "1".
- **The user loses their style** unless they save and reload the project without any further interaction with the Layer Styling panel.

**QGIS and OS versions**

QGIS version | 3.18.0-Zürich | QGIS code branch | Release 3.18
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.35.0 | Running against SQLite | 3.35.1
PostgreSQL Client Version | 13.2 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.6 | QScintilla2 Version | 2.12.1
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Arch Linux

### PR DESCRIPTION
**Pull request by nyalldawson**
This causes the layer styling dock to update before the layer's
new labeling settings are set, so the dock shows the incorrect
label settings for the previously used style

Fixes #42310

### CODE REVIEW

**Review by rouault — COMMENTED** [review]
Perhaps add a comment to the styleChanged(); signal definition to mention it shouldn't be emitted directly but through emitStyleChanged() ?

**Comment by nyalldawson** [comment]
@rouault done!

File: src/core/qgsmaplayer.h [hunk 1]
```diff
@@ -1420,7 +1420,12 @@ class CORE_EXPORT QgsMapLayer : public QObject
     void opacityChanged( double opacity );
 
     /**
-     * Signal emitted when renderer is changed.
+     * Emitted when the layer's style is changed. This includes any changes which affect the layer's
```
Comment (rouault) [inline src/core/qgsmaplayer.h:1423]: hum, you added that comment to the doc of rendererChanged(), not styleChanged()

Comment (nyalldawson) [reply src/core/qgsmaplayer.h:1423]: Ooops....

Comment (nyalldawson) [reply src/core/qgsmaplayer.h]: Fixed

**Review by rouault — APPROVED** [review]

**Comment by kannes** [comment]
Thank you, Nyall!
