### PR TITLE
[processing] save NULL and empty values into different files in Split Vector Layer algorithm (fix #38105)

### LINKED ISSUE #38105: Split Vector Layer algorithm does not export both null and empty values
**Describe the bug**
The Split Vector Layer algorithm exports both null and empty values to the same filename silently overwriting the former with the later.
This was unintentionally fixed in the couple of last versions when ported to c++ and added a regression by replacing the filename with an numeric id.
By fixing this regression, the empty/null bug was reintroduced, so this is technically a regression too

**How to Reproduce**
Use the Split vector layer algorithm and use a field that contains both null and empty string values.
A single file is created containing only null or empty values.

### PR DESCRIPTION
**Pull request by alexbruy**
## Description
The Split Vector Layer algorithm exports both NULL and empty attribute values to the same filename, as a result one file overwrites another and some results are lost. Proposed PR assigns different suffixes for such files (`_EMPTY` and `_NULL`).

Fixes #38105.

Also fix unreported bug with displaying incorrect number of features written to each output file.

### CODE REVIEW

File: src/analysis/processing/qgsalgorithmsplitvectorlayer.cpp [hunk 1]
```diff
@@ -119,12 +119,25 @@ QVariantMap QgsSplitVectorLayerAlgorithm::processAlgorithm( const QVariantMap &p
     if ( feedback->isCanceled() )
       break;
 
-    QString fileName = QStringLiteral( "%1_%2.%3" ).arg( baseName ).arg( ( *it ).toString() ).arg( outputFormat );
+    QString fileName;
+    if ( ( *it ).isNull() )
+    {
+      fileName = QStringLiteral( "%1_NULL.%2" ).arg( baseName ).arg( outputFormat );
+    }
+    else if ( !( *it ).isNull() && ( *it ).toString().isEmpty() )
```
Comment (nyalldawson) [inline src/analysis/processing/qgsalgorithmsplitvectorlayer.cpp:127]: The ! isNull check is redundant here

**Review by m-kuhn — APPROVED** [review]

File: src/analysis/processing/qgsalgorithmsplitvectorlayer.cpp (hunk 1 above)
Comment (alexbruy) [reply src/analysis/processing/qgsalgorithmsplitvectorlayer.cpp]: Fixed.

**Comment by m-kuhn** [comment]
FYI: Backport bot updated to use `failed backport` instead of `backport failed` to avoid the backport loop issue in the future. CC @3nids
