### PR TITLE
[wms] Fix local raster XYZ tiles directory layer loading (fixes #56371)

### LINKED ISSUE #56371: [Data Source Manager] Adding a local raster XYZ Tiles directory as layer is no longer possible
### What is the bug or the crash?

Having a local raster [XYZ Tiles](https://docs.qgis.org/testing/en/docs/user_manual/managing_data_source/opening_data.html#using-xyz-tile-services) directory in e.g. the `C:\OSGeo4W_V2_6\TILES\` folder, it is no longer possible to add it as a raster XYZ Tiles layer using QGIS 3.34.3
See a screen recording:

https://github.com/qgis/QGIS/assets/16253859/4c935f0d-f806-42a3-afc2-60a1b3403436

The issue doesn't occur using QGIS 3.28.15:

https://github.com/qgis/QGIS/assets/16253859/3af73435-1a47-4d31-bb32-8bf7843b16e2

### Steps to reproduce the issue

1. Go to Data Source Manager -> XYZ
2. Add a new XYZ connection with URL `file:///C:/OSGeo4W_V2_6/TILES/{z}/{x}/{y}.png` and other parameters
3. Select the newly created connection
4. See that the URL parameter is empty, while the other parameters are correctly displayed, and the "Add" button is disabled and grayed out

image

Directly inserting the URL `file:///C:/OSGeo4W_V2_6/TILES/{z}/{x}/{y}.png` as "Custom" connection, then the "Add" button is enabled but adding the layer fails with the following errors depending on the other settings:

```
2024-02-15T17:39:48     CRITICAL    Invalid Data Source : http-header:referer=&interpretation=terrariumterrain&url=file:///C:/OSGeo4W_V2_6/TILES/%7Bz%7D/%7Bx%7D/%7By%7D.png&type=xyz&url=file:///C:/OSGeo4W_V2_6/TILES/%7Bz%7D/%7Bx%7D/%7By%7D.png&zmax=8&zmin=5 is not a valid or recognized data source.
2024-02-15T17:40:16     CRITICAL    Invalid Data Source : interpretation=terrariumterrain&url=file:///C:/OSGeo4W_V2_6/TILES/%7Bz%7D/%7Bx%7D/%7By%7D.png is not a valid or recognized data source.
2024-02-15T17:41:11     CRITICAL    Invalid Data Source : url=file:///C:/OSGeo4W_V2_6/TILES/%7Bz%7D/%7Bx%7D/%7By%7D.png&zmax=18&zmin=5 is not a valid or recognized data source.
```

### Versions

QGIS version
3.34.3-Prizren
QGIS code revision
47373234ac
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.3
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 1903

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Adding the raster XYZ Tiles directory using the QGIS 3.34.3 Browser is also no longer possible, while it is possible using the QGIS 3.28.15 Browser as previously reported: see https://github.com/qgis/QGIS/issues/55391.

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This PR fixes a WMS provider regression whereas a local directory (i.e. file://my/directory/{z}/{x}/{y}.png) XYZ tiles layer wouldn't load anymore.

Fixes #56371.

### CODE REVIEW

**Review by rouault — COMMENTED** [review]
maybe worth a test?

**Review by rouault — APPROVED** [review]

**Comment by agiudiceandrea** [comment]
Hi @nirvn, thanks for the fix. It is now possible again to add a local XYZ tile directory!
Anyway, I noticed a glitch in the XYZ GUI of the Data Source Manager which you may also fix while you are on it....

The "Interpretation" combo box is not correctly updated when a XYZ connection is changed. Such issue leads to adding the XYZ layers with incorrect parameters and thus making them not displayed or incorrectly displayed.

https://github.com/qgis/QGIS/assets/16253859/15039ebe-4405-4ec5-b8b1-186478d4a40c

In fact, following the steps in the screen recording, the OpenStreeMap layer is incorrectly added and not displayed.

**Comment by nirvn** [comment]
@agiudiceandrea , issue reported here fixed in this PR: https://github.com/qgis/QGIS/pull/56441

**Comment by agiudiceandrea** [comment]
Thanks again.

**Comment by nyalldawson** [comment]
@nirvn looks like valid failures here

File: tests/src/providers/testqgswmsprovider.cpp [hunk 1]
```diff
@@ -381,6 +381,20 @@ class TestQgsWmsProvider: public QgsTest
...
+
+      QgsProviderMetadata *wmsMetadata = QgsProviderRegistry::instance()->providerMetadata( "wms" );
+      QVERIFY( wmsMetadata );
+
+      // query sublayers
+      QList< QgsProviderSublayerDetails > sublayers;
+      sublayers = wmsMetadata->querySublayers( QStringLiteral( "type=xyz&url=file:///my/xyz/directory/%7Bz%7D/%7Bx%7D/%7By%7D.png&zmax=19&zmin=0" ) );
+      QCOMPARE( sublayers.size(), 1 );
+      QCOMPARE( sublayers.at( 0 ).providerKey(), QStringLiteral( "wms" ) );
+      QCOMPARE( sublayers.at( 0 ).name(), QStringLiteral( "" ) );
```
Comment (nirvn) [inline tests/src/providers/testqgswmsprovider.cpp:393]:
```suggestion
      QCOMPARE( sublayers.at( 0 ).name(), QLatin1String( "" ) );
```

**Review by nyalldawson — APPROVED** [review]
