### PR TITLE
Fix crash in rendering on proj 6 builds

### LINKED ISSUE #33902: QGIS 3.10.x crashes on zoom in/out
QGIS 3.10.2 on Windows
Zooming in and out (fast) a few times on the attached _qgis_crash.qgs_ project closes QGIS instantly, without the crash report screen.  Doing the same on the other project file (_qgis_no_crash.qgs_) on the other hand works fine. The only difference between the two is the fill type of the included two layers. On previous QGIS versions (3.4.5, 3.8.3) both projects worked fine.  Now I'm aware the vector datasets have some validity errors, but this still shouldn't be happening.

[qgis_crash_on_zoom.zip](https://github.com/qgis/QGIS/files/4083795/qgis_crash_on_zoom.zip)

### PR DESCRIPTION
**Pull request by nyalldawson**
Ensure PJ* objects are never reused across threads.

Fixes #33902

### CODE REVIEW

**Comment by nyalldawson** [comment]
@rouault can i get your eyes on this one?

**Comment by nirvn** [comment]
Oh great, this was on my machine the last in-your-face stability issue with windows builds.

File: src/core/qgscoordinatereferencesystem_p.h [hunk 1]
```diff
@@ -124,6 +136,9 @@ class QgsCoordinateReferenceSystemPrivate : public QSharedData
     bool mIsValid = false;
 
 #if PROJ_VERSION_MAJOR>=6
+
+    // this is the "master" proj object, to be used as a template for new proj objects created on different threads ONLY.
+    // Always use threadLocalProjObject() instead of this.
```
Comment (rouault) [inline src/core/qgscoordinatereferencesystem_p.h]: are we sure that mPj will be destroyed before the PJ_CONTEXT* that owns it ?

File: src/core/qgscoordinatereferencesystem_p.h [hunk 2]
```diff
@@ -138,6 +153,49 @@ class QgsCoordinateReferenceSystemPrivate : public QSharedData
     //! Whether this is a coordinate system has inverted axis
     mutable bool mAxisInverted = false;
 
+#if PROJ_VERSION_MAJOR>=6
+    mutable QReadWriteLock mProjLock;
+    mutable QMap < uintptr_t, PJ * > mProjObjects;
```
Comment (rouault) [inline src/core/qgscoordinatereferencesystem_p.h]: any reason to use uintptr_t instead of PJ_CONTEXT* ?

Comment (nyalldawson) [reply src/core/qgscoordinatereferencesystem_p.h]: Nope, good point!

File: src/core/qgscoordinatereferencesystem_p.h (hunk 1 above)
Comment (nyalldawson) [reply src/core/qgscoordinatereferencesystem_p.h]: This won't have changed in this PR, but I could add mPj to removeObjectsBelongingToCurrentThread for safety?

Comment (nyalldawson) [reply src/core/qgscoordinatereferencesystem_p.h]: @rouault can you get the context which a PJ* belongs to? Does api exist for that?

Comment (rouault) [reply src/core/qgscoordinatereferencesystem_p.h]: > This won't have changed in this PR

agreed

> but I could add mPj to removeObjectsBelongingToCurrentThread for safety?

then QgsCoordinateReferenceSystemPrivate will have a nullptr mPj and be inconsistent, no ? (in the unlikely scenario that a temporary thread would create a CRS and pass it to the main thread)
But, assuming that a QgsCoordinateReferenceSystem object cannot be simultaneously used by several threads at the same time, I'm wondering if instead of that logic of having a per-thread cache of PJ* objects , you couldn't just use proj_assign_context() with the current TLS context ? And at destruction time of mPj, you create a temporary PJ_CONTEXT like done in QgsCoordinateTransformPrivate::freeProj()

Comment (rouault) [reply src/core/qgscoordinatereferencesystem_p.h]: > can you get the context which a PJ* belongs to?

I don't think so. But proj_assign_context() should be cheap enough to do it systematically

Comment (nyalldawson) [reply src/core/qgscoordinatereferencesystem_p.h]: > then QgsCoordinateReferenceSystemPrivate will have a nullptr mPj and be inconsistent, no 

That's fine -- there's already circumstances when this can be nullptr, so it's already guarded against this.

> But, assuming that a QgsCoordinateReferenceSystem object cannot be simultaneously used by several threads at the same time

it can be -- that's the root cause of the issue here.

> And at destruction time of mPj, you create a temporary PJ_CONTEXT like done in QgsCoordinateTransformPrivate::freeProj()

Will do - incoming shortly.

**Comment by jef-n** [comment]
Guess it'll take to morning in my tz for this to land in 3.10…

File: src/core/qgscoordinatereferencesystem_p.h (hunk 1 above)
Comment (nyalldawson) [reply src/core/qgscoordinatereferencesystem_p.h]: > I don't think so. 

No worries - I can easily workaround this by storing the owner PJ_CONTEXT in QgsCoordinateReferenceSystemPrivate

**Comment by nyalldawson** [comment]
@jef-n I'm nearly done... about to push a new version (still need to backport though)

**Comment by nyalldawson** [comment]
Should be good for merging...

**Comment by nirvn** [comment]
I seen green everywhere :wink:
