### PR TITLE
QgsRasterLayer: readXml(): read layer notes even when opening with FlagDontResolveLayers

### LINKED ISSUE #58818: Layer user notes only available for QgsVectorLayer when reading a project with flag QgsProject.FlagDontResolveLayers
### What is the bug or the crash?

When a `QgsProject` is read from a file with flag `QgsProject.FlagDontResolveLayers` we can get layer user notes only for `QgsVectorLayer`

I looked into the code for differences between `QgqVectorLayer` and other layer (for instance `QgsRasterLayer`).

For `QgsRasterLayer` the main difference is that we never load symbology if the data provider is not set (consequence of the `QgsProject.FlagDontResolveLayers`  flags: 

https://github.com/qgis/QGIS/blob/6bf3ee0f3086cc4164c2a608ac4dc815b62a6cf1/src/core/raster/qgsrasterlayer.cpp#L2410-L2420

### Steps to reproduce the issue

1. Create a QGIS project
2. Load a vector layer
3. Add a layer note to this vector layer
4. Load a raster layer
5. Add a layer note to this raster layer
6. Save QGIS project 
7. Run this python code

```python
qgs_project = QgsProject()
path = "/path/to/created/qgis_project.qgz"
project_qgs.read(path, QgsProject.FlagDontResolveLayers)

for name, layer in project_qgs.mapLayers().items():
    print(f"{name=} {QgsLayerNotesUtils.layerNotes(layer)=}")
```

There should be a layer note available for all layers.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.36.3-Maidenhead | QGIS code revision | 2df9655469b
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 14.11 (Ubuntu 14.11-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.3 LTS
  |   |   |  
Active Python plugins
plugin_reloader | 0.11
french_locator_filter | 1.1.1
processing | 2.12.99
MetaSearch | 0.3.6
grassprovider | 2.12.99
db_manager | 0.1.20
menu_from_project | 2.2.0-beta1

</body></html>QGIS version
3.36.3-Maidenhead
QGIS code revision
[2df9655469b](https://github.com/qgis/QGIS/commit/2df9655469b)
Qt version
5.15.3
Python version
3.10.12
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
14.11 (Ubuntu 14.11-0ubuntu0.22.04.1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.3 LTS

Active Python plugins
plugin_reloader
0.11
french_locator_filter
1.1.1
processing
2.12.99
MetaSearch
0.3.6
grassprovider
2.12.99
db_manager
0.1.20
menu_from_project
2.2.0-beta1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I need to access layer user note for the plugin https://plugins.qgis.org/plugins/menu_from_project/

This plugin allow user to have a menu with all layer and group inside a QGIS project.

To avoid manual parsing of the .xml for QGIS project we would like to go with a `QgsProject` that already have all the needed informations.

### PR DESCRIPTION
**Pull request by rouault**
Fixes #58818

Not totally sure if it is safe enough to be backported to LTR (the mDataProvider check at line 2219 had to be added to avoid a crash)

### CODE REVIEW

File: src/core/raster/qgsrasterlayer.cpp [hunk 1]
```diff
@@ -2216,9 +2216,9 @@ bool QgsRasterLayer::readSymbology( const QDomNode &layer_node, QString &errorMe
     {
       const QString rendererType = rasterRendererElem.attribute( QStringLiteral( "type" ) );
       QgsRasterRendererRegistryEntry rendererEntry;
-      if ( QgsApplication::rasterRendererRegistry()->rendererData( rendererType, rendererEntry ) )
+      if ( mDataProvider && QgsApplication::rasterRendererRegistry()->rendererData( rendererType, rendererEntry ) )
```
Comment (nyalldawson) [inline src/core/raster/qgsrasterlayer.cpp:2219]: This isn't safe to do -- it would cause loss of style in case of a layer with a broken file path. (Same with line 2455). Is there an alternative way to fix this?

Comment (rouault) [reply src/core/raster/qgsrasterlayer.cpp:2219]: >  Is there an alternative way to fix this?

Hum, I'm not sure. Not familiar enough with that logic to have an enlightened opinion.

Is the issue is that we now return true in readXml() without having loaded everything in FlatDontResolveLayers mode.
If returning false would solve your concern, then I've verified that doing the follow still solves #58818:

```

  if ( ! mDataProvider )
  {
    if ( !( mReadFlags & QgsMapLayer::FlagDontResolveLayers ) )
    {
      QgsDebugError( QStringLiteral( "Raster data provider could not be created for %1" ).arg( mDataSource ) );
    }

    const QDomElement layerElement = layer_node.toElement();
    readCommonStyle( layerElement, context, QgsMapLayer::AllStyleCategories );

    return false;
  }
```

At least, that's not worse than the current situation, at least if it doesn't solve entirely your concern

Comment (nyalldawson) [reply src/core/raster/qgsrasterlayer.cpp:2219]: Actually sorry, I'm completely wrong here. I was getting mistaken with the vector model where an invalid layer == no data provider. For rasters we still have a provider object, it's just invalid!

Sorry for the noise!

**Review by nyalldawson — APPROVED** [review]
