### PR TITLE
Fix crash when copc file is not there

### LINKED ISSUE #48900: Deleting loaded copc file causes a crash
### What is the bug or the crash?

If a copc file that is opened by qgis as a layer is deleted from the filesystem, qgis crashes when trying to refresh the view

### Steps to reproduce the issue

1. load a copc file (directly or by indexing a laz file)
2. delete copc file from filesystem
3. zoom in
4. crash

### Versions

master on Debian testing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by uclaros**
## Description
Fix #48900

### CODE REVIEW

File: src/core/pointcloud/qgscopcpointcloudindex.cpp [hunk 1]
```diff
@@ -157,6 +157,11 @@ QgsPointCloudBlock *QgsCopcPointCloudIndex::nodeData( const IndexedPointCloudNod
   std::ifstream file( QgsLazDecoder::toNativePath( mFileName ), std::ios::binary );
   file.seekg( blockOffset );
   file.read( rawBlockData.data(), blockSize );
+  if ( !file )
```
Comment (nyalldawson) [inline src/core/pointcloud/qgscopcpointcloudindex.cpp:160]: why is this check after the seek/read?

Comment (uclaros) [reply src/core/pointcloud/qgscopcpointcloudindex.cpp:160]: Both `seekg()` and `read()` may set the `badbit` in `ifstream`, so I thought we can also handle some unexpected `ifstream` error (eg blockOffset out of bounds?)

Comment (nyalldawson) [reply src/core/pointcloud/qgscopcpointcloudindex.cpp:160]: Ok, sounds fair enough to me!

**Review by nyalldawson — APPROVED** [review]
