### PR TITLE
Fix index lost on reload in Attribute Table

### LINKED ISSUE #43902: Attribute table form view looses index when a layer depending on changed
When making changes on a layer the current feature in the attribute table form view is depending on (with layer dependencies) the current layer refreshes as expected but the index is lost and it "jumps" to the first entry.

- Having a reference with parent "wald" and child "baum"
- Having a layer dependency on layer "wald" for layer "baum"
- Having a relation editor widget on the "wald" form

attr_table_loosing_index

**QGIS and OS versions**
- Master 870945c476c1a429eb410af2a793644a7b1db85f and 3.16 LTR
- Ubuntu 20.04

**Demoproject:**
[datallama.zip](https://github.com/qgis/QGIS/files/6707229/datallama.zip)

### PR DESCRIPTION
**Pull request by signedav**
On layer refresh the last index was never concerned. This leaded to confusion when working in the attribute table with relation editors and dependencies:
- Working on form of feature x - working on relation editor, doing a save (on child layer)
- Index lost and is now on the first feature - user is confused since he/she does not noticed the index jump and continues working on the first feature (instead of feature x) - and user breaks his/her data See #43902

In this implementation the member variable `mLastEditSelectionFid? keeping it. See

This implementation fixes #43902

***This PR is based on the branch of #52045***

### CODE REVIEW

File: src/gui/attributetable/qgsfeaturelistview.cpp [hunk 1]
```diff
@@ -183,6 +183,17 @@ void QgsFeatureListView::editSelectionChanged( const QItemSelection &deselected,
...
+  if ( !selected.isEmpty() )
+  {
+    const QModelIndexList indexList = selected.indexes();
+    if ( !indexList.isEmpty() )
+    {
+      QgsFeature selectedFeature;
+      mModel->featureByIndex( mModel->mapFromMaster( indexList.first() ), selectedFeature );
+      mLastEditSelectionFid = selectedFeature.id();
+    }
+  }
```
Comment (m-kuhn) [inline src/gui/attributetable/qgsfeaturelistview.cpp:195]: Else set to null fid?

Comment (signedav) [reply src/gui/attributetable/qgsfeaturelistview.cpp:195]: shouldn't happen. But yes to QgsFeatureId()...

Comment (m-kuhn) [reply src/gui/attributetable/qgsfeaturelistview.cpp:195]: if it _really_ shouldn't happen you can also add a `Q_ASSERT( false )`

Comment (signedav) [reply src/gui/attributetable/qgsfeaturelistview.cpp:195]: I'm not 100% sure. In the workflows I know it does not happen. But it's the attribute table. When it's null just nothing happens (index might jump to 0 like before...) so I would feel better with it...

**Review by m-kuhn — APPROVED** [review]
