### PR TITLE
Block the events while showing a dialog

### LINKED ISSUE #26948: Crash when clicking browse button in attachment edit widget (PLEASE RE-ADD THE BUTTON)
26.7.2019 - @m-kuhn 

> The browse button has been removed as a band aid to prevent the crash.
> Fixing the browse button will require additional work based on the analysis in https://github.com/qgis/QGIS/issues/26948#issuecomment-514972558 .

-------------------

Author Name: **Tom Chadwin** (@tomchadwin)
Original Redmine Issue: [19118](https://issues.qgis.org/issues/19118)
Affected QGIS version: 3.7(master)
Redmine category:edit_widget

---
Steps to recreate:

1. Open a vector layer with at least one text field
2. Change a text field's edit widget to Attachment
3. Open the layer's attribute table
4. Toggle editing
5. Highlight a value in the column whose edit widget you just changed
6. Click the ellipsis browse button

On Win 7 and 10, we have confirmations that this causes a full QGIS crash, with no QGIS crash handler.

---

- [2019-01-29_09-29-35.gif](https://issues.qgis.org/attachments/download/14190/2019-01-29_09-29-35.gif) (Tom Chadwin)
- [Screenshot_2019-05-22_11-37-15.png](https://issues.qgis.org/attachments/download/14971/Screenshot_2019-05-22_11-37-15.png) (Grga Franges)

---

Related issue(s): #27961 (duplicates), #29182 (duplicates), #29271 (duplicates), #29408 (duplicates), #29590 (relates)
Redmine related issue(s): [20140](https://issues.qgis.org/issues/20140), [21365](https://issues.qgis.org/issues/21365), [21454](https://issues.qgis.org/issues/21454), [21592](https://issues.qgis.org/issues/21592), [21775](https://issues.qgis.org/issues/21775)

---

### PR DESCRIPTION
**Pull request by bog-dan-ro**
When showing a file dialog, Qt can choose to use the "system" file
dialog, which will make QgsExternalResourceWidget to loose the focus.
This patch blocks all the events that are sent to
QgsExternalResourceWidget while a dialog is shown, this way it will keep
the focus until the dialog is closed.

Fixes: #26948

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `Fixes #11111` at the bottom of the commit message
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit
- [ ] I have evaluated whether it is appropriate for this PR to be backported, backport requests are left as label or comment

### CODE REVIEW

**Comment by m-kuhn** [comment]
Thanks @bog-dan-ro 

Would it be possible to only ignore specific events (to avoid funky effects caused by missed events)?

File: src/gui/qgsfilewidget.h [hunk 1]
```diff
@@ -184,6 +184,9 @@ class GUI_EXPORT QgsFileWidget : public QWidget
     //! emitted as soon as the current file or directory is changed
     void fileChanged( const QString & );
 
+    //! emitted before and after showing the file dialog
+    void blockEvents( bool );
```
Comment (nyalldawson) [inline src/gui/qgsfilewidget.h]:
```suggestion
    void blockEvents( bool ) SIP_SKIP;
```

This will omit the signal from the PyQt bindings, which is desirable because it's just an internal implementation detail

File: src/gui/qgsexternalresourcewidget.h [hunk 2]
```diff
@@ -147,12 +147,17 @@ class GUI_EXPORT QgsExternalResourceWidget : public QWidget
     //! emitteed as soon as the current document changes
     void valueChanged( const QString & );
 
+  protected:
+    //! Needed to block events when showing a dialog
```
Comment (nyalldawson) [inline src/gui/qgsexternalresourcewidget.h]:
```suggestion
    // Needed to block events when showing a dialog
```

(we usually skip over doxygen for overridden methods)

**Review by nyalldawson — COMMENTED** [review]
Nice fix!

**Comment by bog-dan-ro** [comment]
> Thanks @bog-dan-ro
> 
> Would it be possible to only ignore specific events (to avoid funky effects caused by missed events)?
Done

File: src/gui/qgsfilewidget.h [hunk 3]
```diff
@@ -184,6 +184,9 @@ class GUI_EXPORT QgsFileWidget : public QWidget
     //! emitted as soon as the current file or directory is changed
     void fileChanged( const QString & );
 
+    // emitted before and after showing the file dialog
```
Comment (m-kuhn) [inline src/gui/qgsfilewidget.h]:
```suggestion
    //! emitted before and after showing the file dialog
```
