### PR TITLE
Don't try to render font marker symbols in massive font sizes

### LINKED ISSUE #42270: QGIS crashes on zoom in with wheel closer than 1:1 and font marker in style
**Describe the bug**

For QGIS project containing a layer styled with a font marker, when zooming in closer than 1:1, QGIS CPU usage jumps to 100% and the application crashes after a while.

This is similar to #32489. 

**How to Reproduce**

1. Open QGIS project attached.
2. Zoom in much closer than 1:1 then back to a sensible zoom level several times.
3. QGIS hangs for a while and then crashes

**QGIS and OS versions**

QGIS version | 3.16.4-Hannover | QGIS code revision | 654e76b3cb
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | db_manager; MetaSearch; processing

### PR DESCRIPTION
**Pull request by nyalldawson**
Instead, scale the painter after the font exceeds a certain threshold.
The end result looks the same, but should avoid issues like the
crash described in #42270

Fixes #42270

### CODE REVIEW

File: src/core/symbology/qgsmarkersymbollayer.cpp [hunk 1]
```diff
@@ -3598,6 +3615,8 @@ QRectF QgsFontMarkerSymbolLayer::bounds( QPointF point, QgsSymbolRenderContext &
   {
     chrWidth *= scaledSize / mOrigSize;
   }
+  if ( !qgsDoubleNear( mFontSizeScale, 1.0 ) )
```
Comment (rouault) [inline src/core/symbology/qgsmarkersymbollayer.cpp:3618]: nitpicking: doing this test is probably more expensive than always doing the multiplication

**Review by rouault — APPROVED** [review]

File: src/core/symbology/qgsmarkersymbollayer.cpp (hunk 1 above)
Comment (nyalldawson) [reply src/core/symbology/qgsmarkersymbollayer.cpp]: > nitpicking

That's the best type of picking! Fixed.

**Comment by nyalldawson** [comment]
Unrelated test failure
