### PR TITLE
fix mesh layer relative path

### LINKED ISSUE #46066: 2dm layer saves absolute path when project in relative path mode
### What is the bug or the crash?

When saving a project with 'Save paths' set to 'relative', the paths for 2dm layers are saved as absolute '2DM:/...' paths in the project file.

### Steps to reproduce the issue

Create new project and make sure  'Save paths' is set to 'relative'
Add a 2dm file from a subfolder e.g. ~/qgistest/mesh.2dm
Save the project
Inspect the produced .qgz file with zgrep

> $zgrep mesh.2dm qgistest.qgz
> <layer-tree-layer ...  source="2DM:&quot;/home/kater/qgistest/mesh.2dm&quot;" ...>
> <datasource>2DM:"/home/kater/qgistest/mesh.2dm"</datasource>
> <mesh-dataset-group-tree-item description="/home/kater/qgistest/mesh.2dm" ...>

(The output is shortened)

The nodes will have an absolute path in the 'source' attribute. 

[qgistest.zip](https://github.com/qgis/QGIS/files/7545440/qgistest.zip)

### Versions

QGIS version
3.22.0-Białowieża
QGIS code revision
d9022691f1
Qt version
5.15.2
Python version
3.9.2
GDAL/OGR version
3.2.2
PROJ version
7.2.1
EPSG Registry database version
v10.008 (2020-12-16)
GEOS version
3.9.0-CAPI-1.16.2
SQLite version
3.34.1
PDAL version
2.2.0
PostgreSQL client version
13.4 (Debian 13.4-0+deb11u1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Devuan GNU/Linux 4 (chimaera)

Active Python plugins
DataPlotly
3.7.1
landxml2qgis
0.3.2
quick_map_services
0.19.11.1
crayfish
3.5.3
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99
db_manager
0.1.20
grassprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Possible related bug report https://github.com/qgis/QGIS/issues/28968

### PR DESCRIPTION
**Pull request by vcloarec**
fix #46066

### CODE REVIEW

File: src/core/mesh/qgsmeshlayer.cpp [hunk 1]
```diff
@@ -1503,8 +1503,13 @@ QString QgsMeshLayer::decodedSource( const QString &source, const QString &provi
   QString src( source );
   if ( provider == QLatin1String( "mdal" ) )
   {
-    src = context.pathResolver().readPath( src );
+    QVariantMap uriParts = QgsProviderRegistry::instance()->decodeUri( QStringLiteral( "mdal" ), source );
```
Comment (nyalldawson) [inline src/core/mesh/qgsmeshlayer.cpp:1506]: I'm thinking this should be sufficiently generic to remove the "provider == "mdal" " condition above (ie. If the uriParts contains a "path" value then we always resolve that). That would help avoid the meshlayer version of decodedSource becoming a horrible nightmare of cludges like QgsVectorLayer::decodedSource has become.

Comment (vcloarec) [reply src/core/mesh/qgsmeshlayer.cpp]: Not sure it will help to understand the logic for other provider, for now, only memory mesh provider that will be treated as the MDAL provider.
I don't like sending ALL the logic of treatment of the uri  to the MDAL provider.
But putting the variable `provider` or `mProvider` in `QgsProviderRegistry::instance()->decodeUri()` and then testing if "path" is in `uriParts` should be well generic, like in the last commit?

**Review by nyalldawson — APPROVED** [review]
