### PR TITLE
[processing] replace illegal characters with underscore when splitting vector layer (fix #53856)

### LINKED ISSUE #53856: Split Vector Layer fails if attributes contain a slash
### What is the bug or the crash?

I'm running Vector > Data Management Tools > Split Vector Layer... on a layer showing city council districts for the state of New Mexico. I'm trying to split by city, but one district spans two cities and its "city" field is "Rio Rancho/Corrales". The relevant error in the dialog that pops up is:
```
Creating layer: /home/akkana/Data/votingdistricts/2023/citycouncil/City_Rio Rancho/Corrales.shp
Could not create layer /home/akkana/Data/votingdistricts/2023/citycouncil/City_Rio Rancho/Corrales.shp: Creation of layer failed (OGR error: Failed to create file /home/akkana/Data/votingdistricts/2023/citycouncil/City_Rio Rancho/Corrales.shp: No such file or directory)
```

Of course, / is an illegal character in a filename (at least on Linux/Unix). It would be great if qgis detected this and omitted the slash, or replaced it with some legal character.

I tried fixing this by right-clicking on the layer, opening the attribute table and editing the city to be "Rio Rancho Corrales" for each of the districts in that city. After editing, if I click on them with Identify, it shows no slash, but Split Vector Layers is still using the slash so it still fails. I had to save, quit and restart, after which things worked. (Except that it found a bunch of ring self-intersections that I had to fix, but at least no more slash in filename problems.)

### Steps to reproduce the issue

1. Load a dataset where some of the layer attributes have slashes. (I'll attach a zip of the shapefiles.)
2. Vector > Data Management Tools > Split Vector Layer...
3. Split on the "city" field, choose an output directory, and try to run the splitter.

### Versions

QGIS version
3.28.8-Firenze
QGIS code branch
Release 3.28
Qt version
5.15.10
Python version
3.11.4
Compiled against GDAL/OGR
3.7.0
Running against GDAL/OGR
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.42.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.13.3
OS version
Debian GNU/Linux trixie/sid

Active Python plugins
SRTM-Downloader
3.1.17
quick_map_services
0.19.33
processing
2.12.99
db_manager
0.1.20
grassprovider
2.12.99
sagaprovider
2.12.99
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alexbruy**
## Description

Field values may contain characters which can not be safely used in the file names, as a result Split Vector Layer Processing algorithm fails to create output file. To fix this, algorithm will replace characters `< > : \ / | ? * "` with `_` (underscore) when generating output file name.

Also ignore invalid geometries, as we only want to split vector layer and does not care about geometry validity in this particular case.

Fixes #53856.

### CODE REVIEW

File: src/analysis/processing/qgsalgorithmsplitvectorlayer.cpp [hunk 1]
```diff
@@ -139,13 +139,15 @@ QVariantMap QgsSplitVectorLayerAlgorithm::processAlgorithm( const QVariantMap &p
     }
     else
     {
-      fileName = QStringLiteral( "%1%2.%3" ).arg( baseName ).arg( ( *it ).toString() ).arg( outputFormat );
+      QString value = ( *it ).toString();
+      value.replace( QRegularExpression( "<|>|\\:|\\\\|\\/|\\||\\?|\\*|\"" ), QStringLiteral( "_" ) );
```
Comment (nyalldawson) [inline src/analysis/processing/qgsalgorithmsplitvectorlayer.cpp:143]: Can we use QgsFileUtils::stringToSafeFilename here instead?

Comment (alexbruy) [reply src/analysis/processing/qgsalgorithmsplitvectorlayer.cpp]: Sure, I have updated code.

**Review by nyalldawson — APPROVED** [review]
