### PR TITLE
Ensure that non-EPSG:3857 vector tiles layers can be rendered in the correct place

### LINKED ISSUE #39061: WGS84 vector tiles fail to reproject properly
Since QGIS' vector tiles assume pseudo-mercador CRS, any vector tiles not matching this hard-coded assumption fails. 

For eg, this WGS84 CRS vector tile: https://basemaps.arcgis.com/arcgis/rest/services/OpenStreetMap_GCS_v2/VectorTileServer

### PR DESCRIPTION
**Pull request by nyalldawson**
This fixes the rendering of vector tiles layers which are constructed in any non web Mercator CRS.

It also ensures that vector tiles loaded from an ESRI VectorTileService correctly read and initialise the tile structure, so that these layers will be correctly placed.

(Unfortunately the required information is not recorded in mbtiles packages, so it's necessary to set the correct parameters via
API calls when trying to load non-3857 mbtiles.)

Fixes https://github.com/qgis/QGIS/issues/39061

### CODE REVIEW

**Comment by nirvn** [comment]
Very, very good fix.

File: src/core/vectortile/qgsvectortilestructure.cpp [hunk 1]
```diff
@@ -0,0 +1,90 @@
...
+#include "qgsvectortilestructure.h"
+#include "qgstiles.h"
+#include "qgsvectortileutils.h"
+#include "qgsarcgisrestutils.h"
+
+QgsVectorTileStructure QgsVectorTileStructure::fromWebMercator()
+{
+  QgsVectorTileStructure res;
+  res.setCrs( QgsCoordinateReferenceSystem( QStringLiteral( "EPSG:3857" ) ) );
+  res.setZ0xMin( -20037508.3427892 );
```
Comment (nirvn) [inline src/core/vectortile/qgsvectortilestructure.cpp:25]: Do we have an established convention on setZ0xMin vs setZ0xMinimum?

**Review by nirvn — APPROVED** [review]

File: src/core/vectortile/qgsvectortilestructure.cpp [hunk 2]
```diff
@@ -0,0 +1,90 @@
...
+ *   (at your option) any later version.                                   *
+ *                                                                         *
+ ***************************************************************************/
+
+#include "qgsvectortilestructure.h"
+#include "qgstiles.h"
+#include "qgsvectortileutils.h"
+#include "qgsarcgisrestutils.h"
+
+QgsVectorTileStructure QgsVectorTileStructure::fromWebMercator()
```
[the remark this answers is not in the document]
Comment (wonder-sk) [reply src/core/vectortile/qgsvectortilestructure.cpp:21]: I believe with custom CRS the approach with bounds() is not going to be great. In some countries they have kind of standard tile matrix set for their national CRS, but I doubt it would be the same as the bounds() most of the time (just because of the fact that you want tile matrix boundary to be a square or built by multiple squares). It would be more appropriate to have a collection of "well known tile matrix sets" mainly for countries where there's such agreement (I don't know of any authority for this, but I have seen that MapTiler have a list of such tile matrix sets for some European countries).

File: src/core/vectortile/qgsvectortilestructure.h [hunk 3]
```diff
@@ -0,0 +1,222 @@
...
+#include "qgscoordinatereferencesystem.h"
+
+class QgsTileMatrix;
+
+/**
+ * Encapsulates properties of a vector tile structure, including tile origins and scaling information.
+ * \ingroup core
+ * \since QGIS 3.22.6
+ */
+class CORE_EXPORT QgsVectorTileStructure
```
[the remark this answers is not in the document]
Comment (nyalldawson) [reply src/core/vectortile/qgsvectortilestructure.h:30]: @wonder-sk 

>  think all of it is useful also for raster XYZ tiles and WMTS.

That was my original thought too. But the z0xmin/max etc used for scaling the vector tiles IS vt specific. And that's a large part of this class...

File: src/core/vectortile/qgsvectortilestructure.cpp (hunk 1 above)
Comment (nyalldawson) [reply src/core/vectortile/qgsvectortilestructure.cpp]: You're right, fixed

File: src/core/vectortile/qgsvectortilestructure.h (hunk 3 above)
[the remark this answers is not in the document]
Comment (nyalldawson) [reply src/core/vectortile/qgsvectortilestructure.h]: @wonder-sk 

Ok, I've refactored this to use QgsTileMatrixSet, with a subclass of QgsVectorTileMatrixSet which adds just the vector tile specific bits on top.

[the remark this answers is not in the document]
Comment (nyalldawson) [reply src/core/vectortile/qgsvectortilestructure.h]: @wonder-sk 

To further clarify -- I've taken this as far as I'm able to justify timewise, but there's still some oddness in QgsTileMatrix (outside of this PR, that is). QgsTileMatrix has members for matrixWidth and matrixHeight, which I'd expect to contain the sizes of the matrix at a particular zoom level -- but these are always the root zoom 0 widths/heights (and also aren't used anywhere outside of tests!). Similarly, I'd expect QgsTileMatrix::extent to return the extent of the corresponding zoom level, but again it's always returning zoom level 0's extent.

So we're now closer to proper handling of individual zoom levels, but not quite there yet.

[the remark this answers is not in the document]
Comment (nyalldawson) [reply src/core/vectortile/qgsvectortilestructure.h]: Ping @wonder-sk -- are you happy if I merge the new version?

File: src/core/vectortile/qgsvectortilematrixset.cpp [hunk 4]
```diff
@@ -0,0 +1,104 @@
...
+  bool foundLevel0 = false;
+  double z0Dimension = 0;
+
+  for ( const QVariant &lod : lodList )
+  {
+    const QVariantMap lodMap = lod.toMap();
+    const int level = lodMap.value( QStringLiteral( "level" ) ).toInt();
+    if ( level == 0 )
+    {
+      z0Dimension = lodMap.value( QStringLiteral( "resolution" ) ).toDouble() * 512;
```
Comment (wonder-sk) [inline src/core/vectortile/qgsvectortilematrixset.cpp:74]: Not sure, but maybe if tileInfo.cols (or rows) could be used instead of hardcoded 512?

File: src/core/vectortile/qgsvectortilematrixset.h [hunk 5]
```diff
@@ -0,0 +1,130 @@
...
+     * \note This same structure is utilized in ESRI vtpk archives in the root.json file.
+     */
+    bool fromEsriJson( const QVariantMap &json );
+
+  private:
+
+    double mZ0xMin = 0;
+    double mZ0xMax = 0;
+    double mZ0yMin = 0;
+    double mZ0yMax = 0;
```
Comment (wonder-sk) [inline src/core/vectortile/qgsvectortilematrixset.h:127]: This is where I am confused - why is this necessary to explicitly keep the Z0 rectangle here (rather than accessing extent() from zoom level 0) - is there any difference?

If we need to keep this explicitly, why not use QgsRectangle?

File: src/core/vectortile/qgsvectortilematrixset.cpp (hunk 4 above)
Comment (nyalldawson) [reply src/core/vectortile/qgsvectortilematrixset.cpp:74]: Right -- that looks correct! (All the services I can find have a row/col size of 512 anyway)

File: src/core/vectortile/qgsvectortilematrixset.h (hunk 5 above)
Comment (nyalldawson) [reply src/core/vectortile/qgsvectortilematrixset.h:127]: Right -- I can confirm that these always exactly match the results from tileMatrix(0).extent(). I've dropped them.
