### PR TITLE
Fix sublayers not added to legend after drag and drop

### LINKED ISSUE #56403: WFS sublayer is missing when FeatureType is added from QGIS browser
### What is the bug or the crash?

This happens when:

- the feature type is **drag'n'dropped** from the QGIS browser panel to the layer panel
AND
- "Add layers to group" is **NOT** checked.

grafik

### Steps to reproduce the issue

1. add WFS connection https://xplanservices.krzn.de/viersen/xplansyn-wfs/services/xplansynwfs
2. drag'n'drop FeatureType `xplan:BP_AnpflanzungBindungErhaltung` from browser to layers panel
3. select all sublayers
4. make sure "Add layers to group" is NOT checked
5. click "Add Layers"
6. see error -> only one sublayer of the two selected is added 

### Versions

QGIS version | 3.34.3-Prizren | QGIS code revision | 47373234ac
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.18
GDAL/OGR version | 3.8.3
PROJ version | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.41.1
PDAL version | 2.6.0
PostgreSQL client version | 15.2
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.4
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

@rouault found a workaround in https://github.com/qgis/QGIS/pull/55847/commits/6c7c2418ee948a5d96c98359d3e115f008490455, @elpaso is working on it ref https://github.com/qgis/QGIS/pull/55847#issuecomment-1952139032

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #56403

### CODE REVIEW

**Comment by elpaso** [comment]
CC @rouault

File: src/app/layers/qgsapplayerhandling.cpp [hunk 1]
```diff
@@ -1432,36 +1445,40 @@ T *QgsAppLayerHandling::addLayerPrivate( Qgis::LayerType type, const QString &ur
...
       }
-      result->setName( base );
-      QgsProject::instance()->addMapLayer( result, addToLegend );
+      result.first()->setName( base );
+      QgsProject::instance()->addMapLayer( result.first(), addToLegend );
 
-      QgisApp::instance()->askUserForDatumTransform( result->crs(), QgsProject::instance()->crs(), result );
-      QgsAppLayerHandling::postProcessAddedLayer( result );
+      QgisApp::instance()->askUserForDatumTransform( result.first()->crs(), QgsProject::instance()->crs(), result.first() );
+      QgsAppLayerHandling::postProcessAddedLayer( result.first() );
```
Comment (rouault) [inline src/app/layers/qgsapplayerhandling.cpp:1481]: shouldn't we iterate over all layers instead of just using the first one?

**Review by rouault — APPROVED** [review]
appropriate for backport?

File: src/app/layers/qgsapplayerhandling.cpp (hunk 1 above)
Comment (elpaso) [reply src/app/layers/qgsapplayerhandling.cpp:1481]: I don't think so because in this branch canQuerySublayers is false and QgsMapLayerFactory::createLayer only returns a single layer, `results` will contain at most one single layer.

Comment (rouault) [reply src/app/layers/qgsapplayerhandling.cpp:1481]: ok, fair enough. perhaps add a comment comment to clarify this?

**Comment by elpaso** [comment]
> appropriate for backport?

I would say yes.

File: src/app/layers/qgsapplayerhandling.cpp (hunk 1 above)
Comment (elpaso) [reply src/app/layers/qgsapplayerhandling.cpp:1483]: done

**Comment by rouault** [comment]
I've just tested that the patch of this PR applied on top of https://github.com/qgis/QGIS/pull/55847 with the hack of https://github.com/qgis/QGIS/pull/55847/commits/cc04bba7481266db058ad130f6cbd9470f573026 reverted solves the issue of https://github.com/qgis/QGIS/pull/55847#issuecomment-1899851375
