### PR TITLE
[3d] Fix online terrain ignoring project coordinate transform context

### LINKED ISSUE #40390: 3D scene's reprojected online terrain fails to take project transformation settings into account
**Describe the bug**
The online terrain type fails to take project transformation settings into account when reprojecting DEM tiles. As a result, users can end up with badly re projected tiles, creating elevation gaps (or an total absence of elevation data in worse case scenarios):
image

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This fixes #40390.

### CODE REVIEW

File: src/core/qgsgdalutils.h [hunk 1]
```diff
@@ -66,7 +66,7 @@ class CORE_EXPORT QgsGdalUtils
      * \returns TRUE on success
      * \since QGIS 3.8
      */
-    static bool resampleSingleBandRaster( GDALDatasetH hSrcDS, GDALDatasetH hDstDS, GDALResampleAlg resampleAlg );
+    static bool resampleSingleBandRaster( GDALDatasetH hSrcDS, GDALDatasetH hDstDS, GDALResampleAlg resampleAlg, const char *pszCoordinateOperation = nullptr );
```
Comment (nyalldawson) [inline src/core/qgsgdalutils.h:69]: I would make the operation non optional. I think there's other places calling this method which are also incorrectly ignoring the transform context...

Comment (nirvn) [reply src/core/qgsgdalutils.h:69]: The only other place was in the postgresql provider, and it's only for doing a non reprojected resampling.

Nevertheless, I think you are right :)

**Review by nyalldawson — APPROVED** [review]
