### PR TITLE
Fix missing GPS time when identifying point cloud

### LINKED ISSUE #44168: LiDAR EPT file GPSTime always 0 with identify tool in QGIS 3.20.0 RC
When an LAZ/EPT file is loaded into QGIS 3.20.0 for Windows , the identify tool always reports GPSTime as 0, even when the underlying GPSTime for the point is valid ( non-zero)

**How to Reproduce**

1) Add an LAZ file or remote EPT file to QGIS
2) Click on the identify tool
3) Zoom in until individual points are visible
4) Click on any point.
5) View the results in the Identify results Panel.
Same result occurred with data from:
 https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_VA_Fairfax_County_2018/ept.json
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_WA_MtBaker_2015_LAS_2017/ept.json
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_NC_Sandy_L12_2014_LAS_2015/ept.json

**QGIS and OS versions**

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.20.0-Odense | QGIS code revision | decaadbb31
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.0
PROJ version | 8.0.1
EPSG Registry database version | v10.018 (2021-04-02)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins | arearatioBufferByPercentageCalcAreaCalcOnField-maincartography_toolscreate_layer_from_selected_featuresdataexplorerDataPlotlydzetsakaEasyTemplatePrintexcel_syncgeocat_exportgeometric_attributesGroupStatshabitat_managerHTML_Generator-mainJSONEater-masterKP_findlayer2kmzlayertilesmapcanvaslftoolslocalmaxfilterMagicWand-masterMagneticDeclinationmesmamgrsnumericalDigitizeOSMDownloaderpointsamplingtoolpoint_selectionprocessing_fusionqfieldsyncqgisgbifapiQuickOSMquick_map_servicesQWEPP3relation_batchinsertrivergisSemiAutomaticClassificationPluginshapefile_encoding_fixershapetoolsslyr_communitySpreadsheetLayerstuflowusgs_stream_mapperVectorFieldLayerManagerVectorMCDAvolume_calculation_toolweissflaechenkartierungdb_managerMetaSearchprocessing

</body></html>
**Additional context**

### PR DESCRIPTION
**Pull request by wonder-sk**
Handling of GPS time was somehow omitted when EPT was in LAZ format - it worked with BIN format though.
Added LAZ-based EPT to unit testing suite to ensure it works for both.

Fixes #44168

### CODE REVIEW

File: tests/src/providers/testqgseptprovider.cpp [hunk 1]
```diff
@@ -355,9 +366,10 @@ void TestQgsEptProvider::testIdentify()
       point[ QStringLiteral( "UserData" ) ] =  "17" ;
       point[ QStringLiteral( "X" ) ] =  "498066.27" ;
       point[ QStringLiteral( "Y" ) ] =  "7050995.06" ;
-      point[ QStringLiteral( "Z" ) ] =  "74.60" ;
+      point[ QStringLiteral( "Z" ) ] =  74.6 ;
```
Comment (PeterPetrik) [inline tests/src/providers/testqgseptprovider.cpp:369]: looks strange that is it not string like X a Z in test above

**Review by PeterPetrik — APPROVED** [review]

File: tests/src/providers/testqgseptprovider.cpp (hunk 1 above)
Comment (wonder-sk) [reply tests/src/providers/testqgseptprovider.cpp]: With string representation, the tests were failing with LAZ because of this:
```
   Actual   (identifiedPoints[0][k]): QVariant(double,74.60000000000001)
   Expected (expected[0][k])        : QVariant(QString,74.60)
```
Will try to change them all other expected values to numbers as well.

@nyalldawson test for GpsTime is few lines above - I just made the test to be run for both BIN and LAZ encoding of EPT (previously it was only run for BIN encoded EPT)

**Review by nyalldawson — APPROVED** [review]
