### PR TITLE
[rat] Handle new bool and datetime types 

### LINKED ISSUE #64797: Raster Attribute Table for S-102 does not display correctly
### What is the bug or the crash?

The latest version of QGIS is not displaying the raster attribute table (RAT) from S-102 correctly.  Specifically, it appears that incorrect data is ending up in the columns.  Fields like "sourceSurveyID" are displaying boolean values but should be strings.

RATs were added to S-102 in version 2.2.  S-102 3.0 test files can be found [here](https://noaa-ocs-nationalbathymetry-pds.s3.amazonaws.com/index.html#Test-and-Evaluation/Navigation_Test_and_Evaluation/S102V30/).  I have confirmed the data appears correct in these files using HDF5 readers and also using GDAL.

New RAT data types were added into GDAL, and specifically datetime and boolean data types are being used for the S-102 data.  I suspect, although I'm not sure how to confirm, that something with reading the data in its new type is not working as expected. 

### Steps to reproduce the issue

Open a test file from the provided link in QGIS and view the RAT.
Open the same file with GDAL and view the RAT.
Compare the available data.

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.44.5-Solothurn</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/5c593399236">5c593399236</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.13</td></tr><tr><td>Python version</td><td>3.12.12</td></tr><tr><td>GDAL version</td><td>3.12.0 — <i>Chicoutimi</i></td></tr><tr><td>PROJ version</td><td>9.7.0</td></tr><tr><td>EPSG Registry database version</td><td>v12.022 (2025-08-30)</td></tr><tr><td>GEOS version</td><td>3.13.1-CAPI-1.19.2</td></tr><tr><td>SQLite version</td><td>3.50.4</td></tr><tr><td>PDAL version</td><td>2.9.0</td></tr><tr><td>PostgreSQL client version</td><td>17.3</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.3.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Windows 11 Version 2009</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>crayfish</td><td>4.0.0</td></tr><tr><td>cruisetools</td><td>2.3</td></tr><tr><td>firstaid</td><td>3.2.1</td></tr><tr><td>loadthemall</td><td>3.4</td></tr><tr><td>pluginbuilder3</td><td>3.2.1</td></tr><tr><td>plugin_reloader</td><td>0.18</td></tr><tr><td>profiletool</td><td>4.3.3</td></tr><tr><td>qduckdb</td><td>2.2.6</td></tr><tr><td>quick_map_services</td><td>1.1.0</td></tr><tr><td>Serval</td><td>3.32.0</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Added in GDAL 3.12

Fix https://github.com/qgis/QGIS/issues/64797

Note for reviewers: I added a bunch of unrelated static_casts<int> to silence the infamous size_t -> int warning

### CODE REVIEW

File: src/core/providers/gdal/qgsgdalprovider.cpp [hunk 1]
```diff
@@ -3589,28 +3609,30 @@ bool QgsGdalProvider::readNativeAttributeTable( QString *errorMessage )
...
+                  rowData.push_back( GDALRATGetValueAsInt( hRat, rowIdx, gdalFieldIdx ) );
+                  break;
+                }
+                case QMetaType::Type::Double:
+                {
+                  rowData.push_back( GDALRATGetValueAsDouble( hRat, rowIdx, gdalFieldIdx ) );
+                  break;
+                }
+                default:
+                  rowData.push_back( GDALRATGetValueAsString( hRat, rowIdx, gdalFieldIdx ) );
```
Comment (rouault) [inline src/core/providers/gdal/qgsgdalprovider.cpp:3633]: I assume this means that reading boolean and datetime as strings works fine given the Qt data type is set to the appropriate type before?

File: tests/src/python/test_qgsrasterattributetable.py [hunk 2]
```diff
@@ -1490,6 +1490,108 @@ def testFileStorage(self):
         )
         self.assertEqual(rat.data(), data_rows)
 
+    def testS102Rat(self):
```
Comment (rouault) [inline tests/src/python/test_qgsrasterattributetable.py:1497]: you likely need to conditionalize this test to GDAL >= 3.12

File: src/core/providers/gdal/qgsgdalprovider.cpp (hunk 1 above)
Comment (elpaso) [reply src/core/providers/gdal/qgsgdalprovider.cpp:3633]: yes, the type conversion happens when the row is added to the RAT. 
I thought about calling GetValueAsDateTime but IMHO it's much easier to let QDateTime handle the conversion from a string than using GDALRATDateTime.

File: tests/src/python/test_qgsrasterattributetable.py (hunk 2 above)
Comment (elpaso) [reply tests/src/python/test_qgsrasterattributetable.py:1497]: Thanks for noticing. I forgot to copy/paste the skip instruction from my local test file.

**Review by rouault — APPROVED** [review]
