### PR TITLE
Fix aggregate function returns incorrect results 

### LINKED ISSUE #58221: Legend expression issue
### What is the bug or the crash?

In QGIS versions > 3.30, using @symbol_label as a filter within aggregate function does not result in unique aggregate result values. 

E.g. 
concat(@symbol_label, ' | ', round(aggregate('my_layer','sum', $area, site_no = 3 AND habitat=@symbol_label), 1) || ' m2') gives a different result in QGIS version 3.30 as it does in version 3.38. In earlier version, a unique area value is calculated for each habitat type, but in later versions the area value of the top habitat is repeated for each habitat. 

### Steps to reproduce the issue

concat(@symbol_label, ' | ', round(aggregate('my_layer','sum', $area, site_no = 3 AND habitat=@symbol_label), 1) || ' m2')

### Versions

3.30 versus 3.38

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### LINKED ISSUE #58315: Bug in @Symbol_label using with aggregate function
### What is the bug or the crash?

When using @symbol_layer within an Aggregate function, there is no filtering on the symbol in question.

Layer with 4 categories
Knipsel1

Atlas layout legenda
Knipsel2

Expresion on legenda item
Knipsel3

### Steps to reproduce the issue

Load a layer and simulate in categories.
Create an atlas map and use the layer in the legend.
Enter the expression on the existing layer.
I also use the LTR version (latest), it still works after the update.

### Versions

QGIS-versie
3.38.1-Grenoble
QGIS code revisie
3d4177af
Qt versie
5.15.13
Python versie
3.12.4
GDAL/OGR versie
3.9.1
PROJ versie
9.4.0
EPSG-register databaseversie
v11.004 (2024-02-24)
GEOS versie
3.12.2-CAPI-1.18.2
SQLite versie
3.45.1
PDAL versie
2.6.3
PostgreSQL client versie
unknown
SpatiaLite versie
5.1.0
QWT versie
6.2.0
QScintilla2 versie
2.14.1
OS versie
Windows 11 Version 2009

Actieve Python plug-ins
processing
2.12.99
bfvw_tools
1.3
changeDataSource
3.1
export_to_sql_server
0.4
lizmap
4.3.20
pdokservicesplugin
5.1.1
qconsolidate3
0.2.0
SelectWithin
0.4
qgis2web
3.22.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

After the latest update my expression no longer works as before. Only the name and number of the first symbol are calculated and displayed for all subsequent symbols.

### PR DESCRIPTION
**Pull request by nyalldawson**
When the aggregate uses variables, we need to ensure that the
cache key correctly considers the current value of ALL those
variables. Otherwise we'll return incorrect results when
an expression is re-evaluated after changing the variable
value for the context.

Fixes use of aggregate function with @symbol_label in legends.

Fixes https://github.com/qgis/QGIS/issues/58221

(Possibly also fixes https://github.com/qgis/QGIS/issues/58315, but untested)

### CODE REVIEW

File: src/core/qgsexpressioncontext.cpp [hunk 1]
```diff
@@ -769,3 +769,45 @@ QgsFeedback *QgsExpressionContext::feedback() const
...
+
+QString QgsExpressionContext::uniqueHash( bool &ok, const QSet<QString> &variables ) const
+{
+  QString hash;
+  ok = true;
+  const QString delimiter( QStringLiteral( "||~~||" ) );
+
+  if ( hasFeature() )
+  {
+    hash.append( QString::number( feature().id() ) + delimiter + QString::number( qHash( feature() ) ) + delimiter );
```
Comment (troopa81) [inline src/core/qgsexpressioncontext.cpp:781]: `id` is already included by qhash, why repeat it?

File: src/core/qgsexpressioncontext.cpp [hunk 2]
```diff
@@ -769,3 +769,45 @@ QgsFeedback *QgsExpressionContext::feedback() const
...
+  if ( sortedVars.empty() )
+    sortedVars = variableNames();
+  std::sort( sortedVars.begin(), sortedVars.end() );
+
+  for ( const QString &variableName : std::as_const( sortedVars ) )
+  {
+    const QVariant value = variable( variableName );
+    if ( QgsVariantUtils::isNull( value ) )
+    {
+      hash.append( delimiter );
```
Comment (troopa81) [inline src/core/qgsexpressioncontext.cpp:794]: Shall we not include `variableName in the hash? 2 different variable with the same value could have the same hash (with a different set of given variables but still)

File: src/core/qgsexpressioncontext.cpp [hunk 3]
```diff
@@ -769,3 +769,45 @@ QgsFeedback *QgsExpressionContext::feedback() const
 {
   return mFeedback;
 }
+
+QString QgsExpressionContext::uniqueHash( bool &ok, const QSet<QString> &variables ) const
```
Comment (troopa81) [inline src/core/qgsexpressioncontext.cpp:773]: Why not add a boolean on whether or not we should include the feature part (or a flags on what we should include feature, variables...) so we could use it for the static part also ?

And why not build and return a uint like qHash, and later on convert it to string?

Comment (nyalldawson) [reply src/core/qgsexpressioncontext.cpp:773]: @troopa81 

> Why not add a boolean on whether or not we should include the feature part (or a flags on what we should include feature, variables...) so we could use it for the static part also ?

static part doesn't need **anything** from the context, because it's never going to change within the scope of one set of executions against that context.

> And why not build and return a uint like qHash, and later on convert it to string?

There's risk of collisions, and limited (no?) benefit to doing things that way. qHash can use ints for strings because all the usage of qHash still ends up calling the equality operator on the original values, so a hash collision isn't a bug. Here we'd end up returning completely wrong values. That's also why I'm explicitly NOT relying on the QgsFeature hash alone, but including the feature id as an explicit part of the key.

File: src/core/qgsexpressioncontext.cpp (hunk 1 above)
Comment (nyalldawson) [reply src/core/qgsexpressioncontext.cpp:781]: See comment below for the explanation

File: src/core/qgsexpressioncontext.cpp (hunk 2 above)
Comment (nyalldawson) [reply src/core/qgsexpressioncontext.cpp:794]: Yes, good point! I'll fix

**Review by troopa81 — APPROVED** [review]
