### PR TITLE
Cache only joined attributes without colliding names. Fix #45169

### LINKED ISSUE #45169: Join layer without custom prefix shifts the fields and cache
### What is the bug or the crash?

If one layer is joined to another and no prefix is selected (by selecting custom field name prefix and then just blanking the box), the resulting join layer column are all one to the right of the one they should be.
Similar to #26652, which seems to be resolved but only if join layer is not cached.

### Steps to reproduce the issue

1. Open layers from [test.gpkg.zip](https://github.com/qgis/QGIS/files/7201418/test.gpkg.zip)
2. Open properties of Layer "pts1" and add Join
3. Join Layer: pts2; Join field: id; Target field: field_id
4. Accept and open attributes table -> Everithing ok!
5. Reopn join properties
6. Activate "Custom field_name prefix" and delete prefix text
7. Accept and open attributes table -> Valuse and Fields are shifted. (values of not displayed "fid" in "type" column, values of "type" are in "owner" column and "owner" values are missing)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.21.0-Master | QGIS code revision | 5ea353ba22
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.8.11
GDAL/OGR version | 3.3.1
PROJ version | 7.2.1
EPSG Registry database version | v10.008 (2020-12-16)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.36.0
PostgreSQL client version | 13.3
SpatiaLite version | 4.3.0a
QWT version | 6.2.0
QScintilla2 version | 2.13.0
OS version | openSUSE Tumbleweed
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins | plugin_reloaderquick_map_servicesshlocatordocument_management_systemQgisModelBakerfirstaidprocessingsagaprovidergrassproviderMetaSearchdb_manager

</body></html>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by domi4484**
Cache only joined attributes without colliding names.

### CODE REVIEW

File: src/core/vector/qgsvectorlayerjoinbuffer.cpp [hunk 1]
```diff
@@ -172,9 +172,27 @@ void QgsVectorLayerJoinBuffer::cacheJoinLayer( QgsVectorLayerJoinInfo &joinInfo
...
-        QgsAttributes attrs2 = attrs;
-        attrs2.remove( joinFieldIndex );  // skip the join field to avoid double field names (fields often have the same name)
-        joinInfo.cachedAttributes.insert( key, attrs2 );
+        QgsAttributes attributesCache;
+        for ( int i = 0; i < attrs.size(); i++ )
+        {
+          if ( i == joinFieldIndex )
+            continue;
+
+          if ( !joinInfo.prefix().isNull() ) // Default prefix 'layerName_' used
```
Comment (nyalldawson) [inline src/core/vector/qgsvectorlayerjoinbuffer.cpp:181]: isn't there a possible clash even when using layerName_fieldname? I think it'd be safest to also check for clashes even when there's no prefix

Comment (domi4484) [reply src/core/vector/qgsvectorlayerjoinbuffer.cpp]: Yes it was theoretically possible, I have changed it know.

**Review by nyalldawson — APPROVED** [review]
