### PR TITLE
Fix crash when exporting layout

### LINKED ISSUE #29798: QGIS crahses when exporting a template
Author Name: **Christophe Poupon** (Christophe Poupon)
Original Redmine Issue: [21983](https://issues.qgis.org/issues/21983)
Affected QGIS version: 3.6.2
Redmine category:map_composer/printing

---
QGIS crash when i export a layout create from a template. 
First i create a new layout in layout manager from my template. 
Then, without changing anything,i export the layout to pdf or pgn -> crashed

As alternative, i select and copy all item that i paste in a new blank layout.

Crash ID: 3ed09f0b9da4a6fd9d2c76522e1b24cdcc418bd5

Stack Trace

QGraphicsItem::pos :
QgsLayoutMultiFrame::handlePageChange :
QMetaObject::activate :
QgsLayoutPageCollection::reflow :
QgsLayout::refresh :
QgsVertexEditorModel::flags :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.6.2-Noosa
QGIS code revision: 656500e0c4
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

---

- [QGIS model_A3_paysage_cartouche quart vertical droite.qpt](https://issues.qgis.org/attachments/download/14884/QGIS%20model_A3_paysage_cartouche%20quart%20vertical%20droite.qpt) (Christophe Poupon)

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #29798

### CODE REVIEW

File: src/core/layout/qgslayoutmultiframe.cpp [hunk 1]
```diff
@@ -385,20 +385,23 @@ void QgsLayoutMultiFrame::handlePageChange()
     }
   }
 
-  //page number of the last item
-  QgsLayoutFrame *lastFrame = mFrameItems.last();
-  int lastItemPage = mLayout->pageCollection()->predictPageNumberForPoint( lastFrame->pos() );
-
-  for ( int i = lastItemPage + 1; i < mLayout->pageCollection()->pageCount(); ++i )
+  if ( mFrameItems.count( ) )
```
Comment (nyalldawson) [inline src/core/layout/qgslayoutmultiframe.cpp]: !mFrameItems.empty()

Comment (elpaso) [inline src/core/layout/qgslayoutmultiframe.cpp]:
```suggestion
  if ( !mFrameItems.empty() )
```

**Review by nyalldawson — APPROVED** [review]
