### PR TITLE
Fix circular string digitizing tool

### LINKED ISSUE #51936: Circular String tool does not work as expected
### What is the bug or the crash?

Closely related to #38493, but this bug is about the circular string digitizing tools and not the circle digitizing tool.

It is one of the consequences of #25167: when the layer crs != map crs, the circular string tool does not work as expected.

curve_tool

PR #51931 addresses the problem for the Circle tools.

### Steps to reproduce the issue

- Create a new project
- (Optionaly add a basemap)
- Set the CRS to EPSG:3857
- Create a new Temporary Scratch CompoundCurve Layer, with EPSG:4326
- Edit the curve layer
- Display the "Shape Digitizing Toolbar"
- Add a new feature
- Chose "Digitizing with curve" (digitizing toolbar), or "Circular string by radius" (shape digitizing toolbar)
- Draw the curve

### Versions

QGIS version
3.29.0-Master
QGIS code revision
994da50a64
Qt version
5.15.3
Python version
3.9.5
Compiled against GDAL/OGR
3.7.0dev-986b841325
Running against GDAL/OGR
3.7.0dev-a828b2b5a9
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by YoannQDQ**
Fixes #51936
Partially adresses #25167

## Description

Circular strings do not play well with different crs between map and layer and the resulting shape can be funky.

This PR completes #51931 

- Fixes `QgsMapToolShapeCircularStringRadius` "Circular string by radius" 

circular_by_radius

- Fixes the Curve mode of the `QgsMapToolCapture` (used to create new Line/Polygon features, add rings, reshape features...) 

menu

capture_tool

### CODE REVIEW

File: src/app/maptools/qgsmaptoolshapecircularstringabstract.cpp [hunk 1]
```diff
@@ -191,7 +191,20 @@ void QgsMapToolShapeCircularStringAbstract::addCurveToParentTool()
...
-  mParentTool->addCurve( c );
+
+  // Check whether to draw the circle as a polygon or a circular string
+  const QgsCoordinateReferenceSystem layerCrs = mParentTool->layer()->crs();
+  const QgsCoordinateReferenceSystem mapCrs = mParentTool->canvas()->mapSettings().destinationCrs();
+  const bool drawAsPolygon = layerCrs != mapCrs;
+  if ( drawAsPolygon )
+  {
+    std::unique_ptr<QgsLineString> ls( c->curveToLine( ) );
+    mParentTool->addCurve( ls.release() );
```
Comment (rouault) [inline src/app/maptools/qgsmaptoolshapecircularstringabstract.cpp:202]: this will leak ``c``

File: src/gui/qgsmaptoolcapture.cpp [hunk 2]
```diff
@@ -806,20 +806,28 @@ int QgsMapToolCapture::addCurve( QgsCurve *c )
...
     mCaptureCurve.removeCurve( 0 );
 
-  // we set the extendPrevious option to true to avoid creating compound curves with many 2 vertex linestrings -- instead we prefer
-  // to extend linestring curves so that they continue the previous linestring wherever possible...
-  mCaptureCurve.addCurve( c, !mStartNewCurve );
+  // Transform back to layer CRS in case map CRS and layer CRS are different
+  const QgsCoordinateTransform ct = mCanvas->mapSettings().layerTransform( layer() );
+  if ( ct.isValid() && !ct.isShortCircuited() )
+  {
+    QgsLineString *segmented = c->curveToLine();
```
Comment (rouault) [inline src/gui/qgsmaptoolcapture.cpp:818]: this will leak c

**Review by rouault — CHANGES_REQUESTED** [review]
memleaks

File: src/app/maptools/qgsmaptoolshapecircularstringabstract.cpp (hunk 1 above)
Comment (YoannQDQ) [reply src/app/maptools/qgsmaptoolshapecircularstringabstract.cpp:202]: You're right. I fixed it.

File: src/gui/qgsmaptoolcapture.cpp (hunk 2 above)
Comment (YoannQDQ) [reply src/gui/qgsmaptoolcapture.cpp:818]: You're right. I fixed it.

**Comment by rouault** [comment]
LGTM regrading the memleak fixes but not an expert in that area

File: src/app/maptools/qgsmaptoolshapecircularstringabstract.cpp [hunk 3]
```diff
@@ -191,7 +191,21 @@ void QgsMapToolShapeCircularStringAbstract::addCurveToParentTool()
 {
   QgsCircularString *c = new QgsCircularString();
   c->setPoints( mPoints );
-  mParentTool->addCurve( c );
+
+  // Check whether to draw the circle as a polygon or a circular string
+  const QgsCoordinateReferenceSystem layerCrs = mParentTool->layer()->crs();
```
Comment (nyalldawson) [inline src/app/maptools/qgsmaptoolshapecircularstringabstract.cpp:196]: Note for myself -- double check if layer() can be nullptr here before merging

Comment (nyalldawson) [reply src/app/maptools/qgsmaptoolshapecircularstringabstract.cpp:195]: @YoannQDQ this is indeed the case -- layer() may be nullptr in some circumstances. Eg QgsMapToolProfileCurve::layer(). In this case the map canvas crs should be used.

Comment (YoannQDQ) [reply src/app/maptools/qgsmaptoolshapecircularstringabstract.cpp]: Ok

File: src/app/maptools/qgsmaptoolshapecircularstringabstract.cpp [hunk 4]
```diff
@@ -189,7 +190,27 @@ void QgsMapToolShapeCircularStringAbstract::addCurveToParentTool()
...
+
+  // Check whether to draw the circle as a polygon or a circular string
+  bool drawAsPolygon = false;
+
+  if ( mParentTool->layer() )
+  {
+    const QgsCoordinateReferenceSystem layerCrs = mParentTool->layer()->crs();
+    const QgsCoordinateReferenceSystem mapCrs = mParentTool->canvas()->mapSettings().destinationCrs();
+    drawAsPolygon = layerCrs != mapCrs;
+  }
```
Comment (nyalldawson) [inline src/app/maptools/qgsmaptoolshapecircularstringabstract.cpp:202]:
```suggestion
  if ( QgsMapLayer* layer = mParentTool->layer() )
  {
    const QgsCoordinateReferenceSystem layerCrs = layer->crs();
    const QgsCoordinateReferenceSystem mapCrs = mParentTool->canvas()->mapSettings().destinationCrs();
    drawAsPolygon = layerCrs != mapCrs;
  }
```

**Review by nyalldawson — APPROVED** [review]

File: src/app/maptools/qgsmaptoolshapecircularstringabstract.cpp [hunk 5]
```diff
@@ -189,7 +190,27 @@ void QgsMapToolShapeCircularStringAbstract::addCurveToParentTool()
 {
   QgsCircularString *c = new QgsCircularString();
   c->setPoints( mPoints );
-  mParentTool->addCurve( c );
+
+  // Check whether to draw the circle as a polygon or a circular string
+  bool drawAsPolygon = false;
+
+  if ( QgsMapLayer* layer = mParentTool->layer() )
```
Comment (nyalldawson) [inline src/app/maptools/qgsmaptoolshapecircularstringabstract.cpp:197]:
```suggestion
  if ( QgsMapLayer *layer = mParentTool->layer() )
```
