### PR TITLE
Fix crash due to style cache issue in QT<5.12.4. Fixes #39693 #39725 #39615

### LINKED ISSUE #39693: QGIS crash showing raster symbology in layer properties
**Describe the bug**
QGIS crash showing raster symbology in layer properties

**How to Reproduce**

1. add a raster into the project
2. Double click on the added layer to open layer properties
3. Click on Symbology => crash

Not F7 works correctly

**QGIS and OS versions**

QGIS version | 3.16.0-Hannover | QGIS code revision | 43b64b13f3
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 13.0 (Ubuntu 13.0-1.pgdg18.04+1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.5 LTS | This copy of QGIS writes debugging output.
Active python plugins | plugin_reloader; IPyConsole; remotedebug; Qgis2threejs; db_manager; processing; MetaSearch

**Additional context**

### PR DESCRIPTION
**Pull request by luipir**
Fix crash due to style cache issue in QT<5.12.4. Fixes #39693 #39725 #39615
No tests available :/

workaround to  QT bug https://bugreports.qt.io/browse/QTBUG-69204

Partially sponsored by QGIS Spanish User Group qgis.es

### CODE REVIEW

File: src/gui/qgscollapsiblegroupbox.cpp [hunk 1]
```diff
@@ -383,6 +383,11 @@ void QgsCollapsibleGroupBoxBasic::updateStyle()
     ss += QLatin1String( "  background-color: rgba(0,0,0,0)" );
   }
   ss += '}';
+#if QT_VERSION < QT_VERSION_CHECK(5, 12, 4)
```
[the remark this answers is not in the document]
Comment (luipir) [reply src/gui/qgscollapsiblegroupbox.cpp:386]: right! changing it

**Comment by nirvn** [comment]
@luipir , other than @rouault 's suggestion, fix looks good. Just in time.

I'd reduce the comment to a single line, something like
  // Fix crash on old Qt versions, see https://github.com/qgis/QGIS/issues/39693

**Comment by DelazJ** [comment]
Thanks @luipir for all the efforts.

**Comment by luipir** [comment]
some squash to clean commits

**Comment by luipir** [comment]
@rouault @DelazJ @nirvn let me know if I can merge or any modification more

File: src/gui/qgscollapsiblegroupbox.h [hunk 2]
```diff
@@ -130,6 +130,7 @@ class GUI_EXPORT QgsCollapsibleGroupBoxBasic : public QGroupBox
     void checkToggled( bool ckd );
     void checkClicked( bool ckd );
     void toggleCollapsed();
+    void setStyleSheet( const QString &style );
```
Comment (nyalldawson) [inline src/gui/qgscollapsiblegroupbox.h:133]: Just add docs, don't expand the missing doc list!

**Comment by nyalldawson** [comment]
I'm a little confused how this fix works -- QWidget::setStyleSheet isn't virtual, so how does this intercept all attempts to set the group box style?

**Comment by luipir** [comment]
> I'm a little confused how this fix works -- QWidget::setStyleSheet isn't virtual, so how does this intercept all attempts to set the group box style?

is it done calling parent setStyleSheet? or do you mean to move the fix to upper levels?

File: src/gui/qgscollapsiblegroupbox.h (hunk 2 above)
Comment (luipir) [reply src/gui/qgscollapsiblegroupbox.h:133]: I followed the same as the other overloaded slots because the documentation I suppose is based on base class documentation. BTW I'll add doc.

**Comment by rouault** [comment]
> I'm a little confused how this fix works -- QWidget::setStyleSheet isn't virtual, so how does this intercept all attempts to set the group box style?

this won't intercept all attempts, just those done by this class. Perhaps the method should be internalSetStyleSheet() to avoid any confusion ?

**Comment by luipir** [comment]
> > I'm a little confused how this fix works -- QWidget::setStyleSheet isn't virtual, so how does this intercept all attempts to set the group box style?
> 
> this won't intercept all attempts, just those done by this class. Perhaps the method should be internalSetStyleSheet() to avoid any confusion ?

well.. @nyalldawson I'm confused too about why the crash happen always in the same class and does not affect the other call to setStyleSheet (175) all over the qgis code.

**Comment by luipir** [comment]
> > I'm a little confused how this fix works -- QWidget::setStyleSheet isn't virtual, so how does this intercept all attempts to set the group box style?
> 
> this won't intercept all attempts, just those done by this class. Perhaps the method should be internalSetStyleSheet() to avoid any confusion ?

because the crash happen only with this class, I prefered to leave the same method name to avoid to call setStyleSheet  falling again in a crash.

File: src/gui/qgscollapsiblegroupbox.h (hunk 2 above)
Comment (luipir) [reply src/gui/qgscollapsiblegroupbox.h:138]: added

**Comment by nyalldawson** [comment]
Should we also backport to 3.10 to be extra safe?

**Comment by nirvn** [comment]
Sure.

**Review by nirvn — APPROVED** [review]
Let's get this into 3.16 so we can ship a crash free version asap.

Code looks good. The documentation could be improved but we can do that in a follow up PR.

**Comment by msevilla00** [comment]
I updated my installation through  `deb [arch=amd64] https://qgis.org/ubuntugis-nightly-release bionic main` and I'm still having this issue :-(

Here it is my configuration:

About QGIS - 64 Bit — About_645

**Comment by nirvn** [comment]
@msevilla00 , that build is too old.

**Comment by PedroVenancio** [comment]
> About QGIS - 64 Bit — About_645

@msevilla00 last commit included in your build is from 5 days ago.

**Comment by msevilla00** [comment]
Ok, thanks, I did apt update & upgrade and changed... I thought included the latest fix.

I'll try with the other repos. 

Cheers
