### PR TITLE
OGR provider: only enable journal_mode = wal when editing. requires GDAL >= 3.4.2 (fixes #23991)

### LINKED ISSUE #23991: Opening a Vector Geopackage in QGIS alters its file even when no changes are done by user
Author Name: **Johannes Kroeger** (Johannes Kroeger)
Original Redmine Issue: [16076](https://issues.qgis.org/issues/16076)
Affected QGIS version: 3.6.0
Redmine category:unknown

---
Opening a Vector Geopackage in QGIS alters its file. Simply loading the file is enough, you do not even need to load any actual data (visibly to the user).

```
$ wget http://www.geopackage.org/data/geonames_belgium.gpkg
2017-01-13 17:58:54 (1.28 MB/s) - ‘geonames_belgium.gpkg’ saved [11594752/11594752]

$ cp geonames_belgium.gpkg geonames_belgium.gpkg_original

$ md5sum geonames_belgium.gpkg*

4dacf68ae3a5f2c2fb55a35d062dc580  geonames_belgium.gpkg
4dacf68ae3a5f2c2fb55a35d062dc580  geonames_belgium.gpkg_original

$ ogrinfo -so geonames_belgium.gpkg
INFO: Open of `geonames_belgium.gpkg'
      using driver `GPKG' successful.
1: administrative (3D Measured Point)
2: hydrography (3D Measured Point)
3: leisure (3D Measured Point)
4: places (3D Measured Point)
5: roads (3D Measured Point)
6: spots (3D Measured Point)
7: terrain (3D Measured Point)
8: undersea (3D Measured Point)
9: vegetation (3D Measured Point)

$ md5sum geonames_belgium.gpkg*
4dacf68ae3a5f2c2fb55a35d062dc580  geonames_belgium.gpkg
4dacf68ae3a5f2c2fb55a35d062dc580  geonames_belgium.gpkg_original

hannes@hilmar:/mnt/earx/geodata$ qgis geonames_belgium.gpkg
Warning: loading of qgis translation failed [/usr/share/qgis/i18n//qgis_en_US]
Warning: loading of qt translation failed [/usr/share/qt/translations/qt_en_US]
Warning: QCss::Parser - Failed to load file  "/style.qss"

```

Here the layer chooser dialog appeared on which I clicked Cancel and quit QGIS.

```
$ md5sum geonames_belgium.gpkg*
99fad69efe058b1d308088b96d60e915  geonames_belgium.gpkg
4dacf68ae3a5f2c2fb55a35d062dc580  geonames_belgium.gpkg_original

``` 

QGIS changes only some stuff in the header:

```
$ hexdump -C geonames_belgium.gpkg > geonames_belgium.gpkg.hex
$ hexdump -C geonames_belgium.gpkg_original > geonames_belgium.gpkg_original.hex
$ diff geonames_belgium.gpkg*.hex
2c2
< 00000010  04 00 01 01 00 40 20 20  00 00 00 56 00 00 2c 3b  |.....@  ...V..,;|
---
> 00000010  04 00 01 01 00 40 20 20  00 00 00 54 00 00 2c 3b  |.....@  ...T..,;|
6,7c6,7
< 00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 56  |...............V|
< 00000060  00 2e 05 42 05 00 00 00  26 03 42 00 00 00 2c 3b  |...B....&.B...,;|
---
> 00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 54  |...............T|
> 00000060  00 2d e6 06 05 00 00 00  26 03 42 00 00 00 2c 3b  |.-......&.B...,;|

```

I could not reproduce this bug with the Raster GPKG https://portal.opengeospatial.org/files/63156 but with any other Vector GPKG I tried.

Please ensure that merely opening a file does never alter it.

### PR DESCRIPTION
**Pull request by rouault**
This requires the NOLOCK open option of the GPKG driver added per https://github.com/OSGeo/gdal/pull/5207
For earlier GDAL version, previous behaviour is kept.

With GDAL >= 3.4.2, when creating a QgsOgrProvider object, we first open
it in update mode without forcing WAL, to get the appropriate
capabilities, close it, and re-open it in read-only mode with the
NOLOCK=YES open option. This option will only be honoured if the file
wasn't already in WAL mode.
When editing a layer, the file is re-opened in update mode and with
enabling WAL to avoid blocking between readers and writers.
When closing a file, journal mode is attempted to be reset to DELETE as
before.

I've verified that test_provider_ogr_gpkg.py and test_provider_ogr.py
pass locally with GDAL master + OSGeo/gdal#5207

Could be worth backporting to LTR, but perhaps would require some additional testing from others

### CODE REVIEW

**Comment by nirvn** [comment]
I'd love to see this backported. Maybe after it lives on 3.24 for a month or so.

**Comment by gioman** [comment]
> I'd love to see this backported. Maybe after it lives on 3.24 for a month or so.

Agree, especially if this means that the GPKG open in read only mode will stop to be marked as changed on the file system.

File: src/core/providers/ogr/qgsogrprovider.cpp [hunk 1]
```diff
@@ -3652,6 +3671,9 @@ void QgsOgrProvider::open( OpenMode mode )
 
 void QgsOgrProvider::close()
 {
+  if ( mWriteAccess && mForceRecomputeExtent )
+    extent();
```
Comment (nyalldawson) [inline src/core/providers/ogr/qgsogrprovider.cpp:3675]: Can you explain this addition?

Comment (rouault) [reply src/core/providers/ogr/qgsogrprovider.cpp:3675]: without it, a failure in testGeopackageExtentUpdate() would appear with the new behaviour when doing
```
        # Test moving a geometry that touches the bbox
        self.assertTrue(vl.startEditing())
        self.assertTrue(vl.changeGeometry(1, QgsGeometry.fromWkt('Point (0.5 0)')))
        self.assertTrue(vl.commitChanges())
        reference = QgsGeometry.fromRect(QgsRectangle(0.5, 0.0, 1.0, 1.0))
        provider_extent = QgsGeometry.fromRect(vl.extent())
        self.assertTrue(QgsGeometry.compare(provider_extent.asPolygon()[0], reference.asPolygon()[0], 0.00001),
                        provider_extent.asPolygon()[0])
```
The reason is that vl.changeGeometry() sets the mForceRecomputeExtent flag, but that one was only taken into extent() to actually trigger the "RECOMPUTE EXTENT ON" command.  With GDAL < 3.4.2, commitChanges() wouldn't close the file, which was in update mode, and thus extent() could complete succesfully. With GDAL >= 3.4.2, commitChanges() causes a close() and reopen(ReadOnly), and thus in close() we need to make sure to force actual extent recomputation.

**Comment by kannes** [comment]
This would fix #23991, thank you so much in advance.

**Review by nyalldawson — APPROVED** [review]

**Comment by florisvdh** [comment]
Thank you SO very much for handling this! :+1: :tada:  Looking forward to the next releases.

FYI @paleolimbot

**Comment by gdt** [comment]
When a file is opened as NOLOCK=yes, does that really mean no locking?   Isn't it then the case that reading from the geopackage is unsound if some other program has it open?

I think an underlying issue is likely a difference of opinion as to the nature of geopackage files.   qgis seems to view them as private data files within the qgis world, as opposed to databases that can be accessed by others, or at least that's how it seems reading the discussions.   sqlite is an odd case in databases, as it can be both private storage for a program (perhaps the more common case) as well as functioning like a regular database.

**Comment by rouault** [comment]
> When a file is opened as NOLOCK=yes, does that really mean no locking?

yes

> Isn't it then the case that reading from the geopackage is unsound if some other program has it open?

see bottom of comment of https://github.com/OSGeo/gdal/pull/5207#issuecomment-1026432051

**Comment by agiudiceandrea** [comment]
@rouault tested with QGIS 3.24.0 and GDAL 3.4.2 on Windows:
- it seems not possible to set NOLOCK=YES as default for GPKG files dragged and dropped in QGIS
- the possibility to set the NOLOCK=YES for GPKG files is only available if the GPKG file is added using the Add Vector Layer window
Is this behavior expected? If yes, could it be improved in order to let the user set the NOLOCK=YES option as default for dragged and dropped GPKG files?

**Comment by rouault** [comment]
>    it seems not possible to set NOLOCK=YES as default for GPKG files dragged and dropped in QGIS.    the possibility to set the NOLOCK=YES for GPKG files is only available if the GPKG file is added using the Add Vector Layer window.    Is this behavior expected? If yes, could it be improved in order to let the user set the NOLOCK=YES option as default for dragged and dropped GPKG files?

The NOLOCK=YES open option is mostly an internal detail. Users shouldn't need to set it generally. The provider is supposed to do the right thing, and set it automatically when the layer is in read-only mode, whatever how it was added to the project

**Comment by agiudiceandrea** [comment]
> The provider is supposed to do the right thing, and set it automatically when the layer is in read-only mode, whatever how it was added to the project

It seems to me it is not the case. Adding a GPKG layer (not opened by any other process) with drag and drop or using the Add Vector Layer window and leaving the NOLOCK option as <default>, then the whal and shm files are created and the modify date of the gpkg file is changed even if the layer in QGIS is not edited.
Did I miss something or I misunderstand the point of this PR?

**Comment by rouault** [comment]
Has your QGIS version being rebuilt against GDAL 3.4.2 headers (and not just using it at runtime) ?

**Comment by agiudiceandrea** [comment]
Hi @rduivenvoorde I've tested this patch with QGIS 3.24.1 (qgis-3.24.1-2 from OSGeo4W on Windows 10) built against GDAL 3.4.2 and using GDAL 3.4.2 runtime DLL.

The behaviour seems correct to me when a GPKG file is dragged and dropped in QGIS or added to a map using the Browser panel (in such cases the whal and shm files are not created and the modify date of the gpkg file is not changed).

If the GPKG file is added to a map using the Vector Layer window, then the behaviour is always the same (whal and shm files are not created and the modify date of the gpkg file is not changed) however the user sets the NOLOCK option (Yes, No, <Default>).
Is this behaviour expected? If yes, what's the point to expose the NOLOCK option to the user in QGIS?

**Comment by rduivenvoorde** [comment]
@agiudiceandrea I was mentioned in your comment, but you probably meant @rouault ?
Or do you want me to double check something...?

**Comment by agiudiceandrea** [comment]
> I was mentioned in your comment

Please, excuse me! I meant to tag Even Rouault.

**Comment by rouault** [comment]
> If yes, what's the point to expose the NOLOCK option to the user in QGIS?

it shouldn't be exposed  (it is currently, as it is done automatically since QGIS auto-discovers open options from GDAL driver metadata). Fixed per https://github.com/qgis/QGIS/pull/47992

**Comment by agiudiceandrea** [comment]
It seems to me the issue reported at https://github.com/qgis/QGIS/issues/48003 could be related to this PR.

**Comment by agiudiceandrea** [comment]
Hi @rouault, it seems to me the issues reported at https://github.com/qgis/QGIS/issues/48003 and https://github.com/qgis/QGIS/issues/48024 could be related to this PR.

**Comment by agiudiceandrea** [comment]
Since this PR causes some regressions (https://github.com/qgis/QGIS/issues/48003 not yet fixed and https://github.com/qgis/QGIS/issues/48024 fixed in a not yet released GDAL 3.4.x version), would it be worth to revert its backport (https://github.com/qgis/QGIS/pull/47301 and cf0af098cfee69013391230a66caafe72993503d) at least in the 3.22 LTR branch to prevent the occurrence of such regressions in the upcoming QGIS LTR 3.22.6?

**Comment by rouault** [comment]
> Since this PR causes some regressions (#48003 not yet fixed and #48024 fixed in a not yet released GDAL 3.4.x version), would it be worth to revert its backport (#47301 and [cf0af09](https://github.com/qgis/QGIS/commit/cf0af098cfee69013391230a66caafe72993503d)) at least in the 3.22 LTR branch to prevent the occurrence of such regressions in the upcoming QGIS LTR 3.22.6?

hopefully https://github.com/qgis/QGIS/pull/48119 should fix network issues, but only compile-tested here

**Comment by agiudiceandrea** [comment]
> hopefully #48119 should fix network issues, but only compile-tested here

Thanks a lot again! I will try the MingW64 build and report back ASAP.

**Comment by agiudiceandrea** [comment]
I can confirm that https://github.com/qgis/QGIS/pull/48119 fixes https://github.com/qgis/QGIS/issues/48003 on Windows 10 (QGIS 3.25.0-Master MingW64 build)

**Comment by agiudiceandrea** [comment]
Hi @rouault, it seems to me that also the issue reported at https://github.com/qgis/QGIS/issues/48154 ("Adding additional layers to GPKG does not load them correctly") may be related to this PR.

**Comment by rouault** [comment]
> Hi @rouault, it seems to me that also the issue reported at #48154 ("Adding additional layers to GPKG does not load them correctly") may be related to this PR.

fix in https://github.com/qgis/QGIS/pull/48157

**Comment by agiudiceandrea** [comment]
Hi @rouault, I think the issue https://github.com/qgis/QGIS/issues/48671, which is similar to https://github.com/qgis/QGIS/issues/48154, could be related to this PR.

**Comment by agiudiceandrea** [comment]
Please have a look at the issue report https://github.com/qgis/QGIS/issues/60023: I guess it is related with this PR and / or https://github.com/OSGeo/gdal/pull/5207.

**Comment by rouault** [comment]
> Hi @rouault, I think the issue #48671, which is similar to #48154, could be related to this PR.

I'm afraid that whenever I'm tyring to fix a use case related to GeoPackage and locking, I'm breaking another one.
Safest setting would be turn on write-ahead log all the time, but that breaks things related to backups that rely on not modifying files, and also doesn't work great with files on network shares, and that creates side-car files that are obviously an inconvenience. 
People should just use shapefiles maybe :-) ?
