### PR TITLE
Better handling of PDAL errors

### LINKED ISSUE #50078: loading empty point cloud results in endless task
### What is the bug or the crash?

When loading an empty point cloud, qgis tries to index it using untwine. An upstream bug in untwine causes the indexing task to hang https://github.com/hobuinc/untwine/issues/128

We could avoid this if we skip the pointless indexing attempt when loading an empty file.

### Steps to reproduce the issue

Load an empty point cloud file that is not indexed, ie not ept nor copc.
This is not hard to come by using the new exporting functionality for point clouds with a filter

### Versions

Master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by uclaros**
## Description
This PR handles better some pdal errors.
- handles json parsing errors when reading the pointcloud's metadata
- handles empty pointclouds to avoid hitting upstream untwine issue (see #50078)
- appends pdal errors to `QgsPdalProvider` so that broken files cannot be added by drag and drop
- avoids adding broken and/or empty files when exporting pointclouds to pdal formats

Fix #50078

### CODE REVIEW

File: src/app/qgisapp.cpp [hunk 1]
```diff
@@ -8434,12 +8434,17 @@ QString QgisApp::saveAsPointCloudLayer( QgsPointCloudLayer *pclayer )
       QgsMapLayer *ml = exp->takeExportedLayer();
```
Comment (nyalldawson) [inline src/app/qgisapp.cpp:8434]: Would be nicer here if ml was a unique_ptr

**Review by nyalldawson — APPROVED** [review]
