### PR TITLE
Fix hang when picking point/extent for algorithm from model designer dialog

### LINKED ISSUE #59063: QGIS Crashes when picking a point on the map while Model designer window is open
### What is the bug or the crash?

While designing a model using the Model designer, i had to check if the model is running correctly. The model i was building had an input where the user have to pick the point in the map canvas. But while the model designer window is open, ran the model after saving. Clicked on the pick the point option and then the entire QGIS freezes and crashes.
I'm using Ubuntu 22.04.5 LTS

### Steps to reproduce the issue

1. Open QGIS and start a new project.
2. Go to the Model Designer to create a new model.
3. In the model designer, add an input parameter of type Point. (This allows the user to select a point on the map canvas.)
4. Save the model.
5. Run the model directly from the Model Designer window (without closing the designer).
6. When prompted, click on the “Pick Point” option in the dialog that appears to allow the user to pick a point on the map canvas.

### Versions

QGIS Version: 3.38.3-Grenoble
OS: Ubuntu 22.04.5 LTS

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nyalldawson**
When a processing widget is shown in a modal dialog, we can't offer the actions to draw the point/extent on the canvas. So hide in these contexts.

Fixes #59063

### CODE REVIEW

File: src/gui/processing/qgsprocessingwidgetwrapperimpl.cpp [hunk 1]
```diff
@@ -4126,6 +4135,19 @@ void QgsProcessingPointPanel::setValue( const QgsPointXY &point, const QgsCoordi
   updateRubberBand();
 }
 
+void QgsProcessingPointPanel::showEvent( QShowEvent * )
+{
+  if ( mFirstShow )
+  {
+    // we don't support select on canvas if the dialog is modal
+    if ( QWidget *parentWindow = window() )
```
Comment (rouault) [inline src/gui/processing/qgsprocessingwidgetwrapperimpl.cpp:4143]: I assume we do this in showEvent() since we can't get that information in the QgsProcessingPointPanel constructor? Probably the modality of the window might be changed atter QgsProcessingPointPanel has been created?

**Review by rouault — APPROVED** [review]

File: src/gui/processing/qgsprocessingwidgetwrapperimpl.cpp (hunk 1 above)
Comment (nyalldawson) [reply src/gui/processing/qgsprocessingwidgetwrapperimpl.cpp:4143]: That's correct -- it's not until after the dialog has been completely constructed, when a later call to "exec" actually causes the modal mode to kick in
