### PR TITLE
Fix #62337 - Pressing F1 do not open API page

### LINKED ISSUE #62337: Pressing F1 does not open API page matching the hovered/selected text
### What is the bug or the crash?

Quoting #58962:
> When pressing F1, open the API page matching
>
> * selected text if any OR
> * word at the mouse position (if enabled in settings, see below) OR
> * word at the text cursor position

I'm unable to confirm this **on Windows**. Selecting or hovering a text in the Python console prompt or editor, and then **pressing** "F1" tries to use the topmost document set in the "Options --> System --> Documentation paths" widget. Neither Qt nor PyQGIS docs.
However, right-clicking and selecting "Contextual Help (F1)" DOES open the correct page in target document.

### Steps to reproduce the issue

1. Open Plugins --> Python console menu
2. Write `QgsProcessing` or `QDialog` in either the command prompt or the Python text editor
3. Select the text and press F1
4. The browser or Development Tools dialog will open the user manual (or whatever document is listed first in the "Options --> System --> Documentation paths" widget. Instead, it should have opened the Qt or PyQGIS API docs.
The Settings --> Options --> Python --> Contextual Help (F1) values don't seem to have any effects.
5. Now right-click the text and select "Contextual help". The Qt or PyQGIS docs opens correctly, either in browser or as embedded in QGIS

Tested unsuccessfully on Windows 10, on both 3.42 and master. 
Tested successfully on macOS, with 3.42

### Versions

<table width='100%' align='center'><tr><td>Version de QGIS</td><td>3.43.0-Master</td></tr><tr><td>Révision du code</td><td><a href="https://github.com/qgis/QGIS/commit/6c62b930b02">6c62b930b02</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Bibliothèques</b></td></tr><tr><td>Version de Qt</td><td>5.15.13</td></tr><tr><td>Version de Python</td><td>3.12.10</td></tr><tr><td>GDAL version</td><td>3.12.0dev-75a784eecf</td></tr><tr><td>Version de Proj</td><td>9.6.0</td></tr><tr><td>Version de la base de données du registre EPSG</td><td>v12.004 (2025-03-02)</td></tr><tr><td>Version de GEOS</td><td>3.13.1-CAPI-1.19.2</td></tr><tr><td>Version de SQLite</td><td>3.46.1</td></tr><tr><td>Version de PDAL</td><td>2.8.3</td></tr><tr><td>Version du client PostgreSQL</td><td>17.3</td></tr><tr><td>Version de SpatiaLite</td><td>5.1.0</td></td></tr><tr><td>Version de QWT</td><td>6.3.0</td></tr><tr><td>Version de QScintilla2</td><td>2.14.1</td></tr><tr><td>Version de l'OS</td><td>Windows 10 Version 2009</td></tr><tr><td colspan="2"><i>Cette copie de QGIS dispose d'une sortie de débogage.</i></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Extensions Python actives</b></td></tr><tr><td>lizmap</td><td>4.5.0</td></tr><tr><td>plugin_reloader</td><td>0.17</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### PR DESCRIPTION
**Pull request by YoannQDQ**
- Fix #62337 
 
## Description
Override the global F1 shortcut while QgsCodeEditor has keyboard focus

### CODE REVIEW

File: src/gui/codeeditors/qgscodeeditor.cpp [hunk 1]
```diff
@@ -359,6 +359,23 @@ void QgsCodeEditor::contextMenuEvent( QContextMenuEvent *event )
   }
 }
 
+bool QgsCodeEditor::event( QEvent *event )
+{
+  if ( event->type() == QEvent::ShortcutOverride )
+  {
+    if ( QKeyEvent *keyEvent = dynamic_cast<QKeyEvent *>( event ) )
+    {
+      if ( keyEvent->key() == Qt::Key_F1 )
```
Comment (nyalldawson) [inline src/gui/codeeditors/qgscodeeditor.cpp]: Does this work? Might be safer than hardcoding F1 here:

```suggestion
      if ( keyEvent->matches( QKeySequence::HelpContents ) )
```

Comment (YoannQDQ) [reply src/gui/codeeditors/qgscodeeditor.cpp]: Yes, it would work. It would translate as `Cmd+?` on MacOS though, and the hardcoded F1 shortcut should also be replaced in the editors context menu.

Should we proceed with it?

**Review by nyalldawson — APPROVED** [review]
