### PR TITLE
PG raster: fix wrong wkb data type conversion

### LINKED ISSUE #36689: Loading PostGIS raster with QGIS 3.12.3 crashes
**Describe the bug**

QGIS crashes when loading PostGIS raster layer.  This same exercise works fine in QGIS 3.10.6
FWIW I'm running PostgreSQL 13 beta1 so might be related. 

I'm going to do some more tests to make sure my newer PG is not the culprit and it's not a GDAL bug

**How to Reproduce**
 
I loaded data from here - http://biogeo.ucdavis.edu/data/worldclim/v2.1/base/wc2.1_10m_prec.zip
Using command

raster2pgsql -s 4326 -I -C -M prec/*.tif -F -t 256x256 ch12.prec | psql

**QGIS and OS versions**

Get below error
Crash ID: 8db542d910c169105d910e7e9ec58abf67aed639

Stack Trace

memcpy_repmovs memcpy.asm:114
GDALCopyWords64 :
MEMRasterBand::IRasterIO :
GDALRasterBand::RasterIO :
GDALRasterIO :
QgsPostgresRasterProvider::readBlock qgspostgresrasterprovider.cpp:455
QgsRasterDataProvider::block qgsrasterdataprovider.cpp:201
QgsSingleBandGrayRenderer::block qgssinglebandgrayrenderer.cpp:91
QgsBrightnessContrastFilter::block qgsbrightnesscontrastfilter.cpp:118
QgsHueSaturationFilter::block qgshuesaturationfilter.cpp:123
QgsRasterResampleFilter::block qgsrasterresamplefilter.cpp:162
QgsRasterProjector::block qgsrasterprojector.cpp:885
QgsRasterIterator::readNextRasterPartInternal qgsrasteriterator.cpp:130
QgsRasterDrawer::draw qgsrasterdrawer.cpp:60
QgsRasterLayerRenderer::render qgsrasterlayerrenderer.cpp:272
QgsMapRendererParallelJob::renderLayerStatic qgsmaprendererparalleljob.cpp:353
QtConcurrent::MapKernel::iterator,QtConcurrent::FunctionWrapper1 >::runIteration qtconcurrentmapkernel.h:69
QtConcurrent::MapKernel::iterator,QgsImageOperation::ProcessBlockUsingPixelOperation >::runIterations qtconcurrentmapkernel.h:78
QtConcurrent::IterateKernel::iterator,void>::forThreadFunction qtconcurrentiteratekernel.h:256
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.12.3-Bucure?ti
QGIS code revision: 8234261527
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**Additional context**

### PR DESCRIPTION
**Pull request by elpaso**
Fix #36689

### CODE REVIEW

File: src/providers/postgres/raster/qgspostgresrasterprovider.cpp [hunk 1]
```diff
@@ -310,15 +310,15 @@ bool QgsPostgresRasterProvider::readBlock( int bandNo, const QgsRectangle &viewE
...
+          QgsMessageLog::logMessage( tr( "Cannot convert identified value to int" ), QStringLiteral( "PostGIS" ), Qgis::Warning );
           return false;
         }
         std::memcpy( data, &_int, sizeof( int ) );
         break;
       }
       case Qgis::DataType::Int32:
       {
-        const long _long { val.toInt( &ok ) };
+        const long _long { val.toLong( &ok ) };
```
Comment (rouault) [inline src/providers/postgres/raster/qgspostgresrasterprovider.cpp:321]: seeing this "_long" identifier, I believe it is not a good idea. https://en.cppreference.com/w/cpp/language/identifiers mentions "identifiers that begin with an underscore are reserved in the global namespace".

Comment (elpaso) [reply src/providers/postgres/raster/qgspostgresrasterprovider.cpp:321]: ok, I'll fix it in separate PR
