### PR TITLE
Set project as dirty when editing symbols through layers panel (fixes 55623)

### LINKED ISSUE #55623: Changing symbology using Layers panel doesn't trigger project dirty status
### What is the bug or the crash?

Changing a layer's symbology using the legend in the layer browser panel doesn't mark the project as having changed. Therefore the project save dialog isn't triggered when quitting which can cause lost work.

### Steps to reproduce the issue

1. Add a vector layer to a project (tested with spatialite and PostGIS).
2. Set the symbology to categorized and categorize the layer based on an attribute.
3. Make sure project is saved.
4. Change symbology of one of the categories using the layer browser preview
image
5. Note that the project name doesn't have the "changed" asterisk, and when closing it does not prompt to save.

### Versions

QGIS version
3.34.1-Prizren
QGIS code revision
133927424d
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.8.1
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JuhoErvasti**
## Description

Fixes #55623, where project dirty status isn't set when changing the symbology of categorized or graduated vector layers' individual range/category symbols through the layers panel (by double- clicking the symbol). I also noticed that setting a symbol node as visible / not visible didn't mark the project as dirty and a fix for that is included.

prgif

### CODE REVIEW

**Comment by rouault** [comment]
@JuhoErvasti Thanks for your contribution. May I suggest you to put a more informative pull request title than just "Fix XXXX". It makes it hard with just that for potential reviewers to decide if the pull request is in an area of the software they have expertise to review

**Comment by JuhoErvasti** [comment]
@rouault Oh yes, I overlooked that. Thank you for the suggestion, I've changed the title.

File: src/core/layertree/qgslayertreemodellegendnode.cpp [hunk 1]
```diff
@@ -635,6 +635,8 @@ bool QgsSymbolLegendNode::setData( const QVariant &value, int role )
 
   vlayer->renderer()->checkLegendSymbolItem( mItem.ruleKey(), value == Qt::Checked );
 
+  QgsProject::instance()->setDirty( true );
```
Comment (nyalldawson) [inline src/core/layertree/qgslayertreemodellegendnode.cpp:638]: We should never reference QgsProject::instance() in new core code. 
```suggestion
  if ( QgsProject* project = vlayer->project() )
     project->setDirty( true );
```

Comment (JuhoErvasti) [reply src/core/layertree/qgslayertreemodellegendnode.cpp]: Right, I've commited the suggestion and will keep that in mind!

**Review by nyalldawson — APPROVED** [review]

File: src/core/layertree/qgslayertreemodellegendnode.cpp [hunk 2]
```diff
@@ -635,6 +635,9 @@ bool QgsSymbolLegendNode::setData( const QVariant &value, int role )
 
   vlayer->renderer()->checkLegendSymbolItem( mItem.ruleKey(), value == Qt::Checked );
 
+  if ( QgsProject* project = vlayer->project() )
```
Comment (nyalldawson) [inline src/core/layertree/qgslayertreemodellegendnode.cpp:638]:
```suggestion
  if ( QgsProject *project = vlayer->project() )
```

**Comment by JuhoErvasti** [comment]
Hi, I've fixed the style (yet again). Apologies for the many mistakes here, I've set up the pre-commit hook now in case I make other PRs in the future.
