### PR TITLE
Prefer using copc index file for processing if it exist

### LINKED ISSUE #53486: Use COPC files instead of LAS files in Processing if they are present
### What is the bug or the crash?

It is more a feature or a conceptual issue than a bug.

If you use tools like _Point cloud conversion - Export to raster_ (also with using triangulation) when you choose las/laz point cloud layer from project (from layers panel) algorithm run only single thread.
I can understand it, multi-thread approach is probably optimised to run on COPC because of internal structure of data.

But in the case of using las/laz formats, the background COPC is always created by QGIS. 
Unexperienced user can think that for those processing tools are automatically used COPC from background, but in this case it is not true, because input is still las/laz, that mean single core processing.

I can understand the core of this issue, las/laz can be modified in project e.g. own attribute filters, own definition of CRS and it is natural to use them like input. But on the other side, it is unintended loss of performance and resources, especially when COPC already exist.

I dont know an optimal solution, maybe some textual warning in the processing tool? Or some temporal ‘side file’ for COPC with same parameters as are set in QGIS project and use of COPC?

But anyway, big thanks, I really look forward for using QGIS in lidar workflows.

### Steps to reproduce the issue

- Add som las/laz to QGIS
- Use tool like _Point cloud conversion - Export to raster_
- Select lidar layer from project => single thread
- Select same COPC from drive => multi thread

### Versions

QGIS version
3.31.0-Master
QGIS code revision
8e1a12b921
Qt version
5.15.3
Python version
3.9.5
Compiled against GDAL/OGR
3.8.0dev-818e536b10
Running against GDAL/OGR
3.8.0dev-931a57a19c
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

This copy of QGIS writes debugging output.

Active Python plugins
changeDataSource
3.1
FreehandRasterGeoreferencer
0.8.3
HCMGIS
23.2.1
latlontools
3.6.9
nominatim
1.4.5
profiletool
4.2.5
rvt-qgis
0.9.6
wbt_for_qgis
1.0.9
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JanCaha**
## Description

This loads **copc** index file as **PointCloudLayer** for processing instead of original **PointCloudLayer** (could be las or laz etc.). This should make processing faster. 

Fixes #53486

### CODE REVIEW

File: src/analysis/processing/pdal/qgspdalalgorithmbase.cpp [hunk 1]
```diff
@@ -288,4 +289,37 @@ QVariantMap QgsPdalAlgorithmBase::processAlgorithm( const QVariantMap &parameter
   return outputs;
 }
 
+QgsPointCloudLayer *QgsPdalAlgorithmBase::parameterAsPointCloudLayer( const QVariantMap &parameters, const QString &name, QgsProcessingContext &context, QgsProcessing::LayerOptionsFlags flags ) const
+{
+  QgsPointCloudLayer *layer = QgsProcessingParameters::parameterAsPointCloudLayer( parameterDefinition( name ), parameters, context, flags );
+
+  if ( !layer )
```
Comment (wonder-sk) [inline src/analysis/processing/pdal/qgspdalalgorithmbase.cpp:296]: I guess we should check for layer->dataProvider() not being null as well

File: src/analysis/processing/pdal/qgspdalalgorithmbase.cpp [hunk 2]
```diff
@@ -288,4 +289,37 @@ QVariantMap QgsPdalAlgorithmBase::processAlgorithm( const QVariantMap &parameter
...
+    return nullptr;
+
+  if ( layer->dataProvider()->name() == QStringLiteral( "copc" ) )
+  {
+    return layer;
+  }
+
+  const QString copcFileName = QgsPdalAlgorithmBase::copcIndexFile( layer->source() );
```
Comment (wonder-sk) [inline src/analysis/processing/pdal/qgspdalalgorithmbase.cpp:304]: How does it work with remote sources (going through http/https) ? I guess we could just use the remote URL as it is and not try to modify it, to avoid trying some non-sense file names...  (see e.g. QgsCopcPointCloudIndex::load() how it differentiates local/remote files)

File: src/analysis/processing/pdal/qgspdalalgorithmbase.cpp [hunk 3]
```diff
@@ -288,4 +289,37 @@ QVariantMap QgsPdalAlgorithmBase::processAlgorithm( const QVariantMap &parameter
...
+  const QFileInfo fiCopcFile( copcFileName );
+
+  if ( fiCopcFile.exists() )
```
Comment (wonder-sk) [inline src/analysis/processing/pdal/qgspdalalgorithmbase.cpp:307]: micro-optimization: there is QFileInfo::exists( filename ) static function, which should be faster

File: src/analysis/processing/pdal/qgspdalalgorithmbase.cpp (hunk 2 above)
Comment (JanCaha) [reply src/analysis/processing/pdal/qgspdalalgorithmbase.cpp:314]: update

**Review by wonder-sk — APPROVED** [review]
