### PR TITLE
Fix #51543 and make big forms more fluid by reducing calls to updateFieldDependencies

### LINKED ISSUE #51543: Bug or new behaviour on default fields values on QGIS 3.28.X
### What is the bug or the crash?

Default values are called on every field update instead of only at the opening of the form even if the update default is not checked :

QGEP_rp_from_to_fields_demo

image

### Steps to reproduce the issue

1. Create a layer with some attributes
2.  Set a default value base on $geometry or $z value for one of the values
3. Create a feature with this default value used
4. Edit the default value
5. Edit another field

-> The default value for the first field is reset to default value

Expected : updated value is still present instead of default.

### Versions

QGIS 3.28.X

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Parent issue :
https://github.com/QGEP/QGEP/issues/779

[qgep.zip](https://github.com/QGEP/QGEP/files/10478562/qgep.zip) qgis project used

(demo-data)
https://github.com/QGEP/datamodel/releases/download/1.5.6-1/qgep_1.5.6-1_structure_and_demo_data.backup

### PR DESCRIPTION
**Pull request by domi4484**
As of the current implementation when creating a new feature the attribute form behaves as "Always apply default values" checkbox was activated for all default values. After this pr the checkbox will be respected even when creating new features. 

1. Update default values only during setting the feature (or always if "Always apply default values" checkbox is checked)

2. updateFieldDependencies only when resetting the form. This should make working with big forms more fluid as it spares a lot of loops trough all fields. Small downside for an edge case: if the dependencies are changed (for example default value expression on children layer) when a form is open, that form will not reflect the changes until reopened.

### CODE REVIEW

**Comment by ponceta** [comment]
@domi4484 will this be backported to QGIS 3.28? This is a prio1 on our side, otherwise there's a no go on QGIS 3.28.

**Comment by andreasneumann** [comment]
> @domi4484 will this be backported to QGIS 3.28? This is a prio1 on our side, otherwise there's a no go on QGIS 3.28.

I agree - it would be really important to get such form improvements into 3.28.

But it will require lots of testing by users. Form code is a bit fragile ..

**Comment by domi4484** [comment]
> But it will require lots of testing by users. Form code is a bit fragile ..

This would be very welcome and almost mandatory for such kind of changes.
But I still have to look at the failing tests before

**Comment by domi4484** [comment]
@ponceta @andreasneumann from my point of view this pr is ready. If you could do some additional manual tests it would be very appreciated!

**Comment by andreasneumann** [comment]
@domi4484 - this is still in a separate PR and not yet in master - right? I can do some tests tonight.

**Comment by domi4484** [comment]
@andreasneumann yes it is not merged yet

**Comment by andreasneumann** [comment]
@domi4484 - I tested this PR.

I can confirm that the forms feel a lot "snappier" when the forms are big and have a lot of default values with "Apply on update". Good Work.

I can't tell for sure that there are no side effects but so far I haven't found any problems.

It would be great if another person that has complex forms could test as well. Otherwise I am definitely interested to see this land in master and backported to the LTR version.

**Comment by andreasneumann** [comment]
@ponceta - do you have a chance to test this? I would really like to see this land in master, and then after quarantine in an upcoming 3.28 release.

For us, it makes a HUGE difference in our complex forms. Before it was very slow - now instant.

**Comment by ponceta** [comment]
I never build a custom QGIS with a PR yet but I do agree with Andreas, this is a great improvement.

File: src/gui/qgsattributeform.cpp [hunk 1]
```diff
@@ -557,7 +555,11 @@ void QgsAttributeForm::updateValuesDependenciesDefaultValues( const int originId
     QgsEditorWidgetWrapper *eww = qobject_cast<QgsEditorWidgetWrapper *>( ww );
     if ( eww )
     {
-      //do not update when when mMode is not AddFeatureMode and it's not applyOnUpdate
+      // Update only on form opening (except when applyOnUpdate is activated)
+      if ( mValuesInitialized && !eww->field().defaultValueDefinition().applyOnUpdate() )
+        continue;
+
+      // Update only when mMode is AddFeatureMode (except when applyOnUpdate is activated)
```
Comment (signedav) [inline src/gui/qgsattributeform.cpp:562]: Why those are two if conditions and not just one? For the readability?

**Review by elpaso — APPROVED** [review]

File: src/gui/qgsattributeform.cpp (hunk 1 above)
Comment (domi4484) [reply src/gui/qgsattributeform.cpp:562]: Yes just for readability

**Comment by domi4484** [comment]
@signedav can you add the label for automatic backport? I don't have permissions for that

**Comment by ponceta** [comment]
Thank you a lot, that's a huge thing for us, tried today on QGIS 3.28.4-2 and it's working as expected!

**Comment by andreasneumann** [comment]
@ponceta - thank you for the feedback. No troubles or side-effects were observed?

For me it is the same - quite a good improvement!

**Comment by ponceta** [comment]
Not yet at least! ;)

**Comment by spacerat1** [comment]
Hi,
is there a possibility to bring back the behaviour of #51543 (maybe as option 'Update fields only on creating new features') ?
I found the 'bug' very convenient. I have many forms where the user gets suggestions depending on most common use cases.  For example: the user creates a "cable" -> the field for 'status' is set to 'new', but he can change it to 'existing'. (Just to iilustrate, there are many other fields)
With the last update, this field is not updating anymore. 
So now i need to fill all fields either manually, or check the 'Always apply default values', but run the risk of  losing all my 'manual changed data' if i refresh parts of the attribute table.

So it would be very convenient for me, to have the behaviour of 'Always apply default values' while creating new features, but let the data untouched while refreshing the attribute table.
(just like the 'bug' worked, but as an option)

**Comment by peterantkowiak** [comment]
Hi!
I have a similar issue as @spacerat1. I have developed drill-down forms for quick field work where the most probable default value is inserted into a field by running an expression on inputs further up in the form. 
For this to work, I want the default value to be applied only once when creating the feature so that it is possible to record values differing from default and not delete all my data everytime I edit the entry afterwards.
This behavior worked beautifully with QGIS 3.28 / QField 2.6 until some update in March or April. With QGIS 3.34.1 / QField 3.0.7, expressions for defaults don't work at all unless I check the "apply defaults on update" box, which in turn resets all my recorded data to default when going back and editing a feature.

So I agree, an "apply defaults only when inserting feature" option would be highly appreciated.

**Comment by signedav** [comment]
@peterankowiak and @spacerat1 I'm not sure if I understand your requirement. What you wish is the "Apply default value on update" behavior (live update in the form) on creating features, but not on changing values on existing features? 

There is a clear bug #54446 (maybe introduced with this PR but not sure) that in the attribute table the values are updated with "Apply default value on update" even when no value changed (no update is performed). Maybe you would already have the needed behavior when this is fixed?

**Comment by peterantkowiak** [comment]
Thanks for your reply @signedav !  I will try to explain using an example.

I use QField to map birds as point features. The form has the following fields:
- species code
- breeding status code (e.g. territorial male, feeding pair, migratory flock etc.)
- sex
- number of individuals
- observation time
- observation duration
- optional comment (e.g. details on plummage)
- some optional fields for behavioral details only recorded sometimes
- a bunch of other metadata that are editable, but usually filled in automatically, e.g. a session key, linking the observation to a weather record, type of inventory and observer details

As I need to be quick in the field (like 3 seconds per entry), I usually only enter species and breeding status code when creating a record, and pre-fill the rest of the form with defaults, based on expressions applied to those two entries. E.g. if I select "territorial male" -> sex = male, number = 1, observation time = now() and duration = 1, as this is the most likely combination. If other values occur (e.g. multiple individuals, observation in the past), I change them manually.
Assume I have saved the feature, keep adding other records, but after 15 mins I notice that the bird is still there. I want to update its record and set observation duration to 15 minutes. With the current behavior (irrespective of #54446 afaik), all fields are re-set to default, even if only a single field is changed, so I practically have to re-enter the whole observation, whose details I might already have forgotten. The alternative is to not use default values at all, which takes to much time.

For such use cases, where somewhat complex features need to be updated frequently, it would be ideal to have an option to apply defaults on feature creation only, but not again when updating a feature. As I mentioned in my previous post, this worked for me with older QGIS / QField versions, but stopped working at some point in spring 2023 (Was it possibly unintended behavior? Could it somehow be related to #51543?).

**Comment by signedav** [comment]
You have to note that this part of the implementation is in the GUI - means QGIS and QField have independent implementations. 

I think yes, what you require is to be able to apply this functionality on create feature only. Maybe you could make a feature request issue for that option.

**Comment by peterantkowiak** [comment]
Thank you! So if I understand you correctly, it would have to be a feature request for both QField and QGIS? 

As I recall, it used to work (for my use case, in both QField and QGIS) when entering an expression in the defaults field but leaving the "apply defaults on update" box unchecked. In the recent versions, I observe the following behavior:

QGIS 3.34: 
If "apply on update"-box is unchecked, defaults are applied once at feature creation, but not updated while filling the form, so no drill-down-form functionality (expressions like "now()" will work, but expressions based on values entered in other fields won't). 
If "apply on update"-box is checked, defaults are updated throughout feature creation, but when modifying a single field of a feature later, all fields with the box checked are reset to default values.

QField 3.0: 
Expression-based defaults only work if the "apply on update"-box is checked. In this case, the form behaves the same as in QGIS, so that defaults are applied to all fields with the box checked, when a feature is updated.
