### PR TITLE
Fix missing features in 3d views

### LINKED ISSUE #48295: 3d features randomly disappear from view when getting close too the camera
### What is the bug or the crash?

When a 3d map is navigated, features randomly disappear from the view as they get closer to the camera. This seems to be worse the higher features are placed. Eg. in the attached project the polygons are placed on the terrain, which leads to the issue. If i remove the terrain surface and place the polygons on the plane at 0 height then things work as expected.

[project.zip](https://github.com/qgis/QGIS/files/8525585/project.zip)

See screencast below:

https://user-images.githubusercontent.com/1829991/164327859-62528bf6-960d-45ef-9e73-5734afb62b72.mp4

### Steps to reproduce the issue

Open attached project, navigate the 3d view as shown in the screencast

### Versions

master

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nyalldawson**
Instead of starting with a bounding box with an estimated z range
based on sampled vertex height only, we now start with a "maximal"
z range and refine this after actually determine the real z range
of the vector layer child nodes.

This allows us to correctly account for features which are at
large height offsets or with large extrusion, and avoids these
features being incorrectly culled from the 3d views when their
estimated bounding boxes are out of view.

Fixes https://github.com/qgis/QGIS/issues/48295

Refs discussion in https://github.com/qgis/QGIS/pull/48313#issuecomment-1106242969

### CODE REVIEW

File: src/3d/qgsvectorlayer3drenderer.cpp [hunk 1]
```diff
@@ -70,10 +70,15 @@ Qt3DCore::QEntity *QgsVectorLayer3DRenderer::createEntity( const Qgs3DMapSetting
...
-  return new QgsVectorLayerChunkedEntity( vl, zMin + map.terrainElevationOffset(), zMax +  + map.terrainElevationOffset(), tilingSettings(), mSymbol.get(), map );
+  // we start with a maximal z range (based on a number similar to the radius of the Earth),
+  // because we can't know this upfront. There's too many
+  // factors to consider eg vertex z data, terrain heights, data defined offsets and extrusion heights,...
+  // This range will be refined after populating the nodes to the actual z range of the generated chunks nodes.
+  // Assuming the vertical height is in meter, then it's extremely unlikely that a real vertical
+  // height will exceed this amount!
+  constexpr double MINIMUM_VECTOR_Z_ESTIMATE = -5000000;
+  constexpr double MAXIMUM_VECTOR_Z_ESTIMATE = 5000000;
+  return new QgsVectorLayerChunkedEntity( vl, MINIMUM_VECTOR_Z_ESTIMATE, MAXIMUM_VECTOR_Z_ESTIMATE, tilingSettings(), mSymbol.get(), map );
```
Comment (wonder-sk) [inline src/3d/qgsvectorlayer3drenderer.cpp:81]: I think the same code update should also happen in QgsRuleBased3DRenderer::createEntity()

Comment (nyalldawson) [reply src/3d/qgsvectorlayer3drenderer.cpp:81]: Ok, I'll add

Comment (nyalldawson) [reply src/3d/qgsvectorlayer3drenderer.cpp:81]: Done

**Review by wonder-sk — APPROVED** [review]
