### PR TITLE
[relations] Fix problematic polymorphic relation's generated relation IDs

### LINKED ISSUE #47445: Polymorphic relation is lost in form if the referencing layer is renamed
### What is the bug or the crash?

Currently, the generated relation ID between a Referenced Layer and a Referencing layer is created by concatenating the **ID** of the Referenced layer + the **Name** of the referencing layer.

The problem is that when the referencing layer is renamed it the ID of the relation is changed but the Generated Relation Widget points to the old relation ID so the Widget doesn't work anymore.

Untitled

### Steps to reproduce the issue

1. Add a Polymorphic relation.
2. Add the generated widget to a form
3. Rename the layer 
4. The widget still works until you save and reopen the project
5. The form cannot see the widget anymore

The GIF tells it all:

poly_bug

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.4-Białowieża | QGIS code revision | ce8e65e95e
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.2
GDAL/OGR version | 3.4.1
PROJ version | 7.2.1
EPSG Registry database version | v10.008 (2020-12-16)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.34.1
PDAL version | 2.2.0
PostgreSQL client version | 14.2 (Debian 14.2-1.pgdg110+1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Debian GNU/Linux 11 (bullseye)
  |   |   |  
Active Python plugins

</body></html>QGIS version
3.22.4-Białowieża
QGIS code revision
[ce8e65e95e](https://github.com/qgis/QGIS/commit/ce8e65e95e)
Qt version
5.15.2
Python version
3.9.2
GDAL/OGR version
3.4.1
PROJ version
7.2.1
EPSG Registry database version
v10.008 (2020-12-16)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.34.1
PDAL version
2.2.0
PostgreSQL client version
14.2 (Debian 14.2-1.pgdg110+1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Debian GNU/Linux 11 (bullseye)

Active Python plugins

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This PR fixes https://github.com/qgis/QGIS/issues/47445 by insuring that polymorphic relations' generated relations rely on generated IDs that will remain valid if users change the referenced layer name.

~~To avoid breaking preexisting projects, relations using the weaker IDs (using layer name instead of layer ID) are also generated with a (deprecated) suffix added to their names. A //TODO is added to remove this whenever we hop onto QGIS 4 where we can break things ;)~~ The relation ID is automatically updated by the relation manager, insuring projects saved prior to this change don't break. 

I'd suggest backporting to LTR, IMHO a worthy fix. Among other things, it allows for polymorphic relationships to not go broken with translated projects.

### CODE REVIEW

File: src/core/qgsrelationmanager.cpp [hunk 1]
```diff
@@ -93,6 +93,19 @@ void QgsRelationManager::removeRelation( const QgsRelation &relation )
 
 QgsRelation QgsRelationManager::relation( const QString &id ) const
 {
+  if ( !mRelations.contains( id ) )
+  {
+    // Check whether the provided ID refers to a polymorphic relation's generated ID using QGIS < 3.38
```
Comment (m-kuhn) [inline src/core/qgsrelationmanager.cpp:98]:
```suggestion
    // Check whether the provided ID refers to a polymorphic relation's generated ID using QGIS < 3.38
    // If it has not yet been upgraded to a stable id, upgrade now
```

I think that gives a bit more context

File: src/core/qgspolymorphicrelation.h [hunk 2]
```diff
@@ -285,6 +285,10 @@ class CORE_EXPORT QgsPolymorphicRelation
     void setRelationStrength( Qgis::RelationshipStrength relationStrength );
 
   private:
+    friend class QgsRelationManager;
+
+    //! Upgrade a relation ID from IDs generated using QGIS < 3.38
```
Comment (m-kuhn) [inline src/core/qgspolymorphicrelation.h:290]:
```suggestion
    //! Upgrade a relation ID to a stable ID if generated using QGIS < 3.38
```

**Review by m-kuhn — APPROVED** [review]

**Comment by nirvn** [comment]
@m-kuhn , thanks for the review, comments added.
