### PR TITLE
Cache snapping results in feature dialog for subsequent recalculation

### LINKED ISSUE #37359: Default values using @snapping_result delete attributes
Given a point layer with an attribute `name` and an attribute `time`.
Configure the default value for the field `name` using the expression below. Disable (or enable) apply on update.

Expected behavior: when I add a point on top of an existing one, it will copy the name and I'm able to fine tune the fields.
Observed behavior: when I add a point on top of an existing one, it will copy the name but as soon as I edit the time, the field `name` is cleared.

```
with_variable(
  'first_snapped_point',
  array_first( @snapping_results ),
  attribute(
    get_feature_by_id(
      map_get( @first_snapped_point, 'layer' ),
      map_get( @first_snapped_point, 'feature_id' )
    ),
    'name'
  )
)
```

### PR DESCRIPTION
**Pull request by m-kuhn**
Snapping results are used for initial calculation of default values on an attribute form.

If a default value has to be recalculated (because it depends on another attribute) the snapping results are no longer available.

Fixes #37359

### CODE REVIEW

**Comment by m-kuhn** [comment]
@signedav can I get your eyes on this?

File: src/gui/qgsattributedialog.h [hunk 1]
```diff
@@ -95,6 +95,14 @@ class GUI_EXPORT QgsAttributeDialog : public QDialog
      */
     bool event( QEvent *e ) override;
 
+    /**
+     * Sets an additional expression context scope to be used
+     * for calculations in this form.
```
Comment (signedav) [inline src/gui/qgsattributedialog.h:100]: Is it an "additional"/"extra" scope or is it just "the" scope used in the expression context for the calculations?
Anyway, maybe add the param like: `Sets \a extraScope as the additional expression...`

**Review by signedav — APPROVED** [review]
Code looks good :+1:

File: src/gui/qgsattributedialog.h (hunk 1 above)
Comment (m-kuhn) [reply src/gui/qgsattributedialog.h:100]: Other scopes are already there (global, project, layer, form) and this one can be provided from the exterior (e.g. map tool capture)
I'll adjust
