### PR TITLE
Fix atlas export when file name contains multiple dots

### LINKED ISSUE #29980: Export atlas as image fail when expression filename contain dot
**Describe the bug**
Under windows 10, atlas export as image fail when filename contain dot "." character while it worked perfectly fine under QGIS 2.18. This is a quite used, accepted and useful character for filenames so I really see this as a regression.

**How to Reproduce**

0. Download, unzip and open attached demo project
[20190527_bug_path_atlas.zip](https://github.com/qgis/QGIS/files/3226551/20190527_bug_path_atlas.zip)

1. Go to Layout > "atlas (bugging with all features)"
2. Click on 'preview atlas' and see that all is fine
atlas_export_fail_setup

3. Click on export atlas as images (I used png) and choose destination folder
Notice that export will fail on feature 3 with expected filename "output_foo.bar.png"
atlas_export_fail

4. Optionally open Layout > "atlas (working with feature 1&2)"
Run same steps 2&3 and notice everything work smoothly as feature 3 is excluded in atlas filter.

**Desktop environment (please complete the following information):**

 - OS and version: Winwdows 10

**QGIS version**

QGIS version | 3.6.2-Noosa | QGIS code revision | 656500e0c4
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.0-CAPI-1.11.0 | Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version | 9.2.4 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018

**Additional context**

Possibly linked to #28829

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #29980

### CODE REVIEW

File: src/core/layout/qgslayoutexporter.cpp [hunk 1]
```diff
@@ -346,7 +346,13 @@ QgsLayoutExporter::ExportResult QgsLayoutExporter::exportToImage( const QString
   PageExportDetails pageDetails;
   pageDetails.directory = fi.path();
   pageDetails.baseName = fi.baseName();
-  pageDetails.extension = fi.completeSuffix();
+  pageDetails.extension = fi.suffix();
+  // Deal with multiple dots, issue GH-29980
+  const auto completeSuffix { fi.completeSuffix() };
+  if ( completeSuffix != pageDetails.extension )
```
Comment (nyalldawson) [inline src/core/layout/qgslayoutexporter.cpp]: Would completeBaseName work here instead?

Comment (elpaso) [reply src/core/layout/qgslayoutexporter.cpp]: Yes, sure, I missed that one.

**Review by nyalldawson — APPROVED** [review]
