### PR TITLE
Fix post MultiPart

### LINKED ISSUE #46989: MultiPart post network request stopped working
### What is the bug or the crash?

One of my plugins stopped working in QGIS master, because some of the requests seem invalid. Specifically requests that post data data with a file as multipart content do not work

### Steps to reproduce the issue

Not easy to reproduce by clicking, but I wrote a script to test this. I posted it on the developer mailing list: https://lists.osgeo.org/pipermail/qgis-developer/2022-January/064437.html

### Versions

Well it depends on the versions. I've been building many to get close to the date it broke:
14 sep: works
1 oct: works
1 dec: works
7 dec: broken
16 dec: broken
1 jan: broken
23 jan: broken

Here's the output for my December 7 build:

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.23.0-Master | QGIS code revision | be5613883c
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.3 LTS
  |   |   |  
Active Python plugins
ImaerPlugin | version 3.1.0
plugin_reloader | 0.9.1
pdokservicesplugin | 3.7.3
qgis_3d_ams | 0.1
QuickOSM | 2.0.0
firstaid | 2.1.5
QCopycanvas | 0.5
sagaprovider | 2.12.99
processing | 2.12.99

</body></html>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by m-kuhn**
This reverts commit c62a2558e24b335caca53d0769487e0eddf0f0da.

Calling `readAll()` on `outgoingData` breaks multipart post requests.

Fixes https://github.com/qgis/QGIS/issues/46989

### CODE REVIEW

**Review by nirvn — APPROVED** [review]
I also confirm removing the block fixed things.

Hurrah for the additional test.

**Comment by elpaso** [comment]
Can you please wait to merge? 

You have disabled a test about another problem that this code was fixing.

**Comment by m-kuhn** [comment]
Happy to wait for you @elpaso

**Comment by m-kuhn** [comment]
@elpaso can you be more precise about the problem?
This pull request avoids reading the complete request into memory prior to sending it:

 - depending on the QIODevice acting as source, this can only be read once. This is the main problem being fixed here.
 - If the request is submitting a huge file, this blows up memory usage unnecessarily
 - Downside: we don't have the complete request in the debugger and other code external code, but I don't think that is how Qt meant this to work

File: tests/src/core/testqgsnetworkaccessmanager.cpp [hunk 1]
```diff
@@ -556,6 +558,23 @@ void TestQgsNetworkAccessManager::fetchPost()
...
 }
 
+void TestQgsNetworkAccessManager::fetchPostMultiPart()
+{
+  QUrl u =  QUrl( QStringLiteral( "http://" ) + mHttpBinHost + QStringLiteral( "/post" ) );
+  QNetworkRequest req( u );
+
+  // MultiPart
+  QNetworkReply *reply = QgsNetworkAccessManager::instance()->post( req, new QHttpMultiPart( QHttpMultiPart::MixedType ) );
+
```
Comment (elpaso) [inline tests/src/core/testqgsnetworkaccessmanager.cpp:568]:
```suggestion
    multiPart->setParent(reply);
```

Comment (elpaso) [reply tests/src/core/testqgsnetworkaccessmanager.cpp:568]: Wait, missing the whole part:

```C++
  QHttpMultiPart* multiPart = new QHttpMultiPart( QHttpMultiPart::FormDataType );
  QHttpPart part;
  part.setHeader( QNetworkRequest::ContentDispositionHeader,
                  QStringLiteral( "form-data; name=\"param\"" ) );
  part.setBody( QStringLiteral( "some data") .toUtf8() );
  multiPart->append( part );
  QNetworkReply *reply = QgsNetworkAccessManager::instance()->post( req, multiPart);
  multiPart->setParent(reply);
```

File: tests/src/python/test_qgsaction.py [hunk 2]
```diff
@@ -64,38 +64,41 @@ def _req_logger(self, params):
...
-            'Content-Disposition: form-data; name="a&+b"',
-            '',
-            'a and plus b',
-            '--boundary_.oOo.UUID',
-            'Content-Disposition: form-data; name="a=b"',
-            '',
-            'a equals b',
-            '--boundary_.oOo.UUID',
-            '']))
+# TEST DISABLED
```
Comment (elpaso) [inline tests/src/python/test_qgsaction.py:67]: I think you can remove the whole test case: I don't really know how to test it without the content: any idea?

I don't want to add a subprocess with a (python) server, this proved to be fragile in the past.

**Review by elpaso — APPROVED** [review]
LGTM, I checked the action manually and it works as expected, I added that piece of code to be able to test the action but obviously it had unwanted side effects.

File: tests/src/python/test_qgsaction.py (hunk 2 above)
Comment (m-kuhn) [reply tests/src/python/test_qgsaction.py]: Done.
I think it would be possible to add a test too by storing an action result inside the action, but I do not have the intention to go further in this area myself.
