### PR TITLE
Raster paletted/unique float support

### LINKED ISSUE #39058: Wrong assignments of raster values to symbology Paletted/Unique values or Singleband Pseudocolor
I'm seeing some inconsistencies when styling raster layers.

Here is a sample raster (Float32) that has pixels with 4 different values:

[prob0115_sample.zip](https://github.com/qgis/QGIS/files/5289216/prob0115_sample.zip)

```
 - 0;
 - 3.450000047683716;
 - 6.900000095367432;
 - 10.350000381469727.
```
 
Loading it to QGIS, the default Singleband Gray render type shows the 4 values with different levels of gray.

- If I try to apply a Paletted/Unique Values render style, to get different colours for each value, canvas shows these different colours, but legend on TOC display wrong values for each one:

```
 - 0;
 - 3.78333;
 - 6.62083;
 - 10.4042.
```

imagem

As you can see, value in Symbology dialogue only show 0, 3, 6 and 10, and labels are different from raster values (not even rounded).

- If I try to use Singleband Pseudocolor as render type, with Exact interpolation, to get 4 particular colours to each one of the 4 raster values, I get some classes not rendered in canvas (just transparent):

imagem

However, if I assign the exact raster values manually, with full precision (all decimal places), they are already rendered:

imagem

Here is a screencast that shows this behaviour: https://cld.pt/dl/download/02852983-9f11-439d-bc81-33b58ade21bc/raster_symbology.mp4 

So, I believe that all these problems come from the raster precision that is not captured or is rounded by symbology engine. Anyone confirm?

Tested with 

QGIS version | 3.14.16-Pi | QGIS code revision | 2b2f966720
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.2.0dev | Running against GDAL/OGR | 3.2.0dev
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 7.2.0 | Running against PROJ | Rel. 7.2.0, November 1st, 2020
OS Version | Windows 10 (10.0) | This copy of QGIS writes debugging output.

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #39058 an adds some small improvements in the
progress feedback.

This is technically an API change, even if it's small I'm not sure we can merge it now, I could create another ctor for Python API if needed.

### CODE REVIEW

File: src/core/raster/qgspalettedrasterrenderer.cpp [hunk 1]
```diff
@@ -472,37 +475,98 @@ QgsPalettedRasterRenderer::ClassData QgsPalettedRasterRenderer::classDataFromRas
...
     {
-      data << Class( currentValue, QColor(), QLocale().toString( currentValue ) );
-      presentValues++;
+      return data;
+    }
+    const double yStep { fullExtent.height() / raster->ySize() };
+    // Max MAX_FLOAT_CLASSES classes!
+    qgssize col = 0;
+    qgssize row = 0;
+    for ( row = raster->ySize() - 1; row >= 0; --row )
```
Comment (nyalldawson) [inline src/core/raster/qgspalettedrasterrenderer.cpp:495]: It would be more performant to iterate over the raster using QgsRasterIterator here -- row sized blocks like this will result in many data requests.

File: src/core/raster/qgspalettedrasterrenderer.cpp [hunk 2]
```diff
@@ -472,37 +475,98 @@ QgsPalettedRasterRenderer::ClassData QgsPalettedRasterRenderer::classDataFromRas
...
   double presentValues = 0;
-  for ( int idx = 0; idx < histogram.binCount; ++idx )
+
+  // Collect unique values for float rasters
+  if ( raster->dataType( bandNumber ) == Qgis::DataType::Float32 || raster->dataType( bandNumber ) == Qgis::DataType::Float64 )
   {
-    int count = histogram.histogramVector.at( idx );
-    if ( count > 0 )
+    const QgsRectangle fullExtent { raster->extent() };
+    QList<double> values;
```
Comment (nyalldawson) [inline src/core/raster/qgspalettedrasterrenderer.cpp:485]: A list isn't a great choice here -- could you use an ordered set instead? or unordered set and sort after collecting the values?

**Comment by nyalldawson** [comment]
> This is technically an API change, even if it's small I'm not sure we can merge it now, I could create another ctor for Python API if needed.

I don't think that's an issue here

**Review by nyalldawson — APPROVED** [review]

**Comment by PedroVenancio** [comment]
@elpaso This is working great with floats in 3.16.

The only thing I see is that the legend is not ordered by value:

imagem

imagem

It can be manually reordered, so, nothing problematic.

**Comment by elpaso** [comment]
Can you file another ticket for the ordering issue please?
