### PR TITLE
Fix QgsUnsetAttributeValue toString

### LINKED ISSUE #61529: PG: Can't add/update feature when numeric field with numeric default is set to default
### What is the bug or the crash?

This error occurs for layers backed by a Postgres/PostGIS table having a numeric column whose default value is a number.

When adding or updating a feature with the numeric field set to the default value then the feature is not added/updated and an error like the following is displayed:

```
Could not commit changes to layer name_of_the_layer

Errors: ERROR: 1 feature not added.
  
  Provider errors:
      PostGIS error while adding features: ERROR:  invalid input syntax for integer: ""
    LINE 1: ... VALUES (st_multi(st_geomfromwkb($1::bytea,4326)),'') RETURN...
                                                                 ^
```

### Steps to reproduce the issue

- In your PostGIS database create a test table:
```sql
-- DROP TABLE IF EXISTS public.defval_test;

CREATE SEQUENCE IF NOT EXISTS public.defval_test_id_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
-- If needed:
-- ALTER TABLE public.defval_test_id_seq OWNER TO my_postgres_user_name;

CREATE TABLE public.defval_test
(
  id integer NOT NULL DEFAULT nextval('defval_test_id_seq'::regclass),
  geom geometry(MultiPolygon,4326),
  status smallint DEFAULT 0,
  CONSTRAINT defval_test_pkey PRIMARY KEY (id)
);
-- If needed:
-- ALTER TABLE public.defval_test OWNER TO my_postgres_user_name;
```
- Create a new QGIS project
- Add the `defval_test` table to the project via **Layer→Add Layer→Add PostGIS Layers**
- Make the layer editable
- Add a new feature to the layer, leaving `status` at its default value
- Click on **Save Layer Edits**
- The following error is displayed:
```
Could not commit changes to layer defval_test

Errors: ERROR: 1 feature not added.
  
  Provider errors:
      PostGIS error while adding features: ERROR:  invalid input syntax for integer: ""
    LINE 1: ... VALUES (st_multi(st_geomfromwkb($1::bytea,4326)),'') RETURN...
                                                                 ^
 ```
- Press `Ctrl+Z` to remove the feature.
- Add a new feature to the layer, setting `status` to something other than its default value (i.e. a non-zero value)
- Click on **Save Layer Edits**
  *The feature will be successfully added.*
- Switch to the **Identify Features** tool
- Click on the feature
- Change `status` to its default value (`0` in this case)
- Click on **Save Layer Edits**
- The following error is displayed:
```
Could not commit changes to layer defval_test

Errors: ERROR: 1 attribute value change not applied.
  
  Provider errors:
      PostGIS error while changing attributes: ERROR:  invalid input syntax for integer: ""
    LINE 1: UPDATE "public"."defval_test" SET "status"='' WHERE "id"=3
                                                       ^
    
```

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.43.0-Master</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/a6aa24e41c">a6aa24e41c</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.3</td></tr><tr><td>Python version</td><td>3.10.12</td></tr><tr><td>GDAL version</td><td>3.4.1</td></tr><tr><td>PROJ version</td><td>8.2.1</td></tr><tr><td>EPSG Registry database version</td><td>v10.041 (2021-12-03)</td></tr><tr><td>GEOS version</td><td>3.10.2-CAPI-1.16.0</td></tr><tr><td>SQLite version</td><td>3.37.2</td></tr><tr><td>PDAL version</td><td>2.9.0</td></tr><tr><td>PostgreSQL client version</td><td>17.4</td></tr><tr><td>SpatiaLite version</td><td>5.0.1</td></td></tr><tr><td>QWT version</td><td>6.1.4</td></tr><tr><td>QScintilla2 version</td><td>2.11.6</td></tr><tr><td>OS version</td><td>Ubuntu 22.04.5 LTS</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>layer_color_plugin</td><td>0.3</td></tr><tr><td>processing</td><td>2.12.99</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr></table>

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I have isolated and fixed the issues; will submit a PR shortly.

These issues may also be present in other providers; this was not checked.

### PR DESCRIPTION
**Pull request by elpaso**
Fix #61529

### CODE REVIEW

**Comment by nyalldawson** [comment]
@elpaso can you give some more details about how this fixes the linked issue?

**Comment by elpaso** [comment]
> @elpaso can you give some more details about how this fixes the linked issue?

Using a debugger I tracked down the issue to the default value being returned as an empty string, even if a default value clause was set.

This was the root cause of a series of issues, including the harmless warning

```bash
WARNING    Query: BEGIN READ ONLY;DECLARE qgis_1 BINARY CURSOR FOR SELECT "id","status_d"::text FROM "public"."defval_test_minimal" WHERE ("id" = '') LIMIT 2 returned 7 [ERROR: invalid input syntax for integer: ""
        LINE 1: ...FROM "public"."defval_test_minimal" WHERE ("id" = '') LIMIT ...
         ^
        ]
WARNING    1 cursor states lost.
        SQL: BEGIN READ ONLY;DECLARE qgis_1 BINARY CURSOR FOR SELECT "id","status_d"::text FROM "public"."defval_test_minimal" WHERE ("id" = '') LIMIT 2
        Result: 7 (ERROR: invalid input syntax for integer: ""
        LINE 1: ...FROM "public"."defval_test_minimal" WHERE ("id" = '') LIMIT ...
         ^
        )
```

This was caused by https://github.com/qgis/QGIS/blob/master/src/core/vector/qgsvectorlayerutils.cpp#L437 not returning true, which was caused by https://github.com/qgis/QGIS/blob/master/src/providers/postgres/qgspostgresprovider.cpp#L2106

In particular, what was failing was `mDefaultValues.value( fieldIndex ) == value.toString()` , which led me to the fix:

```c++
 QMetaType::registerConverter<QgsUnsetAttributeValue, QString>( &QgsUnsetAttributeValue::toString );
```

and 
```c++
    QString QgsUnsetAttributeValue::toString() const
    {
      return mDefaultValueClause;
    }
```

**Comment by elpaso** [comment]
@nyalldawson sorry I messed this up a little, the real changes to review are:

https://github.com/qgis/QGIS/pull/62010/files#diff-7f947fdb335de46cfdcbe17158b0ff4fb9e619322980962b67b13b178f1a7441R166

and
https://github.com/qgis/QGIS/pull/62010/files#diff-8fc1e19bdc3a51f281bf3789e7087de205ae9287ad1a30225aaaf7d92e033154R2106

plus
https://github.com/qgis/QGIS/pull/62010/files#diff-dd59a9bee25102df14d09b59261cd22c10b62b8b9c53d72667f2d0d5cf7bd0f1R57

the other changes are variable renaming, const correctness and the introduction of `static bool isUnsetAttributeValue( const QVariant &variant )`

File: src/core/qgsauxiliarystorage.cpp [hunk 1]
```diff
@@ -635,7 +635,8 @@ QgsAuxiliaryStorage::QgsAuxiliaryStorage( const QString &filename, bool copy )
 
 QgsAuxiliaryStorage::~QgsAuxiliaryStorage()
 {
-  QFile::remove( mTmpFileName );
+  if ( QFile::exists( mTmpFileName ) )
```
Comment (nyalldawson) [inline src/core/qgsauxiliarystorage.cpp:638]: unrelated changes

File: tests/src/python/test_provider_postgres.py [hunk 2]
```diff
@@ -2362,6 +2362,65 @@ def testSkipConstraintCheck(self):
...
+                QgsUnsetAttributeValue(),
+            )
+        )
+        self.assertTrue(
+            vl.dataProvider().skipConstraintCheck(
+                0,
+                QgsFieldConstraints.Constraint.ConstraintNotNull,
+                QgsUnsetAttributeValue(),
+            )
+        )
```
Comment (nyalldawson) [inline tests/src/python/test_provider_postgres.py:2378]: To be safe, can you add a test here for a field index which DOESN'T have a default clause? Those fields should return False to skipConstraintCheck if passed a unset attribute value (at least for the ConstraintNotNull constraint)

**Comment by nyalldawson** [comment]
Looking good @elpaso!

File: src/providers/hana/qgshanaprovider.cpp [hunk 3]
```diff
@@ -1180,7 +1180,7 @@ bool QgsHanaProvider::changeAttributeValues( const QgsChangedAttributesMap &attr
         if ( field.name.isEmpty() || field.isAutoIncrement )
           continue;
 
-        if ( it2->userType() == qMetaTypeId< QgsUnsetAttributeValue >() )
+        if ( QgsVariantUtils::isUnsetAttributeValue( it2 ) )
```
Comment (elpaso) [inline src/providers/hana/qgshanaprovider.cpp:1183]:
```suggestion
        if ( QgsVariantUtils::isUnsetAttributeValue( it2.value() ) )
```

File: tests/src/python/test_provider_postgres.py (hunk 2 above)
Comment (nyalldawson) [reply tests/src/python/test_provider_postgres.py:2378]: >  The more I dig into this the more I lack the comparator (toString()) I initially added, we should be able to get the default clause out of the QgsUnsetAttributeValue to check whether it is empty or equal to the current value (given that the current toString returns an empty string).

The problem is that any string to defaultValue comparisons will break the design of QgsUnsetAttributeValue, which is intended to work correctly across different providers. I.e. when copying a feature from one provider to another, we shouldn't be relying on any provider-side default value comparisons as these will be different. (Or, to use a real-world example, copying an unsaved feature from a geopackage layer with fid attribute set to `QgsUnsetAttributeValue( "Autogenerate" )` should still paste without issue into a postgres layer with a different default value clause for that field (or even, no default value clause). 

The **only** time we should be doing comparisons against the default value clause is to maintain compatibility with old API, where we relied on checking string values against provider default values as a way to quasi-detect unset attributes.

But to get back to your original issue:

> does not consider the case when value is a QgsUnsetAttributeValue with no default clause

I'd treat this the same as a null, as that's what standard behavior for a database would be (i.e. `INSERT INTO some_table_with_many_columns (col1, col3) values (1, 3)` would typically result in NULL values for col2)

Comment (elpaso) [reply tests/src/python/test_provider_postgres.py:2378]: @nyalldawson ok, done, test passes locally, let's hope CI is benevolent today.

Comment (nyalldawson) [reply tests/src/python/test_provider_postgres.py:2378]: @elpaso there's a Ubuntu issue ongoing -- see https://askubuntu.com/questions/1549622/problem-with-archive-ubuntu-com-most-of-the-servers-are-not-responding/1549644

File: src/core/qgsauxiliarystorage.cpp [hunk 4]
```diff
@@ -635,8 +635,7 @@ QgsAuxiliaryStorage::QgsAuxiliaryStorage( const QString &filename, bool copy )
 
 QgsAuxiliaryStorage::~QgsAuxiliaryStorage()
 {
-  if ( QFile::exists( mTmpFileName ) )
-    QFile::remove( mTmpFileName );
+  QFile::remove( mTmpFileName );
```
Comment (nyalldawson) [inline src/core/qgsauxiliarystorage.cpp]: This has crept back in

**Review by nyalldawson — APPROVED** [review]

File: src/core/qgsauxiliarystorage.cpp (hunk 4 above)
Comment (elpaso) [reply src/core/qgsauxiliarystorage.cpp]: fixed
