### PR TITLE
[layouts] Use nicer number formatting for dynamic map scale labels

### LINKED ISSUE #51764: Add Dynamic Text -> Scale on layout not inserting correct scale
### What is the bug or the crash?

When I try to add dynamic scale text on my layout, it is not working properly.

Instead of inserting the correct scale, it inserts the scale with .99999999. Please look the attached pic. The map has a scale of 
4 000 000, and when I try to add the scale using the add dynamic text scale function it inserts the scale as 3 999 999.9999999.

Please fix this issue asap, I need this option in order to create and export layouts for my work !!

Thanks in advance

image

### Steps to reproduce the issue

not correct scale

### Versions

QGIS version
3.28.3-Firenze
QGIS code revision
c12bcb2f76c
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
batchvectorlayersaver
0.9
flurstuecksfinder-nrw
1.3.0
kmltools
3.1.27
latlontools
3.6.7
mmqgis
2021.9.10
OpenTopography-DEM-Downloader
1.0
profiletool
4.2.2
QuickOSM
2.1.1
quick_map_services
0.19.33
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nyalldawson**
Fixes #51764

### CODE REVIEW

File: src/gui/layout/qgslayoutlabelwidget.cpp [hunk 1]
```diff
@@ -146,7 +146,7 @@ void QgsLayoutLabelWidget::buildInsertDynamicTextMenu( QgsLayout *layout, QMenu
     QMenu *mapMenu = new QMenu( map->displayName(), mapsMenu );
     for ( const std::pair< QString, QString > &expression :
           {
-            std::make_pair( tr( "Scale (%1)" ).arg( map->scale() ), QStringLiteral( "item_variables('%1')['map_scale']" ).arg( map->id() ) ),
+            std::make_pair( tr( "Scale (%1)" ).arg( map->scale() ), QStringLiteral( "format_number(item_variables('%1')['map_scale'], 6, omit_group_separators:=true, trim_trailing_zeroes:=true)" ).arg( map->id() ) ),
```
Comment (nirvn) [inline src/gui/layout/qgslayoutlabelwidget.cpp:149]: I'm curious, why 6 decimals here?

**Review by nirvn — APPROVED** [review]

File: src/gui/layout/qgslayoutlabelwidget.cpp (hunk 1 above)
Comment (nyalldawson) [reply src/gui/layout/qgslayoutlabelwidget.cpp:149]: I figure it can't hurt to go more vs less given we are trimming trailing zeroes, and there's at least report in the system from users who are using print layouts for micro (macro?) scale work in the sub-mm range.

Comment (nirvn) [reply src/gui/layout/qgslayoutlabelwidget.cpp:149]: @nyalldawson , if we'd be willing to complexify the formula, would could make the nb of decimal based on scale (i.e. < if (scale < 100, 6, 3)).

Comment (nyalldawson) [reply src/gui/layout/qgslayoutlabelwidget.cpp:149]: I'm reluctant to make these too complex, as they are a nice way to gently expose users to the expression engine. If they get too fancy then we'll lose the transparency of what's actually happening. 

What about if we added the argument name for the decimals parameter so that it's a bit clearer to a user what this number means (and hopefully empower them to easily change it themselves)?

Comment (nirvn) [reply src/gui/layout/qgslayoutlabelwidget.cpp:149]: @nyalldawson , sounds good.

Comment (roya0045) [reply src/gui/layout/qgslayoutlabelwidget.cpp:149]: > I'm reluctant to make these too complex, as they are a nice way to gently expose users to the expression engine. If they get too fancy then we'll lose the transparency of what's actually happening.
> 
> What about if we added the argument name for the decimals parameter so that it's a bit clearer to a user what this number means (and hopefully empower them to easily change it themselves)?

Exposing the number would be a good idea, though what lead to the ticket was the difference between the two displayed values. I'm guessing having the same formatting would make sense in this case as this is show as a way to display outwark what is in the UI.

Though what might be more interesting is exposing a variable that countrols the level or rounding above the decimals (decimal precision in scale should be irrelevant in nearly all cases) but having a way to round to the 1000s or 100s might be a nice things to let users tweak and get them more at ease with expressions. Should format number accept negative values to allow this kind of rounding?

Comment (nyalldawson) [reply src/gui/layout/qgslayoutlabelwidget.cpp:149]: > Should format number accept negative values to allow this kind of rounding?

Sounds like a great idea!

**Comment by uclaros** [comment]
@nyalldawson why does the scale need rounding though, while the user explicitly sets a round scale number?

**Comment by nyalldawson** [comment]
@uclaros 

Cos of floating point precision -- without it you'll get scales like 29999.99999999999

**Comment by uclaros** [comment]
> Cos of floating point precision -- without it you'll get scales like 29999.99999999999

Well, what is not that obvious to me is why the scale is _calculated_ when the user explicitly sets 30000, which should be nicely representable by doubles. And furthermore, why it is not rounded upon calculation (the variable `map_scale` is still 29999.99999999999) and only rounded on the dynamic label?
