### PR TITLE
addresses #46673 (QgsProcessingMapLayerComboBox shows layers out of

### LINKED ISSUE #46673: QgsProcessingMapLayerComboBox shows layers out of QgsProcessingParameterWidgetContext
### What is the bug or the crash?

A QgsProcessingParameterWidgetContext allows to specify the context in which processing parameter widgets are shown. This allows to modify the set of map layers that is shown to users, e.g. by using a self defined QgsProject:

However, the QgsProcessingMapLayerComboBox does not reflect the new context, while other widgets like the QgsProcessingMultipleLayerPanelWidget correctly do. The python code below (see Steps to reproduce) wants to present 'Layer B', but the map layer combo box still allows to select 'Layer B' only:

image

The QgsProcessingMapLayerComboBox uses the QgsMapLayerComboBox and this is using the QgsMapLayerModel.
A solution might therefore be to add a new `QgsMapLayerModel::setProject( QgsProject *project)` and modify  `QgsProcessingMapLayerComboBox::setWidgetContext` accordingly.

### Steps to reproduce the issue

````python
from qgis.PyQt.QtWidgets import QWidget, QGridLayout
from qgis.core import QgsProcessingParameterMultipleLayers, QgsProcessingContext, \
    QgsVectorLayer, QgsProject, QgsProcessingParameterVectorLayer

from qgis.gui import QgsProcessingGui, QgsGui, QgsProcessingParameterWidgetContext
from qgis.testing.mocked import start_app
APP = start_app()

uri = 'Point?crs=epsg:4326&field=id:integer&field=name:string(20)'
layerA = QgsVectorLayer(uri, 'Layer A', 'memory')
QgsProject.instance().addMapLayer(layerA)

layerB = QgsVectorLayer(uri, 'Layer B', 'memory')
localProject = QgsProject()
localProject.addMapLayer(layerB)
localWidgetContext = QgsProcessingParameterWidgetContext()
localWidgetContext.setProject(localProject)
localProcessingContext = QgsProcessingContext()
localProcessingContext.setProject(localProject)

param1 = QgsProcessingParameterVectorLayer('SINGLE_LAYER', 'Single Layer')
param2 = QgsProcessingParameterMultipleLayers('MULTIPLE_LAYERS', 'Multiple Layers')

l = QGridLayout()
for row, param in enumerate([param1, param2]):
    wrapper = QgsGui.processingGuiRegistry().createParameterWidgetWrapper(param, QgsProcessingGui.Standard)
    wrapper.setWidgetContext(localWidgetContext)
    l.addWidget(wrapper.createWrappedLabel(), row, 0)
    l.addWidget(wrapper.createWrappedWidget(localProcessingContext), row, 1)

w = QWidget()
w.setLayout(l)
w.show()
APP.exec_()
````

### Versions

QGIS 3.23.0-Master 
QGIS code revision 307bb854b1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jakimowb**
## Description

This PR fixes #46673 (QgsProcessingMapLayerComboBox shows layers out of QgsProcessingParameterWidgetContext),
which caused that QgsProcessingMapLayerComboBox disregards the QgsProject of the QgsProcessingParameterWidgetContext.

## Changes

A new `setProject(QgsProject *project)` has been implemented in `QgsMapLayerModel`, `QgsMapLayerProxyModel` and `QgsMapLayerComboBox`: 

    src/core/qgsmaplayermodel.cpp
    src/core/qgsmaplayermodel.h
    src/core/qgsmaplayerproxymodel.cpp
    src/core/qgsmaplayerproxymodel.h

Accordingly, new `testProject(self)` tests were added to:

    tests/src/python/test_qgsmaplayercombobox.py 
    tests/src/python/test_qgsmaplayermodel.py 

This way, `QgsProcessingMapLayerComboBox` now can update the QgsProject of it's map layer combo box:

````cpp
void QgsProcessingMapLayerComboBox::setWidgetContext( const QgsProcessingParameterWidgetContext &context )
{
  mBrowserModel = context.browserModel();
  mCombo->setProject( context.project() );
}
````

SIP files were updated by scripts/sipify_all.sh:
   
    python/core/auto_generated/qgsmaplayermodel.sip.in
    python/core/auto_generated/qgsmaplayerproxymodel.sip.in
    python/gui/auto_generated/qgsmaplayercombobox.sip.in

### CODE REVIEW

File: src/core/qgsmaplayermodel.cpp [hunk 1]
```diff
@@ -40,6 +40,25 @@ QgsMapLayerModel::QgsMapLayerModel( QObject *parent, QgsProject *project )
...
+
+  // remove layers from previous project
+  if ( mProject )
+  {
+    removeLayers( mProject->mapLayers().keys() );
+    disconnect( mProject, &QgsProject::layersAdded, this, &QgsMapLayerModel::addLayers );
+    disconnect( mProject, static_cast < void ( QgsProject::* )( const QStringList & ) >( &QgsProject::layersWillBeRemoved ), this, &QgsMapLayerModel::removeLayers );
+  }
+
+  mProject = project;
```
Comment (nyalldawson) [inline src/core/qgsmaplayermodel.cpp:54]:
```suggestion
  mProject = project ? project : QgsProject::instance();
```

File: src/core/qgsmaplayerproxymodel.h [hunk 2]
```diff
@@ -88,6 +89,13 @@ class CORE_EXPORT QgsMapLayerProxyModel : public QSortFilterProxyModel
      */
     const Filters &filters() const { return mFilters; }
 
+    /**
+     * Sets the QgsProject from which map layers are shown
```
Comment (nyalldawson) [inline src/core/qgsmaplayerproxymodel.h:93]:
```suggestion
     * Sets the \a project from which map layers are shown.
     *
     * If \a project is NULLPTR then QgsProject::instance() will be used.
```

File: src/gui/qgsmaplayercombobox.h [hunk 3]
```diff
@@ -73,6 +73,14 @@ class GUI_EXPORT QgsMapLayerComboBox : public QComboBox
      */
     QStringList excludedProviders() const;
 
+    /**
+     * Sets the QgsProject from which map layers are shown
```
Comment (nyalldawson) [inline src/gui/qgsmaplayercombobox.h:77]:
```suggestion
     * Sets the \a project from which map layers are shown.
     *
     * If \a project is NULLPTR then QgsProject::instance() will be used.     
```

**Review by nyalldawson — APPROVED** [review]
