### PR TITLE
Fail algorithm when sink cannot be flushed

### LINKED ISSUE #59237: extract by expression save to geopackage creates empty layer when fid is not unique
### What is the bug or the crash?

Running the tool Extract by expression and saving the result as a geopackage creates an empty layer and no warning when the input layer is a temporary layer with a fid column which has no unique values.
When the result is a temporary layer, there is no problem.

### Steps to reproduce the issue

You can use the world map layer in QGIS for this:

Run Dissolve on the world map and dissolve by field ISO-A3 > output as temporary layer
Run Multipart to singleparts on the Dissolved result > output as temporary layer
Check fid attribute and notice that multiple fid values are the same, as expected
Run Extract by Expression on the Singleparts output, use  "NAME" LIKE 'A%' and save Matching Features as geopackage.
The new layer will be empty.
However, outputting the result as a temporary layer, you do get a result.

It seems the Extract result can not be saved in a geopackage because the existing fid column in the temporary singelparts layer no longer has unique values.

Note that saving the Multipart to singleparts output to a geopackage solves this problem. The singlepart layer is getting a (new, improved??) fid column which has unique values.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.11-Prizren | QGIS code revision | 2904bcec
-- | -- | -- | --
Qt version | 5.15.13
Python version | 3.12.6
GDAL/OGR version | 3.9.2
PROJ version | 9.4.0
EPSG Registry database version | v11.004 (2024-02-24)
GEOS version | 3.12.2-CAPI-1.18.2
SQLite version | 3.45.1
PDAL version | 2.6.3
PostgreSQL client version | 16.2
SpatiaLite version | 5.1.0
QWT version | 6.2.0
QScintilla2 version | 2.14.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
batchvectorlayersaver | 0.9
GroupStats | 2.2.7
inspireatomclient | 0.8.1
maplibrary | 1.3
pdokservicesplugin | 5.1.1
pdok_locatieserver_locator_filter | 0.2.1
PluginLoadTimes | 4.1.0
qgis2web | 3.22.0
QNEAT3 | 1.0.5
quick_map_services | 0.19.34
SelectionFilter | 1.0
SpreadsheetLayers | 2.1.2
wfs_styler | 1.0.1
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99

</body></html>QGIS version
3.34.11-Prizren
QGIS code revision
[2904bcec](https://github.com/qgis/QGIS/commit/2904bcec)
Qt version
5.15.13
Python version
3.12.6
GDAL/OGR version
3.9.2
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009

Active Python plugins
batchvectorlayersaver
0.9
GroupStats
2.2.7
inspireatomclient
0.8.1
maplibrary
1.3
pdokservicesplugin
5.1.1
pdok_locatieserver_locator_filter
0.2.1
PluginLoadTimes
4.1.0
qgis2web
3.22.0
QNEAT3
1.0.5
quick_map_services
0.19.34
SelectionFilter
1.0
SpreadsheetLayers
2.1.2
wfs_styler
1.0.1
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nyalldawson**
Fixes https://github.com/qgis/QGIS/issues/59237

I don't particularly like this fix, because it requires that EVERY algorithm which uses feature sinks (ie, basically every vector algorithm) should adapt d4d302daedd79b7836634d909264e4e1e702412d manually. Ideas welcome for better approaches...

### CODE REVIEW

File: src/analysis/processing/qgsalgorithmextractbyexpression.cpp [hunk 1]
```diff
@@ -156,6 +156,14 @@ QVariantMap QgsExtractByExpressionAlgorithm::processAlgorithm( const QVariantMap
     }
   }
 
+  if ( matchingSink && !matchingSink->flushBuffer() )
+  {
+    throw QgsProcessingException( matchingSink->lastError() );
+  }
```
Comment (rouault) [inline src/analysis/processing/qgsalgorithmextractbyexpression.cpp:162]: If we have to do that in all algorithms, perhaps have a flushBufferAndThrowProcessingExceptionIfError() method (or if not appropriate in the feature sink class, in some utility class), to be able to do:
```suggestion
  if ( matchingSink )
  {
    matchingSink->flushBufferAndThrowProcessingExceptionIfError();
  }
```

Other idea: have parameterAsSink() return a feature sink that does this if (!flushBufer()) ) throw QgsProcessingException(...) in its destructor.

Comment (nyalldawson) [reply src/analysis/processing/qgsalgorithmextractbyexpression.cpp:162]: @rouault 

> throw QgsProcessingException(...) in its destructor.

That was my original plan, but throwing exceptions is explicitly illegal in destructors. 

Other thoughts I had:

- use the destructor to mark a "throw exception" member in the processing context, and throw the actual exception from elsewhere (pretty messy)
- add some "finalize" method on the sink which flushes the buffer and raises the exception. Algorithms would still need to explicitly call this, but it's a little nicer then flushBuffer calls
- for python we could maybe hack in some __del__ magic in the sink which raises the exception when the python wrapper is deleted (although I'm unsure if the python wrapper is always deleted before the C++ object....)
- ???

Comment (troopa81) [reply src/analysis/processing/qgsalgorithmextractbyexpression.cpp:162]: > add some "finalize" method on the sink which flushes the buffer and raises the exception. Algorithms would still need to explicitly call this, but it's a little nicer then flushBuffer calls

This looks like the appropriate way of doing it. fstream [example](https://stackoverflow.com/questions/130117/if-you-shouldnt-throw-exceptions-in-a-destructor-how-do-you-handle-errors-in-i) looks like very much what we have here, meaning close/finalize would trigger an exception that can be dealt by calling code, but its destructor would not.

Comment (nyalldawson) [reply src/analysis/processing/qgsalgorithmextractbyexpression.cpp:162]: Thanks @troopa81 , that's a valuable link! 

I saw with interest this later reply : https://stackoverflow.com/a/41429901 which looks potentially like a safe way to throw in the destructor. What do you think about that approach? (Also cc @rouault )

Comment (troopa81) [reply src/analysis/processing/qgsalgorithmextractbyexpression.cpp:162]: I have mixed feelings. On one hand it looks like complicated, maybe difficult it debug, a workaround of something set illegal in the language for good reason. On the other hand it solves the issue for all the algorithms, even the python plugin ones, without modifying the algorithms.

So, why not.

Comment (nyalldawson) [reply src/analysis/processing/qgsalgorithmextractbyexpression.cpp:162]: @troopa81 ok, that's a no go -- we can't mark the destructor as noexcept(false) because it overrides the base class destructor and we get ` error: looser exception specification on overriding virtual function ` -- and we can't change the base class destructor unless we change ALL the featuresink subclass destructors to noexcept... and we CAN'T do that because some of them also inherit QObject. :upside_down_face: 

I'll go with explicit finalize calls instead.

**Comment by nyalldawson** [comment]
Ok, this is good to go now

**Review by troopa81 — APPROVED** [review]
