### PR TITLE
Fix missing tiles in 3D view

### LINKED ISSUE #40685: Sometimes tiles in 3d map view are blank until refreshed
**Describe the bug**
Sometimes when using a 3d map view, nothing is rendered in the view, or one of the rendered tiles is blank. Zooming/panning/rotating/resizing the 3d map window refreshes the view and fixes this.
This could be a local issue, not sure.

**How to Reproduce**
1. Open the attached project [tmp_project.zip](https://github.com/qgis/QGIS/files/5721623/tmp_project.zip)
2. Create a new 3d map view
3. The 3d map window is blank.
4. Resize the 3d map view / pan / zoom / rotate camera, and the 3d content is drawn

**QGIS and OS versions**
677ccf5a on debian testing

**Additional context**
This always happens when creating a new view for me, but sometimes, on larger maps, a single 3d tile is left blank in the view.

### LINKED ISSUE #48334: When exporting a 3D animation, terrain tiles go missing on a number of frames
### What is the bug or the crash?

Check this video:

https://user-images.githubusercontent.com/1728657/164850185-c8a9a190-126b-438a-be10-359de5823de7.mp4

You'll notice part of the terrain "flashes" on a number of frames during this video. Here's an example of a few exported frames:

image

You can see frame 54 and 64 have tiles missing. It's not random, if I re-export, the same tiles will go missing for the same frames.

Needless to say, it's not great :)

### Steps to reproduce the issue

1. Create a scene of a few square kilometers
2. Set the terrain to be a DEM layer
3. Make a quick flight over the terrain, export animation
4. Notice the tiles going missing on a number of frames

### Versions

QGIS master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by wonder-sk**
Fixes #48334

With these changes, the test project is not missing any tiles on load, and the animation export also gives correct results.

It turns out this is most likely a Qt3D bug - if an entity is initially added to the scene as disabled, sometimes it does not get shown after enabling it, it need some extra refresh of the scene to actually appear. There does not seem to be any existing Qt3D bug, but there are indications this may be the case:
- https://stackoverflow.com/questions/52424008/qentitys-setenabled-does-not-work-properly-when-entities-are-created-in-a-metho
- https://github.com/florianblume/qt3d-gizmo (see caveats in readme, although that's related to picking)

We work this around by returning enabled 3D entities (actually only DEM-based terrain and flat terrain was returning disabled entities) and that seems to help.

In theory it's not great that we immediately show an entity right after it was created (because the scene may have changed since the time it was requested), but the scene gets updated very soon afterwards anyway.

### CODE REVIEW

**Comment by uclaros** [comment]
This also fixes #40685 for me :)

**Comment by nirvn** [comment]
@wonder-sk , that did fix animation export, nice job. There are still tiles going missing for like 100ms or so while moving around at times, but that's merely flashing while the tile's loading, i.e. it has no impact on exported animations.

**Comment by wonder-sk** [comment]
> There are still tiles going missing for like 100ms or so while moving around at times, but that's merely flashing while the tile's loading, i.e. it has no impact on exported animations.

Yeah I can also see some occasional temporary flashes, but those are likely from a completely different reason... My hypothesis is that this could be caused by some delays when geometry/texture data is still being uploaded to GPU, but that's just a speculation :slightly_smiling_face:

File: src/3d/chunks/qgschunkedentity_p.cpp [hunk 1]
```diff
@@ -534,6 +534,14 @@ void QgsChunkedEntity::onActiveJobFinished()
 
     if ( entity )
     {
+      // The returned QEntity is initially enabled, so let's add it to active nodes too.
+      // Soon afterwards updateScene() will be called, which would remove it from the scene
+      // if the node should not be shown anymore. Ideally entities should be initially disabled,
+      // but there seems to be a bug in Qt3D - if entity is disabled initially, showing it
+      // by setting setEnabled(true) is not reliable (entity eventually gets shown, but only after
+      // some more changes in the scene) - see #48334
```
Comment (uclaros) [inline src/3d/chunks/qgschunkedentity_p.cpp:542]:
```suggestion
      // some more changes in the scene) - see https://github.com/qgis/QGIS/issues/48334
```

**Review by uclaros — APPROVED** [review]
