### PR TITLE
fix TIN interpolation #40668

### LINKED ISSUE #40668: TIN interpolation crashes QGIS or creates empty output
Add the attached line layer

Interpolate the "elevation" attribute using "Break lines" or "structure lines" as type.

QGIS 3.10.12 crashes.

QGIS 3.16.1 creates an empty output.

If using "points" as type works 
[cn.zip](https://github.com/qgis/QGIS/files/5717883/cn.zip)
ok on both versions.

Tested on Windows 10.

### PR DESCRIPTION
**Pull request by vcloarec**
fix #40668
The issue come from that a QgsPoint is not 3D, is stay not 3D even if setZ() is called...

### CODE REVIEW

**Comment by m-kuhn** [comment]
If you use `point.addZValue()` where there's no Z and `setZ` where there is already one, it will be possible to do this more efficiently without a temporary copy.

File: src/analysis/interpolation/qgstininterpolator.cpp [hunk 1]
```diff
@@ -294,14 +294,21 @@ int QgsTinInterpolator::insertData( const QgsFeature &f, QgsInterpolator::ValueS
...
+                  if ( point.is3D() )
+                    point.setZ( attributeValue );
+                  else
+                    point.addZValue( attributeValue );
                   break;
 
-                case ValueZ:
+                case ValueM:
+                  if ( point.is3D() )
+                    point.setZ( point.m() );
```
Comment (m-kuhn) [inline src/analysis/interpolation/qgstininterpolator.cpp:305]: Substituting m with z ison purpose?

Comment (vcloarec) [reply src/analysis/interpolation/qgstininterpolator.cpp:305]: it was here before the fix, so I kept the logic...

**Review by m-kuhn — APPROVED** [review]
