### PR TITLE
[Bugfix] North arrow / image should account for item rotation too.

### LINKED ISSUE #33482: North Arrow - bug when rotating Map in composer
**Describe the bug**
Working with 3.10.1 (ef24c52), Nort arrow does not rotate anymore when rotating map ...

**How to Reproduce**

1. Add map
2. Add arrow
3. Rotate map (here 15°)
4. See error, as below 

image

**QGIS and OS versions**

Version de QGIS | 3.10.1-A Coruña | Révision du code | ef24c526da
-- | -- | -- | --
Compilé avec Qt | 5.12.4 | Utilisant Qt | 5.12.4
Compilé avec GDAL/OGR | 2.4.2 | Utilisé avec GDAL/OGR | 2.4.2
Compilé avec GEOS | 3.7.2-CAPI-1.11.2 | Utilisé avec GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
Version du client PostgreSQL | 11.5 (Ubuntu 11.5-1) | Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.10.4
Compilé avec PROJ | 5.2.0 | Fonctionne avec PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Ubuntu 19.10
Extensions Python actives | VectorBender; AnotherDXF2Shape; mask; Qgis2threejs; GeoCoding; vector_tiles_reader; ORStools; qconsolidate3; shapetools; Hqgis; DataPlotly; french_locator_filter; SRTM-Downloader; Beeline; OSMtools; QNEAT3; loadthemall; db_manager; MetaSearch; processing

### PR DESCRIPTION
**Pull request by roya0045**
## Description
This is my proposal to fix #33482 .

The changes implemented are the following:

Override the rotateitem method in qgslayoutitemmap to add the rotation signal.

Change the mapRotationChanged signals by adding the rotation value of the item.

Backport for 3.10 is suggested.

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `Fixes #11111` at the bottom of the commit message
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit
- [x] I have evaluated whether it is appropriate for this PR to be backported, backport requests are left as label or comment

### CODE REVIEW

**Comment by roya0045** [comment]
PR might not be ready for review, haven't tested, just made it so I don't forget when I get back to work.

File: src/core/layout/qgslayoutitemmap.cpp [hunk 1]
```diff
@@ -447,7 +447,7 @@ void QgsLayoutItemMap::setMapRotation( double rotation )
   mMapRotation = rotation;
   mEvaluatedMapRotation = mMapRotation;
   invalidateCache();
-  emit mapRotationChanged( rotation );
+  emit mapRotationChanged( rotation + itemRotation() );
```
Comment (nyalldawson) [inline src/core/layout/qgslayoutitemmap.cpp]: The mapRotationChanged signal is used quite heavily in other areas of code outside of the north arrow, so I'm reluctant to change it's current behavior here. I'd suggest instead hooking into the existing QgsLayoutItem::rotationChanged signal, i.e. by making the picture item listen out for both the mapRotationChanged AND rotationChanged signals (i.e. adding new connections to rotationChanged wherever QgsLayoutItemPicture currently uses mapRotationChanged )

Also note that you'll need to update QgsLayoutItemPicture::updateMapRotation() -- it doesn't use the rotation value from the mapRotationChanged signal in any case, so it needs to be updated to base the picture orientation on mRotationMap->mapRotation() + mRotationMap->rotation().

**Review by nyalldawson — COMMENTED** [review]
Thanks for working on this one!

File: src/core/layout/qgslayoutitemmap.cpp (hunk 1 above)
Comment (roya0045) [reply src/core/layout/qgslayoutitemmap.cpp]: I'm confused as to why the value provided was useless, I saw the function and thought it was overloaded somewhere else to accept the given value and couldn't find that overloaded method. + the holiday lack of sleep doesn't help. I was debating simply changing the function at first but didn't want to alter some core component if it could be prevented.

File: src/core/layout/qgslayoutitemmap.cpp [hunk 2]
```diff
@@ -2526,3 +2526,10 @@ void QgsLayoutItemMap::createStagedRenderJob( const QgsRectangle &extent, const
   mStagedRendererJob->start();
 }
 
+void QgsLayoutItemMap::rotateItem( const double angle, const QPointF transformOrigin )
```
Comment (nyalldawson) [inline src/core/layout/qgslayoutitemmap.cpp]: This override can be dropped now, it's not required

**Review by nyalldawson — COMMENTED** [review]
Nearly there!

File: src/core/layout/qgslayoutitemmap.cpp (hunk 1 above)
Comment (nyalldawson) [reply src/core/layout/qgslayoutitemmap.cpp]: It's not useless, it's just not used by the north arrow code. Check the QgsLayoutItemPicture::updateMapRotation() slot, it doesn't have an argument accepting the rotation value used in the signal.

**Comment by nyalldawson** [comment]
There's also one connection missed in QgsLayoutItemPicture::finalizeRestoreFromXml()

File: src/core/layout/qgslayoutitempicture.cpp [hunk 3]
```diff
@@ -454,7 +455,7 @@ void QgsLayoutItemPicture::updateMapRotation()
     return;
 
   // take map rotation
-  double rotation = mRotationMap->mapRotation();
+  double rotation = mRotationMap->mapRotation() + mRotationMap->itemRotation();
```
Comment (nyalldawson) [inline src/core/layout/qgslayoutitempicture.cpp]:
```suggestion
  double rotation = mRotationMap->mapRotation() + mRotationMap->rotation();
```

This one is subtle, but check the docs for itemRotation as there's an explanation in those

Comment (roya0045) [reply src/core/layout/qgslayoutitempicture.cpp]: since the only way to access the attribute in the layoutitem was through this I thought it was the only way to get this variable. I forgot to read the doc of the existing variable and only checked the output. My mistake :/

Comment (nyalldawson) [reply src/core/layout/qgslayoutitempicture.cpp]: Totally understandable.. I missed this one too!   It's a rather poor API, but can't be fixed because the underlying qt class method isn't virtual...

**Review by nyalldawson — APPROVED** [review]
