### PR TITLE
Show units instead of a number for the frame_timestep_unit variable

### LINKED ISSUE #49101: frame_timestep_unit variable does not return the actual unit
### What is the bug or the crash?

The frame_timestep_unit variable returns an integer corresponding to the index of the unit (in the temporal controller combobox) instead of the actual unit. Afaics, the other unit-related variables return unit.

### Steps to reproduce the issue

image

### Versions

QGIS 3.25 but applies to elder versions also

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Samweli**
Fixes https://github.com/qgis/QGIS/issues/49101

Changes the stored valued for the `frame_timestep_unit` variable to be a unit.

**Current behaviour**
image

**New behaviour**
image

### CODE REVIEW

**Comment by nyalldawson** [comment]
This risks breaking existing user projects. Could we instead add a new one "frame_timestep_units" and hide the old one (but leave its value unchanged)?

**Comment by Samweli** [comment]
> This risks breaking existing user projects. Could we instead add a new one "frame_timestep_units" and hide the old one (but leave its value unchanged)?

Right!

File: src/core/qgstemporalnavigationobject.cpp [hunk 1]
```diff
@@ -78,6 +78,7 @@ QgsExpressionContextScope *QgsTemporalNavigationObject::createExpressionContextS
   scope->setVariable( QStringLiteral( "frame_duration" ), mFrameDuration, true );
   scope->setVariable( QStringLiteral( "frame_timestep" ), mFrameDuration.originalDuration(), true );
   scope->setVariable( QStringLiteral( "frame_timestep_unit" ), mFrameDuration.originalUnit(), true );
+  scope->setVariable( QStringLiteral( "frame_timestep_units" ), QgsUnitTypes::toString( mFrameDuration.originalUnit() ), true );
```
Comment (nyalldawson) [inline src/core/qgstemporalnavigationobject.cpp:81]: QgsExpressionContext::filteredVariableNames should now strip out the older frame_timestep_unit variable

**Comment by nyalldawson** [comment]
Can you adapt the tests in TestQgsTemporalNavigationObject::expressionContext() to include the new variable please?

**Comment by Samweli** [comment]
> Can you adapt the tests in TestQgsTemporalNavigationObject::expressionContext() to include the new variable please?
Sure, thanks @nyalldawson

File: src/core/qgstemporalnavigationobject.cpp (hunk 1 above)
Comment (Samweli) [reply src/core/qgstemporalnavigationobject.cpp:81]: @nyalldawson I'm not sure how do you want to achieve this, If I add `_` to the start of `frame_timestep_unit` it will be filtered out but the tests coverage for it in `TestQgsTemporalNavigationObject::expressionContext()` will fail!

Comment (nyalldawson) [reply src/core/qgstemporalnavigationobject.cpp:81]: I'd just hardcode "frame_timestep_unit" as an new exception in QgsExpressionContext::filteredVariableNames.

Comment (Samweli) [reply src/core/qgstemporalnavigationobject.cpp:81]: > I'd just hardcode "frame_timestep_unit" as an new exception in QgsExpressionContext::filteredVariableNames.

Right!

Comment (Samweli) [reply src/core/qgstemporalnavigationobject.cpp:81]: @nyalldawson I have provided the change as you requested, I ll be more happy if we had a more robust way for removing variable names when filtering them. I'm planning on making another PR for that if you are okay with that. thanks.

**Review by nyalldawson — APPROVED** [review]
