### PR TITLE
Fix oriented minimum bounding box algorithm

### LINKED ISSUE #33532: Oriented Minimum Bounding Box strange behavior
**Describe the bug**

By running the "Oriented Minimum Bounding Box" algorithm from the Processing Toolbox, on a polygons vector layer, in some (seemingly random) cases, the result is not as expected (it is visibly appreciated that an oriented bounding box of smaller area could be generated). 

By creating a very small decimal radius buffer to the geometries of the problematic features, running the Oriented Minimum Bounding Box algorithm over the resulting geometry, gives the expected result.

**How to Reproduce**

1. Create a feature with the following geometry:  
`Polygon ((264 -525, 248 -521, 244 -519, 233 -508, 231 -504, 210 -445, 196 -396, 180 -332, 178 -322, 176 -310, 174 -296, 174 -261, 176 -257, 178 -255, 183 -251, 193 -245, 197 -243, 413 -176, 439 -168, 447 -166, 465 -164, 548 -164, 552 -166, 561 -175, 567 -187, 602 -304, 618 -379, 618 -400, 616 -406, 612 -414, 606 -420, 587 -430, 575 -436, 547 -446, 451 -474, 437 -478, 321 -511, 283 -521, 275 -523, 266 -525, 264 -525))`  
(Tested in a layer defined in CRS = EPSG:3857, with no projection applied to the project canvas. Although I think it doesn't matter.)  

2. Run the Oriented Minimum Bounding Box algorithm to that feature.  
The output box attributes are: _width = 361.00_, _height = 444.00_, _angle = 90.00_.  

3. Create a Buffer of _Radius = 0.001_ from the original feature.   

4. Run the Oriented Minimum Bounding Box algorithm to the buffered geometry feature.  
The output box attributes are: _width = 417.63_, _height = 298.02_, _angle = 162.68_.   

The area of the box returned by the buffered geometry feature is smaller than that returned by the original one.

**QGIS and OS versions**

QGIS version 3.10.1-A Coruña
Windows 10, 64bit (OSGeoo4W installation).

### PR DESCRIPTION
**Pull request by lbartoletti**
## Description

Fixes #33532

### CODE REVIEW

File: src/core/geometry/qgsgeometry.cpp [hunk 1]
```diff
@@ -1000,7 +1000,7 @@ QgsGeometry QgsGeometry::orientedMinimumBoundingBox( double &area, double &angle
       height = bounds.height();
     }
 
-    pt2 = pt1;
+    pt1 = pt2;
```
Comment (nyalldawson) [inline src/core/geometry/qgsgeometry.cpp]: Ouch, nice fix!

(Funny story -- I ran into this bug a while ago, and for the last 2 years I've had a set of 6 tabs open on my phone researching alternative OMBB algorithms which I planned to get to "some time". Thanks for allowing me to finally close these tabs :wink:  )

Comment (lbartoletti) [reply src/core/geometry/qgsgeometry.cpp]: Thanks. :)

I spent more than 4 hours looking for an alternative; I thought there was a bug in the function when the tested points were orthogonal. When I came back with my coffee... I saw this... :laughing:

Comment (nyalldawson) [reply src/core/geometry/qgsgeometry.cpp]: Well, you beat me by 1.98904836 years :smile:
