### PR TITLE
Exclude virtualraster from processing raster input

### LINKED ISSUE #55890: Raster Calculator Raster Menu - on the fly layer name gives issues
### What is the bug or the crash?

The raster calculater in the Raster menu gives a layer name/source filename with "illigeal" charcters for "terraen_volumen@1" >= 4 if using "On-the-fly-raster"
The filename takes the expression as name both as layer name and in the source.
Renaming the layer does not have any effect, because it is the source that are used in further calculations ex. Clip Raster.
In the following 3 dialogs I have used the original layer name with the expression layer name. In dialog 4 I have renamed the layer to easy_name, and the run the clip raster. The result/error is shown in yellow.

dialog1

dialog 2

dialog 3

dialog4

### Steps to reproduce the issue

Description in dialog images

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.0-Prizren | QGIS code revision | ffbdd67881
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.2
PROJ version | 9.3.0
EPSG Registry database version | v10.094 (2023-08-08)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.41.1
PDAL version | 2.5.5
PostgreSQL client version | 15.2
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.4
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
AddressToolsDK | 0.1
Dataforsyningen | 0.4
DigitizingTools | 1.5.2
dmpcatalogue | 1.1.1
geosearch_dk | 2.0.0
Mergin | 2023.4.1
processing_saga_nextgen | 1.0.0
StreetView | 3.2
valuetool | 3.0.17
view_drone | 0.3
processing | 2.12.99

</body></html>QGIS version
3.34.0-Prizren
QGIS code revision
[ffbdd67881](https://github.com/qgis/QGIS/commit/ffbdd67881)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.2
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
AddressToolsDK
0.1
Dataforsyningen
0.4
DigitizingTools
1.5.2
dmpcatalogue
1.1.1
geosearch_dk
2.0.0
Mergin
2023.4.1
processing_saga_nextgen
1.0.0
StreetView
3.2
valuetool
3.0.17
view_drone
0.3
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Also add a tooltip.

Fixes #55890

There is a chance that "qgis" and "native" algorithms can handle virtual rasters but other almost certainly cannot
so we exclude them from the list of available layers for processing algorithms

### CODE REVIEW

File: src/gui/processing/qgsprocessingmaplayercombobox.cpp [hunk 1]
```diff
@@ -180,8 +187,19 @@ QgsProcessingMapLayerComboBox::QgsProcessingMapLayerComboBox( const QgsProcessin
 
   if ( filters )
     mCombo->setFilters( filters );
+
   mCombo->setExcludedProviders( QStringList() << QStringLiteral( "grass" ) ); // not sure if this is still required...
 
+  // see https://github.com/qgis/QGIS/issues/55890
+  // There is a chance that "qgis" algorithms can handle virtual rasters but other almost certainly cannot
+  // so we exclude them from the list of available layers for processing algorithms
+  const QStringList providersCompatibleWithVirtualRaster {{ QStringLiteral( "qgis" ), QStringLiteral( "native" ) }};
```
Comment (nyalldawson) [inline src/gui/processing/qgsprocessingmaplayercombobox.cpp:196]: instead of hardcoding this logic here, could we make it a virtual method in QgsProcessingProvider ? It could even be a new QgsProcessingProvider::Flag value.

Comment (elpaso) [reply src/gui/processing/qgsprocessingmaplayercombobox.cpp]: Done

**Review by nyalldawson — APPROVED** [review]

**Comment by DelazJ** [comment]
Is this backportable as is, for fixing the issue in 3.34 LTR?
