### PR TITLE
Fix #47089 wrong rotation point for rotate label tool preview

### LINKED ISSUE #47089: Label Rotate Tool uses wrong rotation point for preview by Offset from poin placement mode
### What is the bug or the crash?

For label placed with mode "Offset from Point" the preview shown by the label rotate tool use the wrong rotation point if the quadrant is different than `AboveRight`
LabelRotateWrongStartPoint

### Steps to reproduce the issue

1. Open attached project
2. Digitize one point
3. Rotate the label wit `Rotate a label` tool

[LabelTurnPoint.zip](https://github.com/qgis/QGIS/files/7970005/LabelTurnPoint.zip)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.23.0-Master | QGIS code revision | 304475806f
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.8.12
GDAL/OGR version | 3.4.1
PROJ version | 8.2.0
EPSG Registry database version | v10.038 (2021-10-21)
GEOS version | 3.10.1-CAPI-1.16.0
SQLite version | 3.37.1
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.2.0
QScintilla2 version | 2.13.1
OS version | openSUSE Tumbleweed
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
plugin_reloader | 0.8.2
quick_map_services | 0.19.19
document_management_system | dev
QgisModelBaker | dev
firstaid | 2.1.5
enhanced_relation_editor_widget | dev
processing | 2.12.99
grassprovider | 2.12.99
MetaSearch | 0.3.6
db_manager | 0.1.20

</body></html>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by domi4484**
Fix #47089 wrong rotation point for rotate label tool preview

### CODE REVIEW

File: src/app/labeling/qgsmaptoollabel.cpp [hunk 1]
```diff
@@ -335,25 +335,84 @@ QString QgsMapToolLabel::currentLabelText( int trunc )
...
+    QString hali = QStringLiteral( "Left" );
+    QString vali = QStringLiteral( "Bottom" );
+    hali = evaluateDataDefinedProperty( QgsPalLayerSettings::Hali, mCurrentLabel.settings, f, hali ).toString();
+    vali = evaluateDataDefinedProperty( QgsPalLayerSettings::Vali, mCurrentLabel.settings, f, vali ).toString();
+
+    if ( hali.compare( QLatin1String( "Left" ), Qt::CaseInsensitive ) == 0 )
+    {
+      if ( vali.compare( QLatin1String( "Top" ), Qt::CaseInsensitive ) == 0 || vali.compare( QLatin1String( "Cap" ), Qt::CaseInsensitive ) == 0 )
+        quadrantPosition = QgsPalLayerSettings::QuadrantBelowRight;
+      else if ( vali.compare( QLatin1String( "Half" ), Qt::CaseInsensitive ) == 0 )
```
Comment (nyalldawson) [inline src/app/labeling/qgsmaptoollabel.cpp:390]: There's also the "Cap" mode -- this isn't the same as half, and unfortunately doesn't map to an existing quadrant value.

Potentially the quadrant enum could be extended to include the cap based placements....

Comment (domi4484) [reply src/app/labeling/qgsmaptoollabel.cpp:390]: Oh I see, in the current implementation `Top` and `Cap` where treated in one block so I assumed they were the same.

Instead of extending the enum i would rename this function to `currentAlignmentOffset` and return directly `xdiff` and `ydiff`.

Comment (domi4484) [reply src/app/labeling/qgsmaptoollabel.cpp:424]: @nyalldawson I was feeling wrong adding the Cap/Base alignments to an enum called "Quadrant". I added a new Alignment enum to QgsMapToolLabel for internal use. Are you ok with this?

**Comment by nyalldawson** [comment]
Let's delay this till after 3.24.0 final to be safe. It's not a new regression, so the risk outweighs the reward of a merge at this stage.

**Comment by 3nids** [comment]
any objection to merge this one?

File: tests/src/app/testqgsmaptoollabel.cpp [hunk 2]
```diff
@@ -298,10 +298,8 @@ class TestQgsMapToolLabel : public QObject
       tool->mCurrentLabel = QgsMapToolLabel::LabelDetails( pos, canvas.get() );
 
       // defaults to bottom left
-      QString hali, vali;
-      tool->currentAlignment( hali, vali );
-      QCOMPARE( hali, QStringLiteral( "Left" ) );
-      QCOMPARE( vali, QStringLiteral( "Bottom" ) );
+      QgsMapToolLabel::LabelAlignment labelAlignment = tool->currentAlignment();
+      QCOMPARE( labelAlignment, QgsMapToolLabel::LabelAlignment::HalfCenter );
```
Comment (nyalldawson) [inline tests/src/app/testqgsmaptoollabel.cpp:302]: Can you explain why this result has changed from bottom left to half center?

**Comment by nyalldawson** [comment]
Looks good to me -- I've just the one question about why the existing test result has changed

File: tests/src/app/testqgsmaptoollabel.cpp (hunk 2 above)
Comment (domi4484) [reply tests/src/app/testqgsmaptoollabel.cpp:302]: Yes, this is because the former implementation was just ignoring the `quadOffset` property as of line 271. I should change the comment anyway.
Effectively if I pythonize this code and execute in QGIS the label at the beginning is aligned half center and not bottom left.

**Review by nyalldawson — APPROVED** [review]
