### PR TITLE
Limit number of rows for Postgis retrieveLayerTypes

### LINKED ISSUE #39897: Viewing table fields in PostGIS browser shows hourglass for 15 minutes
**Describe the bug**
I have various PostgreSQL databases with many millions of objects and with QGIS 3.16 when using the PostGIS dataprovider for inspecting tables/fields it takes over 15 minutes for each table to open.

The reason is that the whole table is read to determine the geometry types.

"Don't resolve type of unrestricted colums" or "use estimated metadata" makes no difference.

**How to Reproduce**

1. Create PostgreSQL table with millions of object which have a generic `Geometry` attribute
2. Inspect the table (see screenshot) and get a long running hourglass:

Screenshot from 2020-11-06 08-41-34

**QGIS and OS versions**

3.16

**Additional context**

See #39885 for a potential fix

### PR DESCRIPTION
**Pull request by tomtor**
When PostgreSQL databases have many millions of objects with a geometry attribute
the PostGIS dataprovider for inspecting tables/fields takes over 15 minutes for each table to open.

The reason is that whole tables are read to determine the geometry types.

This commit only inspects the first GEOM_TYPE_SELECT_LIMIT rows

Fixes #39897

## Description

[Replace this with some text explaining the rationale and details about this pull request]

### CODE REVIEW

File: src/providers/postgres/qgspostgresconn.cpp [hunk 1]
```diff
@@ -1924,7 +1924,17 @@ void QgsPostgresConn::retrieveLayerTypes( QVector<QgsPostgresLayerProperty *> &l
 
       sql += QLatin1String( ") " );
 
-      sql += " FROM " + table;
+      if ( type == QgsWkbTypes::Unknown )
```
Comment (rouault) [inline src/providers/postgres/qgspostgresconn.cpp:1927]: this looks a bit convoluted to me. There might perhaps be a good reason, but why not just appending ``QStringLiteral(" LIMIT %1").arg( GEOM_TYPE_SELECT_LIMIT )`` after the existing ``sql += " FROM " + table;`` ?
I'm not clear why the restriction is only when the layer geometry type is unknown. Wouldn't the issue also occur with big tables of known geometry type ?

Comment (tomtor) [reply src/providers/postgres/qgspostgresconn.cpp:1927]: The point is:

https://github.com/qgis/QGIS/blob/6ae5d22f1da6ddf8c518919d7b5b36cfad5a3d3e/src/providers/postgres/qgspostgresconn.cpp#L1893

and
https://github.com/qgis/QGIS/blob/6ae5d22f1da6ddf8c518919d7b5b36cfad5a3d3e/src/providers/postgres/qgspostgresconn.cpp#L1912

https://github.com/qgis/QGIS/blob/6ae5d22f1da6ddf8c518919d7b5b36cfad5a3d3e/src/providers/postgres/qgspostgresconn.cpp#L1914

Only for unknown geometry the `array_agg` is performed on the WHOLE table for `UPPER(geometry)`, else its performed on static texts.
We would like to apply the `limit` to the `array_agg` but SQL does not allow this.

Appending the LIMIT would still query the whole table.

Comment (rouault) [reply src/providers/postgres/qgspostgresconn.cpp:1927]: thanks for the explanations. Maybe adding a bit of comment in the code would help future readers

Comment (tomtor) [reply src/providers/postgres/qgspostgresconn.cpp:1927]: @rouault Yes, I will add some comments

**Review by elpaso — APPROVED** [review]
