### PR TITLE
Fix building with llvm13

### LINKED ISSUE #46406: failure to build with llvm 13
### What is the bug or the crash?

building with llvm 13 on OpenBSD; the build fails with:
```
/usr/obj/ports/qgis-3.22.1/qgis-3.22.1/src/core/providers/ogr/qgsogrproviderutils.cpp:2595:34: error: no matching constructor for initialization of 'QgsOgrDatasetSharedPtr' (aka 'shared_ptr<QgsOgrDataset>')
  QgsOgrDatasetSharedPtr dsRet = QgsOgrDatasetSharedPtr( new QgsOgrDataset(), QgsOgrProviderUtils::releaseDataset );
                                 ^                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/v1/__memory/shared_ptr.h:469:26: note: candidate constructor template not viable: no known conversion from 'QgsOgrDataset *' to 'std::nullptr_t' (aka 'nullptr_t') for 1st argument
    template <class _Dp> shared_ptr(nullptr_t __p, _Dp __d);
                         ^
/usr/include/c++/v1/__memory/shared_ptr.h:464:9: note: candidate template ignored: requirement '__shared_ptr_deleter_ctor_reqs<void (*)(QgsOgrDataset *&), QgsOgrDataset, QgsOgrDataset>::value' was not satisfied [with _Yp = QgsOgrDataset, _Dp = void (*)(QgsOgrDataset *&)]
        shared_ptr(_Yp* __p, _Dp __d,
        ^
/usr/include/c++/v1/__memory/shared_ptr.h:471:51: note: candidate template ignored: could not match 'shared_ptr<type-parameter-0-0>' against 'QgsOgrDataset *'
    template<class _Yp> _LIBCPP_INLINE_VISIBILITY shared_ptr(const shared_ptr<_Yp>& __r, element_type* __p) _NOEXCEPT;
                                                  ^
/usr/include/c++/v1/__memory/shared_ptr.h:476:9: note: candidate template ignored: could not match 'shared_ptr<type-parameter-0-0>' against 'QgsOgrDataset *'
        shared_ptr(const shared_ptr<_Yp>& __r,
        ^
/usr/include/c++/v1/__memory/shared_ptr.h:481:52: note: candidate template ignored: could not match 'shared_ptr<type-parameter-0-0>' against 'QgsOgrDataset *'
    template<class _Yp> _LIBCPP_INLINE_VISIBILITY  shared_ptr(shared_ptr<_Yp>&& __r,
                                                   ^
/usr/include/c++/v1/__memory/shared_ptr.h:484:34: note: candidate template ignored: could not match 'weak_ptr<type-parameter-0-0>' against 'QgsOgrDataset *'
    template<class _Yp> explicit shared_ptr(const weak_ptr<_Yp>& __r,
                                 ^
/usr/include/c++/v1/__memory/shared_ptr.h:488:9: note: candidate template ignored: could not match 'auto_ptr<type-parameter-0-0>' against 'QgsOgrDataset *'
        shared_ptr(auto_ptr<_Yp>&& __r,
        ^
/usr/include/c++/v1/__memory/shared_ptr.h:492:9: note: candidate template ignored: could not match 'unique_ptr<type-parameter-0-0, type-parameter-0-1>' against 'QgsOgrDataset *'
        shared_ptr(unique_ptr<_Yp, _Dp>&&,
        ^
/usr/include/c++/v1/__memory/shared_ptr.h:500:9: note: candidate template ignored: could not match 'unique_ptr<type-parameter-0-0, type-parameter-0-1>' against 'QgsOgrDataset *'
        shared_ptr(unique_ptr<_Yp, _Dp>&&,
        ^
/usr/include/c++/v1/__memory/shared_ptr.h:441:23: note: candidate constructor not viable: requires 1 argument, but 2 were provided
    _LIBCPP_CONSTEXPR shared_ptr(nullptr_t) _NOEXCEPT;
                      ^
/usr/include/c++/v1/__memory/shared_ptr.h:454:14: note: candidate constructor template not viable: requires single argument '__p', but 2 arguments were provided
    explicit shared_ptr(_Yp* __p) : __ptr_(__p) {
             ^
/usr/include/c++/v1/__memory/shared_ptr.h:473:5: note: candidate constructor not viable: requires single argument '__r', but 2 arguments were provided
    shared_ptr(const shared_ptr& __r) _NOEXCEPT;
    ^
/usr/include/c++/v1/__memory/shared_ptr.h:480:5: note: candidate constructor not viable: requires single argument '__r', but 2 arguments were provided
    shared_ptr(shared_ptr&& __r) _NOEXCEPT;
    ^
/usr/include/c++/v1/__memory/shared_ptr.h:470:40: note: candidate constructor template not viable: requires 3 arguments, but 2 were provided
    template <class _Dp, class _Alloc> shared_ptr(nullptr_t __p, _Dp __d, _Alloc __a);
                                       ^
/usr/include/c++/v1/__memory/shared_ptr.h:439:23: note: candidate constructor not viable: requires 0 arguments, but 2 were provided
    _LIBCPP_CONSTEXPR shared_ptr() _NOEXCEPT;
                      ^
/usr/include/c++/v1/__memory/shared_ptr.h:467:9: note: candidate constructor template not viable: requires at least 3 arguments, but 2 were provided
        shared_ptr(_Yp* __p, _Dp __d, _Alloc __a,
```

### Steps to reproduce the issue

try to build with llvm 13 

### Versions

3.22.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rhurlin**
## Description

Since llvm13, the build is broken with:
```
/usr/ports/graphics/qgis/work/QGIS-final-3_22_1/src/core/providers/ogr/qgsogrproviderutils.cpp:2595:34: error: no matching constructor for initialization of 'QgsOgrDatasetSharedPtr' (aka 'shared_ptr<QgsOgrDataset>')
      QgsOgrDatasetSharedPtr dsRet = QgsOgrDatasetSharedPtr( new QgsOgrDataset(), QgsOgrProviderUtils::releaseDataset );
```

This was solved for FreeBSD with commit https://github.com/freebsd/freebsd-ports/commit/eacf34a1cf4b6b81e54d4fe74ad931ee93d1d8ef

Fixes #46406

### CODE REVIEW

**Review by lbartoletti — APPROVED** [review]

File: src/core/providers/ogr/qgsogrproviderutils.cpp [hunk 1]
```diff
@@ -2337,15 +2337,14 @@ void QgsOgrProviderUtils::release( QgsOgrLayer *&layer )
...
-void QgsOgrProviderUtils::releaseDataset( QgsOgrDataset *&ds )
+void QgsOgrProviderUtils::releaseDataset( QgsOgrDataset *ds )
 {
   if ( !ds )
     return;
 
   QMutexLocker locker( sGlobalMutex() );
   releaseInternal( ds->mIdent, ds->mDs, true );
   delete ds;
-  ds = nullptr;
```
Comment (nyalldawson) [inline src/core/providers/ogr/qgsogrproviderutils.cpp:2348]: This is not quite the same meaning. Are you sure it won't lead to use after free errors?

Comment (lbartoletti) [reply src/core/providers/ogr/qgsogrproviderutils.cpp:2348]: I don't think so. Same point of view as @m-kuhn : https://github.com/qgis/QGIS/pull/46409#issuecomment-988680806

BTW, we have not experienced any crash with this patch on FreeBSD.
