### PR TITLE
Get the username from current_user to fill layer_styles' owner field for Postgresql based connections

### LINKED ISSUE #32133: Owner not recorded in layer_styles when using Postgresql service based connections
**Describe the bug**

Styles can be saved in Postgresql (and using other providers, as well). When saved, the username used in the connection is stored in the `owner` field, in the table `layer_styles`.

If the Postgresql connection is based on [services](https://docs.qgis.org/testing/en/docs/user_manual/managing_data_source/opening_data.html#postgresql-service-connection-file), the username is not available from `QgsDataSourceUri`. **No information about the `owner` is stored in `layer_styles` in such case.**

**How to Reproduce**

* Create a connection based on pg_services.
* Store a style on the database
* The `owner` field is empty.

no owner using pg_services

**QGIS and OS versions**

QGIS 3.4, QGIS 3.8 and master

**Solution**

PR under preparation

### PR DESCRIPTION
**Pull request by jgrocha**
## Description

Fix #32133.

For connections using pg_services the connection's username can be retrieved using `CURRENT_USER` on the server side. This works for any kind of Postgresql connection, since it is managed on the Postgresql server side.

The DDL changed to:

```sql
    QgsPostgresResult res( conn->PQexec( "CREATE TABLE layer_styles("
                                         "id SERIAL PRIMARY KEY"
                                         ",f_table_catalog varchar"
                                         ",f_table_schema varchar"
                                         ",f_table_name varchar"
                                         ",f_geometry_column varchar"
                                         ",styleName text"
                                         ",styleQML xml"
                                         ",styleSLD xml"
                                         ",useAsDefault boolean"
                                         ",description text"
                                         ",owner varchar(63) DEFAULT CURRENT_USER"
                                         ",ui xml"
                                         ",update_time timestamp DEFAULT CURRENT_TIMESTAMP"
                                         ")" ) );
```

Both INSERT and UPDATE queries will set `owner` to `CURRENT_USER`. This supports previous lay_styles tables without the `owner` default value set.

## Checklist

- [X] Commit messages are descriptive and explain the rationale for changes
- [X] Commits which fix bugs include `Fixes #11111` at the bottom of the commit message
- [X] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] New unit tests have been added for core changes
- [X] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit
- [ ] I have evaluated whether it is appropriate for this PR to be backported, backport requests are left as label or comment

### CODE REVIEW

File: src/providers/postgres/qgspostgresprovider.cpp [hunk 1]
```diff
@@ -4759,9 +4759,9 @@ bool QgsPostgresProviderMetadata::saveStyle( const QString &uri, const QString &
   // two values are both replaced in the final .arg call of the string construction.
 
   QString sql = QString( "INSERT INTO layer_styles("
-                         "f_table_catalog,f_table_schema,f_table_name,f_geometry_column,styleName,styleQML,styleSLD,useAsDefault,description,owner%11"
+                         "f_table_catalog,f_table_schema,f_table_name,f_geometry_column,styleName,styleQML,styleSLD,useAsDefault,description%11"
                          ") VALUES ("
-                         "%1,%2,%3,%4,%5,XMLPARSE(DOCUMENT %16),XMLPARSE(DOCUMENT %17),%8,%9,%10%12"
```
Comment (jef-n) [inline src/providers/postgres/qgspostgresprovider.cpp]: Why not just set `owner` to `current_user` instead of the uri param with current user?  If the table already exists the new default won't be set.

Comment (jgrocha) [reply src/providers/postgres/qgspostgresprovider.cpp]: Thanks @jef-n for the review.

Really helpful your suggestion! It supports old `layer_styles` tables, with the default value declared. Implemented, as suggested.

**Comment by jgrocha** [comment]
@jef-n Can you review this PR again? Do you think it is ok to merge?
