### PR TITLE
Fix #47569. Unable to copy data stored in JSON and list fields

### LINKED ISSUE #47569: Unable to copy data stored in `JSON` fields in the attribute table
### What is the bug or the crash?

When copying data stored in `json` format (recently appeared in QGIS) - the data of this field remain empty.

### Steps to reproduce the issue

1. Download this geopackage file: [test data.zip](https://github.com/qgis/QGIS/files/8152910/test.data.zip).
2. Open the attrubute table.
3. Copy all data (using Ctrl+C or corresponding button).
4. Paste the results into notepad.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.0-Tisler | QGIS code revision | 6b44a42058
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
AppendFeaturesToLayer | 1.2.0
DigitizingTools | 1.5.1
Go2NextFeature3 | 2.1
latlontools | 3.6.2
loadthemall | 3.3.0
MapsPrinter | 0.9
PluginLoadTimes | 3.0.1
qgsAzimuth | 0.9.15
rasterstats | 0.4.3
valuetool | 3.0.15
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
otbprovider | 2.12.99
processing | 2.12.99

</body></html>QGIS version
3.24.0-Tisler
QGIS code revision
[6b44a42058](https://github.com/qgis/QGIS/commit/6b44a42058)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
AppendFeaturesToLayer
1.2.0
DigitizingTools
1.5.1
Go2NextFeature3
2.1
latlontools
3.6.2
loadthemall
3.3.0
MapsPrinter
0.9
PluginLoadTimes
3.0.1
qgsAzimuth
0.9.15
rasterstats
0.4.3
valuetool
3.0.15
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

notepad++_AfU3fj3Cds

### PR DESCRIPTION
**Pull request by ismailsunni**
## Description

Fix #47569. Unable to copy data stored in JSON and list fields

Peek 2022-03-08 17-59 - fix copy json and list attribute

Funded by Camptocamp https://www.camptocamp.com/

### CODE REVIEW

**Comment by ismailsunni** [comment]
It seems the failed test in unrelated with the PR.

File: src/app/qgsclipboard.cpp [hunk 1]
```diff
@@ -131,14 +133,15 @@ void QgsClipboard::generateClipboardText( QString &textContent, QString &htmlCon
 
         for ( int idx = 0; idx < attributes.count(); ++idx )
         {
-          QString value = attributes.at( idx ).toString();
+          QString value = QString::fromStdString( QgsJsonUtils::jsonFromVariant( attributes.at( idx ) ).dump() );
```
[the remark this answers is not in the document]
Comment (ismailsunni) [reply src/app/qgsclipboard.cpp:136]: The diference is, in v3.24 all is copied without `"`, e.g.
```
wkt_geom	date	datetime	integerlist	decimallist	stringlist2	stringlist	integerlist2	decimallist2	integer	string
Point (7.60173582322795571 51.9631281667119751)	2022-02-22	04:00:00.000							4	abc
```
While with that jsonFromVariant, all except the number is copied with `"`
```
wkt_geom	date	datetime	integerlist	decimallist	stringlist2	stringlist	integerlist2	decimallist2	integer	string
Point (7.60173582322795571 51.9631281667119751)	"2022-02-22"	"04:00:00.000"	[2,1]	[0.9,0.0]	["c","b","a"]	["a","b","c"]	[2,1]	[0.9,0.0]	4	"abc"
```

The second one seems more consistent. We can differentiate a number and non-number here.

But after reading your comment, perhaps the original purpose is to copy the value without the `"`. Is that correct? If so, I will update it. But not sure how it works with JSON data type. Should it include the full format like:
```
{"date":"3333","def":"ghi","test":"abc"}
```
or a simple one:
```
date: 3333, def: ghi, test: abc
``` 

Thanks for the feedback!

[the remark this answers is not in the document]
Comment (ismailsunni) [reply src/app/qgsclipboard.cpp]: Hi @nyalldawson, after some thought, I decided to only use JSON-way if it's not convertible to String. Below are some examples:
```
wkt_geom	fid	json	val
Point (-0.7402777777777777 0.625)	1	{"date":"3333","def":"ghi","test":"abc"}	11111

wkt_geom	date	datetime	integerlist	decimallist	stringlist2	stringlist	integerlist2	decimallist2	integer	string
Point (7.60227984718220906 51.96190223848584822)	2022-03-02	00:00:00.000	[3,2,1]	[8.0,0.0]	["c","b","a"]	["z","y","x"]	null	[8.0,0.0]	1	ghi
```

I think it makes sense since we only want to copy the value, but for JSON and list, we still get the `"` char to differentiate between string or non-string (and make the JSON format valid)

File: src/app/qgsclipboard.cpp [hunk 2]
```diff
@@ -131,14 +133,30 @@ void QgsClipboard::generateClipboardText( QString &textContent, QString &htmlCon
 
         for ( int idx = 0; idx < attributes.count(); ++idx )
         {
-          QString value = attributes.at( idx ).toString();
+          QString value;
+          if ( attributes.at( idx ).canConvert( QVariant::String ) )
```
Comment (nyalldawson) [inline src/app/qgsclipboard.cpp:137]: canConvert is unfortunately not safe to use here -- the definition has changed in Qt6 from "i definitely CAN represent this value as a string" to "it's theoretical possible to create a string value here regardless of what the variant type is" . 

So for Qt 6 builds a list variant will return true for canConvert( QVariant::String ). 

I think you'll need to invert this logic, and have a hardcoded list of types which you want to format as json. I.e. QVariant::StringList, QVariant::List, QVariant::Map. And for the rest fallback to the toString() method.

File: src/app/qgsclipboard.cpp [hunk 3]
```diff
@@ -131,14 +133,34 @@ void QgsClipboard::generateClipboardText( QString &textContent, QString &htmlCon
 
         for ( int idx = 0; idx < attributes.count(); ++idx )
         {
-          QString value = attributes.at( idx ).toString();
+          QString value;
+          QVariant variant = attributes.at( idx );
+          bool useJSONFromVariant = variant.canConvert( QVariant::StringList ) || variant.canConvert( QVariant::List ) || variant.canConvert( QVariant::Map );
+          useJSONFromVariant = useJSONFromVariant && ( variant.type() != QVariant::String ); // String is convertible to StringList, but we want to use toString for String variant
```
Comment (nyalldawson) [inline src/app/qgsclipboard.cpp:139]:
```suggestion
          const bool useJSONFromVariant = variant.type() == QVariant::StringList || variant.type() == QVariant::List || variant.type() == QVariant::Map;
```

Basically, canConvert is a no-go now. We shouldn't use it anywhere anymore.

**Review by nyalldawson — APPROVED** [review]

File: src/app/qgsclipboard.cpp (hunk 3 above)
Comment (ismailsunni) [reply src/app/qgsclipboard.cpp]: ah thanks, I misunderstood your previous comment.
