### PR TITLE
Macos fixes

### LINKED ISSUE #52389: No render of QML widget on MacOS
### What is the bug or the crash?

When creating a form with a QML widget, no render of the QML code is done **under MacOS** (neither while creating/editing the code of the widget nor while rendering the form).
Works on Windows with the same .qgs project / QML code.

### Steps to reproduce the issue

Create a form in drag/drop mode.
Add a QML Widget, and open it to edit its code.
No render is done no matter what the code is, even presets code. Render window stays blank. OK to close the window.
No render is done in form in the space dedicated to the widget (other form datas appear well).

On Windows, the same steps work as expected. Rendering works even from a QML code created under MacOS.

### Versions

QGis 3.26.0-Buenos Aires and 3.28.4-Firenze (LTR)
(Qt 5.12.2)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

No warning in QGis log console.
On the same Mac computer, with another app which is able to read .qgs files (QField for MacOS), the rendering of the form with the QML code works well.

### LINKED ISSUE #59979: No preview in Attribute form QML dialog
### What is the bug or the crash?

Vector layer properties --> Form attributes --> Drag-and-drop, and add a QML widget
Switch to a "Rectangle" type, and you'd see on the right a blue rectangle, corresponding to the code in the text box.
Switch now to "Pie chart" or "Bar chart" and you'll notice that, despite the code updated in the text box, nothing happens on the right side

Peek 20-12-2024 01-52

### Steps to reproduce the issue

See above.
For information, this is how it used to work (from #7801)
45079754-9cdbeb80-b0f3-11e8-8dba-3e02f0351517

### Versions

Issue also already met on an earlier version, with macOS

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.41.0-Master</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/992ccc92939">992ccc92939</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.8</td></tr><tr><td>Python version</td><td>3.11.2</td></tr><tr><td>GDAL/OGR version</td><td>3.6.2</td></tr><tr><td>PROJ version</td><td>9.1.1</td></tr><tr><td>EPSG Registry database version</td><td>v10.076 (2022-08-31)</td></tr><tr><td>GEOS version</td><td>3.11.1-CAPI-1.17.1</td></tr><tr><td>SQLite version</td><td>3.40.1</td></tr><tr><td>PDAL version</td><td>2.6.0</td></tr><tr><td>PostgreSQL client version</td><td>15.10 (Debian 15.10-0+deb12u1)</td></tr><tr><td>SpatiaLite version</td><td>5.0.1</td></td></tr><tr><td>QWT version</td><td>6.1.4</td></tr><tr><td>QScintilla2 version</td><td>2.13.3</td></tr><tr><td>OS version</td><td>Debian GNU/Linux 12 (bookworm)</td></tr><tr><td colspan="2"><i>This copy of QGIS writes debugging output.</i></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### LINKED ISSUE #64374: macOS: qgis_process does not work
### What is the bug or the crash?

The ‘qgis_process’ executable still does not work. When executed, library addressing errors occur.

```
% /Applications/QGIS.app/Contents/MacOS/qgis_process plugins

proj_get_authorities_from_database: Cannot find proj.db

Couldn't load Python support library: Cannot load library /Applications/QGIS.app/Contents/Contents/Frameworks/qgispython: (dlopen(/Applications/QGIS.app/Contents/Contents/Frameworks/libqgispython.dylib, 0x000A): tried: '/ Applications/QGIS.app/Contents/Contents/Frameworks/libqgispython.dylib' (no such file), ‘/System/Volumes/Preboot/Cryptexes/OS/Applications/QGIS.app/Contents/Contents/Frameworks/libqgispython.dylib’ (no such file), '/Applications/QGIS.app/Contents/Contents/Frameworks/libqgispython.dylib' (no such file))

```

### Steps to reproduce the issue

QGIS 3.44.6 - macOS version

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.44.6-Solothurn</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/386cd767">386cd767</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.18</td></tr><tr><td>Python version</td><td>3.12.11</td></tr><tr><td>GDAL version</td><td>3.12.0 — <i>Chicoutimi</i></td></tr><tr><td>PROJ version</td><td>9.7.0</td></tr><tr><td>EPSG Registry database version</td><td>v12.022 (2025-08-30)</td></tr><tr><td>GEOS version</td><td>3.14.1-CAPI-1.20.5</td></tr><tr><td>SQLite version</td><td>3.50.4</td></tr><tr><td>PDAL version</td><td>2.9.2</td></tr><tr><td>PostgreSQL client version</td><td>16.9</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.2.1</td></tr><tr><td>QScintilla2 version</td><td>2.13.4</td></tr><tr><td>OS version</td><td>macOS 15.7</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>qwc2_tools</td><td>1.4.3</td></tr><tr><td>models2plugin</td><td>latest</td></tr><tr><td>wbt_for_qgis</td><td>1.0.9</td></tr><tr><td>ee_plugin</td><td>0.1.6</td></tr><tr><td>quick_map_services</td><td>1.1.0</td></tr><tr><td>QGIS2VectorTiles</td><td>1.1</td></tr><tr><td>AttributeTransferTool</td><td>1.0.0</td></tr><tr><td>orfeoToolbox_provider</td><td>3.0.3</td></tr><tr><td>hypercoast</td><td>0.2.0</td></tr><tr><td>scipy_filters</td><td>1.99</td></tr><tr><td>whitebox_workflows_for_qgis</td><td>1.2.6</td></tr><tr><td>ArcGeekCalculator</td><td>4.0.3</td></tr><tr><td>modeler_search_enhancer</td><td>1.2</td></tr><tr><td>processing_saga_nextgen</td><td>1.1.0</td></tr><tr><td>qgis2web</td><td>3.31.0</td></tr><tr><td>processing_r</td><td>4.1.0</td></tr><tr><td>qfieldsync</td><td>v4.17.3</td></tr><tr><td>dzetsaka</td><td>4.2.2</td></tr><tr><td>custom_map_downloader</td><td>0.1.1</td></tr><tr><td>TerraClimateDownloader</td><td>0.0.2</td></tr><tr><td>edit_tracking_tools</td><td>1.0.0</td></tr><tr><td>qgis_geonode</td><td>2.1.0</td></tr><tr><td>unsupervised_classifier</td><td>1.0.2</td></tr><tr><td>ProcessX</td><td>1.7.1</td></tr><tr><td>enmapboxplugin</td><td>3.17.2</td></tr><tr><td>lizmap</td><td>4.5.6</td></tr><tr><td>GroupStats</td><td>2.2.7</td></tr><tr><td>RasterTransparencySetter</td><td>1.0</td></tr><tr><td>mapflow</td><td>3.4.0</td></tr><tr><td>treemap</td><td>1.1</td></tr><tr><td>basemaps</td><td>1.5</td></tr><tr><td>processing</td><td>2.12.99</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr></table>

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by m-kuhn**
Several macos fixes:

Python plugin path and proj support for qgis_process:
Fixes https://github.com/qgis/QGIS/issues/64374

Qml plugins are now bundled (also a prerequisite for the new welcome screen):
Fixes https://github.com/qgis/QGIS/issues/52389
Fixes https://github.com/qgis/QGIS/issues/59979

References https://github.com/qgis/QGIS/issues/64486 (at least partially fixed)

### CODE REVIEW

File: src/process/main.cpp [hunk 1]
```diff
@@ -166,15 +166,6 @@ int main( int argc, char *argv[] )
...
 
-  QString myPrefixPath;
-  if ( myPrefixPath.isEmpty() )
-  {
-    QDir dir( QCoreApplication::applicationDirPath() );
-    dir.cdUp();
-    myPrefixPath = dir.absolutePath();
-  }
-  QgsApplication::setPrefixPath( myPrefixPath, true );
-
```
Comment (m-kuhn) [inline src/process/main.cpp:177]: @nyalldawson the prefix path is also setup by `QgsApplication::resolvePkgPath` which is invoked during `QgsApplication::init()` and contains some additional platform specific logic:

https://github.com/qgis/QGIS/blob/de30659865a24d0855eed8850675ab0181ee19c0/src/core/qgsapplication.cpp#L1037-L1116

This has been here since the beginning, do you see any risk in removing this code (which falls back to the logic from the main qgis binary).

Comment (nyalldawson) [reply src/process/main.cpp:177]: If I recall correctly I originally just copied the initialization from bench/main.cpp. I don't see any issues using the standard init.

**Review by nyalldawson — APPROVED** [review]

**Comment by TimMcCauley** [comment]
Many thanks @m-kuhn  !
