### PR TITLE
[ogr] Fix quoted identifier logic for sqlite-based drivers

### LINKED ISSUE #58508: Layer with data defined symbology does not appear when QGIS opened
### What is the bug or the crash?

Files with data defined symbology do not appear when they should appear. A workaround to this problem is to set the layer in question to Editable, then zoom in or out. The layer will then appear.

### Steps to reproduce the issue

1. Unzip the folder Bug_Issue. Open QGIS using the file bug.qgz.
3. When QGIS is opened, two layers appear in the Layers panel, but of which should represent the same thing. Both use data defined symbology, with link width varying according to field values.
4. Untick 'DT_Model\am_Link_Counts', and this Layer disappears, as it should. The layer called 'Not_Working_Correctly...' should show the same thing as the other layer, but shows nothing.
5. Make 'Not_Working_Correctly...' editable, and zoom in or out. The layer then appears, showing the same thing as the other layer.

There is one difference between the two layers. The layer 'DT_Model\am_Link_Counts' was initially temporary, and was manually Made Permanent and had the symbology manually saved. 'Not_Working_Correctly...' was saved using Package Layers and had the symbology saved to the geopackage file, then loaded back into QGIS. I believe this issue also occurs when the layer is Exported to geopackage as well.

I am fairly sure this is only an issue when data defined symbology is used. This may or may not be related, but I expected the symbology of the layer 'DT_Model\am_Link_Counts' to be saved to the geopackage, but it was saved as a QML file instead.
[Bug_Issue.zip](https://github.com/user-attachments/files/16781591/Bug_Issue.zip)

### Versions

3.34.7

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This PR fixes https://github.com/qgis/QGIS/issues/58508 , whereas the OGR feature iterator was creating an erroneous SQL string to fetch rows from a geopackage when the feature request had an order by clause. 

The problem had to do with the QgsOgrProviderUtils::quotedIdentifier wrongly escaping backslashes for sqlite-based drivers.

### CODE REVIEW

File: src/core/providers/ogr/qgsogrproviderutils.cpp [hunk 1]
```diff
@@ -1314,6 +1314,11 @@ QByteArray QgsOgrProviderUtils::quotedIdentifier( QByteArray field, const QStrin
     field.replace( '`', "``" );
     return field.prepend( '`' ).append( '`' );
   }
+  else if ( driverName == QLatin1String( "GPKG" ) || driverName == QLatin1String( "SQLite" ) || driverName == QLatin1String( "SpatiaLite" ) )
```
Comment (rouault) [inline src/core/providers/ogr/qgsogrproviderutils.cpp:1317]: there's no spatialite driver. It is a sub-mode of the SQLite one:
```suggestion
  else if ( driverName == QLatin1String( "GPKG" ) || driverName == QLatin1String( "SQLite" ) )
```

Comment (nirvn) [reply src/core/providers/ogr/qgsogrproviderutils.cpp:1317]: @rouault , thanks.

**Comment by nirvn** [comment]
@rouault , review addressed, thanks.

**Review by rouault — APPROVED** [review]
