### PR TITLE
[keyboard shorcuts] When importing/loading keyboard shortcuts, insure preexisting shortcuts for different actions are taken into consideration

### LINKED ISSUE #61717: Custom shortcuts are not replacing default ones when imported from XML
### What is the bug or the crash?

When changing my QGIS version from 3.28 to 3.40.6, I saved my custom shortcuts in XML. 
When I loaded the XML in the 3.40 version, I noticed some custom shortcuts were not working, this is because the default shortcut is not erased. 

### Steps to reproduce the issue

Create a custom shortcut reassigned from default QGIS shortcut (e.g. F11 for "about")
Save customs shortcut as XML file.
Set the custom shortcut to another action (e.g. F11 for "add a GPX layer")
Load the XML file previously saved with customs shortcuts.
See that F11 is now the shortcut for two actions "about" or "add à GPX layer"

Image

### Versions

3.40.6

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I noticed the bug while changing QGIS version, but it occurs also when not changing the QGIS version

### PR DESCRIPTION
**Pull request by nirvn**
## Description

image

This PR fixes https://github.com/qgis/QGIS/issues/61717 . If a user tries to import a keyboard shortcut that's already bound to a _different_ action, they will be asked what to do.

### CODE REVIEW

**Comment by alexbruy** [comment]
Maybe we should add "No to All" option too?

**Comment by nirvn** [comment]
@alexbruy , good idea

File: src/gui/qgsconfigureshortcutsdialog.cpp [hunk 1]
```diff
@@ -280,20 +280,110 @@ void QgsConfigureShortcutsDialog::loadShortcuts()
   QString actionSettingKey;
 
   QDomElement child = root.firstChildElement();
+  bool reassignAll = false;
+  bool skipAll = false;
```
Comment (nyalldawson) [inline src/gui/qgsconfigureshortcutsdialog.cpp]: since these are mutually exclusive I'd lean towards a private enum, eg:

    enum class ActionOnExisting
    {
        Ask,
        ReassignAll,
        SkipAll
    };
    ActionOnExisting onExisting = ActionOnExisting::Ask;

Comment (nirvn) [reply src/gui/qgsconfigureshortcutsdialog.cpp]: Good idea.

**Comment by nirvn** [comment]
@nyalldawson , done.

**Comment by nyalldawson** [comment]
@nirvn build failure IS valid here

**Comment by nirvn** [comment]
@nyalldawson , yeah, it's nice to be able to rely on CI failures again! :)

**Review by nyalldawson — APPROVED** [review]
