### PR TITLE
[ui][diagrams] Fix drag and drop to reorder stacked diagram not working

### LINKED ISSUE #59505: Unable to reorder subdiagrams in stacked diagrams dialog
### What is the bug or the crash?

_Still on the road to features parity between rule-based dialogs and the stacked diagram one_

It should be possible to move up and down order of the diagrams. Assuming you would like to reorder how the various subdiagrams are displayed, afaict there is no way other than deleting the ones above in the list and recreate them later (because there is no "copy" button either - #59504 )

### Steps to reproduce the issue

Trying vainly to drag-and-drop

https://github.com/user-attachments/assets/819dd578-bb40-47be-bc87-52f4fe2af07f

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.40.0-Bratislava</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/1d561ad8ad9">1d561ad8ad9</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.2</td></tr><tr><td>Python version</td><td>3.9.5</td></tr><tr><td>GDAL/OGR version</td><td>3.3.2</td></tr><tr><td>PROJ version</td><td>8.1.1</td></tr><tr><td>EPSG Registry database version</td><td>v10.028 (2021-07-07)</td></tr><tr><td>GEOS version</td><td>3.9.1-CAPI-1.14.2</td></tr><tr><td>SQLite version</td><td>3.35.2</td></tr><tr><td>PDAL version</td><td>2.3.0</td></tr><tr><td>PostgreSQL client version</td><td>unknown</td></tr><tr><td>SpatiaLite version</td><td>5.0.1</td></td></tr><tr><td>QWT version</td><td>6.1.6</td></tr><tr><td>QScintilla2 version</td><td>2.11.5</td></tr><tr><td>OS version</td><td>macOS 14.6</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>QuickOSM</td><td>2.2.3</td></tr><tr><td>search_and_replace_in_projects</td><td>1.3</td></tr><tr><td>changeDataSource</td><td>3.1</td></tr><tr><td>On-the-Fly-Shortest-Path</td><td>1.3.1</td></tr><tr><td>Qgis2threejs</td><td>2.8</td></tr><tr><td>MemoryLayerSaver</td><td>5.0.2</td></tr><tr><td>MapsPrinter</td><td>0.9</td></tr><tr><td>lizmap</td><td>4.3.19</td></tr><tr><td>processing</td><td>2.12.99</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr></table>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This PR fixes https://github.com/qgis/QGIS/issues/59505 whereas the stacked diagrams tree view was not allowing for drag and drop re-ordering of sub-diagrams. It's an important UI/UX that users would definitively expect here as we allow for drag and drop re-ordering for symbology renderers and rule-based label renderer widgets.

In addition, while fixing this, I've harmonized the tree view by removing the "Enabled" column in favor of adding a checkbox in the first column where the diagram name is located (like we do pretty much everywhere else), as well as adding a nice touch of night mapping (eye toggles!).

Screenshot From 2025-01-27 09-43-45

### CODE REVIEW

File: src/gui/vector/qgsstackeddiagramproperties.cpp [hunk 1]
```diff
@@ -373,7 +374,117 @@ Qt::ItemFlags QgsStackedDiagramPropertiesModel::flags( const QModelIndex &index
...
+
+  const auto constIndexes = indexes;
+  for ( const QModelIndex &index : constIndexes )
+  {
+    // each item consists of several columns - let's add it with just first one
+    if ( !index.isValid() || index.column() != 0 )
+      continue;
+
+    // we use a clone of the existing rule because it has a new unique rule key
+    // non-unique rule keys would confuse other components using them (e.g. legend)
```
Comment (gacarrillor) [inline src/gui/vector/qgsstackeddiagramproperties.cpp:410]: Could we please adapt the comment to diagram renderers?

**Comment by DelazJ** [comment]
Thanks @nirvn 
One point raised in the issue report I can't tell if covered here is the handling of sub-diagram placement. Per the [initial PR](https://github.com/qgis/QGIS/pull/58568):
> Note there are some shared settings like placement settings (e.g., over point), that the stacked diagram will take from its first subdiagram. Thus, other subdiagrams won't be able to set or change those specific settings, unless they become the first subdiagram in the stacked diagram. Therefore, when editing a subdiagram that is not located in the first place, we show labels to let users know why they don't see the expected widgets (e.g., placement ones) and where they can find them (i.e., in the first subdiagram).

Some options of subdiagrams not topmost are currently greyed out. My suggestion was to allow any diagram options to be modified anytime, regardless the rank of the subdiagram, and then have a method that would apply only placement options from the topmost to the whole stack. That way, a simple-drag-and-drop would be enough to preview what I expect, and not require subsequent placement options modifications. And if I switch again the order...?
Better have the subdiagram options set when I'm configuring the subdiagram, once for all.

**Comment by nirvn** [comment]
@DelazJ , let's merge this PR which gives us generic re-ordering support here and deal with the extra UX enhancements you mentioned in subsequent PRs if that's OK with you.

**Comment by DelazJ** [comment]
OK, @nirvn

**Review by nyalldawson — APPROVED** [review]
