### PR TITLE
Fix Georeferencer report issues: always include RMS error value and make the text selectable

### LINKED ISSUE #55411: Georeferencer: the PDF report doesn't include the RMS error value for non linear transformation types
### What is the bug or the crash?

The PDF report generated by the Georeferencer doesn't include the RMS error value for non linear transformation types and if the "Create world file" is not set to true, although the RMS error value is calculated for any transformation types.

### Steps to reproduce the issue

1. in the Georeferencer setting windows set a transformation type other than Linear or Helmert and set a valid path for the PDF report
2. georeference an image
3. run the georeferencing and see that the RMS error value is missing in the generated PDF report

### Versions

QGIS 3.34.0, QGIS 3.28.12 and QGIS 3.35.0-Master on Windows (OSGeo4W)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

When a linear transformation type is used and the the "Create world file" is set to true, then the RMS error value is included in the PDF report, e.g.:
image

Side note: the text in the PDF report is not searchable and not selectable.

### PR DESCRIPTION
**Pull request by agiudiceandrea**
## Description

The PDF report generated by the Georeferencer currently includes the RMS (Root Mean Square) error value only for linear transformation types ("Linear" or "Helmert" types) and only if the "Create world file" is set to true, e.g:
image

Since the RMS error value is calculated and it is relevant for any transformation type, this PR makes sure that the RMS error value is included in the PDF report also for non linear transformation types and also when the "Create world file" is set to false, e.g.:
image

(I'd like some suggestions on how to improve the wording and / or the layout)

This PR also makes the text in the PDF report selectable (and searchable).

Fixes #55411.

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]

File: src/app/georeferencer/qgsgeorefmainwindow.cpp [hunk 1]
```diff
@@ -2081,6 +2098,7 @@ bool QgsGeoreferencerMainWindow::writePDFReportFile( const QString &fileName, co
   QgsLayoutExporter exporter( &layout );
   QgsLayoutExporter::PdfExportSettings settings;
   settings.dpi = 300;
+  settings.textRenderFormat = Qgis::TextRenderFormat::AlwaysText;
```
Comment (nyalldawson) [inline src/app/georeferencer/qgsgeorefmainwindow.cpp:2101]: Good move! :+1:
