### PR TITLE
Fix Crash when saving layout after removing map

### LINKED ISSUE #53988: QGIS crashes on save when layout objects have been deleted.
## User Feedback

QGIS crashes on save when layout objects have been deleted.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x000044c8 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QgsLayoutItemAttributeTable::writePropertiesToElement :
QgsLayoutMultiFrame::writeXml :
QgsLayout::writeXml :
QgsPrintLayout::writeXml :
QgsPrintLayout::writeLayoutXml :
QgsLayoutManager::writeXml :
QgsProject::writeProjectFile :
QgsProject::zip :
QgsProject::write :
QgisApp::fileSave :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.32.1-Lima
QGIS code revision: 4a078ecf63
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.1
Running against GDAL: 3.7.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

Open existing layout.
delete an object
click save project
QGIS crashes 

### Versions

QGIS version
3.32.1-Lima
QGIS code revision
4a078ecf63
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
Qgis2threejs
2.7.1
qgis_resource_sharing
1.0.0
qgis_stac
1.1.1
QuickOSM
2.2.2
quick_map_services
0.19.33
shapetools
3.4.14
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by YoannQDQ**
- Fix #53988

## Description

This PR ensure the layout map is always disconnected from the linked attribute table items when it is destroyed, by storing the map item as a `QPointer< QgsLayoutItemMap >`.

### CODE REVIEW

File: src/core/layout/qgslayoutitemattributetable.cpp [hunk 1]
```diff
@@ -941,12 +942,7 @@ bool QgsLayoutItemAttributeTable::readPropertiesFromElement( const QDomElement &
 
   //map
   mMapUuid = itemElem.attribute( QStringLiteral( "mapUuid" ) );
-  if ( mMap )
-  {
-    disconnect( mMap, &QgsLayoutItemMap::extentChanged, this, &QgsLayoutTable::refreshAttributes );
-    disconnect( mMap, &QgsLayoutItemMap::mapRotationChanged, this, &QgsLayoutTable::refreshAttributes );
-    mMap = nullptr;
```
Comment (nyalldawson) [inline src/core/layout/qgslayoutitemattributetable.cpp:948]: Is the issue here a dangling pointer to mMap? If so, making mMap a QPointer might be a simpler/safer fix

Comment (YoannQDQ) [reply src/core/layout/qgslayoutitemattributetable.cpp:948]: Good point.

**Review by nyalldawson — APPROVED** [review]
