### PR TITLE
[fix] Make the Oriented Minimum Bounding Box of a singlepart point return the Bounding Box of the point

### LINKED ISSUE #62126: Disallow point layer as input to `Oriented Minimum Bounding Box`
### What is the bug or the crash?

Calculating bounding boxes for features in point layers does not make sense.

For the `Oriented Minimum Bounding Box` processing algorithm, output features end up with
* no extent
* width, height and area set to 1796… (`MAX_INT` or the like)
* perimeter set to inf

### Steps to reproduce the issue

Input a point layer to the `Oriented minimum bounding box` processing algorithm

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.40.6-Bratislava</td></tr><tr><td>QGIS code branch</td><td><a href="https://github.com/qgis/QGIS/tree/release-3_40">Release 3.40</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.15</td></tr><tr><td>Python version</td><td>3.13.3</td></tr><tr><td>GDAL version</td><td>3.10.3</td></tr><tr><td>PROJ version</td><td>9.6.0</td></tr><tr><td>EPSG Registry database version</td><td>v12.004 (2025-03-02)</td></tr><tr><td>GEOS version</td><td>3.13.1-CAPI-1.19.2</td></tr><tr><td>SQLite version</td><td>3.46.1</td></tr><tr><td>PostgreSQL client version</td><td>17.4 (Debian 17.4-2)</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.1.4</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Debian GNU/Linux 13 (trixie)</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>ohsomeTools</td><td>0.3</td></tr><tr><td>quick_map_services</td><td>0.21.2</td></tr><tr><td>ORStools</td><td>2.0.0</td></tr><tr><td>valhalla</td><td>2.5.0</td></tr><tr><td>processing_saga_nextgen</td><td>1.0.0</td></tr><tr><td>veloroutes_voies_vertes</td><td>1.0.0</td></tr><tr><td>geest</td><td>0.3.6</td></tr><tr><td>QuickOSM</td><td>2.4.1</td></tr><tr><td>qgis2web</td><td>3.20.0</td></tr><tr><td>PeliasGeocoding</td><td>0.1</td></tr><tr><td>pluginbuilder3</td><td>3.2.1</td></tr><tr><td>plugin_reloader</td><td>0.17</td></tr><tr><td>mmqgis</td><td>2024.11.8</td></tr><tr><td>risk_assessment</td><td>0.1.7</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>processing</td><td>2.12.99</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

This is probably not restricted to the `Oriented Minimum Bounding Box` algorithm, but others as well.

### PR DESCRIPTION
**Pull request by gacarrillor**
Thus, the result will now have a valid extent, and more meaningful geometric attributes (area. angle, width, height).

Includes unit tests.

Fix #62126

### CODE REVIEW

File: src/analysis/processing/qgsalgorithmorientedminimumboundingbox.cpp [hunk 1]
```diff
@@ -57,7 +57,7 @@ Qgis::WkbType QgsOrientedMinimumBoundingBoxAlgorithm::outputWkbType( Qgis::WkbTy
 
 QString QgsOrientedMinimumBoundingBoxAlgorithm::shortHelpString() const
 {
-  return QObject::tr( "This algorithm calculates the minimum area rotated rectangle which covers each feature in an input layer." ) + QStringLiteral( "\n\n" ) + QObject::tr( "See the 'Minimum bounding geometry' algorithm for a oriented bounding box calculation which covers the whole layer or grouped subsets of features." );
+  return QObject::tr( "This algorithm calculates the minimum area rotated rectangle which covers each feature in an input layer." ) + QStringLiteral( "\n\n" ) + QObject::tr( "For singlepart point features, the output corresponds to the bounding box of the geometry." ) + QStringLiteral( "\n\n" ) + QObject::tr( "See the 'Minimum bounding geometry' algorithm for a oriented bounding box calculation which covers the whole layer or grouped subsets of features." );
```
Comment (DelazJ) [inline src/analysis/processing/qgsalgorithmorientedminimumboundingbox.cpp]:
```suggestion
  return QObject::tr( "This algorithm calculates the minimum area rotated rectangle which covers each feature in an input layer." ) + QStringLiteral( "\n\n" ) + QObject::tr( "For singlepart point features, the output corresponds to the bounding box of the geometry." ) + QStringLiteral( "\n\n" ) + QObject::tr( "See the 'Minimum bounding geometry' algorithm for an oriented bounding box calculation which covers the whole layer or grouped subsets of features." );
```

File: src/core/geometry/qgsgeometry.cpp [hunk 2]
```diff
@@ -1336,6 +1336,16 @@ QgsBox3D QgsGeometry::boundingBox3D() const
 QgsGeometry QgsGeometry::orientedMinimumBoundingBox( double &area, double &angle, double &width, double &height ) const
 {
   mLastError.clear();
+
+  if ( type() == Qgis::GeometryType::Point && d->geometry->partCount() == 1 )
```
Comment (nyalldawson) [inline src/core/geometry/qgsgeometry.cpp:1343]:
```suggestion

  if ( isNull() )
    return QgsGeometry();

  if ( type() == Qgis::GeometryType::Point && d->geometry->partCount() == 1 )
```

Comment (nyalldawson) [reply src/core/geometry/qgsgeometry.cpp:1343]: (Otherwise there's a potential nullptr dereference of `d`)

Comment (gacarrillor) [reply src/core/geometry/qgsgeometry.cpp:1343]: Thanks!

**Review by nyalldawson — APPROVED** [review]
