### PR TITLE
correctly handle hidden widgets inside QgsCollapsibleGroupBox (fix #55443)

### LINKED ISSUE #55443: "Data source encoding" dropdown not shown in layer properties for delimited text layer
### What is the bug or the crash?

The [documentation ](https://docs.qgis.org/3.28/en/docs/user_manual/working_with_vector/vector_properties.html#source-properties) states that in the "Source" tab of the layer properties dialog, there should be a dropdown to select the character encoding for the layer. However, in QGIS 3.32.2 this dropdown is not shown for a layer added with "Add Delimited Text Layer..." (see attached screenshot). I am certain it used to be here in older versions, as I am using this for a GIS course I teach.

### Steps to reproduce the issue

1. Create a new QGIS project
2. Menu "Layer" > "Add Layer" > "Add delimited text layer...". You can use the attached CSV file [places_test.csv](https://github.com/qgis/QGIS/files/13485170/places_test.csv), which is encoded in ISO-8859-1. (Select lon and lat as X/Y fields)
3. After adding the layer, go to layer properties > Source
4. The encoding dropdown should appear on top underneath the Layer name field. On my machine, it is not there.

QGIS-layerproperties

### Versions

3.32.2 Windows – I will verify later today whether this is present in the latest release.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alexbruy**
## Description

If widget inside `QgsCollapsibleGroupBox` is hidden, it will become visible after collapse/expand as groupbox hides and shows its child widgets without taking their initial visibility in consideration.

Only initially visible child widgets should be hidden and shown during collapse/expand.

Fixes #55443.

### CODE REVIEW

File: src/gui/qgscollapsiblegroupbox.cpp [hunk 1]
```diff
@@ -475,7 +477,10 @@ void QgsCollapsibleGroupBoxBasic::collapseExpandFixes()
       if ( w && w != mCollapseButton )
       {
         if ( w->property( hideKey ).toBool() )
+        {
+          w->setProperty( hideKey, true );
```
Comment (nyalldawson) [inline src/gui/qgscollapsiblegroupbox.cpp]: isn't this implied by the check above?

Comment (alexbruy) [reply src/gui/qgscollapsiblegroupbox.cpp]: This is an oversight from my side, this line is not needed.

File: src/gui/qgscollapsiblegroupbox.cpp [hunk 2]
```diff
@@ -453,7 +453,9 @@ void QgsCollapsibleGroupBoxBasic::collapseExpandFixes()
     for ( QObject *child : constChildren )
     {
       QWidget *w = qobject_cast<QWidget *>( child );
-      if ( w && w != mCollapseButton )
+      // ignore already hidden widgets, so they won't become visible on expand
+      // see https://github.com/qgis/QGIS/issues/55443
+      if ( w && w != mCollapseButton && w->isVisible() )
```
Comment (nyalldawson) [inline src/gui/qgscollapsiblegroupbox.cpp]: is "isVisible" correct here? I think we may instead want "!isHidden()", if we're trying to filter out explicitly hidden widgets (as opposed to those just not visible because eg they are on a non-visible tab). 

(The qt api is confusing there -- see https://doc.qt.io/qt-6/qwidget.html#isHidden )

**Review by nyalldawson — APPROVED** [review]
