### PR TITLE
[fix] Fix custom node initialization for custom elevation profiles

### LINKED ISSUE #65058: Broken custom node initialization for Custom Elevation Profile Sources
### What is the bug or the crash?

For instance, plugins that create and register a Custom Profile Source cannot see a corresponding custom node in the Elevation tree view anymore (in the current master, 3.99).

Expected behavior when registering a Custom Profile Source (like [SwissLocator](https://github.com/opengisch/qgis-swiss-locator/) plugin does): the custom node at the top.
Image

### Steps to reproduce the issue

1. Open a new project.
2. Register a Custom Profile Source (e.g., by running this code snippet: https://gist.github.com/gacarrillor/4bb82379e4fa30df500c5532be1c9a13, you can verify the Python console, which prints `True` if the Custom Profile Source was registered).
3. Open an Elevation Profile widget.

Current result: The custom node is not in the Elevation layer tree.

Image

Expected result with the code snippet provided above:

Image

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.99.0-Master</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/f937ebdfd0b">f937ebdfd0b</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>6.9.2</td></tr><tr><td>Python version</td><td>3.13.7</td></tr><tr><td>GDAL version</td><td>3.10.3</td></tr><tr><td>PROJ version</td><td>9.6.0</td></tr><tr><td>EPSG Registry database version</td><td>v12.004 (2025-03-02)</td></tr><tr><td>GEOS version</td><td>3.13.1-CAPI-1.19.2</td></tr><tr><td>SFCGAL version</td><td>No support</td></tr><tr><td>GeographicLib version</td><td>No support</td></tr><tr><td>SQLite version</td><td>3.46.1</td></tr><tr><td>PostgreSQL client version</td><td>17.7</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.3.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Ubuntu 25.10</td></tr><tr><td colspan="2"><i>This copy of QGIS writes debugging output.</i></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>AppendFeaturesToLayer</td><td>3.0.0</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>a00_qpip</td><td>dev</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>open_alaqs</td><td>dev</td></tr><tr><td>pg_service_parser</td><td>0.9.0</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gacarrillor**
References https://github.com/qgis/QGIS/pull/64219#issuecomment-3808001159

Includes unit test to avoid regressions.

Fix https://github.com/qgis/QGIS/issues/65058

### CODE REVIEW

**Comment by gacarrillor** [comment]
Rebasing to resolve conflicts.

**Review by 3nids — APPROVED** [review]

**Comment by 3nids** [comment]
since this is an API break if we let go out 4.0 before merging, we'll merge this before friday if there is no objection

File: src/core/layertree/qgslayertreegroup.cpp [hunk 1]
```diff
@@ -227,13 +227,22 @@ void QgsLayerTreeGroup::removeLayer( QgsMapLayer *layer )
   updateGroupLayers();
 }
 
-void QgsLayerTreeGroup::removeCustomNode( const QString &id )
+void QgsLayerTreeGroup::removeCustomNode( QgsLayerTreeCustomNode *customNode )
```
Comment (nyalldawson) [inline src/core/layertree/qgslayertreegroup.cpp:230]: Can you explain the rationale behind this change? Is it because we may potentially have MANY custom nodes with the same ID?

**Review by nyalldawson — APPROVED** [review]

File: src/core/layertree/qgslayertreegroup.cpp (hunk 1 above)
Comment (nyalldawson) [reply src/core/layertree/qgslayertreegroup.cpp:230]: (this isn't a blocker -- it's just that the previous API looks a little safer to me)

Comment (gacarrillor) [reply src/core/layertree/qgslayertreegroup.cpp:230]: Many custom nodes sharing id should not be possible, since we check and avoid registering a node if its id is already registered (see the corresponding [insert/add methods](https://github.com/qgis/QGIS/blob/7e2166d74c1f7de790681a4d777ada6e6f806d23/src/core/layertree/qgslayertreegroup.cpp#L115-L157)).

I wanted to make the API more predictable, aligning the `removeCustomNode()` with the corresponding method for layers, which gets a pointer, not an id.

Comment (nyalldawson) [reply src/core/layertree/qgslayertreegroup.cpp:230]: Ok, that's a fair argument!
