### PR TITLE
[vector layer] Fix geometry validity check preventing saving of changes after removing problematic feature(s)

### LINKED ISSUE #59688: Unable to save after error in Geometry Validation
### What is the bug or the crash?

In a project I have made settings in the layer properties _Check Geometry Is Valid_
image

If I then digitize a normal feature and press save. All good.
If I digitize a feature with illegal geometry I get a warning - as expected.
Then I delete the feature - and try to save. Then I get a warning - unable to save
image

In earlier versions I have been able to make a _Fix geometries_ (using multipolygon or multiline). Now Unable to solve using _Fix _geometry__

It seems the digitizing an illegal feature and deleting, it is still in the cash...
This bug make it almost impossible to digitize.

All my students have the same issue on different platforms same QGIS version.

### Steps to reproduce the issue

In a layer set properties - Check Geometry _is Valid_
Digitize a nomal feature - Save
Digitize an illegal feature - Save
Delete the feature.
Digitize a new feature - Save

### Versions

3.40.0 Windows and Mac

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This PR fixes https://github.com/qgis/QGIS/issues/59688 whereas logic was missing to ensure that delete feature(s) with problematic geometry would allow for the remaining valid changes to be saved during an editing session.

### CODE REVIEW

File: src/app/qgsgeometryvalidationservice.cpp [hunk 1]
```diff
@@ -133,12 +133,16 @@ void QgsGeometryValidationService::onGeometryChanged( QgsVectorLayer *layer, Qgs
 
 void QgsGeometryValidationService::onFeatureDeleted( QgsVectorLayer *layer, QgsFeatureId fid )
 {
+  mLayerChecks[layer].singleFeatureCheckErrors.remove( fid );
```
Comment (nyalldawson) [inline src/app/qgsgeometryvalidationservice.cpp:136]: There's a few QHash lookups to `mLayerChecks[layer]` in this method -- how about retrieving the value once as a reference, and reusing throughout?

Comment (nirvn) [reply src/app/qgsgeometryvalidationservice.cpp]: @nyalldawson , addressed, thanks.

**Review by nyalldawson — APPROVED** [review]
