### PR TITLE
attribute table shortcuts when docked [needs-docs]

### LINKED ISSUE #29633: Shortcut does not work when dock attribute table
Author Name: **Maxime RIOU** (Maxime RIOU)
Original Redmine Issue: [21818](https://issues.qgis.org/issues/21818)
Affected QGIS version: 3.6.1
Redmine category:attribute_table

---
When attribute table is on the same windows as the main map (using dock attribute table), the shortcut ctrl+J is not working

### LINKED ISSUE #29945: Unable to copy selected rows from attibute table while it is docked
Author Name: **URIIT URIIT** (URIIT URIIT)
Original Redmine Issue: [22134](https://issues.qgis.org/issues/22134)
Affected QGIS version: 3.6.1
Redmine category:attribute_table

---
While the “Dock Attribute Table” button is pressed, it is not possible to copy all selected lines in the attribute table using the “Ctrl + c” key combination.
After undocking the attribute table, everything works fine.

---

- [1.png](https://issues.qgis.org/attachments/download/14979/1.png) (URIIT URIIT)

### PR DESCRIPTION
**Pull request by jgrocha**
## Description

We have the same shortcuts assigned to the main window and to the attribute table.

When the attribute table is docked, both (the main window and the attribute table) have conflicting shortcuts. When they are separated as two different windows, events goes to the focused one, and we don't have conflicts.

The error logged on the console was:
```
QAction::event: Ambiguous shortcut overload: Ctrl+J
```

To solve this issue, I'm using the attribute table dock/undock event to remove and recreate the shortcuts. I had to test this manually and it works.

Users reported this limitation just the <kbd>Ctrl</kbd>+<kbd>J</kbd> and <kbd>Ctrl</kbd>+<kbd>C</kbd> shortcuts, but there are more. I review all overlapping shortcuts.

This PR fixes #29633. This also fixes the duplicated #29945.

From the discussion on #29633, I agree with @nyalldawson and I'm also proposing the removal of two shortcuts on the attribute panel:

| Shortcut | Action | 
| --- | --- | 
|<kbd>Ctrl</kbd>+<kbd>L</kbd> | Delete field | 
| <kbd>Ctrl</kbd>+<kbd>S</kbd>| Save edits | 

Delete field is not a common operation. 

After the table is docked, we were not able to use <kbd>Ctrl</kbd>+<kbd>S</kbd> for saving features. Even when the table is undocked, save feature edits using the same shortcut as save project is dangerous. 

We still have <kbd>Ctrl</kbd>+<kbd>E</kbd> (toggle edit shortcut) to stop editing that works either when the table is docked or undocked.

### Documentation

On the documentation, we need to remove references to these two shortcuts that are not available any more in the attribute table:

| Shortcut | Action | 
| --- | --- | 
|<kbd>Ctrl</kbd>+<kbd>L</kbd> | Delete field | 
| <kbd>Ctrl</kbd>+<kbd>S</kbd>| Save edits | 

That is enough, I think. Eventually, if we keep a list of all QGIS shortcuts, we also need to update that list.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [X] Commit messages are descriptive and explain the rationale for changes
- [X] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [X] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [X] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [X] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [X] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [X] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

Closes #29633, fix #29945,

### CODE REVIEW

File: src/app/qgsattributetabledialog.cpp [hunk 1]
```diff
@@ -1221,6 +1233,19 @@ void QgsAttributeTableDialog::toggleDockMode( bool docked )
     updateTitle();
     mDialog->restoreGeometry( QgsSettings().value( QStringLiteral( "Windows/BetterAttributeTable/geometry" ) ).toByteArray() );
     mDialog->show();
+
+    // restore attribute table shortcuts in window mode
+    QgsDebugMsg( QStringLiteral( "Restore attribute table dialog shortcuts in window mode" ) );
+    // duplicated on Main Window
+    mActionCopySelectedRows->setShortcut( QApplication::translate( "QgsAttributeTableDialog", "Ctrl+C", Q_NULLPTR ) );
```
Comment (nyalldawson) [inline src/app/qgsattributetabledialog.cpp]: I don't believe we usually translate shortcuts

**Comment by DelazJ** [comment]
@m-kuhn Since [needs-docs] is not in the commit message, removing it from the title will make QGIS-Documentation not get any notification

**Comment by m-kuhn** [comment]
Appended it again. I hope my grant proposal for moving this behavior to labels is accepted.

File: src/app/qgsattributetabledialog.cpp (hunk 1 above)
Comment (jgrocha) [reply src/app/qgsattributetabledialog.cpp]: Code generated by QT Creator makes these shortcuts translatable. If we keep the same policy in our written code, we will enable translatable shortcuts in the future.

For example, in Portuguese and Spanish, the usual shortcut for saving is <kbd>Ctrl</kbd>+<kbd>G</kbd> (Guardar, Gravar).

But **I don't have a strong opinion on this**. It it causes noise, I'll be happy to remove.

Comment (nyalldawson) [reply src/app/qgsattributetabledialog.cpp]: I'd say remove it. There's hundreds of shortcuts set in the code which aren't translated already, this would require a coordinated approach to address.

Comment (jgrocha) [reply src/app/qgsattributetabledialog.cpp]: Done

File: src/app/qgsattributetabledialog.cpp [hunk 2]
```diff
@@ -1193,6 +1193,18 @@ void QgsAttributeTableDialog::toggleDockMode( bool docked )
     connect( this, &QObject::destroyed, mDock, &QWidget::close );
     QgisApp::instance()->addDockWidget( Qt::BottomDockWidgetArea, mDock );
     updateTitle();
+
+    // To prevent "QAction::event: Ambiguous shortcut overload"
+    QgsDebugMsg( QStringLiteral( "Remove shortcuts from attribute table already defined in main window" ) );
```
Comment (nyalldawson) [inline src/app/qgsattributetabledialog.cpp]:
```suggestion
    QgsDebugMsgLevel( QStringLiteral( "Remove shortcuts from attribute table already defined in main window" ), 2 );
```

File: src/app/qgsattributetabledialog.cpp [hunk 3]
```diff
@@ -1221,6 +1233,19 @@ void QgsAttributeTableDialog::toggleDockMode( bool docked )
     updateTitle();
     mDialog->restoreGeometry( QgsSettings().value( QStringLiteral( "Windows/BetterAttributeTable/geometry" ) ).toByteArray() );
     mDialog->show();
+
+    // restore attribute table shortcuts in window mode
+    QgsDebugMsg( QStringLiteral( "Restore attribute table dialog shortcuts in window mode" ) );
```
Comment (nyalldawson) [inline src/app/qgsattributetabledialog.cpp]:
```suggestion
    QgsDebugMsgLevel( QStringLiteral( "Restore attribute table dialog shortcuts in window mode" ), 2 );
```

**Comment by SrNetoChan** [comment]
Is this going to be backported to 3.4?
