### PR TITLE
Fix crash when snapping to curved geometry without curved segments

### LINKED ISSUE #33234: Crash on clik in "Enable Snapping on Intersection" from Snapping  Toolbar
Crash ID: ff48eba451388ba43cf68cb2852b6171adc14573

Stack Trace

_geometrySegmentsInRect qgspointlocator.cpp:355
QgsPointLocator_VisitorEdgesInRect::visitData qgspointlocator.cpp:403
Index::~Index :
Index::~Index :
QgsPointLocator::edgesInRect qgspointlocator.cpp:918
QgsPointLocator::edgesInRect qgspointlocator.cpp:927
QgsSnappingUtils::snapToMap qgssnappingutils.cpp:263
QgsMapMouseEvent::snapPoint qgsmapmouseevent.cpp:52
QgsMapToolAdvancedDigitizing::canvasMoveEvent qgsmaptooladvanceddigitizing.cpp:110
QgsMapCanvas::mouseMoveEvent qgsmapcanvas.cpp:1726
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1598
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.0-A Coru�a
QGIS code revision: 6ffa89eb3e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.14393

### PR DESCRIPTION
**Pull request by m-kuhn**
When a geometry that supports curves has only straight segments and a user snaps to it with "snap to intersections" enabled, QGIS crashes.

Fixes https://github.com/qgis/QGIS/issues/33234

### CODE REVIEW

File: src/core/qgspointlocator.cpp [hunk 1]
```diff
@@ -466,8 +466,10 @@ static QgsPointLocator::MatchList _geometrySegmentsInRect( QgsGeometry *geom, co
   for ( auto part = straightGeom.const_parts_begin(); part != straightGeom.const_parts_end(); ++part )
   {
     // Checking for invalid linestrings
-    // A linestring should/(must?) have at least two points
-    if ( qgsgeometry_cast<QgsLineString *>( *part )->numPoints() < 2 )
+    // A linestring should/(must?) have at least two points.
```
Comment (lbartoletti) [inline src/core/qgspointlocator.cpp:469]: Must, if we want to comply with the ogc standard, cf [our discussions](https://github.com/qgis/QGIS/pull/9379#discussion_r269432326)

BTW, I wanted (and I forgot...) to add a method to return if the linestring is valid or not. Something like

```
bool QgsCurve::isValid() {
..
  return curve->numPoints() < 2
}
```

I think this code deserves to be in the class QgsCurve / QgsLineString and the method called here.

**Review by nirvn — APPROVED** [review]

File: src/core/qgspointlocator.cpp (hunk 1 above)
Comment (lbartoletti) [reply src/core/qgspointlocator.cpp:469]: Sure.

**Review by lbartoletti — APPROVED** [review]
