### PR TITLE
Fix timestep UI handling in temporal controller widget

### LINKED ISSUE #40894: Temporal controller widget overwrite timestep and timestep unit for some input values.
As mention by @rduivenvoorde  here https://github.com/qgis/QGIS/issues/37829#issuecomment-755205663

The temporal controller widget timestep and timestep unit input get changed when user input some values.
Example: setting 30 timestep and days as timestep unit will automatically be changed to 1 timestep and months as the timestep 
unit and setting 7 timestep and days as timestep unit will also be changed to 1 timestep and weeks as the timestep unit.

This issue is on QGIS master and QGIS 3.16

see below screenshot

guessing_issue_in_TC

### PR DESCRIPTION
**Pull request by Samweli**
Fixes https://github.com/qgis/QGIS/issues/40894

Recent changes in https://github.com/qgis/QGIS/pull/40654  has made QgsInterval support storing timestep and timestep unit and accessing them via "originalDuration()" and "originalUnit()", now we can use those functions to directly set the temporal controller widget timestep and timestep unit.

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
Looks good to me. @rduivenvoorde can you compile and test too please?

File: src/gui/qgstemporalcontrollerwidget.cpp [hunk 1]
```diff
@@ -538,43 +538,15 @@ void QgsTemporalControllerWidget::setTimeStep( const QgsInterval &timeStep )
   if ( ! timeStep.isValid() || timeStep.seconds() <= 0 )
     return;
 
-  // Search the time unit the most appropriate :
```
Comment (vcloarec) [inline src/gui/qgstemporalcontrollerwidget.cpp:541]: When this method was implemented, the aim was to provide an adapted time step (duration and unit) when loading mesh layer (https://github.com/qgis/QGIS/pull/36949/files) and the method was used only for that and was called only when first mesh layer is loaded. 
Since this method is now called when frame duration is changed (even by user). I think the problem is not what  this original method do internally but it could be maybe better to create another method that will be called when frame duration changed. So, maybe, let this original method like before, and create another to change the time step when frame duration change.
Indeed, I think I will be quite sad if this  there is no this "unit guessing" anymore (and maybe also other users of mesh layers).

**Review by vcloarec — CHANGES_REQUESTED** [review]

File: src/gui/qgstemporalcontrollerwidget.cpp (hunk 1 above)
Comment (Samweli) [reply src/gui/qgstemporalcontrollerwidget.cpp:541]: > So, maybe, let this original method like before, and create another to change the time step when frame duration change

Sure @vcloarec , I will create another one then.

**Comment by rduivenvoorde** [comment]
> Looks good to me. @rduivenvoorde can you compile and test too please?

I did and reported at the issue: https://github.com/qgis/QGIS/issues/40894#issuecomment-756761193
(and in de meantime: I agree with comments of @vcloarec )

**Comment by Samweli** [comment]
> (and in de meantime: I agree with comments of @vcloarec )

ok @rduivenvoorde, I have worked on @vcloarec comments and updated the PR. Please let me know if you are okay with the latest changes.

**Review by vcloarec — APPROVED** [review]
thanks
