### PR TITLE
[server][wms] Add displayName to GFI JSON response

### LINKED ISSUE #59353: QGIS Server OGC: Display name is not provided in GetFeatureInfo json/gml response
### What is the bug or the crash?

If the WITH_DISPLAY_NAME parameter is included in a WMS GetFeatureInfo request, the display name is omitted from the response GeoJSON or WFS GML format. It would be included as attribute with ... name in properties object for each feature.

The displayName field is included in the text/xml response format, but the XML structure is not standardized and harder to parse with standard FE libraries (openlayers ... ).

Example of responses for GET service=WMS&request=GetFeatureInfo&INFO_FORMAT=application/json&WITH_DISPLAY_NAME=true

json :-1: no display name :
```json
{
  "features": [
    {
      "geometry": {
        "coordinates": [-111, 111],
        "type": "Point"
      },
      "id": "closure_df66a4aa_cf33_497e_b134_aa157ea885df.339",
      "properties": {
        "ID": 106,
      },
      "type": "Feature"
    }]
}
```

```text/xml``` :+1:
```xml 
<GetFeatureInfoResponse>
 <Layer name="closure_df66a4aa_cf33_497e_b134_aa157ea885df">
  <Feature id="339">
   <Data>
    <Attribute name="ID" value="106"/>
   </Data>
   <Attribute name="displayName" value="Item 339"/>
   <BoundingBox CRS="EPSG:3857" minx="-111" miny="111" maxy="6803278.84325854" maxx="-111"/>
   <Attribute type="derived" name="geometry" value="Point (-111 111)"/>
  </Feature>
 </Layer>
</GetFeatureInfoResponse>
```

_Note: coordinates are just examples_

### Steps to reproduce the issue

1. GO to layer properties
2. GO to Display
3. Enable display name attribute
4. Make GetFeatureInfo request to this project with ```WITH_DISPLAY_NAME``` parameter (as documented here https://docs.qgis.org/3.34/en/docs/server_manual/services/wms.html#wms-withdisplayname)

### Versions

3.34.12-Prizren

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
In the gray zone between a feature and a bugfix...

Fixes #59353

### CODE REVIEW

File: src/server/services/wms/qgswmsrenderer.cpp [hunk 1]
```diff
@@ -2881,6 +2883,24 @@ namespace QgsWms
...
+            for ( int k = 0; k < attrs.count(); k++ )
+            {
+              const QDomElement elm = attrs.at( k ).toElement();
+              if ( elm.attribute( QStringLiteral( "name" ) ).compare( "displayName" ) == 0 )
+              {
+                displayName = elm.attribute( "value" );
+                break;
+              }
+            }
+            fidDisplayNameMap.insert( feature.id(), displayName );
```
Comment (rouault) [inline src/server/services/wms/qgswmsrenderer.cpp:2901]: Is it possible that for a given feature displayName wouldn't be set ? If so, would we report an empty string, or nothing ? Not sure what is the desired behavior, and if that matters...

Besides that, LGTM

**Review by rouault — APPROVED** [review]

File: src/server/services/wms/qgswmsrenderer.cpp (hunk 1 above)
Comment (elpaso) [reply src/server/services/wms/qgswmsrenderer.cpp:2901]: I think it's possible even if probably rare, the display name comes from the evaluation of an user-defined expression.
