### PR TITLE
show authid for instead of 'WGS84' text in the Copy Coordinate context menu (fix #37226)

### LINKED ISSUE #37226: Inconsequence in CRS-names/id's in Copy Coordinate in MapCanvas
I truly like the new(?) context menu in the mapcanvas "Copy Coordinate" and the fact that you can copy 2 (? please make it 3 or 4 :-) ) different crs coordinates.

But if you have a project CRS other then EPSG:4326, the fixed alternative is shown as WGS84?

Screenshot-20200615132846-549x224

Should that not show a EPSG-code instead of the string WGS84? Or is this on purpose? And is this actually not a CRS?

In the QGIS's own CRS list WGS84 is not very conclusive:

Screenshot-20200615132737-617x557

And IF you happen to have a project CRS EPSG:4326, it is shown as EPSG:4326 and for reference I added another 'WGS84'-named crs:

Screenshot-20200615133044-754x202

But as said, maybe I'm just plain wrong and WGS84 is meant to be there...

### PR DESCRIPTION
**Pull request by alexbruy**
## Description
Show CRS authid "EPSG:4326" instead of "WGS84" text in the "Copy Coordinate" context menu. This not only homogenizes this menu item with the way how custom CRS is shown but also avoids possible confusion by make it clear which WGS84 variant is used.

Fixes #37226.

Before
зображення
After
зображення

### CODE REVIEW

**Review by lbartoletti — APPROVED** [review]

File: src/gui/qgsmapcanvas.cpp [hunk 1]
```diff
@@ -1114,8 +1114,9 @@ void QgsMapCanvas::showContextMenu( QgsMapMouseEvent *event )
   };
 
   addCoordinateFormat( tr( "Map CRS — %1" ).arg( mSettings.destinationCrs().userFriendlyIdentifier( QgsCoordinateReferenceSystem::ShortString ) ), mSettings.destinationCrs() );
-  if ( mSettings.destinationCrs() != QgsCoordinateReferenceSystem( QStringLiteral( "EPSG:4326" ) ) )
-    addCoordinateFormat( tr( "WGS84" ), QgsCoordinateReferenceSystem( QStringLiteral( "EPSG:4326" ) ) );
+  QgsCoordinateReferenceSystem wgs84( QStringLiteral( "EPSG:4326" ) );
+  if ( mSettings.destinationCrs() != wgs84 )
+    addCoordinateFormat( wgs84.userFriendlyIdentifier( QgsCoordinateReferenceSystem::ShortString ), wgs84 );
```
Comment (nyalldawson) [inline src/gui/qgsmapcanvas.cpp:1119]: Can i suggest using the medium string for both these? Ie 
```suggestion
    addCoordinateFormat( wgs84.userFriendlyIdentifier( QgsCoordinateReferenceSystem::MediumString ), wgs84 );
```

That is "EPSG:4326 - WGS 84" (and "EPSG:3857 - WGS 84 / Pseudo-Mercator"). In my training experience a surprising number of users don't have any mental mapping between raw epsg codes and their meaning.

Comment (alexbruy) [reply src/gui/qgsmapcanvas.cpp]: Done for all occurrences in the Copy Coordinate context menu.

**Review by nyalldawson — APPROVED** [review]
