### PR TITLE
[symbology] Fix group layer not rendering properly when magnifier != 100% or when effect is on

### LINKED ISSUE #48324: When render layer as a group is checked in and draw effects is active, layout map items rendering fail
### What is the bug or the crash?

Screencast [click to download the video and use VLC or something, the browser fails! :)](https://user-images.githubusercontent.com/1728657/164655239-a3d8019a-26be-4391-b9c8-2710354ea1c4.mp4)

As seen above, if a group's [x] render layer as a group is checked and draw effects is active, the group's rendering glitches out when drawing a layout map item.

### Steps to reproduce the issue

1. Open the following test project: [group_glitch.zip](https://github.com/qgis/QGIS/files/8538749/group_glitch.zip)
2. Open the layout in that project
3. Zoom in and out of the layout sheet, notice the rendering glitch on the satellite imagery
 

### Versions

QGIS master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This PR fixes #48324, whereas a group that's rendered as a group layer would not  display _raster layers_ properly when zooming in and out in the layout designer, as well as the main map canvas when magnifier wasn't 100%.

The long story short here is that the raster layer renderer code (sitting in QgsRasterDrawer) was using the painter's device logical DPI value, which is not always reliable. For e.g., when a group layer had effects enabled, the painter gets replaced (https://github.com/qgis/QGIS/blob/master/src/core/qgsgrouplayerrenderer.cpp#L76) from the original one (attached to a QImage which holds the correct logical DPI information) to a temporary one bound to a QPicture (https://github.com/qgis/QGIS/blob/master/src/core/effects/qgspainteffect.cpp#L100), which has a static DPI value of 96. This messed with the raster renderer, who prior to this PR relied on a DPI value that reflects the rendering context setting.

The solution is to switch away from the unreliable painter device value to the QgsRenderContext::scaleFactor() value.

A few lines of code changed, and things behave _much_ better.

### CODE REVIEW

**Comment by nirvn** [comment]
(No need for a backport as the feature was introduced post current 3.22 LTR)

File: src/core/raster/qgsrasterdrawer.h [hunk 1]
```diff
@@ -42,8 +42,9 @@ class CORE_EXPORT QgsRasterDrawer
      * The QgsRasterDrawer constructor.
      * \param iterator the raster iterator to fetch data from
      * \param dpiTarget the target \a dpi (dots per inch) to be taken into consideration when rendering
+     * \param scaleFactor the scale factor for the render to convert painter units to physical sizes
      */
-    QgsRasterDrawer( QgsRasterIterator *iterator, double dpiTarget = -1.0 );
+    QgsRasterDrawer( QgsRasterIterator *iterator, double dpiTarget = -1.0, double scaleFactor = -1.0 );
```
Comment (nyalldawson) [inline src/core/raster/qgsrasterdrawer.h:47]: It would be cleaner at this stage to pass on the whole render context to QgsRasterDrawer. How do you feel about deprecating this constructor and making a new one:

    QgsRasterDrawer( QgsRasterIterator *iterator );

and then deprecating the current draw method and making one:

        void draw( QgsRenderContext& context, QgsRasterViewPort *viewPort, QgsRasterBlockFeedback *feedback = nullptr );

Comment (nirvn) [reply src/core/raster/qgsrasterdrawer.h:47]: Sounds good to me @nyalldawson

File: src/core/raster/qgsrasterdrawer.h [hunk 2]
```diff
@@ -41,9 +41,16 @@ class CORE_EXPORT QgsRasterDrawer
     /**
      * The QgsRasterDrawer constructor.
      * \param iterator the raster iterator to fetch data from
-     * \param dpiTarget the target \a dpi (dots per inch) to be taken into consideration when rendering
+     * \param dpiTarget the target dpi (dots per inch) to be taken into consideration when rendering
+     * \deprecated since QGIS 3.28
      */
-    QgsRasterDrawer( QgsRasterIterator *iterator, double dpiTarget = -1.0 );
+    Q_DECL_DEPRECATED QgsRasterDrawer( QgsRasterIterator *iterator, double dpiTarget );
```
Comment (nyalldawson) [inline src/core/raster/qgsrasterdrawer.h:47]:
```suggestion
    Q_DECL_DEPRECATED QgsRasterDrawer( QgsRasterIterator *iterator, double dpiTarget ) SIP_DEPRECATED;
```

File: src/core/raster/qgsrasterdrawer.h [hunk 3]
```diff
@@ -41,9 +41,16 @@ class CORE_EXPORT QgsRasterDrawer
     /**
      * The QgsRasterDrawer constructor.
      * \param iterator the raster iterator to fetch data from
-     * \param dpiTarget the target \a dpi (dots per inch) to be taken into consideration when rendering
+     * \param dpiTarget the target dpi (dots per inch) to be taken into consideration when rendering
+     * \deprecated since QGIS 3.28
```
Comment (nyalldawson) [inline src/core/raster/qgsrasterdrawer.h:45]:
```suggestion
     * \deprecated since QGIS 3.28. Use the constructor without the \a dpiTarget argument instead, as DPI is now handled by the draw() method which accepts a QgsRenderContext.
```

File: src/core/raster/qgsrasterdrawer.h [hunk 4]
```diff
@@ -54,6 +61,15 @@ class CORE_EXPORT QgsRasterDrawer
...
     void draw( QPainter *p, QgsRasterViewPort *viewPort, const QgsMapToPixel *qgsMapToPixel, QgsRasterBlockFeedback *feedback = nullptr );
 
+    /**
+     * Draws raster data.
+     * \param context the render context
+     * \param viewPort viewport to render
+     * \param feedback optional raster feedback object for cancellation/preview.
+     * \since QGIS 3.28
+     */
+    void draw( QgsRenderContext *context, QgsRasterViewPort *viewPort, QgsRasterBlockFeedback *feedback = nullptr );
```
Comment (nyalldawson) [inline src/core/raster/qgsrasterdrawer.h:71]:
```suggestion
    void draw( QgsRenderContext &context, QgsRasterViewPort *viewPort, QgsRasterBlockFeedback *feedback = nullptr );
```

File: src/core/raster/qgsrasterdrawer.h [hunk 5]
```diff
@@ -54,6 +61,15 @@ class CORE_EXPORT QgsRasterDrawer
      */
     void draw( QPainter *p, QgsRasterViewPort *viewPort, const QgsMapToPixel *qgsMapToPixel, QgsRasterBlockFeedback *feedback = nullptr );
```
Comment (nyalldawson) [inline src/core/raster/qgsrasterdrawer.h:62]: Can we deprecate this one?

Comment (nirvn) [reply src/core/raster/qgsrasterdrawer.h:62]: It's used in other places where it seems it's useful to have that version of draw (e.g. QgsRasterLayer::draw), so maybe we can leave it as is?

**Comment by nyalldawson** [comment]
Why are you replacing the test images here instead of updating the masks?

**Review by nyalldawson — APPROVED** [review]
