### PR TITLE
Anonymise  logs when loading a project from postgresql

### LINKED ISSUE #54437: Database string connection visible in the message bar/QGIS logs
### What is the bug or the crash?

Task complete INFO reveals string connection when the project is loaded from the postgres database. This is first pushed in the message bar and then you can find it in the QGIS logs.
If there is no way to prevent this or alter the message, this could be considered a security issue from my standpoint. 
e.g.
2023-08-31T14:10:11     INFO    Task complete : Loading “postgresql://user:password@host:5432?sslmode=disable&dbname=database&schema=schema&project=project”

### Steps to reproduce the issue

1. Save QGIS project into postgres
2. Load the project from the postgres
3. Check the message bar (appears only for 1s) and the logs.

### Versions

QGIS version
3.28.10-Firenze
QGIS code revision
e2edb9c468
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
DigitizingTools
1.5.2
go2streetview
8.6
pluginbuilder3
3.2.1
plugin_reloader
0.9.3
quick_map_services
0.19.33
StreetView
3.2
ZoomToPostcode
1.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pblottiere**
## Description

Fixes https://github.com/qgis/QGIS/issues/54437

### CODE REVIEW

File: src/core/qgsdatasourceuri.cpp [hunk 1]
```diff
@@ -248,6 +248,17 @@ QString QgsDataSourceUri::removePassword( const QString &aUri )
     regexp.setPattern( QStringLiteral( "/.*@" ) );
     safeName.replace( regexp, QStringLiteral( "/@" ) );
   }
+  else if ( aUri.contains( QLatin1String( "postgresql:" ) ) )
+  {
+    // postgresql://user:pwd@...
+    regexp.setPattern( QStringLiteral( "/.*@" ) );
+    const QString matched = regexp.match( aUri ).capturedView().toString();
```
Comment (troopa81) [inline src/core/qgsdatasourceuri.cpp:255]:
```suggestion
    const QString matched = regexp.match( aUri ).captured();
```

**Review by troopa81 — APPROVED** [review]
Just a cosmetic modification

File: tests/src/core/testqgsdatasourceuri.cpp [hunk 2]
```diff
@@ -524,5 +525,11 @@ void TestQgsDataSourceUri::checkParameterKeys()
   QVERIFY( uri.parameterKeys().contains( QLatin1String( "bar" ) ) );
 }
 
+void TestQgsDataSourceUri::checkRemovePassword()
+{
+  const QString uri = QgsDataSourceUri::removePassword( QStringLiteral( "postgresql://user:password@127.0.0.1:5432?dbname=test" ) );
+  QCOMPARE( uri, QStringLiteral( "postgresql://user@127.0.0.1:5432?dbname=test" ) );
```
Comment (Gustry) [inline tests/src/core/testqgsdatasourceuri.cpp:531]: Side request, I would be nice to have an option in `QgsDataSourceUri::removePassword` to actually not "remove" the password but replacing it by `XXXXXXXXX`. I got one day confused about the logs itself in another area of QGIS server about not knowing if the password was really missing from the datasource or just removed by this function :)

**Review by Gustry — APPROVED** [review]
LGTM, thanks.

File: src/core/qgsdatasourceuri.cpp [hunk 3]
```diff
@@ -248,6 +248,17 @@ QString QgsDataSourceUri::removePassword( const QString &aUri )
...
+
+    QString anonymised = matched.split( QStringLiteral( ":" ) )[0];
+    anonymised.append( QStringLiteral( "@" ) );
```
Comment (uclaros) [inline src/core/qgsdatasourceuri.cpp:258]: This logic considers that both `user` and `pwd` are present in the uri.
If `pwd` is omitted (eg `trust` in `pg_hba.conf`) the result will be `postgresql://user@@...`

**Review by uclaros — COMMENTED** [review]
The uri with the clear text password is also visible in the _Open Recent_ menu items as well as in the project properties

File: src/core/qgsdatasourceuri.cpp (hunk 1 above)
Comment (pblottiere) [reply src/core/qgsdatasourceuri.cpp]: Done, thanks

File: tests/src/core/testqgsdatasourceuri.cpp (hunk 2 above)
Comment (pblottiere) [reply tests/src/core/testqgsdatasourceuri.cpp]: I added a `hide` parameter to `removePassword()` static method

File: src/core/qgsdatasourceuri.cpp (hunk 3 above)
Comment (pblottiere) [reply src/core/qgsdatasourceuri.cpp]: Yes indeed. It's fixed and I added a unit test accordingly.

**Comment by pblottiere** [comment]
> The uri with the clear text password is also visible in the Open Recent menu items as well as in the project properties

@uclaros Connection strings are now anonymized in project properties and welcome page. Thanks for the input :+1:

**Comment by Gustry** [comment]
Nice update, thanks !
Do you think it can be backported ? It would avoid any confusion about missing password.

I can review all usages of `removePassword`, I added 2 I think : server and UI recently.

**Comment by pblottiere** [comment]
Hello @troopa81 :hand:,

Do you agree with the last modifications? Because CI is green so I can merge.

File: src/core/qgsdatasourceuri.h [hunk 4]
```diff
@@ -188,7 +188,7 @@ class CORE_EXPORT QgsDataSourceUri
     /**
      * Removes the password element from a URI.
      */
-    static QString removePassword( const QString &aUri );
+    static QString removePassword( const QString &aUri, bool hide = false );
```
Comment (troopa81) [inline src/core/qgsdatasourceuri.h:191]: Can we complete the documentation?

**Review by troopa81 — COMMENTED** [review]
One doc comment, the rest looks good

File: src/core/qgsdatasourceuri.h (hunk 4 above)
Comment (pblottiere) [reply src/core/qgsdatasourceuri.h:196]: Yes, thanks for pointing that out :+1:

**Review by troopa81 — APPROVED** [review]
