### PR TITLE
ATLAS: LEGEND support clipping

### LINKED ISSUE #54654: taxon legend from map whis atlas
### What is the bug or the crash?

Hello,

I make an atlas based on the layer "Périmètre de l'OAP"
- objects in this layer can be close to each other so that on a map of "polygon 1", part of the "polygon 2" can appear
- the layer "Périmètre de l'OAP" is configured in the atlas so that only the one concerned by the atlas entity appears: it works well (black arrow from map - "cartes 1, 2 and 3" in exemple : [https://geoscope.fr/nextcloud/index.php/s/t6knHdtDHC6EgfE](url)
- the layer "Enjeux OAP surf UD" is configured so that they appear completely even if none of their polygon intersects the targeted polygon. Objects appear logically in legend (blue arrow) it works well
- layer "Enjeux OAP surf VE" should only appear in the targeted perimeter: it works BUT in legend appears the taxa "verger" and "espace vert urbain" which are hidden because only concerns the perimeter of the neighboring object. The objects are well hidden, but they appear in legend, which I do not want (red arrow).
The two taxa "verger" and "espace vert urbain" are not visible, they should not appear in legend. Is this a bug?

### Steps to reproduce the issue

Screen capture for exemple : [https://geoscope.fr/nextcloud/index.php/s/t6knHdtDHC6EgfE](url)

carte 1 : map canvas whis "perimetre 1" and "perimetre 2"
carte 2 : relation between object on map and taxon of legend
carte 3 : detail of the configuration of layers in the atlas

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Version de QGIS | 3.32.2-Lima | Révision du code | c0b8833964
-- | -- | -- | --
Version de Qt | 5.15.3
Version de Python | 3.9.5
Version de GDAL/OGR | 3.7.1
Version de Proj | 9.2.1
Version de la base de données du registre EPSG | v10.088 (2023-05-13)
Version de GEOS | 3.12.0-CAPI-1.18.0
Version de SQLite | 3.41.1
Version de PDAL | 2.5.5
Version du client PostgreSQL | 15.2
Version de SpatiaLite | 5.1.0
Version de QWT | 6.1.6
Version de QScintilla2 | 2.13.1
Version de l'OS | Windows 10 Version 2009

</body></html>Version de QGIS
3.32.2-Lima
Révision du code
[c0b8833964](https://github.com/qgis/QGIS/commit/c0b8833964)
Version de Qt
5.15.3
Version de Python
3.9.5
Version de GDAL/OGR
3.7.1
Version de Proj
9.2.1
Version de la base de données du registre EPSG
v10.088 (2023-05-13)
Version de GEOS
3.12.0-CAPI-1.18.0
Version de SQLite
3.41.1
Version de PDAL
2.5.5
Version du client PostgreSQL
15.2
Version de SpatiaLite
5.1.0
Version de QWT
6.1.6
Version de QScintilla2
2.13.1
Version de l'OS
Windows 10 Version 2009

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Fix #54654

Working on the tests...

@Geoscope19 please test the artifact when ready.

### CODE REVIEW

**Comment by Geoscope19** [comment]
I’m a new, I don’t understand what to do. Could you explain to me how to proceed?

**Comment by elpaso** [comment]
> I’m a new, I don’t understand what to do. Could you explain to me how to proceed?

Sure, you couldn't possibly know, it is well hidden.

Download this package on windows, unzip it twice in a folder of your choice and run the qgis exe.
 
https://github.com/qgis/QGIS/suites/16418208318/artifacts/938243476

This is a QGIS build automatically created with the changes in this PR so you can test the changes.

**Comment by Geoscope19** [comment]
@elpaso Thank you.
Impeccable, the bug is fixed :-)

**Comment by elpaso** [comment]
> @elpaso Thank you. Impeccable, the bug is fixed :-)

Thanks for checking!

**Comment by Geoscope19** [comment]
It is quite normal, it is you who are struggling to improve Qgis, it is rather for me to thank you for all the work

File: src/core/layout/qgslayoutitemlegend.cpp [hunk 1]
```diff
@@ -1133,14 +1133,29 @@ void QgsLayoutItemLegend::doUpdateFilterByMap()
...
 
+    QList<QgsMapLayer *> layersToClip;
+    if ( !atlasGeometry.isNull() && mMap->atlasClippingSettings()->enabled() )
+    {
+      layersToClip = mMap->atlasClippingSettings()->layersToClip();
+      for ( QgsMapLayer *layer : std::as_const( layersToClip ) )
+      {
+        QList<QgsMapLayer *> mapLayers { filterSettings.mapSettings().layers( true ) };
+        mapLayers.removeAll( layer );
+        filterSettings.mapSettings().setLayers( mapLayers );
```
Comment (troopa81) [inline src/core/layout/qgslayoutitemlegend.cpp:1148]: Why do we need that ? And why override it in mapsettings for each layer?

File: src/core/layout/qgslayoutitemlegend.cpp [hunk 2]
```diff
@@ -1133,14 +1133,29 @@ void QgsLayoutItemLegend::doUpdateFilterByMap()
...
-    const QgsGeometry atlasGeometry = mInAtlas ? mLayout->reportContext().currentGeometry( mapSettings.destinationCrs() ) : QgsGeometry();
+    const QgsGeometry atlasGeometry { mLayout->reportContext().currentGeometry( mapSettings.destinationCrs() ) };
 
     QgsLayerTreeFilterSettings filterSettings( mapSettings );
 
+    QList<QgsMapLayer *> layersToClip;
+    if ( !atlasGeometry.isNull() && mMap->atlasClippingSettings()->enabled() )
+    {
+      layersToClip = mMap->atlasClippingSettings()->layersToClip();
+      for ( QgsMapLayer *layer : std::as_const( layersToClip ) )
```
Comment (troopa81) [inline src/core/layout/qgslayoutitemlegend.cpp:1144]:
```suggestion
      const QList<QgsMapLayer *>  layersToClip = mMap->atlasClippingSettings()->layersToClip();
      for ( QgsMapLayer *layer : layersToClip) 
```

We can reduce the scope of layersToClip here

File: src/core/layout/qgslayoutitemlegend.cpp [hunk 3]
```diff
@@ -1133,14 +1133,29 @@ void QgsLayoutItemLegend::doUpdateFilterByMap()
 
     mapSettings.setExpressionContext( createExpressionContext() );
 
-    const QgsGeometry atlasGeometry = mInAtlas ? mLayout->reportContext().currentGeometry( mapSettings.destinationCrs() ) : QgsGeometry();
+    const QgsGeometry atlasGeometry { mLayout->reportContext().currentGeometry( mapSettings.destinationCrs() ) };
```
Comment (troopa81) [inline src/core/layout/qgslayoutitemlegend.cpp:1136]: if we remove the condition on `mInAtlas`, on clipping with coming from `atlasClippingSettings()` would work, not the one coming from the `mFilterLegendByAtlasCheckBox` in `QgsLayoutLegendWidget` ([see](https://github.com/qgis/QGIS/blob/master/src/gui/layout/qgslayoutlegendwidget.cpp#L1226) ), no?

**Review by troopa81 — COMMENTED** [review]
I have to admit I'm no expert in this part of the code, sorry if I failed to understand the cause of some of this modifications.

File: src/core/layout/qgslayoutitemlegend.cpp (hunk 1 above)
Comment (elpaso) [reply src/core/layout/qgslayoutitemlegend.cpp:1148]: It took me a while to get there too :)

Because of the convoluted logic inside the filter settings object which holds a mapsettings member object: it takes the layer from mapsettings with higher priority so we need to remove the layers we want to filter from the mapsettings if we want to use the overrided configuration from filtersettings.

File: src/core/layout/qgslayoutitemlegend.cpp (hunk 3 above)
Comment (elpaso) [reply src/core/layout/qgslayoutitemlegend.cpp:1136]: I didn't really remove the condition, I just moved down to where it was used: https://github.com/qgis/QGIS/pull/54692/files#diff-e7d9625a78a678e8657e01df0b53ef2c124469d2a30ef3977c13a8bc03ce14f1R1178  

IMHO it is much clearer than relying on the null geometry for the `if` banching.

File: src/core/layout/qgslayoutitemlegend.cpp (hunk 2 above)
Comment (elpaso) [reply src/core/layout/qgslayoutitemlegend.cpp:1144]: Yes, the `std::as_const` should stay though even if it is redundant: I was told several times from other developers that it makes things clearer.

Comment (elpaso) [reply src/core/layout/qgslayoutitemlegend.cpp:1144]: Question: isn't my original version slightly faster? I don't know if the compiler can optimize it.

File: src/core/layout/qgslayoutitemlegend.cpp (hunk 1 above)
Comment (troopa81) [reply src/core/layout/qgslayoutitemlegend.cpp:1148]: OK.  I get it!

File: src/core/layout/qgslayoutitemlegend.cpp (hunk 2 above)
Comment (troopa81) [reply src/core/layout/qgslayoutitemlegend.cpp:1144]: Yes, we can keep the std::as_const indeed, it doesn't harm.

Not sure to understand why it would be slighly faster. Anyway it is purely cosmetic and non blocking for merge

**Review by troopa81 — APPROVED** [review]

File: src/core/layout/qgslayoutitemlegend.cpp (hunk 2 above)
Comment (elpaso) [reply src/core/layout/qgslayoutitemlegend.cpp:1144]: > Yes, we can keep the std::as_const indeed, it doesn't harm.
> 
> Not sure to understand why it would be slighly faster. Anyway it is purely cosmetic and non blocking for merge

because the assignment down inside the loop is done multiple times instead of once before the loop.

Comment (troopa81) [reply src/core/layout/qgslayoutitemlegend.cpp:1144]: my comment was just to move the declaration at the same line of the assignment, not inside the loop. But nevermind that's not a big deal.
