### PR TITLE
[3d] Do not include private header from public header

### LINKED ISSUE #57294: Private header is included in public header
### What is the bug or the crash?

When including `qgs3dutils.h` in a custom application the build will fail because it includes a private header `qgsraycastingutils_p.h`.

### Steps to reproduce the issue

1. Create an app
2. Include `qgs3dutils.h`
3. Build

### Versions

at least 3.34 and 3.36

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Introduced in https://github.com/qgis/QGIS/commit/b371267fbe117ecf54f56dd8c9948db0d89dfdd1

CC @uclaros

### PR DESCRIPTION
**Pull request by m-kuhn**
Fixes https://github.com/qgis/QGIS/issues/57294

### CODE REVIEW

File: src/3d/qgsraycastingutils_p.h [hunk 1]
```diff
@@ -27,10 +27,8 @@
 // version without notice, or even be removed.
 //
 
-#include "qgsfeatureid.h"
+#include "qgsraycastingutils.h"
 #include <QSize>
```
Comment (m-kuhn) [inline src/3d/qgsraycastingutils_p.h:31]:
```suggestion
```

**Review by nyalldawson — APPROVED** [review]

File: src/3d/qgsraycastingutils.h [hunk 2]
```diff
@@ -0,0 +1,69 @@
+/***************************************************************************
+  qgsraycastingutils.h
+  --------------------------------------
+  Date                 : April 2024
+  Copyright            : (C) 2014 by Matthias Kuhn
```
Comment (uclaros) [inline src/3d/qgsraycastingutils.h:5]:
```suggestion
  Copyright            : (C) 2024 by Matthias Kuhn
```

**Review by uclaros — APPROVED** [review]
Thanks @m-kuhn !
