### PR TITLE
Fix QgsCoordinateFormatter rounding error when precision >= 8

### LINKED ISSUE #52927: Incorrect coordinate formatting with QgsCoordinateFormatter.format()
### What is the bug or the crash?

At some precision values, the [QgsCoordinateFormatter.format()](https://qgis.org/pyqgis/master/core/QgsCoordinateFormatter.html#qgis.core.QgsCoordinateFormatter.format) formatting results are wrong!

### Steps to reproduce the issue

Run this code in the `QGIS Python console`:

``` python
y, x = 61.01896450, 69.08860610
point = QgsPointXY(x, y)
format_flags = QgsCoordinateFormatter.FlagDegreesUseStringSuffix
coords_format = QgsCoordinateFormatter.FormatDegreesMinutesSeconds

for precision in range(7, 11):
    print(QgsCoordinateFormatter.format(point, coords_format, precision, format_flags, Qgis.CoordinateOrder.YX), f'precision = {precision}')
```
Output:

``` python
61°1′8,2722000″N 69°5′18,9819600″E precision = 7
61°1′8,27220000″N 69°6′0,00000000″E precision = 8  # the second coordinate is incorrect
61°2′0,000000000″N 69°6′0,000000000″E precision = 9  #  all coordinates are wrong
61°1′8,2722000000″N 69°5′18,9819600000″E precision = 10
```

Expected result:
``` python
61°1′8,2722000″N 69°5′18,9819600″E precision = 7
61°1′8,27220000″N 69°5′18,98196000″E precision = 8
61°1′8,272200000″N 69°5′18,981960000″E precision = 9
61°1′8,2722000000″N 69°5′18,9819600000″E precision = 10
```
Another user confirmed the error:
https://gis.stackexchange.com/questions/458583/qgis-3-incorrect-rounding-with-qgscoordinateformatter-format/458623#comment748795_458583

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.30.1-'s-Hertogenbosch | QGIS code revision | 9035a01e
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
Compiled against GDAL/OGR | 3.6.3 | Running against GDAL/OGR | 3.6.4
PROJ version | 9.2.0
EPSG Registry database version | v10.082 (2023-02-06)
GEOS version | 3.11.2-CAPI-1.17.2
SQLite version | 3.41.1
PDAL version | 2.5.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
AnotherDXF2Shape | 1.2.6
AppendFeaturesToLayer | 1.4.0
ContrastHomogenizer | 3.2
fast_field_filler | 1.0
FreehandRasterGeoreferencer | 0.8.3
GisEC | 0.0.30
Go2NextFeature3 | 2.1
latlontools | 3.6.9
loadthemall | 3.3.0
MapsPrinter | 0.9
pluginbuilder3 | 3.2.1
PluginLoadTimes | 3.0.2
plugin_reloader | 0.9.3
profiletool | 4.2.5
qgsAzimuth | 0.9.15
quick_map_services | 0.19.33
rasterstats | 0.4.3
scheme_builder | 0.1
db_manager | 0.1.20
processing | 2.12.99

</body></html>QGIS version
3.30.1-'s-Hertogenbosch
QGIS code revision
[9035a01e](https://github.com/qgis/QGIS/commit/9035a01e)
Qt version
5.15.3
Python version
3.9.5
Compiled against GDAL/OGR
3.6.3
Running against GDAL/OGR
3.6.4
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
AnotherDXF2Shape
1.2.6
AppendFeaturesToLayer
1.4.0
ContrastHomogenizer
3.2
fast_field_filler
1.0
FreehandRasterGeoreferencer
0.8.3
GisEC
0.0.30
Go2NextFeature3
2.1
latlontools
3.6.9
loadthemall
3.3.0
MapsPrinter
0.9
pluginbuilder3
3.2.1
PluginLoadTimes
3.0.2
plugin_reloader
0.9.3
profiletool
4.2.5
qgsAzimuth
0.9.15
quick_map_services
0.19.33
rasterstats
0.4.3
scheme_builder
0.1
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### PR DESCRIPTION
**Pull request by YoannQDQ**
- Fix #52927

## Description

Fix an integer overflow in `QgsCoordinateFormatter::formatXAsDegreesMinutesSeconds` and `QgsCoordinateFormatter::formatYAsDegreesMinutesSeconds` which caused rounding errors when precision was >= 8. 

This was already fixed for `QgsGeographicCoordinateNumericFormat` (see https://github.com/qgis/QGIS/commit/a70a1d90ad4e41f1a01d305a7ca952754df03f61)

Update the tests accordingly

### CODE REVIEW

File: src/core/qgscoordinateformatter.cpp [hunk 1]
```diff
@@ -20,6 +20,7 @@
 
 #include <QObject> // for tr()
 #include <QLocale>
+#include <QDebug>
```
Comment (nicogodet) [inline src/core/qgscoordinateformatter.cpp:23]: Still needed ?

Comment (YoannQDQ) [reply src/core/qgscoordinateformatter.cpp:23]: Nope. My bad.

**Review by nyalldawson — APPROVED** [review]
