### PR TITLE
[OAPIF] Handle features with complex attribute of QMap type (fixes #54275)

### LINKED ISSUE #54275: Complex Attributes in OGC API Feature-Items have empty content
### What is the bug or the crash?

If an item of the result of an OGC API Feature query contains a complex property, that means a property with sub-nodes, the content of the resulting field is always empty.

### Steps to reproduce the issue

Call an OGC-Feature-API which delivers a property with a complex result, e.g. the property _center_ in the following example:
```
  {
            "type": "Feature",
            "id": "item123",
            "geometry": {
                "type": "Polygon",
                "coordinates": [
                    [
                       [...],
                       [...]
                    ]
                ]
            },
            "geometry_name": "geom",
            "properties": {
                "prop1": 2,
                "prop2": "abc",
                "center": {
                    "type": "Point",
                    "coordinates": [
                        6.50,
                        51.80
                    ]
                }
            },
            "bbox": [...]
        }
```
This happens if delivering a polygon-layer with a representative point with geoserver.

If inserting this layer into QGIS, all columns are generated correctly, the column "center" as Type=Map, Type Name=JSON. But the content of field _center_ is empty for all features.

### Versions

QGIS version
3.32.1-Lima
QGIS code revision
4a078ecf63
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
excel_sync
3.6
pluginbuilder3
3.2.1
plugin_reloader
0.9.1
qgis2web
3.16.0
topojson_writer
0.1.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

File: src/providers/wfs/qgsbackgroundcachedfeatureiterator.cpp [hunk 1]
```diff
@@ -945,6 +946,8 @@ void QgsBackgroundCachedFeatureIterator::copyFeature( const QgsFeature &srcFeatu
         dstFeature.setAttribute( i, v );
       else if ( fieldType == QVariant::DateTime && !QgsVariantUtils::isNull( v ) )
         dstFeature.setAttribute( i, QVariant( QDateTime::fromMSecsSinceEpoch( v.toLongLong() ) ) );
+      else if ( fieldType == QVariant::Map && !QgsVariantUtils::isNull( v ) )
+        dstFeature.setAttribute( i, QVariant( QJsonDocument::fromJson( v.toString().toUtf8() ).toVariant() ) );
```
Comment (m-kuhn) [inline src/providers/wfs/qgsbackgroundcachedfeatureiterator.cpp:950]:
```suggestion
        dstFeature.setAttribute( i, QJsonDocument::fromJson( v.toString().toUtf8() ).toVariant() );
```

No need for this constructor I think?

**Review by m-kuhn — APPROVED** [review]

File: src/providers/wfs/qgsbackgroundcachedfeatureiterator.cpp (hunk 1 above)
Comment (rouault) [reply src/providers/wfs/qgsbackgroundcachedfeatureiterator.cpp]: indeed, fixed

**Comment by rouault** [comment]
backport in https://github.com/qgis/QGIS/pull/54679
