### PR TITLE
[server][wms] Fix #60216 missing transformation ctx

### LINKED ISSUE #60216: QGIS Server does not respect datum transformation
### What is the bug or the crash?

GetMap WMS request to QGIS server shows image with features shifted by few meters comparing to map that is shown in QGIS Desktop when I open the same QGS file.

The QGS file contains two vector layers, layer `vaclav-epsg-3857` with four points in EPSG:3857 (green crosses) and layer `vaclav-epsg-5514` with the same four points in EPSG:5514 (red circles). The project's CRS is EPSG:3857. One of suggested datum transformations is used:

Image

If I open the QGS file in QGIS Desktop v3.40.2, I see points from both layers placed in the same location:

Image

However, if I publish the same QGS file to QGIS Server v3.40.2 and send WMS GetMap request, e.g.
```
http://localhost:8090/qgis/?MAP=/qgis/data/vaclav.qgs&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=1606261.367126520025%2C6460065.113021261059%2C1606371.941027208464%2C6460150.805113065057&CRS=EPSG%3A3857&WIDTH=1032&HEIGHT=799&LAYERS=OpenStreetMap,vaclav-epsg-3857,vaclav-epsg-5514&STYLES=&FORMAT=image%2Fpng&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi%3A96&TRANSPARENT=TRUE
```
four points in `vaclav-epsg-5514` layer (red circles) are shifted by several meters:

Image

I expect that points in GetMap request should be in the same location as they are in QGIS Desktop. I guess it's because QGIS Server somehow ignores the selected datum transformation.

I did not find similar bug among open issues. However I found this StackExchange post from 2020 that suggests that the same issue was also with QGIS 3.10: https://gis.stackexchange.com/questions/364744/datum-transformation-in-qgis-server-3-10

### Steps to reproduce the issue

1. Download and unzip file [data.zip](https://github.com/user-attachments/files/18504232/data.zip)
2. Open `vaclav.qgs` in QGIS Desktop. You should see four green crosses and four red circles from placed in the same locations:
  
Image
3. Publish the same QGS file to QGIS Server. You can use [containerized](https://docs.qgis.org/3.34/en/docs/server_manual/containerized_deployment.html) QGIS Server (this is how I am using it).
4. Send WMS GetMap request, e.g.   
   ```
   http://localhost:8090/qgis/?MAP=/qgis/data/vaclav.qgs&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=1606261.367126520025%2C6460065.113021261059%2C1606371.941027208464%2C6460150.805113065057&CRS=EPSG%3A3857&WIDTH=1032&HEIGHT=799&LAYERS=OpenStreetMap,vaclav-epsg-3857,vaclav-epsg-5514&STYLES=&FORMAT=image%2Fpng&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi%3A96&TRANSPARENT=TRUE
   ```  
(you probably need to adjust `MAP` parameter value to correct path).
5. See the error, four points in `vaclav-epsg-5514` layer (red circles) are shifted by several meters:  
   
Image

### Versions

All QGS file, QGIS Desktop and QGIS Server are v3.40.2. This StackExchange post from 2020 suggests that the issue was also with QGIS 3.10, so maybe it's quite old: https://gis.stackexchange.com/questions/364744/datum-transformation-in-qgis-server-3-10

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
fix #60216

### CODE REVIEW

File: src/server/services/wms/qgswmsrenderer.cpp [hunk 1]
```diff
@@ -1424,6 +1424,8 @@ namespace QgsWms
     //then set destinationCrs
     mapSettings.setDestinationCrs( outputCRS );
 
+    mapSettings.setTransformContext( QgsProject::instance()->transformContext() );
```
Comment (nyalldawson) [inline src/server/services/wms/qgswmsrenderer.cpp:1427]: Elsewhere in this method I see `mProject` used, not QgsProject::instance.

Comment (elpaso) [reply src/server/services/wms/qgswmsrenderer.cpp:1427]:
```suggestion
    mapSettings.setTransformContext( mProject->transformContext() );
```
yes: that works the same. A project pointer is also stored in wms context object, we have plenty of choices.

**Review by nyalldawson — APPROVED** [review]
