### PR TITLE
Fix drag and drop to GDB results in columns shifted by one

### LINKED ISSUE #51435: Importing Data into a QGIS Created File Based Geodatabase
### What is the bug or the crash?

When importing data into File Based Geodatabse (created in QGIS) the attributes shift one column to the left. 

In the screenshot all the data should be in the column to the right. 

Screenshot from 2023-01-11 15-19-25

### Steps to reproduce the issue

1. Download this ESRI File Based Geodatabase: https://tnmap.tn.gov/NG911/TN_NG911.zip
2. Add Centerlines to QGIS 
3. Create File Based Geodatabase using the browser 
4. Drag and Drop the Centerline into the new File Geodatabase 
5. Open Attribute Table - In the newly imported layer - Pretype will be the names of roads. Everything shifts one column left. 
Example: 

Screenshot from 2023-01-11 15-29-16

### Versions

3.28.2 On Fedora (using the conda installer) and Windows 10

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

There is no problem with editing. The only problem seems to be importing this into a new file geodatabase. I can save it out to geopackage and I'm fine. I tried a ESRI File Based Geodatabase -> Geopackage -> QGIS Produced File Based Geodatbase and it still shifted the data one column to the left. .

### PR DESCRIPTION
**Pull request by nyalldawson**
Fixes #51435

@rouault  I'd love your thoughts here . While it works, I don't like this proposed fix and don't think this logic really should be in a place like this.

### CODE REVIEW

**Comment by rouault** [comment]
@nyalldawson I've an additional tuning to your pull request as a pull request on yours at https://github.com/nyalldawson/QGIS/pull/36

I've also done a fix in the OpenFileGDB driver in https://github.com/OSGeo/gdal/pull/7147. This is the same as what GeoPackage does when creating a field with the name of the FID column.
I'm not fully satisfied with having to put such hacks in drivers. Ideally QGIS should detect that it tries to create an attribute column with the same name as the FID column, and deal with that by moving the content of that attribute column to the FID special attribute. I've looked a bit at changing that but that looked more intimating than doing the fix/workaround in the OpenFileGDB driver

File: src/core/providers/ogr/qgsogrprovider.cpp [hunk 1]
```diff
@@ -300,6 +300,28 @@ Qgis::VectorExportResult QgsOgrProvider::createEmptyLayer( const QString &uri,
...
+#if GDAL_VERSION_NUM < GDAL_COMPUTE_VERSION(3, 6, 3)
+  // Temporary solution. Proper fix in https://github.com/OSGeo/gdal/pull/7147
+  if ( driverName == QLatin1String( "OpenFileGDB" ) )
+  {
+    QString fidColumn = QStringLiteral( "OBJECTID" );
+    for ( const QString &layerOption : layerOptions )
+    {
+      if ( layerOption.startsWith( QLatin1String( "FID=" ), Qt::CaseInsensitive ) )
+      {
+        fidColumn = layerOption.mid( strlen( "FID=" ) );
```
Comment (rouault) [inline src/core/providers/ogr/qgsogrprovider.cpp:313]:
```suggestion
        fidColumn = layerOption.mid( static_cast<int>( strlen( "FID=" ) ) );
```

**Review by rouault — APPROVED** [review]

**Comment by rouault** [comment]
looks good to me to be merged

**Comment by agiudiceandrea** [comment]
@nyalldawson @rouault it seems the issue is not completely fixed: see https://github.com/qgis/QGIS/issues/52017#issuecomment-1456034065

**Comment by agiudiceandrea** [comment]
Hi @nyalldawson, any news about the complete fix of the issue, since it seems it is not yet completely fixed as reported in https://github.com/qgis/QGIS/issues/52017#issuecomment-1456034065?
