### PR TITLE
[server] WMS GetLegendGr.. cascading size

### LINKED ISSUE #57422: QGIS Server: fixed width of 200 px of cascaded WMS layer legends
### What is the bug or the crash?

Hi there, 

I came across https://github.com/qgis/QGIS/issues/42063 and yippie, getting the legend of cascaded WMS layer is working again after a long time!

While testing this, I have discovered, that the resulting legend image of the requested layer has always a max width value of `200 px`. 
This does not make sense in my opinion, as it leads to labels which are to small to read, especially if the legend graphic of the original layer is much wider than `200 px`. 

So where is this value come from and why is it there?

My suggestion would be to just cascade the width and height of the original layer legend here instead of setting a fixed value.

Thanks for any reply!

### Steps to reproduce the issue

1. Setting up a QGIS project to publish via QGIS Server
2. include a WMS layer from an external OGC service
3. publish the project via QGIS Server
4. Request the legend image of the external wms layer with a GetLegendGraphic-Request

### Versions

3.34.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Fix #57422 by adjusting the legend size considering the cascaded legend image size.

### CODE REVIEW

File: src/core/layertree/qgslayertreemodellegendnode.h [hunk 1]
```diff
@@ -747,6 +747,14 @@ class CORE_EXPORT QgsWmsLegendNode : public QgsLayerTreeModelLegendNode
 
     void invalidateMapBasedData() override;
 
+    /**
+     *  Lazily initializes mImage
```
Comment (troopa81) [inline src/core/layertree/qgslayertreemodellegendnode.h:751]: We need get rid of  `mImage` in the documentation, and state that if synchronous is false, the returned image could be invalid, and it would require to wait for getLegendGraphicFinished/Errored/Progress signals.

We also need to make those signals public.

**Review by troopa81 — COMMENTED** [review]
Do you mind adding tests?

File: src/core/layertree/qgslayertreemodellegendnode.h (hunk 1 above)
Comment (elpaso) [reply src/core/layertree/qgslayertreemodellegendnode.h:751]: Given that the only usage is from server code, would it be more convenient to keep it private add a new method that fetches the image synchronously?

**Comment by elpaso** [comment]
> Do you mind adding tests?

Well, I considered that and IMHO it doesn't worth the effort, unless there is a way to not involve real network calls to a WMS server to get the legend graphic. AFAIK `fake_qgis_http_endpoint`  is not available in the image fetcher code.

File: src/core/layertree/qgslayertreemodellegendnode.h (hunk 1 above)
Comment (elpaso) [reply src/core/layertree/qgslayertreemodellegendnode.h]: done with https://github.com/qgis/QGIS/pull/58790/commits/1f86ad11b7aba9d8e3e48b0c5021e1d75afb1cfc

Comment (troopa81) [reply src/core/layertree/qgslayertreemodellegendnode.h]: Yes, it's better this way

**Review by troopa81 — APPROVED** [review]
