### PR TITLE
Sync nodata raster transparency widget

### LINKED ISSUE #45132: "Display nodata as" color widget is not automatically updated in layer styling panel
### What is the bug or the crash?

Setting a color for nodata in the layer properties does not update the widget in the layer styling panel if the transparency tab is already opened

### Steps to reproduce the issue

See above

### Versions

3.21

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #45132

### CODE REVIEW

File: src/gui/raster/qgsrasterlayerproperties.cpp [hunk 1]
```diff
@@ -732,58 +732,11 @@ void QgsRasterLayerProperties::sync()
     mInvertColorsCheck->setChecked( hueSaturationFilter->invertColors() );
   }
 
-  /*
```
Comment (nyalldawson) [inline src/gui/raster/qgsrasterlayerproperties.cpp:735]: Why is all this code redundant? I can't see where the replacement is? (unless it's coming from QgsRasterLayerProperties::setRendererWidget)

Comment (elpaso) [reply src/gui/raster/qgsrasterlayerproperties.cpp:735]: QgsRasterTransparencyWidget::syncToLayer() is called from QgsRasterTransparencyWidget ctor which is called from QgsRasterLayerProperties::QgsRasterLayerProperties.

I think that the code was redundant because the old implementation was not using the widget itself, this PR is a followup of https://github.com/qgis/QGIS/pull/45063

**Review by nyalldawson — APPROVED** [review]
