### PR TITLE
[ui] Improve visibility of the output layer attribute in the DXF export dialog

### LINKED ISSUE #45441: DXF export GUI
### What is the bug or the crash?

DXF export, Output Layer Attribute is not easily visible, see screencast

https://user-images.githubusercontent.com/7631137/136272406-77e1425f-d3fb-4fb0-893f-5fb2dcef309e.mp4

### Steps to reproduce the issue

1. load a vector layer;
2. From the Project menu, select Import / Export | Export Project to DXF ...
image

### Versions

```
QGIS version 3.21.0-Master
QGIS code revision a703d5d787
Qt version 5.15.2
Python version 3.9.5
GDAL/OGR version 3.3.1
PROJ version 8.1.1
EPSG Registry database version v10.028 (2021-07-07)
GEOS version 3.9.1-CAPI-1.14.2
SQLite version 3.35.2
PDAL version 2.3.0
PostgreSQL client version 13.0
SpatiaLite version 5.0.1
QWT version 6.1.3
QScintilla2 version 2.11.5
OS version Windows 10 Version 2009

This copy of QGIS writes debugging output.

Active Python plugins db_manager 0.1.20
grassprovider 2.12.99
MetaSearch 0.3.5
processing 2.12.99
sagaprovider 2.12.99
```

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This fixes a UI/UX issue with the DXF export dialog whereas its layer tree widget does a really good job at hiding the 'Output Layer Attribute' column by resizing individual columns to match the width of the widget itself.

With the PR, both columns are visible, making it clear to the user that this option is here, and much easier to navigate:
image

Fixes #45441

### CODE REVIEW

**Comment by DelazJ** [comment]
@nirvn Thanks. Fixes #45441

File: src/app/qgsdxfexportdialog.cpp [hunk 1]
```diff
@@ -431,10 +431,26 @@ void QgsVectorLayerAndAttributeModel::deSelectAll()
...
+QgsDxfExportLayerTreeView::QgsDxfExportLayerTreeView( QWidget *parent )
+  : QgsLayerTreeView( parent )
+{
+}
+
+void QgsDxfExportLayerTreeView::resizeEvent( QResizeEvent *event )
+{
+  header()->setMinimumSectionSize( viewport()->width() / 2 );
+  header()->setMaximumSectionSize( viewport()->width() / 2 );
+  QTreeView::resizeEvent( event );
```
Comment (nirvn) [inline src/app/qgsdxfexportdialog.cpp:443]:
```suggestion
  QTreeView::resizeEvent( event ); // NOLINT(bugprone-parent-virtual-call)
```

**Review by alexbruy — APPROVED** [review]
