### PR TITLE
Fix duplicate menu entry "Move to another schema..."

### LINKED ISSUE #62263: Duplicate of "Move to Another Schema" right-click option on PostgreSQL table in Browser
### What is the bug or the crash?

When right clicking on a table in a PostgreSQL connection, there are 2 options to "Move to Another Schema". One of these should be removed.

Image

Similar to https://github.com/qgis/qgis/issues/62183

### Steps to reproduce the issue

1. Connect to a PostgreSQL database
2. Right-click on a table

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.43.0-Master</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/cd2944e57f9">cd2944e57f9</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.13</td></tr><tr><td>Python version</td><td>3.12.10</td></tr><tr><td>GDAL version</td><td>3.12.0dev-1acfddd843 (Compiled)<br/>3.12.0dev-876504da2b (Running)</td></tr><tr><td>PROJ version</td><td>9.6.0</td></tr><tr><td>EPSG Registry database version</td><td>v12.004 (2025-03-02)</td></tr><tr><td>GEOS version</td><td>3.13.1-CAPI-1.19.2</td></tr><tr><td>SQLite version</td><td>3.46.1</td></tr><tr><td>PDAL version</td><td>2.8.3</td></tr><tr><td>PostgreSQL client version</td><td>17.3</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.3.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Windows 11 Version 2009</td></tr><tr><td colspan="2"><i>This copy of QGIS writes debugging output.</i></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JanCaha**
## Description

Fixes issue with duplicated menu entry "Move to Another Schema...".

Fixes #62263 and #62183

### CODE REVIEW

**Comment by JanCaha** [comment]
The failed test is unrelated to this.

**Review by nyalldawson — APPROVED** [review]

File: src/app/browser/qgsinbuiltdataitemproviders.cpp [hunk 1]
```diff
@@ -1863,7 +1863,6 @@ void QgsDatabaseItemGuiProvider::populateContextMenu( QgsDataItem *item, QMenu *
     if ( conn && conn->capabilities().testFlag( QgsAbstractDatabaseProviderConnection::Capability::MoveTableToSchema ) )
```
Comment (uclaros) [inline src/app/browser/qgsinbuiltdataitemproviders.cpp]: This is not enough to fix #62183
We also need to skip showing the `moveToSchemaAction` when the context menu was spawned on a connection or schema:

```suggestion
    // Move to schema should not be available for connections and schemata
    const bool isTable = qobject_cast<QgsLayerItem *>( item );
    if ( isTable && conn && conn->capabilities().testFlag( QgsAbstractDatabaseProviderConnection::Capability::MoveTableToSchema ) )
```

**Review by uclaros — CHANGES_REQUESTED** [review]

**Review by uclaros — APPROVED** [review]
