### PR TITLE
[map layer] When saving/loading 'Rendering' category to/from QML, including auto refresh details

### LINKED ISSUE #58656: "Refresh layer at interval" settings are not saved to QML
### What is the bug or the crash?

If you have something configured in layer properties -> Rendering -> "Refresh layer at interval", those settings are not saved to a QML file if you export the symbology.

### Steps to reproduce the issue

1. Have a layer, e.g. `world`
2. Save its style as QML, including Symbology and Rendering
3. Go to layer properties -> Rendering -> "Refresh layer at interval" and set a reload data interval
4. Save its style as QML, including Symbology and Rendering, again

The two files are identical.

If you start from scratch with the same layer and load the style, the layer is not reloading at interval.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.38.1-Grenoble | QGIS code branch | Release 3.38
-- | -- | -- | --
Qt version | 5.15.14
Compiled against Python | 3.12.4 | Running against Python | 3.12.5
GDAL/OGR version | 3.9.1
PROJ version | 9.4.1
EPSG Registry database version | v11.006 (2024-03-13)
GEOS version | 3.12.2-CAPI-1.18.2
Compiled against SQLite | 3.46.0 | Running against SQLite | 3.46.1
PDAL version | 2.7.2
PostgreSQL client version | 16.3
SpatiaLite version | 5.1.0
QWT version | 6.3.0
QScintilla2 version | 2.14.1
OS version | Manjaro Linux
  |   |   |  
Active Python plugins
MetaSearch | 0.3.6
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

This is my export of the `world` easter egg layer styling, including Symbology and Rendering, in QML:

```
<!DOCTYPE qgis PUBLIC 'http://mrcc.com/qgis.dtd' 'SYSTEM'>
<qgis version="3.38.1-Grenoble" simplifyDrawingTol="1" simplifyLocal="1" maxScale="0" hasScaleBasedVisibilityFlag="0" simplifyMaxScale="1" minScale="0" symbologyReferenceScale="-1" styleCategories="Symbology|Rendering" simplifyDrawingHints="1" simplifyAlgorithm="0">
  <renderer-v2 referencescale="-1" forceraster="0" enableorderby="0" symbollevels="0" type="singleSymbol">
    <symbols>
      <symbol force_rhr="0" name="0" is_animated="0" clip_to_extent="1" alpha="1" frame_rate="10" type="fill">
        <data_defined_properties>
          <Option type="Map">
            <Option value="" name="name" type="QString"/>
            <Option name="properties"/>
            <Option value="collection" name="type" type="QString"/>
          </Option>
        </data_defined_properties>
        <layer enabled="1" pass="0" locked="0" id="{a5ce0d67-5f7f-4764-85f5-f361fc9ac018}" class="SimpleFill">
          <Option type="Map">
            <Option value="3x:0,0,0,0,0,0" name="border_width_map_unit_scale" type="QString"/>
            <Option value="224,220,202,154,rgb:0.8784313725490196,0.86274509803921573,0.792156862745098,0.60392156862745094" name="color" type="QString"/>
            <Option value="bevel" name="joinstyle" type="QString"/>
            <Option value="0,0" name="offset" type="QString"/>
            <Option value="3x:0,0,0,0,0,0" name="offset_map_unit_scale" type="QString"/>
            <Option value="MM" name="offset_unit" type="QString"/>
            <Option value="119,116,104,154,rgb:0.46666666666666667,0.45490196078431372,0.40784313725490196,0.60392156862745094" name="outline_color" type="QString"/>
            <Option value="solid" name="outline_style" type="QString"/>
            <Option value="0.26" name="outline_width" type="QString"/>
            <Option value="MM" name="outline_width_unit" type="QString"/>
            <Option value="solid" name="style" type="QString"/>
          </Option>
          <data_defined_properties>
            <Option type="Map">
              <Option value="" name="name" type="QString"/>
              <Option name="properties"/>
              <Option value="collection" name="type" type="QString"/>
            </Option>
          </data_defined_properties>
        </layer>
      </symbol>
    </symbols>
    <rotation/>
    <sizescale/>
    <data-defined-properties>
      <Option type="Map">
        <Option value="" name="name" type="QString"/>
        <Option name="properties"/>
        <Option value="collection" name="type" type="QString"/>
      </Option>
    </data-defined-properties>
  </renderer-v2>
  <selection mode="Default">
    <selectionColor invalid="1"/>
    <selectionSymbol>
      <symbol force_rhr="0" name="" is_animated="0" clip_to_extent="1" alpha="1" frame_rate="10" type="fill">
        <data_defined_properties>
          <Option type="Map">
            <Option value="" name="name" type="QString"/>
            <Option name="properties"/>
            <Option value="collection" name="type" type="QString"/>
          </Option>
        </data_defined_properties>
        <layer enabled="1" pass="0" locked="0" id="{d17b079a-e60e-4894-914a-f497c099dbc1}" class="SimpleFill">
          <Option type="Map">
            <Option value="3x:0,0,0,0,0,0" name="border_width_map_unit_scale" type="QString"/>
            <Option value="0,0,255,255,rgb:0,0,1,1" name="color" type="QString"/>
            <Option value="bevel" name="joinstyle" type="QString"/>
            <Option value="0,0" name="offset" type="QString"/>
            <Option value="3x:0,0,0,0,0,0" name="offset_map_unit_scale" type="QString"/>
            <Option value="MM" name="offset_unit" type="QString"/>
            <Option value="35,35,35,255,rgb:0.13725490196078433,0.13725490196078433,0.13725490196078433,1" name="outline_color" type="QString"/>
            <Option value="solid" name="outline_style" type="QString"/>
            <Option value="0.26" name="outline_width" type="QString"/>
            <Option value="MM" name="outline_width_unit" type="QString"/>
            <Option value="solid" name="style" type="QString"/>
          </Option>
          <data_defined_properties>
            <Option type="Map">
              <Option value="" name="name" type="QString"/>
              <Option name="properties"/>
              <Option value="collection" name="type" type="QString"/>
            </Option>
          </data_defined_properties>
        </layer>
      </symbol>
    </selectionSymbol>
  </selection>
  <blendMode>0</blendMode>
  <featureBlendMode>0</featureBlendMode>
  <layerOpacity>1</layerOpacity>
  <layerGeometryType>2</layerGeometryType>
</qgis>
```

### PR DESCRIPTION
**Pull request by nirvn**
## Description

Fixes https://github.com/qgis/QGIS/issues/58656 .

### CODE REVIEW

**Review by signedav — APPROVED** [review]

File: src/core/qgsmaplayer.cpp [hunk 1]
```diff
@@ -920,6 +920,8 @@ void QgsMapLayer::writeCommonStyle( QDomElement &layerElement, QDomDocument &doc
     layerElement.setAttribute( QStringLiteral( "hasScaleBasedVisibilityFlag" ), hasScaleBasedVisibility() ? 1 : 0 );
     layerElement.setAttribute( QStringLiteral( "maxScale" ), QString::number( maximumScale() ) );
     layerElement.setAttribute( QStringLiteral( "minScale" ), QString::number( minimumScale() ) );
+    layerElement.setAttribute( QStringLiteral( "autoRefreshMode" ), qgsEnumValueToKey( mAutoRefreshMode ) );
+    layerElement.setAttribute( QStringLiteral( "autoRefreshInterval" ), QString::number( autoRefreshInterval() ) );
```
Comment (nyalldawson) [inline src/core/qgsmaplayer.cpp:924]: @nirvn since this change we're now writing BOTH "autoRefreshInterval" and "autoRefreshTime" to the maplayer element, even though both values are the same. Shouldn't we be reusing the existing autoRefreshTime attribute here instead?
