### PR TITLE
mActionZoomToLayers does something using selected or active layer

### LINKED ISSUE #41288: Zoom to Layer(s) action does nothing when no layer is selected in layer panel
A layer absolutely needs to be selected in the layer panel for the Zoom to Layer(s) action to do something. 

Steps to reproduce:

1. Select a spatial layer in the layer panel
2. Deselect it with ctrl+left click on the layer
3. With the layer being deselected but still the "active layer", click on Zoom to Layer(s) (View menu or Map Navigation toolbar)
4. The action should do nothing

Peek 2021-01-31 21-07

### PR DESCRIPTION
**Pull request by TurboGraphxBeige**
mActionZoomToLayers now does something using the current layer's extent if no layer is selected in the layer panel.

Peek 2021-01-31 21-30

Fixes #41288

### CODE REVIEW

File: src/gui/layertree/qgslayertreeviewdefaultactions.cpp [hunk 1]
```diff
@@ -304,8 +304,8 @@ void QgsLayerTreeViewDefaultActions::zoomToLayer( QgsMapCanvas *canvas )
 void QgsLayerTreeViewDefaultActions::zoomToLayers( QgsMapCanvas *canvas )
 {
   const QList<QgsMapLayer *> layers = mView->selectedLayers();
-  if ( layers.isEmpty() )
-    return;
+//  if ( layers.isEmpty() )
+//    return;
```
Comment (nyalldawson) [inline src/gui/layertree/qgslayertreeviewdefaultactions.cpp:308]:
```suggestion
```

File: src/gui/layertree/qgslayertreeviewdefaultactions.cpp [hunk 2]
```diff
@@ -375,30 +375,41 @@ void QgsLayerTreeViewDefaultActions::zoomToLayers( QgsMapCanvas *canvas, const Q
   QgsRectangle extent;
   extent.setMinimal();
 
-  for ( int i = 0; i < layers.size(); ++i )
+  if ( layers.size() >= 1 )
```
Comment (nyalldawson) [inline src/gui/layertree/qgslayertreeviewdefaultactions.cpp:378]:
```suggestion
  if ( !layers.empty() )
```

File: src/gui/layertree/qgslayertreeviewdefaultactions.cpp [hunk 3]
```diff
@@ -375,30 +375,41 @@ void QgsLayerTreeViewDefaultActions::zoomToLayers( QgsMapCanvas *canvas, const Q
...
-    layerExtent = canvas->mapSettings().layerExtentToOutputExtent( layer, layerExtent );
+      //transform extent
+      layerExtent = canvas->mapSettings().layerExtentToOutputExtent( layer, layerExtent );
 
+      extent.combineExtentWith( layerExtent );
+    }
+  }
+
+  // If no layer is selected, use current layer
+  else
```
Comment (nyalldawson) [inline src/gui/layertree/qgslayertreeviewdefaultactions.cpp:409]:
```suggestion
  else if ( mView->currentLayer() )
```

**Comment by nyalldawson** [comment]
Unrelated test failure
