### PR TITLE
[layout] fix mouse grab on locked items

### LINKED ISSUE #57331: Unable to edit elements in the print layout after locking an element
### What is the bug or the crash?

When you group elements and locking them, and then press on the locked group afterwards you are unable to edit any other elements. It's as if all other elements gets locked as well.

### Steps to reproduce the issue

1. Open print layout
2. Add a few elements forexample labels
3. Create a group and lock it
4. Press the locked group
5. Press other elements

qgis-ltr-bin_ztz6BurYmO

### Versions

QGIS-version
3.34.4-Prizren
QGIS-koderevision
decd43dc
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL klient version
16.1
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Fix #57331

See  details at: https://github.com/qgis/QGIS/issues/57331#issuecomment-2126886098

### CODE REVIEW

File: src/gui/layout/qgslayoutviewtoolselect.cpp [hunk 1]
```diff
@@ -130,6 +130,12 @@ void QgsLayoutViewToolSelect::layoutPressEvent( QgsLayoutViewMouseEvent *event )
     return;
   }
 
+  if ( selectedItem->isLocked() )
```
Comment (nyalldawson) [inline src/gui/layout/qgslayoutviewtoolselect.cpp:133]: I think this logic actually belongs in QgsLayout::layoutItemAt, when ignoreLocked is true we should be ignoring items which are part of a locked group and instead returning the NEXT item below at the specified position.

Right now this just aborts the selection, which isn't correct -- it should transparently select the next item below.

Comment (elpaso) [reply src/gui/layout/qgslayoutviewtoolselect.cpp]: Thanks for the suggestion. I applied it and it works as expected even with stacked locked group over an unlocked item.

**Review by nyalldawson — APPROVED** [review]
Looks good! Can you add a test too?
