### PR TITLE
[mesh] Fixes time reference for mesh layer #32186 #33399 #31933

### LINKED ISSUE #32186: use default reference time from MDAL_G_referenceTime
in MDAL 0.4.x there is new function https://github.com/lutraconsulting/MDAL/issues/152 `MDAL_G_referenceTime`. The output of this function should be used as default value for absolute time 

related to #31933 and #31934

### PR DESCRIPTION
**Pull request by vcloarec**
fixes #32186 #33399 #31933
since 6e2ef1544f14c7a5f700447825780f5d93c3c927, MDAL provide time reference for dataset.
This PR allows QGis to read this time reference for mesh layer
If there is a valid time reference provided with dataset groups, this time reference is used to displaying time (using absolute time).
If there is no reference time provided, the time is displayed using relative time, and a time reference can be set by the user to display absolute time.
When no time reference is provided, default one is current date + time set with 00:00:00.
A push button is added to reload the reference time provided with dataset groups, if needed.

Also adds a new feature to let the user set the time unit of the provider with a combo box if thise time unit is different than hours.

image

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `Fixes #11111` at the bottom of the commit message
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit
- [x] I have evaluated whether it is appropriate for this PR to be backported, backport requests are left as label or comment

### CODE REVIEW

File: src/app/mesh/qgsmeshtimeformatdialog.cpp [hunk 1]
```diff
@@ -54,7 +58,11 @@ void QgsMeshTimeFormatDialog::loadSettings()
     mUseTimeComboBox->setCurrentIndex( 1 );
   }
 
-  mReferenceDateTimeEdit->setDateTime( settings.absoluteTimeReferenceTime() );
+  if ( settings.absoluteTimeReferenceTime().isValid() ) //set the reference time, if not valid, set the current date + time 00:00:00
```
Comment (PeterPetrik) [inline src/app/mesh/qgsmeshtimeformatdialog.cpp]: if you can move comment to separate line (line too wide), add 3rd person ("sets") and whitespace after //

File: src/app/mesh/qgsmeshtimeformatdialog.cpp [hunk 2]
```diff
@@ -96,4 +104,22 @@ void QgsMeshTimeFormatDialog::enableGroups( bool useAbsoluteTime )
   mRelativeTimeGroupBox->setEnabled( ! useAbsoluteTime );
 }
 
+bool QgsMeshTimeFormatDialog::layerHasReferenceTime() const
+{
+  if ( !mLayer )
+    return false;
+  int groupCount = mLayer->dataProvider()->datasetGroupCount();
+  bool found = false;
```
Comment (PeterPetrik) [inline src/app/mesh/qgsmeshtimeformatdialog.cpp]: you can remove this variable and simplify this to 

``` 
for ( int i=0; i< mLayer->dataProvider()->datasetGroupCount(); ++i)
  if (mLayer->dataProvider()->datasetGroupMetadata( i ).referenceTime().isValid())
    return true;

return false;
```

Comment (PeterPetrik) [reply src/app/mesh/qgsmeshtimeformatdialog.cpp]: thinking about it, maybe you can return here the index of dataset group that HAS the reference time, and -1 if not found. that way you do not need to search second time for this group

File: src/app/mesh/qgsmeshtimeformatdialog.h [hunk 3]
```diff
@@ -39,12 +39,18 @@ class APP_EXPORT QgsMeshTimeFormatDialog: public QDialog, private Ui::QgsMeshTim
     ~QgsMeshTimeFormatDialog();
 
   private slots:
-
+    void reloadLayerReferenceTime()
```
Comment (PeterPetrik) [inline src/app/mesh/qgsmeshtimeformatdialog.h]: move to cpp

File: src/core/mesh/qgsmeshlayer.cpp [hunk 4]
```diff
@@ -165,6 +165,33 @@ void QgsMeshLayer::setTimeSettings( const QgsMeshTimeSettings &settings )
   emit timeSettingsChanged();
 }
 
+void QgsMeshLayer::setDefaultTimeSettings()
+{
+  mTimeSettings.setRelativeTimeOffsetHours( 0 );
+
+  //search for the first valid reference time in the dataset groups
```
Comment (PeterPetrik) [inline src/core/mesh/qgsmeshlayer.cpp]: add whitespace after //

File: src/core/mesh/qgsmeshlayer.h [hunk 5]
```diff
@@ -221,6 +221,20 @@ class CORE_EXPORT QgsMeshLayer : public QgsMapLayer
      */
     void setTimeSettings( const QgsMeshTimeSettings &settings );
 
+    /**
+     * Sets time default format settings
+     *
+     * \since QGIS 3.12
+     */
+    void setDefaultTimeSettings();
```
Comment (PeterPetrik) [inline src/core/mesh/qgsmeshlayer.h]: this function probably does not fir into qgsmeshlayer class. I would create some helper (ideally not exported out of CORE) function somewhere in mesh layer utils or the class that calls setTimeSettings. so the flow would be

1) resolve refence time
2) assign to QgsMeshTimeSettings
3) call meshlayer->setTimeSettings

File: src/core/mesh/qgsmeshlayer.h [hunk 6]
```diff
@@ -221,6 +221,20 @@ class CORE_EXPORT QgsMeshLayer : public QgsMapLayer
...
+
+    /**
+     * Loads the first valid reference time of the dataset groups.
+     *
+     * \since QGIS 3.12
+     */
+    void loadReferenceTime();
```
Comment (PeterPetrik) [inline src/core/mesh/qgsmeshlayer.h]: this function probably does not fir into qgsmeshlayer class

File: src/providers/mdal/qgsmdalprovider.cpp [hunk 7]
```diff
@@ -493,13 +493,17 @@ QgsMeshDatasetGroupMetadata QgsMdalProvider::datasetGroupMetadata( int groupInde
     metadata[key] = value;
   }
 
+  QString referenceTimeString( MDAL_G_referenceTime( group ) );
+  QDateTime referenceTime = QDateTime::fromString( referenceTimeString, Qt::ISODate );
```
Comment (PeterPetrik) [inline src/providers/mdal/qgsmdalprovider.cpp]: what if referenceTimeString is empty string?

**Review by PeterPetrik — CHANGES_REQUESTED** [review]

**Comment by PeterPetrik** [comment]
very good work, just some small changes requested

File: src/providers/mdal/qgsmdalprovider.cpp (hunk 7 above)
Comment (vcloarec) [reply src/providers/mdal/qgsmdalprovider.cpp]: If the static method of QDateTime fails to parse the string, it returns invalid QDateTime and we considers that the dataset group don't have valid reference time.

File: src/core/mesh/qgsmeshlayer.h (hunk 5 above)
Comment (vcloarec) [reply src/core/mesh/qgsmeshlayer.h]: ok, I simplified that with only a new method in qgsmeshutils. This method return the first valid reference time of the dataset goups.
This function is called from the QgsMeshTimeFormatDialog (only when needed)  but also from the QgsMeshLayer class just after the provider is set. I think this last call is the best place to set the default reference time for those reasons :
- default reference time is defined when the mesh layer is created. Whatever needs the reference time (time widget, active renderer widget, other future stuff), the default reference time is defined from the layer's data.
- When the mesh layer is created when opening project, the read xml method can replace the default time reference with the one saved

File: src/core/mesh/qgsmeshlayerutils.h [hunk 8]
```diff
@@ -178,6 +178,15 @@ class CORE_EXPORT QgsMeshLayerUtils
      * Formats hours in human readable string based on settings
      */
     static QString formatTime( double hours, const QgsMeshTimeSettings &settings );
+
+    /**
+      * Searches and returns the first valid reference time in layer's dataset group
+      * \param meshLayer mesh layer to parse
+      *
+      * * \since QGIS 3.12
```
Comment (PeterPetrik) [inline src/core/mesh/qgsmeshlayerutils.h]: extra *

File: src/core/mesh/qgsmeshtimesettings.h [hunk 9]
```diff
@@ -35,7 +35,19 @@
 class CORE_EXPORT QgsMeshTimeSettings
 {
   public:
-    //! Default constructor for relative time format and 0 offset
+    //! Time units used to display time
```
Comment (PeterPetrik) [inline src/core/mesh/qgsmeshtimesettings.h]: add `\since QGIS 3.12`

File: src/core/mesh/qgsmeshtimesettings.h [hunk 10]
```diff
@@ -84,6 +96,11 @@ class CORE_EXPORT QgsMeshTimeSettings
     //! Sets format used for absolute time
     void setAbsoluteTimeFormat( const QString &absoluteTimeFormat );
 
+    //! Returns the provider time unit
```
Comment (PeterPetrik) [inline src/core/mesh/qgsmeshtimesettings.h]: \since QGIS 3.12

File: src/core/mesh/qgsmeshtimesettings.h [hunk 11]
```diff
@@ -84,6 +96,11 @@ class CORE_EXPORT QgsMeshTimeSettings
...
+    TimeUnit providerTimeUnit() const;
+    //! Sets the provider time unit
```
Comment (PeterPetrik) [inline src/core/mesh/qgsmeshtimesettings.h]: \since QGIS 3.12

**Review by PeterPetrik — CHANGES_REQUESTED** [review]
final doc changes needed...

**Review by PeterPetrik — APPROVED** [review]
