### PR TITLE
[fix] Make sure diagram data defined properties are preserved when reopening diagram properties

### LINKED ISSUE #62936: Diagram properties related to variables and expressions are not saved
### What is the bug or the crash?

Any configured diagram property is reset after clicking OK or saving the style in QML

### Steps to reproduce the issue

1. Create a vector layer with a boolean field
2. Open the layer properties on the Diagrams tab
3. Select a diagram type
4. Go to the Rendering tab
5. Bind the “Show diagram” property to the layer’s field
6. Click OK
7. Reopen the layer properties on the same tab
8. The setting will be reset

https://github.com/user-attachments/assets/3cc68537-3f3d-47b8-9c6a-e45efa017078

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.44.1-Solothurn</td></tr><tr><td>QGIS code branch</td><td><a href="https://github.com/qgis/QGIS/tree/release-3_44">Release 3.44</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.17</td></tr><tr><td>Python version</td><td>3.13.5</td></tr><tr><td>GDAL version</td><td>3.11.3 — <i>Eganville</i></td></tr><tr><td>PROJ version</td><td>9.6.0</td></tr><tr><td>EPSG Registry database version</td><td>v12.004 (2025-03-02)</td></tr><tr><td>GEOS version</td><td>3.13.1-CAPI-1.19.2</td></tr><tr><td>SQLite version</td><td>3.50.3</td></tr><tr><td>PDAL version</td><td>2.9.0</td></tr><tr><td>PostgreSQL client version</td><td>17.5</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.3.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Arch Linux</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>digitizr</td><td>1.2.0</td></tr><tr><td>molusce</td><td>5.0.0</td></tr><tr><td>nextgis_toolbox</td><td>1.0.2</td></tr><tr><td>wurman_dots</td><td>2.0.0</td></tr><tr><td>geometry_paster</td><td>1.2.0</td></tr><tr><td>clickfu</td><td>0.8.0</td></tr><tr><td>firstaid</td><td>3.2.1</td></tr><tr><td>plugin_reloader</td><td>0.18</td></tr><tr><td>qgis_layers_data_update</td><td>0.3.0</td></tr><tr><td>qgis_points2one</td><td>0.4.0</td></tr><tr><td>map_tile_loader</td><td>0.2.0</td></tr><tr><td>reconstruct_line</td><td>0.8.0</td></tr><tr><td>HCMGIS</td><td>25.1.9</td></tr><tr><td>zoom_level</td><td>0.3.3</td></tr><tr><td>devtools</td><td>1.2.0</td></tr><tr><td>identifyplus</td><td>4.2.0</td></tr><tr><td>OpenTopography-DEM-Downloader</td><td>3.0</td></tr><tr><td>shortcut_manager</td><td>1.2.0</td></tr><tr><td>copy_coords</td><td>0.4.0</td></tr><tr><td>pluginbuilder3</td><td>3.2.1</td></tr><tr><td>connect_points</td><td>0.5.0</td></tr><tr><td>qgis_versioning</td><td>1.0</td></tr><tr><td>osmpoly_export</td><td>0.7.0</td></tr><tr><td>quicksaveqml</td><td>0.2.0</td></tr><tr><td>multiqml</td><td>0.7.0</td></tr><tr><td>osminfo</td><td>1.2.0</td></tr><tr><td>simplereports</td><td>0.4.0</td></tr><tr><td>processing_saga_nextgen</td><td>1.1.0</td></tr><tr><td>ngq_rosreestr_tools</td><td>3.0.1</td></tr><tr><td>qgis_easy_query</td><td>1.1.0</td></tr><tr><td>qgis_ogrstyle</td><td>0.3.0</td></tr><tr><td>quick_map_services</td><td>0.21.2</td></tr><tr><td>qtiles</td><td>1.8.0</td></tr><tr><td>joinlines</td><td>0.6.0</td></tr><tr><td>AppendFeaturesToLayer</td><td>2.1.0</td></tr><tr><td>dumploadfield</td><td>0.4.0</td></tr><tr><td>nextgis_connect</td><td>3.4.0</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gacarrillor**
Fix #62936 

Note: Changes to tests/testdata/stacked_diagrams.gpkg are intentional (added boolean field).

----

Includes unit tests.

### CODE REVIEW

File: src/gui/vector/qgsdiagramproperties.cpp [hunk 1]
```diff
@@ -406,6 +406,27 @@ void QgsDiagramProperties::insertDefaults()
   mDiagramTypeComboBox_currentIndexChanged( mDiagramTypeComboBox->currentIndex() );
 }
 
+void QgsDiagramProperties::updateDataDefinedButtons()
+{
+  const auto propertyOverrideButtons { findChildren<QgsPropertyOverrideButton *>() };
```
Comment (nyalldawson) [inline src/gui/vector/qgsdiagramproperties.cpp]: no auto here

**Review by nirvn — APPROVED** [review]
Thanks for the additional test coverage.

**Comment by nirvn** [comment]
@gacarrillor , can we backport to 3.44?

**Comment by gacarrillor** [comment]
> @gacarrillor , can we backport to 3.44?

Yeah, I forgot the label, thanks!

**Review by nyalldawson — APPROVED** [review]
