### PR TITLE
Fix merge features with hidden fields

### LINKED ISSUE #28253: "Merge Selected Feature" do not works correctly with hidden fields
Author Name: **Jan Lippmann** (@j-lippmann)
Original Redmine Issue: [20433](https://issues.qgis.org/issues/20433)
Affected QGIS version: 3.5(master)
Redmine category:digitising

---

"Take Attributes from selected feature" takes not the value from the selected feature.

!feature_merge_hidden_id_2.gif!

---

- [feature_merge_hidden_id_2.gif](https://issues.qgis.org/attachments/download/13723/feature_merge_hidden_id_2.gif) (Jan Lippmann)
- [merge_take_attributes.gif](https://issues.qgis.org/attachments/download/13758/merge_take_attributes.gif) (Jan Lippmann)

### PR DESCRIPTION
**Pull request by vaahtokarkki**
## Description

Merge selected features tool won't merge correctly hidden attribute values. With this PR the tool will use for hidden fields the default value defined for field, or the value from the selected feature, if any is selected. 

Fixes #28253 
Backport needed for 3.34 and 3.36

### CODE REVIEW

File: src/app/qgsmergeattributesdialog.cpp [hunk 1]
```diff
@@ -183,12 +186,17 @@ void QgsMergeAttributesDialog::createTableWidgetContents()
...
     QComboBox *cb = createMergeComboBox( mFields.at( idx ).type(), col );
     if ( ! mVectorLayer->dataProvider()->pkAttributeIndexes().contains( mFields.fieldOriginIndex( idx ) ) &&
-         mFields.at( idx ).constraints().constraints() & QgsFieldConstraints::ConstraintUnique )
+         mFields.at( idx ).constraints().constraints() & QgsFieldConstraints::ConstraintUnique || mHiddenAttributes.contains( idx ) )
     {
       cb->setCurrentIndex( cb->findData( "skip" ) );
     }
     mTableWidget->setCellWidget( 0, col, cb );
 
+    if ( setup.type() == QLatin1String( "Hidden" ) )
```
Comment (Joonalai) [inline src/app/qgsmergeattributesdialog.cpp:195]: Here the same method as in line 189 can be used to detect hidden field:
```suggestion
    if ( mHiddenAttributes.contains( idx ) )
```

File: src/app/qgsmergeattributesdialog.cpp [hunk 2]
```diff
@@ -768,18 +776,11 @@ QgsAttributes QgsMergeAttributesDialog::mergedAttributes() const
...
   {
-    if ( mHiddenAttributes.contains( fieldIdx ) )
-    {
-      //hidden attribute, set to default value
-      results[fieldIdx] = QVariant();
-      continue;
-    }
-
     QComboBox *comboBox = qobject_cast<QComboBox *>( mTableWidget->cellWidget( 0, widgetIndex ) );
+    QVariant value;
```
Comment (Joonalai) [inline src/app/qgsmergeattributesdialog.cpp:780]: This change is not necessary.
```suggestion
```

File: src/app/qgsmergeattributesdialog.cpp [hunk 3]
```diff
@@ -768,18 +776,11 @@ QgsAttributes QgsMergeAttributesDialog::mergedAttributes() const
...
     if ( !comboBox )
       continue;
```
Comment (Joonalai) [inline src/app/qgsmergeattributesdialog.cpp:783]:
```suggestion
    QVariant value;
```

**Review by Joonalai — APPROVED** [review]
Looks good! I just added few minor comments :smile:

File: src/app/qgsmergeattributesdialog.cpp (hunk 1 above)
Comment (vaahtokarkki) [reply src/app/qgsmergeattributesdialog.cpp]: Thanks for the suggestions! Now both of them applied to the commit

**Comment by Joonalai** [comment]
@nyalldawson could you review this as well?

**Comment by Joonalai** [comment]
Not stale, just waiting for review. Could perhaps some of you @nyalldawson, @3nids, @m-kuhn please review this?

File: tests/src/app/testqgsmergeattributesdialog.cpp [hunk 4]
```diff
@@ -150,6 +150,78 @@ class TestQgsMergeattributesDialog : public QgsTest
...
+      // Create test layer
+      QgsVectorFileWriter::SaveVectorOptions options;
+      QgsVectorLayer ml( "LineString", "test", "memory" );
+      QVERIFY( ml.isValid() );
+
+      QgsField notHiddenField( QStringLiteral( "not_hidden" ), QVariant::Int );
+      QgsField hiddenField( QStringLiteral( "hidden" ), QVariant::Int );
+      // hide the field
+      ml.setEditorWidgetSetup( 1, QgsEditorWidgetSetup( QStringLiteral( "Hidden" ), QVariantMap() ) );
+      QVERIFY( ml.dataProvider()->addAttributes(
```
Comment (lnicola) [inline tests/src/app/testqgsmergeattributesdialog.cpp:165]: Nit: this seems pretty unreadable to me, I think it should fit on a single line.

Comment (vaahtokarkki) [reply tests/src/app/testqgsmergeattributesdialog.cpp]: Thanks for pointing out, it is indeed better formatted as single line.

File: tests/src/app/testqgsmergeattributesdialog.cpp [hunk 5]
```diff
@@ -150,6 +150,74 @@ class TestQgsMergeattributesDialog : public QgsTest
...
+      QVERIFY( ml.isValid() );
+
+      QgsField notHiddenField( QStringLiteral( "not_hidden" ), QVariant::Int );
+      QgsField hiddenField( QStringLiteral( "hidden" ), QVariant::Int );
+      // hide the field
+      ml.setEditorWidgetSetup( 1, QgsEditorWidgetSetup( QStringLiteral( "Hidden" ), QVariantMap() ) );
+      QVERIFY( ml.dataProvider()->addAttributes( { notHiddenField, hiddenField } ) );
+      ml.updateFields();
+
+      // Create a features
```
Comment (elpaso) [inline tests/src/app/testqgsmergeattributesdialog.cpp:168]:
```suggestion
      // Create features
```

File: tests/src/app/testqgsmergeattributesdialog.cpp [hunk 6]
```diff
@@ -150,6 +150,74 @@ class TestQgsMergeattributesDialog : public QgsTest
...
+      QgsField notHiddenField( QStringLiteral( "not_hidden" ), QVariant::Int );
+      QgsField hiddenField( QStringLiteral( "hidden" ), QVariant::Int );
+      QVERIFY( ml.dataProvider()->addAttributes( { notHiddenField, hiddenField } ) );
+      ml.updateFields();
+
+      // hide the field
+      ml.setEditorWidgetSetup( 1, QgsEditorWidgetSetup( QStringLiteral( "Hidden" ), QVariantMap() ) );
+
+
+      // Create a features
```
Comment (elpaso) [inline tests/src/app/testqgsmergeattributesdialog.cpp:203]:
```suggestion
      // Create features
```

**Review by elpaso — APPROVED** [review]

**Comment by vaahtokarkki** [comment]
Again not stale and just waiting for the GitHub actions to run. Could you @elpaso allow them to run, thanks again!

**Comment by elpaso** [comment]
> Again not stale and just waiting for the GitHub actions to run. Could you @elpaso allow them to run, thanks again!

Can you try to rebase from current master an force-push?

**Comment by elpaso** [comment]
@vaahtokarkki thank you for you contribution. 
I'm sorry the review process took so long, the automated CI sometimes seems to work against us.

**Comment by Joonalai** [comment]
@elpaso there does not seem to be a backport PR of this fix for release-3_34? Should we make it manually or is "Backport queued_ltr_backports" ending up to some 3.34 release?

**Comment by elpaso** [comment]
> @elpaso there does not seem to be a backport PR of this fix for release-3_34? Should we make it manually or is "Backport queued_ltr_backports" ending up to some 3.34 release?

queued_ltr_backports will be merged in 3.34 but not in the next point release, we skip one point release to give extra time for testing before merging into a LTR.
