### PR TITLE
pass color ramp name to the color ramp transformer to generate correct expression (fix #48889)

### LINKED ISSUE #48889: Using the Assistant for Data Defined Colors incorrectly shows 'custom ramp' instead of the correct colour ramp name
### What is the bug or the crash?

When using the Assistant for some type of data defined color in the Symbology editor, the user can pick a particular color ramp for a field of interest (e.g. 'Reds' or 'Turbo'). While the colors are correctly shown in the vector layer, the expression the Assistant produces is not correct. Instead of showing the name of the color ramp one has picked, it shows the words 'custom ramp'. This is not a big problem, but interferes with the usability of data defined overrides (and a Plugin I am working on).

### Steps to reproduce the issue

1. Open vector layer Properties
2. Go to Symbology
3. Click 'Simple Line' (or equivalent for other type of layer)
4. Click the data defined Assistant for some type of color option
5. Select the inputs and any color ramp, and OK
6. Click Edit on the data defined field, and note that the ramp name is not correct.

### Versions

Tested in 3.20, 3.24.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alexbruy**
## Description

When configuting data-defined color using Assistant dialog/widget generated expression uses "custom ramp" instead of actual color ramp name. This happens because color ramp name is never passed to the `QgsColorRampTransformer` object.

Fixes #48889.

### CODE REVIEW

File: src/core/qgspropertytransformer.h [hunk 1]
```diff
@@ -615,11 +615,13 @@ class CORE_EXPORT QgsColorRampTransformer : public QgsPropertyTransformer
      * \param maxValue maximum expected value
      * \param ramp source color ramp. Ownership is transferred to the transformer.
      * \param nullColor color to return for null values
+     * \param rampName name of the source color ramp
```
Comment (nyalldawson) [inline src/core/qgspropertytransformer.h:618]:
```suggestion
     * \param rampName name of the source color ramp (since QGIS 3.36)
```

**Review by nyalldawson — APPROVED** [review]
