### PR TITLE
Fix elevation profile on virtual point cloud

### LINKED ISSUE #54728: Elevation profile does not recognise VPC as an input layer
### What is the bug or the crash?

The elevation profile tool ignores the Virtual Point Cloud and does not generate a profile from the layer.

### Steps to reproduce the issue

1- Open QGIS
2- Add a VPC layer
3- Create an elevation profile from the layer
4- No data is shown in the elevation profile plot area

### Versions

QGIS maste https://github.com/qgis/QGIS/commit/6b371430693

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dvdkon**
## Description

This PR fixes elevation profile generation on virtual point cloud (VPC) layers by changing `QgsPointCloudLayerProfileGenerator::generateProfile()` to consider sub-indexes.

Will fix #54728

### CODE REVIEW

File: src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp [hunk 1]
```diff
@@ -389,12 +389,22 @@ bool QgsPointCloudLayerProfileGenerator::generateProfile( const QgsProfileGenera
   // this is not AT ALL thread safe, but it's what QgsPointCloudLayerRenderer does !
   // TODO: fix when QgsPointCloudLayerRenderer is made thread safe to use same approach
 
-  QgsPointCloudIndex *pc = mLayer->dataProvider()->index();
-  if ( !pc || !pc->isValid() )
+  QVector<QgsPointCloudIndex *> indexes;
+  QgsPointCloudIndex *mainIndex = mLayer->dataProvider()->index();
+  if ( mainIndex && mainIndex->isValid() ) indexes.append( mainIndex );
```
Comment (nyalldawson) [inline src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp:394]:
```suggestion
  if ( mainIndex && mainIndex->isValid() )
    indexes.append( mainIndex );
```

File: src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp [hunk 2]
```diff
@@ -389,12 +389,22 @@ bool QgsPointCloudLayerProfileGenerator::generateProfile( const QgsProfileGenera
...
+
+  // Gather all relevant sub-indexes
+  auto profileCurveBbox = mProfileCurve->boundingBox();
```
Comment (nyalldawson) [inline src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp:397]:
```suggestion
  const QgsRectangle profileCurveBbox = mProfileCurve->boundingBox();
```

File: src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp [hunk 3]
```diff
@@ -389,12 +389,22 @@ bool QgsPointCloudLayerProfileGenerator::generateProfile( const QgsProfileGenera
...
+  for ( auto &subidx : mLayer->dataProvider()->subIndexes() )
```
Comment (nyalldawson) [inline src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp:398]:
```suggestion
  for ( const QgsPointCloudSubIndex &subidx : mLayer->dataProvider()->subIndexes() )
```

File: src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp [hunk 4]
```diff
@@ -389,12 +389,22 @@ bool QgsPointCloudLayerProfileGenerator::generateProfile( const QgsProfileGenera
...
   {
-    return false;
+    QgsPointCloudIndex *index = subidx.index();
+    if ( index && index->isValid() && subidx.polygonBounds().intersects( profileCurveBbox ) )
+      indexes.append( subidx.index() );
   }
 
+  if ( indexes.size() == 0 )
```
Comment (nyalldawson) [inline src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp:405]:
```suggestion
  if ( indexes.empty() )
```

File: src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp [hunk 5]
```diff
@@ -515,21 +487,64 @@ bool QgsPointCloudLayerProfileGenerator::generateProfile( const QgsProfileGenera
 
   request.setAttributes( attributes );
 
-  switch ( pc->accessType() )
+  mResults = std::make_unique< QgsPointCloudLayerProfileResults >();
+  mResults->copyPropertiesFromGenerator( this );
+  mResults->mMaxErrorInLayerCoordinates = 0;
+
+  for ( auto pc : indexes )
```
Comment (nyalldawson) [inline src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp:494]:
```suggestion
  for ( QgsPointCloudIndex *pc : std::as_const( indexes ) )
```

File: src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp [hunk 6]
```diff
@@ -515,21 +487,64 @@ bool QgsPointCloudLayerProfileGenerator::generateProfile( const QgsProfileGenera
...
-    case QgsPointCloudIndex::AccessType::Local:
+    const IndexedPointCloudNode root = pc->root();
+    const QgsRectangle rootNodeExtentLayerCoords = pc->nodeMapExtent( root );
+    QgsRectangle rootNodeExtentInCurveCrs;
+    try
     {
-      visitNodesSync( nodes, pc, request, context.elevationRange() );
-      break;
+      QgsCoordinateTransform extentTransform = mLayerToTargetTransform;
+      extentTransform.setBallparkTransformsAreAppropriate( true );
```
Comment (nyalldawson) [inline src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp:502]: This could be moved outside the loop

File: src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp [hunk 7]
```diff
@@ -515,21 +487,64 @@ bool QgsPointCloudLayerProfileGenerator::generateProfile( const QgsProfileGenera
...
-      visitNodesAsync( nodes, pc, request, context.elevationRange() );
-      break;
+      QgsDebugError( QStringLiteral( "Could not transform node extent to curve CRS" ) );
+      rootNodeExtentInCurveCrs = rootNodeExtentLayerCoords;
+    }
+
+    const double rootErrorInMapCoordinates = rootNodeExtentInCurveCrs.width() / pc->span(); // in curve coords
+
+    const double mapUnitsPerPixel = context.mapUnitsPerDistancePixel();
+    if ( ( rootErrorInMapCoordinates < 0.0 ) || ( mapUnitsPerPixel < 0.0 ) || ( maximumErrorPixels < 0.0 ) )
```
Comment (nyalldawson) [inline src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp:514]: The mapUnitsPerPixel logic could be moved outside the loop

**Review by nyalldawson — COMMENTED** [review]
Looking good! Just some minor code consistency comments to bring it inline with conventions used across the QGIS codebase

**Comment by dvdkon** [comment]
> Looking good! Just some minor code consistency comments to bring it inline with conventions used across the QGIS codebase

Thanks! I've pushed a revised commit.

File: src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp (hunk 5 above)
Comment (dvdkon) [reply src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp]: What does the `std::as_const()` add here? I'm not accessing the raw iterator and I'm getting out copies of (non-const) pointers, so it shouldn't matter, no?

Comment (nyalldawson) [reply src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp]: It's a qt thing, relating to detachment of the implicitly shared Qt container classes. See https://www.kdab.com/blog-qasconst-and-stdas_const/ for more details.

File: src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp [hunk 8]
```diff
@@ -515,22 +494,75 @@ bool QgsPointCloudLayerProfileGenerator::generateProfile( const QgsProfileGenera
...
+  extentTransform.setBallparkTransformsAreAppropriate( true );
+
+  const double mapUnitsPerPixel = context.mapUnitsPerDistancePixel();
+  if ( mapUnitsPerPixel < 0.0 )
+  {
+    QgsDebugError( QStringLiteral( "Invalid map units per pixel ratio" ) );
+    return false;
+  }
+
+  for ( QgsPointCloudIndex *pc : indexes )
```
Comment (nyalldawson) [inline src/core/pointcloud/qgspointcloudlayerprofilegenerator.cpp:511]:
```suggestion
  for ( QgsPointCloudIndex *pc : std::as_const( indexes ) )
```

**Review by nyalldawson — APPROVED** [review]

**Comment by nicogodet** [comment]
Hi @dvdkon, I think this PR reintroduced the bug described in https://github.com/qgis/QGIS/issues/54349
In 3.40.7, I have an endless loop if I plot a profile outside the extent of a displayed pointcloud layer. Works fine in 3.34

**Comment by dvdkon** [comment]
> Hi @dvdkon, I think this PR reintroduced the bug described in #54349 In 3.40.7, I have an endless loop if I plot a profile outside the extent of a displayed pointcloud layer. Works fine in 3.34

I'll try to reproduce this and fix it, hopefully it's just a "cosmetic" issue like last time.

**Comment by nicogodet** [comment]
Let me know if you need additional details

**Comment by nicogodet** [comment]
Might be related (or not): https://github.com/qgis/QGIS/issues/62125
