### PR TITLE
Insuring legendLayersAdded is called when adding sorted layers 

### LINKED ISSUE #50718: legendLayersAdded signal not fired anymore in master?
### What is the bug or the crash?

Hi, having a plugin which uses the legendLayersAdded signal:
https://qgis.org/pyqgis/master/core/QgsProject.html?#qgis.core.QgsProject.legendLayersAdded

I found that current master (only) it is not fired anymore (while in 3.28 and older it is)

### Steps to reproduce the issue

- open QGIS
- open Python console
- run following lines of code

```
QgsProject.instance().legendLayersAdded.connect(lambda: print('legendLayersAdded fired'))
QgsProject.instance().layerWasAdded.connect(lambda: print('layerWasAdded fired'))
```

Now drag/drop a shpfile/geojson whatever onto the mapcanvas.

In 3.28 I see:
```
layerWasAdded fired
legendLayersAdded fired
```

but in master only:
```
layerWasAdded fired
```

Anybody can confirm?

### Versions

QGIS version | 3.29.0-Master | QGIS code revision | f2873572fd6
-- | -- | -- | --
Qt version | 5.15.4
Python version | 3.10.7
GDAL/OGR version | 3.5.2
PROJ version | 9.1.0
EPSG Registry database version | v10.074 (2022-08-01)
GEOS version | 3.11.0-CAPI-1.17.0
SQLite version | 3.39.4
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Debian GNU/Linux bookworm/sid
  |   |   |  
This copy of QGIS writes debugging output.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nirvn**
This PR fixes  #50718 by restoring the QgsProject::legendLayersAdded signal when app handles insertion of sorted layers.

@rduivenvoorde , this should fix your issue.

### CODE REVIEW

**Comment by rduivenvoorde** [comment]
@nirvn thanks! I just build your PR, and indeed now I get both signals again.

Are there any tests, to see if important objects like QgsProject is loosing signals?

Thinking about some test in which you register for all signals, and do the things to trigger them, and then check if all are fired?

Looking into that: https://github.com/qgis/QGIS/blob/master/tests/src/core/testqgsproject.cpp#L373
using QSignalSpy to count signals?

File: src/app/layers/qgsapplayerhandling.cpp [hunk 1]
```diff
@@ -175,7 +175,7 @@ void QgsAppLayerHandling::addSortedLayersToLegend( QList<QgsMapLayer *> &layers
     } );
   }
 
-  QgsLayerTreeGroup *parent = nullptr;
+  /*QgsLayerTreeGroup *parent = nullptr;
   QgsLayerTreeNode *currentNode = QgisApp::instance()->layerTreeView()->currentNode();
```
Comment (nyalldawson) [inline src/app/layers/qgsapplayerhandling.cpp:179]: Is this a wip?

Comment (nirvn) [reply src/app/layers/qgsapplayerhandling.cpp:179]: Nope, it's a push that was missing --force and failed without me noticing

Comment (nirvn) [reply src/app/layers/qgsapplayerhandling.cpp]: @nyalldawson , fixed

**Review by nyalldawson — APPROVED** [review]
