### PR TITLE
Do not query geography_columns on postgis < 1.5

### LINKED ISSUE #38580: QGIS Postgres provider does not load any postgres 8.4 postgis 1.4.2 geometry table
I know it's and old version but this is a serious regression.

DB manager loads the tables correctly.

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #38580

### CODE REVIEW

File: src/providers/postgres/qgspostgresconn.cpp [hunk 1]
```diff
@@ -488,7 +488,7 @@ bool QgsPostgresConn::getTableInfo( bool searchGeometryColumnsOnly, bool searchP
       dimName    = QStringLiteral( "l.coord_dimension" );
       gtableName = QStringLiteral( "geometry_columns" );
     }
-    else if ( i == SctGeography )
+    else if ( i == SctGeography && mPostgresqlVersion >= 150000 )
```
Comment (rouault) [inline src/providers/postgres/qgspostgresconn.cpp:491]: testing the postgres version looks wrong to me. Should rather be against mPostgisVersionMajor and mPostgisVersionMinor

Comment (elpaso) [reply src/providers/postgres/qgspostgresconn.cpp:491]: yes, right. Thanks for noticing.
