### PR TITLE
[ui] Insure that all style categories have tooltips

### LINKED ISSUE #56362: Add missing tooltip for "Custom Properties" style category
### What is the bug or the crash?

Please add a tooltip to the style category "Custom Properties" in order to describe affected layer properties (variables, ...)!

This affects the copy/paste style with context menu and also the import/export style dialog.

image

I just tried to copy variables from one layer to another. Eventually, I realized that it is done with copying "Custom Properties". However, I am not sure if other layer properties are included.

### Steps to reproduce the issue

1. Right click vector layer to open context menu
2. Styles
3. Copy style
4. Hover "Custom Properties"
5. See that there is no tooltip

### Versions

QGIS version
3.34.3-Prizren
QGIS code revision
47373234ac
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.3
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This PR fixes #56362 by insuring that all style categories have a tooltip. For more obscure categories such as Custom Properties, the tooltip tries to provide useful hints as to what that is.

For self-explanatory categories such as Labels, adding tooltips is still important as it teaches users to expect tooltips there to begin with (and avoids users wondering why menu item A has a tooltip while B does not).

### CODE REVIEW

File: src/gui/qgsmaplayerstylecategoriesmodel.cpp [hunk 1]
```diff
@@ -230,7 +227,7 @@ QVariant QgsMapLayerStyleCategoriesModel::data( const QModelIndex &index, int ro
         case Qt::DisplayRole:
           return tr( "Custom Properties" );
         case Qt::ToolTipRole:
-          return QVariant();
+          return tr( "Custom properties (often used by plugins and custom python code)" );
```
Comment (agiudiceandrea) [inline src/gui/qgsmaplayerstylecategoriesmodel.cpp:230]: According to the issue report, should't it be mentioned that the variables (and what else? are among the layer's custom properties?

Comment (nirvn) [inline src/gui/qgsmaplayerstylecategoriesmodel.cpp:230]:
```suggestion
          return tr( "Variables, custom properties (often used by plugins and custom python code)" );
```

**Review by nyalldawson — APPROVED** [review]
