### PR TITLE
Message for VPC files that contain files that cannot be properly displayed

### LINKED ISSUE #53765: VPC that references LAS/LAZ files does not get any points shown
### What is the bug or the crash?

Currently in QGIS, virtual point cloud (VPC) files that reference LAS/LAZ files only get their boundaries shown, but not the actual points. The point only show when the VPC file references COPC files or EPT (i.e. format that is indexed).

It would be better to at least show a warning that the files need to be converted to allow visualization - or to do the conversion automatically (like we do when a single LAS/LAZ file is loaded in QGIS).

### Steps to reproduce the issue

1. build a VPC using LAS/LAZ files
2. load it in QGIS
3. zoom in map canvas (2d or 3d) - no points will appear (only boundaries are shown)

### Versions

QGIS 3.32

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JanCaha**
## Description

Provides warning message when VPC file is loaded that contains files that cannot be properly rendered in QGIS.

Fix #53765

### CODE REVIEW

File: src/app/layers/qgsapplayerhandling.cpp [hunk 1]
```diff
@@ -208,6 +208,15 @@ void QgsAppLayerHandling::postProcessAddedLayer( QgsMapLayer *layer )
         }
       }
 #endif
+
+      if ( const QgsVirtualPointCloudProvider *vpcProvider = dynamic_cast<QgsVirtualPointCloudProvider *>( layer->dataProvider() ) )
+      {
+        if ( vpcProvider->containsUnsupportedFiles() )
+        {
+          QgisApp::instance()->visibleMessageBar()->pushWarning( QObject::tr( "Unsupported files in VPC" ), QObject::tr( "Some files (i.e. LAZ or LAS files) referenced by the virtual point cloud are unsupported and cannot be displayed." ) );
```
Comment (uclaros) [inline src/app/layers/qgsapplayerhandling.cpp]: I'd suggest:
title: Unsupported files in VPC layer
body: Layer %1 references point cloud files that can only be displayed by their extents.
pushbutton: More Info
info dialog body: QGIS can display the actual points of a virtual point cloud only if the referenced point cloud files are in COPC or EPT format. You can convert the files to COPC format by running the Build virtual point cloud (VPC) algorithm and enabling the Convert individual files to COPC format checkbox.

**Review by uclaros — APPROVED** [review]
