### PR TITLE
Don't segmentize digitized feature if the layer supports curves

### LINKED ISSUE #53818: Shift+O does not always turn segments into real curved line
### What is the bug or the crash?

Pressing `Shift+O` (the letter not zero) with vertex tool while a vertex is selected is supposed to turn adjacent segments into curved line or straight lines (if already a curve).
Turning adjacent straight lines into a curve does not generate always a "real" curve. This seems to depend on whether there is already a curve in the geometry.

### Steps to reproduce the issue

1. Create a curve polygon layer
2. Add a feature combining both straight and curved lines (feat 1)
3. Add another feature with only straight lines (feat 2)
4. Using the vertex tool, select a vertex (not the one at the start of the feature -- see #53817) and press `Shit+o`
  - on feat 1: the segments adjacent to the vertex are turned into straight lines or a curved one (that is only 3points). And pressing again the keys you get the old geometry.
  - on feat 2: the segments adjacent to the vertex are split into multiple straight lines shaping a curve. Not really a curve imho. And no way to move back to the old geometry with that tool.

I think feat 2 should also turn the segments into a 3 points curved line.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.30.2-'s-Hertogenbosch | QGIS code revision | 0992b53397
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 13.4
  |   |   |  
Active Python plugins
qtribu | 0.14.2
bdtopo_importer | 0.2
MemoryLayerSaver | 4.0.4
MapsPrinter | 0.9
lizmap | 3.8.3
processing | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6
ICEtool | 1.4.0

</body></html>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Djedouas**
## Description

Fixes #53818 

This fixes a behavior that happens after finishing digitizing a polygon feature (after right click), but before the feature is saved in the layer (save button, to commit the change).

At that moment, on a CurvePolygon Layer, using the vertex tool to convert a vertex into a curve vertex always results in a segmentized curve.

image

image

Now, the digitized polygon, if no curve is part of it, is only segmentized if the layer type does not support curves.

---

Funded by Métropole de Lille

### CODE REVIEW

File: src/gui/maptools/qgsmaptoolcapturelayergeometry.cpp [hunk 1]
```diff
@@ -37,11 +37,9 @@ void QgsMapToolCaptureLayerGeometry::geometryCaptured( const QgsGeometry &geomet
       break;
     case QgsMapToolCapture::CaptureLine:
     case QgsMapToolCapture::CapturePolygon:
-      //does compoundcurve contain circular strings?
       //does provider support circular strings?
-      const bool hasCurvedSegments = captureCurve()->hasCurvedSegments();
```
Comment (m-kuhn) [inline src/gui/maptools/qgsmaptoolcapturelayergeometry.cpp:42]: I don't understand this fix, does `hasCurvedSegments()` return `false` even when there are curves?

Comment (Djedouas) [reply src/gui/maptools/qgsmaptoolcapturelayergeometry.cpp:42]: `hasCurvedSegments()` is correct.

The problem here is the following: if the digitized feature does not have curved segments, we must still keep it a CompoundCurve if the layer/provider supports curves.

That way, we can still use the "convert vertex to curve" without the #53818 issue

Comment (m-kuhn) [reply src/gui/maptools/qgsmaptoolcapturelayergeometry.cpp:42]: I am probably not correctly understanding the term "digitized feature" here. My understanding: if we convert a vertex to a curve point, the "digitized feature" now has curved segments and the check should return true. Or is the "digitized feature" something else than the geometry of the rubberband?

Comment (Djedouas) [reply src/gui/maptools/qgsmaptoolcapturelayergeometry.cpp:42]: You are right, when the user digitizes his feature using curves it works that way.

The problem is when the user digitizes his feature without curves, then switches to the vertex tool (so digitizing is finished), selects a vertex, and converts it to a curved vertex with the `O` keyboard shortcut.

Comment (m-kuhn) [reply src/gui/maptools/qgsmaptoolcapturelayergeometry.cpp:42]: So the "digitized feature" does not contain the edited geometry including the curve that was created with `O`? It's just the "old" unmodified geometry?

Comment (Djedouas) [reply src/gui/maptools/qgsmaptoolcapturelayergeometry.cpp:42]: In the end (user digitizes the feature without curve, selects vertex tool, selects a vertex, hits `O`) the newly created curve is segmentized (see capture).

Comment (m-kuhn) [reply src/gui/maptools/qgsmaptoolcapturelayergeometry.cpp:42]: I think the first part is not even needed (you can also take a pre-existing feature).
So let me ask differently: what does `captureCurve()` represent exactly? The geometry of the unmodified feature (before pressing `O`)?

Comment (Djedouas) [reply src/gui/maptools/qgsmaptoolcapturelayergeometry.cpp:42]: Yes, `captureCurve()` is the geometry before pressing `O`. It's the digitized geometry, after right-clicking.

Comment (m-kuhn) [reply src/gui/maptools/qgsmaptoolcapturelayergeometry.cpp:42]: Do we have access to the geometry including the modification?

Comment (Djedouas) [reply src/gui/maptools/qgsmaptoolcapturelayergeometry.cpp:42]: In fact, if the user digitizes 3 features without curves (for example) in a layer compatible with curves, if those features are not saved in the layer yet, the bug will occur if we try to convert a vertex.

That's why I specify "digitized features" and not "features".

Because a geometry without curves, already available from a data source (already saved in the layer), has been forced by the "save to layer / commit" action to have a correct geometry type (CompoundCurve), and everything is fine when converting one vertex to curve vertex.

Difficult to explain, but we'll get to it :D

Comment (m-kuhn) [reply src/gui/maptools/qgsmaptoolcapturelayergeometry.cpp:42]: Ok, got it. Thanks!

Do we have access to a modified geometry? I.e. if we have not added a curve, can we leave the feature uncurved (this seems to have been the intention of this)

Comment (Djedouas) [reply src/gui/maptools/qgsmaptoolcapturelayergeometry.cpp:42]: > Do we have access to a modified geometry?

Sorry, I don't understand the question...

> I.e. if we have not added a curve, can we leave the feature uncurved (this seems to have been the intention of this)

The digitizing gives `captureCurve()` as a result, which is a CompoundCurve.

If we have not added a curve, 
- before this PR the geometry was converted into a LineString (whatever the layer type is)
- after this PR the geometry won't be changed and remain CompoundCurve if the layer is compatible, or be converted into a LineString if the layer is not compatible

Comment (m-kuhn) [reply src/gui/maptools/qgsmaptoolcapturelayergeometry.cpp:42]: Hmmm... A check could be done on `g` (that's what I meant), but I'm not actually sure if that brings value.

**Review by m-kuhn — APPROVED** [review]
Lgtm, thank you
