### PR TITLE
Emit customPropertyChanged when read from XML

### LINKED ISSUE #44692: "Layer notes" icon is not displayed when copy-pasting a style
### What is the bug or the crash?

When you copy a note from one layer to another, the target layer does not display the notes icon until you edit that note.

### Steps to reproduce the issue

1. Right-click the layer with the notes, Styles --> Copy style --> All style categories
1. Right-click the destination layer,  Styles --> Paste style --> All style categories
2. There's no "layer notes" icon next to the destination layer but if you look at the context menu, there's now an "Edit layer notes..." item, meaning that there are notes applied.
3. Edit the notes and the icon is now visible

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.21.0-Master | QGIS code revision | 32c2cea54c
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PostgreSQL client version | 12.7 (Ubuntu 12.7-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.2 LTS
  |   |   |  
Active Python plugins | trackable_project_files closest_points MapsPrinter MemoryLayerSaver plugin_reloader layertreeicons db_manager grassprovider MetaSearch processing sagaprovider

</body></html>

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by troopa81**
Fixes #44692 : We need to fire the signal *customPropertyChanged* when we read custom properties from XML so the icon could be displayed when copying style.

### CODE REVIEW

File: src/core/qgsmaplayer.cpp [hunk 1]
```diff
@@ -774,7 +774,17 @@ void QgsMapLayer::resolveReferences( QgsProject *project )
 
 void QgsMapLayer::readCustomProperties( const QDomNode &layerNode, const QString &keyStartsWith )
 {
+  const QgsObjectCustomProperties oldKeys = mCustomProperties;
+
   mCustomProperties.readXml( layerNode, keyStartsWith );
+
+  for ( const QString key : mCustomProperties.keys() )
```
Comment (nyalldawson) [inline src/core/qgsmaplayer.cpp:781]:
```suggestion
  for ( const QString &key : mCustomProperties.keys() )
```

File: src/core/qgsmaplayer.cpp [hunk 2]
```diff
@@ -1963,6 +1973,10 @@ void QgsMapLayer::setCustomProperty( const QString &key, const QVariant &value )
 void QgsMapLayer::setCustomProperties( const QgsObjectCustomProperties &properties )
 {
   mCustomProperties = properties;
+  for ( const QString key : mCustomProperties.keys() )
```
Comment (nyalldawson) [inline src/core/qgsmaplayer.cpp:1976]:
```suggestion
  for ( const QString &key : mCustomProperties.keys() )
```

**Review by nyalldawson — APPROVED** [review]
