### PR TITLE
Fix PDF export size of elevation plots

### LINKED ISSUE #57880: Elevation profile PDF export
### What is the bug or the crash?

Exporting any elevation profile to PDF there is a scaling problem in the created PDF. Only a very small part of the upper left corner of the profile is visible in the exported PDF. Export the profile as image is correct using the same chart ranges as in PDF export.
I suppose it is a scaling problem.

### Steps to reproduce the issue

1. Open an elevation raster/DEM
2. Open the elevation profile panel
3. Capture a line on the DEM
4. Click on Export PDF tool
5. Accept default chart ranges ans save
6. Open the exported PDF to see the issue.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.8-Prizren | QGIS code revision | 91642333b10
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 14.12 (Ubuntu 14.12-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.4 LTS
  |   |   |  
Active Python plugins
ClipMultipleLayers | 3.2.0
quick_map_services | 0.19.34
cesium_ion | v1.0.2
fuzzy_join | 0.1
StreetView | 3.2
thematics | 0.6
QuickOSM | 2.2.3
processing_saga_nextgen | 1.0.0
arearatio | 0.2
configurable_search | 0.5
grassprovider | 2.12.99
db_manager | 0.1.20
processing | 2.12.99

</body></html>QGIS version
3.34.8-Prizren
QGIS code revision
[91642333b10](https://github.com/qgis/QGIS/commit/91642333b10)
Qt version
5.15.3
Python version
3.10.12
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
14.12 (Ubuntu 14.12-0ubuntu0.22.04.1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.4 LTS

Active Python plugins
ClipMultipleLayers
3.2.0
quick_map_services
0.19.34
cesium_ion
v1.0.2
fuzzy_join
0.1
StreetView
3.2
thematics
0.6
QuickOSM
2.2.3
processing_saga_nextgen
1.0.0
arearatio
0.2
configurable_search
0.5
grassprovider
2.12.99
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nyalldawson**
QPdfWriter doesn't return the output resolution as the device physicalDpiX(?!), so let's hack around this by just setting the output resolution to match the value reported by physicalDpiX...

Fixes #57880

### CODE REVIEW

**Comment by nyalldawson** [comment]
@troopa81 @m-kuhn @alexbruy @rouault @3nids can i get a review of this one? I'd love to get this fix in before tomorrow's set of releases...

File: src/app/elevation/qgselevationprofilewidget.cpp [hunk 1]
```diff
@@ -768,7 +768,7 @@ void QgsElevationProfileWidget::exportAsPdf()
   pageLayout.setMode( QPageLayout::FullPageMode );
   pdfWriter.setPageLayout( pageLayout );
   pdfWriter.setPageMargins( QMarginsF( 0, 0, 0, 0 ) );
-  pdfWriter.setResolution( 300 );
+  pdfWriter.setResolution( 1200 );
```
Comment (nirvn) [inline src/app/elevation/qgselevationprofilewidget.cpp:771]: (For the record, that's this value: https://github.com/qt/qtbase/blob/a984d98c971234c111dd144681402c1e20e9d806/src/gui/painting/qpdf.cpp#L1413-L1415)

**Review by nirvn — APPROVED** [review]
