### PR TITLE
fix Global Map Shading z factor value #52189

### LINKED ISSUE #52189: Global Map Shading z factor value doesn't display properly and doesn't persist
### What is the bug or the crash?

When I enter a value smaller than 0.01 into the Z Factor field (ie. with 3 or more decimal places), it re-writes it to 0.00:

image

The hillshade renders correctly, but if I make any changes to the other controls (e.g. azimuth), the Z factor reverts to 0.00.

### Steps to reproduce the issue

With a lat/long SRTM DEM layer in the canvas:
1. Go to the Layer Styling panel, Shading Renderer tab
2. Check Hillshading and attempt to put 0.00001 into the Z Factor field
3. Layer renders as expected, but Z Factor field changes to 0.00
4. Any changes to other Hillshading controls result in Z Factor reverting to 0.00 both in the field display and the layer rendering 

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.30.0-'s-Hertogenbosch | QGIS code revision | f186b8efe0
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.6
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.2 LTS
  |   |   |  
Active Python plugins
QlrBrowser | 3.0.0
SRTM-Downloader | 3.1.17
mammoth_gis_utilities | 0.1.5
qgis_resource_sharing | 1.0.0
profiletool | 4.2.3
slyr | 6.2.1
splitmultipart | 1.0.0
QuickOSM | 2.1.1
zoom_level | 0.1
qgis-maptiler-plugin | 3.1.1
geoscience | 1.9
Mergin | 2023.1
quick_map_services | 0.19.33
lizmap | 3.11.0
processing | 2.12.99
MetaSearch | 0.3.6
grassprovider | 2.12.99
db_manager | 0.1.20

</body></html>QGIS version
3.30.0-'s-Hertogenbosch
QGIS code revision
[f186b8efe0](https://github.com/qgis/QGIS/commit/f186b8efe0)
Qt version
5.15.3
Python version
3.10.6
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.2 LTS

Active Python plugins
QlrBrowser
3.0.0
SRTM-Downloader
3.1.17
mammoth_gis_utilities
0.1.5
qgis_resource_sharing
1.0.0
profiletool
4.2.3
slyr
6.2.1
splitmultipart
1.0.0
QuickOSM
2.1.1
zoom_level
0.1
qgis-maptiler-plugin
3.1.1
geoscience
1.9
Mergin
2023.1
quick_map_services
0.19.33
lizmap
3.11.0
processing
2.12.99
MetaSearch
0.3.6
grassprovider
2.12.99
db_manager
0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vcloarec**
Should fix #52189

### CODE REVIEW

File: src/core/qgselevationshadingrenderer.cpp [hunk 1]
```diff
@@ -114,16 +114,16 @@ void QgsElevationShadingRenderer::writeXml( QDomElement &elem, const QgsReadWrit
   elem.setAttribute( QStringLiteral( "combined-method" ), static_cast<int>( mCombinedElevationMethod ) );
 
   elem.setAttribute( QStringLiteral( "edl-is-active" ), mRenderEdl ? 1 : 0 );
-  elem.setAttribute( QStringLiteral( "edl-strength" ), mEyeDomeLightingStrength );
-  elem.setAttribute( QStringLiteral( "edl-distance" ), mEyeDomeLightingDistance );
+  elem.setAttribute( QStringLiteral( "edl-strength" ),  QString::number( mEyeDomeLightingStrength ) );
```
Comment (nyalldawson) [inline src/core/qgselevationshadingrenderer.cpp:117]:
```suggestion
  elem.setAttribute( QStringLiteral( "edl-strength" ),  qgsDoubleToString( mEyeDomeLightingStrength ) );
```

**Comment by vcloarec** [comment]
unrelated MingW64 test fail

**Review by nyalldawson — APPROVED** [review]
