### PR TITLE
Fix QgsImageCache [fix #43787]

### LINKED ISSUE #43787: [composer][memory] High memory usage when loading a JPG file in composers
I discovered QGIS has a **high usage of memory** when the project has one or several **print composers** with JPG raster images, usually used to show icons or pictures. 

In my context, the memory usage increase with **~ 250MB for one composer** with one JPG image, which lead to ~ 2.5 Gb if the project has 10 composers with the same JPG logo.

In **QGIS Server** context, where several QGIS workers can be used, the memory consumption adds up. If you have 10 workers, and only one "problematic" project, you fill up your memory pretty fast.

I created a sample project to illustrate the issue, with no layers and ten print composers with only the one attached JPG picture inside.

* Ubuntu 20.04 focal
* Version: QGIS 3.16.5
* Project (rename from .txt to .qgz: I renamed it due to Github extension policy): 
[high_memory_usage_composer.txt](https://github.com/qgis/QGIS/files/6678213/high_memory_usage_composer.txt)

* JPG picture: 
PDS

### PR DESCRIPTION
**Pull request by dmarteau**
## Description

Fix QgsImageCache:

- Allow configuration of the max cache size from qgis settings.
- Fix size calculation as *bytes* instead of *bits* as stated from documentation.

The actual implementation allow only a max cache size of abount 2Mb,  this is totally inneficient when using layout images for with multiple composers that could be tens (even hundreds) of Mb for large printing output. In that case image are loaded  for each composer an may increase the memory footprint dramatically (see related issue).  

This is also a problem on serverside when GetPrint requests are enabled.

Fixes #43787

### CODE REVIEW

File: src/core/qgsimagecache.cpp [hunk 1]
```diff
@@ -66,7 +67,7 @@ int QgsImageCacheEntry::dataSize() const
   int size = 0;
   if ( !image.isNull() )
   {
-    size += ( image.width() * image.height() * 32 );
+    size += ( image.width() * image.height() * 4 );
```
Comment (nyalldawson) [inline src/core/qgsimagecache.cpp:70]:
```suggestion
    size += image.sizeInBytes();
```

It's more accurate, since it'll correctly handle different colour depths.

File: src/core/qgsimagecache.cpp [hunk 2]
```diff
@@ -127,15 +134,15 @@ QImage QgsImageCache::pathAsImage( const QString &f, const QSize size, const boo
     long cachedDataSize = 0;
     bool isBroken = false;
     result = renderImage( file, size, keepAspectRatio, opacity, targetDpi, isBroken, blocking );
-    cachedDataSize += result.width() * result.height() * 32;
+    cachedDataSize += result.width() * result.height() * 4;
```
Comment (nyalldawson) [inline src/core/qgsimagecache.cpp:137]:
```suggestion
    cachedDataSize += result.sizeInBytes();
```

File: src/core/qgsimagecache.cpp [hunk 3]
```diff
@@ -127,15 +134,15 @@ QImage QgsImageCache::pathAsImage( const QString &f, const QSize size, const boo
...
     if ( cachedDataSize > mMaxCacheSize / 2 )
     {
       fitsInCache = false;
       currentEntry->image = QImage();
     }
     else
     {
-      mTotalSize += ( result.width() * result.height() * 32 );
+      mTotalSize += ( result.width() * result.height() * 4 );
```
Comment (nyalldawson) [inline src/core/qgsimagecache.cpp:145]:
```suggestion
      mTotalSize += result.sizeInBytes();
```

File: src/core/qgsimagecache.cpp (hunk 1 above)
Comment (dmarteau) [reply src/core/qgsimagecache.cpp]: Done

File: src/core/qgsimagecache.cpp (hunk 3 above)
Comment (dmarteau) [reply src/core/qgsimagecache.cpp]: Done

**Review by nyalldawson — APPROVED** [review]
