### PR TITLE
Fix missing render of global raster in small area local projection

### LINKED ISSUE #60807: WMS and XYZ Tiles Not Displaying in Project CRS (EPSG:5514) After Updating QGIS
### What is the bug or the crash?

After updating QGIS to the latest LTS version, which is currently 3.40.4 Bratislava, WMS and XYZ tile layers that are in CRS EPSG:3857 do not display at all when the project CRS is set to EPSG:5514 (or its newer realisation EPSG:8353, which are both standard in Slovakia). The layers only appear if the project CRS is changed to match the CRS of the WMS or XYZ tiles, so EPSG:3857 for most of them. This issue is also present in 3.42.0 version. This behavior was not present in QGIS 3.38.3, where on-the-fly CRS transformation worked as expected. I replicated this issue on multiple devices, including clean install of both affected versions of QGIS.

### Steps to reproduce the issue

1. Set the project CRS to EPSG:5514 (or EPSG:8353)
2. Add a WMS or XYZ tile layer with a different CRS (e.g. OpenStreetMap ttps://tile.openstreetmap.org/{z}/{x}/{y}.png)
3. Observe that the layer does not display in the map canvas.
4. Change the project CRS to match the layer's CRS (e.g., EPSG:3857), and the layer appears correctly.

### Versions

Issue was spotted in LTR version 3.40.4, but the latest version 3.42.0 is also affected. Version 3.38.3 works as expected. Other versions were not tested.

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nyalldawson**
Honestly, it was just pure chance that this worked before :shrug: 

Fixes https://github.com/qgis/QGIS/issues/60807

### CODE REVIEW

**Review by nirvn — APPROVED** [review]

File: src/core/raster/qgsrasterlayerrenderer.cpp [hunk 1]
```diff
@@ -127,55 +127,78 @@ QgsRasterLayerRenderer::QgsRasterLayerRenderer( QgsRasterLayer *layer, QgsRender
...
+      viewExtentInMapCrs = rendererContext.extent();
     }
     else
     {
       try
       {
         QgsCoordinateTransform ct = rendererContext.coordinateTransform();
         ct.setBallparkTransformsAreAppropriate( true );
-        myProjectedViewExtent = ct.transformBoundingBox( rendererContext.extent() );
+        viewExtentInMapCrs = rendererContext.mapExtent(); //ct.transformBoundingBox( rendererContext.extent() );
```
Comment (rouault) [inline src/core/raster/qgsrasterlayerrenderer.cpp:138]:
```suggestion
        viewExtentInMapCrs = rendererContext.mapExtent();
```

File: src/core/raster/qgsrasterlayerrenderer.cpp [hunk 2]
```diff
@@ -127,55 +127,78 @@ QgsRasterLayerRenderer::QgsRasterLayerRenderer( QgsRasterLayer *layer, QgsRender
...
-    myProjectedLayerExtent = layer->extent();
+    viewExtentInMapCrs = rendererContext.extent();
+    layerExtentInMapCrs = layer->extent();
   }
 
   // clip raster extent to view extent
-  QgsRectangle myRasterExtent = layer->ignoreExtents() ? myProjectedViewExtent : myProjectedViewExtent.intersect( myProjectedLayerExtent );
-  if ( myRasterExtent.isEmpty() )
+  QgsRectangle visibleExtentOfRasterInMapCrs = layer->ignoreExtents() ? viewExtentInMapCrs : viewExtentInMapCrs.intersect( layerExtentInMapCrs );
+  if ( visibleExtentOfRasterInMapCrs.isEmpty() && !rendererContext.coordinateTransform().isShortCircuited() )
```
Comment (rouault) [inline src/core/raster/qgsrasterlayerrenderer.cpp:168]: shouldn't we return when isEmpty() && isShortCircuited() ?

Comment (nyalldawson) [reply src/core/raster/qgsrasterlayerrenderer.cpp]: Indeed, fixed
