### PR TITLE
Move to QGIS4 settings storage, add migration from QGIS3

### LINKED ISSUE #60088: Qt6: recent project paths are stored in QGIS.ini in UTF-8 (instead of hex-escaped Unicode), incompatible with Qt5 version
### What is the bug or the crash?

Using a Mac Qt6 build (thanks @m-kuhn!)
– the QGIS.ini file from regular (Qt5) releases is interpreted correctly
– but when it is written back out, recent project paths are encoded in UTF-8
The UTF-8 encoded QGIS.ini cannot be read correctly by Qt5 QGIS, which tries to interpret each octet of UTF-8 as if it were a separate Unicode character.
The UTF-8 QGIS.ini is (fortunately) interpreted correctly by Qt6 QGIS. Switching back and forth between Qt5 and Qt6 builds, however, leads to increasing problems.

### Steps to reproduce the issue

1. In a Qt5 QGIS, create a project and save it under a name containing a non-ASCII character, e.g. • (U+2022). Quit QGIS
2. Examine QGIS.ini with a text editor. In the recentProjects section, find the newly saved project: its name will contain \x2022
3. Now open Qt6 QGIS. Note the (correct) filename in the recent projects lists. Quit QGIS
4. Examine QGIS.ini with a text editor. The project's name will have been rewritten in UTF-8, so it will display normally if the text editor is correctly interpreting UTF-8 text. The hex codes for the • character will be E2 80 A2.
5. Open Qt5 QGIS. In the recent files list, the file is greyed out and its name is displayed incorrectly with three characters in place of the •, the Unicode code points U+00E2 U+0080 U+00A2. Quit QGIS
6. Examine QGIS.ini with a text editor again, there will now be \xe2\x80\xa2, the misinterpretation is now hex-escaped and getting difficult to recover from.

### Versions

<head></head>
QGIS version | 3.41.0-Master
-- | --
QGIS code revision | 9f6d7bd6
 
Libraries
Qt version | 6.8.1
Python version | 3.11.10
GDAL/OGR version | 3.9.3
PROJ version | 9.5.1
EPSG Registry database version | v11.022 (2024-11-05)
GEOS version | 3.13.0-CAPI-1.19.0
SQLite version | 3.47.2
PDAL version | 2.8.1
PostgreSQL client version | unknown
SpatiaLite version | 5.1.0
QWT version | 6.3.0
QScintilla2 version | 2.14.1
OS version | macOS Sonoma (14.7)
 
Active Python plugins
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99

QGIS version
3.41.0-Master
QGIS code revision
[9f6d7bd6](https://github.com/qgis/QGIS/commit/9f6d7bd6)
 
Libraries
Qt version
6.8.1
Python version
3.11.10
GDAL/OGR version
3.9.3
PROJ version
9.5.1
EPSG Registry database version
v11.022 (2024-11-05)
GEOS version
3.13.0-CAPI-1.19.0
SQLite version
3.47.2
PDAL version
2.8.1
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.3.0
QScintilla2 version
2.14.1
OS version
macOS Sonoma (14.7)
 
Active Python plugins
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Although this is not an issue if one sticks to Qt5 or Qt6, it makes switching back and forth difficult (unless one limits filenames to ASCII characters). Some sort of workaround would be helpful to avoid problems when the transition arrives.

### PR DESCRIPTION
**Pull request by nyalldawson**
Since the QGIS 3- > QGIS 4 -> QGIS 3 round trip corrupts the QGIS settings ini, we need to silo away the QGIS 4 settings in order to avoid user profile corruption.

We do this now by a one-time copy of the loaded user profile from the QGIS3 path to a new QGIS4 path on startup. This is a lossless settings migration, with all user settings maintained. Note that it is ONE TIME ONLY, and after that initial migration any changes made to the profile in QGIS 4 won't be reflected in QGIS 3 and vice versa.

Fixes https://github.com/qgis/QGIS/issues/61636
Fixes https://github.com/qgis/QGIS/issues/60088

Marking for changelog inclusion, as this change WILL impact enterprise deployments and associated scripting

### CODE REVIEW

**Comment by agiudiceandrea** [comment]
I'm not sure to understand exactly what will happens in various situations:

1) QGIS is launched without `--profiles-path` nor `--profile`: does it copy only the profile folder of a single QGIS profile from `[system dependent path]/QGIS/QGIS3/profiles/` to `[system dependent path]/QGIS/QGIS4/profiles/` or does it copy all the profiles folders present under `[system dependent path]/QGIS/QGIS3/profiles/` to `[system dependent path]/QGIS/QGIS4/profiles/`? Is `profiles.ini` also copied from `[system dependent path]/QGIS/QGIS3/profiles/` to `[system dependent path]/QGIS/QGIS4/profiles/`?

2) QGIS is launched with `--profile profilename`: does it copy the `[system dependent path]/QGIS/QGIS3/profiles/profilename` to `[system dependent path]/QGIS/QGIS4/profiles/profilename` or all the profiles folders under `[system dependent path]/QGIS/QGIS3/profiles/`?

3) What happens if QGIS is launched with `--profiles-path profilespath` or `--profiles-path profilespath --profile profilename`?

4) What happens to absolute paths stored in QGIS3.ini which point to resources inside `[system dependent path]/QGIS/QGIS3/profiles/profilename/` when copied to QGIS4.ini in `[system dependent path]/QGIS/QGIS4/profiles/profilename/QGIS/`?

**Comment by 3nids** [comment]
apparently the issue is due to a different encoding in QSettings between Qt5 and Qt6:

[Qt5](https://doc.qt.io/archives/qt-5.15/qsettings.html):
Following the philosophy that we should be liberal in what we accept and conservative in what we generate, [QSettings](https://doc.qt.io/archives/qt-5.15/qsettings.html) will accept Latin-1 encoded INI files, but generate pure ASCII files, where non-ASCII values are encoded using standard INI escape sequences. To make the INI files more readable (but potentially less compatible), call [setIniCodec](https://doc.qt.io/archives/qt-5.15/qsettings.html#setIniCodec)().

Qt6:
In line with most implementations today, [QSettings](https://doc.qt.io/qt-6/qsettings.html) will assume that values in the INI file are UTF-8 encoded. This means that values will be decoded as UTF-8 encoded entries and written back as UTF-8. To retain backward compatibility with older Qt versions, keys in the INI file are written in %-encoded format, but can be read in both %-encoded and UTF-8 formats.
**Compatibility with older Qt versions**
Please note that this behavior is different to how [QSettings](https://doc.qt.io/qt-6/qsettings.html) behaved in versions of Qt prior to Qt 6. INI files written with Qt 5 or earlier are however fully readable by a Qt 6 based application (unless a ini codec different from utf8 had been set). But INI files written with Qt 6 will only be readable by older Qt versions if you set the "iniCodec" to a UTF-8 textcodec.

I think we can handle this in QgsSettingsEntryString if that's preferable.
But that would be my question, do we prefer distinct profiles?

**Comment by nirvn** [comment]
If feels like we need to take a decision on this sooner than later.

@3nids , this part "_INI files written with Qt 6 will only be readable by older Qt versions if you set the "iniCodec" to a UTF-8 textcodec._" refers to compatibility for Qt 5, which I guess by now for us is irrelevant (i.e., even if we would be to patch the latest Qt5 LTR with this iniCodec fix, it's still leave way too many installations broken and incompatible with hopping between 3.X and 4.X).

I'd be a +1 for distinct profiles. It's "compatible" with QGIS 4.0 hard breaking project files for QGIS 3.X builds too ;)

**Comment by 3nids** [comment]
> it's still leave way too many installations broken and incompatible with hopping between 3.X and 4.X

yes, the only alternative would be to stick to Latin-1 encoding in QGIS 4, but it's really not worth it.
And indeed, having distinct profiles makes things easier.

so +1 for me too on this approach.

**Comment by nyalldawson** [comment]
@agiudiceandrea 
> QGIS is launched without --profiles-path nor --profile: does it copy only the profile folder of a single QGIS profile from [system dependent path]/QGIS/QGIS3/profiles/ to [system dependent path]/QGIS/QGIS4/profiles/ or does it copy all the profiles folders present under [system dependent path]/QGIS/QGIS3/profiles/ to [system dependent path]/QGIS/QGIS4/profiles/? 

It does two things:
1. Creates **empty** directories under QGIS4/profiles for each profile which is present in QGIS3/profiles (if those profile folders don't already exist). 
2. Copies and translates the current profile (whatever the default one to load is) to QGIS4 (if that profile folder isn't already migrated)

> Is profiles.ini also copied from [system dependent path]/QGIS/QGIS3/profiles/ to [system dependent path]/QGIS/QGIS4/profiles/?

Not yet, I'll add that logic :+1:

> QGIS is launched with --profile profilename: does it copy the [system dependent path]/QGIS/QGIS3/profiles/profilename to [system dependent path]/QGIS/QGIS4/profiles/profilename or all the profiles folders under [system dependent path]/QGIS/QGIS3/profiles/?

It does two things:
1. Creates **empty** directories under QGIS4/profiles for each profile which is present in QGIS3/profiles (if those profile folders don't already exist). 
2. Copies and translates that target `profilename` profile to QGIS4 (if that profile folder isn't already migrated)

> What happens if QGIS is launched with --profiles-path profilespath or --profiles-path profilespath --profile profilename?

I'll make sure this does nothing. I don't think in this case we should do any auto migration, and leave that up to the system administrator to handle.

> What happens to absolute paths stored in QGIS3.ini which point to resources inside [system dependent path]/QGIS/QGIS3/profiles/profilename/ when copied to QGIS4.ini in [system dependent path]/QGIS/QGIS4/profiles/profilename/QGIS/?

I'll make it do a one-time search/replace run over that ini file

**Comment by nyalldawson** [comment]
@3nids
> But that would be my question, do we prefer distinct profiles?

I think distinct profiles is much safer.

For instance, loading a 3.0 profile in 4.0 means all non-4.0 plugins get disabled, and then loading up qgis 3 with that same profile (assuming it didn't get corrupted!) frustratingly leaves those plugins disabled.

**Comment by nyalldawson** [comment]
@agiudiceandrea should be all addressed now

**Comment by mbernasocchi** [comment]
Thanks a lot @nyalldawson, @nirvn , @agiudiceandrea and @3nids  for getting this going! 🙏🏼 
I also agree that separated profiles are the safest path here.

File: src/app/main.cpp [hunk 1]
```diff
@@ -229,6 +229,54 @@ void myPrint( const char *fmt, ... )
...
+  {
+    QgsDebugMsgLevel( u"No QGIS3 profiles path exists at %1, nothing to migrate"_s.arg( qgis3ProfilesRootPath.path() ), 2 );
+    return;
+  }
+
+  QgsDebugMsgLevel( u"Syncing profile list from %1 to %2"_s.arg( qgis3ProfilesRootPath.path(), qgis4ProfilesRootPath.path() ), 2 );
+  const QStringList qgis3Profiles = QDir( qgis3ProfilesRootPath ).entryList( QDir::Dirs | QDir::NoDotAndDotDot );
+  if ( qgis4ProfilesRootPath.exists() )
+  {
+    if ( !qgis4ProfilesRootPath.mkpath( "." ) )
```
Comment (nirvn) [inline src/app/main.cpp]: Is there a logic issue here? shouldn't we make path if !qgis4ProfilesRootPath.exists() ?

File: src/app/main.cpp [hunk 2]
```diff
@@ -229,6 +229,54 @@ void myPrint( const char *fmt, ... )
...
 }
 
+void copyProfileNamesFromQgis3( const QString &configLocalStorageLocation )
+{
+  const QDir qgisConfigRootPath = QDir( configLocalStorageLocation );
+  const QDir qgis3ProfilesRootPath = QDir( QDir::cleanPath( qgisConfigRootPath.filePath( u"../QGIS3/profiles"_s ) ) );
+  const QDir qgis4ProfilesRootPath = QDir( QDir::cleanPath( qgisConfigRootPath.filePath( u"../QGIS4/profiles"_s ) ) );
+  if ( !qgis3ProfilesRootPath.exists() )
+  {
+    QgsDebugMsgLevel( u"No QGIS3 profiles path exists at %1, nothing to migrate"_s.arg( qgis3ProfilesRootPath.path() ), 2 );
```
Comment (nirvn) [inline src/app/main.cpp:239]: Maybe around the time of 4.2 or 4.4, we'll want to either get rid of this message or lower priority to 4? It'll become increasingly the case that a QGIS3/profiles will not exist for new users.

File: src/app/main.cpp [hunk 3]
```diff
@@ -229,6 +229,54 @@ void myPrint( const char *fmt, ... )
...
+    }
+  }
+
+  const QString qgis3ProfilesIniPath = QDir::cleanPath( qgisConfigRootPath.filePath( u"../QGIS3/profiles/profiles.ini"_s ) );
+  const QString qgis4ProfilesIniPath = QDir::cleanPath( qgisConfigRootPath.filePath( u"../QGIS4/profiles/profiles.ini"_s ) );
+  if ( QFile::exists( qgis3ProfilesIniPath ) && !QFile::exists( qgis4ProfilesIniPath ) )
+  {
+    if ( !QFile::copy( qgis3ProfilesIniPath, qgis4ProfilesIniPath ) )
+    {
+      QgsDebugError( u"Could not copy profiles.ini from %1 to %2, skipping"_s.arg( qgis3ProfilesIniPath, qgis4ProfilesIniPath ) );
```
Comment (nirvn) [inline src/app/main.cpp:275]: Should we try and copy the .ini before, and if it fails avoid copying individual profile folders? Without the ini, the folders won't register anyways?

File: src/app/main.cpp (hunk 1 above)
Comment (nyalldawson) [reply src/app/main.cpp]: indeed! (It didn't have an impact because we later create this parent path in the mkpath command for each profile.)

File: src/app/main.cpp (hunk 3 above)
Comment (nyalldawson) [reply src/app/main.cpp:275]: The ini is not mandatory -- it just contains the last used profile and the setting for which profile to default to.

**Review by nirvn — APPROVED** [review]

**Comment by agiudiceandrea** [comment]
@nyalldawson, what is the reasonale of creating empty directories under QGIS4/profiles for each profile which is present in QGIS3/profiles? The QGIS4/profiles folder is now bloated by empty profile folders which probably will never need to be used with a Qt6 build and, even deleted from QGIS4/profiles, they will be recreated each time QGIS 3.99/4 starts.
I also worry that some user, looking at the folder in QGIS4/profiles and seeing all the profile folders, might think that all the profiles have been actually copied from QGIS3/profiles and thus might delete the profiles folder in QGIS3/profiles...
Why not only copying the profile folder that QGIS is started with?

Anyway, I've tested the new build and I'm seeing a little glitch: after starting for the first time with the old profile (with --profile xxxx), despite such profile xxxx was set to have the GUI in American English (on an Italian Windows system), nevertless QGIS starts with an Italian GUI. The second time QGIS is started, it correctly starts with the American English GUI.

**Comment by nyalldawson** [comment]
@agiudiceandrea 
> what is the reasonale of creating empty directories under QGIS4/profiles for each profile which is present in QGIS3/profiles?

That's what the profiles list is constructed from. If we didn't create those empty directories, then a user won't see any profiles except in QGIS4 except for the default one.

**Comment by agiudiceandrea** [comment]
> That's what the profiles list is constructed from. If we didn't create those empty directories, then a user won't see any profiles except in QGIS4 except for the default one.

It makes sense. Thanks for the explanation. Do you know what might be the cause of the glitch about the GUI language at first start?

**Comment by agiudiceandrea** [comment]
> I'll make it do a one-time search/replace run over that ini file

Hi @nyalldawson, it seems to me the search/replace is not effective, at least on Windows: using a QGIS 3.44 profile with the latest QGIS 3.99.0-Master the paths pointing to the old user profile's folder are not replaced with the new path.

For example, the QGIS3.ini of the qgis344 profile's folder in %AppData%\QGIS\QGIS3\profiles contains the following paths:
`recentProjects\1\previewImage=C:/Users/Andrea/AppData/Roaming/QGIS/QGIS3\\profiles\\qgis344//previewImages/3203d2e7668d272eb46a77d2cb174ca3.png`
`recentProjects\8\previewImage=C:/Users/Andrea/AppData/Roaming/QGIS/QGIS3\\profiles\\qgis344//previewImages/e6b01141a1ac612c3da62a5f3caa17fc.png`
`projectTemplateDir=C:/Users/Andrea/AppData/Roaming/QGIS/QGIS3\\profiles\\qgis344/project_templates`
`searchPathsForSVG=C:/OSE37B~1/apps/qgis/./svg/, C:/Users/Andrea/AppData/Roaming/QGIS/QGIS3\\profiles\\qgis344/svg/`
`PackageInstallerQgis\prefix=C:\\Users\\Andrea\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\qgis344\\python\\depend`

After opening the latest QGIS 3.99.0-Master with the same profile, the profile folder is copied into \QGIS\QGIS4\profiles and QGIS3.ini to QGIS4.ini. Anyway the paths pointing to \QGIS\QGIS3\ have not been replaced with \QGIS\QGIS4\ in QGIS4.ini:

`recentProjects\1\previewImage=C:/Users/Andrea/AppData/Roaming/QGIS/QGIS3\\profiles\\qgis344//previewImages/3203d2e7668d272eb46a77d2cb174ca3.png`
`recentProjects\8\previewImage=C:/Users/Andrea/AppData/Roaming/QGIS/QGIS3\\profiles\\qgis344//previewImages/e6b01141a1ac612c3da62a5f3caa17fc.png`
`projectTemplateDir=C:/Users/Andrea/AppData/Roaming/QGIS/QGIS3\\profiles\\qgis344/project_templates`
`searchPathsForSVG=C:/OSE37B~1/apps/qgis/./svg/, C:/Users/Andrea/AppData/Roaming/QGIS/QGIS3\\profiles\\qgis344/svg/`
`PackageInstallerQgis\prefix=C:\\Users\\Andrea\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\qgis344\\python\\dependencies`
