### PR TITLE
Fix bug when exporting layer and using both displayed value and diffe…

### LINKED ISSUE #54005: Value Becomes 0 When Exporting Layer with Different Field Name and Use Displayed Value from Value Relation
### What is the bug or the crash?

When exporting a vector layer, there are options to use a different export name and replace the value with the displayed value (with different field data types e.g. `int` to `string`). If we only use one of those two option, it works fine. But if we use both options, the value of the attribute is set to 0.

### Steps to reproduce the issue

1. Create a layer (layer A) whose field that referenced to the other layer's (layer B) value via value relation. The fields have different data types (e.g. int in layer A, and string/text in layer B). You can also use this test data: [db-null-export.zip](https://github.com/qgis/QGIS/files/12214562/db-null-export.zip) Illustrated below: image

2. Right-click on layer A -> Export -> Save Feature As
3. Set the parameters like below:
     image
4. Click `Ok`
5. Result as below: image

As you can see, the `Both` field has value = 0, while the one using only value relations has a correct value. The `Both Integer` field also has a correct value because it has the same data type in layers A and B

### Versions

Also occurs in QGIS Master.

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.32.1-Lima | QGIS code revision | 4a078ecf63
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.6
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 14.8 (Ubuntu 14.8-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Pop!_OS 22.04 LTS
  |   |   |  
Active Python plugins
qgis_hub_plugin | 0.1.0
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.32.1-Lima
QGIS code revision
[4a078ecf63](https://github.com/qgis/QGIS/commit/4a078ecf63)
Qt version
5.15.3
Python version
3.10.6
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
14.8 (Ubuntu 14.8-0ubuntu0.22.04.1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Pop!_OS 22.04 LTS

Active Python plugins
qgis_hub_plugin
0.1.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ismailsunni**
…rent export attribute name

## Description

Adding consideration when the field doesn't use the original name when the user wants to use the displayed value (value relation). Fix #54005 

Sample project to test
[db-null-export.zip](https://github.com/qgis/QGIS/files/12214414/db-null-export.zip)

Before:
 image
After:
image

### CODE REVIEW

File: src/app/qgisapp.cpp [hunk 1]
```diff
@@ -8337,7 +8337,7 @@ void QgisApp::saveStyleFile( QgsMapLayer *layer )
 class QgisAppFieldValueConverter : public QgsVectorFileWriter::FieldValueConverter
 {
   public:
-    QgisAppFieldValueConverter( QgsVectorLayer *vl, const QgsAttributeList &attributesAsDisplayedValues );
+    QgisAppFieldValueConverter( QgsVectorLayer *vl, const QgsAttributeList &attributesAsDisplayedValues, const QStringList attributesExportNames );
```
Comment (nyalldawson) [inline src/app/qgisapp.cpp:8340]:
```suggestion
    QgisAppFieldValueConverter( QgsVectorLayer *vl, const QgsAttributeList &attributesAsDisplayedValues, const QStringList &attributesExportNames );
```

File: src/app/qgisapp.cpp [hunk 2]
```diff
@@ -8348,11 +8348,14 @@ class QgisAppFieldValueConverter : public QgsVectorFileWriter::FieldValueConvert
   private:
     QPointer< QgsVectorLayer > mLayer;
     QgsAttributeList mAttributesAsDisplayedValues;
+    QStringList mAttributesExportNames;
 };
 
-QgisAppFieldValueConverter::QgisAppFieldValueConverter( QgsVectorLayer *vl, const QgsAttributeList &attributesAsDisplayedValues )
+QgisAppFieldValueConverter::QgisAppFieldValueConverter( QgsVectorLayer *vl, const QgsAttributeList &attributesAsDisplayedValues, const QStringList attributesExportNames )
```
Comment (nyalldawson) [inline src/app/qgisapp.cpp:8354]:
```suggestion
QgisAppFieldValueConverter::QgisAppFieldValueConverter( QgsVectorLayer *vl, const QgsAttributeList &attributesAsDisplayedValues, const QStringList &attributesExportNames )
```

**Review by nyalldawson — APPROVED** [review]

**Comment by ismailsunni** [comment]
Thanks @nyalldawson for the review. Do you think it's ok to backport the fix to the LTR also?
