### PR TITLE
[vector file writer] Fix another FID corner scenario (fixes #34613)

### LINKED ISSUE #34613: FID data type error saving from GPKG to SHP and back to GPKG
Running QGIS 3.10.2 64-bit or 3.11 weekly (code revision 7c7c2d775b) on Windows 10:

If you save a layer from a geopackage as a shapefile, the FID from the geopackage layer is created as data type 'double' in the shapefile. If your workflow then requires saving back into a geopackage layer, the operation fails because of "wrong field type for FID". I assume that the geopackage is expecting a 64-bit long integer data type.

### PR DESCRIPTION
**Pull request by nirvn**
## Description

Our old friend FID coming in to complicate things, again.

This PR fixes a corner scenario whereas a user is trying to convert a non-geopackage dataset with a pre-existing FID field to  geopackage which would fail when the FID field was not set to integer. This could easily happen when someone saves an original geopackage as shapefile - which would transform the integer field to double field with precision 0 - and then back to geopackage.

It fixes #25795 and #34613.

### CODE REVIEW

**Comment by nirvn** [comment]
@rouault , you might want to consider adding a similar workaround in GDAL itself for this scenario.

File: src/core/qgsvectorfilewriter.cpp [hunk 1]
```diff
@@ -650,7 +650,16 @@ void QgsVectorFileWriter::init( QString vectorFileName,
             break;
 
           case QVariant::Double:
-            ogrType = OFTReal;
+            if ( ( mOgrDriverName == QLatin1String( "GPKG" ) || mOgrDriverName == QLatin1String( "SQLite" ) ) &&
+                 attrField.precision() == 0 && attrField.name().compare( QStringLiteral( "fid" ), Qt::CaseInsensitive ) == 0 )
+            {
+              // Convert field to match required FID type
+              ogrType = OFTInteger;
```
Comment (rouault) [inline src/core/qgsvectorfilewriter.cpp:657]: for more safety:
```suggestion
              ogrType = OFTInteger64;
```

File: src/core/qgsvectorfilewriter.cpp [hunk 2]
```diff
@@ -650,7 +650,16 @@ void QgsVectorFileWriter::init( QString vectorFileName,
             break;
 
           case QVariant::Double:
-            ogrType = OFTReal;
+            if ( ( mOgrDriverName == QLatin1String( "GPKG" ) || mOgrDriverName == QLatin1String( "SQLite" ) ) &&
```
Comment (rouault) [inline src/core/qgsvectorfilewriter.cpp:653]: we only need this for GPKG
```suggestion
            if ( mOgrDriverName == QLatin1String( "GPKG") &&
```

File: src/core/qgsvectorfilewriter.cpp [hunk 3]
```diff
@@ -650,7 +650,16 @@ void QgsVectorFileWriter::init( QString vectorFileName,
...
+                 attrField.precision() == 0 && attrField.name().compare( QStringLiteral( "fid" ), Qt::CaseInsensitive ) == 0 )
```
Comment (rouault) [inline src/core/qgsvectorfilewriter.cpp:654]: Instead of comparing to "fid", we should compare to the value of the FID layer creation option (which defaults to "fid")

**Review by rouault — COMMENTED** [review]
wouldn't hurt to add a test

File: src/core/qgsvectorfilewriter.cpp (hunk 3 above)
Comment (nirvn) [reply src/core/qgsvectorfilewriter.cpp:654]: @rouault , fair point.

**Comment by saberraz** [comment]
Hi @nirvn thanks for looking into this issue. Will this be backported to 3.16?

**Comment by rouault** [comment]
Due to https://github.com/OSGeo/gdal/pull/3812, you might conditionalize the new code path with GDAL_VERSION_NUM < GDAL_COMPUTE_VERSION(3,3,1)

**Comment by nirvn** [comment]
@rouault , :muscle: , super.

File: src/core/qgsvectorfilewriter.cpp (hunk 2 above)
Comment (nirvn) [reply src/core/qgsvectorfilewriter.cpp:653]: @rouault , shouldn't that also apply to spatialite datasets?

Comment (nirvn) [reply src/core/qgsvectorfilewriter.cpp:653]: Ignore me :) thanks for the review.

Comment (rouault) [reply src/core/qgsvectorfilewriter.cpp:653]: > shouldn't that also apply to spatialite datasets?

Potentially yes, but as QGIS doesn't expose the FID column of Spatialite datasets as an attribute column, the practical risk is much lower

**Comment by nirvn** [comment]
@rouault , comments addressed, thanks for the review.

**Comment by nirvn** [comment]
@rouault , if the changes now satisfy you, can you approve? Ready on my end.

File: src/core/qgsvectorfilewriter.cpp [hunk 4]
```diff
@@ -237,6 +237,21 @@ void QgsVectorFileWriter::init( QString vectorFileName,
     mOgrDriverName = driverName;
   }
 
+  QString fidFieldName;
```
Comment (rouault) [inline src/core/qgsvectorfilewriter.cpp:240]: could be protected under #if GDAL_VERSION_NUM < GDAL_COMPUTE_VERSION(3,3,1) as well. This will make future clean-up easier.
(and the "defined(GDAL_COMPUTE_VERSION) &&" test is not needed given our base requirement for GDAL)

**Comment by nirvn** [comment]
@rouault , test added, last comment addressed.

File: tests/src/python/test_provider_ogr.py [hunk 5]
```diff
@@ -1297,6 +1297,25 @@ def testShapefilesWithNoAttributes(self):
         vl = QgsVectorLayer(os.path.join(d.path(), 'writetest.shp'))
         self.assertEqual(vl.featureCount(), 1)
 
+    def testFidDoubleSaveAsGeopackage(self):
+        """Test issue GH #25795"""
+
+        ml = QgsVectorLayer('Point?crs=epsg:4326&field=fid:double(20:0)', 'test', 'memory')
+        self.assertTrue(ml.isValid())
+        self.assertEqual(ml.fields()[0].type(), 10)
```
Comment (rouault) [inline tests/src/python/test_provider_ogr.py:1305]: isn't there a constant name instead of 10 ?

File: tests/src/python/test_provider_ogr.py [hunk 6]
```diff
@@ -1297,6 +1297,25 @@ def testShapefilesWithNoAttributes(self):
...
+        options = QgsVectorFileWriter.SaveVectorOptions()
+        options.driverName = 'GPKG'
+        options.layerName = 'fid_double_test'
+        err, _ = QgsVectorFileWriter.writeAsVectorFormatV2(ml, os.path.join(d.path(), 'fid_double_test.gpkg'),
+                                                           QgsCoordinateTransformContext(), options)
+        self.assertEqual(err, QgsVectorFileWriter.NoError)
+        self.assertTrue(os.path.isfile(os.path.join(d.path(), 'fid_double_test.gpkg')))
+
+        vl = QgsVectorLayer(os.path.join(d.path(), 'fid_double_test.gpkg'))
+        self.assertEqual(vl.fields()[0].type(), 4)
```
Comment (rouault) [inline tests/src/python/test_provider_ogr.py:1317]: same here

**Comment by nirvn** [comment]
@rouault , done.

**Review by rouault — APPROVED** [review]
