### PR TITLE
fix inserting break lines in dual edge triangulation

### LINKED ISSUE #30549: TIN creation crash
Crash ID: 185de4a9a11eb29f05672d8b176e731c0d36ee2f

```
Stack Trace


MathUtils::lineIntersection :
DualEdgeTriangulation::insertForcedSegment :
DualEdgeTriangulation::addLine :
QgsTinInterpolator::insertData :
QgsTinInterpolator::initialize :
QgsTinInterpolator::interpolatePoint :
PyInit__analysis :
QgsGridFileWriter::writeFile :
PyInit__analysis :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_sip :
CPLStringList::empty :
PyInit__core :
QgsProcessingAlgorithm::runPrepared :
QgsProcessingAlgRunnerTask::run :
PyInit__core :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
```

QGIS Info
QGIS Version: 3.8.0-Zanzibar
QGIS code revision: 11aff65f10
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

### PR DESCRIPTION
**Pull request by vcloarec**
fix  #30549 and more generally inserting break line in dual edge triangulation.
Hope it is the last issue... (surely not!)

### CODE REVIEW

File: src/analysis/interpolation/qgsdualedgetriangulation.cpp [hunk 1]
```diff
@@ -1327,13 +1327,39 @@ unsigned int QgsDualEdgeTriangulation::insertEdge( int dual, int next, int point
 
 }
 
+static bool triangleIsFlat( const QgsPoint &pt1, const QgsPoint &pt2, const QgsPoint &pt3, double tolerance )
```
Comment (lbartoletti) [inline src/analysis/interpolation/qgsdualedgetriangulation.cpp:1330]: Maybe this method could be useful in QgsTriangle class?

Comment (lbartoletti) [reply src/analysis/interpolation/qgsdualedgetriangulation.cpp:1330]: Or in QgsGeometryUtils to avoid the creation of a triangle each time

Comment (vcloarec) [reply src/analysis/interpolation/qgsdualedgetriangulation.cpp:1330]: Ad this function is not complete (but sufficient in this context), no sure. Indeed, only the distance between the segment [pt1,pt2] from pt3 is checked. So if this segment is very small and pt3 far away, the triangle is flat but the function does not return `true`. 
This is acceptable here and changing that will slow down the function. I think I will change the function name / add comments.

**Review by nyalldawson — COMMENTED** [review]
Pretty tricky to review this one, but I can't see any glaring issues!

**Comment by vcloarec** [comment]
@nyalldawson , also pretty tricky to fix...

**Comment by nyalldawson** [comment]
I can imagine! I'm just glad that these classes are getting some love and no longer produce embarrassing results!!
