### PR TITLE
[maptools] Fix extra duplicated feature when using the copy+move map tool action

### LINKED ISSUE #54607: Copy and move map tool duplicates original feature
### What is the bug or the crash?

When using the copy and move features map tool it duplicates the original feature in addition to the new copied and moved feature. GIF to demonstrate:
copyandmovebug

### Steps to reproduce the issue

1. Create a new (temporary) layer (geometry type doesn't matter)
2. Add a new feature.
3. Use the 'copy and move feature(s)' map tool to copy the feature.
4. Check if the original feature was duplicated (by moving, or check the attribute table/use identify etc.)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.33.0-Master | QGIS code revision | 569d60ddb7
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.4.3
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.2 LTS
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
quick_map_services | 0.19.33
infrao | 0.1.1
processing | 2.12.99
MetaSearch | 0.3.6
db_manager | 0.1.20
grassprovider | 2.12.99

</body></html>QGIS version
3.33.0-Master
QGIS code revision
[569d60ddb7](https://github.com/qgis/QGIS/commit/569d60ddb7)
Qt version
5.15.3
Python version
3.10.12
GDAL/OGR version
3.4.3
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.2 LTS

This copy of QGIS writes debugging output.

Active Python plugins
quick_map_services
0.19.33
infrao
0.1.1
processing
2.12.99
MetaSearch
0.3.6
db_manager
0.1.20
grassprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Tried also in 3.32.0, doesn't appear there. Might be related to #53965?

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This PR fixes https://github.com/qgis/QGIS/issues/54607 , a regression which slipped into QGIS master through this PR (#53965). 

@agiudiceandrea , thanks for the ping, I wouldn't have caught the issue being filed otherwise. Cheers.

### CODE REVIEW

**Comment by agiudiceandrea** [comment]
Thank you for fixing it so quickly.

File: src/core/vector/qgsvectorlayertools.cpp [hunk 1]
```diff
@@ -69,34 +76,25 @@ bool QgsVectorLayerTools::copyMoveFeatures( QgsVectorLayer *layer, QgsFeatureReq
...
-      const QgsFeatureId fid = newFeature.id();
-#endif
-      // paste feature
-      if ( !layer->addFeature( newFeature ) )
-      {
-        couldNotWriteCount++;
-        QgsDebugError( QStringLiteral( "Could not add new feature. Original copied feature id: %1" ).arg( fid ) );
-      }
-      else
+      fidList.insert( newFeature.id() );
```
Comment (troopa81) [inline src/core/vector/qgsvectorlayertools.cpp:90]: We should not do this part if the addFeature has failed, no ? 

It looks like also the `fidList` param is usefull only for `request` parameter which is never used. Could we get rid of these?

**Review by troopa81 — COMMENTED** [review]
Can we have a test for this ?

File: src/app/qgsmaptoolmovefeature.cpp [hunk 2]
```diff
@@ -244,6 +244,7 @@ void QgsMapToolMoveFeature::cadCanvasReleaseEvent( QgsMapMouseEvent *e )
       }
       case CopyMove:
         QgsFeatureRequest request;
+        qDebug() << mMovedFeatures;
```
[the remark this answers is not in the document]
Comment (nirvn) [reply src/app/qgsmaptoolmovefeature.cpp]: Fixed.

File: src/core/vector/qgsvectorlayertools.cpp (hunk 1 above)
Comment (nirvn) [reply src/core/vector/qgsvectorlayertools.cpp]: Fixed, thanks for spotting this.

The request parameter is passed by reference in the function, I assume the intent was for the request to have filter IDs that match the created features. In any case, I'll avoid changing for now since I wasn't the original author.

**Review by nyalldawson — APPROVED** [review]

**Comment by nirvn** [comment]
@nyalldawson , thanks

@troopa81 , test tweaked to insure only one feature is copied.

**Review by troopa81 — APPROVED** [review]
