### PR TITLE
Server: add logging handlers for CRS grid issues

### LINKED ISSUE #43072: Datum transformation using custom gsb grid for WMS Layer in QGIS Server does not work
Hello there, 

we have a problem using datum transformations within QGIS Server 3.16 on Ubuntu 20.04 (Focal Fossa). Within a qgs project with layers of different projections (EPSG: 3397 and EPSG: 25832) there is no datum transformation applied on these layers.

There are others with the same issue (https://gis.stackexchange.com/questions/364744/datum-transformation-in-qgis-server-3-10) but there are no replies yet.

It works with an older QGIS Server 2.18 whe have running. 
On the newer one everything is set up like described in this thread: https://www.mail-archive.com/qgis-user@lists.osgeo.org/msg35445.html. The corresponding NTv2gridTH.gsb file is placed in the proj folder /usr/share/proj, there is an entry for the transformation within the srs.db and the standard transformation is defined in the apache configs.
But unfortunately this does not work on the newer QGIS 3.16 anymore. The function was implemented here: https://github.com/qgis/QGIS/blob/28c0380166078bcf6605f3784fb87944d5ee688b/src/core/qgsmaprenderer.cpp#L1300, but the file qgsmaprenderer.cpp is not part of QGIS 3 anymore.

The hope was, that the QGIS Server recognizes a standard transformation of a project file, which can be set in project settings within "project - settings - transformation" (https://www.mail-archive.com/qgis-user@lists.osgeo.org/msg44456.html), but this setting has not effect on the interpretation of the QGIS Server.

Does the problem corresponse to changes with the use of PROJ6 since QGIS 3.10? (Another issue but mentioned here: https://www.mail-archive.com/qgis-user@lists.osgeo.org/msg45441.html) 

Two raster layers with different projections loaded via wms from the qgis server:
example

Here is a qgs-project with two included raster layers with the named projections to test this on an own qgis server:
https://cloud.jena.de/index.php/s/0YWh2ZXE3MEEfjR 

I would appreciate any help. Thanks!

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #43072  --- well, not really a fix, but without
this information in the logs life is harder.

This PR adds some more information in the logs so that the instructions to fix the issue are visible.

Screenshot_20210524_150540

### CODE REVIEW

File: src/server/qgsserver.cpp [hunk 1]
```diff
@@ -216,6 +216,73 @@ bool QgsServer::init()
     QgsServerLogger::instance()->setLogStderr();
   }
 
+  // Logging handlers for CRS grid issues
+  QgsCoordinateTransform::setCustomMissingRequiredGridHandler( [ = ]( const QgsCoordinateReferenceSystem & sourceCrs,
+      const QgsCoordinateReferenceSystem & destinationCrs,
+      const QgsDatumTransform::GridDetails & grid )
+  {
+    QgsServerLogger::instance()->logMessage( QStringLiteral( "Cannot use project transform between %1 and %2 - missing grid %3" )
```
Comment (nyalldawson) [inline src/server/qgsserver.cpp:224]:
```suggestion
    QgsServerLogger::instance()->logMessage( QStringLiteral( "No transform is available between %1 and %2 - missing grid %3" )
```

File: src/server/qgsserver.cpp [hunk 2]
```diff
@@ -216,6 +216,73 @@ bool QgsServer::init()
...
+  QgsCoordinateTransform::setCustomMissingGridUsedByContextHandler( [ = ]( const QgsCoordinateReferenceSystem & sourceCrs,
+      const QgsCoordinateReferenceSystem & destinationCrs,
+      const QgsDatumTransform::TransformDetails & details )
+  {
+    QgsServerLogger::instance()->logMessage( QStringLiteral( "Cannot use project transform between %1 and %2 - %3" )
+        .arg( sourceCrs.userFriendlyIdentifier( QgsCoordinateReferenceSystem::ShortString ),
+              destinationCrs.userFriendlyIdentifier( QgsCoordinateReferenceSystem::ShortString ),
+              details.name ),
+        QStringLiteral( "QGIS Server" ), Qgis::MessageLevel::Warning );
+  } );
```
Comment (nyalldawson) [inline src/server/qgsserver.cpp:241]: If you want to be even more helpful I'd suggest inserting this here:

```
  for ( const QgsDatumTransform::GridDetails &grid : details.grids )
  {
    if ( !grid.isAvailable )
    {
      gridName = grid.shortName;
      QString m = QStringLiteral( "This transformation requires the grid file “%1”, which is not available for use on the system." ).arg( grid.shortName );
      // ^^ either append to existing message, or log this as a separate message 
```

File: src/server/qgsserver.cpp [hunk 3]
```diff
@@ -216,6 +216,73 @@ bool QgsServer::init()
...
+                        .arg( preferredOperation.name ).arg( preferredOperation.accuracy );
+
+    const QString longMessage = QStringLiteral( "The preferred transform between '%1' and '%2' is not available for use on the system.\n" ).arg( sourceCrs.userFriendlyIdentifier(),
+                                destinationCrs.userFriendlyIdentifier() )
+                                + gridMessage + accuracyMessage;
+
+    QgsServerLogger::instance()->logMessage( longMessage, QStringLiteral( "QGIS Server" ), Qgis::MessageLevel::Warning );
+
+  } );
+
```
Comment (nyalldawson) [inline src/server/qgsserver.cpp:285]: There's also setCustomCoordinateOperationCreationErrorHandler, which should be handled here as it will only be emitted for critical errors

**Review by nyalldawson — APPROVED** [review]
