### PR TITLE
[Snapping] Remove and delete locator when layer is destroyed

### LINKED ISSUE #59530: Vertex tool and snapping stop working when layers are removed and added to the project multiple times
### What is the bug or the crash?

Snapping and vertex tool stop working when layers are removed and added again back to the project. Sometimes this happens after the first time and sometimes after numerous times. Only way to recover from this is to restart QGIS.

snapping_stops_working

### Steps to reproduce the issue

It was incredibly difficult to reproduce the bug reliably but finally after hours of trying I managed to do that with a little bit of scripting. I prepared a [snapping.zip](https://github.com/user-attachments/files/17831209/snapping.zip) that includes snapping.gpkg with two layers and python script snapping.py with this content:

<details>

```python
from pathlib import Path
from typing import cast

from qgis.core import (
    Qgis,
    QgsPointXY,
    QgsProject,
    QgsSnappingConfig,
    QgsSnappingUtils,
    QgsVectorLayer,
)
from qgis.gui import QgisInterface
from qgis.PyQt.QtCore import QCoreApplication
from qgis.utils import iface as utils_iface

GPKG_PATH = Path(__file__).parent / "snapping.gpkg"

LAYER_NAMES = ["area1", "area2"]

SHAPES = ["Polygon ((0 0, 1 0, 1 1, 0 1, 0 0))", "Polygon ((2 0, 3 0, 3 1, 2 1, 2 0))"]


iface = cast(QgisInterface, utils_iface)


def set_snapping_mode_to_all_layers():
    snapping_config = QgsSnappingConfig(QgsProject.instance().snappingConfig())
    snapping_config.setMode(Qgis.SnappingMode.AllLayers)
    snapping_config.setEnabled(True)
    QgsProject.instance().setSnappingConfig(snapping_config)


def check_if_location_snapping_is_working_for_layers() -> bool:
    for layer in QgsProject.instance().mapLayers().values():
        works = _check_if_location_snapping_is_working_for_layer(layer)
        if not works:
            return False
    return True


def snapping_still_works() -> bool:
    """
    For users to be able to observe the bug,
    the snapping should not be working initially
    """
    if not check_if_location_snapping_is_working_for_layers():
        layer = next(
            layer.name()
            for layer in QgsProject.instance().mapLayers().values()
            if layer.isEditable()
        )
        print(f"Snapping is not working for {layer}")
        return False

    for i in range(100):
        print(f"Sub-iteration {i}")
        _add_layers()
        if not check_if_location_snapping_is_working_for_layers():
            return True
        _remove_layers()
        _process_events()

    return True


def _check_if_location_snapping_is_working_for_layer(layer: QgsVectorLayer) -> bool:
    layer.startEditing()
    iface.setActiveLayer(layer)
    geom = next(iter(layer.getFeatures())).geometry()
    vertex = next(iter(geom.vertices()))
    utils: QgsSnappingUtils = iface.mapCanvas().snappingUtils()
    utils.setMapSettings(iface.mapCanvas().snappingUtils().mapSettings())
    utils.setCurrentLayer(layer)

    point = QgsPointXY(vertex.x(), vertex.y())
    match = utils.snapToMap(point, relaxed=False)
    if not match.isValid():
        # Leave the layer in edit mode to make it easy to observe manually
        return False
    layer.rollBack()
    return True


def _add_layers():
    for layer_name in LAYER_NAMES:
        layer = QgsVectorLayer(
            f"{GPKG_PATH!s}|layername={layer_name}", layer_name, "ogr"
        )
        QgsProject.instance().addMapLayer(layer)


def _remove_layers():
    QgsProject.instance().removeAllMapLayers()


def _process_events():
    QCoreApplication.processEvents()


def test_reproduce_snapping_bug():
    set_snapping_mode_to_all_layers()
    for i in range(20):
        print(f"Iteration {i}")
        snapping_working = snapping_still_works()
        if not snapping_working:
            return
        _process_events()
    print("Could not reproduce the bug...")

```

</details>

1. Download and extract [snapping.zip](https://github.com/user-attachments/files/17831209/snapping.zip) 
2. Open QGIS
3. Open and run snapping.py in QGIS Python console
4. Run `test_reproduce_snapping_bug()` in python console
5. Observe how snapping nor vertex tool are no longer working with the layer mentioned in the console

 I sincerely ask not to put a "Python Console" label in this issue since this is merely a way to reproduce the bug reliably. 

### Versions

<details>

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.40.0-Bratislava</td></tr><tr><td>QGIS code branch</td><td><a href="https://github.com/qgis/QGIS/tree/release-3_40">Release 3.40</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.15</td></tr><tr><td>Python version</td><td>3.12.7</td></tr><tr><td>GDAL/OGR version</td><td>3.10.0</td></tr><tr><td>PROJ version</td><td>9.5.0</td></tr><tr><td>EPSG Registry database version</td><td>v11.016 (2024-08-31)</td></tr><tr><td>GEOS version</td><td>3.12.2-CAPI-1.18.2 (Compiled)<br/>3.13.0-CAPI-1.19.0 (Running)</td></tr><tr><td>SQLite version</td><td>3.46.1</td></tr><tr><td>PDAL version</td><td>2.8.0</td></tr><tr><td>PostgreSQL client version</td><td>16.3</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.3.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>EndeavourOS</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>processing</td><td>2.12.99</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr></table>

And also with 3.41.0-Master

</details>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I tested with QGIS debugging and it seems that the bug lies in this line: https://github.com/qgis/QGIS/blob/458185a6704cb032f9c7dc31de1a6b89904066eb/src/core/qgspointlocator.cpp#L1338 For some reason when the snapping is halted, it never goes here https://github.com/qgis/QGIS/blob/458185a6704cb032f9c7dc31de1a6b89904066eb/src/core/qgspointlocator.cpp#L112 and thus the match is never valid.

### PR DESCRIPTION
**Pull request by troopa81**
Fixes #59530 and very likely #59308 and avoid also memory leaks

The issue were happening because a previously created locator were assigned to a new layer having the same address than a now deleted layer.

**Funded by GISPO**

### CODE REVIEW

File: src/core/qgssnappingutils.cpp [hunk 1]
```diff
@@ -43,6 +43,11 @@ QgsPointLocator *QgsSnappingUtils::locatorForLayer( QgsVectorLayer *vl )
   {
     QgsPointLocator *vlpl = new QgsPointLocator( vl, destinationCrs(), mMapSettings.transformContext(), nullptr );
     connect( vlpl, &QgsPointLocator::initFinished, this, &QgsSnappingUtils::onInitFinished );
+    connect( vl, &QObject::destroyed, this, [this, vl]()
+    {
+      mLocators.remove( vl );
```
Comment (uclaros) [inline src/core/qgssnappingutils.cpp:48]: Shouldn't you `delete mLocators[vl]` first or `vlpl` would leak?

**Review by nyalldawson — APPROVED** [review]

**Comment by tylerchism** [comment]
> Fixes #59530 and very likely #59308 and avoid also memory leaks
> 
> The issue were happening because a previously created locator were assigned to a new layer having the same address than a now deleted layer.
> 
> **Funded by GISPO**

Is there a way to refresh snapping locator for a layer through pyqgis? This would help give me a solution in my plugin until I can upgrade to get this change.

**Comment by troopa81** [comment]
> Is there a way to refresh snapping locator for a layer through pyqgis? This would help give me a solution in my plugin until I can upgrade to get this change.

Be ware that the fix has been backported and is available in 3.40.4.

As a workaround you could maybe delete and create a new QgsSnappingUtils for your canvas. But I'm afraid about the errors that you could get. You'd better upgrade to current LTR

**Comment by tylerchism** [comment]
> > Is there a way to refresh snapping locator for a layer through pyqgis? This would help give me a solution in my plugin until I can upgrade to get this change.
> 
> Be ware that the fix has been backported and is available in 3.40.4.
> 
> As a workaround you could maybe delete and create a new QgsSnappingUtils for your canvas. But I'm afraid about the errors that you could get. You'd better upgrade to current LTR

Thanks, just FYI I was seeing a similar issue when manually updating geometries on a layer like this:
`
            self.map_layer.startEditing()
            self.map_layer.dataProvider().changeGeometryValues(changed_geometry_dict)
            self.map_layer.commitChanges()
            self.map_layer.updateExtents()
            self.map_layer.triggerRepaint()
`
trying to edit the features after this would give me the same problem.
I assume its the same root issue, but could be wrong. Its actually fixed by doing this instead:
`
            self.map_layer.startEditing()
            for feature_id, geometry in changed_geometry_dict.items():
                self.map_layer.changeGeometry(feature_id, geometry)
            self.map_layer.commitChanges()
            self.map_layer.updateExtents()
            self.map_layer.triggerRepaint()
`

Let me know if I should make a new issue for this.

**Comment by troopa81** [comment]
I think this is not an issue. Your first piece code modify directly the data without going though the vector layer abstraction, and so no dataChanged signal is fired. As a consequence, snapping cache is not aware it has to be refreshed, and so it contains old value.

The second one is using vector layer abstraction, so it fires the signal and so it works
