### PR TITLE
[WIP] Fix customization #45116

### LINKED ISSUE #45116: Customization : toolbar and dock are not handle
### What is the bug or the crash?

Since QGIS 3.20, the customization configuration (QGISCUSTOMIZATION3.ini or indicated file in cli) doesn't work for toolbars and docks.

I tried to debug qgscustomization.cpp, it seems QGIS reads the file correctly and uses the QgisApp methods `removeToolBar` and `removeDockWidget` but without being effective (cf. [qgscustomization.cpp](https://github.com/qgis/QGIS/blob/master/src/app/qgscustomization.cpp#L825))

### Steps to reproduce the issue

create a new profile with empty configuration : 

```
qgis --profile new_profile
```

The main windows is full of toolbar etc

Launch QGIS again with the test.ini file inside test.zip : 

[test.zip](https://github.com/qgis/QGIS/files/7186586/test.zip)

```
qgis --profile new_profile --customizationfile test.ini
```

There is still toolbars even if they are disabled in the ini file

### Versions

</head><body>

Version de QGIS | 3.21.0-Master | Révision du code | f5bd9ccaee
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compilé avec GEOS | 3.8.0-CAPI-1.13.1 | Utilisé avec GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PostgreSQL client version | 12.8 (Ubuntu 12.8-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.3 LTS
  |   |   |  
Cette copie de QGIS dispose d'une sortie de débogage.
  |   |   |  
Active Python plugins | sagaproviderMetaSearchgrassproviderprocessingdb_manager

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SebastienPeillet**
## Description

FIX  #45116

Since QGIS 3.20, the customization configuration (QGISCUSTOMIZATION3.ini or indicated file in cli) doesn't work for toolbars and docks.

I tried to debug qgscustomization.cpp, it seems QGIS reads the file correctly and uses the QgisApp methods removeToolBar and removeDockWidget but without being effective (cf.  [qgscustomization.cpp](https://github.com/qgis/QGIS/blob/master/src/app/qgscustomization.cpp#L825) ). I'm not sure what is the cause as the code of qgscustomization.cpp did not change between 3.18 and 3.20, but removing the parent of removed toolbars/dockwidget does the job

### CODE REVIEW

File: src/app/qgscustomization.cpp [hunk 1]
```diff
@@ -823,6 +823,7 @@ void QgsCustomization::updateMainWindow( QMenu *toolBarMenu )
       if ( !visible )
       {
         mw->removeToolBar( tb );
+        tb->setParent( NULL );
```
Comment (nyalldawson) [inline src/app/qgscustomization.cpp:826]:
```suggestion
        tb->setParent( nullptr );
```

File: src/app/qgscustomization.cpp [hunk 2]
```diff
@@ -880,6 +881,9 @@ void QgsCustomization::updateMainWindow( QMenu *toolBarMenu )
       if ( !visible )
       {
         mw->removeDockWidget( dw );
+        dw->setParent( NULL );
```
Comment (nyalldawson) [inline src/app/qgscustomization.cpp:884]:
```suggestion
        dw->setParent( nullptr );
```

**Comment by nyalldawson** [comment]
> I'm not sure what is the cause as the code of qgscustomization.cpp did not change between 3.18 and 3.20, but removing the parent of removed toolbars/dockwidget does the job

It causes a memory leak as a result, as these objects will never get deleted. But IMO that's a minor issue, and there's MANY ways a user can completely mess up a QGIS install through this interface customisation tool!

**Review by nyalldawson — APPROVED** [review]
