### PR TITLE
Fix predefined scales with locale

### LINKED ISSUE #51735: Project predefined scales are trimmed at thousand separator after project restart/reopening properties
### What is the bug or the crash?

When the "_Show group (thousand) separator_" setting is active, project predefined scales are trimmed after reopening _project properties_ or reopening a project after restarting QGIS.

### Steps to reproduce the issue

Make sure the setting 'Show group (thousand) separator' is enabled in _General_ tab of QGIS settings.
1. (Re-)Start QGIS
2. Create a new empty project
3. Open the project properties
4. Enable project predefined scales
5. Add new scales, apply and/or hit _OK_  --> Predefined scales now selectable for canvas
7. Reopen the project properties --> The scales now show the thousand separator
8. Close the project properties again --> Predefined scales are now trimmed at the thousand separator

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.28.3-Firenze | QGIS code revision | c12bcb2f76c
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

https://user-images.githubusercontent.com/78353871/216823281-879006cb-18b0-4663-b91c-41898e05df05.mp4

### PR DESCRIPTION
**Pull request by elpaso**
Fix #51735

### CODE REVIEW

File: src/app/qgsprojectproperties.cpp [hunk 1]
```diff
@@ -2633,34 +2641,40 @@ void QgsProjectProperties::addScaleToScaleList( QListWidgetItem *newItem )
   QListWidgetItem *duplicateItem = lstScales->findItems( newItem->text(), Qt::MatchExactly ).value( 0 );
   delete duplicateItem;
 
-  int newDenominator = newItem->text().split( ':' ).value( 1 ).toInt();
+  int newDenominator = newItem->data( Qt::UserRole ).toInt();
```
Comment (troopa81) [inline src/app/qgsprojectproperties.cpp:2644]:
```suggestion
  const int newDenominator = newItem->data( Qt::UserRole ).toInt();
```

File: src/app/qgsprojectproperties.cpp [hunk 2]
```diff
@@ -2633,34 +2641,40 @@ void QgsProjectProperties::addScaleToScaleList( QListWidgetItem *newItem )
...
   int i;
   for ( i = 0; i < lstScales->count(); i++ )
   {
-    int denominator = lstScales->item( i )->text().split( ':' ).value( 1 ).toInt();
+    int denominator = lstScales->item( i )->data( Qt::UserRole ).toInt();
```
Comment (troopa81) [inline src/app/qgsprojectproperties.cpp:2648]:
```suggestion
    const int denominator = lstScales->item( i )->data( Qt::UserRole ).toInt();
```

File: src/app/qgsprojectproperties.cpp (hunk 1 above)
Comment (troopa81) [reply src/app/qgsprojectproperties.cpp:2644]: And why int when we treat them as double in the rest of the code?

Comment (elpaso) [reply src/app/qgsprojectproperties.cpp:2644]: I actually asked myself the same question and decided not to change the old implementation (`toInt()`) : it's a denominator so is should definitely be an int, but  `void QgsProjectViewSettings::setMapScales( const QVector<double> &scales )`.

I don't think it makes any sense to handle doubles in the GUI (i.e. when displaying the scales or when editing/entering them).

Comment (troopa81) [reply src/app/qgsprojectproperties.cpp]: Ok :+1:

File: src/app/qgsprojectproperties.cpp [hunk 3]
```diff
@@ -1277,14 +1277,11 @@ void QgsProjectProperties::apply()
   projectScales.reserve( lstScales->count() );
   for ( int i = 0; i < lstScales->count(); ++i )
   {
-    const QString scaleText = lstScales->item( i )->text();
-    const QStringList parts = scaleText.split( ':' );
-    if ( parts.size() == 2 )
+    bool ok;
+    const int scaleDenominator = lstScales->item( i )->data( Qt::UserRole ).toDouble( &ok );
```
[the remark this answers is not in the document]
Comment (troopa81) [reply src/app/qgsprojectproperties.cpp:1281]: I think you'd still  have to fix this one because you're narrowing double to int without explicit cast. clang-tidy should warn here.

**Review by troopa81 — APPROVED** [review]

File: src/app/qgsprojectproperties.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (elpaso) [reply src/app/qgsprojectproperties.cpp:1281]: I'll make it a double, it won't affect UX anyway.
