### PR TITLE
Fix vertical anchor on font symbols to the baseline

### LINKED ISSUE #59732: Allow using baseline for font marker placement
### What is the bug or the crash?

It should be possible to use the baseline of a font for symbol placement.

The following image shows the font [cadastra](https://www.cadastre-manual.admin.ch/de/plan-fur-das-grundbuch) which has set the baseline to the center of the symbol. The point should be centered over the intersection point of the lines.

image

This is currently possibly by setting an offset, but this becomes complex with zoom levels and units

image

The font would be much more usable if the baseline could be set as reference for placement.

### Steps to reproduce the issue

Download the font [cadastra](https://www.cadastre-manual.admin.ch/de/plan-fur-das-grundbuch)
Configure it as symbol marker as shown above

### Versions

3.40

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by signedav**
With Font Marker Symbols an offset ("off1" in the sketch) is appended to the coordinates to know where to start drawing the symbol (at "point"). This offset is half of the *scaled* defined size (what later defines the size from baseline to top of a sign without accents). On the other hand,  an offset ("off2") is appended to this point concerning the vertical anchor (top, bottom, center). This second offset ("off2") was not half of the scaled defined size, but the half of the distance between baseline and the FontMetric Ascent - and **these two measurements differed**! What leaded to the wrong placement (alpha and beta)...

With this fix, the two offsets are always calculated the same, which leads to a correct position of the FontMarkers on Bottom.

IMG_20250103_091221

Means before on bottom (example with Font DejaVu Sans and CadastraSymbol):

Screenshot from 2025-01-03 09-25-44

Screenshot from 2025-01-03 09-26-13

Now:

Screenshot from 2025-01-03 09-25-38

Screenshot from 2025-01-03 09-26-28

Fixes #59732

Since this fix should not affect positions of markers in existing projects, we had to append a new setting instead of replacing the old. With the implementation of calculating the positions with bounds (like mentioned in this issue https://github.com/qgis/QGIS/issues/59732) the existing anchor types should become legacy. This is prepared in the following implementation, having a verticalAnchorMode in the FontMarker. As well it's provided that when I configure a Font Marker with a Bottom on Baseline, then change the marker to an SVG Marker, the anchor is Bottom, and when I go back to Font Marker it's Bottom on Baseline again.

What about "Top on Baseline" (and Center)? 
With this fix as well the Top and the Center Anchors would differ on the `verticalAnchorMode:Baseline`. But since it's not really recognizable and - I think - rarely used, I did not add it to the settings. But the backend with the `verticalAnchorMode`, would be prepared to add them on request.

The implementation of the bounds might follow. I see what I can do...

### CODE REVIEW

**Comment by nyalldawson** [comment]
I'd like to review this but can't for the next couple of weeks. please do not merge before then!

**Comment by signedav** [comment]
@nyalldawson Cool. I hoped for your feedback, since you already brought up your thoughts in the issue.

Since it's definitely a bug (although a side case) it would be great to have it in the upcoming LTR. Hope this can still be possible.

**Comment by m-kuhn** [comment]
Test comments are outdated and no longer valid (now hidden)
It would be great if these could be backported to 3.40, @nyalldawson do you think you'll be able to review before 3.42?

**Comment by m-kuhn** [comment]
Ping @nyalldawson

**Comment by nyalldawson** [comment]
@m-kuhn it's on my list for the second half of next week

**Comment by m-kuhn** [comment]
Thanks!

**Comment by nyalldawson** [comment]
@signedav ok, I've had a look over this, and I'm -1 to this approach (introducing the new mode enum)

Instead I would rather see QgsMarkerSymbolLayer::VerticalAnchorPoint extended with a new option for "Baseline" (which is exposed in the GUI only for font marker symbol layers.

Later we can consider adding the Legacy modes to this enum and moving the top/center/bottom font marker modes to use the font character bounds instead.

**Comment by signedav** [comment]
Thanks for the feedback.
I followed this approach because we can keep the anchor (top,center,bottom) when changing the symbol type (e.g. from font marker to svg and back) and because it's (in my opinion) more clear in the code, when the char offset is calculated (because there it needs to consider the new mode and not the anchor).

**Comment by signedav** [comment]
Concerning the bounds integration #60080, I don't like having 4 types in `QgsMarkerSymbolLayer::VerticalAnchorPoint` that are only meaningful in one of the inheritances (FontMarker). Or do I misunderstand something (like that those types can be meaningful for other markers as well)?

**Comment by nyalldawson** [comment]
@signedav 
> Concerning the bounds integration https://github.com/qgis/QGIS/pull/60080, I don't like having 4 types in QgsMarkerSymbolLayer::VerticalAnchorPoint that are meaningful in only one of the inheritances (FontMarker). Or do I misunderstand something (like that those types can be meaningful for other markers as well)?

I agree it's not ideal, but practically I think it's still the best solution. For all non font-marker types we'd just equate Top/Middle/Bottom with LegacyTop/LegacyMiddle/LegacyBottom, and then ignore the Baseline alignment.

Otherwise we get a messy situation of the Baseline VerticalAnchorMode which is meaningless for top/middle alignment, and the API and logic complexity which comes from having to consider a completely different mode setting vs just the one vertical alignment setting.

**Comment by signedav** [comment]
Fair enough. Unclear for me is how it should be done with the bounds. 

> Later we can consider adding the Legacy modes to this enum and moving the top/center/bottom font marker modes to use the font character bounds instead.

I think when we introduce the bounds, the existing project should remain having the (future) legacy options. But when we add 3 more legacy options we need to change options according to the QGIS version etc. or am I wrong?
Having those "modes" here giving another dimension to the option could handle it easily.

**Comment by signedav** [comment]
@nyalldawson I changed it according to your inputs. Thanks for your feedback.

File: src/core/symbology/qgssymbollayer.h [hunk 1]
```diff
@@ -781,6 +781,7 @@ class CORE_EXPORT QgsMarkerSymbolLayer : public QgsSymbolLayer
       Top, //!< Align to top of symbol
       VCenter, //!< Align to vertical center of symbol
       Bottom, //!< Align to bottom of symbol
+      Baseline, //!< Align font markers bottom to baseline
```
Comment (nyalldawson) [inline src/core/symbology/qgssymbollayer.h:784]:
```suggestion
      Baseline, //!< Align to baseline of symbol, e.g. font baseline for font marker symbol layers. Treated as Bottom if no baseline is available for the symbol layer type. \since QGIS 3.42
```

File: src/core/symbology/qgsmarkersymbollayer.cpp [hunk 2]
```diff
@@ -3608,7 +3615,15 @@ QString QgsFontMarkerSymbolLayer::characterToRender( QgsSymbolRenderContext &con
...
-      charOffset = QPointF( charWidth / 2.0, -mFontMetrics->ascent() / 2.0 );
+      if ( mVerticalAnchorPoint == VerticalAnchorPoint::Baseline )
+      {
+        const double sizePixels = context.renderContext().convertToPainterUnits( mSize, mSizeUnit, mSizeMapUnitScale );
+        charOffset = QPointF( charWidth / 2.0, -sizePixels / 2.0 );
+      }
+      else
+      {
+        charOffset = QPointF( charWidth / 2.0, -mFontMetrics->ascent() / 2.0 );
+      }
```
Comment (nyalldawson) [inline src/core/symbology/qgsmarkersymbollayer.cpp:3626]: I think you may also need to update QgsFontMarkerSymbolLayer::bounds

**Comment by nyalldawson** [comment]
@signedav looking good! Just needs some tests now...

File: src/core/symbology/qgsmarkersymbollayer.cpp (hunk 2 above)
Comment (signedav) [reply src/core/symbology/qgsmarkersymbollayer.cpp:3626]: QgsFontMarkerSymbolLayer::bounds uses this function as well, no? Here https://github.com/qgis/QGIS/blob/5baaf69614c0a46c318902981b47efbed34d4923/src/core/symbology/qgsmarkersymbollayer.cpp#L3928

Comment (nyalldawson) [reply src/core/symbology/qgsmarkersymbollayer.cpp:3626]: Yes, but "chrOffset" isn't used anywhere in the bounds function

Comment (signedav) [reply src/core/symbology/qgsmarkersymbollayer.cpp:3626]: Yes. That's right, sorry. Anyway. I don't see where it should need this correction in this function. It's already using the scaledSize here (and not the mFontMetrics, which was wrong in the other functions). Or do I don't see the obvious?

The only thing we could do is making it behave consequently wrong with the bottom setting. But this would break backwards compatibility with the projects, and that is the only reason we're keeping the original way (with bottom) and not replacing it with this bug fix at all until it can be replaced by the bounds-implementation you suggested.

Comment (nyalldawson) [reply src/core/symbology/qgsmarkersymbollayer.cpp:3626]: Can you adapt the  TestQgsFontMarkerSymbol::bounds() test to check other vertical alignments?

Comment (signedav) [reply src/core/symbology/qgsmarkersymbollayer.cpp:3626]: Okay, I did that. When we compare an object in the result image it looks like this.

bounds-compare

Honestly, I'm a little bit confused and I don't know if I understand everything right. I expected the bounds to be the same on baseline and bottom. Since the offset of the anchor is calculated in `calculateOffsetAndRotation` (as always) and the positioning - that is fixed in the other functions on baseline with this implementation - is here in the bounds always `-scaledSize / 2.0` (no matter if baseline or not).

Comment (signedav) [reply src/core/symbology/qgsmarkersymbollayer.cpp:3626]: @nyalldawson Is this okay now? The bounds are the same like before, since it's calculated already the *new* way.

**Comment by signedav** [comment]
I suggest to merge that next week if no objections. And don't put it into today's release.

File: src/core/symbology/qgsmarkersymbollayer.cpp (hunk 2 above)
Comment (nyalldawson) [reply src/core/symbology/qgsmarkersymbollayer.cpp:3626]: > on the other hand, the bounds are in fact the same. Just the symbol position differs, what is expected.

I'm not 100% confident it's the best we can get (ideally bounds returns the tightest possible rect containing the symbol, or labels will be visually far from their corresponding symbols), but we can always tweak that later if/when needed.

File: src/core/symbology/qgssymbollayer.h [hunk 3]
```diff
@@ -781,6 +781,7 @@ class CORE_EXPORT QgsMarkerSymbolLayer : public QgsSymbolLayer
       Top, //!< Align to top of symbol
       VCenter, //!< Align to vertical center of symbol
       Bottom, //!< Align to bottom of symbol
+      Baseline, //!< Align to baseline of symbol, e.g. font baseline for font marker symbol layers. Treated as Bottom if no baseline is available for the symbol layer type. \since QGIS 3.42
```
Comment (nyalldawson) [inline src/core/symbology/qgssymbollayer.h:784]:
```suggestion
      Baseline, //!< Align to baseline of symbol, e.g. font baseline for font marker symbol layers. Treated as Bottom if no baseline is available for the symbol layer type. \since QGIS 3.44
```

**Review by nyalldawson — APPROVED** [review]

File: src/core/symbology/qgsmarkersymbollayer.cpp (hunk 2 above)
Comment (signedav) [reply src/core/symbology/qgsmarkersymbollayer.cpp:3626]: Maybe it would be better to have the “real” bounds, yes, but still, this is a fix of a wrong previous behavior, just introduced with a new setting to keep the old (wrong) behavior for backwards compatibility. So I think it's better not to introduce a new behavior here either. But with this PR here #60080 I have started to implement the anchors for the bounds, which would replace the old anchors, except this baseline anchor (but I closed it again, because I continue work on it currently).

**Comment by signedav** [comment]
Thanks a lot @nyalldawson  See my reply on your last comment above.

But I forgot to put the backport label here, so I did a manual backport PR #60837. In my opinion, it's definitely worth a backport as it's an unrisky fix and not really a new feature. However, I think it's not relevant enough for the LTR, so 3.42 is sufficient. Hope you agree.
