### PR TITLE
Data Source Manger: connect the Help button to the docs for some providers (Fix #54125)

### LINKED ISSUE #54125: Data Source Manger: the Help button, although active, doesn't actually work for some providers
### What is the bug or the crash?

In the Data Source Manager dialog windows, the Help button is always active but, if clicked on, it actually makes a web page of the documentation to open only for some items and not for other ones:

Vector -> managing_data_source/opening_data.html#loading-a-layer-from-a-file
**Raster -> none**
**Mesh -> none**
**Point Cloud -> none**
Delimited Text -> managing_data_source/opening_data.html#importing-a-delimited-text-file
GeoPackage -> managing_data_source/opening_data.html#GeoPackage-layers
**GPS -> none**
Spatialite -> managing_data_source/opening_data.html#spatialite-layers
PostgreSQL, MS SQL Server, SAP HANA -> managing_data_source/opening_data.html#loading-a-database-layer
Virtual Layer -> managing_data_source/create_layers.html#creating-virtual-layers
WMS/WMTS, WFS / OGC API - Features, WCS -> working_with_ogc/ogc_client_support.html
XYZ -> managing_data_source/opening_data.html#using-xyz-tile-services
Vector Tile -> managing_data_source/opening_data.html#using-vector-tiles-services
**Scene -> none** (only 3.33)
ArcGIS REST Server -> managing_data_source/index.html
**GeoNode -> none** (only 3.28)
**Metadata Search -> none**

### Steps to reproduce the issue

1. Go to Data Source Manager
2. select one of Raster, Mesh, Point Cloud, GPS, Geonode, Scene, Metadata Search and click on the Help button.

### Versions

QGIS 3.28 - QGIS 3.33 master on Windows

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by agiudiceandrea**
## Description

This PR connects the Help button of some items of the Data Source Manger dialog window to the docs:

Raster -> [managing_data_source/opening_data.html#loading-a-layer-from-a-file](https://docs.qgis.org/testing/en/docs/user_manual/managing_data_source/opening_data.html#loading-a-layer-from-a-file)
Mesh -> [managing_data_source/opening_data.html#loading-a-mesh-layer](https://docs.qgis.org/testing/en/docs/user_manual/managing_data_source/opening_data.html#loading-a-mesh-layer)
GPS -> [managing_data_source/opening_data.html#gps](https://docs.qgis.org/testing/en/docs/user_manual/managing_data_source/opening_data.html#gps)
Metadata Search -> [managing_data_source/opening_data.html#the-layer-metadata-search-panel](https://docs.qgis.org/testing/en/docs/user_manual/managing_data_source/opening_data.html#the-layer-metadata-search-panel)
Point Cloud -> [managing_data_source/opening_data.html#loading-a-layer-from-a-file](https://docs.qgis.org/testing/en/docs/user_manual/managing_data_source/opening_data.html#loading-a-layer-from-a-file)
Scene -> [managing_data_source/opening_data.html](https://docs.qgis.org/testing/en/docs/user_manual/managing_data_source/opening_data.html)

A specific paragraph for the Point Cloud provider is currently missing, anyway the paragraph at managing_data_source/opening_data.html#loading-a-layer-from-a-file should be OK since the Point Cloud dialog is very similar to the Raster one.

A specific paragraph for the Scene provider is currently missing: I've linked the Help button the generic Data Source Manager doc page managing_data_source/opening_data.html.

Fixes https://github.com/qgis/QGIS/issues/54125.

@DelazJ, could you please have a look at this?

Would it be better to not add the link for the Point Cloud and / or the Scene providers?

This would need a manual backport to release-3_32 branch (missing Scene in 3.32) and to release-3_28 (missing Scene, GeoNode present).

### CODE REVIEW

File: src/gui/providers/gdal/qgsgdalsourceselect.h [hunk 1]
```diff
@@ -21,6 +21,7 @@
 #include "qgsabstractdatasourcewidget.h"
 #include "qgis_gui.h"
 #include "qgis_sip.h"
+#include "qgshelp.h"
```
Comment (nyalldawson) [inline src/gui/providers/gdal/qgsgdalsourceselect.h:24]: These should all be moved to the .cpp files -- minimising the number of includes in the headers greatly speeds up compilation times.

**Review by nyalldawson — APPROVED** [review]
