### PR TITLE
Accept fields of type "name" in PG 12

### LINKED ISSUE #37313: Postgres provider does not load fields of type "name" (in PG 12)
**Describe the bug**
I executed (il latest master 359498091e) the following query  to discover table name in a postgres DB

SELECT * FROM information_schema.tables

the result is:
Screenshot from 2020-06-19 11-29-22

but should be:
Screenshot from 2020-06-19 11-32-02

The DB is a local db in a docker container, but shouldn't be the problem. I tested also in an empty profile with a clean build.

**How to Reproduce**

To replicate, run query on any Postgres DB instance.

1. Go to DB Manager
2. Select a Postgres DB
3. Open query editor
4. run query: SELECT * FROM information_schema.tables => table is incorrect as image above

**QGIS and OS versions**

QGIS version | 3.13.0-Master | QGIS code revision | 359498091e
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 12.3 (Ubuntu 12.3-1.pgdg18.04+1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.4 LTS | This copy of QGIS writes debugging output.
Active python plugins | plugin_reloader; qgis_resource_sharing; IPyConsole; remotedebug; Qgis2threejs; db_manager; processing; MetaSearch

**Additional context**

This is the log:

../src/providers/postgres/qgspostgresconn.cpp:223 : (QgsPostgresConn) [417277ms] [thread:0x5588d28e4230] New PostgreSQL connection for dbname='gis' host=localhost port=25432 user='docker' password='docker' sslmode=disable
../src/core/qgsdatasourceuri.cpp:162 : (QgsDataSourceUri) [3ms] [thread:0x5588d28e4230] connection timeout ignored
../src/providers/postgres/qgspostgresconn.cpp:325 : (QgsPostgresConn) [0ms] [thread:0x5588d28e4230] setting client encoding to UNICODE
../src/providers/postgres/qgspostgresconn.cpp:329 : (QgsPostgresConn) [0ms] [thread:0x5588d28e4230] encoding successfully set
../src/providers/postgres/qgspostgresconn.cpp:340 : (QgsPostgresConn) [0ms] [thread:0x5588d28e4230] Connection to the database was successful
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: select regclass('pg_class')::oid
../src/providers/postgres/qgspostgresconn.cpp:1690 : (deduceEndian) [0ms] [thread:0x5588d28e4230] Creating binary cursor
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: BEGIN
../src/providers/postgres/qgspostgresconn.cpp:1351 : (openCursor) [0ms] [thread:0x5588d28e4230] Binary cursor oidcursor for select regclass('pg_class')::oid
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: DECLARE oidcursor BINARY CURSOR FOR select regclass('pg_class')::oid
../src/providers/postgres/qgspostgresconn.cpp:1695 : (deduceEndian) [0ms] [thread:0x5588d28e4230] Fetching a record and attempting to get check endian-ness
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: fetch forward 1 from oidcursor
../src/providers/postgres/qgspostgresconn.cpp:1705 : (deduceEndian) [0ms] [thread:0x5588d28e4230] Got oid of 1259 from the binary cursor
../src/providers/postgres/qgspostgresconn.cpp:1706 : (deduceEndian) [0ms] [thread:0x5588d28e4230] First oid is 1259
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: CLOSE oidcursor
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: COMMIT
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT postgis_version()
../src/providers/postgres/qgspostgresconn.cpp:1026 : (postgisVersion) [31ms] [thread:0x5588d28e4230] PostGIS version info: 3.0 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT postgis_geos_version(), postgis_proj_version()
../src/providers/postgres/qgspostgresconn.cpp:1051 : (postgisVersion) [0ms] [thread:0x5588d28e4230] geos:3.7.1-CAPI-1.11.1 27a5e771 proj:Rel. 5.2.0, September 15th, 2018
../src/providers/postgres/qgspostgresconn.cpp:1067 : (postgisVersion) [0ms] [thread:0x5588d28e4230] Checking for topology support
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT has_schema_privilege(n.oid, 'usage')   AND has_table_privilege(t.oid, 'select')   AND has_table_privilege(l.oid, 'select')  FROM pg_namespace n, pg_class t, pg_class l WHERE n.nspname = 'topology'   AND t.relnamespace = n.oid   AND l.relnamespace = n.oid   AND t.relname = 'topology'   AND l.relname = 'layer'
../src/providers/postgres/qgspostgresconn.cpp:1092 : (postgisVersion) [1ms] [thread:0x5588d28e4230] Topology support available :)
../src/providers/postgres/qgspostgresconn.cpp:1103 : (postgisVersion) [0ms] [thread:0x5588d28e4230] Checking for pointcloud support
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: 
SELECT
 has_table_privilege(c.oid, 'select')
 AND has_table_privilege(f.oid, 'select')
FROM pg_class c, pg_class f, pg_namespace n, pg_extension e
WHERE c.relnamespace = n.oid
  AND c.relname = 'pointcloud_columns'
  AND f.relnamespace = n.oid
  AND f.relname = 'pointcloud_formats'
  AND n.oid = e.extnamespace
  AND e.extname = 'pointcloud'
    
../src/providers/postgres/qgspostgresconn.cpp:1123 : (postgisVersion) [1ms] [thread:0x5588d28e4230] Checking for raster support
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: 
SELECT
 has_table_privilege(c.oid, 'select')
FROM pg_class c, pg_namespace n, pg_type t
WHERE c.relnamespace = n.oid
  AND n.oid = t.typnamespace
  AND c.relname = 'raster_columns'
  AND t.typname = 'raster'
    
../src/providers/postgres/qgspostgresconn.cpp:1138 : (postgisVersion) [0ms] [thread:0x5588d28e4230] Raster support available!
../src/providers/postgres/qgspostgresconn.cpp:349 : (QgsPostgresConn) [0ms] [thread:0x5588d28e4230] Checking for GEOS support
../src/providers/postgres/qgspostgresconn.cpp:357 : (QgsPostgresConn) [0ms] [thread:0x5588d28e4230] GEOS support available!
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SET application_name='QGIS'
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT * FROM information_schema.tables
../src/providers/postgres/qgspostgresconn.cpp:223 : (QgsPostgresConn) [25ms] [thread:0x5588d28e4230] New PostgreSQL connection for dbname='gis' host=localhost port=25432 user='docker' password='docker' sslmode=disable
../src/core/qgsdatasourceuri.cpp:162 : (QgsDataSourceUri) [3ms] [thread:0x5588d28e4230] connection timeout ignored
../src/providers/postgres/qgspostgresconn.cpp:325 : (QgsPostgresConn) [0ms] [thread:0x5588d28e4230] setting client encoding to UNICODE
../src/providers/postgres/qgspostgresconn.cpp:329 : (QgsPostgresConn) [0ms] [thread:0x5588d28e4230] encoding successfully set
../src/providers/postgres/qgspostgresconn.cpp:340 : (QgsPostgresConn) [0ms] [thread:0x5588d28e4230] Connection to the database was successful
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: select regclass('pg_class')::oid
../src/providers/postgres/qgspostgresconn.cpp:1690 : (deduceEndian) [0ms] [thread:0x5588d28e4230] Creating binary cursor
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: BEGIN
../src/providers/postgres/qgspostgresconn.cpp:1351 : (openCursor) [0ms] [thread:0x5588d28e4230] Binary cursor oidcursor for select regclass('pg_class')::oid
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: DECLARE oidcursor BINARY CURSOR FOR select regclass('pg_class')::oid
../src/providers/postgres/qgspostgresconn.cpp:1695 : (deduceEndian) [0ms] [thread:0x5588d28e4230] Fetching a record and attempting to get check endian-ness
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: fetch forward 1 from oidcursor
../src/providers/postgres/qgspostgresconn.cpp:1705 : (deduceEndian) [0ms] [thread:0x5588d28e4230] Got oid of 1259 from the binary cursor
../src/providers/postgres/qgspostgresconn.cpp:1706 : (deduceEndian) [0ms] [thread:0x5588d28e4230] First oid is 1259
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: CLOSE oidcursor
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: COMMIT
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT postgis_version()
../src/providers/postgres/qgspostgresconn.cpp:1026 : (postgisVersion) [25ms] [thread:0x5588d28e4230] PostGIS version info: 3.0 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT postgis_geos_version(), postgis_proj_version()
../src/providers/postgres/qgspostgresconn.cpp:1051 : (postgisVersion) [0ms] [thread:0x5588d28e4230] geos:3.7.1-CAPI-1.11.1 27a5e771 proj:Rel. 5.2.0, September 15th, 2018
../src/providers/postgres/qgspostgresconn.cpp:1067 : (postgisVersion) [0ms] [thread:0x5588d28e4230] Checking for topology support
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT has_schema_privilege(n.oid, 'usage')   AND has_table_privilege(t.oid, 'select')   AND has_table_privilege(l.oid, 'select')  FROM pg_namespace n, pg_class t, pg_class l WHERE n.nspname = 'topology'   AND t.relnamespace = n.oid   AND l.relnamespace = n.oid   AND t.relname = 'topology'   AND l.relname = 'layer'
../src/providers/postgres/qgspostgresconn.cpp:1092 : (postgisVersion) [1ms] [thread:0x5588d28e4230] Topology support available :)
../src/providers/postgres/qgspostgresconn.cpp:1103 : (postgisVersion) [0ms] [thread:0x5588d28e4230] Checking for pointcloud support
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: 
SELECT
 has_table_privilege(c.oid, 'select')
 AND has_table_privilege(f.oid, 'select')
FROM pg_class c, pg_class f, pg_namespace n, pg_extension e
WHERE c.relnamespace = n.oid
  AND c.relname = 'pointcloud_columns'
  AND f.relnamespace = n.oid
  AND f.relname = 'pointcloud_formats'
  AND n.oid = e.extnamespace
  AND e.extname = 'pointcloud'
    
../src/providers/postgres/qgspostgresconn.cpp:1123 : (postgisVersion) [1ms] [thread:0x5588d28e4230] Checking for raster support
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: 
SELECT
 has_table_privilege(c.oid, 'select')
FROM pg_class c, pg_namespace n, pg_type t
WHERE c.relnamespace = n.oid
  AND n.oid = t.typnamespace
  AND c.relname = 'raster_columns'
  AND t.typname = 'raster'
    
../src/providers/postgres/qgspostgresconn.cpp:1138 : (postgisVersion) [0ms] [thread:0x5588d28e4230] Raster support available!
../src/providers/postgres/qgspostgresconn.cpp:349 : (QgsPostgresConn) [0ms] [thread:0x5588d28e4230] Checking for GEOS support
../src/providers/postgres/qgspostgresconn.cpp:357 : (QgsPostgresConn) [0ms] [thread:0x5588d28e4230] GEOS support available!
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SET application_name='QGIS'
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT typname FROM pg_type WHERE oid = 19
../src/providers/postgres/qgspostgresproviderconnection.cpp:274 : (executeSqlPrivate) [0ms] [thread:0x5588d28e4230] Unhandled PostgreSQL type name
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT typname FROM pg_type WHERE oid = 19
../src/providers/postgres/qgspostgresproviderconnection.cpp:274 : (executeSqlPrivate) [0ms] [thread:0x5588d28e4230] Unhandled PostgreSQL type name
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT typname FROM pg_type WHERE oid = 19
../src/providers/postgres/qgspostgresproviderconnection.cpp:274 : (executeSqlPrivate) [0ms] [thread:0x5588d28e4230] Unhandled PostgreSQL type name
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT typname FROM pg_type WHERE oid = 1043
../src/providers/postgres/qgspostgresproviderconnection.cpp:274 : (executeSqlPrivate) [0ms] [thread:0x5588d28e4230] Unhandled PostgreSQL type varchar
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT typname FROM pg_type WHERE oid = 19
../src/providers/postgres/qgspostgresproviderconnection.cpp:274 : (executeSqlPrivate) [0ms] [thread:0x5588d28e4230] Unhandled PostgreSQL type name
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT typname FROM pg_type WHERE oid = 1043
../src/providers/postgres/qgspostgresproviderconnection.cpp:274 : (executeSqlPrivate) [0ms] [thread:0x5588d28e4230] Unhandled PostgreSQL type varchar
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT typname FROM pg_type WHERE oid = 19
../src/providers/postgres/qgspostgresproviderconnection.cpp:274 : (executeSqlPrivate) [0ms] [thread:0x5588d28e4230] Unhandled PostgreSQL type name
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT typname FROM pg_type WHERE oid = 19
../src/providers/postgres/qgspostgresproviderconnection.cpp:274 : (executeSqlPrivate) [0ms] [thread:0x5588d28e4230] Unhandled PostgreSQL type name
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT typname FROM pg_type WHERE oid = 19
../src/providers/postgres/qgspostgresproviderconnection.cpp:274 : (executeSqlPrivate) [0ms] [thread:0x5588d28e4230] Unhandled PostgreSQL type name
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT typname FROM pg_type WHERE oid = 1043
../src/providers/postgres/qgspostgresproviderconnection.cpp:274 : (executeSqlPrivate) [0ms] [thread:0x5588d28e4230] Unhandled PostgreSQL type varchar
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT typname FROM pg_type WHERE oid = 1043
../src/providers/postgres/qgspostgresproviderconnection.cpp:274 : (executeSqlPrivate) [0ms] [thread:0x5588d28e4230] Unhandled PostgreSQL type varchar
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT typname FROM pg_type WHERE oid = 1043
../src/providers/postgres/qgspostgresproviderconnection.cpp:274 : (executeSqlPrivate) [0ms] [thread:0x5588d28e4230] Unhandled PostgreSQL type varchar
../src/providers/postgres/qgspostgresprovider.cpp:107 : (QgsPostgresProvider) [22ms] [thread:0x5588d28e4230] URI: dbname='gis' host=localhost port=25432 user='docker' password='docker' sslmode=disable key='__rid__' checkPrimaryKeyUnicity='1' table="(SELECT row_number() OVER () AS __rid__, * FROM (SELECT * FROM information_schema.tables) as foo)" 
../src/providers/postgres/qgspostgresprovider.cpp:161 : (QgsPostgresProvider) [0ms] [thread:0x5588d28e4230] Connection info is dbname='gis' host=localhost port=25432 user='docker' password='docker' sslmode=disable
../src/providers/postgres/qgspostgresprovider.cpp:162 : (QgsPostgresProvider) [0ms] [thread:0x5588d28e4230] Geometry column is: 
../src/providers/postgres/qgspostgresprovider.cpp:163 : (QgsPostgresProvider) [0ms] [thread:0x5588d28e4230] Schema is: 
../src/providers/postgres/qgspostgresprovider.cpp:164 : (QgsPostgresProvider) [0ms] [thread:0x5588d28e4230] Table name is: 
../src/providers/postgres/qgspostgresprovider.cpp:165 : (QgsPostgresProvider) [0ms] [thread:0x5588d28e4230] Query is: (SELECT row_number() OVER () AS __rid__, * FROM (SELECT * FROM information_schema.tables) as foo)
../src/providers/postgres/qgspostgresprovider.cpp:166 : (QgsPostgresProvider) [0ms] [thread:0x5588d28e4230] Where clause is: 
../src/providers/postgres/qgspostgresconn.cpp:223 : (QgsPostgresConn) [0ms] [thread:0x5588d28e4230] New PostgreSQL connection for dbname='gis' host=localhost port=25432 user='docker' password='docker' sslmode=disable
../src/core/qgsdatasourceuri.cpp:162 : (QgsDataSourceUri) [4ms] [thread:0x5588d28e4230] connection timeout ignored
../src/providers/postgres/qgspostgresconn.cpp:325 : (QgsPostgresConn) [0ms] [thread:0x5588d28e4230] setting client encoding to UNICODE
../src/providers/postgres/qgspostgresconn.cpp:329 : (QgsPostgresConn) [0ms] [thread:0x5588d28e4230] encoding successfully set
../src/providers/postgres/qgspostgresconn.cpp:340 : (QgsPostgresConn) [0ms] [thread:0x5588d28e4230] Connection to the database was successful
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: select regclass('pg_class')::oid
../src/providers/postgres/qgspostgresconn.cpp:1690 : (deduceEndian) [0ms] [thread:0x5588d28e4230] Creating binary cursor
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: BEGIN
../src/providers/postgres/qgspostgresconn.cpp:1351 : (openCursor) [0ms] [thread:0x5588d28e4230] Binary cursor oidcursor for select regclass('pg_class')::oid
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: DECLARE oidcursor BINARY CURSOR FOR select regclass('pg_class')::oid
../src/providers/postgres/qgspostgresconn.cpp:1695 : (deduceEndian) [0ms] [thread:0x5588d28e4230] Fetching a record and attempting to get check endian-ness
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: fetch forward 1 from oidcursor
../src/providers/postgres/qgspostgresconn.cpp:1705 : (deduceEndian) [0ms] [thread:0x5588d28e4230] Got oid of 1259 from the binary cursor
../src/providers/postgres/qgspostgresconn.cpp:1706 : (deduceEndian) [0ms] [thread:0x5588d28e4230] First oid is 1259
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: CLOSE oidcursor
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: COMMIT
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT postgis_version()
../src/providers/postgres/qgspostgresconn.cpp:1026 : (postgisVersion) [31ms] [thread:0x5588d28e4230] PostGIS version info: 3.0 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT postgis_geos_version(), postgis_proj_version()
../src/providers/postgres/qgspostgresconn.cpp:1051 : (postgisVersion) [0ms] [thread:0x5588d28e4230] geos:3.7.1-CAPI-1.11.1 27a5e771 proj:Rel. 5.2.0, September 15th, 2018
../src/providers/postgres/qgspostgresconn.cpp:1067 : (postgisVersion) [0ms] [thread:0x5588d28e4230] Checking for topology support
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT has_schema_privilege(n.oid, 'usage')   AND has_table_privilege(t.oid, 'select')   AND has_table_privilege(l.oid, 'select')  FROM pg_namespace n, pg_class t, pg_class l WHERE n.nspname = 'topology'   AND t.relnamespace = n.oid   AND l.relnamespace = n.oid   AND t.relname = 'topology'   AND l.relname = 'layer'
../src/providers/postgres/qgspostgresconn.cpp:1092 : (postgisVersion) [1ms] [thread:0x5588d28e4230] Topology support available :)
../src/providers/postgres/qgspostgresconn.cpp:1103 : (postgisVersion) [0ms] [thread:0x5588d28e4230] Checking for pointcloud support
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: 
SELECT
 has_table_privilege(c.oid, 'select')
 AND has_table_privilege(f.oid, 'select')
FROM pg_class c, pg_class f, pg_namespace n, pg_extension e
WHERE c.relnamespace = n.oid
  AND c.relname = 'pointcloud_columns'
  AND f.relnamespace = n.oid
  AND f.relname = 'pointcloud_formats'
  AND n.oid = e.extnamespace
  AND e.extname = 'pointcloud'
    
../src/providers/postgres/qgspostgresconn.cpp:1123 : (postgisVersion) [0ms] [thread:0x5588d28e4230] Checking for raster support
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: 
SELECT
 has_table_privilege(c.oid, 'select')
FROM pg_class c, pg_namespace n, pg_type t
WHERE c.relnamespace = n.oid
  AND n.oid = t.typnamespace
  AND c.relname = 'raster_columns'
  AND t.typname = 'raster'
    
../src/providers/postgres/qgspostgresconn.cpp:1138 : (postgisVersion) [0ms] [thread:0x5588d28e4230] Raster support available!
../src/providers/postgres/qgspostgresconn.cpp:349 : (QgsPostgresConn) [0ms] [thread:0x5588d28e4230] Checking for GEOS support
../src/providers/postgres/qgspostgresconn.cpp:357 : (QgsPostgresConn) [0ms] [thread:0x5588d28e4230] GEOS support available!
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SET application_name='QGIS'
../src/providers/postgres/qgspostgresprovider.cpp:1287 : (hasSufficientPermsAndCapabilities) [0ms] [thread:0x5588d28e4230] Checking for permissions on the relation
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT * FROM (SELECT row_number() OVER () AS __rid__, * FROM (SELECT * FROM information_schema.tables) as foo) AS "subQuery_0" LIMIT 1
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [2ms] [thread:0x5588d28e4230] Executing SQL: SELECT * FROM (SELECT row_number() OVER () AS __rid__, * FROM (SELECT * FROM information_schema.tables) as foo) AS "subQuery_0" LIMIT 0
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [1ms] [thread:0x5588d28e4230] Executing SQL: SELECT oid,typname,typtype,typelem,typlen FROM pg_type
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [2ms] [thread:0x5588d28e4230] Executing SQL: SELECT attrelid, attnum, pg_catalog.format_type(atttypid,atttypmod), pg_catalog.col_description(attrelid,attnum), pg_catalog.pg_get_expr(adbin,adrelid), atttypid, attnotnull::int, indisunique::int, attidentity, attgenerated FROM pg_attribute LEFT OUTER JOIN pg_attrdef ON attrelid=adrelid AND attnum=adnum LEFT OUTER JOIN ( SELECT DISTINCT indrelid, indkey, indisunique FROM pg_index WHERE indisunique ) uniq ON attrelid=indrelid AND attnum::text=indkey::text  WHERE attrelid IN (14260)
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [2ms] [thread:0x5588d28e4230] Executing SQL: SELECT format_type(19, -1)
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] [thread:0x5588d28e4230] 2020-06-19T11:33:43 PostGIS[1] Field table_catalog ignored, because of unsupported type b
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT format_type(19, -1)
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] [thread:0x5588d28e4230] 2020-06-19T11:33:43 PostGIS[1] Field table_schema ignored, because of unsupported type b
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT format_type(19, -1)
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] [thread:0x5588d28e4230] 2020-06-19T11:33:43 PostGIS[1] Field table_name ignored, because of unsupported type b
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT format_type(1043, -1)
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT format_type(19, -1)
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] [thread:0x5588d28e4230] 2020-06-19T11:33:43 PostGIS[1] Field self_referencing_column_name ignored, because of unsupported type b
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT format_type(1043, -1)
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT format_type(19, -1)
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] [thread:0x5588d28e4230] 2020-06-19T11:33:43 PostGIS[1] Field user_defined_type_catalog ignored, because of unsupported type b
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT format_type(19, -1)
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] [thread:0x5588d28e4230] 2020-06-19T11:33:43 PostGIS[1] Field user_defined_type_schema ignored, because of unsupported type b
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT format_type(19, -1)
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] [thread:0x5588d28e4230] 2020-06-19T11:33:43 PostGIS[1] Field user_defined_type_name ignored, because of unsupported type b
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT format_type(1043, 7)
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT format_type(1043, 7)
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT format_type(1043, -1)
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT EXISTS ( SELECT oid FROM pg_catalog.pg_class WHERE relname='qgis_editor_widget_styles')
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT count(distinct ("__rid__"))=count(("__rid__")) FROM (SELECT row_number() OVER () AS __rid__, * FROM (SELECT * FROM information_schema.tables) as foo) AS "subQuery_0"
../src/core/qgsvectorlayer.cpp:1728 : (setDataProvider) [2ms] [thread:0x5588d28e4230] Instantiated the data provider plugin
../src/core/qgsvectorlayer.cpp:1756 : (setDataProvider) [0ms] [thread:0x5588d28e4230] Beautifying layer name dbmanager_cursor
../src/core/qgsvectorlayer.cpp:1779 : (setDataProvider) [0ms] [thread:0x5588d28e4230] Beautified layer name dbmanager_cursor
../src/providers/postgres/qgspostgresconn.cpp:223 : (QgsPostgresConn) [0ms] [thread:0x5588d28e4230] New PostgreSQL connection for dbname='gis' host=localhost port=25432 user='docker' password='docker' sslmode=disable
../src/core/qgsdatasourceuri.cpp:162 : (QgsDataSourceUri) [4ms] [thread:0x5588d28e4230] connection timeout ignored
../src/providers/postgres/qgspostgresconn.cpp:325 : (QgsPostgresConn) [0ms] [thread:0x5588d28e4230] setting client encoding to UNICODE
../src/providers/postgres/qgspostgresconn.cpp:329 : (QgsPostgresConn) [0ms] [thread:0x5588d28e4230] encoding successfully set
../src/providers/postgres/qgspostgresconn.cpp:340 : (QgsPostgresConn) [0ms] [thread:0x5588d28e4230] Connection to the database was successful
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: select regclass('pg_class')::oid
../src/providers/postgres/qgspostgresconn.cpp:1690 : (deduceEndian) [0ms] [thread:0x5588d28e4230] Creating binary cursor
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: BEGIN
../src/providers/postgres/qgspostgresconn.cpp:1351 : (openCursor) [0ms] [thread:0x5588d28e4230] Binary cursor oidcursor for select regclass('pg_class')::oid
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: DECLARE oidcursor BINARY CURSOR FOR select regclass('pg_class')::oid
../src/providers/postgres/qgspostgresconn.cpp:1695 : (deduceEndian) [0ms] [thread:0x5588d28e4230] Fetching a record and attempting to get check endian-ness
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: fetch forward 1 from oidcursor
../src/providers/postgres/qgspostgresconn.cpp:1705 : (deduceEndian) [0ms] [thread:0x5588d28e4230] Got oid of 1259 from the binary cursor
../src/providers/postgres/qgspostgresconn.cpp:1706 : (deduceEndian) [0ms] [thread:0x5588d28e4230] First oid is 1259
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: CLOSE oidcursor
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: COMMIT
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT postgis_version()
../src/providers/postgres/qgspostgresconn.cpp:1026 : (postgisVersion) [30ms] [thread:0x5588d28e4230] PostGIS version info: 3.0 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT postgis_geos_version(), postgis_proj_version()
../src/providers/postgres/qgspostgresconn.cpp:1051 : (postgisVersion) [0ms] [thread:0x5588d28e4230] geos:3.7.1-CAPI-1.11.1 27a5e771 proj:Rel. 5.2.0, September 15th, 2018
../src/providers/postgres/qgspostgresconn.cpp:1067 : (postgisVersion) [0ms] [thread:0x5588d28e4230] Checking for topology support
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT has_schema_privilege(n.oid, 'usage')   AND has_table_privilege(t.oid, 'select')   AND has_table_privilege(l.oid, 'select')  FROM pg_namespace n, pg_class t, pg_class l WHERE n.nspname = 'topology'   AND t.relnamespace = n.oid   AND l.relnamespace = n.oid   AND t.relname = 'topology'   AND l.relname = 'layer'
../src/providers/postgres/qgspostgresconn.cpp:1092 : (postgisVersion) [1ms] [thread:0x5588d28e4230] Topology support available :)
../src/providers/postgres/qgspostgresconn.cpp:1103 : (postgisVersion) [0ms] [thread:0x5588d28e4230] Checking for pointcloud support
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: 
SELECT
 has_table_privilege(c.oid, 'select')
 AND has_table_privilege(f.oid, 'select')
FROM pg_class c, pg_class f, pg_namespace n, pg_extension e
WHERE c.relnamespace = n.oid
  AND c.relname = 'pointcloud_columns'
  AND f.relnamespace = n.oid
  AND f.relname = 'pointcloud_formats'
  AND n.oid = e.extnamespace
  AND e.extname = 'pointcloud'
    
../src/providers/postgres/qgspostgresconn.cpp:1123 : (postgisVersion) [0ms] [thread:0x5588d28e4230] Checking for raster support
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: 
SELECT
 has_table_privilege(c.oid, 'select')
FROM pg_class c, pg_namespace n, pg_type t
WHERE c.relnamespace = n.oid
  AND n.oid = t.typnamespace
  AND c.relname = 'raster_columns'
  AND t.typname = 'raster'
    
../src/providers/postgres/qgspostgresconn.cpp:1138 : (postgisVersion) [0ms] [thread:0x5588d28e4230] Raster support available!
../src/providers/postgres/qgspostgresconn.cpp:349 : (QgsPostgresConn) [0ms] [thread:0x5588d28e4230] Checking for GEOS support
../src/providers/postgres/qgspostgresconn.cpp:357 : (QgsPostgresConn) [0ms] [thread:0x5588d28e4230] GEOS support available!
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SET application_name='QGIS'
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT EXISTS ( SELECT oid FROM pg_catalog.pg_class WHERE relname='layer_styles')
../src/providers/postgres/qgspostgresprovider.cpp:326 : (~QgsPostgresProvider) [1ms] [thread:0x5588d28e4230] deconstructing.
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT * FROM information_schema.tables
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [2ms] [thread:0x5588d28e4230] Executing SQL: SELECT typname FROM pg_type WHERE oid = 19
../src/providers/postgres/qgspostgresproviderconnection.cpp:274 : (executeSqlPrivate) [0ms] [thread:0x5588d28e4230] Unhandled PostgreSQL type name
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT typname FROM pg_type WHERE oid = 19
../src/providers/postgres/qgspostgresproviderconnection.cpp:274 : (executeSqlPrivate) [0ms] [thread:0x5588d28e4230] Unhandled PostgreSQL type name
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT typname FROM pg_type WHERE oid = 19
../src/providers/postgres/qgspostgresproviderconnection.cpp:274 : (executeSqlPrivate) [0ms] [thread:0x5588d28e4230] Unhandled PostgreSQL type name
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT typname FROM pg_type WHERE oid = 1043
../src/providers/postgres/qgspostgresproviderconnection.cpp:274 : (executeSqlPrivate) [0ms] [thread:0x5588d28e4230] Unhandled PostgreSQL type varchar
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT typname FROM pg_type WHERE oid = 19
../src/providers/postgres/qgspostgresproviderconnection.cpp:274 : (executeSqlPrivate) [0ms] [thread:0x5588d28e4230] Unhandled PostgreSQL type name
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT typname FROM pg_type WHERE oid = 1043
../src/providers/postgres/qgspostgresproviderconnection.cpp:274 : (executeSqlPrivate) [0ms] [thread:0x5588d28e4230] Unhandled PostgreSQL type varchar
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT typname FROM pg_type WHERE oid = 19
../src/providers/postgres/qgspostgresproviderconnection.cpp:274 : (executeSqlPrivate) [0ms] [thread:0x5588d28e4230] Unhandled PostgreSQL type name
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT typname FROM pg_type WHERE oid = 19
../src/providers/postgres/qgspostgresproviderconnection.cpp:274 : (executeSqlPrivate) [0ms] [thread:0x5588d28e4230] Unhandled PostgreSQL type name
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT typname FROM pg_type WHERE oid = 19
../src/providers/postgres/qgspostgresproviderconnection.cpp:274 : (executeSqlPrivate) [0ms] [thread:0x5588d28e4230] Unhandled PostgreSQL type name
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT typname FROM pg_type WHERE oid = 1043
../src/providers/postgres/qgspostgresproviderconnection.cpp:274 : (executeSqlPrivate) [0ms] [thread:0x5588d28e4230] Unhandled PostgreSQL type varchar
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT typname FROM pg_type WHERE oid = 1043
../src/providers/postgres/qgspostgresproviderconnection.cpp:274 : (executeSqlPrivate) [0ms] [thread:0x5588d28e4230] Unhandled PostgreSQL type varchar
../src/providers/postgres/qgspostgresconn.cpp:1258 : (PQexec) [0ms] [thread:0x5588d28e4230] Executing SQL: SELECT typname FROM pg_type WHERE oid = 1043
../src/providers/postgres/qgspostgresproviderconnection.cpp:274 : (executeSqlPrivate) [0ms] [thread:0x5588d28e4230] Unhandled PostgreSQL type varchar

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #37313

### CODE REVIEW

**Comment by luipir** [comment]
confirmed thjat the PR fix the issue

**Review by luipir — APPROVED** [review]

File: src/providers/postgres/qgspostgresproviderconnection.cpp [hunk 1]
```diff
@@ -271,7 +271,8 @@ QList<QVariantList> QgsPostgresProviderConnection::executeSqlPrivate( const QStr
             }
             else
             {
-              QgsDebugMsg( QStringLiteral( "Unhandled PostgreSQL type %1" ).arg( typName ) );
+              // Just a warning, usually ok
+              QgsDebugMsgLevel( QStringLiteral( "Unhandled PostgreSQL type %1, assuming string" ).arg( typName ), 2 );
```
Comment (luipir) [inline src/providers/postgres/qgspostgresproviderconnection.cpp:275]: good to have notification of implicit type management

**Comment by luipir** [comment]
I tagged with Backport to 3.10, if not correct because not so critical, feel free to remove it

**Comment by elpaso** [comment]
I actually discovered that max length is 64 - 1 = 63 and not 64 (probably a C string) ... It needs to be fixed.
