### PR TITLE
Resolves #49578 ('Delete holes' bug when 'area' argument is used)

### LINKED ISSUE #49578: 'Delete holes' bug when 'area' argument is used
### What is the bug or the crash?

I discovered that 'Delete holes' does not work reliable when you use the 'area' argument i.e. when you want to delete all holes smaller than a specified area.
Sometimes holes larger than the specified area are incorrectly removed.
Therefore I have created a small example in an attached geopackage file which shows the problem.

### Steps to reproduce the issue

Open the attached geopackage which is uploaded below within the zip file.
It contains one layer named "delete_holes" defined in the Swedish CRS "SWEREF 99 TM" i.e. the unit are meters.
There is only one polygon in the layer and the outer ring  is a square (20x20 meters) and all four inner rings are also squares and with these sizes:
4 (2x2) , 9 (3x3) , 16 (4x4) , 36 (6x6)
When 'Delete holes' is used with the area argument 12 then only the two smaller holes (with areas 4 and 9) should be removed, but as you can see in a screenshot  below, the largest hole with area 36 is also removed.
[delete_holes.zip](https://github.com/qgis/QGIS/files/9262143/delete_holes.zip)
delete_holes_dialog
delete_holes_incorrect_result

### Versions

QGIS 3.22 but the problem is also in the current master and I will soon create a pull request.
As you can see in an attached screenshot I am using the 'master' branch code as of github commit '4861ee8a2f'

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Regarding the QGIS version, I discovered the problem when using Windows 10 and QGIS 3.22 but the problem is still there in the 'master' branch.
I know that since I decided to try and solve the problem myself, so I have setup the development environment for my Linux Ubuntu,
and when debugging it **I have found the problem and will create a pull request**.

So, you do not need to try figure out what the problem is since I intend to very soon (at least within 24 hours and probably sooner) create a pull request, when I have finished a unit test case, referring to this github issue.

### PR DESCRIPTION
**Pull request by TomasJohansson**
## Description

Fixed the problem in issue [49578](https://github.com/qgis/QGIS/issues/49578)

But the third commit is just a performance improvement for a method I noticed when fixing the problem,
and I thought it would be considered as overkill to create a separate pull request for that commit (6e8de5cd164b0cdc2fb67a470fad8fe06fd3e725)

Fixes #49578

### CODE REVIEW

File: src/core/geometry/qgslinestring.cpp [hunk 1]
```diff
@@ -1936,12 +1936,16 @@ QgsPoint QgsLineString::centroid() const
 
 void QgsLineString::sumUpArea( double &sum ) const
 {
+  // Please note that the area calculated in this method will be negative if the line points are defined in clockwise order.
```
Comment (nyalldawson) [inline src/core/geometry/qgslinestring.cpp:1939]: These comments would belong better as additions to the docstrings in the header file, so that they get included in the API docs and PyQGIS references.

Comment (TomasJohansson) [reply src/core/geometry/qgslinestring.cpp]: OK I have now added comments to the header file instead.

**Comment by TomasJohansson** [comment]
Today I noted that there is now a new result but with one failure.
I do not know how the process works, i.e. maybe someone is now waiting for me to commit something new to fix the problem 
and then after a new expected commit, someone is automatically notified about it and then decides to try executing the tests again?

If so, I now want to say that you should not wait for me to do that, since I am pretty sure that this test failure has nothing to do with this pull request of mine.
When I clicked "Details" of the failed tests it leads to this URL:
https://github.com/qgis/QGIS/runs/7834878518?check_suite_focus=true
```
The following tests FAILED:
	136 - test_core_networkaccessmanager (Timeout)
```

I have not commited anything related to network access.

**Comment by nyalldawson** [comment]
@TomasJohansson the merge conflict needs fixing here -- it's preventing the ci tests from running

**Comment by TomasJohansson** [comment]
@nyalldawson Okay, now I have merged

**Comment by TomasJohansson** [comment]
I merged 15 days ago.
"Review required" and "5 workflows awaiting approval"
@nyalldawson

**Comment by TomasJohansson** [comment]
Today I again had to merge.
There had been changes to qgslinestring.cpp which I now let override my performance improvement I mentioned when I created this pull request **almost two months ago**.
So, now there is only the following **one line of production code** (the other things in this PR are just test code and non-executable things such as comments) that needs to be merged into the master by someone with write access:
(in the file qgscurvepolygon.cpp)
`if ( area < minimumAllowedArea )`
==> 
`if ( std::fabs( area ) < minimumAllowedArea )`

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
@TomasJohansson the fix is good, sorry about the slow merge! 

I think it's worth reviving the optimisation (the unnecessary duplicate multiplication) , but can we do that in a follow up pr?

**Comment by TomasJohansson** [comment]
> @TomasJohansson the fix is good, sorry about the slow merge!
> 
> I think it's worth reviving the optimisation (the unnecessary duplicate multiplication) , but can we do that in a follow up pr?

Thank you, okay I have now created a [new PR for the duplicate multiplications](https://github.com/qgis/QGIS/pull/50450)
