### PR TITLE
[processing] Fix feature iteration against a model

### LINKED ISSUE #60131: Modeler - Feature iteration does not work
### What is the bug or the crash?

When running a processing model with a `Vector Features` input, using the "Iterate over this layer..." option only runs correctly once. The remainder of iterations all "run", but with 0 algorithms being executed.

### Steps to reproduce the issue

1. Create a new processing model
2. Add a Vector Features input
3. Add some processing algorithm (such as a buffer tool) & set that algorithms output as final
4. Run model
5. Set the "Iterate over this layer..." option
6. Execute model
7. See output

My output (abridged for conciseness):
```
Algorithm 'Iteration Test' starting…
Input parameters:
{ 'input_features' : QgsProcessingFeatureSourceDefinition(...), 'output' : 'TEMPORARY_OUTPUT' }

Executing iteration 1/6…
Prepare algorithm: native:buffer_1
Running Buffer [1/1]
Input Parameters:
{ INPUT: '...', DISSOLVE: False, ... }
Results:
{ OUTPUT: 'Buffered_35d8d698_40f2_4c78_bacb_905843d212f6' }
OK. Execution took 0.005 s (1 output).
Model processed OK. Executed 1 algorithm total in 0.011s.
Executing iteration 2/6…
Model processed OK. Executed 0 algorithms total in 0s.
Executing iteration 3/6…
Model processed OK. Executed 0 algorithms total in 0s.
Executing iteration 4/6…
Model processed OK. Executed 0 algorithms total in 0s.
Executing iteration 5/6…
Model processed OK. Executed 0 algorithms total in 0s.
Executing iteration 6/6…
Model processed OK. Executed 0 algorithms total in 0s.
Loading resulting layers
Execution completed in 0.09 seconds
Algorithm 'Iteration Test' finished
```

### Versions

|QGIS version|3.40.2-Bratislava|
|--|--|
|QGIS code revision|14826ca1|

|Libraries||
|--|--|
|Qt version|5.15.13|
|Python version|3.12.8|
|GDAL/OGR version|3.9.3|
|PROJ version|9.5.0|
|EPSG Registry database version|v11.016 (2024-08-31)|
|GEOS version|3.13.0-CAPI-1.19.0|
|SQLite version|3.46.1|
|PDAL version|2.8.1|
|PostgreSQL client version|16.2|
|SpatiaLite version|5.1.0|
|QWT version|6.3.0|
|QScintilla2 version|2.14.1|
|OS version|Windows 11 Version 2009|

|Active Python plugins||
|--|--|
|db_manager|0.1.20|
|grassprovider|2.12.99|
|processing|2.12.99|

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

This is a regression, as this works as-expected in QGIS 3.34.14 LTR.

The example I ran was running just the buffer tool in a model with all default values.
My test model is here: [Iteration Test.zip](https://github.com/user-attachments/files/18398447/Iteration.Test.zip)

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This PR fixes processing algorithm feature iteration against a model.

Fixes #60131.

### CODE REVIEW

File: src/core/processing/qgsprocessingcontext.h [hunk 1]
```diff
@@ -794,6 +794,13 @@ class CORE_EXPORT QgsProcessingContext
      */
     QgsProcessingModelResult &modelResult() SIP_SKIP { return mModelResult; }
 
+    /**
+     * Clears model results previously populated when the context was used to run a model algorithm.
+     *
+     * \since QGIS 3.42
```
Comment (agiudiceandrea) [inline src/core/processing/qgsprocessingcontext.h:800]: Since the PR must be backported to release-3_40 branch, shouldn't this method be "since QGIS 3.40"?

Comment (troopa81) [reply src/core/processing/qgsprocessingcontext.h:800]: Well, I don't think so (But not 100% sure). IIRC, that's the way we deal with such scenario, because the modification wouldn't be effective in 3.4.**0** only in 3.40.**3** and that could lead to misunderstanding for people who would read the documentation.

**Review by troopa81 — APPROVED** [review]
Looks good to me

File: src/core/processing/qgsprocessingcontext.h (hunk 1 above)
Comment (nyalldawson) [reply src/core/processing/qgsprocessingcontext.h:800]: @troopa81 is correct -- the convention we use for this is just to tag with the newer version, so that there's no risk of someone incorrectly assuming it's available in an older release

**Review by nyalldawson — APPROVED** [review]
