### PR TITLE
ReadEntry ok value must be set to False when property doesn't exist

### LINKED ISSUE #37851: readEntry and readBoolEntry always report found
**Describe the bug**

readEntry and readBoolEntry alwys report found as true.    readNumEntry does not

**How to Reproduce**

Start QGIS.  Do not load a project file
Open the Python Console and type the following commands (responses in italic)
proj = QgsProject.instance() 
proj.readBoolEntry('', 'xxx', False) 
*(False, True)*
proj.readEntry('', 'xxx', 'xx') 
*('xx', True)*
proj.readNumEntry('', 'xxx', -1) 
*(-1, False)*

**QGIS and OS versions**

QGIS version | 3.10.7-A Coruña | QGIS code revision | 7b4ca4c8d0
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | plugin_reloader; QSWAT3; QSWATPlus3_64; remotedebug; db_manager; MetaSearch; processing

**Additional context**

### PR DESCRIPTION
**Pull request by troopa81**
Fixes #37851 : fix readXXXEntry methods, add few tests and complete documentation

### CODE REVIEW

File: src/core/qgsproject.h [hunk 1]
```diff
@@ -500,9 +500,32 @@ class CORE_EXPORT QgsProject : public QObject, public QgsExpressionContextGenera
      */
     QStringList readListEntry( const QString &scope, const QString &key, const QStringList &def = QStringList(), bool *ok = nullptr ) const;
 
+    /**
+     * \returns entry value as string from \a scope given its \a key
+     * \param def returned value if key doesn't exist
+     * \param ok set to TRUE if key exists and has been successfully retrieved
+     */
     QString readEntry( const QString &scope, const QString &key, const QString &def = QString(), bool *ok = nullptr ) const;
```
Comment (nyalldawson) [inline src/core/qgsproject.h:508]: Can you mark ok as "SIP_OUT" in here so that the python docs are correctly generated?

File: src/core/qgsproject.h [hunk 2]
```diff
@@ -500,9 +500,32 @@ class CORE_EXPORT QgsProject : public QObject, public QgsExpressionContextGenera
      */
     QStringList readListEntry( const QString &scope, const QString &key, const QStringList &def = QStringList(), bool *ok = nullptr ) const;
 
+    /**
+     * \returns entry value as string from \a scope given its \a key
```
Comment (nyalldawson) [inline src/core/qgsproject.h:504]: Returns needs to come after the param annotations so that sipify can do its full magic

File: src/core/qgsproject.h (hunk 1 above)
Comment (m-kuhn) [reply src/core/qgsproject.h:508]: Isn't that an API change?

Comment (nyalldawson) [reply src/core/qgsproject.h:508]: Doesn't seem to be - check the test results from this pr, sip is already treating ok as a return argument. It's just sipify which needs the hints for the documentation.

Comment (troopa81) [reply src/core/qgsproject.h]: indeed, there is no API change. I added SIP_OUT

File: src/core/qgsproject.h (hunk 2 above)
Comment (troopa81) [reply src/core/qgsproject.h]: Thanks for pointing that out. I did the modifications

**Comment by troopa81** [comment]
I fixed readEntryList also

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
@m-kuhn this pr shows a number of warnings in the documentation action (not all related to this pr, some have slipped in through other prs). These used to error out the builds, but don't anymore. Any ideas why?

**Comment by m-kuhn** [comment]
Good question. Do you have a link to those warnings (are they on the CI)?
Otherwise we could add a new job to the workflows, dedicated to check api docs only
