### PR TITLE
restore fill brush when switching back to single and double box scalebar (fix #37413)

### LINKED ISSUE #37413: Switching back to Box style scale bar after having switched to Hollow does not reset the fill brush
**Describe the bug**
Switching back to Box style scale bar after having switched to Hollow does not reset the fill brush

**How to Reproduce**
In a map layout, add a map and scalebar. Set to single or double box style.
Set to Hollow style.
Set to single or double box style again
The style brush does not revert from No Brush. This can be observed by going to the Display section, expanding the options for Primary fill, Configure symbol, and looking at the Fill style for the Simple fill style layer. Setting the Fill style to Solid returns the bar color for the scale.

**QGIS and OS versions**
QGIS 3.14 on Linux Mint 19.3

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by alexbruy**
## Description

When a Hollow style of scalebar is selected, scalebar settings are updated and brush style is set to `Qt::NoBrush` and stroke is set to `Qt::NoPen`. When switching back to Single or Double box style of scalebar brush and pen are not restored as these two renderers do not override `applyDefaultSettings()` method.

Fixes #37413.

### CODE REVIEW

File: src/core/scalebar/qgsdoubleboxscalebarrenderer.h [hunk 1]
```diff
@@ -42,6 +42,14 @@ class CORE_EXPORT QgsDoubleBoxScaleBarRenderer: public QgsScaleBarRenderer
                const QgsScaleBarSettings &settings,
                const QgsScaleBarRenderer::ScaleBarContext &scaleContext ) const override;
 
+    /**
+     * Applies any default settings relating to the scalebar to the passed \a settings object.
+     *
+     * Returns TRUE if settings were applied.
+     *
+     * \since QGIS 3.42
+     */
```
Comment (nyalldawson) [inline src/core/scalebar/qgsdoubleboxscalebarrenderer.h:51]:
```suggestion
```

File: src/core/scalebar/qgssingleboxscalebarrenderer.h [hunk 2]
```diff
@@ -43,6 +43,14 @@ class CORE_EXPORT QgsSingleBoxScaleBarRenderer: public QgsScaleBarRenderer
                const QgsScaleBarSettings &settings,
                const QgsScaleBarRenderer::ScaleBarContext &scaleContext ) const override;
 
+    /**
+     * Applies any default settings relating to the scalebar to the passed \a settings object.
+     *
+     * Returns TRUE if settings were applied.
+     *
+     * \since QGIS 3.42
+     */
```
Comment (nyalldawson) [inline src/core/scalebar/qgssingleboxscalebarrenderer.h:52]:
```suggestion
```

File: src/core/scalebar/qgsdoubleboxscalebarrenderer.cpp [hunk 3]
```diff
@@ -190,3 +191,24 @@ void QgsDoubleBoxScaleBarRenderer::draw( QgsRenderContext &context, const QgsSca
   //draw labels using the default method
   drawDefaultLabels( context, settings, scaleContext );
 }
+
+bool QgsDoubleBoxScaleBarRenderer::applyDefaultSettings( QgsScaleBarSettings &settings ) const
+{
+  // restore the fill symbols by default
+  std::unique_ptr< QgsFillSymbol > fillSymbol = std::make_unique< QgsFillSymbol >();
```
Comment (nyalldawson) [inline src/core/scalebar/qgsdoubleboxscalebarrenderer.cpp:198]: I'd make this conditional on the settings.fillSymbol() being invisible -- otherwise changing between single box and double box will keep resetting the fill symbol back to default, when we should be able to retain the symbol between these renderers.

File: src/core/scalebar/qgsdoubleboxscalebarrenderer.cpp [hunk 4]
```diff
@@ -190,3 +191,29 @@ void QgsDoubleBoxScaleBarRenderer::draw( QgsRenderContext &context, const QgsSca
   //draw labels using the default method
   drawDefaultLabels( context, settings, scaleContext );
 }
+
+bool QgsDoubleBoxScaleBarRenderer::applyDefaultSettings( QgsScaleBarSettings &settings ) const
+{
+  QgsSimpleFillSymbolLayer *fill = qgis::down_cast< QgsSimpleFillSymbolLayer * >( settings.fillSymbol()->symbolLayers().at( 0 ) );
```
Comment (nyalldawson) [inline src/core/scalebar/qgsdoubleboxscalebarrenderer.cpp:197]: qgis::down_cast will assert if the layer isn't a simple fill, so eg if the user changed to a gradient fill then this will crash:

```suggestion
  QgsSimpleFillSymbolLayer *fill = dynamic_cast< QgsSimpleFillSymbolLayer * >( settings.fillSymbol()->symbolLayers().at( 0 ) );
```

**Review by nyalldawson — APPROVED** [review]
