### PR TITLE
Fix qgsVariantGreaterThan may return false result when values are equal

### LINKED ISSUE #61759: Problem in comparison function
### What is the bug or the crash?

Qsort callback qgsVariantGreaterThan may return false result when input structs have all compared fields equal. This in turn may causes inconsistent order or even crashes in some qsort implementations.
The location of the error function is src/core/qgis.cpp.

### Steps to reproduce the issue

According to the following part of the code, when the two input structures are exactly the same, the function qgsVariantLessThan will return false, and thus the function qgsVariantGreaterThan will return true.
```
bool qgsVariantGreaterThan( const QVariant &lhs, const QVariant &rhs )
{
  return ! qgsVariantLessThan( lhs, rhs );
}
```

### Versions

3.24

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nyalldawson**
Fixes #61759

### CODE REVIEW

**Review by alexbruy — APPROVED** [review]

File: src/core/qgis.cpp [hunk 1]
```diff
@@ -126,52 +126,115 @@ void qgsFree( void *ptr )
...
+      const qulonglong lhsULongLong = lhs.toULongLong();
+      const qulonglong rhsULongLong = rhs.toULongLong();
+      return lhsULongLong < rhsULongLong ? -1 : ( lhsULongLong == rhsULongLong ? 0 : 1 );
+    }
     case QMetaType::Type::Double:
-      return lhs.toDouble() < rhs.toDouble();
+    {
+      const double lhsDouble = lhs.toDouble();
+      const double rhsDouble = rhs.toDouble();
+      return lhsDouble < rhsDouble ? -1 : ( lhsDouble == rhsDouble ? 0 : 1 );
```
Comment (rouault) [inline src/core/qgis.cpp:186]: what about NaN comparisons ? (also true for Float).

I'd suggest considering NaN < any non-NaN value.

So 
```suggestion
      if ( std::isnan(lhsDouble) )
      {
           return std::isnan(rhsDouble) ? 0 : -1;
      }
      else if ( std::isnan(rhsDouble) )
      {
          return 1;
      }
      return lhsDouble < rhsDouble ? -1 : ( lhsDouble == rhsDouble ? 0 : 1 );
```

Comment (nyalldawson) [reply src/core/qgis.cpp:186]: Ok, added
