### PR TITLE
Fix inconsistent field name line edit focus behaviour when creating new vector layers

### LINKED ISSUE #58482: Inconsistent action in similar 'New [x] Layer' dialogue
### What is the bug or the crash?

In the 'New Temporary Scratch Layer' dialogue, while adding a new field, when the 'Add to Fields List' button is clicked, the cursor and focus returns to the 'Name' data entry box. This is excellent behavior.

In the 'New GeoPackage Layer' dialogue, focus is not returned to the 'Name' data entry box, but has to be clicked on or tabbed to.

### Steps to reproduce the issue

Similarly to what is described above, 

1. click the 'New GeoPackage Layer' button in the 'Data Source Manager Toolbar'
2. click in the 'Name' box of the 'New Field' block in the dialogue, add some text.
3. click the 'Add to Fields List' button in the same 'New Field' block
4. notice that the 'Name' data entry box has to be re-selected for subsequent 'New Field' entries

To see the nicer method:
1. click the 'New Temporary Scratch Layer' button in the 'Data Source Manager Toolbar'
2. click in the 'Name' box of the 'New Field' block in the dialogue, add some text.
3. click the 'Add to Fields List' button in the same 'New Field' block
4. notice that the cursor is in the now empty 'Name' data entry box and has focus for quick addition of new fields, simply leaving the mouse above the 'Add to Fields List' button and clicking for each new field of the same type.

Additionally, after testing, noticed that the desired action works on 'New Shapefile Layer' but not on 'New SpatiaLite Layer'

### Versions

QGIS version
3.38.2-Grenoble
QGIS code revision
130c432394
Qt version
5.15.13
Python version
3.12.5
GDAL/OGR version
3.9.2
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009

Active Python plugins
changeDataSource
3.1
document_management_system
0.3.3
processing_saga_nextgen
1.0.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

EDIT: added 'add some text' to steps 2 in 'how to reproduce'

### PR DESCRIPTION
**Pull request by benwirf**
## Description

This PR fixes inconsistent behavior when adding fields to new layers by returning focus to the field name line edits in the `mAddAttributeButton_clicked` slot methods of the create new layer dialogues when the <kbd>Add to fields list</kbd> button is clicked.

Fixes #58482

### CODE REVIEW

File: src/app/qgsnewspatialitelayerdialog.cpp [hunk 1]
```diff
@@ -178,6 +178,11 @@ void QgsNewSpatialiteLayerDialog::mAddAttributeButton_clicked()
     checkOk();
 
     mNameEdit->clear();
+
+    if ( !mNameEdit->hasFocus() )
+    {
+      mNameEdit->setFocus( Qt::MouseFocusReason );
```
Comment (nyalldawson) [inline src/app/qgsnewspatialitelayerdialog.cpp:184]: Is the "MouseFocusReason" required here? Or does `mNameEdit->setFocus();` work on its own?

Comment (benwirf) [reply src/app/qgsnewspatialitelayerdialog.cpp:184]: Hi @nyalldawson, I tested `setFocus()` with no argument while I was working on this PR, and yes- it does work fine. I decided to include the `Qt::MouseFocusReason` argument after consulting the [Qt docs](https://doc.qt.io/qt-6/qwidget.html#setFocus) as it seemed appropriate given that the line edit widget is getting focus due to a mouse (button click) event. Though it's very possible my reasoning is flawed & I have no strong opinion either way.

Comment (nyalldawson) [reply src/app/qgsnewspatialitelayerdialog.cpp:184]: The docs aren't super helpful here, in that they don't state exactly what the practical differences are as a result of using the different flags. My understanding is that the mouse focus reason should be used for mouse interactions directly with the focused widget, eg clicks/drops/etc. 

I'd lean toward NOT specifying the method, so that Qt::OtherFocusReason is used. That one seems closest to the actual situation triggering the focus, and must be a safe choice if Qt defaults to it

Comment (benwirf) [reply src/app/qgsnewspatialitelayerdialog.cpp:184]: Sure, that makes sense. Thanks Nyall, I will update this PR accordingly.

**Review by 3nids — APPROVED** [review]

**Comment by benwirf** [comment]
Thank you @3nids :-)
