### PR TITLE
PostgreSQL Provider: Fix M detection

### LINKED ISSUE #55223: Unable to add layers with M (measure) geometries from PostGIS
### What is the bug or the crash?

The layer is considered not to have a geometry.

### Steps to reproduce the issue

On PostGIS run :

create table point_with_measure as
select ST_GeomFromText('POINT M (797290.9084747223 6295271.877055189 24500)', 2154) as geom

Try to display this layer in QGIS.

3.28.12 --> KO
3.34.0 --> KO
3.16.16 --> OK

### Versions

Version de QGIS
3.28.12-Firenze
Révision du code
dcc633b2de
Version de Qt
5.15.3
Version de Python
3.9.5
Version de GDAL/OGR
3.7.2
Version de Proj
9.3.0
Version de la base de données du registre EPSG
v10.094 (2023-08-08)
Version de GEOS
3.12.0-CAPI-1.18.0
Version de SQLite
3.41.1
Version de PDAL
2.5.5
Version du client PostgreSQL
unknown
Version de SpatiaLite
5.1.0
Version de QWT
6.1.6
Version de QScintilla2
2.13.4
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

image

### PR DESCRIPTION
**Pull request by lbartoletti**
## Description

Unlike Geometry(Z), GeometryM contains already M suffix. It's useless to add M suffix here, since it will add a new name and the geometry type name will be something like GeometryMM.

Fixes #55223

### CODE REVIEW

**Comment by lbartoletti** [comment]
with this "fix": 

image

cc @Michael-cd30

**Comment by lbartoletti** [comment]
and : 

image

**Review by elpaso — COMMENTED** [review]
LGTM 
Any chance to have a test?

File: src/providers/postgres/qgspostgresconn.cpp [hunk 1]
```diff
@@ -2354,7 +2354,11 @@ void QgsPostgresConn::retrieveLayerTypes( QVector<QgsPostgresLayerProperty *> &l
       switch ( zmFlags )
       {
         case 1:
-          typeString.append( 'M' );
+          // Unlike Geometry(Z), GeometryM contains already M suffix.
+          // It's useless to add M suffix here,
+          // since it will add a new name and the geometry type name will be something like GeometryMM.
+          // see: https://github.com/qgis/QGIS/issues/55223
+          //typeString.append( 'M' );
```
Comment (nirvn) [inline src/providers/postgres/qgspostgresconn.cpp:2361]: Could we avoid introducing commented-out code here? :)

Comment (lbartoletti) [reply src/providers/postgres/qgspostgresconn.cpp:2361]: Since I wasn't sure about my fix, and it still seems like something that deserves an explanation, I preferred to add my comment and leave the code as a comment. Do you agree, if I leave my comment, but delete the "faulty" line?

**Comment by lbartoletti** [comment]
> Any chance to have a test?

@elpaso I confess I have no idea how to test it :/

**Comment by elpaso** [comment]
> > Any chance to have a test?
> 
> @elpaso I confess I have no idea how to test it :/


Create the test table `test_linestringm`  then something like:

```python
md = QgsProviderRegistry.instance().providerMetadata('postgres')
geom_typs = [t.geometryColumnTypes()[0] for t in md.createConnection('dbname=qgis_test port=5433', {}).tables() if t.tableName() == 'test_linestringm']

# Expected:
[<QgsAbstractDatabaseProviderConnection.TableProperty.GeometryColumnType: 'LineString, EPSG:2154'>,
<QgsAbstractDatabaseProviderConnection.TableProperty.GeometryColumnType: 'LineStringM, EPSG:2154'>]
```

See here for examples:  https://github.com/qgis/QGIS/blob/master/tests/src/python/test_qgsproviderconnection_postgres.py#L386

**Review by elpaso — APPROVED** [review]
