### PR TITLE
Fix json hanlding of bools and complete json(b) PG support

### LINKED ISSUE #30131: Saving edits to a layer with JSON field throws an error
Easy to reproduce:
1. Add a postgis layer with json (jsonb) column to a QGIS project.
2. Start editing and add a new record.
3. Click Save edits. 

**Boom!**
```
Could not commit changes to layer (your_layer_here)
Errors: ERROR: 1 feature(s) not added.

  Provider errors:
      PostGIS error while adding features: ERROR:  column "jsonb_column" is of type jsonb but expression is of type hstore
    LINE 1: ...::hstor...
                                                                 ^
    HINT:  You will need to rewrite or cast the expression.
```
Looks like QGIS casts jsonb to hstore for internal representation and forgets to cast back when inserting/updating postgresql table.

Found on QGIS 3.6

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #30131 and add tests for jsonutils

### CODE REVIEW

**Comment by m-kuhn** [comment]
Looks good

**Comment by elpaso** [comment]
@m-kuhn thanks for the review!

File: src/core/qgsjsonutils.h [hunk 1]
```diff
@@ -345,6 +345,19 @@ class CORE_EXPORT QgsJsonUtils
      */
     static json jsonFromVariant( const QVariant &v ) SIP_SKIP;
 
+    /**
+     * Converts JSON QString \a jsonString to a QVariant, in case of parsing error an invalid QVariant is returned.
```
Comment (m-kuhn) [inline src/core/qgsjsonutils.h]:
```suggestion
     * Converts JSON \a jsonString to a QVariant, in case of parsing error an invalid QVariant is returned.
```

I think the types in the two docstring here and below are mixed up. But I'd just skip them both, they are trivial to see from the signature itself.

File: src/providers/postgres/qgspostgresconn.cpp [hunk 2]
```diff
@@ -1057,6 +1059,16 @@ QString QgsPostgresConn::quotedValue( const QVariant &value )
...
 }
 
+QString QgsPostgresConn::quotedJsonValue( const QVariant &value )
+{
+  if ( value.isNull() || !value.isValid() )
+    return QStringLiteral( "null" );
+  if ( value.type() == QVariant::Bool )
+    return value.toBool() ?  QStringLiteral( "true" ) : QStringLiteral( "false" );
+  const auto j { QgsJsonUtils::jsonFromVariant( value ) };
+  return QStringLiteral( "'%1'" ).arg( QString::fromStdString( j.dump() ) );
```
Comment (nyalldawson) [inline src/providers/postgres/qgspostgresconn.cpp]: Should QgsPostgresConn::quotedValue be used here? Or has escaping quotes already been done by j.dump()?

File: src/providers/postgres/qgspostgresconn.cpp [hunk 3]
```diff
@@ -1057,6 +1059,16 @@ QString QgsPostgresConn::quotedValue( const QVariant &value )
   }
 }
 
+QString QgsPostgresConn::quotedJsonValue( const QVariant &value )
+{
+  if ( value.isNull() || !value.isValid() )
```
Comment (nyalldawson) [inline src/providers/postgres/qgspostgresconn.cpp]:
```suggestion
  if ( value.isNull() || !value.isValid() || value.type() == QVariant::Bool )
     return QgsPostgresConn::quotedValue( value );
```

(for consistency)?

File: src/providers/postgres/qgspostgresconn.cpp (hunk 2 above)
Comment (elpaso) [reply src/providers/postgres/qgspostgresconn.cpp]: j.dump() returns valid JSON, and quotedValue() would return `NULL` instead of `null` and `TRUE` instead of `true` moreover it format strings, for this reason it's not suitable here but `quotedString()` is.
I've added a test for values that require escaping.

File: src/providers/postgres/qgspostgresconn.cpp (hunk 3 above)
Comment (elpaso) [reply src/providers/postgres/qgspostgresconn.cpp]: I've added a few more tests, null, true and false should be handled correctly now.

File: src/core/qgsjsonutils.h [hunk 4]
```diff
@@ -345,6 +345,19 @@ class CORE_EXPORT QgsJsonUtils
...
 
+    /**
+     * Converts JSON \a jsonString to a QVariant, in case of parsing error an invalid QVariant is returned.
+     * \note Not available in Python bindings
+     * \since QGIS 3.8
+     */
+    static QVariant parseJson( const std::string &jsonString ) SIP_SKIP;
+
+    /**
+     * Converts JSON std::string \a jsonString to a QVariant, in case of parsing error an invalid QVariant is returned.
```
Comment (m-kuhn) [inline src/core/qgsjsonutils.h]:
```suggestion
     * Converts JSON \a jsonString to a QVariant, in case of parsing error an invalid QVariant is returned.
```
