### PR TITLE
Fix broken coordinate transform when exporting features to dxf

### LINKED ISSUE #43449: Export to cad, problem with cordinates
Hi,

I have problem with export project from qgis3 to dxf.

After export points on autocad have diffrent points cordinates (bad cordinates)

Here are movie showed this
https://www.youtube.com/watch?v=dukIOdf5mo8

### PR DESCRIPTION
**Pull request by nyalldawson**
Fixes #43449

### CODE REVIEW

File: src/core/dxf/qgsdxfexport.h [hunk 1]
```diff
@@ -585,13 +585,20 @@ class CORE_EXPORT QgsDxfExport : public QgsLabelSink
...
-     * \param ct the coordinate transform
+     * \param ct coordinate transform from CRS of feature being added to destination DXF CRS
      * \param layer the layer name
      * \param symbolLayer the symbollayer to write to the dxf file
      * \param allSymbolLayers if TRUE, all symbol layers of the subsymbol are written. If FALSE, only the first one is written
     */
     void addGeometryGeneratorSymbolLayer( QgsSymbolRenderContext &ctx, const QgsCoordinateTransform &ct, const QString &layer, QgsSymbolLayer *symbolLayer, bool allSymbolLayers );
 
+    /**
+     * \param ctx
```
Comment (nirvn) [inline src/core/dxf/qgsdxfexport.h:596]: Maybe add a one liner description? Adds a feature into the DXF (scene|file|whatever)?

**Review by nirvn — APPROVED** [review]

**Comment by lbartoletti** [comment]
Thanks @nyalldawson !

fyi @jmarsac
