### PR TITLE
Fix extreme zoom out

### LINKED ISSUE #40283: crash when extrem zoom out with mesh layer
with extreme zoom out, this line https://github.com/qgis/QGIS/blob/74edcbed5f8d302813427206f92de662a1e3c615/src/core/mesh/qgsmeshlayerrenderer.cpp#L104 can calculate an excessive output size that lead to a extreme used of memory and eventually to a crash of QGIS when rendering.

With 3.16 and master

### PR DESCRIPTION
**Pull request by vcloarec**
When there is an extreme zoom out, QgsMaptoPixel parameters produce an invalid transform. In that case, parameter are not changed but the map extent changes anyway, and map extent and the QgsMapToPixel instance of QgsMapsettings are not longer sync. With zoom out map extent grows while map to pixels does not change. 
That induces a increasing output size of the mesh layer rendering that finishes with an overflow.

To fix that, this PR invalidates the QgsMapSettings instance when QgsMapToPixel parameters induce invalid transform.

Then, the rendering is not done when map settings are invalid.

fix #40283

### CODE REVIEW

File: src/core/maprenderer/qgsmaprendererjob.h [hunk 1]
```diff
@@ -221,7 +221,7 @@ class CORE_EXPORT QgsMapRendererJob : public QObject
      * Start the rendering job and immediately return.
      * Does nothing if the rendering is already in progress.
      */
-    virtual void start() = 0;
+    void start();
```
Comment (m-kuhn) [inline src/core/maprenderer/qgsmaprendererjob.h:224]: Can you add that to api_break.dox?

File: src/core/maprenderer/qgsmaprendererjob.h [hunk 2]
```diff
@@ -490,6 +490,14 @@ class CORE_EXPORT QgsMapRendererJob : public QObject
 
     //! Convenient method to allocate a new image and a new QPainter on this image
     QPainter *allocateImageAndPainter( QString layerId, QImage *&image );
+
+    /**
+     *  This virtual method has to be implemented in derived class for starting the rendering.
+     *  This method is called in start() method after ckecking if the map can be rendered.
+     *  \since QGIS 3.20
+     */
+    virtual void startPrivate() {};
```
Comment (nyalldawson) [inline src/core/maprenderer/qgsmaprendererjob.h:499]:
```suggestion
    virtual void startPrivate() = 0;
```

File: src/core/qgsmaptopixel.h [hunk 3]
```diff
@@ -237,10 +237,26 @@ class CORE_EXPORT QgsMapToPixel
      * \param widthPixels Output width, in pixels
      * \param heightPixels Output height, in pixels
      * \param rotation clockwise rotation in degrees
+     *
+     * \note if parameters leads to a non valid transform, parameters are not changed
```
Comment (nyalldawson) [inline src/core/qgsmaptopixel.h:241]:
```suggestion
     * \note if the specified parameters result in an invalid transform then no changes will be applied to the object
```

File: src/core/qgsmaptopixel.h [hunk 4]
```diff
@@ -237,10 +237,26 @@ class CORE_EXPORT QgsMapToPixel
...
 
+    /**
+     * Set parameters for use in transforming coordinates
+     * \param mapUnitsPerPixel Map units per pixel
+     * \param centerX X coordinate of map center, in geographical units
+     * \param centerY Y coordinate of map center, in geographical units
+     * \param widthPixels Output width, in pixels
+     * \param heightPixels Output height, in pixels
+     * \param rotation clockwise rotation in degrees
+     * \param ok will be set to true if parameters leads to a valid transform, otherwise  parameters are not changed and ok will be set to false
```
Comment (nyalldawson) [inline src/core/qgsmaptopixel.h:254]:
```suggestion
     * \param ok will be set to TRUE if the specified parameters result in a valid transform, otherwise the changes are ignored and ok will be set to FALSE.
```

File: src/core/maprenderer/qgsmaprendererjob.h (hunk 2 above)
Comment (nyalldawson) [reply src/core/maprenderer/qgsmaprendererjob.h:499]: While this is technically an API break I would argue that QgsMapRendererJob was never designed to be subclassed by Python, and any plugins/scripts which ARE subclassing it are an extreme edge case which falls firmly into the "not officially supported" camp!

Comment (vcloarec) [reply src/core/maprenderer/qgsmaprendererjob.h:499]: This method and this doc is in the private part of the class, so not exposed to Python, no? Or I have misunderstoodd your comment...

For the pure virtual method, my first intention was to make this method pure virtual, but I couldn't make SIP accept it: when building, I've got some error with the sub classes (I don't remember exactly which errors...), the only to make the building was to not make this method not pure virtual.

Comment (nyalldawson) [reply src/core/maprenderer/qgsmaprendererjob.h:499]: You might need to add SIP_ABSTRACT to the base class definition

e.g. 

```
class CORE_EXPORT QgsMapLayerRenderer SIP_ABSTRACT
```

Comment (vcloarec) [reply src/core/maprenderer/qgsmaprendererjob.h]: Indeed, much better, and also for abstract sub classes.

**Comment by vcloarec** [comment]
unrelated test failed

**Review by nyalldawson — APPROVED** [review]
