### PR TITLE
Fix pointcloud properties dialog minimum size

### LINKED ISSUE #43276: Point Cloud Property window resizing issue
I'm making a ticket in case anyone else has this. 

When trying to resize the Property window for a Point Cloud layer in QGIS 3.18.2 on windows, the window suddenly disappears and can never be seen again.

This seems to occur on symbology with Attribute by Ramp is active.

Since this is a modal window nothing else can be done for the session.
Point_cloud_window_issue

### PR DESCRIPTION
**Pull request by uclaros**
## Description
The _3D View_ tab in a point cloud's properties dialog was forcing the dialog to relatively big minimum height.
Peek 2024-01-24 17-45

Probably fixes #43276 , not sure about the disappearing part but I hope it was some QT weirdness when hitting the minimum size.

### CODE REVIEW

File: src/gui/qgsstackedwidget.h [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+ * \ingroup gui
+ * \brief A QStackedWidget that can be shrunk to its current widget's size.
+ *
+ * A regular QStackedWidget can be shrunk down the size of its
+ * largest page widget. A QgsStackedWidget only takes the current
+ * page widget into account when resizing.
+ *
+ * \since QGIS 3.36
+ */
+class GUI_EXPORT QgsStackedWidget : public QStackedWidget
```
Comment (nyalldawson) [inline src/gui/qgsstackedwidget.h:37]: Nice approach!

Can I suggest for future proofness that we:

1. Add an enum:
```
enum class SizeMode {
    ConsiderAllPages, //!< The sizes of all pages are considered when calculating the stacked widget size
    CurrentPage, //!< Only the size of the current page is considered when calculating the stacked widget size
};
```

2. Add getters/setters for SizeMode, default SizeMode to ConsiderAllPages (ie match QStackedWidget)
3. Adapt the subclass sizeHint methods to consider the SizeMode

This way we could start moving everything over from QStackedWidget to QgsStackedWidget, and we'd have a natural place to add other tweaks and improvements in future. Much like what we do for QgsScrollArea. (There's also a test to force use of QgsScrollArea over QScrollArea, we could potentially add the same for QgsStackedWidget later)

Comment (uclaros) [reply src/gui/qgsstackedwidget.h:37]: Hmm, I guess we could, I'm not sure about the potential gain (other than homogeneity). In most places we use a stacked widget it either holds similar widgets or it is used as a temporary container and the inactive page gets deleted.
With QgsScrollArea it was quite different, as it implemented the absolutely necessary functionality to avoid messing with widgets while scrolling.

File: src/gui/qgsstackedwidget.h [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+ *   it under the terms of the GNU General Public License as published by  *
+ *   the Free Software Foundation; either version 2 of the License, or     *
+ *   (at your option) any later version.                                   *
+ *                                                                         *
+ ***************************************************************************/
+
+#ifndef QGSSTACKEDWIDGET_H
+#define QGSSTACKEDWIDGET_H
+
+#define SIP_NO_FILE
```
[the remark this answers is not in the document]
Comment (uclaros) [reply src/gui/qgsstackedwidget.h:19]: Should we maybe backport this as is and then expose and expand on a separate PR?

File: src/gui/qgsstackedwidget.h (hunk 1 above)
Comment (nyalldawson) [reply src/gui/qgsstackedwidget.h:37]: There's definitely value in this minimal height stacked widget elsewhere. There's lots of places where we have ugly empty space in dialogs because a stacked widget has forced a too large minimum height for the current page, and all the widgets under that get pushed down for no visible reason.

I'd still push for the enum setting added, because this is kind of our one change to do that and have the default behavior match QStackedWidget. If we need to add other tweaks to QgsStackedWidget in future then things get a bit messier as we'd need to avoid breaking the initial default behaviour.

File: src/gui/qgsstackedwidget.h (hunk 2 above)
[the remark this answers is not in the document]
Comment (nyalldawson) [reply src/gui/qgsstackedwidget.h:19]: I'm ok with that

**Review by nyalldawson — APPROVED** [review]
