### PR TITLE
Fix metal/rough material and fix flat shading

### LINKED ISSUE #55752: 3D Tiles dataset without textures not shaded correctly
### What is the bug or the crash?

When I load swisstopo dataset with 3D buildings, it does not look right in the 3D view:

image

There seem to be two issues:
- some parts of the data may be rendered completely black
- when colors are applied, the shading does not seem to work properly - e.g. roofs should have different shades depending on their orientation (this is likely because we do not calculate normals for gltf data)

### Steps to reproduce the issue

1. create a new 3D Tiles connection with the following URL: https://3d.geo.admin.ch/ch.swisstopo.swisstlm3d.3d/v1/tileset.json
2. open the connection as a tiled scene layer
3. use a background map (e.g. OSM) to zoom in to a town and set project extent just to that extent
4. open 3D view, browse the dataset and you will see issues as decribed above

### Versions

QGIS master

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by wonder-sk**
Commit 1: Move away from using a shader graph in metal/rough material (follow up of https://github.com/qgis/QGIS/pull/55756#issuecomment-1925999763)

The rationale is that it is difficult to update / maintain materials that are based on qt3d's JSON shader graphs - the format is not really documented anywhere and there is no tooling available either.

We are moving to having the whole fragment shader for metal/rough material in a single file, with a couple of #ifdefs that are resolved by GLSL compiler. In QGIS 3D we do only minimal pre-processing, by adding #define lines as needed.

By moving away from shader graphs, we are loosing its support for multiple graphics APIs (GL, GL ES, RHI), but that does not seem like a problem, given that all our other shaders only support OpenGL and not the other APIs.

This also fixes issue where the fragment shader code in `src/3d/shaders/metalrough.frag` was not really being used by the material at all, because the shader graph was pulling code from qt3d's resources.

We are now using QgsMetalRoughMaterial for rendering of 3D Tiles, rather than QMetalRoughMaterial from Qt3DExtras.

---

Commit 2: Add flat shading to metal/rough material

Fixes #55752

It turns out we don't need to build normals on the CPU, which is quite clumsy and complicated (mesh can be indexed or not, and when indexed, one would need to completely rebuild the buffers, because one vertex could appear in different faces with different normals).

The GPU-based solution is actually quite simple: in fragment shader we can use partial derivatives of position to find out normals for flat shading.

Before:

flat-shading-broken

After:

flat-shading-fixed

### CODE REVIEW

File: src/3d/materials/qgsmetalroughmaterial.cpp [hunk 1]
```diff
@@ -39,8 +39,12 @@ QgsMetalRoughMaterial::QgsMetalRoughMaterial( QNode *parent )
   , mMetalRoughGL3Technique( new Qt3DRender::QTechnique() )
   , mMetalRoughGL3RenderPass( new Qt3DRender::QRenderPass() )
   , mMetalRoughGL3Shader( new Qt3DRender::QShaderProgram() )
-  , mMetalRoughGL3ShaderBuilder( new Qt3DRender::QShaderProgramBuilder() )
   , mFilterKey( new Qt3DRender::QFilterKey )
+  , mUsingBaseColorMap( false )
+  , mUsingMetalnessMap( false )
+  , mUsingRoughnessMap( false )
+  , mUsingAmbientOcclusionMap( false )
+  , mUsingNormalMap( false )
```
Comment (nyalldawson) [inline src/3d/materials/qgsmetalroughmaterial.cpp:47]: These can be dropped, they are already set in the header

**Review by nyalldawson — APPROVED** [review]

File: src/3d/materials/qgsmetalroughmaterial.cpp (hunk 1 above)
Comment (nyalldawson) [inline src/3d/materials/qgsmetalroughmaterial.cpp:47]:
```suggestion
```

**Comment by nyalldawson** [comment]
Great move!
