### PR TITLE
Fix WMS connection refresh functionality

### LINKED ISSUE #40350: Layer list of a WMS connection is not refreshed in browser
See https://github.com/qgis/QGIS/issues/39476#issuecomment-734899713

Create a WMS connection

Connect with browser > user see the list of layers

Modify the WMS service (i.e. add a new layer)

Try refresh the connection in browser > new layer do not show

Go to "Add WMS layer" and connect to service

Return to browser and refresh > new layer shows up

Tested on 3.10 and 3.16 on Windows and Linux.

### PR DESCRIPTION
**Pull request by Samweli**
Fixes https://github.com/qgis/QGIS/issues/40350

Ensure the WMS capabilities are refetched when refreshing connection items, this enables to check if there are new 
published layers in the WMS service.

screenshot showing refresh functionality on a WMS connection item using a Qgis server WMS service.
wms_refresh_via_qgis_server

### CODE REVIEW

**Comment by troopa81** [comment]
Maybe I'm missing something but the `mForceRefresh` new boolean is never used in the code to trigger a refresh of capabilities.

A unittest would be great.

**Comment by Samweli** [comment]
> Maybe I'm missing something but the `mForceRefresh` new boolean is never used in the code to trigger a refresh of capabilities.

@troopa81 the `mForceRefresh` is used here https://github.com/qgis/QGIS/blob/543005b67e7a249c2b69a4da6996edbc89e54ee1/src/providers/wms/qgswmscapabilities.cpp#L2331

File: src/providers/wms/qgswmsdataitems.cpp [hunk 1]
```diff
@@ -41,6 +41,12 @@ QgsWMSConnectionItem::~QgsWMSConnectionItem()
   delete mCapabilitiesDownload;
 }
 
+void QgsWMSConnectionItem::refresh()
+{
+  mCapabilitiesDownload->setForceRefresh( true );
+  QgsDataItem::refresh();
+}
```
Comment (nyalldawson) [inline src/providers/wms/qgswmsdataitems.cpp:48]: Shouldn't this flag be cleared after the refresh has occurred?

**Comment by troopa81** [comment]
> @troopa81 the mForceRefresh is used here 

Thanks, I did miss something. I agree with @nyalldawson comment, but in the end, what the advantages of changing the download capabilities status on refresh compared to just initialize it to true when creating the object.

File: src/providers/wms/qgswmsdataitems.cpp (hunk 1 above)
Comment (Samweli) [reply src/providers/wms/qgswmsdataitems.cpp:48]: I had felt it ll be redundant to add the code for clearing the flag since the capabilities will only be fetched through refresh action only.

**Comment by Samweli** [comment]
> what the advantages of changing the download capabilities status on refresh compared to just initialize it to true when creating the object

@troopa81 on refresh the download capabilities object has already been created but we must ensure that the capabilities are refetched.

File: src/providers/wms/qgswmsdataitems.cpp (hunk 1 above)
Comment (Samweli) [reply src/providers/wms/qgswmsdataitems.cpp:48]: ping @nyalldawson

Comment (Samweli) [reply src/providers/wms/qgswmsdataitems.cpp:48]: ping @nyalldawson

**Comment by Samweli** [comment]
ping @nyalldawson

**Comment by timlinux** [comment]
Hi @Samweli I tested here and is working nicely for me.

**Comment by Samweli** [comment]
ping @nyalldawson 

> Hi @Samweli I tested here and is working nicely for me.

thanks @timlinux

File: src/providers/wms/qgswmsdataitems.cpp (hunk 1 above)
Comment (nyalldawson) [reply src/providers/wms/qgswmsdataitems.cpp:48]: Ok, sounds reasonable to me!

**Review by nyalldawson — APPROVED** [review]
