### PR TITLE
Simplify the attachment widget using comboboxes

### LINKED ISSUE #45089: Attachment widget options are reset when you reopen the field widget properties
### What is the bug or the crash?

Both "storage mode" and "Relative paths" buttons are reset to default when you reopen the field widget properties
attachmentcheckboxes

### Steps to reproduce the issue

See above

### Versions

master 3.21

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

I think it's due to some widget visibility checks in https://github.com/qgis/QGIS/commit/b1fa33386f23a40c1863369a836db03510295b2a

### PR DESCRIPTION
**Pull request by DelazJ**
instead of radiobuttons groups.
attachment_old

I tried to rewrite the tooltips on the buttons and would appreciate any feedback
Also this should fix #45089

### CODE REVIEW

File: src/gui/editorwidgets/qgsexternalresourceconfigdlg.cpp [hunk 1]
```diff
@@ -240,22 +247,18 @@ void QgsExternalResourceConfigDlg::setConfig( const QVariantMap &config )
...
-      mRelativeGroupBox->setChecked( false );
-    }
-    else
-    {
-      mRelativeGroupBox->setChecked( true );
-      mRelativeButtonGroup->button( relative )->setChecked( true );
-    }
+
+    if ( ( QgsFileWidget::RelativeStorage )relative == QgsFileWidget::RelativeDefaultPath )
+      enableCbxItem( mStoragePathCbx, 2, true );
```
Comment (troopa81) [inline src/gui/editorwidgets/qgsexternalresourceconfigdlg.cpp:252]: Is this really necessary to enable it here? It should be done when `mRootPath` or `mRootPathExpression` is updated no?

File: src/gui/editorwidgets/qgsexternalresourceconfigdlg.cpp [hunk 2]
```diff
@@ -128,6 +126,21 @@ void QgsExternalResourceConfigDlg::chooseDefaultPath()
     mRootPath->setText( rootName );
 }
 
+void QgsExternalResourceConfigDlg::enableCbxItem( QComboBox *comboBox, int index, bool enabled )
+{
+  // https://stackoverflow.com/a/62261745
+  auto *model = qobject_cast<QStandardItemModel *>( comboBox->model() );
```
Comment (troopa81) [inline src/gui/editorwidgets/qgsexternalresourceconfigdlg.cpp:132]:
```suggestion
  const auto *model = qobject_cast<QStandardItemModel *>( comboBox->model() );
```

**Review by troopa81 — COMMENTED** [review]
It looks like cleaner this way! Thanks

File: src/gui/editorwidgets/qgsexternalresourceconfigdlg.cpp (hunk 1 above)
Comment (DelazJ) [reply src/gui/editorwidgets/qgsexternalresourceconfigdlg.cpp:252]: I think it should. I wanted to be safe (or actually I was unsure of what was happening).
Looking to the code, I can't find what is stored in config when people use mRootPathExpression instead of mRootPath. Am I missing something?

Comment (troopa81) [reply src/gui/editorwidgets/qgsexternalresourceconfigdlg.cpp]: `mRootPathExpression` is related to the data defined property button, it's stored under the data defined property configuration and override the classic configuration mRootPath. 

To sum up, mRootPath and mRootPathExpression target the same config, if one is not null, the relativeDefaultPath should be enabled. and so the signal connection should deal with this.

Comment (DelazJ) [reply src/gui/editorwidgets/qgsexternalresourceconfigdlg.cpp]: Yes, this is what i noticed while testing

**Comment by DelazJ** [comment]
I think every concerns are addressed

**Review by troopa81 — APPROVED** [review]
LGTM
