### PR TITLE
Fix non-default field order in join bys

### LINKED ISSUE #61121: Join-by-nearest can mismatch field names when run in a script/plugin.
### What is the bug or the crash?

See the MWE below.

When the order of `FIELDS_TO_COPY` is different from the order in the input layer, `Field1_2`  now has value `D` (rather than `C`) in the output layer. 

This will not be seen when run through the config dialog because the correct order is enforced, however it can be a problem as part of a script/plugin when used on new input data. Eg, QuickOSM will return fields in different order depending on the exact query.

These appear to be the responsible lines:
 - Field names/indices added in same order as found in the `fieldsToCopy` parameter. Eg, index 2 can be before index 1.
```cpp

for ( const QString &field : fieldsToCopy )
{
  const int index = input2->fields().lookupField( field );
  if ( index >= 0 )
  {
    fields2Indices << index;
    outFields2.append( input2->fields().at( index ) );
  }
}
```
- Attributes (field values) added sequentially. Ie, in same order as found in the input layer.
```cpp

QgsAttributes attributes;
const int attributeCount = f.attributeCount();
for ( int j = 0; j < attributeCount; ++j )
{
  if ( ! fields2Indices.contains( j ) )
    continue;
  attributes << f.attribute( j );
}
input2AttributeCache.insert( f.id(), attributes );
```
https://github.com/qgis/QGIS/blob/master/src/analysis/processing/qgsalgorithmjoinbynearest.cpp

### Steps to reproduce the issue

MWE:

```python
import pandas as pd

# Create a point layer containing a single point
def new_layer(name, attr1, attr2, X, Y):
    layer    = QgsVectorLayer("Point", name, "memory")
    provider = layer.dataProvider()
    provider.addAttributes([QgsField("Field1", QVariant.String), 
                            QgsField("Field2", QVariant.String)])

    newfeat = QgsFeature(layer.fields())
    newfeat.setAttributes([attr1, attr2])

    newfeat.setGeometry(QgsGeometry.fromPoint(QgsPoint(X, Y)))

    provider.addFeature(newfeat)
    layer.updateFields()

    return layer

# Create two layers
layer1 = new_layer("layer1", "A", "B", 0, 0)
layer2 = new_layer("layer2", "C", "D", 1, 1)

# Run join-by-nearest algorithm
fields_to_copy = [['Field1','Field2'], ['Field2','Field1']]
for fields in fields_to_copy:
    alg_params = {'DISCARD_NONMATCHING' : False, 
                  'FIELDS_TO_COPY'      : fields, 
                  'INPUT'               : layer1, 
                  'INPUT_2'             : layer2, 
                  'MAX_DISTANCE'        : None, 
                  'NEIGHBORS'           : 1, 
                  'OUTPUT'              : 'TEMPORARY_OUTPUT', 
                  'PREFIX'              : '' }
    
    joined_layer = processing.run('native:joinbynearest', alg_params)['OUTPUT']
    
    res = {"name" : joined_layer.fields().names(),
           "value" : next(joined_layer.getFeatures())}

    print()
    print({"Input Field Order": fields})
    print(pd.DataFrame(res))
```
Results:
```python
{'Input Field Order': ['Field1', 'Field2']}
        name     value
0     Field1         A
1     Field2         B
2   Field1_2         C
3   Field2_2         D
4          n         1
5   distance  1.414214
6  feature_x       0.0
7  feature_y       0.0
8  nearest_x       1.0
9  nearest_y       1.0

{'Input Field Order': ['Field2', 'Field1']}
        name     value
0     Field1         A
1     Field2         B
2   Field2_2         C
3   Field1_2         D
4          n         1
5   distance  1.414214
6  feature_x       0.0
7  feature_y       0.0
8  nearest_x       1.0
9  nearest_y       1.0
```

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.40.3-Bratislava</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/2a274ab7754">2a274ab7754</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.3</td></tr><tr><td>Python version</td><td>3.10.12</td></tr><tr><td>GDAL/OGR version</td><td>3.4.1</td></tr><tr><td>PROJ version</td><td>8.2.1</td></tr><tr><td>EPSG Registry database version</td><td>v10.041 (2021-12-03)</td></tr><tr><td>GEOS version</td><td>3.10.2-CAPI-1.16.0</td></tr><tr><td>SQLite version</td><td>3.37.2</td></tr><tr><td>PDAL version</td><td>2.3.0</td></tr><tr><td>PostgreSQL client version</td><td>14.15 (Ubuntu 14.15-0ubuntu0.22.04.1)</td></tr><tr><td>SpatiaLite version</td><td>5.0.1</td></td></tr><tr><td>QWT version</td><td>6.1.4</td></tr><tr><td>QScintilla2 version</td><td>2.11.6</td></tr><tr><td>OS version</td><td>Linux Mint 21.3</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>QuickOSM</td><td>2.3.2</td></tr><tr><td>plugin_reloader</td><td>0.17</td></tr><tr><td>GetNameCandidates</td><td>0.1</td></tr><tr><td>processing</td><td>2.12.99</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr></table>

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by roya0045**
## Description

Fixes https://github.com/qgis/QGIS/issues/61121

The original implementation looped through the attribute in order and added the field if it was present in the selectionned fields.

This fix simply takes the listed field in their provided order and added them to the result. This remove the mismatch between the field order and the attributes as mentionned in the issue reported.

This has been changed in both jon by Attribute and Join by Nearest.

### CODE REVIEW

**Comment by roya0045** [comment]
Unrelated test failure.

**Comment by roya0045** [comment]
Hana test failure is unrelated, awaiting review.

**Comment by roya0045** [comment]
Same as previously.

File: src/analysis/processing/qgsalgorithmjoinbyattribute.cpp [hunk 1]
```diff
@@ -191,12 +191,10 @@ QVariantMap QgsJoinByAttributeAlgorithm::processAlgorithm( const QVariantMap &pa
 
     // only keep selected attributes
     QgsAttributes attributes;
-    const int attributeCount = feat.attributeCount();
-    for ( int j = 0; j < attributeCount; ++j )
+    QList<int>::const_iterator fieldItr;
+    for ( fieldItr = fields2Indices.constBegin(); fieldItr != fields2Indices.constEnd(); ++fieldItr )
```
Comment (nyalldawson) [inline src/analysis/processing/qgsalgorithmjoinbyattribute.cpp]:
```suggestion
    for ( int field2Index : fields2Indices )
```

File: src/analysis/processing/qgsalgorithmjoinbyattribute.cpp [hunk 2]
```diff
@@ -191,12 +191,10 @@ QVariantMap QgsJoinByAttributeAlgorithm::processAlgorithm( const QVariantMap &pa
...
     {
-      if ( !fields2Indices.contains( j ) )
-        continue;
-      attributes << feat.attribute( j );
+      attributes << feat.attribute( *fieldItr );
```
Comment (nyalldawson) [inline src/analysis/processing/qgsalgorithmjoinbyattribute.cpp]:
```suggestion
      attributes << feat.attribute( field2Index );
```

File: src/analysis/processing/qgsalgorithmjoinbynearest.cpp [hunk 3]
```diff
@@ -202,12 +202,10 @@ QVariantMap QgsJoinByNearestAlgorithm::processAlgorithm( const QVariantMap &para
 
     // only keep selected attributes
     QgsAttributes attributes;
-    const int attributeCount = f.attributeCount();
-    for ( int j = 0; j < attributeCount; ++j )
+    QList<int>::const_iterator  fieldItr;
+    for ( fieldItr  = fields2Indices.constBegin(); fieldItr != fields2Indices.constEnd(); ++fieldItr )
```
Comment (nyalldawson) [inline src/analysis/processing/qgsalgorithmjoinbynearest.cpp]:
```suggestion
    for ( int field2Index : fields2Indices )
```

File: src/analysis/processing/qgsalgorithmjoinbynearest.cpp [hunk 4]
```diff
@@ -202,12 +202,10 @@ QVariantMap QgsJoinByNearestAlgorithm::processAlgorithm( const QVariantMap &para
...
     {
-      if ( ! fields2Indices.contains( j ) )
-        continue;
-      attributes << f.attribute( j );
+      attributes << f.attribute( *fieldItr );
```
Comment (nyalldawson) [inline src/analysis/processing/qgsalgorithmjoinbynearest.cpp]:
```suggestion
      attributes << f.attribute( field2Index );
```

**Review by nyalldawson — APPROVED** [review]

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
Thanks @roya0045 , looks good!

**Comment by roya0045** [comment]
> Thanks @roya0045 , looks good!

Thanks for the review and merge Nyall!
