### PR TITLE
Make wind barbs face the other way on southern hemisphere

### LINKED ISSUE #57393: Wind barbs for south Hampshire should face the opposite side
### What is the bug or the crash?

With the recent addition of wind barb as a styling option for mesh vectors, the barbs face the wrong direction for the south Hampshire:

image

See: https://en.wikipedia.org/wiki/Station_model#Plotted_winds

Note the ones exactly on the equator should follow the north hemisphere direction.

### Steps to reproduce the issue

- Open QGIS
-  Download [this data set](https://drive.google.com/file/d/1IHDAk0k8g2t1zDzzp7srOiV2NKo3NHgm/view?usp=sharing)
- Unzip and load the data as mesh in QGIS
- Style the wind data using windbarb styling
- Zoom around the equator and you will see the barbs are all facing the same direction both in the north and south

### Versions

3.37

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by uclaros**
## Description
Fixes #57393

### CODE REVIEW

File: src/core/mesh/qgsmeshvectorrenderer.cpp [hunk 1]
```diff
@@ -542,6 +542,8 @@ QgsMeshVectorWindBarbRenderer::QgsMeshVectorWindBarbRenderer(
         context,
         size )
 {
+  const QgsCoordinateReferenceSystem mapCrs = mContext.coordinateTransform().destinationCrs();
+  mMapToWgs = QgsCoordinateTransform( mapCrs, QgsCoordinateReferenceSystem::fromEpsgId( 4326 ), mContext.coordinateTransform().context() );
```
Comment (nyalldawson) [inline src/core/mesh/qgsmeshvectorrenderer.cpp:546]: fromEpgsId should probably be deprecated now, let's go with:

```suggestion
  mMapToWgs = QgsCoordinateTransform( mapCrs, QgsCoordinateReferenceSystem( QStringLiteral("EPSG:4326" ), mContext.coordinateTransform().context() );
```

BUT -- how will this work with non-earth coordinate systems? I'd check the map's crs celestialBodyName before attempting this logic.

Comment (uclaros) [reply src/core/mesh/qgsmeshvectorrenderer.cpp:546]: > fromEpgsId should probably be deprecated now

Ah, I had a deja-vu about using this, I had to check the headers to verify it's not deprecated! Let's deprecate it then!





> BUT -- how will this work with non-earth coordinate systems?

If the transform does not exist or the transformation fails we default to the _North hemisphere_ mode.

Extra-terrestrial meteorologists working on their celestial body's southern hemisphere will be disappointed though...

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
Thanks @uclaros !

I realise the non-earth use case is esoteric, but it IS something i'd like to see us pay more attention to in future.
