### PR TITLE
remove read-only line edit in QgsRelationReferenceWidget

### LINKED ISSUE #42813: Use a read-only line edit instead of combobox in relation reference doesn't allow to add a child from the parent
**Describe the bug**
Use a read-only line edit instead of combobox in relation reference doesn't allow to add a child from the parent

**How to Reproduce**

1. Consider having 2 tables (`parent` and `child`)
2. Create a relation between them (Project - Propreties - Relations)
3. Open propreties of `child` layer and go to the *Attributes Form* panel
4. Set the widget type as *Relation Reference*
5. Check the *Use a read-only line edit instead of combobox*
6. Ok
7. Add a new feature in `parent`
8. When doing this, add a new child feature
9. Bug --> The field of the parent is empty

If in 5. we do not check *Use a read-only line edit instead of combobox*, the 9. is fine (we have the `(id)` of the parent in the field)

**QGIS and OS versions**

```
QGIS version
3.16.5-Hannover
QGIS code revision
58ba7c1ed6
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
actions_for_relations; 
geomapfish_locator; 
quick_map_services; 
db_manager; 
processing
```

### PR DESCRIPTION
**Pull request by 3nids**
keep the read-only config and make the drop-down read-only instead

fixes #42813

### CODE REVIEW

File: tests/src/gui/testqgsrelationreferencewidget.cpp [hunk 1]
```diff
@@ -572,24 +572,6 @@ void TestQgsRelationReferenceWidget::testIdentifyOnMap()
   w.featureIdentified( feature );
   QCOMPARE( w.mComboBox->currentData( Qt::DisplayRole ).toInt(), 10 );
```
Comment (m-kuhn) [inline tests/src/gui/testqgsrelationreferencewidget.cpp:574]:
```suggestion
    w.setReadOnlySelector( true );
    QVERIFY( !w.mComboBox->enabled() );
```

Should we readd a minimal test like this?

**Review by m-kuhn — APPROVED** [review]
