### PR TITLE
Fix use of inline data for SVG content

### LINKED ISSUE #59575: Inline data URIs for SVG markers are not directly supported in QGIS 3.40.x
### What is the bug or the crash?

In Sept. 2020 I found out that we can use inline SVG definitions to define a point marker symbol in QGIS: https://gis.stackexchange.com/questions/374223/using-embedded-svg-symbol-in-multiple-layers

In QGIS 3.36.x it was possible to enter the following data URI in Expression Builder to define a SVG marker:

`'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Layer_1" x="0px" y="0px" viewBox="0 0 100 100" enable-background="new 0 0 100 100" xml:space="preserve" height="100px" width="100px"><path fill="param(fill) #000000" d="M50,2.5c-19.2,0-34.8,15-34.8,33.4C15.2,61.3,50,97.5,50,97.5s34.8-36.2,34.8-61.6  C84.8,17.5,69.2,2.5,50,2.5z M50,48.2c-7.1,0-12.9-5.8-12.9-12.9c0-7.1,5.8-12.9,12.9-12.9c7.1,0,12.9,5.8,12.9,12.9  C62.9,42.4,57.1,48.2,50,48.2z"/></svg>'`

Unfortunately, this no longer works in QGIS 3.40.x.

In QGIS 3.40.x we also need to convert the data URI to base64 to achieve the same effect:

`'base64:'|| to_base64('<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Layer_1" x="0px" y="0px" viewBox="0 0 100 100" enable-background="new 0 0 100 100" xml:space="preserve" height="100px" width="100px"><path fill="param(fill) #000000" d="M50,2.5c-19.2,0-34.8,15-34.8,33.4C15.2,61.3,50,97.5,50,97.5s34.8-36.2,34.8-61.6  C84.8,17.5,69.2,2.5,50,2.5z M50,48.2c-7.1,0-12.9-5.8-12.9-12.9c0-7.1,5.8-12.9,12.9-12.9c7.1,0,12.9,5.8,12.9,12.9  C62.9,42.4,57.1,48.2,50,48.2z"/></svg>')`

QGIS 3.40.x can no longer process inline data URIs for SVG markers directly.

### Steps to reproduce the issue

See bug report.

### Versions

QGIS 3.40.x Windows

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nyalldawson**
Fixes #59575

### CODE REVIEW

File: src/core/qgsabstractcontentcache.cpp [hunk 1]
```diff
@@ -45,15 +45,29 @@ void QgsAbstractContentCacheBase::onRemoteContentFetched( const QString &, bool
 
 bool QgsAbstractContentCacheBase::parseBase64DataUrl( const QString &path, QString *mimeType, QString *data )
 {
-  const thread_local QRegularExpression sRx( QStringLiteral( "^data:(.*/.*?);?(?:base64)?,(.*)$" ) );
+  const thread_local QRegularExpression sRx( QStringLiteral( "^data:([a-zA-Z0-9+]*\\/[a-zA-Z0-9+]*?)(?:;(base64|utf8))?,(.*)$" ) );
```
Comment (troopa81) [inline src/core/qgsabstractcontentcache.cpp:48]: Can we not have dash in the media type like [vnd-example](https://en.wikipedia.org/wiki/Data_URI_scheme)

Comment (nyalldawson) [reply src/core/qgsabstractcontentcache.cpp]: Done

**Review by troopa81 — APPROVED** [review]
