### PR TITLE
fix output fields creation in feature based algorithms (prevent same field names)

### LINKED ISSUE #56940: orientedminimumboundingbox misplaces output when there are duplicate column names
### What is the bug or the crash?

The processing algorithm native:orientedminimumboundingbox creates five additional columns: width, height, angle, area, perimeter and fills each column with a value.
When the original dataset al ready has a column called width, the algorithm does not create a new column width, but does fill each new column with the values in the order which is set in the algorithm.
So the value for width is put in height, the value for height is put in angle, etc, and the value for perimeter has no 5th new column, so is ignored.
There is no error message in the algorithm log.

### Steps to reproduce the issue

create a new scratch vectorlayer polygon with a random field
draw a random polygon
run native:orientedminimumboundingbox
all five new columns have been added in a new temp layer

add to the original scratch layer a new field called width
run native:orientedminimumboundingbox
now only four new columns have been added in a new temp layer and all values have 'shifted'

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.3-Prizren | QGIS code revision | 47373234ac
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.18
GDAL/OGR version | 3.8.3
PROJ version | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.41.1
PDAL version | 2.6.0
PostgreSQL client version | 15.2
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.4
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.34.3-Prizren
QGIS code revision
[47373234ac](https://github.com/qgis/QGIS/commit/47373234ac)
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.3
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ViperMiniQ**
fix: #56940 

see #61713

### CODE REVIEW

File: src/analysis/processing/qgsalgorithmaddincrementalfield.cpp [hunk 1]
```diff
@@ -117,6 +118,12 @@ bool QgsAddIncrementalFieldAlgorithm::prepareAlgorithm( const QVariantMap &param
   mSortAscending = parameterAsBoolean( parameters, QStringLiteral( "SORT_ASCENDING" ), context );
   mSortNullsFirst = parameterAsBoolean( parameters, QStringLiteral( "SORT_NULLS_FIRST" ), context );
 
+  if ( source->fields().lookupField( mFieldName ) >= 0 )
+  {
+    feedback->reportError( QObject::tr( "Field with the same name already exists" ) );
```
Comment (nyalldawson) [inline src/analysis/processing/qgsalgorithmaddincrementalfield.cpp:123]: we should raise the exception here instead, given that it's a fatal error which prevents the algorithm running:

```suggestion
    throw QgsProcessingException( QObject::tr( "Field with the same name already exists" ) );
```

File: src/analysis/processing/qgsalgorithmaddincrementalfield.cpp [hunk 2]
```diff
@@ -117,6 +118,11 @@ bool QgsAddIncrementalFieldAlgorithm::prepareAlgorithm( const QVariantMap &param
   mSortAscending = parameterAsBoolean( parameters, QStringLiteral( "SORT_ASCENDING" ), context );
   mSortNullsFirst = parameterAsBoolean( parameters, QStringLiteral( "SORT_NULLS_FIRST" ), context );
 
+  if ( source->fields().lookupField( mFieldName ) >= 0 )
+  {
+    throw QgsProcessingException( QObject::tr( "Field with the same name already exists" ) );
```
Comment (nyalldawson) [inline src/analysis/processing/qgsalgorithmaddincrementalfield.cpp:123]:
```suggestion
    throw QgsProcessingException( QObject::tr( "A field with the same name (%1) already exists" ).arg( mFieldName ) );
```

File: src/analysis/processing/qgsalgorithmaddtablefield.cpp [hunk 3]
```diff
@@ -121,13 +121,19 @@ QgsFields QgsAddTableFieldAlgorithm::outputFields( const QgsFields &inputFields
...
   const QString name = parameterAsString( parameters, QStringLiteral( "FIELD_NAME" ), context );
   const int type = parameterAsInt( parameters, QStringLiteral( "FIELD_TYPE" ), context );
   const int length = parameterAsInt( parameters, QStringLiteral( "FIELD_LENGTH" ), context );
   const int precision = parameterAsInt( parameters, QStringLiteral( "FIELD_PRECISION" ), context );
   const QString alias = parameterAsString( parameters, QStringLiteral( "FIELD_ALIAS" ), context );
   const QString comment = parameterAsString( parameters, QStringLiteral( "FIELD_COMMENT" ), context );
 
+  if ( source->fields().lookupField( name ) >= 0 )
+  {
+    throw QgsProcessingException( QObject::tr( "Field with the same name already exists" ) );
```
Comment (nyalldawson) [inline src/analysis/processing/qgsalgorithmaddtablefield.cpp:134]:
```suggestion
    throw QgsProcessingException( QObject::tr( "A field with the same name (%1) already exists" ).arg( name ) );
```

**Review by nyalldawson — APPROVED** [review]

**Comment by agiudiceandrea** [comment]
@ViperMiniQ, have you also checked if there are Python `qgis:` algorithms that also add field(s) without using combineFields?

**Comment by agiudiceandrea** [comment]
Great, thanks!

**Comment by agiudiceandrea** [comment]
Just a reminder that manual backports are needed since the automatic ones failed.
