### PR TITLE
Postgres: add ZM to type identification logic

### LINKED ISSUE #43268: Data Source Manager fails to derive exact 3D geometry type for `GeometryZ` PostGIS tables
**Describe the bug**
When adding layers from a PostGIS database, QGIS's Data Source Manager offers multiple items in the list view for relations that contain a variety of geometry types. See the following screenshot for an example:

image

(This time it's a materialized view, hence the warning sign).

However, when the table's geometry column is of type `GeometryZ` (see the excerpt from `geometry_columns` below) QGIS fails to downstream this information into the individual list view items so a 2D geometry type is inferred (e.g. `LineString` instead of `LineStringZ`).

There also seems to be no way to manually change the inferred geometry type (which might be by design).

This is problematic because AFAICT there's no way to add these relations as layers w/ a 3D geometry type.

image

**How to Reproduce**

1. Open the Data Source Manager
2. Connect to a PostGIS database that has a relation w/ a field of type `geometry(GeometryZ, ...)`
3. Observe QGIS offers multiple layers to add (one for each geometry type).
4. Observe QGIS derives 2D geometry types with no clear option to override this behavior.
5. Add any of the above layers, open Layer Properties, observe geometry is 2D.

**QGIS and OS versions**

QGIS version: 3.18.0-Zürich
OS version: macOS 11.1 (20C69)

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #43268

Use https://postgis.net/docs/ST_Zmflag.html to get ZM information.

### CODE REVIEW

File: src/providers/postgres/qgspostgresconn.cpp [hunk 1]
```diff
@@ -2061,9 +2061,27 @@ void QgsPostgresConn::retrieveLayerTypes( QVector<QgsPostgresLayerProperty *> &l
       if ( sridAndTypeString == "NULL" )
         continue;
 
-      QStringList sridAndType = sridAndTypeString.split( ':' );
-      int srid = sridAndType[0].toInt();
+      const QStringList sridAndType = sridAndTypeString.split( ':' );
+      const int srid = sridAndType[0].toInt();
```
Comment (rouault) [inline src/providers/postgres/qgspostgresconn.cpp:2065]: given the complexity of the code that composes the sql statement, it would be prudent to add an assertion that sridAndType.size() == 3

File: src/providers/postgres/qgspostgresconn.cpp [hunk 2]
```diff
@@ -2061,9 +2061,27 @@ void QgsPostgresConn::retrieveLayerTypes( QVector<QgsPostgresLayerProperty *> &l
       if ( sridAndTypeString == "NULL" )
         continue;
 
-      QStringList sridAndType = sridAndTypeString.split( ':' );
-      int srid = sridAndType[0].toInt();
+      const QStringList sridAndType = sridAndTypeString.split( ':' );
```
Comment (elpaso) [inline src/providers/postgres/qgspostgresconn.cpp:2064]:
```suggestion
      const QStringList sridAndType = sridAndTypeString.split( ':' );
      Q_ASSERT(sridAndType.size() == 3);
```

**Comment by elpaso** [comment]
@rouault does this looks ok to you now?

**Review by rouault — APPROVED** [review]
