### PR TITLE
Make Vertex Editor selection render last

### LINKED ISSUE #54034: vertex editor highlight not working on first and last vertex of polygon
### What is the bug or the crash?

The vertex editor highlight vertex with red circle and the selected vertex in the list with blue circles but in the case of polygon features, the first and the last vertex wich have the same coordinates are never highlighted with blue circle. 
The same thing happens when 2 vertex are similar (green cross highlight).
It seems that the red highlight is always over the blue one. 
vertexeditor

### Steps to reproduce the issue

activate vertex tool
right clic on a polygon
clic on the first vertex in the list 

### Versions

tested in 3.20.3  and 3.32.1

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by baswein**
## Description

A proposed solution to #54034 that adds a z order to vertex selection so that a selected vertex is always visible. Also increases the selected vertex size so that overlapping vertices are more obvious when only one is selected. While this is much better than the previous behavior the size change revealed that when vertices are selected using a mouse on the canvas they still draw the unselected vertex style underneath the selected style (as can be seen in this image: 
image ) 
rather than only the selected vertex style like when a vertex is selected in the table
(as can be seen in this image: 
image
). I was not able to figure out how to fix that issue. Open to suggestions. 

Fixes https://github.com/qgis/QGIS/issues/54034

### CODE REVIEW

File: src/app/vertextool/qgsvertextool.cpp [hunk 1]
```diff
@@ -2696,7 +2696,8 @@ void QgsVertexTool::setHighlightedVertices( const QList<Vertex> &listVertices, H
 
     QgsVertexMarker *marker = new QgsVertexMarker( canvas() );
     marker->setIconType( QgsVertexMarker::ICON_CIRCLE );
-    marker->setIconSize( QgsGuiUtils::scaleIconSize( 10 ) );
+    marker->setZValue( marker->zValue() + 1 );
+    marker->setIconSize( QgsGuiUtils::scaleIconSize( 12 ) );
```
Comment (nyalldawson) [inline src/app/vertextool/qgsvertextool.cpp:2700]: I'd drop this change, given the issues you describe with seeing the unhighlighted point marker below the marker anyway. The z value fix looks good on its own.

Comment (baswein) [reply src/app/vertextool/qgsvertextool.cpp]: Sounds good. I reverted it. If in the future I can figure out how to fix the rendering do you think it makes sense to increase the size?

Comment (nyalldawson) [reply src/app/vertextool/qgsvertextool.cpp]: Yes, I like that idea!

**Review by nyalldawson — APPROVED** [review]
