### PR TITLE
Fix group layer rendering

### LINKED ISSUE #52769: Group layer rendering causes incorrect opacity
### What is the bug or the crash?

The opacity of layers in a group renders incorrectly because it appears that all layers in that group are rendered multiple times based on the number of layers in the group. So, as the number of layers in the group increases, the opacity also increases. 

Note: I am not referring to features from one layer in a group overlapping a feature in another layer of the group. Entire layers in a group are affected. So even if you have a feature that does not overlap any feature from any other layer in the group, you will see that the opacity increases, as you add more layers to the group. 

### Steps to reproduce the issue

1. Create a group
2. Change the styling of the group to Render layers as a group
3. Set the opacity to something like 33%
4. Add the first layer to the group.
5. Add another layer to the group (preferably without any overlap between features of the first group so that you can see the opacity change isolated). 
6. Repeat step 5 and see how the opacity of the on screen image is higher for each layer added.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.3-Buenos Aires | QGIS code revision | 65e4edfdada
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.1
PROJ version | 9.1.0
EPSG Registry database version | v10.074 (2022-08-01)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.38.1
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
dms_2_deg | 0.3
FreehandRasterGeoreferencer | 0.8.3
GroupStats | 2.2.6
latlontools | 3.6.7
LayerBoard | 1.0.1
mapswipetool_plugin | 1.2
NNJoin | 3.1.3
pluginbuilder3 | 3.2.1
plugin_reloader | 0.9.3
shapetools | 3.4.9
SpreadsheetLayers | 2.0.1
StreetView | 3.2
db_manager | 0.1.20
processing | 2.12.99

</body></html>QGIS version
3.26.3-Buenos Aires
QGIS code revision
[65e4edfdada](https://github.com/qgis/QGIS/commit/65e4edfdada)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
dms_2_deg
0.3
FreehandRasterGeoreferencer
0.8.3
GroupStats
2.2.6
latlontools
3.6.7
LayerBoard
1.0.1
mapswipetool_plugin
1.2
NNJoin
3.1.3
pluginbuilder3
3.2.1
plugin_reloader
0.9.3
shapetools
3.4.9
SpreadsheetLayers
2.0.1
StreetView
3.2
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by YoannQDQ**
- Fixes #52769

## Description

In `QgsLayerTreeMapCanvasBridge::setCanvasLayers`, if a node was a `QgsGroupLayer` (group with "render as a group" enabled), it was added to the canvas layers for every child layer. So if the group contained 5 layers, the whole group was actually rendered 5 times. 

This PR ensure the QgsGroupLayer is only added once.

Besides, it makes the project dirty when the group styling properties (opacity, blending mode and draw effects) are changed

### CODE REVIEW

File: src/gui/layertree/qgslayertreemapcanvasbridge.cpp [hunk 1]
```diff
@@ -160,7 +160,7 @@ void QgsLayerTreeMapCanvasBridge::setCanvasLayers( QgsLayerTreeNode *node, QList
       if ( QgsGroupLayer *groupLayer = group->groupLayer() )
       {
         canvasLayers << groupLayer;
-        continue;
+        break;
```
Comment (nyalldawson) [inline src/gui/layertree/qgslayertreemapcanvasbridge.cpp:163]: I don't fully understand this fix -- if the child node is a group layer, then the continue here will already ensure that the call to setCanvasLayers on line 166 isn't called. But by using 'break' here then we risk missing nodes (eg a node which contains two child nodes, where the first is a group and the other is just a normal child layer)

Comment (YoannQDQ) [reply src/gui/layertree/qgslayertreemapcanvasbridge.cpp:163]: It's not the child node that is a group ; it's `node` itself. But it could probably be rewritten to just skip the children loop when `node` is a `QgsLayerTreeGroup` (that is linked to a QgsGroupLayer)

Comment (nyalldawson) [reply src/gui/layertree/qgslayertreemapcanvasbridge.cpp:163]: ooooo -- I think the actual bug is that it should be:

```if ( QgsLayerTreeGroup *group = QgsLayerTree::toGroup( child ) )```

Comment (YoannQDQ) [reply src/gui/layertree/qgslayertreemapcanvasbridge.cpp]: Yes, I tried that, it crashed, and I got lazy.  :sweat_smile:

So the problem lies with :

` if ( QgsLayerTreeGroup *group = QgsLayerTree::toGroup( node ) ) `

This does not work to check the validity since `QgsLayerTree::toGroup` performs a static_cast.
This didn't crash before, since this code was reached only if `node` actually had children.

I added a `QgsLayerTree::isGroup` check.

Why not use `dynamic_cast` for `QgsLayerTree::toGroup` and `QgsLayerTree::toLayer` though?

**Review by nyalldawson — APPROVED** [review]
