### PR TITLE
Use a checkbox to create virtual mesh in mesh calculator

### LINKED ISSUE #45246: Harmonize raster and mesh calculators GUI: virtual radiobutton vs checkbox
### What is the bug or the crash?

It could be nice to harmonize the two dialogs since they have a lot in common
image

The "create on the fly raster instead of writing to disk" checkbox has, if I'm not wrong, the same purpose as the mesh "On File/Virtual" buttons. It could be nice to harmonize things here.

### Steps to reproduce the issue

see above

### Versions

master 3.21

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by DelazJ**
instead of current radiobuttons (fixes #45246)
A more explicit label and it mimics the raster calculator dialog

### CODE REVIEW

File: src/app/mesh/qgsmeshcalculatordialog.cpp [hunk 1]
```diff
@@ -354,10 +354,10 @@ void QgsMeshCalculatorDialog::updateInfoMessage()
   }
 }
 
-void QgsMeshCalculatorDialog::onOutputRadioButtonChange()
+void QgsMeshCalculatorDialog::onVirtualCheckboxChange()
 {
-  mOutputDatasetFileWidget->setEnabled( mOutputOnFileRadioButton->isChecked() );
-  mOutputFormatComboBox->setEnabled( mOutputOnFileRadioButton->isChecked() );
+  mOutputDatasetFileWidget->setEnabled( !mUseVirtualProviderCheckBox->isChecked() );
+  mOutputFormatComboBox->setEnabled( !mUseVirtualProviderCheckBox->isChecked() );
```
Comment (DelazJ) [inline src/app/mesh/qgsmeshcalculatordialog.cpp:360]: I'm just disabling these widgets here, following the current behavior but wonder whether I should hide them instead, like in the raster calculator context.

**Review by vcloarec — APPROVED** [review]
