### PR TITLE
Processing: Transect Add fixed distance interval option

### LINKED ISSUE #48663: Transect algorithm - Add option to generate a transect at a fixed distance (ignore existing vertices)
### Feature description

As discussed with @lbartoletti, this algorithm comes from the plugin "[Station lines](https://plugins.qgis.org/plugins/stationlines/)" which create a transect at a fixed distance.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lbartoletti**
## Description

This PR adds a long-awaited option to the transect tool. When converting my old Station Line plugin into QGIS, I had considered that it was possible to densify via processing tools and that this option was unnecessary. Technically, that's true, but it requires too much effort to implement and people continue to use the plugin.
A few years later, here's the complete integration of the plugin into QGIS core. It was integrated for QGIS 3, and it will be before QGIS 4 :rofl: 
@nico, @antonio, would you mind testing this and let me know what might be missing? Thanks

TODO:

- [x] add new tests

Fixes #48663

### CODE REVIEW

**Comment by nyalldawson** [comment]
Rather then adding a new option to the existing algorithm, how about exposing this as a new algorithm "transect (fixed distance)". I'd say thats more inline with the native processing tool philosophy where we try to avoid having options which change behaviour like this in a single tool.

**Comment by nicogodet** [comment]
Works as expected!
The only thing I have to say is the orientation of transect (right to left) which is not the hydraulic convention for river transects. I made this change in the plugin but it might not be possible to do the same here without breaking things or adding complexity...

+1 on Nyall's comment: no useless param if the checkbox is not ticked. From what I learned when designing algo for my company, more simple algorithms with explicit names is better than fewer complex algorithms.

**Comment by lbartoletti** [comment]
OK to write a new algorithm. About the orientation of transect. Is an option acceptable here?

**Comment by nicogodet** [comment]
No strong opinion. If it were just me, yes (with default to current orientation).

**Comment by antonio** [comment]
> @antonio, would you mind testing this and let me know what might be missing?

Wrong Antonio! No worries, it happens quite often. I'm just commenting here so that you're aware and notify the proper person :smile:

**Comment by lbartoletti** [comment]
> > @antonio, would you mind testing this and let me know what might be missing?
> 
> Wrong Antonio! No worries, it happens quite often. I'm just commenting here so that you're aware and notify the proper person 😄

Sorry! Wrong autocompletion :sweat_smile: 

So, cc @antoniolocandro :smile:

**Comment by antoniolocandro** [comment]
can we remove the stale comment and open again? Haven't been able to test but will do. Shame to leave this out.

**Comment by antoniolocandro** [comment]
Please reopen, @lbartoletti this version deactivates all plugins due to the version 3.99 check I think so I can't test.
image

**Comment by antoniolocandro** [comment]
@lbartoletti is this possible to get tested?

**Comment by antoniolocandro** [comment]
This needs to be reopened.

**Comment by lbartoletti** [comment]
@nicogodet, @antoniolocandro (with good nicks this time :stuck_out_tongue: ) , would you mind testing this and let me know what might be missing? Thanks

File: src/analysis/processing/qgsalgorithmtransectbase.cpp [hunk 1]
```diff
@@ -0,0 +1,221 @@
...
+
+    double evaluatedLength = mLength;
+    if ( mDynamicLength )
+      evaluatedLength = mLengthProperty.valueAsDouble( context.expressionContext(), mLength );
+    double evaluatedAngle = mAngle;
+    if ( mDynamicAngle )
+      evaluatedAngle = mAngleProperty.valueAsDouble( context.expressionContext(), mAngle );
+
+    inputGeometry.convertToMultiType();
+    const QgsMultiLineString *multiLine = static_cast<const QgsMultiLineString *>( inputGeometry.constGet() );
```
Comment (nyalldawson) [inline src/analysis/processing/qgsalgorithmtransectbase.cpp]: this isn't a safe assumption -- the geometry may be a curved type. You'd need to segmentize it first to be sure.

(also should be qgsgeometry_cast)

File: src/analysis/processing/qgsalgorithmtransectbase.cpp [hunk 2]
```diff
@@ -0,0 +1,221 @@
...
+
+    for ( int part = 0; part < multiLine->numGeometries(); ++part )
+    {
+      const QgsLineString *lineString = multiLine->lineStringN( part );
+      if ( !lineString )
+        continue;
+
+      QgsLineString line = *lineString;
```
Comment (nyalldawson) [inline src/analysis/processing/qgsalgorithmtransectbase.cpp]: avoid this unnecessary copy -- just pass the const pointer to generateSamplingPoints direct, or derefence it in the call to that function.

File: src/analysis/processing/qgsalgorithmtransectbase.cpp [hunk 3]
```diff
@@ -0,0 +1,221 @@
...
+  QgsPolyline line;
+
+  if ( ( orientation == QgsTransectAlgorithmBase::Right ) || ( orientation == QgsTransectAlgorithmBase::Both ) )
+  {
+    pLeft = point.project( length, angle + 180.0 / M_PI * angleAtVertex );
+    if ( orientation != QgsTransectAlgorithmBase::Both )
+      pRight = point;
+  }
+
+  if ( ( orientation == QgsTransectAlgorithmBase::Left ) || ( orientation == QgsTransectAlgorithmBase::Both ) )
```
Comment (nyalldawson) [inline src/analysis/processing/qgsalgorithmtransectbase.cpp]: use switch here

File: src/analysis/processing/qgsalgorithmtransectfixeddistance.cpp [hunk 4]
```diff
@@ -0,0 +1,99 @@
...
+}
+
+QgsTransectFixedDistanceAlgorithm *QgsTransectFixedDistanceAlgorithm::createInstance() const
+{
+  return new QgsTransectFixedDistanceAlgorithm();
+}
+
+void QgsTransectFixedDistanceAlgorithm::addAlgorithmParams()
+{
+  addParameter( new QgsProcessingParameterNumber( QStringLiteral( "INTERVAL" ), QObject::tr( "Fixed sampling interval" ), Qgis::ProcessingNumberParameterType::Double, 10.0, false, 0 ) );
```
Comment (nyalldawson) [inline src/analysis/processing/qgsalgorithmtransectfixeddistance.cpp]: QgsProcessingParameterDistance

File: src/analysis/processing/qgsalgorithmtransectfixeddistance.cpp [hunk 5]
```diff
@@ -0,0 +1,99 @@
...
+{
+  std::vector<QgsPoint> samplingPoints;
+
+  // Sample points at fixed intervals
+  double totalLength = line.length();
+  for ( double d = 0; d <= totalLength; d += mInterval )
+  {
+    QgsPoint *pt = line.interpolatePoint( d );
+    samplingPoints.push_back( *pt );
+  }
```
Comment (nyalldawson) [inline src/analysis/processing/qgsalgorithmtransectfixeddistance.cpp]: This will be very slow for long lines, as it involves restarting the distance calculation from the start of the line for EVERY interval. 

Use QgsLineString::visitPointsByRegularDistance instead, that's the efficient way to handle this. (and use the processing feedback to handle early cancelation from that function)

File: src/analysis/processing/qgsalgorithmtransectbase.cpp [hunk 6]
```diff
@@ -0,0 +1,221 @@
...
+  length->setDynamicLayerParameterName( QStringLiteral( "INPUT" ) );
+  addParameter( length.release() );
+
+  auto angle = std::make_unique<QgsProcessingParameterNumber>( QStringLiteral( "ANGLE" ), QObject::tr( "Angle in degrees from the original line at the vertices" ), Qgis::ProcessingNumberParameterType::Double, 90.0, false, 0, 360 );
+  angle->setIsDynamic( true );
+  angle->setDynamicPropertyDefinition( QgsPropertyDefinition( QStringLiteral( "ANGLE" ), QObject::tr( "Angle in degrees" ), QgsPropertyDefinition::Double ) );
+  angle->setDynamicLayerParameterName( QStringLiteral( "INPUT" ) );
+  addParameter( angle.release() );
+
+  addParameter( new QgsProcessingParameterEnum( QStringLiteral( "SIDE" ), QObject::tr( "Side to create the transects" ), QStringList() << QObject::tr( "Left" ) << QObject::tr( "Right" ) << QObject::tr( "Both" ), false ) );
```
Comment (nicogodet) [inline src/analysis/processing/qgsalgorithmtransectbase.cpp]: Could we set the default value to "Both" (only GUI to avoid breaking existing model) ?

File: src/analysis/processing/qgsalgorithmtransectbase.cpp [hunk 7]
```diff
@@ -0,0 +1,221 @@
...
+
+  // Allow subclasses to add their specific parameters
+  addAlgorithmParams();
```
Comment (nicogodet) [inline src/analysis/processing/qgsalgorithmtransectbase.cpp]: I would be in favor of moving up this parameter (just below INPUT)

Comment (nicogodet) [reply src/analysis/processing/qgsalgorithmtransectbase.cpp]: As subparam are the purpose of the subalg, they should be moved up, shouldn't they ?

**Comment by antoniolocandro** [comment]
For me this works as expected 👍

**Review by nicogodet — APPROVED** [review]

**Comment by lbartoletti** [comment]
@nyalldawson I have applied all your recommendations. May I ask you to review/approve, please? Thanks

**Comment by lbartoletti** [comment]
@nicogodet I had to do a rebase, and I corrected a rebase error. Can I ask you to do another manual test to make sure everything is working? Tests are OK, and it works for me (c).
I think I've applied all your and @nyalldawson 's requests. If it's OK, I'll merge it within the week.

**Comment by nicogodet** [comment]
Last note: transect orientation which does not follow hydraulic convention.
We had previous discussion about it but I'm OK to merge as it is.

Otherwise, tested OK.

**Comment by lbartoletti** [comment]
> Last note: transect orientation which does not follow hydraulic convention.
> We had previous discussion about it but I'm OK to merge as it is.

Ah, indeed. But it's the same convention since QGIS 3.0 and I didn't want to break the orientation here. 
However. If it's a hard requirement, and it will be for QGIS 4.0. Maybe we can change the orientation.

What do you think?

**Comment by nicogodet** [comment]
We could add a parameter (default to current orientation) but change default GUI value. It would not affect existing scripts/models

**Comment by lbartoletti** [comment]
> We could add a parameter (default to current orientation) but change default GUI value. It would not affect existing scripts/models

OK! So, I suggest merging this PR first. And after, open a new one with this suggestion to separate concerns (one for the transect with distance, one with the new orientation).

**Comment by nicogodet** [comment]
I'm OK with that!
