### PR TITLE
Fix visible state of buttons in the Relation Editor Widget

### LINKED ISSUE #37718: Make more buttons in relation editor configurable
**Feature description.**
It is suggested to make most (all?) buttons configurable (show | don't show) in the relation editor widget:

image

image

This includes:
- Add child feature (important, as in some projects we only want to allow to link/unlink existing features)
- duplicate child feature
- delete child feature
- zoom to child feature

### PR DESCRIPTION
**Pull request by signedav**
`mZoomToFeatureButton` visibility is set on several places and it used to override each other. Same for `mSaveEditsButton` and `mAddFeatureGeometryButton`.

To keep it stable and not being dependent on the order of the setting, it store the configured visibility of buttons in `mButtonsVisibility` and calls `upadteButtons` from `setVisibleButtons`, `setRelation`, `initDualView` and `setEditorContext`.

For `mZoomToFeatureButton` it checks if the flag is set, the editorContexts mapCanvas exists and if the referenced layer of `relation` / the referencing layer of the `nmRelation` is spacial
For `mAddFeatureGeometryButton` it checks the same, but additionally for the existence of `mEditorContext.cadDockWidget()`.

For `mSaveEditsButton` and `mToggleEditingButton` it checks has the member `mLayerInSameTransactionGroup`. This is additionally set correctly according if the parent AND the child are in this group (or with many-to-many relations additionally the "other" parent layer as well).

fixes #37718

### CODE REVIEW

File: src/gui/qgsrelationeditorwidget.cpp [hunk 1]
```diff
@@ -959,14 +945,15 @@ bool QgsRelationEditorWidget::showSaveChildEditsButton() const
...
-  mZoomToFeatureButton->setVisible( buttons.testFlag( QgsAttributeEditorRelation::Button::ZoomToChildFeature ) );
+  mButtons = buttons;
+  mLinkFeatureButton->setVisible( mButtons.testFlag( QgsAttributeEditorRelation::Button::Link ) );
+  mUnlinkFeatureButton->setVisible( mButtons.testFlag( QgsAttributeEditorRelation::Button::Unlink ) );
+  mSaveEditsButton->setVisible( mButtons.testFlag( QgsAttributeEditorRelation::Button::SaveChildEdits ) );
+  mAddFeatureButton->setVisible( mButtons.testFlag( QgsAttributeEditorRelation::Button::AddChildFeature ) );
+  mAddFeatureGeometryButton->setVisible( mButtons.testFlag( QgsAttributeEditorRelation::Button::AddChildFeature ) );
+  mDuplicateFeatureButton->setVisible( mButtons.testFlag( QgsAttributeEditorRelation::Button::DuplicateChildFeature ) );
+  mDeleteFeatureButton->setVisible( mButtons.testFlag( QgsAttributeEditorRelation::Button::DeleteChildFeature ) );
+  mZoomToFeatureButton->setVisible( mButtons.testFlag( QgsAttributeEditorRelation::Button::ZoomToChildFeature ) && mChildIsSpatial );
```
Comment (3nids) [inline src/gui/qgsrelationeditorwidget.cpp:956]:
```suggestion
  mZoomToFeatureButton->setVisible( mButtons.testFlag( QgsAttributeEditorRelation::Button::ZoomToChildFeature ) && mChildIsSpatial && mEditorContext.mapCanvas() );
```

**Review by 3nids — APPROVED** [review]
Looks much cleaner!
What about the check for the map canvas, can it be introduced as proposed?

File: src/gui/qgsrelationeditorwidget.cpp [hunk 2]
```diff
@@ -427,27 +420,18 @@ void QgsRelationEditorWidget::updateButtons()
...
-  );
-
   mZoomToFeatureButton->setEnabled( selectionNotEmpty );
-
   mToggleEditingButton->setChecked( editable );
   mSaveEditsButton->setEnabled( editable );
+
+  mLinkFeatureButton->setVisible( mButtonsVisibility.testFlag( QgsAttributeEditorRelation::Button::Link ) );
+  mUnlinkFeatureButton->setVisible( mButtonsVisibility.testFlag( QgsAttributeEditorRelation::Button::Unlink ) );
+  mSaveEditsButton->setVisible( mButtonsVisibility.testFlag( QgsAttributeEditorRelation::Button::SaveChildEdits ) && mToggleEditingButton->isVisible() );
```
Comment (3nids) [inline src/gui/qgsrelationeditorwidget.cpp:429]:
```suggestion
  mSaveEditsButton->setVisible( mButtonsVisibility.testFlag( QgsAttributeEditorRelation::Button::SaveChildEdits ) && editable );
```

sounds better no?

Comment (3nids) [inline src/gui/qgsrelationeditorwidget.cpp:429]: can't we use another condition that the button visibility?

**Review by 3nids — APPROVED** [review]
nice!

File: src/gui/qgsrelationeditorwidget.cpp (hunk 2 above)
Comment (signedav) [reply src/gui/qgsrelationeditorwidget.cpp:429]: One possibility would be to check if the referencing layer is in the `transactionGroup` but I don't like that it iterates here since it's not really something that changed.

Another possibility would be to set the status in something like `mLayerInTransactionGroup = true` or `mLayerEditable = false` here https://github.com/qgis/QGIS/pull/38678/files#diff-52237b5949ffab9a9049c00ed3a713e1L332 and then check the member variable in the `setVisible`.

What do you think?

Comment (3nids) [reply src/gui/qgsrelationeditorwidget.cpp:429]: yes, let's go for the member, it will make the logic more explicit.

**Review by 3nids — APPROVED** [review]

**Comment by signedav** [comment]
Thanks @3nids
