### PR TITLE
Fix crash when using project on multi point

### LINKED ISSUE #45148: projecting label coordinates for multiPoint geometry crashes QGIS
### What is the bug or the crash?

When using the expression functions "x" / "y" in combination with the function "project(_point,distance,azimuth[,elevation]_)" on a **multiPoint** geometry in order to offset the label's position, QGIS crashes.

### Steps to reproduce the issue

1. find a geopackage "label_issue.gpkg" (500 KB) with data, qml and project file here: https://ablage.qgis.de/index.php/s/ayAYG4js6xmi3BT
2. open the project, there are two layers of identical points: "ap_test_point" with geometry type (single) point and styling and "ap_test_multipoint" of geometry type multiPoint, although there are **no multipart objects**, every feature consists of only one single geometry/part. 
3. on the layer **ap_test_multipoint** set a label with data defined override for the placement of the label coordinates using x and y of the **projected** geometry:
`x ( project ( $geometry, 5, 3.14 ))` remember: `$geometry` is multiPoint here, this works fine with single point geometries. 
4. typing or pasting this expression crahes QGIS immediately. 
(The expression on "ap_test_point" looks like this `x(project($geometry,min(@map_scale*0.04,5), -"S0P0P_SY_ROTATION"))` and would also crash QGIS on the multipoint layer.)

### Versions

QGIS version
3.16.11-Hannover
QGIS code revision
26cc1c762f
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 7 SP 1 (6.1)
Active python plugins
alkisplugin; 
BaSYSPlanApp; 
changeDataSource; 
DataDrivenInputMask; 
DataPlotly; 
DbgBaum; 
dimensioning; 
Discovery; 
EasyTemplatePrint; 
instantprint; 
maplibrary; 
menu_from_project; 
pg_metadata; 
PostNAS_Search; 
qgiscloud; 
xplanung; 
db_manager

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

The given points here represent the connection of sewer pipes, so it does not make sense to be multi. The pipe connections are normaly reperested by the single point where their center lines meet. My solution/workaround therefore is to avoid a useless conversion to multipoint. Having these converted to multipoint was by accident anyway, but reveald the described issue.

I'm mot 100% sure, if the used expression _must_ work on multipoints but none the less is the crash not the best way to let the user know...

Cheers!

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #45148

### CODE REVIEW

File: src/core/expression/qgsexpressionfunction.cpp [hunk 1]
```diff
@@ -4359,7 +4359,7 @@ static QVariant fcnProject( const QVariantList &values, const QgsExpressionConte
 {
   QgsGeometry geom = QgsExpressionUtils::getGeometry( values.at( 0 ), parent );
 
-  if ( geom.type() != QgsWkbTypes::PointGeometry )
+  if ( QgsWkbTypes::flatType( geom.wkbType() ) != QgsWkbTypes::Point )
```
Comment (nyalldawson) [inline src/core/expression/qgsexpressionfunction.cpp:4362]: Would be nice here to check it it's a multipart geometry with a single part only first. You can use QgsAbstractGeometry.simplifiedTypeRef to make this easy

Comment (elpaso) [reply src/core/expression/qgsexpressionfunction.cpp:4362]: But that would require patching https://github.com/qgis/QGIS/blob/master/src/core/geometry/qgspoint.cpp#L759 to avoid hitting https://github.com/qgis/QGIS/blob/master/src/core/geometry/qgspoint.cpp#L49

Do you think it qualifies as a bugfix?

**Comment by uclaros** [comment]
Wouldn't it make sense for this function to apply `project` to each part and return a multipoint?

**Comment by elpaso** [comment]
@uclaros not in this context IMO: how would you get a single coordinate out of a multi point ?

File: src/core/expression/qgsexpressionfunction.cpp (hunk 1 above)
Comment (elpaso) [reply src/core/expression/qgsexpressionfunction.cpp:4362]: @nyalldawson nevermind, I've found a way that doesn't require messing with QgsPoint

**Comment by nyalldawson** [comment]
@elpaso perfect, that's what I had in mind

**Comment by nyalldawson** [comment]
Actually -- better add a check that the geometry is non null there too, otherwise you'll get a crash when trying to retrieve the simplified type

**Comment by uclaros** [comment]
@elpaso I would expect that `project( geom_from_wkt( 'multipoint((1 1), (2 2))' ), 1, 0 )` would return `multipoint((1 2), (2 3))`

**Comment by elpaso** [comment]
> @elpaso I would expect that `project( geom_from_wkt( 'multipoint((1 1), (2 2))' ), 1, 0 )` would return `multipoint((1 2), (2 3))`

That makes sense in general but not in this context where we need a single geometry. Anyway this is a bug fix for a crash: I'm not going to alter the general implementation of the function, feel free to file a feature request it you think it worth it.

**Review by nyalldawson — APPROVED** [review]
