### PR TITLE
[WFS provider] Recognize OGC HTTP URIs

### LINKED ISSUE #29391: QGIS doesn't work properly with WFS 2.0.0 combined with OGC HTTP URI srsName style (e.g. http://www.opengis.net/def/crs/EPSG/0/xxxx)
Author Name: **Jonas Pedersen** (Jonas Pedersen)
Original Redmine Issue: [21575](https://issues.qgis.org/issues/21575)
Affected QGIS version: 3.6.0
Redmine category:web_services_clients/wfs

---
When adding a layer from a Geoserver WFS 2.0.0 serving a layer using the OGC HTTP URI srsName style I get lots and lots of errors. 
It looks as if there are more than one problem involved (e.g. QGIS doesn't recognise the CRS and has you choose one).
But after choosing the correct CRS, the problem manifests itself when checking the box "Only request features overlapping the view extent".
When this box is checked QGIS generates a "GetFeature" request containing a malformed BBOX value as can be seen below:
/am/wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&TYPENAMES=am:ManagementRestrictionOrRegulationZone&COUNT=1000000&BBOX=53,6,58,15,

This BBOX value end with a "," where it should end with the srsName to make it valid - like below:
/am/wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&TYPENAMES=am:ManagementRestrictionOrRegulationZone&COUNT=1000000&BBOX=53,6,58,15,http://www.opengis.net/def/crs/EPSG/0/3044
Apart from that it also seems that the BBOX values for the corners themselves are also a little off (although I'm not sure of this).

For reference, I have pasted the corresponding "GetFeature" request, when the layer is served with the OGC URN srsName style (e.g. urn:ogc:def:crs:EPSG::xxxx):
/am/wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&TYPENAMES=am:ManagementRestrictionOrRegulationZone&COUNT=1000000&SRSNAME=urn:ogc:def:crs:EPSG::3044&BBOX=6013288,254451,6430433,1035230,urn:ogc:def:crs:EPSG::3044
Here the BBOX values for the corners are looks more realistic, and this notation works perfectly in QGIS.

Unfortunately I can't provide access to our Geoserver backend, but let me know if any additional information is needed.

regards,
Jonas

---

- [choose-CRS-for-layer.PNG](https://issues.qgis.org/attachments/download/14574/choose-CRS-for-layer.PNG) (Jonas Pedersen)
- [connect.PNG](https://issues.qgis.org/attachments/download/14575/connect.PNG) (Jonas Pedersen)

### PR DESCRIPTION
**Pull request by rouault**
Fixes #29391

*   Add a QgsOgcCrsUtils::parseCrsName() function to parse the different styles of OGC CRS names
    Recognizes the following flavors:
    ```
        //! CRS flavor
        enum class CRSFlavor
        {
          UNKNOWN, //! unknown/unhandled flavor
          AUTH_CODE, //! e.g EPSG:4326
          HTTP_EPSG_DOT_XML, //! e.g. http://www.opengis.net/gml/srs/epsg.xml#4326 (called "OGC HTTP URL" in GeoServer WFS configuration panel)
          OGC_URN, //! e.g. urn:ogc:def:crs:EPSG::4326
          X_OGC_URN, //! e.g. urn:x-ogc:def:crs:EPSG::4326
          OGC_HTTP_URI, //! e.g. http://www.opengis.net/def/crs/EPSG/0/4326
        };
    ```
*   QgsGmlStreamingParser::readEpsgFromAttribute(): use QgsOgcCrsUtils::parseCrsName()
*   QgsCoordinateReferenceSystem::createFromOgcWmsCrs(): use QgsOgcCrsUtils::parseCrsName()
*   [WFS provider] Use QgsOgcCrsUtils::parseCrsName() to be able to handle OGC HTTP URIs

### CODE REVIEW

File: src/core/qgsogcutils.h [hunk 1]
```diff
@@ -565,6 +565,41 @@ class QgsOgcUtilsSQLStatementToFilter
                          QString &srsName,
                          bool &axisInversion );
 };
+
+/**
+ * \ingroup core
+ * \brief Utilities related to OGC CRS encodings.
+ * \note not available in Python bindings
+ */
+class CORE_EXPORT QgsOgcCRSUtils
```
Comment (elpaso) [inline src/core/qgsogcutils.h:574]: I think that it should be (QT-style)
```suggestion
class CORE_EXPORT QgsOgcCrsUtils
```

File: src/core/qgsogcutils.h [hunk 2]
```diff
@@ -565,6 +565,41 @@ class QgsOgcUtilsSQLStatementToFilter
...
+    /**
+     * Parse a CRS name in one of the flavors of OGC services, and decompose it
+     * as authority and code.
+     *
+     * \param crsName CRS name, like "EPSG:4326", "http://www.opengis.net/gml/srs/epsg.xml#4326", "urn:ogc:def:crs:EPSG::4326", etc.
+     * \param authority[out] CRS authority.
+     * \param code[out] CRS code.
+     * \return CRS flavor (UNKNOWN if crsName could not been parsed.
+     */
+    static CRSFlavor parseCRSName( const QString &crsName, QString &authority, QString &code );
```
Comment (elpaso) [inline src/core/qgsogcutils.h:598]:
```suggestion
    static CrsFlavor parseCrsName( const QString &crsName, QString &authority, QString &code );
```

**Review by elpaso — APPROVED** [review]

File: src/core/qgsogcutils.h (hunk 2 above)
Comment (rouault) [reply src/core/qgsogcutils.h]: done
