### PR TITLE
Fix layout map preview issues on high DPI screens

### LINKED ISSUE #54579: Blurry layouts in v3.32.2, not after v3.28.2
### What is the bug or the crash?

The layout in V3.32.2 appears blurry, but the same layout in V3.28.2 does not.  I've attached the screenshots from same monitor to illustrate the issue.
v3 32 2_blurry
v3 28 2_notblurry

### Steps to reproduce the issue

open equivalent workspaces in 3.28 and 3.31 and compare layouts, I'm viewing mine at 155% magnification. 

### Versions

v3.28.2 and v3.32.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This PR fixes #54579 , another important high DPI issue caused by enabling Qt's auto scaling on high DPI screens. Good to fix before 3.34 becomes the LTR.

Before:
image

After (fixed refresh icon rendering):
image

After (fixed map rendering):
image

### CODE REVIEW

File: src/core/layout/qgslayoutitemmap.cpp [hunk 1]
```diff
@@ -1592,11 +1594,18 @@ void QgsLayoutItemMap::recreateCachedImageInBackground()
   if ( w <= 0 || h <= 0 )
     return;
 
-  mCacheRenderingImage.reset( new QImage( w, h, QImage::Format_ARGB32 ) );
+  double devicePixelRatio = 1.0;
+  if ( QWidget *activeWindow = QApplication::activeWindow() )
```
Comment (nyalldawson) [inline src/core/layout/qgslayoutitemmap.cpp:1598]: Hmm, this is pretty ugly. Can't we get it from the paint device again?

Comment (nirvn) [reply src/core/layout/qgslayoutitemmap.cpp:1598]: We can't from here, we haven't created the painter yet.

Comment (nyalldawson) [reply src/core/layout/qgslayoutitemmap.cpp:1598]: but recreateCachedImageInBackground is always triggered via an initial call to paint -- so we could grab the painter ratio just before calling `mBackgroundUpdateTimer->start( 1 );` and store it for use in recreateCachedImageInBackground

Comment (nirvn) [reply src/core/layout/qgslayoutitemmap.cpp:1598]: @nyalldawson , nice!

**Comment by nirvn** [comment]
@nyalldawson , suggestion implemented, much cleaner.

**Review by nyalldawson — APPROVED** [review]
