### PR TITLE
Fix installation of grid shift files (Fix #48193)

### LINKED ISSUE #48193: Preferred Transformation Not Available / Install Grid Shift File - osgb36_xrail84 - ignores file installation
### What is the bug or the crash?

When changing canvas projection from EPSG:277000 to EPSG:102400 QGIS prompts the user with a Preferred Transformation Not Available dialog. The dialog displays the following message:

The preferred transform between ESRI:102400 - London_Survey_Grid and EPSG:27700 - OSGB36 / British National Grid is not available for use on the system.
This transformation requires the grid file “uk/osgb36_xrail84”, which is not available for use on the system.
Current transform “Inverse of London_Survey_Grid + Ballpark geographic offset from GCS_Xrail84 to OSGB36 + British National Grid” has an unknown accuracy, while the preferred transformation “Inverse of London_Survey_Grid + Inverse of OSGB_1936_To_Xrail84_NTv2 + British National Grid” has accuracy 0.5 meters.

On the same dialog, below the message, within the Install Grid Shift File a button named 'Install uk/osgb36_xrail84 from Folder...'

After pointing to the correct file,  i.e. osgb36_xrail84.gsb , QGIS display the message: The uk/osgb36_xrail84 grid shift file has been successfully installed. Please restart QGIS for this change to take effect.

Restarting QGIS and attempting the same transformation described in the first paragraph above prompts the user with the same identical message as if the installation never happened.

### Steps to reproduce the issue

Soon after QGIS installation the following GSB files need be downloading from UK Ordnance Survey and copied into the appropriate folder:
1. Download:
OSTN02_NTv2.gsb
OSTN15_NTv2_ETRStoOSGB.gsb
OSTN15_NTv2_OSGBtoETRS.gsb
From: https://www.ordnancesurvey.co.uk/business-government/tools-support/os-net/for-developers
Copy into: \\..\QGIS 3.22.4\share\proj\
2. Restart QGIS
3. Change canvas current projection (on-the-fly) to EPSG:27700
4. Change canvas current projection (on-the-fly) to ESRI:102400
5. QGIS displays warning: Cannot use preferred transformation between EPSG:27700 and ESRI:102400
6. On the warning message click 'Details' 
7. QGIS shows the Preferred Transformation Not Available dialog
8. Click Install uk/osgb36_xrail84 from Folder...
9. Find the osgb36_xrail84.GSB file (I can provide this file) and install it.
10. Restart QGIS

Repeating points 3 and 4 should set the ESRI:102400 projection without warning. This is not happening. QGIS is still showing the same warning. When attempting a transformation with data in ESRI:102400 (I can provide) to EPSG:27700 the preferred high accuracy transformation is greyed out and not available. This transformation should be available.

image

The Select Transformation dialog states: This transformation requires the grid file "uk/osgb36_xrail84", which is not available for use on the system" even though it was supposedly installed earlier.

### Versions

QGIS version
3.22.4-Białowieża
QGIS code revision
ce8e65e9
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 1909

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Transformation from EPSG:27700 to EPSG:4326 to ESRI:102400 works correctly. It works vice-versa too.
The transformation from EPSG:27700 to ESRI:102400 and vice-versa does not. Using the only ballpark transformation available results in an inaccuracy of 162m.
This transformation should work using the supplied files including the supposedly installed grid shift... but it doesn't. Instead QGIS behaves as if the file was never installed. I also tried saving the file directly into \\...\QGIS 3.22.4\share\proj\ folder with no success.
Admittedly this is not a very common transformation. Data in ESRI:102400 is used by the London's Crossrail project (Elizabeth line) i.e. not a lot of people, and CAD/GIS people likely using software other than QGIS. However, I can't see no reason why this shouldn't work in QGIS also.

### PR DESCRIPTION
**Pull request by agiudiceandrea**
## Description

Fixes the logic of the installation of grid shift files.

When a missing grid shift file is needed, e.g. `nehpgn.gsb` or `uk/osgb36_xrail84`, then the user is asked to select such grid shift file to be copied in the `proj` folder.

The user could select any file that contains the shifts, e.g. `us_noaa_nehpgn.tif` or `osgb36_xrail84.gsb`.

The current (incorrect) behaviour is to copy the selected file with the very same name (e.g. `us_noaa_nehpgn.tif` or `osgb36_xrail84.gsb`) instead of the expected file name (e.g. `nehpgn.gsb` or `osgb36_xrail84` in the `uk` subfolder) to the proj folder: because of this, the PROJ library cannot find the grid shift file.

The proposed new behaviour is to copy the selected file to the correct expected subfolder of the `proj` dir (and create it if it does not exists) and with the correct expected file name: i.e. it will copy the user selected grid shift file, e.g. `us_noaa_nehpgn.tif` or `osgb36_xrail84.gsb` , the former as `nehpgn.gsb` into the `proj` dir and the latter as `osgb36_xrail84` into the `uk` subfolder of the `proj` dir.

See also https://github.com/qgis/QGIS/issues/45470#issuecomment-939765428.

Fixes https://github.com/qgis/QGIS/issues/48193

### CODE REVIEW

File: src/gui/qgsinstallgridshiftdialog.cpp [hunk 1]
```diff
@@ -62,19 +62,21 @@ void QgsInstallGridShiftFileDialog::installFromFile()
...
-  if ( !QDir( baseGridPath ).exists() )
-    QDir().mkdir( baseGridPath );
 
-  const QString destPath = baseGridPath + '/' + fi.fileName();
+  const QString destFilePath = baseGridPath + '/' + mGridName;
+  const QString destPath = QFileInfo( destFilePath ).absolutePath();
 
-  if ( QFile::copy( gridFilePath, destPath ) )
+  if ( !QDir( destPath ).exists() )
+    QDir().mkdir( destPath );
```
Comment (nyalldawson) [inline src/gui/qgsinstallgridshiftdialog.cpp:70]:
```suggestion
    QDir().mkpath( destPath );
```

**Review by nyalldawson — APPROVED** [review]
