### PR TITLE
Fix regression in legend column assignments

### LINKED ISSUE #42672: Legend: regression in column assignment when changing symbol spacing
Hello,

I made a map that I update regularly with Qgis and I just noticed that with the latest versions of the software there is a change in presentation if I change the space between the symbols in the legend.

I have a caption on two columns and if the value between the symbols goes from 3 to 4 mm some of the text shifts to the right.

**********************************************
Bonjour,

J'ai fait une carte que je mets à jour régulièrement avec Qgis et je viens de remarquer qu'avec les dernières versions du logiciel il y a un changement de présentation si je modifie l'espace entre les symboles dans la légende.

J'ai une légende sur deux colonnes et si la valeur entre les symboles passe de 3 à 4 mm une partie du texte se décale vers la droite.

Example: https://georezo.net/forum/viewtopic.php?id=123303

### PR DESCRIPTION
**Pull request by nyalldawson**
Since https://github.com/qgis/QGIS/pull/39052 there's been a regression in the column assignment of some layout legends, where equal item heights will result in legend placements like:

```
Item 1    Item 2   Item 4
          Item 3
```

This PR repairs the logic, an adds an optimisation step after legend column assignment. This optimisation step is allowed to pack the earlier columns of a legend by shifting items back a column IF doing so results in a more compact legend, where EARLIER columns are more likely to take larger heights vs later columns.

It's limited to run at most twice, in order to avoid doing too much work.

Fixes https://github.com/qgis/QGIS/issues/42672

### CODE REVIEW

**Comment by nyalldawson** [comment]
Not suitable for backporting

File: src/core/qgslegendrenderer.cpp [hunk 1]
```diff
@@ -494,36 +499,53 @@ int QgsLegendRenderer::setColumns( QList<LegendComponentGroup> &componentGroups
...
+    const int numberRemainingGroupsIncludingThisOne = componentGroups.size() - i;
+    const int numberRemainingColumnsIncludingThisOne = numberAutoPlacedBreaks + 1 - autoPlacedBreaks;
+    const int numberRemainingColumnBreaks = numberRemainingColumnsIncludingThisOne - 1;
 
-    int numberRemainingGroups = componentGroups.size() - i;
+    const double averageRemainingSpaceAboveGroups = numberRemainingGroupsIncludingThisOne > 1 ? ( totalRemainingSpaceAboveGroups / ( numberRemainingGroupsIncludingThisOne - 1 ) ) : 0;
+    const double estimatedRemainingSpaceAboveGroupsWhichWontBeUsedBecauseGroupsAreFirstInColumn = numberRemainingColumnBreaks * averageRemainingSpaceAboveGroups;
+    const double estimatedRemainingTotalHeightAfterThisGroup = totalRemainingGroupHeight
+        + totalRemainingSpaceAboveGroups
+        - estimatedRemainingSpaceAboveGroupsWhichWontBeUsedBecauseGroupsAreFirstInColumn;
```
Comment (nirvn) [inline src/core/qgslegendrenderer.cpp:527]: @nyalldawson , isThisTheLongestVariableNameWeHaveInOurSourceTree? :) Joking apart, nice job making the code more readable via variable renaming and use of const.

**Review by nirvn — APPROVED** [review]

File: src/core/qgslegendrenderer.cpp (hunk 1 above)
Comment (nyalldawson) [reply src/core/qgslegendrenderer.cpp:527]: :upside_down_face: in all honesty, I couldn't think of a more concise way to name this would wouldn't result in me having to read this code 100x over again to work out exactly what's happening here!!

Comment (nirvn) [reply src/core/qgslegendrenderer.cpp:527]: Yeah, sometimes you just have to settle for a 78 characters variable name :smile:
