### PR TITLE
[ogr] Fix/enhance SQL queries

### LINKED ISSUE #64069: Bug when displaying the result of an SQL query
### What is the bug or the crash?

When I run an SQL select on a GPKG, the output table does not display all the fields requested in the select and produces inconsistencies.

### Steps to reproduce the issue

Here is a simple SQL query that I want to run on a GPKG.

```sql
SELECT 
    id_branche, 
    nom, 
    id_noeud_amont, 
    id_noeud_aval, 
    st_startpoint(geom) as start_point, 
    st_endpoint(geom) as end_point, 
    geom  
FROM branche;
```

I connect my gpkg to the data sources. I right-click on my GPKG and then click on Run SQL. A window opens and I enter my query.

Résult : 

Image

### Two problems 

- Why does end_point display as WKB while start_point is shown as WKT?

- Why is the geom column not displayed? (I encounter this issue very often, and not only with geometry columns.)

### Executed in the DB Manager

No problems.

Image

### Versions

| Component | Version |
|-----------|---------|
| **QGIS Version** | 3.40.12-Bratislava |
| **Code Revision** | 52f6036b969 |
| **Qt Version** | 5.15.13 |
| **Python Version** | 3.12.3 |
| **GDAL Version** | 3.8.4 |
| **Proj Version** | 9.4.0 |
| **EPSG Registry Database** | v11.004 (2024-02-24) |
| **GEOS Version** | 3.12.1-CAPI-1.18.1 |
| **SQLite Version** | 3.45.1 |
| **PostgreSQL Client Version** | 16.10 (Ubuntu 16.10-0ubuntu0.24.04.1) |
| **SpatiaLite Version** | 5.1.0 |
| **QWT Version** | 6.1.4 |
| **QScintilla2 Version** | 2.14.1 |
| **Operating System** | Ubuntu 24.04.3 LTS |

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Support multiple geometries from SQL like

SELECT st_startpoint(g), g FROM t;

Also: try to respect the order of the fields
specified by the SQL even when it includes
geometries or PKs (that are handled as special
fields by GDAL).

Fix #64069

Funded by: Over The Rainbow 𝄞

### CODE REVIEW

File: src/core/providers/ogr/qgsogrproviderconnection.cpp [hunk 1]
```diff
@@ -80,34 +91,87 @@ QVariantList QgsOgrProviderResultIterator::nextRowInternal()
...
+          {
+            // Emit warning
+            QgsMessageLog::logMessage( QStringLiteral( "Geometry column '%1' not found in layer." ).arg( columnName ), QStringLiteral( "OGR" ), Qgis::MessageLevel::Warning );
+            continue;
+          }
+
+          const OGRGeometryH hGeom { OGR_F_GetGeomFieldRef( fet.get(), colOgrIndex ) };
+          if ( hGeom )
+          {
+            // Suppress warning: Potential leak of memory (wkbData is used to construct the QByteArray from raw data below) [clang-analyzer-cplusplus.NewDeleteLeaks]
```
Comment (rouault) [inline src/core/providers/ogr/qgsogrproviderconnection.cpp]: I don't think the suppression is valid. There is a memory leak. QByteArray::fromRawData doesn't take ownership of wkbData. It just stores the pointer, and that pointer must remain alive while the QByteArray is alive.  A safer approach would be to create a QByteArray with ``QByteArray::QByteArray([qsizetype](https://doc.qt.io/qt-6/qttypes.html#qsizetype-typedef) size, Qt::Initialization)`` constructor, and then pass the raw pointer to OGR_G_ExportToWkb()

Comment (elpaso) [reply src/core/providers/ogr/qgsogrproviderconnection.cpp]: Thank you for checking, I misread the ownership part of the documentation. It should be fine now.

**Review by rouault — APPROVED** [review]

**Comment by rouault** [comment]
I believe the failure in prepare_sip step of pre-commit checks is unrelated to this PR and a flaw of the check itself (I've got such similar error locally on work branches), and so that PR can be safely merged
