### PR TITLE
Fix multiline literal filters in OGR

### LINKED ISSUE #47530: Layer filter does not work on multiline strings values with linebreaks
### What is the bug or the crash?

QGIS pre 3.24 was able to filter features that have string multiline values with linebreaks in them. I tested it with 3.22.

In master it does lead to the filter matching 0 rows.

### Steps to reproduce the issue

1. Download http://lists.fossgis.de/pipermail/fossgis-talk-liste/attachments/20220223/138538b7/attachment.bin and rename it to test.gpkg
2. Load it in QGIS
3. Enter the layer filter dialog
4. List all the values for eigentuemer
5. Add a filter for '"eigentuemer" = <one of the entries displayed with ...>'
6. Apply or test the filter

It will show no features (or display "0 rows").

In QGIS 3.22 this worked (reported by a user on a german FOSSGIS mailing list with 3.24, I can confirm this)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.25.0-Master | QGIS code revision | 4e89cdc5bb4
-- | -- | -- | --

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #47530, followup #45797

### CODE REVIEW

File: src/core/providers/ogr/qgsogrproviderutils.cpp [hunk 1]
```diff
@@ -1352,10 +1352,12 @@ OGRLayerH QgsOgrProviderUtils::setSubsetString( OGRLayerH layer, GDALDatasetH ds
 {
   // Remove any comments
   QStringList lines {subsetString.split( QChar( '\n' ) )};
+
   lines.erase( std::remove_if( lines.begin(), lines.end(), []( const QString & line )
   {
     return line.startsWith( QLatin1String( "--" ) );
   } ), lines.end() );
+
```
Comment (m-kuhn) [inline src/core/providers/ogr/qgsogrproviderutils.cpp:1360]: Just because it jumped my eyes, can you add a `as_const` and `const QString`, in the for loop below?

**Review by m-kuhn — APPROVED** [review]

File: src/core/providers/ogr/qgsogrproviderutils.cpp (hunk 1 above)
Comment (elpaso) [reply src/core/providers/ogr/qgsogrproviderutils.cpp:1360]: Can't be const: line is altered a few lines below.

**Comment by elpaso** [comment]
no need to backport,
