### PR TITLE
[Bug] Display message on overly big images

### LINKED ISSUE #41045: Image export is truncated at 32768 pixels
**Describe the bug**

When exporting a map to an image via *Project > Import/Export > Export Map to Image* with an image dimension larger than 32768 pixels the output is truncated at 32768 pixels.

**How to Reproduce**

1. Load a project
2. Go to *Project > Import/Export > Export Map to Image*
3. Export an image using the dimensions 40,000px width and 1,000px height
4. Open the image in a graphics program

Here's how the result looks for me in Gimp:
image
The expected image stops at 32768 pixels.

I have verified that Gimp can load images wider than 32768 pixels produced using other tools.

I can reproduce the problem both with PNG and TIFF images (haven't tried other formats).

**QGIS and OS versions**

QGIS version | 3.10.4-A Coruña | QGIS code branch | Release QGIS code branch.3
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.2 (Ubuntu 12.2-4) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04.1 LTS
Active python plugins | QuickOSM; processing; db_manager; MetaSearch

### PR DESCRIPTION
**Pull request by roya0045**
Fixes #41045

## Description

This simply adds a message if the output size exceeds the maximum supported size for a qpainter as stated in https://doc.qt.io/qt-5/qpainter.html#limitations .

I'm not sure if this should be added elsewhere. Maybe there could be a workaround to this issue, but as a simple solution, this should prevent any surprises.

### CODE REVIEW

File: src/core/layout/qgslayoutexporter.cpp [hunk 1]
```diff
@@ -292,6 +293,8 @@ QImage QgsLayoutExporter::renderRegionToImage( const QRectF &region, QSize image
   QImage image( QSize( width, height ), QImage::Format_ARGB32 );
   if ( !image.isNull() )
   {
+    if ( ( width * height ) > 32768 )
+      QgsMessageLog::logMessage( QObject::tr( "Error: output is bigger than 32768 pixel, result will be clipped" ) );
```
Comment (nyalldawson) [inline src/core/layout/qgslayoutexporter.cpp:297]: I understand that the limitation is on width OR height, so I think this should be:
```suggestion
    // see https://doc.qt.io/qt-5/qpainter.html#limitations
    if ( width > 32768 || height > 32768 )
      QgsMessageLog::logMessage( QObject::tr( "Error: output width or height is larger than 32768 pixel, result will be clipped" ) );
```

Comment (roya0045) [reply src/core/layout/qgslayoutexporter.cpp:297]: Yeah I wasn't too sure, but I think you're right.

**Review by nyalldawson — APPROVED** [review]
