### PR TITLE
Measure Tool - Disable comma field separator when it is used as decimal separator

### LINKED ISSUE #53814: Measure Tool copy coordinates with comma decimal separator
### What is the bug or the crash?

When the current locale uses `,` as decimal separator, the Measure Tool creates invalid data when it is set to use `,` as field separator. 

Two solutions:

- Quick and dirty : Change decimal separators to `.` when field separator is `,`
- Or probably better: explicitely add a decimal separator setting (either a combobox with two values Use locale (default) & dot, or a simple check box `Always use decimal point`) alongside the other measure tool settings, and prevent user from selecting `,`as a field separator when the locale uses it as decimal separator and the setting is not set to `. (dot)`

### Steps to reproduce the issue

- Override system locale (Settings/general/locale) to use decimal comma (e.g. fr_FR)
- Restart QGIS
- Set the measure tool field separator to Comma (settings/Map Tools/Measure Tool Copy Settings/separator)
- Open the measure dialog, and mesaure a segment
- Click copy
- Data in clipboard uses comma as decimal separator and field separator, making it invalid

### Versions

QGIS version
3.32.0-Lima
QGIS code revision
311a8cb8a65
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.0
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
custom_titlebar
1.0.0
layertreeicons
1.5.3
MemoryLayerSaver
5.0.1
multilayerselect
1.4.1
plugin_reloader
0.9.3
quick_map_services
0.19.33
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by YoannQDQ**
- Fixes #53814 

## Description

This PR adds a new setting in the Measure Tool Copy Settings section

image

When `Always use decimal point` is checked, coordinates are copied to the clipboard with a dot separator, even if the current locale uses a comma.

Besides, if the current locale uses a comma and the checkbox is NOT checked, the comma field separator cannot be selected.

### CODE REVIEW

File: src/app/options/qgsoptions.cpp [hunk 1]
```diff
@@ -2594,6 +2598,19 @@ void QgsOptions::moveLocalizedDataPathDown()
   }
 }
 
+void QgsOptions::alwaysUseDecimalPointChanged( bool checked )
+{
+  // In the Measure Tool copy feature,
+  // comma is only allowed as field separator if the locale do not use it as decimal separator
+  // or if the user has overridden the decimal separator to always be a point
+  mSeparatorComma->setEnabled( checked || QLocale().decimalPoint() != QStringLiteral( "," ) );
```
Comment (elpaso) [inline src/app/options/qgsoptions.cpp:2606]:
```suggestion
  mSeparatorComma->setEnabled( checked || QLocale().decimalPoint() != QChar( ',' ) );
```

I kind of remember this was more efficient but I'm not 100% sure.

File: src/app/qgsmeasuredialog.cpp [hunk 2]
```diff
@@ -721,9 +722,16 @@ double QgsMeasureDialog::convertArea( double area, Qgis::AreaUnit toUnit ) const
 void QgsMeasureDialog::copyMeasurements()
 {
   bool includeHeader = settingClipboardHeader->value();
+  bool alwaysUseDecimalPoint = settingClipboardAlwaysUseDecimalPoint->value();
```
Comment (elpaso) [inline src/app/qgsmeasuredialog.cpp:725]:
```suggestion
  const bool alwaysUseDecimalPoint = settingClipboardAlwaysUseDecimalPoint->value();
```

maybe const?

File: src/app/qgsmeasuredialog.cpp [hunk 3]
```diff
@@ -721,9 +722,16 @@ double QgsMeasureDialog::convertArea( double area, Qgis::AreaUnit toUnit ) const
...
+
 
   // Get the separator
   QString separator = settingClipboardSeparator->value();
+
+  // If the field separator is a comma and the locale uses a comma as decimal separator, change to a semicolon
+  if ( separator == QStringLiteral( "," ) && !alwaysUseDecimalPoint && QLocale().decimalPoint() == QLatin1Char( ',' ) )
```
Comment (elpaso) [inline src/app/qgsmeasuredialog.cpp:732]:
```suggestion
  if ( separator == QLatin1Char( ',' ) && !alwaysUseDecimalPoint && QLocale().decimalPoint() == QLatin1Char( ',' ) )
```

File: src/app/qgsmeasuredialog.cpp [hunk 4]
```diff
@@ -721,9 +722,16 @@ double QgsMeasureDialog::convertArea( double area, Qgis::AreaUnit toUnit ) const
...
+    separator = QStringLiteral( ";" );
```
Comment (elpaso) [inline src/app/qgsmeasuredialog.cpp:733]: QLatin1Char or QChar ?

File: src/app/qgsmeasuredialog.cpp [hunk 5]
```diff
@@ -738,11 +746,20 @@ void QgsMeasureDialog::copyMeasurements()
     text += mTable->headerItem()->text( Columns::Distance ) + QStringLiteral( "\n" );
   }
 
+
+  auto replaceDecimalSeparator = [ alwaysUseDecimalPoint ]( const QString & value ) -> QString
+  {
+    QString result = value;
+    if ( alwaysUseDecimalPoint && QLocale().decimalPoint() != QStringLiteral( "." ) )
```
Comment (elpaso) [inline src/app/qgsmeasuredialog.cpp:753]: consider QLatin1Char or QChar ?

**Review by elpaso — APPROVED** [review]
LGTM, just left a few minor comments.

**Comment by YoannQDQ** [comment]
Thanks for your review @elpaso. 

`QLocale()::decimalPoints()` returns a `QString` in Qt6 build, which caused a compilation error with the following snippet
https://github.com/qgis/QGIS/blob/2db38e3ebe6fb8cfdcdbf8b98316781b0abeba53/src/app/qgsmeasuredialog.cpp#L752-L755

For the sake of consistency, I thought it might be better to use `QStringLiteral` everywhere

**Comment by YoannQDQ** [comment]
@elpaso If you've got no further suggestions, do you mind merging this? Thanks :)

**Comment by YoannQDQ** [comment]
@nyalldawson Could you maybe merge this in master? Thanks!

**Review by nyalldawson — APPROVED** [review]
