### PR TITLE
Fix node tool rectangular selection when layer has a different crs to canvas

### LINKED ISSUE #34591: Selection with Vertex Tool does not work with layers in different reference system than the project
**Describe the bug**
Selection with Vertex Tool does not work with layers in different reference system than the project.

This does not happen in QGIS 3.4.15, where everything works as expected, regardless the OTF being used or not.

**How to Reproduce**

Please see the screencast:

vertex_tool_qgis3102

**QGIS and OS versions**

QGIS version | 3.10.2-A Coruña | QGIS code revision | c932794154
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.0dev | Running against GDAL/OGR | 3.1.0dev
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 7.0.0 | Running against PROJ | Rel. 7.0.0, March 1st, 2020
OS Version | Windows 10 (10.0) | This copy of QGIS writes debugging output.
Active python plugins | BackupLayer; DataPlotly; export_to_sql_server; geoprocAlgos; getools; gml_application_schema_toolbox; go2streetview; GroupStats; HCMGIS; lrs; mmqgis; MultiDistanceBuffer; ntv2_transformations; photo2shape; pointsamplingtool; postgis_geoprocessing; PotentialSlopeFailure; processing_circuitscape; processing_gnm; processing_js; processing_prepair; processing_saga; profiletool; qchainage; Qgis2threejs; qgis2web; QNEAT3; quick_map_services; refFunctions; SemiAutomaticClassificationPlugin; SentinelHub; statist; SwapVectorDirection; timemanager; valuetool; verifica_lotesrp; VoGisProfilTool; db_manager; MetaSearch; processing

### PR DESCRIPTION
**Pull request by nyalldawson**
Fixes #34591

### CODE REVIEW

File: src/app/vertextool/qgsvertextool.cpp [hunk 1]
```diff
@@ -533,7 +533,21 @@ void QgsVertexTool::cadCanvasReleaseEvent( QgsMapMouseEvent *e )
...
+      QgsGeometry layerRubberBandGeometry = rubberBandGeometry;
+      try
+      {
+        QgsCoordinateTransform ct = mCanvas->mapSettings().layerTransform( vlayer );
+        if ( ct.isValid() )
+          layerRubberBandGeometry.transform( ct, QgsCoordinateTransform::ReverseTransform );
+      }
+      catch ( QgsCsException & )
+      {
+      }
```
Comment (m-kuhn) [inline src/app/vertextool/qgsvertextool.cpp]: Does it make sense to continue with the untransformed geometry if an exception happens?

Comment (nyalldawson) [reply src/app/vertextool/qgsvertextool.cpp]: True -- fixed.

**Comment by nyalldawson** [comment]
Unrelated test failure
