### PR TITLE
fix mesh settings contours activation

### LINKED ISSUE #46753: Mesh contour reappears after hiding it in layer properties
### What is the bug or the crash?

When I want to hide the display of a mesh contour using layer properties, it reappears after hitting "Apply" then "OK".
export6

OK from Layer Styling panel

### Steps to reproduce the issue

1. Open meshlayer properties window
2. Disable mesh contour display
3. Hit "Apply" then "OK"

### Versions

3.22.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vcloarec**
fix #46753

### CODE REVIEW

File: src/core/mesh/qgsmeshlayer.cpp [hunk 1]
```diff
@@ -71,7 +71,7 @@ QgsMeshLayer::QgsMeshLayer( const QString &meshLayerPath,
   resetDatasetGroupTreeItem();
   setLegend( QgsMapLayerLegend::defaultMeshLegend( this ) );
 
-  if ( isValid() && options.loadDefaultStyle )
+  if ( isValid() )
```
Comment (nyalldawson) [inline src/core/mesh/qgsmeshlayer.cpp:74]: is this change required to fix the issue? It looks wrong to me -- if we aren't specifying that flag, then it indicates that we'll be manually setting the renderer layer later (or don't care because we'll never render the layer)

Comment (vcloarec) [reply src/core/mesh/qgsmeshlayer.cpp]: yes, that was required, but because there was a little mess with default style...
 Indeed, some confusion between 2 methods for default style since https://github.com/qgis/QGIS/commit/b48d7dcc9fd1e5d0a32ab87f37a17b41fa56d8dc I haven't seen.
Also, I didn't catch/remember the new logic for default style...
With the new commit, it should be OK now.

**Review by nyalldawson — APPROVED** [review]
