### PR TITLE
show warning if float raster is used as input in zonal histogram algorithm (fix #30822)

### LINKED ISSUE #30822: zonal histogram unusable results if input raster has many decimal places
**Describe the bug**
When running "zonal histogram" processing tool, in some cases the output does not contains all the polygons in the layer, but only some of them. 
when I tried t run it again, just keeping one of the polygons that got no values in the layer (now only a single polygon in the layer) I did get an output for this polygon. 
In other data sets I did not encounter any issues. 

**How to Reproduce**

Using the uploaded layers in the zip file: 
[CC_zip.zip](https://github.com/qgis/QGIS/files/3410852/CC_zip.zip)

Get the DEM from the cc_dem_utmm folder and the polygon_UTM.shp . Now run the zonal histogram and save the output to csv. Some of the polygons will have all the values in the histogram set as 0. 

if you delete all polygons but an example that had all zero's and run it again you will get values for this polygon. 

**QGIS and OS versions**

QGIS version | 3.6.0-Noosa | QGIS code revision | 5873452
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
PostgreSQL Client Version | 10.6 (Ubuntu 10.6-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493

This also repredused with this data set on a Windows OS. 

**Additional context**

### PR DESCRIPTION
**Pull request by alexbruy**
## Description

Zonal Histogram algorithm from Processing is not suitable for running against floating point raster values with lots of decimal places and produces output with lots of attributes. 

If user uses a floating-point raster as an input the algorithm will now show a warning and suggest to run Reclassify by table or Round raster tools first.

Fixes #30822.

### CODE REVIEW

**Comment by alexbruy** [comment]
@nirvn what do you think about this, maybe it would be enough just to extend algorithm help without introducing rounding of the input?

**Comment by nirvn** [comment]
@alexbruy , I feel when it comes to float, an histogram doesn't make tons of sense even with rounding. Feels more like they should go through a reclassify by table alg. first to define their bins. Or, as you suggested, rounding (I guess if you'd have a temperature raster, some rounding to 0 decimal could give you some interesting 1-degree breakdown of temperature :) ).

In any case, I am wondering if the proper fix here would simply to through users a warning about float not being friendly to histogram and encourage them to use round raster or reclassify by table algs instead of adding a decimal rounding parameter in this alg. 

I've got no strong feelings about it though, if you do like the parameter approach, I'll +1.

**Comment by alexbruy** [comment]
@nirvn I'm also more in favor of warning, as this is more in line with Processing approach. One can create a model/script if necessary. PR updated to show a warning.

File: src/analysis/processing/qgsalgorithmzonalhistogram.cpp [hunk 1]
```diff
@@ -94,6 +109,12 @@ QVariantMap QgsZonalHistogramAlgorithm::processAlgorithm( const QVariantMap &par
   if ( !zones )
     throw QgsProcessingException( invalidSourceError( parameters, QStringLiteral( "INPUT_VECTOR" ) ) );
 
+  if ( !mIsInteger )
```
Comment (nirvn) [inline src/analysis/processing/qgsalgorithmzonalhistogram.cpp:112]: I'd move that block into prepareAlgorithm() which would remove the need for the mIsInteger member now that we're just warning.,

**Review by nirvn — APPROVED** [review]
