### PR TITLE
Fix QgsInternalGeometryEngine::orientedMinimumBoundingBox

### LINKED ISSUE #47726: Possible bug when calculating oriented minimum bounding box
### What is the bug or the crash?

Calculation of orientedMinimumBoundingBox on some geometries seems incorrect

### Steps to reproduce the issue

1. Run QgsGeometry.fromWkt('MultiPolygon (((-57 -30, -56.5 -30, -56 -30, -55.5 -30, -55.5 -29.6667, -55.5 -29.333, -55.5 -29, -56 -29, -56.5 -29, -57 -29, -57 -29.3333, -57 -29.6666, -57 -30)))').orientedMinimumBoundingBox()
2. Result: (<QgsGeometry: Polygon ((-57 -30, -57 -31.5, -56 -31.5, -56 -30, -57 -30))>, 1.5, 90.0, 1.0, 1.5)
3. Visual interpretation: (blue: original, orange: oriented minimum bbox)
image

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.1-Białowieża | QGIS code revision | 663dcf8fb9
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.0
PROJ version | 8.2.0
EPSG Registry database version | v10.038 (2021-10-21)
GEOS version | 3.10.0-CAPI-1.16.0
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
DsgTools | 4.2.0
gridGenerator | 1.3
plugin_edicao | 0.1
plugin_reloader | 0.8.2
quick_map_services | 0.19.28
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.22.1-Białowieża
QGIS code revision
[663dcf8fb9](https://github.com/qgis/QGIS/commit/663dcf8fb9)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.0
PROJ version
8.2.0
EPSG Registry database version
v10.038 (2021-10-21)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
DsgTools
4.2.0
gridGenerator
1.3
plugin_edicao
0.1
plugin_reloader
0.8.2
quick_map_services
0.19.28
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by agiudiceandrea**
## Description

Fixes a regression introduced with PR https://github.com/qgis/QGIS/pull/42648 since QGIS 3.22.

Fixes https://github.com/qgis/QGIS/issues/47726.

I think this PR needs to be backported to 3.22 and 3.24 branches.

### CODE REVIEW

**Comment by lbartoletti** [comment]
@agiudiceandrea Seems ok, can you add the test `QgsGeometry.fromWkt('MultiPolygon (((-57 -30, -56.5 -30, -56 -30, -55.5 -30, -55.5 -29.6667, -55.5 -29.333, -55.5 -29, -56 -29, -56.5 -29, -57 -29, -57 -29.3333, -57 -29.6666, -57 -30)))').orientedMinimumBoundingBox()` from the issue, please?

File: tests/src/core/geometry/testqgsgeometry.cpp [hunk 1]
```diff
@@ -2183,6 +2183,12 @@ void TestQgsGeometry::orientedMinimumBoundingBox()
   QString resultTestWKT = QStringLiteral( "Polygon ((635.86 -420.08, 552.66 -134.85, 153.5 -251.27, 236.69 -536.51, 635.86 -420.08))" );
   QCOMPARE( result.asWkt( 2 ), resultTestWKT );
 
+  // Issue https://github.com/qgis/QGIS/issues/47726
+  geomTest = QgsGeometry::fromWkt( QStringLiteral( "MultiPolygon (((-57 -30, -56.5 -30, -56 -30, -55.5 -30, -55.5 -29.6667, -55.5 -29.333, -55.5 -29, -56 -29, -56.5 -29, -57 -29, -57 -29.3333, -57 -29.6666, -57 -30)))" ) );
+  result = geomTest.orientedMinimumBoundingBox( );
+  QString resultTestWKT = QStringLiteral( "Polygon ((-57 -30, -55.5 -30, -55.5 -29, -57 -29, -57 -30))" );
```
Comment (agiudiceandrea) [inline tests/src/core/geometry/testqgsgeometry.cpp:2189]:
```suggestion
  resultTestWKT = QStringLiteral( "Polygon ((-57 -30, -55.5 -30, -55.5 -29, -57 -29, -57 -30))" );
```

**Comment by lbartoletti** [comment]
@agiudiceandrea Do you think it's still a draft?

**Comment by agiudiceandrea** [comment]
@lbartoletti many thanks for reviewing!

**Review by lbartoletti — APPROVED** [review]

**Comment by agiudiceandrea** [comment]
@lbartoletti I think this PR needs to be backported to 3.22 and 3.24 branches.
