### PR TITLE
Fix Circle Shape tool when layer crs != map crs

### LINKED ISSUE #38212: Drawing circle yields a diamond when digitizing small feature in a project with a geographic CRS
When drawing very small circle features (~0.1M diameter) qgis creates a diamond, not a circle. Above some critical cutoff, around .25M, the shape becomes a circle. 

To reproduce:
Open a new map. Set CRS to EPSG:4326 if that's not your default. (Problem persists for EPSG:26713 - UTM13, NAD23)
Layer->Create New. I used shapefile but geopackage seems to display the same issue.
Set map scale to 1:10
Select new layer
Toggle editing on
Edit->Add Circle->Add circle by Center and another point
Now draw a very small circle - around .1M

diamonds

Feature rubber bands as a circle, but when you right-click the second point, it changes to a diamond.
Shape remains diamond if you remove the layer and add it back to the map. (I suppose it would be more surprising if they showed up as circles again.) 

Problem seems to occur _only_ if newly created layer is in 4326. Does not occur if the created layer is in 26713

### LINKED ISSUE #38493: 'Add circle from two points' doesn't produce a true circle
**Describe the bug**
this is the shape I get - note the dimples at top and bottom
Screenshot 2020-08-30 at 15 06 54

**How to Reproduce**

Digitise a circle with the 'add circle from two points' tool

**QGIS and OS versions**

QGIS version | 3.14.15-Pi | QGIS code revision | d5114d2cfa
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15
Active python plugins | ORStools; SpreadsheetLayers; lrs; DataPlotly; quick_map_services; stac_browser; Discovery; qfieldsync; qchainage; OSMDownloader; qgis_resource_sharing; openlayers_plugin; Projestions; mmqgis; processing_circuitscape; mapswipetool_plugin; Mergin; travel_time_platform_plugin; nominatim_locator_filter; geocatbridge; timemanager; processing; db_manager; MetaSearch

### LINKED ISSUE #38830: All "Create circle" edits on a 4326 layer (geo crs) in non geo crs projec generate flipped hamburgers buns
I understand this is some projection artifact, but I think we should not create hamburgers when we tell to create circles :-)

Should it not be possible to create circles in a geographic crs layer (project?) maybe?

Or is it that a temporary layer cannot handle arc's? Nope, I saved it as gpkg and it still creates buns

Screenshot-20200917112935-489x502

To reproduce:
- create a clean project in EPSG:28992
- load the layer 'provincies' (provinces) from this wms: https://geodata.nationaalgeoregister.nl/bestuurlijkegrenzen/ows?SERVICE=WMS& so you have some reference
- now create a temporary polygon layer and use 4326 as layer crs, the layer is immidiatly editable
- in menu Edit/Add Circle select one of the ways to create a circe (the all show the same artifact)
- note that DURING the edit the circle shown is perfectly fine

Screenshot-20200917113253-597x538

But AFTER the edit (right mouse button), the circle becomes the flipped hamburger...

When going back to epsg:4326 as project crs the geometries stay 'warped', so it is not *only* projection.

Screenshot-20200917113005-416x373

### LINKED ISSUE #44600: Wrong shape for circles in WGS84 layer
### What is the bug or the crash?

When you draw a circle in WGS84 layer, the final shape drawn is not a circle.
It seems to be an old bug (same problem with QGIS 3.4, 3.10, 3.16).

### Steps to reproduce the issue

See my video attached.
Just draw a circle in a WGS84 layer.

https://user-images.githubusercontent.com/55922863/128487777-42e563cc-b567-4f62-8a9e-0a52373f2532.mp4

### Versions

Version de QGIS
3.16.8-Hannover
Révision du code
8c50902ea4
Compilé avec Qt
5.11.2
Utilisant Qt
5.11.2
Compilé avec GDAL/OGR
3.1.4
Utilisé avec GDAL/OGR
3.1.4
Compilé avec GEOS
3.8.1-CAPI-1.13.3
Utilisé avec GEOS
3.8.1-CAPI-1.13.3
Compilé avec SQLite
3.29.0
Fonctionne avec SQLite
3.29.0
Version du client PostgreSQL
11.5
Version de SpatiaLite
4.3.0
Version de QWT
6.1.3
Version de QScintilla2
2.10.8
Compilé avec PROJ
6.3.2
Fonctionne avec PROJ
Rel. 6.3.2, May 1st, 2020
Version de l'OS
Windows 10 (10.0)
Extensions Python actives
cadastre; 
localiserparcelle; 
SgmDxfImportPro; 
StreetView; 
db_manager; 
MetaSearch; 
processing

### Additional context

_No response_

### LINKED ISSUE #51926: Circle Shape Digitizing tool does not work as expected when map crs != layer crs
Duplicates #38493

### What is the bug or the crash?

When the layer CRS is different from the map canvas crs, the Circle Shape Digitizing tool produces incorrect results.

circle

The Ellipse and polygon tools work as expected though.

### Steps to reproduce the issue

- Create a new project
- (Optionaly add a basemap)
- Set the CRS to EPSG:3857
- Create a new Temporary Scratch Polygon Layer, with EPSG:4326
- Edit the polygon layer
- Display the "Shape Digitizing Toolbar"
- Add a new feature
- In the Shape Digitizing Toolbar, select any of the "Circle" option
- Draw the shape

### Versions

QGIS version
3.29.0-Master
QGIS code revision
994da50a64
Qt version
5.15.3
Python version
3.9.5
Compiled against GDAL/OGR
3.7.0dev-986b841325
Running against GDAL/OGR
3.7.0dev-a828b2b5a9
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

This copy of QGIS writes debugging output.

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by YoannQDQ**
Partially addresses #25167 (reprojection and curve tools are still an issue)
Fixes #38212
Fixes #38493
Fixes #38830
Fixes #44600
Fixes #51926

Many duplicates for this one...

## Description

The Circle Shape digitizing tools use `QgsCircularStrings` to draw the shape on the canvas AND to define the resulting feature in the layer coordinates. The problem is that in layer coordinates, the resulting shape is not always a circle, and `QgsCircularStrings` cannot be used to draw an ellipse. When mixing EPSG:4326 and EPSG:2857 for instance, the tools produces shapes like these:

weird_shape 
weird_shape2

This PR aims to fix this with the following behavior:
- When map crs == layer crs, use QgsCircularStrings to draw the circle (as before)
- When map crs != layer crs, convert the curved geometry to a polygon, using the same number of segments as the ellipse tool.

###  Demonstration
circle_tool

Note the difference between the curved geometries (only 4 vertices) and the polygon geometries (many vertices) at the end of the recording.

### CODE REVIEW

File: src/app/maptools/qgsmaptoolshapecircleabstract.cpp [hunk 1]
```diff
@@ -29,7 +32,19 @@ void QgsMapToolShapeCircleAbstract::addCircleToParentTool()
 
   mParentTool->clearCurve();
 
-  std::unique_ptr<QgsCircularString> lineString( mCircle.toCircularString() );
-
-  mParentTool->addCurve( lineString.release() );
+  // Check whether to draw the circle as a polygon or a circular string
+  auto layerCrs = mParentTool->layer()->crs();
+  auto mapCrs = mParentTool->canvas()->mapSettings().destinationCrs();
```
Comment (nyalldawson) [inline src/app/maptools/qgsmaptoolshapecircleabstract.cpp:37]:
```suggestion
  const QgsCoordinateReferenceSystem layerCrs = mParentTool->layer()->crs();
  const QgsCoordinateReferenceSystem mapCrs = mParentTool->canvas()->mapSettings().destinationCrs();
```

File: src/app/maptools/qgsmaptoolshapecircleabstract.cpp [hunk 2]
```diff
@@ -29,7 +32,19 @@ void QgsMapToolShapeCircleAbstract::addCircleToParentTool()
...
+  bool drawAsPolygon = layerCrs != mapCrs;
```
Comment (nyalldawson) [inline src/app/maptools/qgsmaptoolshapecircleabstract.cpp:38]:
```suggestion
  const bool drawAsPolygon = layerCrs != mapCrs;
```

File: src/app/maptools/qgsmaptoolshapecircleabstract.cpp [hunk 3]
```diff
@@ -29,7 +32,19 @@ void QgsMapToolShapeCircleAbstract::addCircleToParentTool()
...
+  if ( drawAsPolygon )
+  {
+    int segments = QgsSettingsRegistryCore::settingsDigitizingOffsetQuadSeg->value() * 12;
```
Comment (nyalldawson) [inline src/app/maptools/qgsmaptoolshapecircleabstract.cpp:41]:
```suggestion
    const int segments = QgsSettingsRegistryCore::settingsDigitizingOffsetQuadSeg->value() * 12;
```

**Review by nyalldawson — APPROVED** [review]

**Comment by DelazJ** [comment]
You should add Fixes https://github.com/qgis/QGIS/issues/25167 considering that the two others are already closed.

**Comment by YoannQDQ** [comment]
> You should add Fixes #25167 considering that the two others are already closed.

It does not entirely fix it though. This PR is focused on the digitizing tool, but #25167 also mention a similar problem when reprojecting a layer containing Curved geometries. https://github.com/qgis/QGIS/issues/25167#issuecomment-1123119552

**Review by nyalldawson — APPROVED** [review]

File: src/app/maptools/qgsmaptoolshapecircleabstract.cpp [hunk 4]
```diff
@@ -29,7 +32,19 @@ void QgsMapToolShapeCircleAbstract::addCircleToParentTool()
 
   mParentTool->clearCurve();
 
-  std::unique_ptr<QgsCircularString> lineString( mCircle.toCircularString() );
-
-  mParentTool->addCurve( lineString.release() );
+  // Check whether to draw the circle as a polygon or a circular string
+  const QgsCoordinateReferenceSystem layerCrs = mParentTool->layer()->crs();
```
Comment (nyalldawson) [inline src/app/maptools/qgsmaptoolshapecircleabstract.cpp:36]: Note to self -- double check if layer can be nullptr here (I think it can)

Comment (nyalldawson) [reply src/app/maptools/qgsmaptoolshapecircleabstract.cpp:36]: @YoannQDQ before this gets merged to LTR in https://github.com/qgis/QGIS/pull/51945/files, can you add a safety check for the nullptr layer issue?

Comment (YoannQDQ) [reply src/app/maptools/qgsmaptoolshapecircleabstract.cpp:36]: @nyalldawson Do you want me to close #51945 and manually open another backport PR? Not quite sure how to do it otherwise.

Comment (nyalldawson) [reply src/app/maptools/qgsmaptoolshapecircleabstract.cpp:36]: @YoannQDQ if you open a pr against master for just the layer nullptr change, then I'll merge the existing backport and then immediately the new backport after.

Comment (YoannQDQ) [reply src/app/maptools/qgsmaptoolshapecircleabstract.cpp:36]: Done
