### PR TITLE
Fixes layer reprojection with curve geometries

### LINKED ISSUE #25167: Circular string doesn't honor the coordinate system
Author Name: **Loïc BARTOLETTI** (@lbartoletti)
Original Redmine Issue: [17269](https://issues.qgis.org/issues/17269)
Affected QGIS version: 3.5(master)
Redmine category:digitising

---
Problem found by Nyall "reviewing":https://github.com/qgis/QGIS/pull/4947#issuecomment-335291640 the new tools for Circle,etc. and reproduce by me in 2.18

Well, when you draw a circular string in a layer with a geographical system (eg WGS84) and a map in projected system (eg EPGS:3946), the circular arc is drawn in is system.

See the video.

---

- [circular.mp4](https://issues.qgis.org/attachments/download/11543/circular.mp4) (Loïc BARTOLETTI)

### PR DESCRIPTION
**Pull request by YoannQDQ**
Fixes #25167 (conjointly with #51943 and #51931)

## Description

When reprojecting a layer containing curved geometries (`native:reprojectlayer`), the curves appear distorted.
This PR fix the issue by converting the geometries to straight segments prior to applying the transformation.

### Before
reproject_bug

### After
reproject_fix

### CODE REVIEW

**Comment by baswein** [comment]
@YoannQDQ - Thanks for tackling this problem. I'm wondering if we could make this conversion a setting in the advanced properties. I am often switching between US state plane coordinate systems. For example from the Massachusetts state plane in Meters to the Ma state plane in Feet. When the doing this the distortion is minimal (I measured it at .000395m for a 100000m diameter circle). In that case I would rather keep the curve geometries especially at the town or site level scales I am often working at. Even when going from MA state plane (EPSG 26986) to the US NAD83(NSRS2007) / Conus Albers (EPSG 5072) the distortion is only 1.9m for a 100000m circle.

**Comment by YoannQDQ** [comment]
> I'm wondering if we could make this conversion a setting in the advanced properties

Good idea.

**Comment by baswein** [comment]
I'm wondering if the default for Keep Geometries as Curves should be True. This has been the behavior since curves were introduced to QGIS. Making it false will result in changes to what people are currently used to and expecting even if this means that their results will continue to be distorted. But I can be convinced either way Accuracy vs Expectations.

**Comment by YoannQDQ** [comment]
I'm afraid that new QGIS users will never see the advanced parameters and will not understand why reprojecting their layer from/to epsg:4326 does not work. On the other hand, old time users that need their geometries to remain curves and disregard the minor distortion in their specific usecase will probably find the parameter more easily.

**Comment by baswein** [comment]
I think users will experience this as not working either way. If they are reprojecting a layer with curves they will expect curves on the other end and those curves to be in the right place. We can only give them one of those things but at least now they have the choice. From that perspective you are probably right that defaulting towards accuracy is the right choice.

**Comment by nyalldawson** [comment]
> wondering if the default for Keep Geometries as Curves should be True

+1 for this -- otherwise it's an effective API break which may impact existing plugins and user models

File: src/analysis/processing/qgsalgorithmtransform.cpp [hunk 1]
```diff
@@ -107,6 +115,12 @@ QgsFeatureList QgsTransformAlgorithm::processFeature( const QgsFeature &f, QgsPr
   if ( feature.hasGeometry() )
   {
     QgsGeometry g = feature.geometry();
+
+    if ( !mKeepCurvedGeometries )
```
Comment (nyalldawson) [inline src/analysis/processing/qgsalgorithmtransform.cpp:119]: Shouldn't we only do this if the crs IS changed? While it may seem silly to use the transform algorithm for no crs change, a processing model may include this step as a way of gauranteeing that any input is always in a particular crs.

**Review by nyalldawson — APPROVED** [review]
