### PR TITLE
Fix interpolated line rendering when no feature is present

### LINKED ISSUE #45028: Interpolated line symbol layers are broken when applied to layout polyline items as well as line annotations
### What is the bug or the crash?

Any symbol's interpolated line layer will fail to render anything when used with a layout polyline item or a line annotation. 

### Steps to reproduce the issue

1. Create a new layout
2. Add a polyline item
3. Edit its symbol, set the symbol layer to 'interpolated line'
4. Notice it failing

### Versions

QGIS 3.20, QGIS master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nyalldawson**
Fixes #45028, and cleans up/simplifies some related code

### CODE REVIEW

File: src/core/symbology/qgsinterpolatedlinerenderer.cpp [hunk 1]
```diff
@@ -903,6 +903,11 @@ QgsSymbolLayer *QgsInterpolatedLineSymbolLayer::create( const QVariantMap &prope
   return symbolLayer.release();
 }
 
+Qgis::SymbolLayerFlags QgsInterpolatedLineSymbolLayer::flags() const
+{
+  return Qgis::SymbolLayerFlag::DisableFeatureClipping;
```
Comment (nirvn) [inline src/core/symbology/qgsinterpolatedlinerenderer.cpp:867]: @nyalldawson , nice idea -- it'd be useful/needed for the arrow symbol layer too.

**Review by nirvn — APPROVED** [review]

**Comment by nirvn** [comment]
@nyalldawson , tested, working _great_ with annotations:
image
