### PR TITLE
JSON fields: logic to guess widget type

### LINKED ISSUE #57673: JSON-String not read from GPKG
### What is the bug or the crash?

I converted a DXF file to GPKG using ogr2ogr. Some block attributes are written to the field BlockAttributes (layer entities). According to ogrinfo (see below), the key-value-pairs are set correctly. Reading the GPKG in QGIS, I see an empty String ("") instead of the (JSON) value.

### Steps to reproduce the issue

1. Download example DXF file https://github.com/OSGeo/gdal/blob/master/autotest/ogr/data/dxf/attrib.dxf
2. Convert DXF to GPKG using `ogr2ogr --config DXF_INLINE_BLOCKS FALSE -f "GPKG" C:/Users/sgr/Downloads/attrib.gpkg "C:/Users/sgr/Downloads/attrib.dxf"`
3. See BlockAttributes value set at first feature of layer entities using `ogrinfo C:/Users/sgr/Downloads/attrib.gpkg entities -geom=no`
4. Also see the field type String(JSON)
5. Load GPKG file in QGIS
6. Open attribute table of layer "attrib — entities"
7. Field BlockAttributes has type JSON, but the value is not set

### Versions

QGIS-Version
3.36.3-Maidenhead
QGIS-Codeversion
2df96554
Qt-Version
5.15.13
Python-Version
3.12.3
GDAL-Version
3.9.0
PROJ-Version
9.4.0
EPSG-Registraturdatenbankversion
v11.004 (2024-02-24)
GEOS-Version
3.12.1-CAPI-1.18.1
SQLite-Version
3.45.1
PDAL-Version
2.6.3
PostgreSQL-Client-Version
16.2
SpatiaLite-Version
5.1.0
QWT-Version
6.2.0
QScintilla2-Version
2.14.1
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Fix #57673 
by trying to examine the first not-null record and check if it's a valid JSON key/value or a JSON array

### CODE REVIEW

File: src/gui/editorwidgets/qgskeyvaluewidgetfactory.cpp [hunk 1]
```diff
@@ -43,5 +43,41 @@ QgsEditorConfigWidget *QgsKeyValueWidgetFactory::configWidget( QgsVectorLayer *v
 unsigned int QgsKeyValueWidgetFactory::fieldScore( const QgsVectorLayer *vl, int fieldIdx ) const
 {
   const QgsField field = vl->fields().field( fieldIdx );
+  if ( field.type() == QMetaType::Type::QVariantMap && ( field.typeName().compare( QStringLiteral( "JSON" ), Qt::CaseSensitivity::CaseInsensitive ) == 0 || field.subType() == QMetaType::Type::QString ) )
+  {
+    // Fetch the first not-null value and check if it is really a map
+    QgsFeatureRequest req;
+    req.setFlags( Qgis::FeatureRequestFlag::NoGeometry );
+    req.setSubsetOfAttributes( { fieldIdx } );
+    req.setFilterExpression( QStringLiteral( R"("%1" IS NOT NULL)" ).arg( field.name() ) );
```
Comment (rouault) [inline src/gui/editorwidgets/qgskeyvaluewidgetfactory.cpp:52]: proper identifier escaping should likely be done for robustness. Same in other files.

I'm also wondering about if doing such feature request could not be sometimes problematic, thinking in particularly to slow datasources like WFS / OGC API Features, where if you are unlucky, it could result in pure client-side evaluation, and ingesting the whole layer if the field appends to be empty.

Comment (elpaso) [reply src/gui/editorwidgets/qgskeyvaluewidgetfactory.cpp:52]: That's a good point. I'll check if there is a way to limit this logic to datasources that don't have this problem.

Comment (elpaso) [reply src/gui/editorwidgets/qgskeyvaluewidgetfactory.cpp]: @rouault I couldn't find a capability for that, I changed the logic to NOT do the filtering and just examine the first 20 features (stopping at the first NOT NULL one).

**Review by rouault — APPROVED** [review]
