### PR TITLE
Fix xyz tile matrix zoom level above 22

### LINKED ISSUE #28987: xyz tile matrix error for zoom max levels above 22
Author Name: **Jean Weber** (Jean Weber)
Original Redmine Issue: [21169](https://issues.qgis.org/issues/21169)
Affected QGIS version: 3.4.4
Redmine category:web_services_clients/xyz

---
xyz tiles are not rendered for zoom levels above 22. The problem is a wrong tile matrix for zoom levels above 22.
for zoom min = 20 and zoom max= 24 I have tile matrix properties as shown on the picture attached hereafter:

---

- [tilematrix.jpg](https://issues.qgis.org/attachments/download/14239/tilematrix.jpg) (Jean Weber)

### PR DESCRIPTION
**Pull request by fguiotte**
## Description

Fix for issue #28987 where XYZ Tiles do not work above zoom level 22. The culprit was an integer overflow in a multiplication, now implemented in double. 

Screenshot from 2022-03-24 15-07-42

Screenshot from 2022-03-24 15-15-56

There are still some strange behaviours when maxZoom is greater than 30, it seems to be a core limitation:

https://github.com/qgis/QGIS/blob/883d31dbc05353f60f91d1ea2e61de61b5d38fb6/src/core/qgstiles.cpp#L47

This limit could be hard-coded right here: 

https://github.com/qgis/QGIS/blob/883d31dbc05353f60f91d1ea2e61de61b5d38fb6/src/providers/wms/qgswmsprovider.cpp#L1690

But it may be better to handle this in the UI: 

Screenshot from 2022-03-24 15-02-02

Fixes #28987

### CODE REVIEW

File: src/providers/wms/qgswmsprovider.cpp [hunk 1]
```diff
@@ -1701,7 +1701,7 @@ void QgsWmsProvider::setupXyzCapabilities( const QString &uri, const QgsRectangl
     tm.topLeft = topLeft;
     tm.tileWidth = tm.tileHeight = 256 * tilePixelRatio;
     tm.matrixWidth = tm.matrixHeight = 1 << zoom;
-    tm.tres = xspan / ( tm.tileWidth * tm.matrixWidth );
+    tm.tres = xspan / ( ( double ) tm.tileWidth * tm.matrixWidth );
```
Comment (nyalldawson) [inline src/providers/wms/qgswmsprovider.cpp:1704]: Does this work instead?

```suggestion
    tm.tres = xspan / ( static_cast< qgssize >( tm.tileWidth ) * tm.matrixWidth );
```

Comment (fguiotte) [reply src/providers/wms/qgswmsprovider.cpp]: Yes, it works.

**Review by nyalldawson — APPROVED** [review]
