### PR TITLE
fix vectorlayer 3D entity generation by filtering duplicates

### LINKED ISSUE #50971: Exporting 3D scene to .obj stores the same feature 16x
### What is the bug or the crash?

I made a 3D scene containing a layer with only one polygon. When exporting this to .obj (and .mtl) the obj contains the same 3D-object 16 times.

image

### Steps to reproduce the issue

* Create a polygon scratch layer
* Draw one polygon and save
* Set layer's 3D View settings to height: 0, extrude: 20
* Open 3D View
* Save scene with default options

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.29.0-Master | QGIS code revision | 5fe715a6c3
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.6
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.1 LTS
  |   |   |  
Active Python plugins
BGTImport | 3.16
ImaerPlugin | version 3.2.0
pdokservicesplugin | 4.1.2
grassprovider | 2.12.99
MetaSearch | 0.3.6
sagaprovider | 2.12.99
db_manager | 0.1.20
processing | 2.12.99
StreetView | 3.2

</body></html>QGIS version
3.29.0-Master
QGIS code revision
[5fe715a6c3](https://github.com/qgis/QGIS/commit/5fe715a6c3)
Qt version
5.15.3
Python version
3.10.6
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.1 LTS

Active Python plugins
BGTImport
3.16
ImaerPlugin
version 3.2.0
pdokservicesplugin
4.1.2
grassprovider
2.12.99
MetaSearch
0.3.6
sagaprovider
2.12.99
db_manager
0.1.20
processing
2.12.99
StreetView
3.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitdm-oslandia**
This PR follow #53063 

The feature selection, in `QgsVectorLayerChunkLoader`, was made according to the intersection of the current quadtree node and the feature geometry. For all features with geometry across quadtree nodes, the geometries were duplicated  inducing memory and cpu degradations. This fix uses the previous filter (bbox intersection) then filters according to the geometry centroid.

closes #50971 

### Old version

Capture d’écran du 2023-03-13 15-50-12

A feature is included in multiple quadtree nodes. We use 1064 primitives in 18 geometries.
If we export the scene and import it into **Blender** we obtain 14 full objects (11 duplicates):

Capture d’écran du 2023-03-13 16-19-37

### New version

Capture d’écran du 2023-03-13 15-55-47

Features across multiple quadtree nodes are clipped in the node bbox. We use 838 primitives in 18 geometries.

If we export the scene and import it into **Blender** we obtain 14 partial objects (one per quadtree node). The only duplicated faces are those created by the walls when the geometry is clipped:

Capture d’écran du 2023-03-13 16-23-36

## Computation time

To do this test, I use a bigger project with 57000 features (from a Geopackage) with QGIS built in release.

I add a `QElapsedTimer` to monitor the time (I will remove it before the merge). 

### Old version

Capture d’écran du 2023-03-13 15-54-04

Log extract: 

```raw

new 3D view map

Warning: Logged warning: ========================== job timer restarted!
Warning: Logged warning: Job took: 81ms
Warning: Logged warning: Job took: 228ms
Warning: Logged warning: Job took: 3317ms

new 3D view map

Warning: Logged warning: ========================== job timer restarted!
Warning: Logged warning: Job took: 38ms
Warning: Logged warning: Job took: 58ms
Warning: Logged warning: Job took: 90ms
Warning: Logged warning: Job took: 2205ms

new 3D view map

Warning: Logged warning: ========================== job timer restarted!
Warning: Logged warning: Job took: 17ms
Warning: Logged warning: Job took: 65ms
Warning: Logged warning: Job took: 2895ms

new 3D view map

Warning: Logged warning: ========================== job timer restarted!
Warning: Logged warning: Job took: 9ms
Warning: Logged warning: Job took: 30ms
Warning: Logged warning: Job took: 95ms
Warning: Logged warning: Job took: 2327ms
```

`(3317+2205+2895+2327)÷4 ~= 2686ms` for 3672934 primitives ==> 0,73µs per primitives.

### New version 

Capture d’écran du 2023-03-13 15-57-53

Log extract: 

```
new 3D view map

Warning: Logged warning: ========================== job timer restarted!
Warning: Logged warning: Job took: 88ms
Warning: Logged warning: Job took: 182ms
Warning: Logged warning: Job took: 3116ms

new 3D view map

Warning: Logged warning: ========================== job timer restarted!
Warning: Logged warning: Job took: 9ms
Warning: Logged warning: Job took: 42ms
Warning: Logged warning: Job took: 79ms
Warning: Logged warning: Job took: 2120ms

new 3D view map

Warning: Logged warning: ========================== job timer restarted!
Warning: Logged warning: Job took: 25ms
Warning: Logged warning: Job took: 29ms
Warning: Logged warning: Job took: 36ms
Warning: Logged warning: Job took: 2775ms

new 3D view map

Warning: Logged warning: ========================== job timer restarted!
Warning: Logged warning: Job took: 22ms
Warning: Logged warning: Job took: 43ms
Warning: Logged warning: Job took: 71ms
Warning: Logged warning: Job took: 2170ms
```

`(3116+2120+2775+2170)÷4 ~= 2545ms` ==> for 3299502 primitives ==> 0,77µs per primitive

We lost ~5% in speed and we gain ~11,3% in primitive count.

The main gain is we have no more geometry duplicates.

### CODE REVIEW

**Comment by nyalldawson** [comment]
> feature is included in only one quadtree node

Wouldn't this mean that features will become invisible as soon as the node containing their centroid out of view? (Even if other nodes containing part of the geometry are still visible)

**Comment by benoitdm-oslandia** [comment]
> Wouldn't this mean that features will become invisible as soon as the node containing their centroid out of view? (Even if other nodes containing part of the geometry are still visible)

Yes, exactly!

**Comment by nyalldawson** [comment]
@benoitdm-oslandia isn't that a regression? Objects will disappear unexpectedly from the edge of views as a 3d map is navigated....

**Comment by uclaros** [comment]
@benoitdm-oslandia also, keep in mind to perform any benchmarking on the optimized release build, as the debug build can have significantly different results!

**Comment by benoitdm-oslandia** [comment]
You were right! It was more obvious for concave geometries. 

I rework my PR by clipping the 2D polygon with the bbox of the current chunk node. Only the used part is kept in the chunk node entity. There is no more duplicate but the clipping increase by a little (17µs per geom) the rendering time.

I will push some perf stats on monday.

**Comment by benoitdm-oslandia** [comment]
@uclaros @nyalldawson can you please have a look?

**Comment by uclaros** [comment]
I'm not sure I like the idea of clipping on the chunk extents. The seams will be visible when rendering edges is enabled.
If the only problem with the currently duplicated primitives is exporting, then would it be possible to implement some fid based filtering when exporting (I've no clue about the exporting code) to avoid exporting the same fid twice?

On another note, I _love_ the tidying up and setting of objectNames! That will help debugging and exploring the scene in Gammaray!
I'd suggest you wrap those unrelated fixes in a separate PR

**Comment by benoitdm-oslandia** [comment]
> I'm not sure I like the idea of clipping on the chunk extents. The seams will be visible when rendering edges is enabled.

Yes indeed. 

> If the only problem with the currently duplicated primitives is exporting, then would it be possible to implement some fid based filtering when exporting (I've no clue about the exporting code) to avoid exporting the same fid twice?

From the exporting function pov the only known objects are the `QEntity` objects obtained by the `createEntity` function of a `chunkLoader`. These Qt entities do not have any fid field. 

1. solution would be to create a base object `Qgs3DFeatureEntity` (inheriting `QEntity`) and change every `chunkLoader` logic to handle the new object and assign fid. 

2. solution would be to use the composition design already available to the `QEntity` and add a new component (with fid) to each `QEntity`. But we will need to change every `chunkLoader` logic to handle the component.

3. solution would be to add a dynamic property to the `QEntity` with the fid and again to change every `chunkLoader` logic to handle the property.

IMHO the 2. and 3. solution are prone to error due to the need to think (or to forget) to add the property or the component. 1. solution in another hand, by changing the `chunkLoader` signature can force to add the fid.

But this is a *big* change just to filter objects during export.

**Comment by wonder-sk** [comment]
One more issue with the current clipping approach is that it is likely not going to work with polygons that are not horizontal (this is common with city models, for example with roofs) - as far as I know, GEOS only does the operations in 2D.

By the way, in the PR, expected_polygon3d_extrusion_opacity.png seems to have a visible horizontal shift compared to the original image - is that correct?

The de-duplication of features in export should be doable with the current implementation - for the purposes of the identify tool, we keep a data structure to understand what triangles map to what feature ID (for tessellated polygon geometries), so this data structure could be used for de-duplication too.

A proper solution would be nice to have for the 3D view too - for solid objects it's all fine, but semi-transparent objects on tile boundaries may be drawn more solid due to the duplication. Apart from the original approach with one feature being only in one tile, and the current approach with clipping, I can imagine a third approach - entities for tiles would only contain features fully inside, and the features spanning more than one tile would be rendered on special "shared" entities which would be enabled whenever adjacent entity gets enabled. That approach would solve all the issues: edge highlighting, semi-transparent objects and export.

**Comment by benoitdm-oslandia** [comment]
@uclaros @nyalldawson can you review please?

**Comment by uclaros** [comment]
@benoitdm-oslandia please try to avoid force-pushing as it makes others lose track of what has happened.
If you need to rebase you can merge master instead and if you need to come up with a completeley different approach (as in this case) you can either revert the unwanted commits, or even better open a separate PR.
All this time I thought this PR was still using the clipping approach!

**Comment by benoitdm-oslandia** [comment]
In fact, I rarely change the approach 3 times in a row to obtain something stable. I will create separated PR next time!

**Comment by benoitdm-oslandia** [comment]
@uclaros @vcloarec can you review this PR please?

**Comment by lbartoletti** [comment]
@uclaros @vcloarec I'll merge the PR next week if there's no feedback by then.

File: src/3d/qgs3dsceneexporter.cpp [hunk 1]
```diff
@@ -523,7 +525,63 @@ QVector<Qgs3DExportObject *> Qgs3DSceneExporter::processSceneLoaderGeometries( Q
...
 {
   // We only export triangles for now
-  if ( geomRenderer->primitiveType() != Qt3DRender::QGeometryRenderer::Triangles ) return nullptr;
+  if ( geomRenderer->primitiveType() != Qt3DRender::QGeometryRenderer::Triangles )
+    return nullptr;
+
+  Qt3DQGeometry *geometry = geomRenderer->geometry();
+
+  // TODO: TO REMOVE
+  qDebug() << "============= Will export geom" << geomRenderer->parent()->objectName();
```
Comment (uclaros) [inline src/3d/qgs3dsceneexporter.cpp:534]: Do remove all those qDebugs, or use some large QgsDebugMsgLevel

File: src/3d/qgs3dsceneexporter.cpp [hunk 2]
```diff
@@ -669,14 +755,23 @@ void Qgs3DSceneExporter::save( const QString &sceneName, const QString &sceneFol
 
   QFile file( objFilePath );
   if ( !file.open( QIODevice::WriteOnly | QIODevice::Text | QIODevice::Truncate ) )
+  {
+    QgsDebugMsgLevel( QStringLiteral( "Scene can be exported to '%1'. File access error." ).arg( objFilePath ), 1 );
```
Comment (uclaros) [inline src/3d/qgs3dsceneexporter.cpp:759]: This is an error, you can use `QgsDebugError()`
Also, 'scene _cannot_ be exported'...

File: src/3d/qgs3dsceneexporter.cpp [hunk 3]
```diff
@@ -669,14 +755,23 @@ void Qgs3DSceneExporter::save( const QString &sceneName, const QString &sceneFol
...
     return;
+  }
   QFile mtlFile( mtlFilePath );
   if ( !mtlFile.open( QIODevice::WriteOnly | QIODevice::Text | QIODevice::Truncate ) )
+  {
+    QgsDebugMsgLevel( QStringLiteral( "Scene can be exported to '%1'. File access error." ).arg( mtlFilePath ), 1 );
```
Comment (uclaros) [inline src/3d/qgs3dsceneexporter.cpp:765]: same

File: src/3d/qgs3dsceneexporter.cpp [hunk 4]
```diff
@@ -523,7 +525,63 @@ QVector<Qgs3DExportObject *> Qgs3DSceneExporter::processSceneLoaderGeometries( Q
...
+      }
+      else
+      {
+        // keep the feature triangle indexes
+        uint startIdx = triangleIndex[idx];
+        uint endIdx = std::numeric_limits<uint>::max();
+        if ( idx < triangleIndex.size() - 1 )
+          endIdx = triangleIndex[idx + 1];
+        // TODO: TO REMOVE
+        qDebug() << "==== Exclude feature '" << feat << "' from idx" << startIdx << "to" << endIdx;
```
Comment (uclaros) [inline src/3d/qgs3dsceneexporter.cpp:574]: This else case is only for debugging, right? Either remove or guard in ifdefs

File: src/3d/qgs3dsceneexporter.cpp [hunk 5]
```diff
@@ -565,11 +622,40 @@ Qgs3DExportObject *Qgs3DSceneExporter::processGeometryRenderer( Qt3DRender::QGeo
     positionData = getAttributeData<float>( positionAttribute, vertexBytes );
   }
 
-//   For tessellated polygons that don't have index attributes
+  // For tessellated polygons that don't have index attributes
   if ( positionAttribute != nullptr && indexAttribute == nullptr )
   {
-    for ( int i = 0; i < positionData.size() / 3; ++i )
-      indexData.push_back( i );
+    for ( uint i = 0; i < ( uint ) positionData.size() / 3; ++i )
```
Comment (uclaros) [inline src/3d/qgs3dsceneexporter.cpp:628]: Can you avoid the c style casts in this method?
Maybe adding temporary variables would help as static_casts sometimes make expressions look too long.

**Review by uclaros — COMMENTED** [review]
:+1: The fid monitoring is a nice solution!

Is the exporting functionality tested? Maybe you could add a test case for filtering the duplicate fids?

File: src/3d/symbols/qgspolygon3dsymbol_p.cpp [hunk 6]
```diff
@@ -110,8 +110,10 @@ bool QgsPolygon3DSymbolHandler::prepare( const Qgs3DRenderContext &context, QSet
   return true;
 }
 
-void QgsPolygon3DSymbolHandler::processPolygon( QgsPolygon *polyClone, QgsFeatureId fid, float height, float extrusionHeight, const Qgs3DRenderContext &context, PolygonData &out )
+void QgsPolygon3DSymbolHandler::processPolygon( const QgsPolygon *poly, QgsFeatureId fid, float height, float extrusionHeight, const Qgs3DRenderContext &context, PolygonData &out )
 {
+  QgsPolygon *polyClone = poly->clone();
```
Comment (nyalldawson) [inline src/3d/symbols/qgspolygon3dsymbol_p.cpp:115]:
```suggestion
  std::unique_ptr< QgsPolygon > polyClone( poly->clone() );
```

File: src/3d/qgs3dsceneexporter.cpp (hunk 2 above)
Comment (benoitdm-oslandia) [reply src/3d/qgs3dsceneexporter.cpp:759]: done

File: src/3d/symbols/qgspolygon3dsymbol_p.cpp [hunk 7]
```diff
@@ -182,17 +185,16 @@ void QgsPolygon3DSymbolHandler::processFeature( const QgsFeature &f, const Qgs3D
   if ( hasDDExtrusion )
     extrusionHeight = ddp.valueAsDouble( QgsAbstract3DSymbol::PropertyExtrusionHeight, context.expressionContext(), extrusionHeight );
 
-  if ( const QgsPolygon *poly = qgsgeometry_cast< const QgsPolygon *>( g ) )
+  if ( QgsPolygon *poly = qgsgeometry_cast< QgsPolygon *>( g ) )
   {
-    QgsPolygon *polyClone = poly->clone();
-    processPolygon( polyClone, f.id(), height, extrusionHeight, context, out );
+    processPolygon( ( const QgsPolygon * )poly, f.id(), height, extrusionHeight, context, out );
```
[the remark this answers is not in the document]
Comment (benoitdm-oslandia) [reply src/3d/symbols/qgspolygon3dsymbol_p.cpp:190]: fixed

File: src/3d/qgs3dsceneexporter.cpp (hunk 4 above)
Comment (benoitdm-oslandia) [reply src/3d/qgs3dsceneexporter.cpp:574]: indeed! Removed!

File: src/3d/qgs3dsceneexporter.cpp (hunk 5 above)
Comment (benoitdm-oslandia) [reply src/3d/qgs3dsceneexporter.cpp:628]: done!

File: src/3d/qgs3dexportobject.cpp [hunk 8]
```diff
@@ -144,11 +145,13 @@ void Qgs3DExportObject::saveTo( QTextStream &out, float scale, const QVector3D &
...
   }
-  int verticesCount = mVertexPosition.size() / 3;
+  int verticesCount = mIndexes.size();
 
+  // we use negative indexes as this is the way to use relative values to reference vertex positions
+  // Positive values are absolute vertex position from the beginning of the file.
   auto getVertexIndex = [&]( int i ) -> QString
   {
-    const int negativeIndex = -1 - ( verticesCount - i );
+    const int negativeIndex = - ( verticesCount - i ) - ( int )mIndexes[0]; // mIndexes[0] is used to shift the index according to the first index (not always 0)
```
[the remark this answers is not in the document]
Comment (benoitdm-oslandia) [reply src/3d/qgs3dexportobject.cpp:154]: I don't really know if there is some wanted design in using uint but I did minimal refactor to handle uint

File: src/3d/symbols/qgspolygon3dsymbol_p.cpp (hunk 6 above)
Comment (benoitdm-oslandia) [reply src/3d/symbols/qgspolygon3dsymbol_p.cpp:115]: done !

**Comment by uclaros** [comment]
@benoitdm-oslandia did you forget to push? :grin:

**Comment by benoitdm-oslandia** [comment]
> @benoitdm-oslandia did you forget to push? 😁

Too many people at home to be efficient :)

**Comment by benoitdm-oslandia** [comment]
please @nyalldawson, @lbartoletti or @troopa81, can I have a review?

**Comment by benoitdm-oslandia** [comment]
@nyalldawson @uclaros can you review please?

File: src/3d/qgs3dexportobject.cpp [hunk 9]
```diff
@@ -117,8 +117,9 @@ void Qgs3DExportObject::saveTo( QTextStream &out, float scale, const QVector3D &
     out << "s off\n";
 
   // Construct vertices
-  for ( int i = 0; i < mVertexPosition.size(); i += 3 )
+  for ( const unsigned int vertice : mIndexes )
   {
+    const int i = ( int ) vertice * 3;
```
Comment (nyalldawson) [inline src/3d/qgs3dexportobject.cpp:122]:
```suggestion
    const int i = static_cast< int >( vertice * 3 );
```

File: src/3d/symbols/qgspolygon3dsymbol.cpp [hunk 10]
```diff
@@ -170,24 +170,27 @@ void QgsPolygon3DSymbol::setMaterialSettings( QgsAbstractMaterialSettings *mater
...
   {
     const QList<Qt3DRender::QGeometryRenderer *> renderers = entity->findChildren<Qt3DRender::QGeometryRenderer *>();
+    int startSize = exporter->mObjects.size();
     for ( Qt3DRender::QGeometryRenderer *renderer : renderers )
     {
       Qgs3DExportObject *object = exporter->processGeometryRenderer( renderer, objectNamePrefix );
-      if ( object == nullptr ) continue;
-      exporter->processEntityMaterial( entity, object );
-      exporter->mObjects.push_back( object );
+      if ( object != nullptr )
```
Comment (nyalldawson) [inline src/3d/symbols/qgspolygon3dsymbol.cpp:181]:
```suggestion
      if ( object )
```

File: src/3d/qgsvectorlayerchunkloader_p.cpp [hunk 11]
```diff
@@ -132,6 +134,7 @@ Qt3DCore::QEntity *QgsVectorLayerChunkLoader::createEntity( Qt3DCore::QEntity *p
   }
 
   Qt3DCore::QEntity *entity = new Qt3DCore::QEntity( parent );
+  entity->setObjectName( mFactory->mLayer->name() + "_" + mNode->tileId().text() );
```
Comment (nyalldawson) [inline src/3d/qgsvectorlayerchunkloader_p.cpp:137]: I don't think it's safe to access mLayer here -- I would store the name as a member string in the QgsVectorLayerChunkLoader constructor and use that here.

File: src/3d/qgstessellatedpolygongeometry.h [hunk 12]
```diff
@@ -108,6 +108,18 @@ class QgsTessellatedPolygonGeometry : public Qt3DCore::QGeometry
...
+    QVector<QgsFeatureId> featureIds() const { return mTriangleIndexFids; }
+
+    //! Returns triangle index for features. For a feature featureIds()[i], matching triangles start at triangleIndexStartingIndices()[i]
+    QVector<uint> triangleIndexStartingIndices() const { return mTriangleIndexStartingIndices; }
+
+    /**
+     * Tests whether the geometry is intersected by \a ray.
+     * In case of success, the \a intersectionPoint and the corresponding \a fid are updated.
+     */
+    bool rayIntersection( const QgsRayCastingUtils::Ray3D &ray, const QMatrix4x4 &worldTransform, QVector3D &intersectionPoint, QgsFeatureId &fid );
```
Comment (nyalldawson) [inline src/3d/qgstessellatedpolygongeometry.h:121]: I think this is a result of a bad merge conflict fix -- it shouldn't be re added here

File: src/3d/qgs3dsceneexporter.cpp [hunk 13]
```diff
@@ -242,17 +245,15 @@ void Qgs3DSceneExporter::processEntityMaterial( Qt3DCore::QEntity *entity, Qgs3D
     const Qt3DRender::QTexture2D *diffuseTexture = diffuseMapMaterial->diffuse().value< Qt3DRender::QTexture2D * >();
     if ( diffuseTexture != nullptr )
     {
-      const QVector<Qt3DRender::QAbstractTextureImage *> textureImages = diffuseTexture->textureImages();
-      QgsImageTexture *imageTexture = nullptr;
-      for ( Qt3DRender::QAbstractTextureImage *tex : textureImages )
+      for ( const Qt3DRender::QAbstractTextureImage *tex : diffuseTexture->textureImages() )
```
Comment (nyalldawson) [inline src/3d/qgs3dsceneexporter.cpp:248]: can you leave the previous approach of storing the images in a const list first? Otherwise we'll get a detachment of the qt container and consequent clazy warnings.

File: src/3d/qgs3dsceneexporter.cpp [hunk 14]
```diff
@@ -514,7 +515,8 @@ QVector<Qgs3DExportObject *> Qgs3DSceneExporter::processSceneLoaderGeometries( Q
   {
     Qt3DRender::QGeometryRenderer *mesh = qobject_cast<Qt3DRender::QGeometryRenderer *>( sceneLoader->component( entityName, Qt3DRender::QSceneLoader::GeometryRendererComponent ) );
     Qgs3DExportObject *object = processGeometryRenderer( mesh, objectNamePrefix, sceneScale, sceneTranslation );
-    if ( object == nullptr ) continue;
+    if ( object == nullptr )
```
Comment (nyalldawson) [inline src/3d/qgs3dsceneexporter.cpp:518]:
```suggestion
    if ( !object )
```

**Comment by nyalldawson** [comment]
Just some very minor changes from my end, otherwise all looks good!

File: src/3d/qgs3dexportobject.cpp (hunk 9 above)
Comment (benoitdm-oslandia) [reply src/3d/qgs3dexportobject.cpp:122]: fixed

File: src/3d/symbols/qgspolygon3dsymbol.cpp (hunk 10 above)
Comment (benoitdm-oslandia) [reply src/3d/symbols/qgspolygon3dsymbol.cpp:181]: fixed

File: src/3d/qgstessellatedpolygongeometry.h (hunk 12 above)
Comment (benoitdm-oslandia) [reply src/3d/qgstessellatedpolygongeometry.h:121]: indeed!

File: src/3d/qgs3dsceneexporter.cpp (hunk 14 above)
Comment (benoitdm-oslandia) [reply src/3d/qgs3dsceneexporter.cpp:518]: fixed

**Comment by benoitdm-oslandia** [comment]
@nyalldawson I have squashed the history too. Let me know!

File: src/3d/qgsvectorlayerchunkloader_p.cpp (hunk 11 above)
Comment (benoitdm-oslandia) [reply src/3d/qgsvectorlayerchunkloader_p.cpp:137]: I need to check that

Comment (benoitdm-oslandia) [reply src/3d/qgsvectorlayerchunkloader_p.cpp]: I made the fix but I do not understand the issue when using `mFactory->mLayer`! Can you explain me?

Comment (nyalldawson) [reply src/3d/qgsvectorlayerchunkloader_p.cpp]: Create entity is called after the job is finished, and there's a chance that the layer has been deleted in the meantime...

File: tests/src/3d/testqgs3drendering.cpp [hunk 15]
```diff
@@ -1691,7 +1696,7 @@ void TestQgs3DRendering::testDebugMap()
   mapSettings.setLightSources( {defaultPointLight.clone() } );
   mapSettings.setOutputDpi( 92 );
 
-  // =========== creating Qgs3DMapScene
+//  // =========== creating Qgs3DMapScene
```
Comment (uclaros) [inline tests/src/3d/testqgs3drendering.cpp:1699]:
```suggestion
 // =========== creating Qgs3DMapScene
```

File: tests/src/3d/testqgs3drendering.cpp [hunk 16]
```diff
@@ -168,7 +173,7 @@ QImage TestQgs3DRendering::convertDepthImageToGray16Image( const QImage &depthIm
   return grayImage;
 }
 
-//runs before all tests
+////runs before all tests
```
Comment (uclaros) [inline tests/src/3d/testqgs3drendering.cpp:176]:
```suggestion
// runs before all tests
```

File: src/3d/symbols/qgspolygon3dsymbol.cpp [hunk 17]
```diff
@@ -170,24 +170,27 @@ void QgsPolygon3DSymbol::setMaterialSettings( QgsAbstractMaterialSettings *mater
 
 bool QgsPolygon3DSymbol::exportGeometries( Qgs3DSceneExporter *exporter, Qt3DCore::QEntity *entity, const QString &objectNamePrefix ) const
 {
-  const QList<Qt3DCore::QEntity *> entities = entity->findChildren<Qt3DCore::QEntity *>( QString(), Qt::FindDirectChildrenOnly );
-  if ( entities.isEmpty() )
+  const QList<Qt3DCore::QEntity *> subEntities = entity->findChildren<Qt3DCore::QEntity *>( QString(), Qt::FindDirectChildrenOnly );
+  if ( subEntities.isEmpty() )
   {
     const QList<Qt3DRender::QGeometryRenderer *> renderers = entity->findChildren<Qt3DRender::QGeometryRenderer *>();
+    int startSize = exporter->mObjects.size();
```
Comment (uclaros) [inline src/3d/symbols/qgspolygon3dsymbol.cpp:177]:
```suggestion
    const int startSize = exporter->mObjects.size();
```

File: src/3d/qgs3dsceneexporter.cpp [hunk 18]
```diff
@@ -565,11 +606,42 @@ Qgs3DExportObject *Qgs3DSceneExporter::processGeometryRenderer( Qt3DRender::QGeo
...
+
+  if ( triangleIndexStartingIndiceToKeep.empty() )
+  {
+    indexData.append( indexDataTmp );
+  }
+  else
+  {
+    int intervalIdx = 0;
+    int triangleIndexStartingIndiceToKeepSize = triangleIndexStartingIndiceToKeep.size();
+    uint indexDataTmpSize = static_cast<uint>( indexDataTmp.size() );
```
Comment (uclaros) [inline src/3d/qgs3dsceneexporter.cpp:626]:
```suggestion
    const int triangleIndexStartingIndiceToKeepSize = triangleIndexStartingIndiceToKeep.size();
    const uint indexDataTmpSize = static_cast<uint>( indexDataTmp.size() );
```

File: src/3d/qgs3dsceneexporter.cpp [hunk 19]
```diff
@@ -523,7 +526,46 @@ QVector<Qgs3DExportObject *> Qgs3DSceneExporter::processSceneLoaderGeometries( Q
...
+    {
+      QgsFeatureId feat = featureIds[idx];
+      if ( ! mExportedFeatureIds.contains( feat ) )
+      {
+        // add the feature as it was unknown
+        mExportedFeatureIds.insert( feat );
+
+        // keep the feature triangle indexes
+        uint startIdx = triangleIndex[idx];
+        uint endIdx = idx < triangleIndex.size() - 1 ? triangleIndex[idx + 1] : std::numeric_limits<uint>::max();
```
Comment (uclaros) [inline src/3d/qgs3dsceneexporter.cpp:558]:
```suggestion
        const uint startIdx = triangleIndex[idx];
        const uint endIdx = idx < triangleIndex.size() - 1 ? triangleIndex[idx + 1] : std::numeric_limits<uint>::max();
```

File: src/3d/qgs3dsceneexporter.cpp [hunk 20]
```diff
@@ -523,7 +526,46 @@ QVector<Qgs3DExportObject *> Qgs3DSceneExporter::processSceneLoaderGeometries( Q
...
+  // the geometry if all the featureid are already present.
+  QVector<std::pair<uint, uint>> triangleIndexStartingIndiceToKeep;
+  QgsTessellatedPolygonGeometry *tessGeom = dynamic_cast<QgsTessellatedPolygonGeometry *>( geometry );
+  if ( tessGeom )
+  {
+    QVector<QgsFeatureId> featureIds = tessGeom->featureIds();
+    QVector<uint> triangleIndex = tessGeom->triangleIndexStartingIndices();
+    for ( int idx = 0; idx < featureIds.size(); idx++ )
+    {
+      QgsFeatureId feat = featureIds[idx];
```
Comment (uclaros) [inline src/3d/qgs3dsceneexporter.cpp:550]:
```suggestion
      const QgsFeatureId feat = featureIds[idx];
```

**Review by uclaros — COMMENTED** [review]
Just a few `const`s here and there

**Review by uclaros — APPROVED** [review]

**Review by nyalldawson — APPROVED** [review]

**Comment by benoitdm-oslandia** [comment]
thanks @nyalldawson @uclaros!

**Comment by nyalldawson** [comment]
@benoitdm-oslandia looks like the new test is a bit fragile -- see eg https://github.com/qgis/QGIS/actions/runs/6179574806/job/16777801856?pr=54578 for a random failure it's been triggering

**Comment by benoitdm-oslandia** [comment]
Train trip today! I will try to fix that asap
