### PR TITLE
Fix cases where pointclouds fail to render on 2d

### LINKED ISSUE #48400: Point cloud layers fail to render on the 2D map canvas
### What is the bug or the crash?

While testing @nyalldawson 's point cloud profile stuff, I noticed a point cloud dataset that rendered fine in previous versions of QGIS now fails on current master. It renders once when the layer is added, but then subsequent renderings by panning around or zooming in and out fail, leaving a blank canvas.

### Steps to reproduce the issue

1. Download this point cloud dataset (https://pointcloud.hcmgis.vn/app/point-cloud/detail/banteay-kdei-temple-angkor-cambodia-5f6addf14bd68) and add it to QGIS
2. Zoom in, notice rendering fails

### Versions

master (to become 3.26)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by uclaros**
## Description
lazperf may throw exceptions which were only caught by a safeguard in `qgsmaprendererparalleljob` when it was too late, messing with actual rendering.

The diff looks complicated because of indentation. Actual change is just the addition of try/catch

Fix  #48400

### CODE REVIEW

File: src/core/pointcloud/qgslazdecoder.cpp [hunk 1]
```diff
@@ -472,78 +472,89 @@ QgsPointCloudBlock *__decompressLaz( FileType &file, const QgsPointCloudAttribut
...
+    QgsDebugMsgLevel( QStringLiteral( "LAZ-PERF Read through the points in %1 seconds." ).arg( t.elapsed() / 1000. ), 2 );
 #endif
-  block->setPointCount( count - skippedPoints );
-  return block.release();
+    block->setPointCount( count - skippedPoints );
+    return block.release();
+  }
+  catch ( std::exception &e )
+  {
+    Q_UNUSED( e )
```
Comment (nyalldawson) [inline src/core/pointcloud/qgslazdecoder.cpp:554]:
```suggestion
```

**Review by nyalldawson — APPROVED** [review]

**Comment by nirvn** [comment]
@uclaros , thanks for this.
