### PR TITLE
Fix crash on value relation multi-column

### LINKED ISSUE #54164: QGIS Crashes when editing multiple features simultaneously that have a Value Relation field
### What is the bug or the crash?

QGIS LTR crashes consistently on MacOS and Windows when I try to edit multiple features simultaneously that have a Value Relation field with Column set to larger than 1 and different values.

### Steps to reproduce the issue

1. Run a PostGIS instance, for my example I ran a docker locally, exposing port 7788 as in:
`postgresql://postgres:qgis@localhost:7788/postgres`
2. Create the dataset as follows:
We just need two tables - `option` is for the Value Relation and `lines` is for the features.
```sql

CREATE TABLE IF NOT EXISTS option (
    id int primary key not null,
    name varchar(20) not null
);

INSERT INTO option VALUES (1, 'option1'), (2, 'option2'), (3, 'option3'), (4, 'option4'), (5, 'option5');


CREATE TABLE IF NOT EXISTS lines (
    id int primary key not null,
    geom geometry(LineString, 4326),
    options integer[]
);

INSERT INTO lines (id, geom, options) VALUES (1, '0102000020E610000003000000BECAB3251C9CFCBFF9F2469027D34640AC56ECC03F8EFCBFB8F2BBF687AB46408244FAC4110D00C014FD3A2577AA4640', '{1}');
INSERT INTO lines (id, geom, options) VALUES (2, '0102000020E6100000030000002D5E379EE06CFFBFD2C2FDC365D246409F36E85D2527FEBFA657EDAECFB44640B74A32F4070A01C052ABBE91FCB24640', '{2}');
```

3. Open a new Project in QGIS
4. In the browser, create a New Connection to PostGIS. Make sure to mark "**Allow list tables with no geometry**"
5. Drag the `lines` Table from `public` schema onto Layers or the Map
6. Drag the `option` Table from `public` schema onto Layers or the map
7. Double-click the `lines` layer and go to `Attributes Form`
8. Select `options` field and change as follows:
   a. Widget Type -> Value Relation
   b. Layer -> option (key and name are not important)
   c. Allow multiple selections -> **True**
   d. Number of columns -> 2 -- **This is the critical step!**
   
image

9. Save the project
10. Ensure the `lines` Layer is Active (selected)
11. On the main toolbar click on "Select Feature by Area or Single Click"
12. Select **both** features
12. Click on "Toggle Editing" (Pencil)
13. Click on "Modify the Attributes of all Selected Features Simultaneously"
14. It crashes on `setCheckState` of the `QTableWidget`

**Notice:**
1. If the Number of Columns is 1, it does not crash
2. If both features had the same values for that field it won't crash either

Provided a QGS Project that completes all steps until 9. [reproduce.zip](https://github.com/qgis/QGIS/files/12306239/reproduce.zip)

### Versions

QGIS version | 3.28.6-Firenze | QGIS code revision | 868c9fa03b
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 13.3
  |   |   |  
Active Python plugins
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>QGIS version
3.28.6-Firenze
QGIS code revision
[868c9fa03b](https://github.com/qgis/QGIS/commit/868c9fa03b)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 13.3

Active Python plugins
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Fix #54164

### CODE REVIEW

File: src/gui/editorwidgets/qgsvaluerelationwidgetwrapper.cpp [hunk 1]
```diff
@@ -157,11 +157,15 @@ void QgsFilteredTableWidget::populate( QgsValueRelationFieldFormatter::ValueRela
...
 void QgsFilteredTableWidget::setIndeterminateState()
 {
-  for ( int j = 0; j < mTableWidget->rowCount(); j++ )
+  for ( int rowIndex = 0; rowIndex < mTableWidget->rowCount(); rowIndex++ )
   {
-    for ( int i = 0; i < mColumnCount; ++i )
+    for ( int columnIndex = 0; columnIndex < mColumnCount; ++columnIndex )
     {
-      whileBlocking( mTableWidget )->item( j, i )->setCheckState( Qt::PartiallyChecked );
+      if ( rowIndex * mColumnCount + columnIndex >= mCache.count() )
```
Comment (nyalldawson) [inline src/gui/editorwidgets/qgsvaluerelationwidgetwrapper.cpp:164]: Is the problem that "item" returns null here? It might be cleaner to just go:

   if ( currentItem = item( rowIndex, columnIndex) ) { ... }

Comment (elpaso) [reply src/gui/editorwidgets/qgsvaluerelationwidgetwrapper.cpp:164]: Yes, that's the problem, but I find it cleaner this way: why would we want to iterate over a non-existing table item when we already know in advance that the index is overflowing?

Comment (nyalldawson) [reply src/gui/editorwidgets/qgsvaluerelationwidgetwrapper.cpp:164]: Well the logic for sizing mCache and building checkbox widgets based on the size of mCache is somewhere else entirely, and there's a good chance that if someone messes with that logic they won't realise that this code even exists and needs updating accordingly.

**Review by nyalldawson — APPROVED** [review]
