### PR TITLE
WFS/OAPIF: fix filtering on duplicated layers (fixes #48465)

### LINKED ISSUE #48465: [regression] New filter for duplicated WFS layer is also applied on source layer
### What is the bug or the crash?

Setting a new filter for a duplicated WFS layer affects also the source layer used for duplication. Also there's no filter symbol for the source layer, also all source features are still shown on the map.

### Steps to reproduce the issue

1. Add WFS connection https://geoservices.krzn.de/security-proxy/services/wfs_verb_grenzen
2. Add layer `gis:kreisgrenzen`
3. Rightclick on layer -> duplicate layer
4. Show feature count for both layers (if not already set)
5. Rightclick on new duplicated layer -> set filter -> `"KREIS" = 'Viersen'`
6. See error: Filter is applied also on source layer, see feature count and inspect attribute table. There's no filter symbol for the source layer, also all source features are still shown on the map.

### Versions

`master` (1eda8b21ae9c1b788807395ae41b615301cc7265) on Ubuntu 20.04.4 LTS

`3.24.2` on Windows 10

**No issue with 3.22.6 LTR on Windows 10**

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

According to `git bisect` this regressed in 3511158887cd331aa11af96a2385af87c4881bf7.

### PR DESCRIPTION
**Pull request by rouault**
This is a continuation of #48500 that fixes the original issue, and passes regression tests

### CODE REVIEW

**Comment by m-kuhn** [comment]
Thanks for the help.
Something that's still on my todo list is checking for connections between signal/slots between layer and shared data.

**Comment by pathmapper** [comment]
Thanks to all, confirmed this fixes the issue for WFS and OAPIF 👍

**Comment by rouault** [comment]
@m-kuhn maybe we should merge this PR as it, pending your follow ups  ?

**Comment by m-kuhn** [comment]
This is new code for me, I am not confident to make the call here.

Given that so far we just copied the shared ptr without connecting it to the cloned layer, I wonder how important that even is (it's for some feedback loop for feature downloading dialogs etc showing up IIRC ?)

**Comment by rouault** [comment]
@m-kuhn  not completely sure if that's what you had in mind but I've added a commit to handle reconnecting the cloned shared data to the provider

**Review by m-kuhn — APPROVED** [review]
That is exactly what I had in mind, thank you very much

File: src/providers/wfs/qgsoapifprovider.cpp [hunk 1]
```diff
@@ -337,7 +337,14 @@ const QString &QgsOapifProvider::clientSideFilterExpression() const
 
 void QgsOapifProvider::handlePostCloneOperations( QgsVectorDataProvider *source )
 {
-  mShared = qobject_cast<QgsOapifProvider *>( source )  ->mShared;
+  disconnect( mShared.get(), &QgsOapifSharedData::raiseError, this, &QgsOapifProvider::pushErrorSlot );
+  disconnect( mShared.get(), &QgsOapifSharedData::extentUpdated, this, &QgsOapifProvider::fullExtentCalculated );
+
+  // We must not change the subset string of the shared data used in another iterator/data provider ...
+  mShared.reset( qobject_cast<QgsOapifProvider *>( source )->mShared->clone() );
```
Comment (m-kuhn) [inline src/providers/wfs/qgsoapifprovider.cpp:344]: Can we stick to doing that just after set subset string or not?

If it's done in here we run some risks again:
- we have the subset string in a shared data that is changed while iterators are running on it, this looks risky to me
- feature ids will be changed on cloned layers which was the original issue related to the label export algorithm having wrong references to original features

can we move this only to post-subset-string change?

Comment (rouault) [reply src/providers/wfs/qgsoapifprovider.cpp:344]: > can we move this only to post-subset-string change?

I actually tried this. But there was one unit test that breaks in [providertestbase.py](https://github.com/qgis/QGIS/pull/48998/files#diff-e112d0d5d27c1dfff4ecd30f58bb07a19c07051a8f2c71ae4f9dbadf85146f77) at the place where I left a comment. This test is related to feature id stability. The fact that this test passes with the current code is mostly a miracle (actually when running this setSubsetString() test in isolation and not the whole test_provider_wfs.py file, it breaks, probably because it depends on other tests to have previously loaded the whole layer in the cache). So maybe we should do just a hack here and not try this test for the WFS provider

Regarding "feature ids will be changed on cloned layers", there might be an issue in using the same SharedData object by 2 layers. If the 2 layers are rendered in separate threads, the SharedData would be used (and the objects it contains, in particular the FID<->gml:id cache) concurrently, and bad things could happen. So it seems safer to me to clone the SharedData as a post processing step of layer cloning. Ideally we'd want to duplicate the FID<-->gml:id cache (which resides in a SQLite db), but that isn't not implemented currently.

Comment (m-kuhn) [reply src/providers/wfs/qgsoapifprovider.cpp:344]: > > can we move this only to post-subset-string change?
> 
> I actually tried this. But there was one unit test that breaks in [providertestbase.py](https://github.com/qgis/QGIS/pull/48998/files#diff-e112d0d5d27c1dfff4ecd30f58bb07a19c07051a8f2c71ae4f9dbadf85146f77) at the place where I left a comment. This test is related to feature id stability. The fact that this test passes with the current code is mostly a miracle (actually when running this setSubsetString() test in isolation and not the whole test_provider_wfs.py file, it breaks, probably because it depends on other tests to have previously loaded the whole layer in the cache). So maybe we should do just a hack here and not try this test for the WFS provider

Skipping this test sounds reasonable with this explanation.

> Regarding "feature ids will be changed on cloned layers", there might be an issue in using the same SharedData object by 2 layers. If the 2 layers are rendered in separate threads, the SharedData would be used (and the objects it contains, in particular the FID<->gml:id cache) concurrently, and bad things could happen. So it seems safer to me to clone the SharedData as a post processing step of layer cloning. Ideally we'd want to duplicate the FID<-->gml:id cache (which resides in a SQLite db), but that isn't not implemented currently.

One single layer can already now have iterators running in different threads, so concurrency shouldn't be something new to handle, unless I am missing some of the magic of the WFS provider.

Comment (rouault) [reply src/providers/wfs/qgsoapifprovider.cpp]: > can we move this only to post-subset-string change?

I've implemented that in the latest commit

> One single layer can already now have iterators running in different threads, so concurrency shouldn't be something new to handle

hum, there might be potential troubles then as I doubt the code is ready for that. (and that would be probably hard to achieve)

Comment (m-kuhn) [reply src/providers/wfs/qgsoapifprovider.cpp]: Ah, sorry I have missed this comment.
In this case I would say let's merge this, it only improves the situation.
In parallel, should we file a ticket to review multithreading here for an upcoming bugfix sprint?

Comment (rouault) [reply src/providers/wfs/qgsoapifprovider.cpp]: > In parallel, should we file a ticket to review multithreading here for an upcoming bugfix sprint?

done in https://github.com/qgis/QGIS/issues/49181
