### PR TITLE
QgsRasterFileWriter::driverForExtension(): make sure querying the tif…

### LINKED ISSUE #59112: QGIS 3.39 tries to create files with SNAP_TIFF read-only driver
### What is the bug or the crash?

I am using QGIS version 3.39.0-Master, QGIS code revision 40246d3509 installed with OSGeo4W. When I try for example to clip a raster layer a GDAL command like this is created:
`gdal_translate -projwin 360853.6639 6714413.7697 360961.8182 6714257.3265 -of SNAP_TIFF C:\data\dem2m.tif C:/Users/JRAHKONEN/AppData/Local/Temp/processing_giGcnu/ad37cba320a145848a03c12bed16db8d/OUTPUT.tif`

Notice the output format SNAP_TIFF, that means this brand new read-only driver https://gdal.org/en/latest/drivers/raster/snap_tiff.html. The SNAP_TIFF driver cannot be used at all for writing, and it should be used only for reading some peculiar TIFF variants.

### Steps to reproduce the issue

Try to clip a raster layer with `GDAL - Raster extraction - Clip raster by extent`. Process fails and the meaningful part of the error message is
```
GDAL command output:
Output driver `SNAP_TIFF' not recognised. 
```

### Versions

QGIS version
3.39.0-Master
QGIS code revision
40246d3509
 
Libraries
Qt version
5.15.13
Python version
3.12.6
GDAL/OGR version
3.10.0dev-b6edb5191e
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009
This copy of QGIS writes debugging output.
 
Active Python plugins
FreehandRasterGeoreferencer
0.8.3
latlontools
3.7.1
Qgis2threejs
2.7.3
rasmover-master
version 0.2
simplewcs
0.2
wfsclient
0.9.11
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Even Rouault claims that he could not reproduce on Linux, see comments at https://github.com/OSGeo/gdal/pull/10867

### PR DESCRIPTION
**Pull request by rouault**
…/tiff extension returns the GTiff driver

Not strictly necessary since has been adressed on GDAL side per https://github.com/OSGeo/gdal/pull/11037 but might be prudent for future similar situations.

Fixes #59112

Already tested per https://github.com/qgis/QGIS/blob/94411b5fcd0c670767332a1ba23ca12786c46118/tests/src/python/test_qgsrasterfilewriter.py#L108

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]

File: src/core/raster/qgsrasterfilewriter.cpp [hunk 1]
```diff
@@ -1072,6 +1072,15 @@ QString QgsRasterFileWriter::driverForExtension( const QString &extension )
   if ( ext.startsWith( '.' ) )
     ext.remove( 0, 1 );
 
+  if ( ext == QLatin1String( "tif" ) || ext == QLatin1String( "tiff" ) )
```
Comment (agiudiceandrea) [inline src/core/raster/qgsrasterfilewriter.cpp:1075]: Shouldn't the comparison be case insensitive?

Comment (rouault) [reply src/core/raster/qgsrasterfilewriter.cpp]: indeed. Fixes. Thanks for the review
