### PR TITLE
Use native raster API in QgsGridFileWriter

### LINKED ISSUE #56653: "TIN interpolation" and "IDW interpolation" algs always output an ASCII grid (AAIGrid) raster regardless of the output file extension
### What is the bug or the crash?

Both the "TIN interpolation" (`qgis:tininterpolation`) and "IDW interpolation" (`qgis:idwinterpolation`) processing algorithms output an ASCII grid (AAIGrid) raster regardless of the output file extension / format chosen.
For example, entering "tinoutput.tif" as the raster output filename, then the raster output file "tinoutput.tif" (provided in [tinoutput.zip](https://github.com/qgis/QGIS/files/14477895/tinoutput.zip)) will be actually in the ASCII grid "AAIGrid" format and will contain ASCII text
```
NCOLS 522
NROWS 472
XLLCORNER 366203.53
YLLCORNER 4697127.9
DX 19.990665
DY 19.97496
NODATA_VALUE -9999
....
```
instead of being a real GeoTIFF.

### Steps to reproduce the issue

1. Just use the "TIN interpolation" or the "IDW interpolation" algorithms and specify an output raster file with whichever file extension / format

### Versions

QGIS version
3.34.4-Prizren
QGIS code revision
https://github.com/qgis/QGIS/commit/decd43dc17cf7de6c13568919605849c89d3708d
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
16.1
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 1903

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alexbruy**
## Description

Update `QgsGridFileWriter` class used to save interpiolation results to use QGIS raster API. This allows to save interpolation results into any GDAL-supported format, not only as ASCII grid.

Fixes #56653.

### CODE REVIEW

**Comment by alexbruy** [comment]
Not sure if this should be backported.

File: src/analysis/interpolation/qgsgridfilewriter.cpp [hunk 1]
```diff
@@ -34,95 +36,67 @@ QgsGridFileWriter::QgsGridFileWriter( QgsInterpolator *i, const QString &outputP
...
+    {
+      break;
+    }
+
     currentXValue = mInterpolationExtent.xMinimum() + mCellSizeX / 2.0; //calculate value in the center of the cell
-    for ( int j = 0; j < mNumColumns; ++j )
+
+    QgsRasterBlock block( Qgis::DataType::Float32, mNumColumns, 1 );
+
+    std::vector<float> float32Row( mNumColumns );
```
Comment (nyalldawson) [inline src/analysis/interpolation/qgsgridfilewriter.cpp:79]: It's be more efficient to move this out of the loop, so that we only incur the allocation cost once.

**Review by nyalldawson — COMMENTED** [review]
Nice improvement!!

**Review by nyalldawson — APPROVED** [review]
