### PR TITLE
Fixes windows issue with QVariant( QString() ) being NULL

### LINKED ISSUE #41076: Empty String '' is shown as NULL with a spatialite layer using OGR provider
**Describe the bug**

In QGIS 3.16.2 empty string fields (value '') are shown as NULL and not an empty field like in 3.10.13  
image

What it should look like
image

Image from the DB Browser for SQLite with BIL1 set too NULL to show the difference that the fields are truly empty strings and not NULL
image

**How to Reproduce**

Have a string field with the value '' 

**QGIS and OS versions**
Tested with 3.10.13 and 
QGIS version
3.16.2-Hannover
QGIS code revision
f1660f9da5

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #41076

### CODE REVIEW

**Comment by elpaso** [comment]
Unrelated test failure

File: src/core/qgsogrutils.cpp [hunk 1]
```diff
@@ -315,7 +323,7 @@ QVariant QgsOgrUtils::getOgrFeatureAttribute( OGRFeatureH ogrFet, const QgsField
   }
   else
   {
-    value = QVariant( QString() );
+    value = QVariant( field.type() );
```
Comment (roya0045) [inline src/core/qgsogrutils.cpp:326]: @elpaso Are you sure that the failing processing tests are unrelated, I didn't check thouroughly but they now seem to be consistant since this PR. Could this be caused by this change?

Comment (elpaso) [reply src/core/qgsogrutils.cpp:326]: That's possible, I'll have a look. In any case, I think that the patch is correct, the old behavior was to return an empty string even when the field type was not a string.

Comment (elpaso) [reply src/core/qgsogrutils.cpp:326]: @roya0045 I can confirm that this was indeed the problem. I'll find a solution.

Comment (roya0045) [reply src/core/qgsogrutils.cpp:326]: Thank you and apologies for the inconvenience. I agree that this fix is needed, though I'm not sure if the tests need to be updated or its something more that need to be modified.

Comment (elpaso) [reply src/core/qgsogrutils.cpp:326]: What apologies? Thank **you** for pointing me to the right direction!

I think that the issue is in the algorithms, they should check for NULL values before using the attribute values for calculations. The old behavior was relying on the fact that a NULL attribute was stored by OGR as an empty string instead of a NULL QVariant of the corresponding field type, the conversion of the `QVariant( QString())` to a numeric field was checked (and it was failing) so everything worked (at least for non-string types) but I think that it was a wrong implementation.
