### PR TITLE
Fix WMS LegendGraphic default style

### LINKED ISSUE #63754: QGIS does not request default style for WMS layer when in group/container
### What is the bug or the crash?

When adding a WMS layer from a group  layer where no styling has been specified, QGIS should request the default style however does not appear to correctly handle the style at all. The layer itself has two styles (one from the group and one from the layer itself) both of which resolve to valid legend graphics.

Image

ArcGIS Pro, for example, handles this by sending a empty &STYLES= parameter. This is conform OGC specification

Image

Image

All three of these requests return a valid legend graphic
`http://dev-geoserver.gdnnet.lan/geoserver/nlog/ows?service=WMS&version=1.3.0&request=GetLegendGraphic&format=image%2Fpng&width=20&height=20&layer=gdw_ng_licence_salt_utm&style=`
`http://dev-geoserver.gdnnet.lan/geoserver/nlog/ows?service=WMS&version=1.3.0&request=GetLegendGraphic&format=image%2Fpng&width=20&height=20&layer=gdw_ng_licence_salt_utm&style=default-style-lic`
`http://dev-geoserver.gdnnet.lan/geoserver/nlog/ows?service=WMS&version=1.3.0&request=GetLegendGraphic&format=image%2Fpng&width=20&height=20&layer=gdw_ng_licence_salt_utm&style=licence_salt`

I can confirm that if all other styles are removed, and only one style remains (default-style-<layer>) then QGIS handles it properly, so this indeed appears to be applications-side

Image

Image

### Steps to reproduce the issue

1. Add a WMS group layer child into QGIS without selecting a style, e.g. drag from Browser to Layers
2. Layer will be added without style, and results in no legend being added

Image

3. Add the same layer via Layer>Vector>Add WMS/WMTS and select either style and it will be processed correctly, but the top level layer remains without a legend.

Image

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.40.10-Bratislava</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/c98da2e682">c98da2e682</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.13</td></tr><tr><td>Python version</td><td>3.12.11</td></tr><tr><td>GDAL version</td><td>3.11.3 — <i>Eganville</i></td></tr><tr><td>PROJ version</td><td>9.6.2</td></tr><tr><td>EPSG Registry database version</td><td>v12.013 (2025-05-26)</td></tr><tr><td>GEOS version</td><td>3.13.1-CAPI-1.19.2</td></tr><tr><td>SQLite version</td><td>3.50.4</td></tr><tr><td>PDAL version</td><td>2.9.0</td></tr><tr><td>PostgreSQL client version</td><td>unknown</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.3.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Windows 11 Version 2009</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>pdokservicesplugin</td><td>5.2.0</td></tr><tr><td>slyr_community</td><td>6.0.0</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

The data is being pulled from GeoServer v2.27.1

ArcGIS Pro version for comparison is 3.2.4

### PR DESCRIPTION
**Pull request by merydian**
## Description

Use the first available style of WMS layer legend graphics if no default style was found, to avoid loading none at all.  

Closes #63754

### CODE REVIEW

File: src/providers/wms/qgswmsprovider.cpp [hunk 1]
```diff
@@ -406,18 +406,16 @@ QString QgsWmsProvider::getLegendGraphicUrl() const
...
-          url = pickLegend( l.style[0] );
+          url = pickLegend( *s );
         }
         else
         {
-          const QgsWmsStyleProperty *s = searchStyle( l.style, u"default"_s );
-          if ( s )
-            url = pickLegend( *s );
+          // If no default style was found, use the first one
+          url = pickLegend( l.style[0] );
```
Comment (elpaso) [inline src/providers/wms/qgswmsprovider.cpp:418]: wouldn't this crash if l.style is empty?

Comment (merydian) [reply src/providers/wms/qgswmsprovider.cpp:418]: Good point, so maybe like this?

```cpp
else if (!l.style.empty())
{
  // If no default style was found, use the first one
  url = pickLegend(l.style[0]);
}
```

**Review by 3nids — APPROVED** [review]
