### PR TITLE
[expressions] Relation aggregate: fix cache key

### LINKED ISSUE #49469: When using a computed or virtual field that refers to other layers's fields having the same name, the wrong value is returned.
### What is the bug or the crash?

We have a layer that has a virtual field with a sum of multiple relation aggregates. It seems that there is some sort of cache for relations and the wrong value is returned.

The virtual field is set to the following expression:
```
relation_aggregate( 'ganancia_a_Cable_acceso_FK_Cable_Acce_fid','sum',"Longitud") + relation_aggregate('CTO_134c70_Cable_Acceso_FK_Cable_Acce_fid','count',"fid") + relation_aggregate('Cierre_Emp_Cable_Acceso_FK_Cable_Acce_fid','count',"fid")  
```

All three relations use `Cable_Acceso` as the referenced layer, `fid` as the referenced field, and `Cable_acceso_FK` as the referencing field as it can be seen below:

image

Now the problem is in the formula, the `relation_aggregate('Cierre_Emp_Cable_Acceso_FK_Cable_Acce_fid','count',"fid")` is returning the same value as `relation_aggregate('CTO_134c70_Cable_Acceso_FK_Cable_Acce_fid','count',"fid")`

Is it possible there is a cache of the aggregate result of sorts and its not using the relation_id as part of the key?

Even if I apply the `relation_aggregate('Cierre_Emp_Cable_Acceso_FK_Cable_Acce_fid','count',"fid")` as a new virtual field and a second field with `relation_aggregate('CTO_134c70_Cable_Acceso_FK_Cable_Acce_fid','count',"fid")`, in the expression editor, looking at each value, the correct result is shown, but then, in the table view, both columns show the same value.

### Steps to reproduce the issue

At least three layers are needed:

* Cable (layer)
  `Name (Text)`
* CTO (layer)
  `Name (Text)`
  `Cable_FK (Uint64)`
* CE (layer)
  `Name (Text)`
  `Cable_FK (Uint64)`

Then the following relations are created:

image

and the same one for CTO_2_Cable

It should look as this:
image

Then create some polylines in the "Cable" layer and add some CE points, associating them to the polylines (the relation field should appear already) and some CTO points as well, also associated

The `CE` table should look as follows:
image

while the `CTO` table would have data similar to this:
image

Finally, in the Cable table, we create three new virtual fields:

The first one, called `sum_count` as type integer with the following expression:
```relation_aggregate('CE_6be67ee_Cable_FK_rel_agg_bu_fid','count',"fid") + relation_aggregate('CTO_023987_Cable_FK_rel_agg_bu_fid','count',"fid")```

which looks like the following:
image

and we already see the problem. The sum is wrong as it can be seen below:

image

 If only a single relation (CE) is used (in the whole form) the value is correct:
image

result:
image

or the other relation (CTO)
image

result:
image

Finally.. if all formulas are used at the same time:
image

the values are wrong:
image

And one final detail, if the order of usage of the relations is changed, the totals change:
In this case, we refer to the `CTO` relation first:
``` relation_aggregate('CTO_023987_Cable_FK_rel_agg_bu_fid','count',"fid") + relation_aggregate('CE_6be67ee_Cable_FK_rel_agg_bu_fid','count',"fid")```

image

and the result is the following:
image

image

### Versions

Also reproducible in 3.16.11 and 3.16.9 as well as the following:

QGIS version
3.22.9-Białowieża
QGIS code revision
a8e9e6fa
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
AnotherDXF2Shape
1.2.4
AppendFeaturesToLayer
1.2.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

This was reproduced in multiple QGIS versions on different machines / users / even in a brand new project

Attached is a zip file with the corresponding project and geopackage

[rel-agg.zip](https://github.com/qgis/QGIS/files/9182658/rel-agg.zip)
.

### PR DESCRIPTION
**Pull request by elpaso**
Fix #49469

### CODE REVIEW

File: src/core/expression/qgsexpressionfunction.cpp [hunk 1]
```diff
@@ -891,11 +891,11 @@ static QVariant fcnAggregateRelation( const QVariantList &values, const QgsExpre
 
   parameters.filter = relation.getRelatedFeaturesFilter( f );
 
-  QString cacheKey = QStringLiteral( "relagg:%1:%2:%3:%4:%5" ).arg( vl->id(),
-                     QString::number( static_cast< int >( aggregate ) ),
-                     subExpression,
-                     parameters.filter,
-                     orderBy );
+  const QString cacheKey = QStringLiteral( "relagg:%1%:%2:%3:%4:%5:%6" ).arg( relationId, vl->id(),
```
Comment (agiudiceandrea) [inline src/core/expression/qgsexpressionfunction.cpp:894]: Is `relagg:%1%:` a typo?

Comment (elpaso) [reply src/core/expression/qgsexpressionfunction.cpp:894]: Yes, it doesn't affect the functionality though.

Comment (elpaso) [inline src/core/expression/qgsexpressionfunction.cpp:894]:
```suggestion
  const QString cacheKey = QStringLiteral( "relagg:%1:%2:%3:%4:%5:%6" ).arg( relationId, vl->id(),
```

**Review by nyalldawson — APPROVED** [review]
