### PR TITLE
Fixes to various issues raised by people trying the new welcome page 

### LINKED ISSUE #64825: Welcome page: various issues in the new UI/UX
It seems to me there area some issues in the new welcome page (https://github.com/qgis/QGIS/pull/64652):

- if you click on "Enable news feed" (in Welcome to QGIS! / Stay up to date!) it is no longer possible to disable the news feed using the button

https://github.com/user-attachments/assets/3b078084-35f8-467a-9a54-77b5e624e12b

- if you click on the OpenStreetMap template project, nothing happens:

https://github.com/user-attachments/assets/eca49852-b84b-47dc-845d-0c601cd857d2

_Originally posted by @agiudiceandrea in https://github.com/qgis/QGIS/issues/64652#issuecomment-3852688264_

- after opening a project, it is not possible to close it and return to the welcome page ("Project->Close") or close it creating a blank project (Project->New or Ctrl+N or "New Project" button).

https://github.com/user-attachments/assets/5e8c200e-cdc5-457c-b6e7-4906c3f6aa0e

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This PR fixes the storm of issues raised in https://github.com/qgis/QGIS/issues/64825 with regards to the new welcome page (and then some more :) ). Big thanks to people providing reports and screencasts while trying it.

--

Edit: after countless attempts to fix the main windows flashing on app launch, I found a workaround by setting the quick graphics API to software (https://github.com/qgis/QGIS/pull/64841/changes#diff-214bd4636579818fc26242a65aee285dbdca02666343ff789ba776caae1ddc9aR967). 

This has to very, _very_ nice benefit of fixing a related problem whereas editing an attribute form QML widget would lead to QGIS being unresponsive to any input events. 

The downside is that until Qt fixes the situation upstream, we won't be able to use advanced layer effects. That said, it's a fair trade to insure QGIS doesn't unexplainably "die" on users.

### CODE REVIEW

File: src/app/qgisapp.cpp [hunk 1]
```diff
@@ -5923,17 +5925,19 @@ void QgisApp::fileClose()
...
 bool QgisApp::canCreateNewProject()
 {
-  return !checkUnsavedLayerEdits() || !checkMemoryLayers() || !saveDirty() || !checkUnsavedRasterAttributeTableEdits();
+  return checkUnsavedLayerEdits() && checkMemoryLayers() && saveDirty() && checkExitBlockers() && checkUnsavedRasterAttributeTableEdits();
 }
 
 //as file new but accepts flags to indicate whether we should prompt to save
 bool QgisApp::fileNew( bool promptToSaveFlag, bool forceBlank )
 {
+  qDebug() << "fileNew!";
```
Comment (CeliaBuira) [inline src/app/qgisapp.cpp]:
```suggestion
```

File: src/app/qgisapp.cpp [hunk 2]
```diff
@@ -5923,17 +5925,19 @@ void QgisApp::fileClose()
...
   if ( checkTasksDependOnProject() )
     return false;
 
   if ( promptToSaveFlag )
   {
+    qDebug() << "promptToSaveFlag!";
```
Comment (CeliaBuira) [inline src/app/qgisapp.cpp]:
```suggestion

```

File: src/app/qgisapp.cpp [hunk 3]
```diff
@@ -5910,11 +5910,13 @@ bool QgisApp::fileNew()
 
 bool QgisApp::fileNewBlank()
 {
+  qDebug() << "fileNewBlank!";
   return fileNew( true, true );
 }
 
 void QgisApp::fileClose()
 {
+  qDebug() << "fileClose!";
```
Comment (CeliaBuira) [inline src/app/qgisapp.cpp]:
```suggestion
```

File: src/app/qgisapp.cpp [hunk 4]
```diff
@@ -5910,11 +5910,13 @@ bool QgisApp::fileNew()
 
 bool QgisApp::fileNewBlank()
 {
+  qDebug() << "fileNewBlank!";
```
Comment (CeliaBuira) [inline src/app/qgisapp.cpp]:
```suggestion
```

**Comment by agiudiceandrea** [comment]
See https://github.com/qgis/QGIS/issues/64825#issuecomment-3867382015 for still occurring issues.

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
Let's get this set merged, then do follow up PRs for remaining issues

File: src/app/qgisapp.cpp [hunk 5]
```diff
@@ -5923,7 +5923,7 @@ void QgisApp::fileClose()
 
 bool QgisApp::canCreateNewProject()
 {
-  return !checkUnsavedLayerEdits() || !checkMemoryLayers() || !saveDirty() || !checkUnsavedRasterAttributeTableEdits();
+  return checkUnsavedLayerEdits() && checkMemoryLayers() && saveDirty() && checkExitBlockers() && checkUnsavedRasterAttributeTableEdits();
```
Comment (uclaros) [inline src/app/qgisapp.cpp:5926]: @nirvn I don't think this is correct here. Exit blockers should block exiting the application, not closing the active project.

Python files being edited are now closed/asked to save when closing the project or creating a new project, which is not desirable.
