### PR TITLE
Layout UI fix when click happened during left mouse button holding

### LINKED ISSUE #46568: When dragging a guide in a layout, cursor icon freezes if right mouse button is pressed before releasing left mouse button
### What is the bug or the crash?

While working on a layout and dragging a guide (from top or left ruler), if the right mouse button is pressed before releasing left mouse button the cursor icon freezes and does not revert back to normal pointer.

The only way to resolve the issue is to restart the software.

The issue only seems to affect Windows platform.
Tested on Windows 10 Pro (Version	10.0.19044 Build 19044) in:
QGIS 3.16.15
QGIS 3.22.2
QGIS 3.23.0-Master (6c93b2adfe)

The issue is NOT present on Fedora 35 in:
QGIS 3.23.0-Master (6a05593f82)

### Steps to reproduce the issue

1. Create a new layout
2. In the layout, drag a guide from the top (or left) ruler
3. Before releasing the left mouse button, press the right mouse button
4. Left-click elsewhere on the layout

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.22.2-Białowieża | QGIS code revision | 1601ec46d0
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.0
PROJ version | 8.2.0
EPSG Registry database version | v10.038 (2021-10-21)
GEOS version | 3.10.0-CAPI-1.16.0
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Might be related to https://github.com/qgis/QGIS/issues/46233

### LINKED ISSUE #46569: When dragging a selection box in a layout, the box remains on screen if right mouse button is pressed before releasing left mouse button
### What is the bug or the crash?

While working on a layout and dragging a selection box, if the right mouse button is pressed before releasing left mouse button the box remains on screen.
Closing and re-opening the layout does not remove the selection box(es).

The issue only seems to affect Windows platform.
Tested on Windows 10 Pro (Version 10.0.19044 Build 19044) in:
QGIS 3.16.15
QGIS 3.22.2
QGIS 3.23.0-Master (6c93b2a)

The issue is NOT present on Fedora 35 in:
QGIS 3.23.0-Master (6a05593)

image

### Steps to reproduce the issue

1. Create an empty layout
2. Start dragging a selection box (Select tool: press and hold left mouse button)
3. While still holding the left mouse button, press the left mouse button
4. Left-click elsewhere on the layout

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.22.2-Białowieża | QGIS code revision | 1601ec46d0
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.0
PROJ version | 8.2.0
EPSG Registry database version | v10.038 (2021-10-21)
GEOS version | 3.10.0-CAPI-1.16.0
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Might be related to https://github.com/qgis/QGIS/issues/46568

### PR DESCRIPTION
**Pull request by SebastienPeillet**
FIX #46568
FIX #46569

## Description

@GisUsers reported some troubles in the layout ui when a click happened during a left mouse button holding operation (see issues above)

### Layout Ruler fix

During a rule creation, left button must be hold to place it and the cursor will change of shape . On a right button release, the QgsLayoutRuler menu pops up and the focus is set on it, so the left button release event won't be received by QgsLayoutRuler. In consequences, the cursor doesn't change of shape back.

### Layout tools fix

On a right click press, the QgsLayoutAppMenuProvider pops up and the focus is set on it instead of the layout. So the left button release event won't be received by QgsLayoutView to be transmitted to the QgsLayoutViewToolXXXX. In consequences, the rubberband created during the holding operation is not removed from QgsLayoutView and a new left press deletes the rubberband reference without remove it from QgsLayoutView. So the rubberband stays until the end of application.

-----

For both situation, before the menu pops up, I trigger a left button release event if a operation is in progress. In this way operations will finish properly. For the zoom tools, I prefered to only remove the rubberband to avoid unwanted zoom

### CODE REVIEW

**Review by elpaso — APPROVED** [review]

File: src/gui/layout/qgslayoutruler.cpp [hunk 1]
```diff
@@ -802,6 +802,8 @@ void QgsLayoutRuler::mouseReleaseEvent( QMouseEvent *event )
   }
   else if ( event->button() == Qt::RightButton )
   {
+    QMouseEvent leftReleaseEvent( event->type(), event->localPos(), Qt::LeftButton, event->buttons(), event->modifiers() );
+    mouseReleaseEvent( &leftReleaseEvent );
```
Comment (nyalldawson) [inline src/gui/layout/qgslayoutruler.cpp:806]: This change looks dangerous to me -- it will result in a second left mouse button release event being sent to the rulers, and looking at QgsLayoutRuler::mouseReleaseEvent this second event will trigger a guide creation event. I think more logic is required in mousePressEvent/mouseReleaseEvent to correctly discard an unexpected release event whichs occurs outside of the usual press/release event pairs.

**Review by nyalldawson — CHANGES_REQUESTED** [review]

File: src/gui/layout/qgslayoutruler.cpp (hunk 1 above)
Comment (SebastienPeillet) [reply src/gui/layout/qgslayoutruler.cpp]: @nyalldawson Yes, I didn't know which should be the expected behavior, as the right click here is probably a mistake from the user, I thought that we could let the guide being created or moved. Then the user can move it yet, if necessary.

But ok, discard is probably the cleaner way to handle this. I changed it : I had to add a new attribute to QgsLayoutRuler, to keep the old position of an existing guide. This attribute is used to replace the guide to the previous position.

Comment (SebastienPeillet) [reply src/gui/layout/qgslayoutruler.cpp]: I also change to logic in the select tool to discard the action and to keep the current selection.

**Review by nyalldawson — APPROVED** [review]
