### PR TITLE
Fix PG error when failing to update geom & constrained field

### LINKED ISSUE #45100: PostGIS error while changing attributes (field value and geometry): prepared statement "updatefeature" already exists
### What is the bug or the crash?

When editing both geometry and field values of a PostGIS feature at the same time, if the edit fails due to a Postgres constraint violation (or any other Postgres error), the next time I try and save a valid geometry and attribute edit I get the following error:

```
Could not commit changes to layer ...

Errors: 
  Provider errors:
      PostGIS error while changing attributes: ERROR:  prepared statement "updatefeature" already exists
```

Edits to just geometry or just attribute values save, but edits involving both will continue to fail with this error until either QGIS is restarted or the layer is removed and re-added.

I'm not entirely sure but, having poked around in qgspostgresprovider.cpp, it looks like there may be a missing "DEALLOCATE updatefeature" in QgsPostgresProvider::changeFeatures after the rollback (line 3508).

### Steps to reproduce the issue

1. Start editing a PostGIS layer with a NOT NULL constraint on one of its fields (uncheck enforce not null constraint).
2. Change a feature's geometry and set it's field value to NULL (so as to cause the postgres error).
3. Try to save layer edits (get the expected constraint violation error).
4. Stop editing and discard edits.
5. Start editing again and change (any) feature's geometry and field value to something valid.
6. Save layer edits (get prepared statement "updatefeature" already exists error).

### Versions

Tested on QGIS 3.16.8, Postgres 10

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
The problem was that throwing an exception the prepared statement
was not deallocated.

Fix #45100

### CODE REVIEW

File: src/providers/postgres/qgspostgresprovider.cpp [hunk 1]
```diff
@@ -3511,6 +3513,7 @@ bool QgsPostgresProvider::changeFeatures( const QgsChangedAttributesMap &attr_ma
   {
     pushError( tr( "PostGIS error while changing attributes: %1" ).arg( e.errorMessage() ) );
     conn->rollback();
+    conn->PQexecNR( QStringLiteral( "DEALLOCATE updatefeature" ) );
```
Comment (rouault) [inline src/providers/postgres/qgspostgresprovider.cpp:3516]: at line 4356 a PGException is also thrown, but there's no related PQprepare updatefature. The DEALLOCATE might perhaps not hurt, but that seems a bit messy. Wouldn't moving that line  just before throwing the exception be cleaner ?

**Review by nyalldawson — APPROVED** [review]
