### PR TITLE
Fix opacity SLD export

### LINKED ISSUE #33376: Exporting SLD doesnt include fill-opacity
**Describe the bug**
Exporting symbology to SLD doesn't include the opacity (fill-opacity in sld) defined using "Layer rendering"

**How to Reproduce**

1. Go to symbology / layer rendering / opacity
2. Click on apply.  The GUI shows the simbology with opacity
3. Export symbology to SLD. The generated SLD doesn`t include the fill-opacity parameter
`        <se:SvgParameter name="fill-opacity">0.25</se:SvgParameter>`

**QGIS and OS versions**
Mac . 3.4.13

**Additional context**

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #33376

### CODE REVIEW

File: src/core/symbology/qgsfillsymbollayer.cpp [hunk 1]
```diff
@@ -404,7 +404,19 @@ void QgsSimpleFillSymbolLayer::toSld( QDomDocument &doc, QDomElement &element, c
     // <Fill>
     QDomElement fillElem = doc.createElement( QStringLiteral( "se:Fill" ) );
     symbolizerElem.appendChild( fillElem );
-    QgsSymbolLayerUtils::fillToSld( doc, fillElem, mBrushStyle, mColor );
+    // Apply alpha from symbol
+    bool ok;
+    const double alpha { props.value( QStringLiteral( "alpha" ), 0.0 ).toDouble( &ok ) };
```
Comment (troopa81) [inline src/core/symbology/qgsfillsymbollayer.cpp:409]: That mean if we don't have the *alpha* properties defined, then the exported color would be fully transparent.

Wouldn't that be better to use QVariant() as a default value so ok would be false

File: src/core/symbology/qgsfillsymbollayer.cpp [hunk 2]
```diff
@@ -404,7 +404,19 @@ void QgsSimpleFillSymbolLayer::toSld( QDomDocument &doc, QDomElement &element, c
...
+    if ( ok )
+    {
+      QColor color { mColor };
+      color.setAlphaF( color.alphaF() * alpha );
+      QgsSymbolLayerUtils::fillToSld( doc, fillElem, mBrushStyle, color );
+    }
+    else
+    {
+      QgsSymbolLayerUtils::fillToSld( doc, fillElem, mBrushStyle, mColor );
```
Comment (troopa81) [inline src/core/symbology/qgsfillsymbollayer.cpp:418]: Just a minor comment for readability, could be remove the else part like it's done in the other modified part

File: src/core/symbology/qgsfillsymbollayer.cpp (hunk 1 above)
Comment (elpaso) [reply src/core/symbology/qgsfillsymbollayer.cpp:409]: Definitely, I'll make the change.

File: src/core/symbology/qgsfillsymbollayer.cpp (hunk 2 above)
Comment (elpaso) [reply src/core/symbology/qgsfillsymbollayer.cpp]: done

File: src/core/symbology/qgsfillsymbollayer.cpp [hunk 3]
```diff
@@ -413,7 +423,15 @@ void QgsSimpleFillSymbolLayer::toSld( QDomDocument &doc, QDomElement &element, c
     QDomElement strokeElem = doc.createElement( QStringLiteral( "se:Stroke" ) );
     symbolizerElem.appendChild( strokeElem );
     double strokeWidth = QgsSymbolLayerUtils::rescaleUom( mStrokeWidth, mStrokeWidthUnit, props );
-    QgsSymbolLayerUtils::lineToSld( doc, strokeElem, mStrokeStyle, mStrokeColor, strokeWidth, &mPenJoinStyle );
+    // Apply alpha from symbol
+    bool ok;
+    const double alpha { props.value( QStringLiteral( "alpha" ), 0.0 ).toDouble( &ok ) };
```
Comment (troopa81) [inline src/core/symbology/qgsfillsymbollayer.cpp:428]:
```suggestion
    const double alpha { props.value( QStringLiteral( "alpha" ), QVariant() ).toDouble( &ok ) };
```

**Comment by elpaso** [comment]
Unrelated random test failures.

**Review by troopa81 — APPROVED** [review]
