### PR TITLE
Do not try to compute the center of a segment of null length

### LINKED ISSUE #34396: 100% cpu on marker symbol placed on center of a degenerate linestring
**Describe the bug**

A single layer with a simple symbology made of a line with marker symbol generates a 100% CPU load.

**How to Reproduce**

Download the project file and dataset from
https://share.oslandia.net/public/a48028

Open it and stare at your CPU burning ...

**QGIS and OS versions**

Linux Debian.

QGIS master commit ef108f3538e96d1e (2020-02-10)

**Additional context**

When we zoom in, save the project, kill qgis, restart it and open the project again, the cpu load is normal. When zooming out, it starts to increase the cpu load.

From an attached gdb session, we can see that something seems to go wrong in `QgsTemplatedLineSymbolLayerBase::collectOffsetPoints`

```
#0  0x000055555556d3ef in QArrayData::data() (this=0x7fff5c169a50) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h:59
#1  0x00007ffff372a052 in QTypedArrayData<QPointF>::data() (this=0x7fff5c169a50) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h:206
#2  0x00007ffff3729072 in QTypedArrayData<QPointF>::begin(QPointF*) (this=0x7fff5c169a50)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h:209
#3  0x00007ffff37ebb0e in QVector<QPointF>::data() (this=0x7fff67bef048) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h:127
#4  0x00007ffff37eb271 in QVector<QPointF>::operator[](int) (this=0x7fff67bef048, i=0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h:437
#5  0x00007ffff37e498a in QgsTemplatedLineSymbolLayerBase::collectOffsetPoints(QVector<QPointF> const&, QVector<QPointF>&, double, double, double, int) (p={...}, dest=<empty>, intervalPainterUnits=0, initialOffset=0, initialLag=0, numberPointsRequired=2)
    at ../src/core/symbology/qgslinesymbollayer.cpp:1594
#6  0x00007ffff37e4f58 in QgsTemplatedLineSymbolLayerBase::renderPolylineCentral(QPolygonF const&, QgsSymbolRenderContext&, double) (this=0x5555570fadf0, points=..., context=..., averageAngleOver=7.559055118110237) at ../src/core/symbology/qgslinesymbollayer.cpp:1668
#7  0x00007ffff37de9a6 in QgsTemplatedLineSymbolLayerBase::renderPolyline(QPolygonF const&, QgsSymbolRenderContext&) (this=0x5555570fadf0, points=..., context=...) at ../src/core/symbology/qgslinesymbollayer.cpp:825
#8  0x00007ffff38abea2 in QgsLineSymbol::renderPolylineUsingLayer(QgsLineSymbolLayer*, QPolygonF const&, QgsSymbolRenderContext&) (this=0x555557331480, layer=0x5555570fadf0, points=..., context=...) at ../src/core/symbology/qgssymbol.cpp:2004
#9  0x00007ffff38abb72 in QgsLineSymbol::renderPolyline(QPolygonF const&, QgsFeature const*, QgsRenderContext&, int, bool) (this=0x555557331480, points=..., f=0x7fff67befe10, context=..., layerIdx=-1, selected=false) at ../src/core/symbology/qgssymbol.cpp:1978
#10 0x00007ffff38a5553 in QgsSymbol::renderFeature(QgsFeature const&, QgsRenderContext&, int, bool, bool, int, double) (this=0x555557331480, feature=..., context=..., layer=-1, selected=false, drawVertexMarker=false, currentVertexMarkerType=1, currentVertexMarkerSize=2)
    at ../src/core/symbology/qgssymbol.cpp:913
#11 0x00007ffff381d16a in QgsFeatureRenderer::renderFeatureWithSymbol(QgsFeature const&, QgsSymbol*, QgsRenderContext&, int, bool, bool) (this=0x5555576583c0, feature=..., symbol=0x555557331480, context=..., layer=-1, selected=false, drawVertexMarker=false)
    at ../src/core/symbology/qgsrenderer.cpp:135
#12 0x00007ffff381d0fc in QgsFeatureRenderer::renderFeature(QgsFeature const&, QgsRenderContext&, int, bool, bool) (this=0x5555576583c0, feature=..., context=..., layer=-1, selected=false, drawVertexMarker=false) at ../src/core/symbology/qgsrenderer.cpp:129
#13 0x00007ffff3f6eb43 in QgsVectorLayerRenderer::drawRenderer(QgsFeatureIterator&) (this=0x555557873240, fit=...)
    at ../src/core/qgsvectorlayerrenderer.cpp:325
#14 0x00007ffff3f6e312 in QgsVectorLayerRenderer::render() (this=0x555557873240) at ../src/core/qgsvectorlayerrenderer.cpp:282
#15 0x00007ffff3d3cdc8 in QgsMapRendererParallelJob::renderLayerStatic(LayerRenderJob&) (job=...)
    at ../src/core/qgsmaprendererparalleljob.cpp:353
```

### PR DESCRIPTION
**Pull request by mhugo**
## Description

The computation of the center of a null-length line segment resulted in an infinite loop. This PR fixes that.

Fix #34396

### CODE REVIEW

File: src/core/symbology/qgslinesymbollayer.cpp [hunk 1]
```diff
@@ -1653,6 +1653,8 @@ void QgsTemplatedLineSymbolLayerBase::renderPolylineCentral( const QPolygonF &po
                            ( last.y() - it->y() ) * ( last.y() - it->y() ) );
       last = *it;
     }
+    if ( length == 0.0 )
```
Comment (m-kuhn) [inline src/core/symbology/qgslinesymbollayer.cpp]:
```suggestion
    if qgsDoubleNear ( length, 0.0 )
```

**Comment by m-kuhn** [comment]
Thanks for the fix.

I just slightly reformatted your message to make github realize the connection to the issue (it parses the comment body, not the title)

**Comment by mhugo** [comment]
@m-kuhn Great, thanks for the review

**Review by m-kuhn — APPROVED** [review]
