### PR TITLE
Server: fix label opacity when OPACITIES is set

### LINKED ISSUE #48020: opacities parameter doesn't apply to labels in GetMap requests
### What is the bug or the crash?

I have vector point layer in qgis project and set labels (rule based) based on point attributes. Both point and label show on map. If make query with opacity, it's not rendered correctly. Points will disappear and labels keep visible. So opacities url parameter in GetMap request is not affect to labels.

### Steps to reproduce the issue

image
image
image

### Versions

QGIS server version 3.22 LTR

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Fix #48020

Implement multiplyOpacity() for QgsTextFormat and use it to alter labeling opacity during server rendering.

### CODE REVIEW

File: src/core/textrenderer/qgstextformat.h [hunk 1]
```diff
@@ -360,6 +360,19 @@ class CORE_EXPORT QgsTextFormat
...
     double opacity() const;
 
+    /**
+     * Multiply opacity by \a opacityFactor.
+     *
+     * This method multiplies the opacity of all the labeling elements (text, shadow, buffer etc.)
+     * by \a opacityFactor effectively changing the opacity of the whole labeling.
+     *
+     * It is currently used by the WMS server to apply the OPACITIES parameters to the layer rendering
+     * of a GetMap request.
```
Comment (nyalldawson) [inline src/core/textrenderer/qgstextformat.h:370]: Let's drop this -- I don't like having things like this in the documentation which are highly likely to become outdated information very quickly.

File: src/core/textrenderer/qgstextformat.cpp [hunk 2]
```diff
@@ -312,6 +312,15 @@ double QgsTextFormat::opacity() const
   return d->opacity;
 }
 
+void QgsTextFormat::multiplyOpacity( double opacityFactor )
+{
+  d->opacity *= opacityFactor;
```
Comment (nyalldawson) [inline src/core/textrenderer/qgstextformat.cpp:317]:
```
if ( qgsDoubleNear( opacityFactor, 1.0 ) )
  return;
```

Just to be super-performance regression safe.

File: tests/src/python/test_qgsserver_wms_getmap.py [hunk 3]
```diff
@@ -2108,6 +2112,110 @@ def test_temporal_properties(self):
...
+        server = QgsServer()
+        server.handleRequest(request, response, project)
+        image = QImage.fromData(response.body(), "PNG")
+        image.save('/tmp/img.png')
+        # Text
+        self.assertEqual(image.pixelColor(105, 84).name(), '#5f5f5f')
+        # Buffer
+        self.assertEqual(image.pixelColor(92, 84).name(), '#bfbfbf')
+        # Shadow
+        self.assertEqual(image.pixelColor(169, 136).name(), '#f0f0f0')
```
Comment (nyalldawson) [inline tests/src/python/test_qgsserver_wms_getmap.py:2189]: could we use the standard render checker approach here? I'm concerned that these tests will be tricky to debug if they start failing in future (eg due to qt rendering changes)

File: src/server/services/wms/qgswmsrestorer.h [hunk 4]
```diff
@@ -56,6 +57,7 @@ class QgsLayerRestorer
     {
       QString name;
       double mOpacity;
+      QgsAbstractVectorLayerLabeling *mLabeling = nullptr;
```
Comment (nyalldawson) [inline src/server/services/wms/qgswmsrestorer.h:60]: unique ptr?

File: src/core/labeling/qgsvectorlayerlabeling.h [hunk 5]
```diff
@@ -99,6 +100,17 @@ class CORE_EXPORT QgsAbstractVectorLayerLabeling
...
 
+    /**
+     * Multiply opacity by \a opacityFactor.
+     *
+     * This method multiplies the opacity of the labeling elements (text, shadow, buffer etc.)
+     * by \a opacity effectively changing the opacity of the whole labeling elements.
+     *
+     * \since QGIS 3.32
+     */
+    virtual void multiplyOpacity( double opacityFactor ) = 0;
```
Comment (nyalldawson) [inline src/core/labeling/qgsvectorlayerlabeling.h:111]: Making this pure virtual is an api break -- I'd go with:

```suggestion
    virtual void multiplyOpacity( double opacityFactor ) { Q_UNUSED( opacityFactor ); };
```

File: src/server/services/wms/qgswmsrestorer.h (hunk 4 above)
Comment (elpaso) [reply src/server/services/wms/qgswmsrestorer.h:60]: This is tricky, because the settings struct is copied. 

Technically the settings never owns the resource, it just keeps it for the duration of its lifetime and transfers it back to the layer when the destructor is called.

Also , the struct is private and it's not exposed to API,  given the (non-copyable) complications of turning this into a unique_ptr  I'd rather not follow your advice.

Comment (elpaso) [reply src/server/services/wms/qgswmsrestorer.h]: BTW here is an attempt: https://github.com/qgis/QGIS/pull/53438/commits/ae23847c5998208d22343ef89bb0b8dbbaa8fe14

**Comment by elpaso** [comment]
ping @rldhont @pblottiere can you please review so that I can merge in time for the next release ?
