### PR TITLE
[OGR provider] Iterate only one feature if having to guess the layer geometry type of a OGCAPI layer

### LINKED ISSUE #58174: QGIS unable to open vector tiles using OGCAPI
### What is the bug or the crash?

It is unclear whether vector tiles should be opened using the "Add Raster Layer" option, or "Add Vector Layer" option, as the [OGCAPI driver](https://gdal.org/drivers/raster/ogcapi.html) is part of the raster drivers of GDAL. However, none of these options work.

### Steps to reproduce the issue

Go to "Add Vector Layer..." and select `OGCAPI` and add the following endpoint: https://maps.gnosis.earth/ogcapi/collections/montreal

In API options, select "Tiles"
image

QGIS will get stuck in a loop trying to read the zoom levels

Screenshot from 2024-07-18 21-02-22

Trying to read the layer using "Add Raster Layer..." also won't work, as QGIS will try to read bands from a raster image and then fail with this message:

`   CRITICAL    Invalid Data Source : OGCAPI:https://demo.pygeoapi.io/master/collections/lakes|option:API=TILES is not a valid or recognized data source.`

Screenshot from 2024-07-18 21-05-52

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.39.0-Master
-- | --
QGIS code revision | 399f7df1c7
Qt version | 5.15.3
Python version | 3.10.3 (Compiled)(Running)
GDAL/OGR version | 3.10.0dev-126a88523a
PROJ version | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.37.2
PDAL version | 2.6.2

</body></html>QGIS version
3.39.0-Master
QGIS code revision
[399f7df1c7](https://github.com/qgis/QGIS/commit/399f7df1c7)
Qt version
5.15.3
Python version
3.10.3 (Compiled)
(Running)
GDAL/OGR version
3.10.0dev-126a88523a
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.37.2
PDAL version
2.6.2

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Opening the layer using GDAL appears to be working correctly:

```
 ogrinfo "OGCAPI:https://maps.gnosis.earth/ogcapi/collections/montreal" -oo API=TILES
INFO: Open of `OGCAPI:https://maps.gnosis.earth/ogcapi/collections/montreal'
      using driver `OGCAPI' successful.
Metadata:
  TITLE=montreal
1: Zoom level 0
2: Zoom level 1
3: Zoom level 2
4: Zoom level 3
5: Zoom level 4
6: Zoom level 5
7: Zoom level 6
8: Zoom level 7
9: Zoom level 8
10: Zoom level 9
11: Zoom level 10
12: Zoom level 11
13: Zoom level 12
14: Zoom level 13
15: Zoom level 14

```

### PR DESCRIPTION
**Pull request by rouault**
Fixes #58174

### CODE REVIEW

File: src/core/network/qgsblockingnetworkrequest.h [hunk 1]
```diff
@@ -82,7 +84,7 @@ class CORE_EXPORT QgsBlockingNetworkRequest : public QObject
      *
      * \see post()
      */
-    ErrorCode get( QNetworkRequest &request, bool forceRefresh = false, QgsFeedback *feedback = nullptr );
+    ErrorCode get( QNetworkRequest &request, bool forceRefresh = false, QgsFeedback *feedback = nullptr, bool emptyResponseIsError = true );
```
Comment (nyalldawson) [inline src/core/network/qgsblockingnetworkrequest.h:87]: Instead of a bool argument, could we go for a "flags" approach instead? That'd avoid risk of a bloating the signature if we need additional options in future...

Comment (rouault) [reply src/core/network/qgsblockingnetworkrequest.h]: good idea, done

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
Oh no, you've angered the sip gods :scream_cat: 

You'll have to randomly change https://github.com/qgis/QGIS/blob/master/CMakeLists.txt#L1106 until they accept your sacrifice and offer you their forgiveness.

File: src/core/network/qgsblockingnetworkrequest.h [hunk 2]
```diff
@@ -281,11 +297,14 @@ class CORE_EXPORT QgsBlockingNetworkRequest : public QObject
     //! Whether we already received bytes
     bool mGotNonEmptyResponse = false;
 
+    //! Request floags
```
Comment (nicogodet) [inline src/core/network/qgsblockingnetworkrequest.h:300]:
```suggestion
    //! Request flags
```

Comment (rouault) [reply src/core/network/qgsblockingnetworkrequest.h]: done
