### PR TITLE
Fix editor vertex with "non-dot" locales

### LINKED ISSUE #29682: can't change value in vertex editor if "locale" settings use commas as decimal separator
Author Name: **Giovanni Manghi** (@gioman)
Original Redmine Issue: [21867](https://issues.qgis.org/issues/21867)
Affected QGIS version: 3.6.1
Redmine category:digitising

---
if you have a locale that uses commas as decimal separator then manually editing values in the vertex editor does not work. Workaround: set QGIS locale to English.

---

Related issue(s): #29811 (duplicates)
Redmine related issue(s): [21996](https://issues.qgis.org/issues/21996)

---

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #29682

### CODE REVIEW

File: src/app/vertextool/qgsvertexeditor.cpp [hunk 1]
```diff
@@ -499,4 +499,11 @@ void CoordinateItemDelegate::setModelData( QWidget *editor, QAbstractItemModel *
   }
 }
 
-
+void CoordinateItemDelegate::setEditorData( QWidget *editor, const QModelIndex &index ) const
+{
+  QLineEdit *lineEdit = qobject_cast<QLineEdit *>( editor );
+  if ( lineEdit && index.isValid() )
+  {
+    lineEdit->setText( QLocale().toString( index.data( ).toDouble( ) ) );
```
Comment (nyalldawson) [inline src/app/vertextool/qgsvertexeditor.cpp:507]: Should we use a fixed precision here to avoid scientific notation values?

Comment (elpaso) [reply src/app/vertextool/qgsvertexeditor.cpp]: Yes, good point, I'll use the same format as in displayText.
