### PR TITLE
fix #30028 Closing Vertex Edititor crashes the app

### LINKED ISSUE #30028: Closing Vertex Edititor crashes the app.
Closing the Vertex Editor panel cause QGIS crash.
This however happens **only when the panel is not docked** (is free floating).

**How to Reproduce**

1. Make a vector layer editable
2. Use Vertex Tool (Vertex Editor panel appears docked; IDK if this is a default behavior)
3. On Vertex Editor panel click the resize icon (in upper-right corner); the panel gets undocked.
4. Click Close icon (x) on the panel: the app crashes immediately.

Position of the panel relative to other windows and panels seems irrelevant. 

**Desktop environment:**

 - OS and version: Win 7 Home Premium SP1
**Dual screen workspace** (this may be important).

**QGIS version**
- 3.6.3

**Additional context**
I had other issues with GUI - probably related to dual screen workspace - like crashing when a panel was dragged over a map window on secondary monitor (https://github.com/qgis/QGIS/issues/29928)

### PR DESCRIPTION
**Pull request by PeterPetrik**
fix #30028

double delete of mVertexEditor (`unique_ptr` in context of Qt's events)

### CODE REVIEW

File: src/app/vertextool/qgsvertextool.cpp [hunk 1]
```diff
@@ -313,6 +313,8 @@ QgsVertexTool::~QgsVertexTool()
   delete mVertexBand;
   delete mEdgeBand;
   delete mEndpointMarker;
+  if ( mVertexEditor )
+    delete mVertexEditor;
```
Comment (wonder-sk) [inline src/app/vertextool/qgsvertextool.cpp]: no need to do "if (x) delete x;" - just do "delete x;"
and we probably don't need to do that anyway since the vertex editor widget has a parent (which will take care of its deletion)

File: src/app/vertextool/qgsvertextool.cpp [hunk 2]
```diff
@@ -1411,7 +1413,11 @@ void QgsVertexTool::showVertexEditor()  //#spellok
 void QgsVertexTool::cleanupVertexEditor()
 {
   mLockedFeature.reset();
-  mVertexEditor.reset();
+  // do not delete immediately because vertex editor
+  // can be still used in the qt event loop
+  mVertexEditor->deleteLater();
+  mVertexEditor = nullptr;
```
Comment (wonder-sk) [inline src/app/vertextool/qgsvertextool.cpp]: it's not necessary to do `mVertexEditor = nullptr;` if we are using QPointer (it would be needed if we used raw pointer)

**Review by wonder-sk — APPROVED** [review]
Looking good. I think we should not use unique_ptr for QObject-based classes in QGIS code to avoid exactly this kind of crashes due to forced delete too early.
