### PR TITLE
Fix 3D CRS becoming stale

### LINKED ISSUE #65122: 3D map CRS reported as 'unnamed' after EPSG:2958 point cloud layer
### What is the bug or the crash?

3D map view reports incorrect CRS after loading a point cloud layer with a specific CRS – EPSG:2958.

Checking the 3D map CRS after loading such a point cloud is reported as `unnamed`, while the same thing doesn’t happen when loading a GPKG layer in the same CRS.

Once broken, the state remains broken, removing the layer and opening a fresh 3D map will continue reporting wrong CRS.

Image

### Steps to reproduce the issue

Take a sip of coffee…

1.) Load the world dataset (type in `world` in `Coordinates`).
2.) Open new 3D Map and go to `Configure…` → `Lights` → `Add new` → Check the label reporting CRS (it should say EPSG:3857).
3.) Close the 3D Map, remove the world layer.
4.) Add the [3d_map_breaking_2958_bug.copc.laz.zip](https://github.com/user-attachments/files/25600067/3d_map_breaking_2958_bug.copc.laz.zip) and repeat the second step – you will now notice CRS is reported as `unnamed`.
5.) Close the 3D Map, remove the layer.
6.) Repeat steps 1 and 2, but while checking the CRS, you should notice the CRS is still stuck being reported as `unnamed`.

Every new 3D Map after that reports `unnamed` CRS for any data, while the 2D map shows the correct CRS.

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.99.0-Master</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/825888e6fa3">825888e6fa3</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>6.10.1</td></tr><tr><td>Python version</td><td>3.14.2</td></tr><tr><td>GDAL version</td><td>3.11.5 — <i>Eganville</i></td></tr><tr><td>PROJ version</td><td>9.6.2</td></tr><tr><td>EPSG Registry database version</td><td>v12.013 (2025-05-26)</td></tr><tr><td>GEOS version</td><td>3.14.1-CAPI-1.20.5</td></tr><tr><td>SFCGAL version</td><td>No support</td></tr><tr><td>GeographicLib version</td><td>No support</td></tr><tr><td>SQLite version</td><td>3.50.2</td></tr><tr><td>PDAL version</td><td>2.9.3</td></tr><tr><td>PostgreSQL client version</td><td>18.1</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.2.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Fedora Linux 43 (KDE Plasma Desktop Edition)</td></tr><tr><td colspan="2"><i>This copy of QGIS writes debugging output.</i></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ViperMiniQ**
fixes: #65122

Since mVerticalCrs is not reset in this method, when rebuilding the 3D CRS, we could end up getting unexpected results, since rebuilding of it depends on the value of mVerticalCrs.

### CODE REVIEW

**Comment by ViperMiniQ** [comment]
This is a bit more complicated, I was hoping for simple fix.
I'll leave the PR open as a note to self to explore a bit more in the future.

File: src/gui/layertree/qgslayertreemapcanvasbridge.cpp [hunk 1]
```diff
@@ -124,10 +124,7 @@ void QgsLayerTreeMapCanvasBridge::setCanvasLayers()
         // Only adjust ellipsoid to CRS if it's not set to planimetric
         QgsProject::instance()->setCrs( mFirstCRS.horizontalCrs(), !planimetric );
         const QgsCoordinateReferenceSystem vertCrs = mFirstCRS.verticalCrs();
-        if ( vertCrs.isValid() )
-        {
-          QgsProject::instance()->setVerticalCrs( vertCrs );
-        }
+        QgsProject::instance()->setVerticalCrs( vertCrs.isValid() ? vertCrs : QgsCoordinateReferenceSystem() );
```
Comment (rouault) [inline src/gui/layertree/qgslayertreemapcanvasbridge.cpp]: wouldn't the following just work ?
```suggestion
        QgsProject::instance()->setVerticalCrs( vertCrs );
```

Comment (ViperMiniQ) [reply src/gui/layertree/qgslayertreemapcanvasbridge.cpp]: :facepalm:
commit amended.

**Review by rouault — APPROVED** [review]
