### PR TITLE
fix(QgsMapToolCapture): Allow snapping point with different crs

### LINKED ISSUE #59792: Z-Coordinate not transferred when snapping between features in different coordinate systems
### What is the bug or the crash?

When snapping from one feature to another (e.g., snapping a line feature to a point feature), the Z-coordinate is not transferred if the two features have different coordinate systems.

While it is understandable that the Z-coordinate datum may be undefined in certain scenarios, this behavior seems counterintuitive in most practical cases. Typically, if a user is snapping features, it is likely that they expect the Z-datum to be consistent or compatible between the features. The current behavior can result in unintended outcomes and additional manual corrections for users.

### Steps to reproduce the issue

1. Create two scratch layers with point geometries, each using a different coordinate system.
2. Create a third scratch layer with line geometries, using a coordinate system that matches one of the point layers.
3. Draw lines between the points in the two point layers.
4. Observe whether the Z-coordinates from the points are transferred to the snapped vertices of the lines.

Video (default z-value is set to -99):
qgis-bin_UQbECGidmY

### Versions

QGIS-version
3.38.2-Grenoble
QGIS-koderevision
130c432394
Qt version
5.15.13
Python version
3.12.5
GDAL/OGR version
3.9.2
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL klient version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009

Aktive Python plugins
batchvectorlayersaver
0.9
changeDataSource
3.1
Coordtransform
1.1
Dataforsyningen
0.5
disconnected-islands
2.1.0
dmpcatalogue
1.2.0
geofa
0.36
geosearch_dk
2.0.4
latlontools
3.7.2
MapRegv2
1.0
MultipleLayerSelection
2.0.1
openlayers_plugin
2.0.0
pluginbuilder3
3.2.1
plugin_reloader
0.17
PointConnector
2.0
profile-manager
0.31
QGISSortAndNumber-master
1.0
QlrBrowser
3.0.0
quick_map_services
0.19.36
SentinelHub
2.0.2
slyr_community
5.0.0
StreetView
3.2
Submission
0.10
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lbartoletti**
## Description

fixes #59792

### CODE REVIEW

File: src/gui/maptools/qgsmaptoolcapture.cpp [hunk 1]
```diff
@@ -642,10 +642,6 @@ int QgsMapToolCapture::fetchLayerPoint( const QgsPointLocator::Match &match, Qgs
   {
     if ( ( match.hasVertex() || match.hasLineEndpoint() ) )
     {
-      if ( sourceLayer->crs() != vlayer->crs() )
```
Comment (nyalldawson) [inline src/gui/maptools/qgsmaptoolcapture.cpp:645]: Can you update the documentation for fetchLayerPoint? It explicitly mentions "if if has the same CRS as the current layer", and "1 if not applicable (CRS mismatch / invalid layer)"

Comment (lbartoletti) [reply src/gui/maptools/qgsmaptoolcapture.cpp:645]: Right! done

**Review by nyalldawson — APPROVED** [review]

**Comment by agiudiceandrea** [comment]
Please have a look at the regression reported at https://github.com/qgis/QGIS/issues/60868 which may be related with this PR.

File: src/gui/maptools/qgsmaptoolcapture.cpp [hunk 2]
```diff
@@ -674,6 +671,10 @@ int QgsMapToolCapture::fetchLayerPoint( const QgsPointLocator::Match &match, Qgs
           layerPoint.dropMValue();
         }
 
+        if ( sourceLayer->crs() != vlayer->crs() )
+        {
+          layerPoint = toLayerCoordinates( vlayer, layerPoint );
+        }
```
Comment (roya0045) [inline src/gui/maptools/qgsmaptoolcapture.cpp:677]: Doesn't this extra transformation cause #60927 & #60868 ?

Comment (lbartoletti) [reply src/gui/maptools/qgsmaptoolcapture.cpp:677]: Yes, but fixes #59792 ... When I found a for one, it's adding regression to another one...
Was AFK last days, and working on it since this morning, and sometimes I would expect that projection doesn't exist...
Anyway, I found other strange logic in QgsMapToolCapture. I hope to find a solution soon...

**Comment by agiudiceandrea** [comment]
Another issue report probably related to this PR: https://github.com/qgis/QGIS/issues/60989.
