### PR TITLE
Fix new profile map scales

### LINKED ISSUE #52383: Scale listbox do not working in QGIS version 3.30.0-'s-Hertogenbosch
### What is the bug or the crash?

Scale listbox do not working in QGIS version 3.30.0-'s-Hertogenbosch.
Scale_listbox

### Steps to reproduce the issue

Open QGIS and click on scale listbox.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.30.0-'s-Hertogenbosch | QGIS code revision | f186b8efe0e
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.30.0-'s-Hertogenbosch
QGIS code revision
[f186b8efe0e](https://github.com/qgis/QGIS/commit/f186b8efe0e)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by YoannQDQ**
- Fixes #52383
## Description

This completes #52511 to fix issues regarding the map scale in QGIS 3.30.1

The map scale setting format has changed (QString -> QStringList). When QGIS launches, if the new setting do not exist, it is initailized from the old key. For new profiles however, the old key does not exist either, causing the default scales to be overwritten with an empty string (which also caused crashes, solved by #52511).

This PR checks if the old key actually exists before attempting to migrate it.

### CODE REVIEW

**Review by 3nids — APPROVED** [review]

**Comment by agiudiceandrea** [comment]
@YoannQDQ, I've tested the MingW64 Windows 64bit Build of this PR.
It fixes the issue using a new QGIS user profile with QGIS 3.30, while it seems to me it doesn't fix the issue using a QGIS 3.28 user profile with QGIS 3.30 as described e.g. in https://github.com/qgis/QGIS/issues/52383#issuecomment-1494474868 and https://github.com/qgis/QGIS/issues/52383#issuecomment-1494507595.

File: src/core/settings/qgssettingsregistrycore.cpp [hunk 1]
```diff
@@ -151,7 +151,7 @@ void QgsSettingsRegistryCore::migrateOldSettings()
   pal::Pal::settingsRenderingLabelCandidatesLimitPolygons->copyValueFromKey( QStringLiteral( "core/rendering/label_candidates_limit_polygons" ), true );
 
   // migrate only one way for map scales
-  if ( !settingsMapScales->exists() )
+  if ( !settingsMapScales->exists() && QgsSettings().contains( QStringLiteral( "Map/scales" ) ) )
```
Comment (3nids) [inline src/core/settings/qgssettingsregistrycore.cpp:154]: // handle bad migration (TODO remove in 3.32 or later)
  if ( settingsMapScales->value() == QString( "" ) )
    settingsMapScales->remove();

Adding this should fix former issues

**Comment by agiudiceandrea** [comment]
It seems to me the behaviour with the new commit is the same as with the previous one: it fixes the issue using a new QGIS user profile with QGIS 3.30, while it doesn't fix the issue using a QGIS 3.28 user profile with QGIS 3.30 as described e.g. in https://github.com/qgis/QGIS/issues/52383#issuecomment-1494474868 and https://github.com/qgis/QGIS/issues/52383#issuecomment-1494507595.

**Comment by YoannQDQ** [comment]
Hopefuly fixed now.

**Comment by agiudiceandrea** [comment]
@YoannQDQ, now the list of scales that is set by an user in Settings->Options->Map Tools in QGIS 3.28 and previous versions, is completely removed by QGIS and substituted to the predefined list of scales.
Why not actually use the list of scales already present in the settings, instead of removing it. I think it would be better.

**Comment by agiudiceandrea** [comment]
It seems to me now the reported issues (with a new user profile and with an old user profile) are completely fixed in the MingW64 Windows 64bit build of this PR. Thanks @YoannQDQ!

@3nids do you know if there are other settings changed from QString to QStringList that needs a better handling like it was needed for the `scale` setting?

It remains open the question about the backward incompatibility: using a QGIS <= 3.28 user profile with QGIS >= 3.30.2 will permanently change the `scales` settings in a way that it will not be properly read again by QGIS <= 3.28.

@3nids do you think the users should be made aware of such backward incompatibility of the `scales` settings and any other settings changed from QString to QStringList?

**Review by 3nids — APPROVED** [review]

**Comment by 3nids** [comment]
Thanks a lot for this @YoannQDQ and @agiudiceandrea for the detailed report.

There is no backward incompatibility since the settings keys are not the same (it's a migration). 

There are other QStringList based settings but I think they are not affected by this issue (I'll check this when I'll be back with a computer).

Thanks again

**Comment by agiudiceandrea** [comment]
> There is no backward incompatibility since the settings keys are not the same (it's a migration).

@3nids, it seems to me it is the same setting and I've checked that the `scales` setting is permanently changed and it is no longer properly read again by QGIS <= 3.28 after the QGIS user profile is used by QGIS form the MingW64 Windows 64bit build of this PR.

**Comment by 3nids** [comment]
Strange, the section was changed from Map to map. I believe the case matters. And there is no deletion of the old setting in the migration. Can you check if both exist (upper and lower case section)?

**Comment by agiudiceandrea** [comment]
> Can you check if both exist (upper and lower case section)?

After opening a QGIS <= 3.28 user profile with QGIS form the MingW64 Windows 64bit build of this PR, there is only 1 `scales` setting in the [Map] (uppercase) section in QGIS3.ini. There is no [map] section.

**Comment by YoannQDQ** [comment]
> I believe the case matters

Actually, it does on Ubuntu for instance, but not on Windows. So Windows users will encounter the problem @agiudiceandrea describes. We can either rename the sTreeMap key to something meaningful other than "map" (not too difficult since it isn't wide-spread yet). Otherwise, profiles will effectively be backward incompatible.Thoughts @3nids ?

**Comment by YoannQDQ** [comment]
@3nids Do you feel like this can now be merged?

**Comment by agiudiceandrea** [comment]
@YoannQDQ, it seems to me the issue is not yet fixed.

In a user profile in QGIS <= 3.28, QGIS3.ini contains e.g.:
```
[Map]

scales="1:5000,1:4000,1:3000,1:2000,1:1000"
```
Using such user profile with QGIS from this PR (MingW64 Windows 64bit Build, actually from https://github.com/agiudiceandrea/QGIS/pull/104, because the MingW64 build here failed), QGIS3.ini contains:

```
[Map]

scales="1:5000,1:4000,1:3000,1:2000,1:1000"
default_scales="1:5000,1:4000,1:3000,1:2000,1:1000"
```

and again...

image

**Comment by YoannQDQ** [comment]
... You're right. Let's try again!

File: src/core/settings/qgssettingsregistrycore.cpp [hunk 2]
```diff
@@ -150,10 +150,37 @@ void QgsSettingsRegistryCore::migrateOldSettings()
   pal::Pal::settingsRenderingLabelCandidatesLimitLines->copyValueFromKey( QStringLiteral( "core/rendering/label_candidates_limit_lines" ), true );
   pal::Pal::settingsRenderingLabelCandidatesLimitPolygons->copyValueFromKey( QStringLiteral( "core/rendering/label_candidates_limit_polygons" ), true );
 
+  // handle bad migration - Fix profiles for old QGIS versions (restore the Map/scales key on windows)
```
Comment (3nids) [inline src/core/settings/qgssettingsregistrycore.cpp:153]: can we maybe add a note to drop this when 3.34 is released (which becomes next LTR)?

**Review by 3nids — APPROVED** [review]
This looks good to me.
Sorry for this and thanks a lot for fixing it!

File: src/core/settings/qgssettingsregistrycore.cpp (hunk 2 above)
Comment (YoannQDQ) [reply src/core/settings/qgssettingsregistrycore.cpp:153]: Is it safe to assume no one will upgrade from 3.30.0|1 to 3.34.X though?

Comment (3nids) [reply src/core/settings/qgssettingsregistrycore.cpp:153]: you're right, bump it to 3.36, so 3.34 is LTR and 3.28 is not supported anymore.
and....if the user could live for 1 year with the bug, I'd say it's ok to drop backward compatibility of an unsupported version. It's not a big deal, but that code is not really explicit, so I'd rather avoid keeping it. Alaso a link to this PR might help too.

**Comment by YoannQDQ** [comment]
@3nids Hum. Shouldn't the backport_release_3.30 PR have been created automatically?

**Comment by agiudiceandrea** [comment]
@YoannQDQ, only now have I had the opportunity to test this PR.
1. With a new user profile: QGIS from this PR now only stores the scales list in `default_scales` setting as QStringList.
This setting is not used by QGIS 3.28, so the custom scales set in QGIS from this PR will not be read by QGIS 3.28 using the same user profile.
2. With a profile created by QGIS 3.30.1 which contains e.g. a QStringList `scales=1:1000, 1:2000, 1:3000` setting: QGIS from this PR creates two settings: a QString `scales="1:1000,1:2000,1:3000"` setting and a QStringList `default_scales=1:1000, 1:2000, 1:3000` setting.
3. With a profile created by QGIS <= 3.28 which contains e.g. a QString `scales=1:1000,1:2000,1:3000` setting: QGIS from this PR adds the QStringList `default_scales=1:1000, 1:2000, 1:3000` setting.

For all the cases, the scales list modified by QGIS 3.28 and QGIS >= 3.30.2 will be stored in separate settings in the same user profile so the list read by QGIS 3.28 may be different from the list read by QGIS >= 3.30.2 for the same user profile.

Anyway, now QGIS no longer crashes and the scales list in the old settings is preserved and it is correctly migrated from the old setting to the new setting, but only one-way (3.28 -> 3.30.2) while it seems to me it is not for the other way round (3.30.2 -> 3.28).

@3nids, I'm concerned if there are other settings changed from QString to QStringList (or other type changing) that needs a better handling like it was needed for the `scales` setting.

**Comment by 3nids** [comment]
>  while it seems to me it is not for the other way round (3.30.2 -> 3.28).

Yes, migration is only forward and not backward for this one. It could be added now that we have changed the name of the keys. But is it really worth it?

> I'm concerned if there are other settings changed from QString to QStringList

as far as I remember and from a quick check now, no it's the only migration. There are other usages but they were already a list of strings.

**Comment by agiudiceandrea** [comment]
> rom a quick check now, no it's the only migration.

Thanks for checking. Since it is the only one, I think it would have been preferable to leave also such setting as it was, in order to avoid these issues.
