### PR TITLE
MSSQL: fix add/fill ring

### LINKED ISSUE #53698: [MSSQL] Add Ring throw SQL Error while saving edits
### What is the bug or the crash?

Can't Save edits after add ring oder fill ring on a MSSQL MultiPolygon Layer

grafik

### Steps to reproduce the issue

1.     You need a MSSQL Multipolygon Layer
2.     You have a Multipolygon or add a new one
3.     Add a ring to this Multipolygon (see screenshot) or Button "Fill Ring" produce same error
4.     click save edits
5.     error appear

### Versions

QGIS 3.28.8
MSSQL Provider

there are no issues with PostgreSQL

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Fix #53698

Funded by: All My Favourite Things ♬

### CODE REVIEW

File: src/core/geometry/qgspolygon.cpp [hunk 1]
```diff
@@ -185,6 +185,50 @@ QByteArray QgsPolygon::asWkb( QgsAbstractGeometry::WkbFlags flags ) const
...
+      {
+        // Type names of linear geometries are omitted
+        childWkt = childWkt.mid( childWkt.indexOf( '(' ) );
+      }
+      wkt += childWkt + ',';
+    }
+    for ( const QgsCurve *curve : mInteriorRings )
+    {
+      QString childWkt;
+      if ( true || curve->hasCurvedSegments() )
```
Comment (nyalldawson) [inline src/core/geometry/qgspolygon.cpp:210]: Hmm, what's the actual issue here? Is it a bad geometry with curved rings in a polygon type?

Comment (elpaso) [reply src/core/geometry/qgspolygon.cpp:210]: Yes, actually I've just found a couple of duplicated issues:  https://github.com/qgis/QGIS/issues/50869 and probably a better fix in https://github.com/qgis/QGIS/pull/55371

I am in favor of closing this if #55371 fixes this issue.

Comment (elpaso) [reply src/core/geometry/qgspolygon.cpp:210]: We are even expecting invalid WKT in the test: https://github.com/qgis/QGIS/blob/master/tests/src/app/testqgsmaptooladdring.cpp#L166 , that should not have been accepted in the first place.

Comment (elpaso) [reply src/core/geometry/qgspolygon.cpp:210]: @nyalldawson I thought about this, IMO the best course of action is to fix the wrong geometry generation in the first place (i.e. fix the maptool or the editing utils which generates the wrong geometry) but also to leave the WKT export cleaning code, because the "perfect" solution which is rewrite the geometry classes in a way that makes it impossible to construct an invalid POLYGON implies a deep refactoring and its way out of scope for this bug fixing effort. And because we don't know how many times and where exactly this wrong geometries can be generated by the QGIS application or by other code which uses the QGIS API.

Comment (lbartoletti) [reply src/core/geometry/qgspolygon.cpp:210]: @elpaso I agree with you. Having worked on it extensively, I've initiated several PRs to address these issues, but there's still a lot to be done. The challenge lies in QGIS being quite lenient on input; it's not necessarily a problem, as users tend to complain otherwise. However, ensuring the accuracy of exports is crucial. I've started working on these matters, but it's still a work in progress.

Comment (elpaso) [reply src/core/geometry/qgspolygon.cpp:210]: @lbartoletti since you know very well the topic and the issues can you please have a look to this PR?

File: src/core/geometry/qgspolygon.cpp [hunk 2]
```diff
@@ -185,6 +185,50 @@ QByteArray QgsPolygon::asWkb( QgsAbstractGeometry::WkbFlags flags ) const
   return wkbArray;
 }
 
+QString QgsPolygon::asWkt( int precision ) const
```
Comment (lbartoletti) [inline src/core/geometry/qgspolygon.cpp:188]: It seems there might be confusion in handling the geometry types. Your test highlights the degenerate WKT output resulting from adding a curve to your polygon. The output generated is `Polygon ((0 0, 0 10, 10 10, 10 0, 0 0),CompoundCurve ((1 1, 1 9, 9 9, 9 1, 1 1)))`, which is invalid. To rectify this, it should ideally be of the type `CurvePolygon ((0 0, 0 10, 10 10, 10 0, 0 0),CompoundCurve ((1 1, 1 9, 9 9, 9 1, 1 1)))`, but that belongs to `QgsCurvePolygon `and not `QgsPolygon`.

To ensure incoming geometries into `QgsPolygon `are segmented properly, it's essential to verify that the layer is indeed of type Polygon and not CurvePolygon. 

As it stands, this fixes the issue, but I'm not sure if it might be masking the real problem that has been occurring in the recent editing versions. AFAIR, it worked before (c)

File: src/providers/mssql/qgsmssqlprovider.cpp [hunk 3]
```diff
@@ -358,6 +359,29 @@ bool QgsMssqlProvider::execLogged( QSqlQuery &qry, const QString &sql, const QSt
   return res;
 }
 
+bool QgsMssqlProvider::execPreparedLogged( QSqlQuery &qry, const QString &queryOrigin ) const
```
Comment (lbartoletti) [inline src/providers/mssql/qgsmssqlprovider.cpp:362]: Is it possible to separate the PR in two. One for the polygon fix and another for the MSSQL improvement?

File: tests/src/core/geometry/testqgspolygon.cpp [hunk 4]
```diff
@@ -2833,6 +2833,27 @@ void TestQgsPolygon::toFromWKT()
...
+  pl3.setExteriorRing( ext3 );
+  QgsLineString *ring3 = new QgsLineString();
+  ring3->setPoints( QgsPointSequence() << QgsPoint( Qgis::WkbType::Point, 1, 1 )
+                    << QgsPoint( Qgis::WkbType::Point, 1, 9 )
+                    << QgsPoint( Qgis::WkbType::Point, 9, 9 )
+                    << QgsPoint( Qgis::WkbType::Point, 9, 1 )
+                    << QgsPoint( Qgis::WkbType::Point, 1, 1 ) );
+  QgsCompoundCurve *compound = new QgsCompoundCurve();
+  compound->addCurve( ring3 );
+  pl3.addInteriorRing( compound );
```
Comment (lbartoletti) [inline tests/src/core/geometry/testqgspolygon.cpp:2854]: I haven't tested, but `addInteriorRing` [uses ](https://github.com/qgis/QGIS/blob/88c4063e262a1497f927e612455efc498b531a2e/src/core/geometry/qgspolygon.cpp#L240) `curveToLine` whereas `setExteriorRing` [uses ](https://github.com/qgis/QGIS/blob/88c4063e262a1497f927e612455efc498b531a2e/src/core/geometry/qgspolygon.cpp#L273) `segmentize`

File: src/providers/mssql/qgsmssqlprovider.cpp (hunk 3 above)
Comment (elpaso) [reply src/providers/mssql/qgsmssqlprovider.cpp:362]: Everything is possible, but takes time, since I am doing this as a volunteer in my spare time for the glory of the project I think we should be tolerant and weight the pros and cons. 

I don't guarantee I'll find the motivation.

File: src/core/geometry/qgspolygon.cpp (hunk 2 above)
Comment (elpaso) [reply src/core/geometry/qgspolygon.cpp:188]: I agree, and we already discussed that in https://github.com/qgis/QGIS/pull/55588#discussion_r1425165009

I don't really know when it was broken, my gut feeling is that it was broken when the maptool started generating compound curves (even when not necessary). 

But, as I already wrote, the real issue IMO is that the API allows to construct an "invalid" QgsPolygon, but we cannot change that without breaking the API. 

So, I cannot think of another solution than to be good citizens and to produce valid WKT from and "invalid" polygon.

File: tests/src/core/geometry/testqgspolygon.cpp (hunk 4 above)
Comment (elpaso) [reply tests/src/core/geometry/testqgspolygon.cpp:2854]: That is irrelevant for this bug because: 
```c++
if ( ring->hasCurvedSegments()  ) ... 
```
isn't `true` so `curveToLine` is never called.

Maybe it is worth another issue though if in other situations it that produecs a different output.

The relevant fact here is that `compound` is a QgsCompoundCurve and this produces a "CompoundCurve" in the generated WKT.

**Review by lbartoletti — APPROVED** [review]
@elpaso let's try this fix!
