### PR TITLE
[OGR provider] Recognize "false"/"true" string as valid value for a boolean field in addFeature()/changeAttributeValues()"

### LINKED ISSUE #55517: Saving feature in vector layer with default boolean value represented by string
### What is the bug or the crash?

Saving feature in vector layer with default boolean value represented by string  is not working anymore in QGIS 3.34.x
This was introduced in https://github.com/qgis/QGIS/pull/54905/files 

It may be bug or feature (?), but definitely it is change of behaviour between versions. 

If the new behaviour is intended, feel free to close the bug report.

### Steps to reproduce the issue

1. open project in QGIS 3.34.0 or 3.34.1
project has boolean field that is populated by string `'true'` or `'false'` as default value 
2. add new point
3. end digitizing 
4. on save  `wrong data type for attribute 1 of feature -2: 10`

Project:
[truefalseregression.zip](https://github.com/qgis/QGIS/files/13561993/truefalseregression.zip)

Error:
Screenshot 2023-12-05 at 15 52 00

### Versions

3.34.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rouault**
Fixes #55517

### CODE REVIEW

File: src/core/providers/ogr/qgsogrprovider.cpp [hunk 1]
```diff
@@ -1895,7 +1930,10 @@ bool QgsOgrProvider::addFeaturePrivate( QgsFeature &f, Flags flags, QgsFeatureId
 
       if ( !ok )
       {
-        pushError( tr( "wrong data type for attribute %1 of feature %2: %3" ).arg( qgisAttributeId ) .arg( f.id() ).arg( qType ) );
+        if ( !errorEmitted )
+        {
+          pushError( tr( "wrong data type for attribute %1 of feature %2: %3" ).arg( qgisAttributeId ) .arg( f.id() ).arg( qType ) );
```
Comment (agiudiceandrea) [inline src/core/providers/ogr/qgsogrprovider.cpp:1935]: Wouldn't it be better to display the type name instead of the QVariant::type enum value?

Comment (rouault) [reply src/core/providers/ogr/qgsogrprovider.cpp]: > Wouldn't it be better to display the type name instead of the QVariant::type enum value?

agreed. I actually tried using QMetaType::name() method (https://doc.qt.io/qt-6/qmetatype.html#name), but it returned a "-" string for 10=String. Probably a mis-use of the Qt API. Ah, actually I see https://doc.qt.io/qt-6/qvariant.html#typeName . Just used that, and it works OK. Commit amended.

**Review by nyalldawson — APPROVED** [review]
