### PR TITLE
Use warped vrt for rasters with geolocation array data

### LINKED ISSUE #51758: QGIS 3.22 wrongly displays NetCDF raster
### What is the bug or the crash?

A raster file is wrongly projected in QGIS 3.22. After reading https://github.com/qgis/QGIS/issues/47158 I chose to set 
IGNORE_XY_AXIS_NAME_CHECKS=YES 
when adding the file, but this did not help.

The upper left corner of my layer has been assigned with coordinates (0,0), but should have been (69.628°N, 17.9877°E) Screenshot is added below:
image

### Steps to reproduce the issue

1. From the top menu in QGIS choose: _Layer_ - _Add Layer_ - _Add raster layer_

2. Load a netcdf file and set IGNORE_XY_AXIS_NAME_CHECKS=YES

3. Press _Add_, select the variable(s) you would like to visualize and press _Add layers_.

4. Double-click on the added layer and in the Source-panel set the Assigned CRS to WGS 84 and press _Apply_.

The layer will now be wrongly projected.

### Versions

3.22.16

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by uclaros**
## Description
If a raster file has _geolocation array_ data, we can render it at the correct place using a warped vrt, similar to how rasters with RPC coeffs are handled.

Fixes: #51758
Fixes: #63456

### CODE REVIEW

**Comment by saberraz** [comment]
Also related to https://github.com/qgis/QGIS/issues/63456

File: src/core/providers/gdal/qgsgdalprovider.cpp [hunk 1]
```diff
@@ -3697,21 +3698,23 @@ void QgsGdalProvider::initBaseDataset()
...
+        && !GDALGetMetadata( mGdalBaseDataset, "RPC" )
+        && !GDALGetMetadata( mGdalBaseDataset, "GEOLOCATION" );
 
     if ( !isSouthUpWithoutRotationGcpOrRPC && GDALGetMaskFlags( GDALGetRasterBand( mGdalBaseDataset, 1 ) ) == GMF_ALL_VALID )
     {
       psWarpOptions->nDstAlphaBand = GDALGetRasterCount( mGdalBaseDataset ) + 1;
     }
 
-    if ( GDALGetMetadata( mGdalBaseDataset, "RPC" ) )
+    if ( GDALGetMetadata( mGdalBaseDataset, "RPC" ) ||
```
Comment (rouault) [inline src/core/providers/gdal/qgsgdalprovider.cpp]: The test for GEOLOCATION here doesn't look appropriate as it will go through the rpcAwareAutoCreateWarpedVrt. Going to the else clause with regular GDALAutoCreateWarpedVRT() should be fine

File: src/core/providers/gdal/qgsgdalprovider.cpp [hunk 2]
```diff
@@ -3810,9 +3813,10 @@ void QgsGdalProvider::initBaseDataset()
   else
   {
     if ( mGdalBaseDataset != mGdalDataset &&
-         GDALGetMetadata( mGdalBaseDataset, "RPC" ) )
+         ( GDALGetMetadata( mGdalBaseDataset, "RPC" ) ||
+           GDALGetMetadata( mGdalBaseDataset, "GEOLOCATION" ) ) )
```
Comment (rouault) [inline src/core/providers/gdal/qgsgdalprovider.cpp]: while in 99.9% case the CRS is indeed going to be EPSG:4326, the cleanest way would be to query  GDALGetMetadataItem( mGdalBaseDataset, "SRS" )  (which if set contains a WKT string )

File: src/core/providers/gdal/qgsgdalprovider.cpp [hunk 3]
```diff
@@ -3697,21 +3698,23 @@ void QgsGdalProvider::initBaseDataset()
     // when the raster is rotated). For example, this fixes the issue for RGB rasters
     // (with no alpha channel) or single-band raster without "no data" value set.
 
-    // South-up oriented raster without any rotation, GCP or RPC doesn't need alpha band
+    // South-up oriented raster without any rotation, GCP, RPC or GEOLOCATION doesn't need alpha band
```
Comment (rouault) [inline src/core/providers/gdal/qgsgdalprovider.cpp:3701]: maybe create a small helper function requiresWarpVRT() ?  since we have the same logic repeated here and at lines 3683-3690

Comment (uclaros) [reply src/core/providers/gdal/qgsgdalprovider.cpp:3701]: These are not the same checks. L3683-3690 check for any geotransform that requires warp vrt, but this checks if it's _south up with no rotation_.

Actually looking at this, why do we skip adding the alpha band only for _South Up/East right_ cases and not for any zero rotation case (ie skip `mGeoTransform[1] > 0.0 && mGeoTransform[5] > 0.0` check)?

File: src/core/providers/gdal/qgsgdalprovider.cpp (hunk 1 above)
Comment (uclaros) [reply src/core/providers/gdal/qgsgdalprovider.cpp]: If we go the `else` route we'll later get:
```cpp
mGdalTransformerArg = GDALCreateGenImgProjTransformer( mGdalBaseDataset, nullptr, nullptr, nullptr, TRUE, 1.0, 0 );
```
instead of
```cpp
mGdalTransformerArg = GDALCreateGenImgProjTransformer2( hSrcDS, hDstDS, opts );
```

Is that OK to pass `bGCPUseOK = TRUE`?

File: src/core/providers/gdal/qgsgdalprovider.cpp (hunk 2 above)
Comment (uclaros) [reply src/core/providers/gdal/qgsgdalprovider.cpp]: Isn't that "wgs84 by convention" also the case for RPCs?

File: src/core/providers/gdal/qgsgdalprovider.cpp (hunk 3 above)
Comment (rouault) [reply src/core/providers/gdal/qgsgdalprovider.cpp:3701]: > These are not the same checks. L3683-3690 check for any geotransform that requires warp vrt, but this checks if it's _south up with no rotation_.

ah sorry, at first sight, they seem to be almost the negation of the other ones.

> Actually looking at this, why do we skip adding the alpha band only for South Up/East right cases and not for any zero rotation case (ie skip mGeoTransform[1] > 0.0 && mGeoTransform[5] > 0.0 check)?

If the raster is just flipped in the vertical direction, we don't need to add an alpha band when using warped VRT since the source rectangle will remain a source rectangle, without additional padding

File: src/core/providers/gdal/qgsgdalprovider.cpp (hunk 1 above)
Comment (rouault) [reply src/core/providers/gdal/qgsgdalprovider.cpp]: > Is that OK to pass `bGCPUseOK = TRUE`?

yes, that should be fine. That's actually doesn't modify the passed opts. Only setting bGCPUseOK = FALSE forbids the use of GCPs. When there are no GCPs, that doesn't change anything

File: src/core/providers/gdal/qgsgdalprovider.cpp (hunk 2 above)
Comment (rouault) [reply src/core/providers/gdal/qgsgdalprovider.cpp]: yes, RPCs (at least when coming from NITF) use WGS84 by convention, and the RPC metadata domain has no SRS key.  The GEOLOCATION does, so we can use it.

File: src/core/providers/gdal/qgsgdalprovider.cpp (hunk 3 above)
Comment (uclaros) [reply src/core/providers/gdal/qgsgdalprovider.cpp:3701]: > since the source rectangle will remain a source rectangle, without additional padding

That's my point, when `mGeoTransform[2] == 0.0 && mGeoTransform[4] == 0.0` don't we always have a rectangle regardless of `mGeoTransform[1]` and `mGeoTransform[5]` values?

Comment (rouault) [reply src/core/providers/gdal/qgsgdalprovider.cpp:3701]: > don't we always have a rectangle regardless of `mGeoTransform[1]` and `mGeoTransform[5]` values?

yes, that's true.   (although east right is really really uncommon)  . You might change the test if you wish

**Comment by saberraz** [comment]
ping @timlinux , could you give this PR a test?

**Comment by timlinux** [comment]
@saberraz thanks I am going to test

**Review by wonder-sk — APPROVED** [review]

**Comment by arongergely** [comment]
This is great! Do you plan to backport it to 3.44.x ?
