### PR TITLE
Fix copy/pasting of features to/from the same layer ignores avoid overlap settings

### LINKED ISSUE #54492: Paste feature ignores avoid overlap
### What is the bug or the crash?

When pasting features on a layer with _avoid overlaps_ enabled, the geometry is no longer modified to _avoid overlaps_ but the whole geometry is pasted as is.
This is a regression.

### Steps to reproduce the issue

1. Load a polygon layer
2. Digitize two overlapping polygons
3. Select one of the two polygons and cut it (ctrl+x)
4. Enable _Avoid overlap on current layer_
5. Paste (ctrl+v)
6. No overlap avoidance is performed resulting in two overlapping polygons 

### Versions

defb622e8dd

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This PR fixes a regression introduced in July whereas features being copied and pasted *onto the same layer* would ignore the avoid overlap settings.

Fixes #54492.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Any chance of a test?

**Comment by nirvn** [comment]
@nyalldawson , test added.

**Comment by troopa81** [comment]
Avoid overlap comes very often with topological editing, which is not managed here.

I tried to gather code in #54790 (still waiting for review) to avoid duplicated code, Could it be reused in that area of the code?

**Comment by nirvn** [comment]
@troopa81 , when you say "not managed here" you mean it was never managed when pasting features before right? In any case, I'd be for working this out in a different PR.

**Comment by troopa81** [comment]
> @troopa81 , when you say "not managed here" you mean it was never managed when pasting features before right? 

Yes

> In any case, I'd be for working this out in a different PR.

I understand that's beyond the scope of the initial PR, My concern was more about copy/pasting those same lines everywhere as soon as we need to deal with overlap and/or topological points. 

But it's non blocking.

File: src/app/qgisapp.cpp [hunk 1]
```diff
@@ -10202,6 +10202,37 @@ void QgisApp::pasteFromClipboard( QgsMapLayer *destinationLayer )
...
+          case Qgis::AvoidIntersectionsMode::AvoidIntersectionsCurrentLayer:
+            avoidIntersectionsLayers.append( pasteVectorLayer );
+            break;
+          case Qgis::AvoidIntersectionsMode::AvoidIntersectionsLayers:
+            avoidIntersectionsLayers = QgsProject::instance()->avoidIntersectionsLayers();
+            break;
+          case Qgis::AvoidIntersectionsMode::AllowIntersections:
+            break;
+        }
+        if ( avoidIntersectionsLayers.size() > 0 )
```
Comment (nyalldawson) [inline src/app/qgisapp.cpp:10225]:
```suggestion
        if ( !avoidIntersectionsLayers.empty() )
```

**Review by nyalldawson — APPROVED** [review]
