### PR TITLE
Fix/wms provider url decoding

### LINKED ISSUE #31192: Add WMS server fails with QGIS Server with Postgresql project
**Context**

QGIS desktop should be able to work with QGIS Server, if the project is stored in Postgresql.

When QGIS Server is used with several different projects, the MAP parameter must be present to tell which project to use.

The following GetCapabilities requests are used against two different projects: one stored on the server filesystem and another stored in Postgresql:
1. http://qgis.demo/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities&MAP=/home/qgis/projects/cartageologica.qgz
2. http://qgis.demo/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities&MAP=postgresql%3A%3Fservice%3Dpg_geotuga%26sslmode%3Ddisable%26dbname%3D%26schema%3Dortos%26project%3Dteste

The second URL, which includes the Postgresql project, **must be properly quoted** to be properly handled on the QGIS Server side:
```python
python -c "import urllib, sys; print urllib.quote(sys.argv[1])" "postgresql:?service=pg_geotuga&sslmode=disable&dbname=&schema=ortos&project=teste"
```

**Describe the bug**

There is no problem to add a QGIS Server url to QGIS desktop, using a `MAP=<project on filesystem>`.

wms with project from filesystem

There is no way to add QGIS Server urls with `MAP=<Postgresql project>`.

error add qis server with postgresql project

I've tried with both the quoted and unquoted URL:
1. http://qgis.demo/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities&MAP=postgresql%3A%3Fservice%3Dpg_geotuga%26sslmode%3Ddisable%26dbname%3D%26schema%3Dortos%26project%3Dteste
1. http://qgis.demo/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities&MAP=postgresql:?service=pg_geotuga&sslmode=disable&dbname=&schema=ortos&project=teste

The error is the same. The string passed to QGIS server is the same.

**How to Reproduce**

1. Go to Add WMS/WMTS layer
2. Add a QGIS Server with a URl that includes the Postgresql project
2. Click connect to get the capabilities document
2. The GetCapabilities fails.

**QGIS and OS versions**

1. QGIS 3.8, 3.9-Master
1. Ubuntu 19.04
1. GDAL 3.0.1

**Additional context**

The server is able to answer only if the MAP string is quoted.

The entry point in the source code is the [`QgsWmsSettings::parseUri`](https://github.com/qgis/QGIS/blob/bf31ce1d8cf2e24e3d2ef499a15afa44f9eb5780/src/providers/wms/qgswmscapabilities.cpp#L38) function.

This calls `uri.setEncodedUri( uriString );` which does not properly quote the project part and send the request to the server like:
`QUERY_STRING: VERSION=1.3.0&MAP=postgresql:?service=pg_geotuga&sslmode=disable&dbname=&schema=ortos&project=teste&SERVICE=WMS&REQUEST=GetCapabilities`
The server breaks the parameters using the `&` character and the MAP becomes only:
`21:04 INFO Server[7789]: MAP:postgresql:?service=pg_geotuga`.

There are several possibilities...
1. Change the postgresql project string format, removing the `&` (this might break existing projects, but using `&` will be always a problem). Better now than later.
2. Make this `uri.setEncodedUri( uriString );` function aware of the MAP parameter and create a proper quoted MAP string.
3. Improve QGIS Server to recreate the proper MAP parameter. QGIS Server receives all the parameters, but separated by `&`.

### LINKED ISSUE #59143: inconsistent URL encoding/decoding with WMS sources
### What is the bug or the crash?

QGIS improperly encodes/decodes data source URLs, including URL parameter values, causing the original values to be altered and leading to data loss. Additionally, QgsDataSourceUri does not fully URL-encode the values when assembling the data source string leading to potential data loss.

When constructing a `QgsDataSourceUri`, parameter values are not fully URL-encoded. In this case only the `=`is encoded to `%26`. This can result in incorrect URL parameters being sent in the requests. For example:

- **Original URL added as WMS source:**  
  `https://127.0.0.1/%26%3F%26%3F/?non_standard_param=%26%3F%26%3F%26%3F`
  
- **Resulting QgsDataSourceUri string:**  
  `dpiMode=7&featureCount=10&tilePixelRatio=0&url=https://127.0.0.1/%26%3F%26%3F/?non_standard_param%3D%26%3F%26%3F%26%3F`
  
- **Actual GetCapabilities Request Sent:**  
  `https://127.0.0.1/&?&?/?non_standard_param=&?&?&?SERVICE=WMS&REQUEST=GetCapabilities`

**Expected behaviour**

- **Original URL added as WMS source:**  
  `https://127.0.0.1/%26%3F%26%3F/?non_standard_param=%26%3F%26%3F%26%3F`
  
- **Resulting QgsDataSourceUri string (values are fully URL-encoded:**  
`dpiMode=7&featureCount=10&tilePixelRatio=0&url=https%3A%2F%2F127.0.0.1%2F%2526%253F%2526%253F%2F%3Fnon_standard_param%3D%2526%253F%2526%253F%2526%253F`
  
- **Actual GetCapabilities Request Sent:**  
  `https://127.0.0.1/%26%3F%26%3F/?non_standard_param=%26%3F%26%3F%26%3F&SERVICE=WMS&REQUEST=GetCapabilities`

### Steps to reproduce the issue

1. open QGIS and the request debug console
2. add a WMS data source with the URL `https://127.0.0.1/%26%3F%26%3F/?non_standard_param=%26%3F%26%3F%26%3F`
  - in qgsnewhttpconnection.cpp (363) QUrl decodes some of the URL-encoded characters resulting in `https://127.0.0.1/%26?%26?/`
    `QUrl url( txtUrl->text().trimmed() );`
  - in qgsnewhttpconnection.cpp (381) the QUrl query is set to `non_standard_param=%26%3F%26%3F%26%3F`
    `url.setQuery( query );`
  - in qgsowsconnection.cpp (87) the QgsDataSourceUri param "url" is set to the original url `https://127.0.0.1/%26%3F%26%3F/?non_standard_param=%26%3F%26%3F%26%3F` resulting in the param value
    `mUri.setParam( QStringLiteral( "url" ), url );`
3. right click the new WMS data source and click refresh
  - in qgswmsdataitems.cpp (61) the QgsDataSourceUri is parsed. mUri has the value `dpiMode=7&featureCount=10&tilePixelRatio=0&url=https://127.0.0.1/%26%3F%26%3F/?non_standard_param%3D%26%3F%26%3F%26%3F`. The key-value separator "=" has been URL-encoded to %3D the other character left untouched making it impossible to retain the original URL. The "url" param of uri becomes `https://127.0.0.1/&%3F&%3F/?non_standard_param=&%3F&%3F&%3F` resulting in an empty value for `non_standard_param`.
    `uri.setEncodedUri( mUri );`
  - in qgswmsprovider.cpp (280) the whole thing is URL-decoded resulting in `https://127.0.0.1/&?&?/?non_standard_param=&?&?&?`
    ```
    // some services provide a percent/url encoded (legend) uri string, always decode here
    uri = QUrl::fromPercentEncoding( uri.toUtf8() );
    ```
4. the GetCapabilities request is made to `https://127.0.0.1/&?&?/?non_standard_param=&?&?&?SERVICE=WMS&REQUEST=GetCapabilities`
  - qgswmscapabilities.cpp (2559) `QNetworkRequest request( url );`

### Versions

QGIS 3.38.3 (probably all previous versions since QgsDataSourceUri was added and used for non database providers)
Master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Related Issues:

- #58579 Tianditu cannot be loaded in QGis WMS/WMTS
- #25029 Allow (and use) URL parameters when connecting to WMS/WFS/WCS

### PR DESCRIPTION
**Pull request by benoitdm-oslandia**
This closes https://github.com/qgis/QGIS/pull/62310 and reopens https://github.com/qgis/QGIS/pull/59144 plus some changes:

* rebase from master 
* remove merge and revert commits
* squash some commits
* fix qgshttpheaders accordingly
* add tests

closes #31192
closes #59143

cc @cioddi

### CODE REVIEW

File: src/providers/wms/qgswmsprovider.cpp [hunk 1]
```diff
@@ -276,7 +276,12 @@ QgsWmsProvider::QgsWmsProvider( QString const &uri, const ProviderOptions &optio
 QString QgsWmsProvider::prepareUri( QString uri )
 {
   // some services provide a percent/url encoded (legend) uri string, always decode here
-  uri = QUrl::fromPercentEncoding( uri.toUtf8() );
+  if ( uri.startsWith( "https%3A%2F%2F" ) || uri.startsWith( "http%3A%2F%2F" ) )
+  {
+    qDebug() << "========================================================================= QgsWmsProvider::prepareUri" << uri;
+    uri = QUrl::fromPercentEncoding( uri.toUtf8() );
+    Q_ASSERT( false );
+  }
```
Comment (benoitdm-oslandia) [inline src/providers/wms/qgswmsprovider.cpp]: @cioddi I do not find a unit test or a user case using this code. Does it still valid? 

And you are talking about decoding but you called the encode function.

Comment (cioddi) [reply src/providers/wms/qgswmsprovider.cpp]: The comment should be already in main, but is correct in general. Only the ", always decode here" part should be removed as it is not the case anymore with the new version in this branch.
Iirc I added only the if clause, to check whether the whole URL actually is urlencoded before just decoding it by chance.

The function fromPercentEncoding() returns a decoded copy of the input it just does not have the best name (https://doc.qt.io/qt-6/qurl.html#fromPercentEncoding).

Comment (cioddi) [reply src/providers/wms/qgswmsprovider.cpp]: Should be reached through the QgsWmsProvider constructor.

edit: That was a mistake, it is QgsWmsSettings::parseUri that is called through the QgsWmsProvider.

`QgsWmsProvider::prepareUri` appears to be only used here in QgsWmsCapabilities https://github.com/qgis/QGIS/blob/b32ddd897208bbbd759a4043f171f3400c461792/src/providers/wms/qgswmscapabilities.cpp#L177

Comment (benoitdm-oslandia) [reply src/providers/wms/qgswmsprovider.cpp]: I misread the function name `fromPercentEncoding()` vs `toPercentEncoding()`! 

As I said, I did not succeed in finding a way to trigger this `if`. Do you have an example? If not, I think we should remove this modification.

Comment (cioddi) [reply src/providers/wms/qgswmsprovider.cpp]: I agree, if we are unable to test it, we should remove it. 

I am currently pretty occupied with another project. I will try to take a look at it over the weekend. But I am totally ok with removing it if it clears the way for the other changes. And I can open another PR including a test for it separately later.

That aside:
I don't have good existing projects to test the build of this branch with, since I am mainly integrating QGIS servers into container infrastructures. Will ask some colleagues to see if it breaks something for them. Did it solve the initial issue for you?

Comment (benoitdm-oslandia) [reply src/providers/wms/qgswmsprovider.cpp]: Ok I will revert this section and squash some commit to improve the git history.

Comment (benoitdm-oslandia) [reply src/providers/wms/qgswmsprovider.cpp]: done!

**Comment by benoitdm-oslandia** [comment]
ping @troopa81, for review please!

**Comment by benoitdm-oslandia** [comment]
rebase from master

**Comment by nyalldawson** [comment]
@benoitdm-oslandia does this change break stable api? I.e would existing code relying on the old behavior (such as constructing a wms layer from a hard coded source string) be impacted?

**Comment by benoitdm-oslandia** [comment]
> @benoitdm-oslandia does this change break stable api? I.e would existing code relying on the old behavior (such as constructing a wms layer from a hard coded source string) be impacted?

Sorry, what do you mean by hard coded? Can you provide a more precise usecase?

**Comment by kannes** [comment]
I am 99% sure Nyall means URI strings that users might have saved and that are required to keep working. E. g. if you have a custom basemap plugin that contains a list of services defined by URIs. Will those keep working fine or is there potential breakage?

**Comment by benoitdm-oslandia** [comment]
@nyalldawson @kannes I am 99% sure the plugins will keep working fine :) The fixes brought by this PR are mainly to improve the support of url decoding and to homogeneize the uri encoding. But maybe some usecases are not tested!

**Comment by nyalldawson** [comment]
@benoitdm-oslandia 

but there's changes in tests like this:

image

and 

image

That to me suggests that the previous hardcoded URIs are now broken, which would also affect plugins and scripts =>this is an api break.

**Comment by benoitdm-oslandia** [comment]
@nyalldawson I add some usecases in the test you mentioned and, from what I understood, it does not generate an API break.

**Comment by cioddi** [comment]
I will try to explain the situation.

The **current state** is, parts of the source configuration is stored in the form of URL parameters. When the value of an individual key is retrieved, it is always decoded using `QUrl::PrettyDecoded` (https://doc.qt.io/qt-6/qurlquery.html#queryItems).

The change in die PR will make sure values that are added to the QUrlQuery object are fully URL encoded (https://doc.qt.io/qt-6/qurl.html#ComponentFormattingOption-enum) first. The retrieval function QUrlQuery::queryItems parameter was changed from the default `QUrl::PrettyDecoded` (from the Qt docs: "The component is returned in a "pretty form", with most percent-encoded characters decoded. **The exact behavior of PrettyDecoded varies from component to component and may also change from Qt release to Qt release**. This is the default.") to the reliable and predictable `QUrl::FullyDecoded`. This ensures that the exact value that was passed in a data source URL parameter can be retrieved from it again. 

**Why is this important?**
Especially in more complex QGIS server deployments we often rely on the non WMS spec "map" URL parameter to specify information about which project or configuration is supposed to be processed with the request. The value often contains characters that collide with URL parameter reserved characters such as ?, &, = so the value must be URL encoded (which is fine).

Now if we consume the WMS provided by QGIS server using a QGIS client the only way to make this work with current versions of QGIS is to double URL encode the values passed to the map parameter. That way at the time QGIS assembles the URL for an HTTP request to the server the value becomes single URL encoded because that is the way QUrlQuery::queryItems works by default.

(The server acts only as an example here, but could be any data source that expects a URL parameter value the QGIS client would send in a URL encoded form)

**What this PR will break**

This will break projects that are currently using the double URL encoded value workaround in a datasource. In those cases the source configuration must be updated. After updating the double URL encoded URL parameter values to single URL encoded ones, those will start working again. (**this must be added to breaking changes**)

**General thoughts**

Using a URL-parameter String is probably not the best way to store/handle the configuration of a data source and maybe in the future it should be considered to switch to something that better fits the requirements (like XML that is already used anyway for project files). This PR makes sure though that we can work with the current URL parameter config in a reliable way.

**Comment by cioddi** [comment]
I will do some tests with the build over the weekend and get back to this PR with my findings.

**Comment by cioddi** [comment]
I have now added a mbtiles layer using drag and drop to a new project. They are loading fine in both, the PR #62446 version and my local QGIS (3.34.4-Prizren). 

PR #62446:
local_mbtiles_src_qgis_PR_62446


QGIS (3.34.4-Prizren):
local_mbtiles_src_qgis_3 34 4-Prizren

Adding a WMS works, and when the project is saved in PR #62446 build it also loads in the old QGIS (3.34.4-Prizren): 

I am also able to load the project saved with my local QGIS (3.34.4-Prizren) in the PR #62446 build and it works fine.
The WFS source from the user profile in my home dir also works fine in the new build.

One problem I have encountered. When examining the source properties the URL displayed in the "information"-tab is not URL-decoded and does not work if I click on the link. If I right click->open URL I get this something like this: "Cannot show URL Failed to load URL [https%3A%2F%2Fsgx.geodatenzentrum.de%2Fwms_basemapde%3FVersion=1.3.0](https://github.com/qgis/QGIS/pull/https%3A%2F%2Fsgx.geodatenzentrum.de%2Fwms_basemapde%3FVersion=1.3.0)."

WMS_src_qgis_PR_62446

So this should be fixed, and we should find out what function is used to retrieve the "url" prop value in that case and why it is not doing any URL-decoding in that case (and of course whether the same method is used anywhere else to retrieve the "url"-value or any other)

**Comment by benoitdm-oslandia** [comment]
Fixed the URL displayed in the "information"-tab!

**Comment by benoitdm-oslandia** [comment]
@nyalldawson 

Test failure in not related to PR changes. Is it ok to you?

File: src/core/qgsdatasourceuri.cpp [hunk 2]
```diff
@@ -928,7 +928,7 @@ QString QgsDataSourceUri::param( const QString &key ) const
   else if ( key == QLatin1String( "authcfg" ) && !mAuthConfigId.isEmpty() )
     return mAuthConfigId;
 
-  return mParams.value( key );
+  return mParams.value( key ).toUtf8();
```
Comment (troopa81) [inline src/core/qgsdatasourceuri.cpp]: Why do we need to transform it in utf8 bytearray whereas the function returns a QString ?

File: src/core/qgsmaplayer.cpp [hunk 3]
```diff
@@ -3250,7 +3250,11 @@ QString QgsMapLayer::generalHtmlMetadata() const
     }
     if ( uriComponents.contains( QStringLiteral( "url" ) ) )
     {
-      const QString url = uriComponents[QStringLiteral( "url" )].toString();
+      QUrl decodedUri = QUrl::fromPercentEncoding( uriComponents[QStringLiteral( "url" )].toString().toLocal8Bit() );
+      if ( decodedUri.scheme().isEmpty() && decodedUri.path().startsWith( "http" ) )
+        // url can be encoded twice and needs another % decoding
```
Comment (troopa81) [inline src/core/qgsmaplayer.cpp]: I don't get why they could be encoded twice ? or even once ? Here we get the non-encoded url, the one store in the layer.  We encode only in `QgsDataSourceUri::encodedUri()`, no?

File: tests/src/core/testqgsvectortilelayer.cpp [hunk 4]
```diff
@@ -458,22 +463,24 @@ void TestQgsVectorTileLayer::testVtpkProviderMetadata()
...
   QCOMPARE( sublayers.at( 0 ).providerKey(), QStringLiteral( "vtpkvectortiles" ) );
   QCOMPARE( sublayers.at( 0 ).name(), QStringLiteral( "testvtpk" ) );
-  QCOMPARE( sublayers.at( 0 ).uri(), QStringLiteral( "type=vtpk&url=%1/testvtpk.vtpk" ).arg( TEST_DATA_DIR ) );
+  QCOMPARE( sublayers.at( 0 ).uri(), QStringLiteral( "type=vtpk&url=%1" ).arg( localVtpkPath ) );
   QCOMPARE( sublayers.at( 0 ).type(), Qgis::LayerType::VectorTile );
 
-  QCOMPARE( vectorTileMetadata->priorityForUri( QStringLiteral( "type=vtpk&url=%1/testvtpk.vtpk" ).arg( TEST_DATA_DIR ) ), 100 );
-  QCOMPARE( vectorTileMetadata->validLayerTypesForUri( QStringLiteral( "type=vtpk&url=%1/testvtpk.vtpk" ).arg( TEST_DATA_DIR ) ), { Qgis::LayerType::VectorTile } );
-  sublayers = vectorTileMetadata->querySublayers( QStringLiteral( "type=vtpk&url=%1/testvtpk.vtpk" ).arg( TEST_DATA_DIR ) );
+  QCOMPARE( vectorTileMetadata->priorityForUri( QStringLiteral( "type=vtpk&url=%1" ).arg( localVtpkPath ) ), 100 );
```
Comment (troopa81) [inline tests/src/core/testqgsvectortilelayer.cpp]: Is it working if we have the old URI format or do we have an API break?

File: src/core/qgsmaplayer.cpp (hunk 3 above)
Comment (troopa81) [reply src/core/qgsmaplayer.cpp]: After discussion, we should display the url as it was entered by the user. If he enters an already encoded URL, we display it encoded.

**Comment by troopa81** [comment]
> One problem I have encountered. When examining the source properties the URL displayed in the "information"-tab is not URL-decoded and does not work if I click on the link. If I right click->open URL I get this something like this: "Cannot show URL Failed to load URL [https%3A%2F%2Fsgx.geodatenzentrum.de%2Fwms_basemapde%3FVersion=1.3.0](https://github.com/qgis/QGIS/pull/https%3A%2F%2Fsgx.geodatenzentrum.de%2Fwms_basemapde%3FVersion=1.3.0)."

But why would you want to enter an already percent encoded URL. I understand that we can have a MAP or postgres url subpart that could be encoded but IMHO encoding the whole URL makes no sense. In the case of postgres/MAP subpart, we should let it encoded because it would be invalid otherwise.

File: src/core/qgsdatasourceuri.cpp (hunk 2 above)
Comment (benoitdm-oslandia) [reply src/core/qgsdatasourceuri.cpp]: indeed seems useless. Removed/

File: tests/src/core/testqgsvectortilelayer.cpp (hunk 4 above)
Comment (benoitdm-oslandia) [reply tests/src/core/testqgsvectortilelayer.cpp]: I reworked  this test part to check with multiple input formats

File: src/core/qgsmaplayer.cpp (hunk 3 above)
Comment (benoitdm-oslandia) [reply src/core/qgsmaplayer.cpp]: In fact, as it is saved encoded, it had to be decoded at least once!

**Comment by benoitdm-oslandia** [comment]
@troopa81 I have found a bug with the vectortile provider while adjusting the tests. It does not seem a nice fix to me :(

**Review by troopa81 — APPROVED** [review]
After long discussion and thorough reviewing, I'm OK with the PR in this actual state.

Thank you @benoitdm-oslandia

**Comment by ViperMiniQ** [comment]
Hi @benoitdm-oslandia,
this broke the loading of SLPK files from local files.
Can you please have a look at #64543?

Also, some of the reported paths in the metadata look weird now and I don't think it was an intended behavior.

Prior to this PR:
Screenshot_20260122_202951

After:
Screenshot_20260122_202919
