### PR TITLE
Bugfix gh5122 mergefeature fid crash

### LINKED ISSUE #51122: QGIS crashing at the saving of PostgreSQL layer after merging features
### What is the bug or the crash?

QGIS crashes when editing a PSQL layer (specifically merging features) and then hitting save. This is reproducible, tested on both 3.28 and 3.22.

### Steps to reproduce the issue

Follow along with the video in the zip. 

SQL code and map are also attached to create the layer.

[crash.zip](https://github.com/qgis/QGIS/files/10157790/crash.zip)

### Versions

3.28 and 3.22 LTR

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

### Additional context

Crash ID: [0dfb5b2e81d9973c919f17cf6df1ee6e7358fbf0](https://github.com/qgis/QGIS/search?q=0dfb5b2e81d9973c919f17cf6df1ee6e7358fbf0&type=Issues)

Stack Trace

QVariant::clear :
QVariant::operator= :
QgsVectorLayerEditBuffer::commitChanges :
QgsVectorLayer::commitChanges :
QgisApp::saveVectorLayerEdits :
QgisApp::saveActiveLayerEdits :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.13-Bia?owie?a
QGIS code revision: 02ff117c
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.0
Running against GDAL: 3.6.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

### PR DESCRIPTION
**Pull request by elpaso**
Fix #51122

Introduced by #47822

This PR handles not-numeric, fidmap and composite PKs.

### CODE REVIEW

File: src/app/qgisapp.cpp [hunk 1]
```diff
@@ -9726,7 +9726,38 @@ void QgisApp::mergeSelectedFeatures()
                          vl->dataProvider()->pkAttributeIndexes().contains( vl->fields().fieldOriginIndex( i ) );
 
     if ( isPrimaryKey && !isDefaultValue )
-      mergeFeatureId = val.toLongLong();
+    {
+      QgsFeatureRequest request;
+      request.setFlags( QgsFeatureRequest::Flag::NoGeometry );
+      // Handle multi pks
+      if ( vl->dataProvider()->pkAttributeIndexes().count() > 1 && vl->dataProvider()->pkAttributeIndexes().count() <= attrs.count() )
```
Comment (nyalldawson) [inline src/app/qgisapp.cpp:9733]: I'm not saying this fix is wrong, but this looks very complex to sit at such a high level component (QgisApp). Do you think it's possible to move this logic into a virtual method in QgsVectorDataProvider? Potentially the data provider can determine this internally without having to resort to a feature request at all, since it will already have internal hashes of attribute(s) to feature ids.

Comment (elpaso) [reply src/app/qgisapp.cpp:9733]: I agree: this logic should not sit in apps and should be CI tested.

I'm just saying that I did this bugfix in my volunteer time because I had a few spare hours, I don't think I have time now for a deeper refactoring.

This is a serious regression IMO, and was even backported.

Comment (nyalldawson) [reply src/app/qgisapp.cpp:9733]: How about we just revert the original PR until a better process is available? (Or someone funds a proper fix for the original issue)

Comment (nyalldawson) [reply src/app/qgisapp.cpp:9733]: Ping @3nids @andreasneumann  @domi4484

Comment (andreasneumann) [reply src/app/qgisapp.cpp:9733]: @domi4484 @elpaso @nyalldawson

Of course we are not amused to pay a fix for a fix - and also having to wait until June 2023 to get this in 3.28.x again, because every fix has to skip one release (quarantine rule). I will have a hard time explaining this to my users.

But that's life - and if you think this has to be reverted, then it has to be done ...

Comment (domi4484) [reply src/app/qgisapp.cpp:9733]: @elpaso I compiled your fix and could test it successfully. It also fixes another unreported error we recently observed. And I suspect it could also fix #48402.

At this point I would ask if it is possible to merge this P.R., because reverting #47822 would result in a regression in 3.28 losing the fix to #47629.

We are currently checking possibilities to follow up with a proper fix and test in the near future.

Comment (elpaso) [reply src/app/qgisapp.cpp:9733]: @domi4484 I'm ok as a temporary fix. If @nyalldawson is ok we can merge (and backport).

Comment (nyalldawson) [reply src/app/qgisapp.cpp:9733]: I won't block it -- but @domi4484  please recognise that it's a significant amount of high maintenance, non-unit-tested code being added, and your follow up improvements would be much welcomed.

Comment (domi4484) [reply src/app/qgisapp.cpp:9733]: Yes I see it and I am sorry for the inconveniences and amount of work that the regression raised up.

Comment (elpaso) [reply src/app/qgisapp.cpp:9733]: @domi4484 do you want me to merge this PR?

Comment (domi4484) [reply src/app/qgisapp.cpp:9733]: @elpaso I have planned to work on this next week (refactor + tests). But we could already merge this so we are sure that something is there before the freeze?
