### PR TITLE
[SelectiveMasking] Use QUuid to reference symbol layer when masking

### LINKED ISSUE #34352: Label masking doesn't work with line pattern symbol sub layers
While testing out the label masking feature some more today, I stumble on an implementation issue, whereas line pattern symbol's sub layer aren't masked.

Test project here:
[mask.zip](https://github.com/qgis/QGIS/files/4170252/mask.zip)

You can see here the hashed lines are checked to be masked but
Screenshot from 2020-02-07 17-35-47

### PR DESCRIPTION
**Pull request by troopa81**
Fixes #34352

This PR is a follow up and implementation of this [comment](https://github.com/qgis/QGIS/pull/47459#issuecomment-1123018070).

Selective masking was using a tuple *symbol key (rule for instance) / symbol layer index path* to reference symbol layer. It's very fragile and is a problem when it comes to cloning symbol layer for instance. This PR propose to replace them with a generated QUuid.

On the API side of things I had to add some *V2* methods in order to not break the API. I changed only the return type of QgsVectorLayerUtils::labelMasks and QgsVectorLayerUtils::symbolLayerMasks but there are not part of Python API.

I implemented a migration method to port from old project. I set the migration code as deprecated in order to remove it when we switch to QGIS 4, so it won't be possible to migrate QGIS project which version is less than 3.28 in QGIS 4. Is it OK?

### CODE REVIEW

**Comment by nyalldawson** [comment]
Nice work @troopa81 -- this should fix a lot of things!

One consideration we need to make is when a clone operation is used to "copy" (or duplicate) a symbol (or a renderer, and accordingly all its symbols).

Eg if I right click a layer and duplicate, then the new layer will need to regenerate all the symbol layer ids. Similarly if I were to press the "duplicate symbol layer" button here then the new layer will need a new id:

image

And lastly -- I think there's some places where we should **never** store symbol layer ids. E.g. when we add a symbol to a QgsStyle library, we'll want to clear out all the ids so that reusing the stored symbols doesn't re-use their original ids.  (For the same reason any of the "copy symbol" actions should clear the stored ids too!)

**Comment by troopa81** [comment]
> Eg if I right click a layer and duplicate, then the new layer will need to regenerate all the symbol layer ids.

Good catch, fixed! 

Regarding the copy/paste style from a layer to another (or saving/loading to/from a qml file), I don't think it's that bad for the id to be copied as long as they are unique for a given vector layer. 

> And lastly -- I think there's some places where we should never store symbol layer ids. E.g. when we add a symbol to a QgsStyle library, we'll want to clear out all the ids so that reusing the stored symbols doesn't re-use their original ids. (For the same reason any of the "copy symbol" actions should clear the stored ids too!)

I fixed [here](https://github.com/qgis/QGIS/pull/50786/files#diff-5ca9ad9f5b6f80d49659a95c002977fd9eab698c8acfab060fce03f37e2e63a6R161) and  [there](https://github.com/qgis/QGIS/pull/50786/files#diff-5ca9ad9f5b6f80d49659a95c002977fd9eab698c8acfab060fce03f37e2e63a6R147) in QgsTextBackgroundSettings and in [QgsStyle::addSymbol](https://github.com/qgis/QGIS/pull/50786/files#diff-b80a4a7571b0ed0ed0a818e1680fcc132f3a3b3d5bdf66c2a608baf7d44d90f5R298). Do you see any feature/part of code that could be impacted ?

**Comment by nyalldawson** [comment]
I will as soon as possible -- my workload is extreme right now, so I can't make any promises as to when this will be.

File: src/core/maprenderer/qgsmaprendererjob.cpp [hunk 1]
```diff
@@ -693,10 +693,8 @@ std::vector< LayerRenderJob > QgsMapRendererJob::prepareSecondPassJobs( std::vec
         if ( !layerJobMapping.contains( sourceLayerId ) )
           continue;
 
-        for ( auto slIt = mit.value().symbolLayerIds.begin(); slIt != mit.value().symbolLayerIds.end(); slIt++ )
-        {
-          slRefs.insert( QgsSymbolLayerReference( mit.key(), *slIt ) );
-        }
+        for ( QString symbolLayerId : mit.value().symbolLayerIds )
```
Comment (nyalldawson) [inline src/core/maprenderer/qgsmaprendererjob.cpp:696]:
```suggestion
        for ( const QString &symbolLayerId : mit.value().symbolLayerIds )
```

File: src/core/maprenderer/qgsmaprendererjob.cpp [hunk 2]
```diff
@@ -826,7 +824,7 @@ std::vector< LayerRenderJob > QgsMapRendererJob::prepareSecondPassJobs( std::vec
       continue;
 
     QList<MaskSource> &sourceList = it->second;
-    const QSet<QgsSymbolLayerId> &symbolList = it->first;
+    const QSet<QString> &symbolList = it->first;
```
Comment (nyalldawson) [inline src/core/maprenderer/qgsmaprendererjob.cpp:827]:
```suggestion
    const QSet<QString> symbolList = it->first;
```

File: src/core/qgsrendercontext.h [hunk 3]
```diff
@@ -143,6 +143,31 @@ class CORE_EXPORT QgsRenderContext : public QgsTemporalRangeObject
...
+     * When rendering a map layer in a second pass (for selective masking),
+     * some symbol layers may be disabled.
+     *
+     * Sets the list of disabled symbol layers.
+     * \see disabledSymbolLayers()
+     * \see isSymbolLayerEnabled()
+     * \since QGIS 3.12
+     * \deprecated since QGIS 3.30 and replaced with setDisabledSymbolLayersV2
+     */
+    Q_DECL_DEPRECATED void setDisabledSymbolLayers( const QSet<const QgsSymbolLayer *> &symbolLayers );
```
Comment (nyalldawson) [inline src/core/qgsrendercontext.h:158]:
```suggestion
    Q_DECL_DEPRECATED void setDisabledSymbolLayers( const QSet<const QgsSymbolLayer *> &symbolLayers ) SIP_DEPRECATED;
```

File: src/core/qgsrendercontext.h [hunk 4]
```diff
@@ -151,8 +176,20 @@ class CORE_EXPORT QgsRenderContext : public QgsTemporalRangeObject
      * \see setDisabledSymbolLayers()
      * \see isSymbolLayerEnabled()
      * \since QGIS 3.12
+     * \deprecated since QGIS 3.30 and replaced with disabledSymbolLayersV2
+     */
+    Q_DECL_DEPRECATED QSet<const QgsSymbolLayer *> disabledSymbolLayers() const;
```
Comment (nyalldawson) [inline src/core/qgsrendercontext.h:181]:
```suggestion
    Q_DECL_DEPRECATED QSet<const QgsSymbolLayer *> disabledSymbolLayers() const SIP_DEPRECATED;
```

File: src/core/qgsrendercontext.h [hunk 5]
```diff
@@ -151,8 +176,20 @@ class CORE_EXPORT QgsRenderContext : public QgsTemporalRangeObject
...
+     * When rendering a map layer in a second pass (for selective masking),
+     * some symbol layers may be disabled.
+     *
+     * Returns the list of disabled symbol layer ids.
+     * \see setDisabledSymbolLayers()
+     * \see isSymbolLayerEnabled()
+     * \since QGIS 3.30
      */
-    QSet<const QgsSymbolLayer *> disabledSymbolLayers() const { return mDisabledSymbolLayers; }
+    const QSet<QString> &disabledSymbolLayersV2() const;
```
Comment (nyalldawson) [inline src/core/qgsrendercontext.h:192]:
```suggestion
    QSet<QString> disabledSymbolLayersV2() const;
```

Since QSet is implicitly shared, there's no advantage in return a const ref (and doing so causes potential issues in sip/python code)

File: tests/src/python/test_selective_masking.py [hunk 6]
```diff
@@ -1095,13 +1191,130 @@ def test_layout_export_2_sources_masking(self):
...
+        map_settings.setBackgroundColor(QColor(152, 219, 249))
+        map_settings.setOutputSize(QSize(420, 280))
+        map_settings.setOutputDpi(72)
+        map_settings.setFlag(QgsMapSettings.Antialiasing, True)
+        map_settings.setFlag(QgsMapSettings.UseAdvancedEffects, False)
+        map_settings.setDestinationCrs(crs)
+
+        map_settings.setLayers([layer])
+
+        self.check_layout_export("layout_export_line_pattern_fill", 0, [layer], extent=extent)
```
Comment (nyalldawson) [inline tests/src/python/test_selective_masking.py:1246]: The text in this image is very small and non-bold, so this test won't be stable across platforms. Can you make it bigger and bold, and ensure that it uses the standard QGIS test font too?

File: tests/src/python/test_selective_masking.py [hunk 7]
```diff
@@ -1095,13 +1191,130 @@ def test_layout_export_2_sources_masking(self):
...
+        map_settings.setBackgroundColor(QColor(152, 219, 249))
+        map_settings.setOutputSize(QSize(420, 280))
+        map_settings.setOutputDpi(72)
+        map_settings.setFlag(QgsMapSettings.Antialiasing, True)
+        map_settings.setFlag(QgsMapSettings.UseAdvancedEffects, False)
+        map_settings.setDestinationCrs(crs)
+
+        map_settings.setLayers([layer])
+
+        self.check_layout_export("layout_export_random_generator_fill", 0, [layer], extent=extent)
```
Comment (nyalldawson) [inline tests/src/python/test_selective_masking.py:1316]: Make sure these tests use the standard test font

File: src/core/textrenderer/qgstextmasksettings.h [hunk 8]
```diff
@@ -196,14 +196,14 @@ class CORE_EXPORT QgsTextMaskSettings
     /**
      * Returns a list of references to symbol layers that are masked by this buffer.
      * \returns a list of references to masked symbol layers
-     * \see setMaskedSymbolLayers
+     * \see setMaskedSymbolLayers()
      */
-    QList<QgsSymbolLayerReference> maskedSymbolLayers() const;
+    const QList<QgsSymbolLayerReference> &maskedSymbolLayers() const;
```
Comment (nyalldawson) [inline src/core/textrenderer/qgstextmasksettings.h:201]:
```suggestion
    QList<QgsSymbolLayerReference> maskedSymbolLayers() const;
```

(as noted earlier)

File: src/core/symbology/qgssymbollayer.cpp [hunk 9]
```diff
@@ -930,3 +925,45 @@ void QgsSymbolLayer::prepareMasks( const QgsSymbolRenderContext &context )
...
+    context.painter()->save();
+    context.painter()->setClipPath( mClipPath, Qt::IntersectClip );
+  }
+
+  QgsSymbol *lSubSymbol = recursive ? subSymbol() : nullptr;
+  if ( lSubSymbol )
+  {
+    for ( QgsSymbolLayer *sl : lSubSymbol->symbolLayers() )
+      sl->installMasks( context, true );
+  }
```
Comment (nyalldawson) [inline src/core/symbology/qgssymbollayer.cpp:942]:
```suggestion
  if ( QgsSymbol *lSubSymbol = recursive ? subSymbol() : nullptr )
  {
    for ( QgsSymbolLayer *sl : lSubSymbol->symbolLayers() )
      sl->installMasks( context, true );
  }
```

File: src/core/symbology/qgssymbollayer.cpp [hunk 10]
```diff
@@ -930,3 +925,45 @@ void QgsSymbolLayer::prepareMasks( const QgsSymbolRenderContext &context )
...
+
+void QgsSymbolLayer::removeMasks( QgsRenderContext &context, bool recursive )
+{
+  if ( !mClipPath.isEmpty() )
+  {
+    context.painter()->restore();
+  }
+
+  QgsSymbol *lSubSymbol = recursive ? subSymbol() : nullptr;
+  if ( lSubSymbol )
```
Comment (nyalldawson) [inline src/core/symbology/qgssymbollayer.cpp:953]:
```suggestion
  if ( QgsSymbol *lSubSymbol = recursive ? subSymbol() : nullptr )
```

File: src/core/symbology/qgssymbollayer.h [hunk 11]
```diff
@@ -626,10 +626,26 @@ class CORE_EXPORT QgsSymbolLayer
...
+     * \since QGIS 3.30
+     */
+    void setId( const QString &id );
+
+    /**
+     * Returns symbol layer identifier
+     * This id is unique in the whole project
+     * \since QGIS 3.30
+     */
+    const QString &id() const;
```
Comment (nyalldawson) [inline src/core/symbology/qgssymbollayer.h:647]:
```suggestion
    QString id() const;
```

File: src/core/symbology/qgssymbollayer.h [hunk 12]
```diff
@@ -626,10 +626,26 @@ class CORE_EXPORT QgsSymbolLayer
...
      * This should be called prior to calling startRender() method.
+     * \see QgsRenderContext::addSymbolLayerClipPath()
+     * \see QgsRenderContext::symbolLayerClipPaths()
      * \since QGIS 3.26
      */
     virtual void prepareMasks( const QgsSymbolRenderContext &context );
 
+    /**
+     * Set symbol layer identifier
+     * This id has to be unique in the whole project
```
Comment (nyalldawson) [inline src/core/symbology/qgssymbollayer.h:637]:
```suggestion
     * \warning This ID must be unique within a whole project.
```

File: src/core/symbology/qgsfillsymbollayer.cpp [hunk 13]
```diff
@@ -2576,14 +2576,16 @@ bool QgsLinePatternFillSymbolLayer::hasDataDefinedProperties() const
   return false;
 }
 
-void QgsLinePatternFillSymbolLayer::startFeatureRender( const QgsFeature &, QgsRenderContext & )
+void QgsLinePatternFillSymbolLayer::startFeatureRender( const QgsFeature &, QgsRenderContext &context )
 {
   // deliberately don't pass this on to subsymbol here
```
Comment (nyalldawson) [inline src/core/symbology/qgsfillsymbollayer.cpp:2581]: it looks here like the existing comment applies to "installMasks", whereas it's actually referring to the call to startFeatureRender. Can you tweak the comments or add spacing or something to keep this distinction clear?

File: src/core/symbology/qgssymbollayerreference.cpp [hunk 14]
```diff
@@ -43,36 +35,57 @@ QgsSymbolLayerReferenceList stringToSymbolLayerReferenceList( const QString &str
   if ( str.isEmpty() )
     return lst;
 
-  // when saving we used ; as a concatenator... but that was silly, cos maybe the symbol keys contain this string!
-  // try to handle this gracefully via regex...
-  const thread_local QRegularExpression partsRx( QStringLiteral( "((?:.*?),(?:.*?),(?:(?:\\d+,)+)?(?:\\d+);)" ) );
-  QRegularExpressionMatchIterator partsIt = partsRx.globalMatch( str + ';' );
-
-  while ( partsIt.hasNext() )
+  if ( str.contains( "," ) )
```
Comment (nyalldawson) [inline src/core/symbology/qgssymbollayerreference.cpp:38]:
```suggestion
  if ( str.contains( ',' ) )
```

File: src/core/symbology/qgssymbollayerreference.cpp [hunk 15]
```diff
@@ -43,36 +35,57 @@ QgsSymbolLayerReferenceList stringToSymbolLayerReferenceList( const QString &str
...
+      {
+        indexPath.append( index.toInt() );
+      }
+      lst.append( QgsSymbolLayerReference( layerId, QgsSymbolLayerId( symbolKey, indexPath ) ) );
+      Q_NOWARN_DEPRECATED_POP
+    }
+  }
+  else
+  {
+    const QStringList elems = str.split( ";" );
```
Comment (nyalldawson) [inline src/core/symbology/qgssymbollayerreference.cpp:82]:
```suggestion
    const QStringList elems = str.split( ';' );
```

File: src/core/symbology/qgssymbollayerutils.h [hunk 16]
```diff
@@ -897,6 +898,39 @@ class CORE_EXPORT QgsSymbolLayerUtils
...
     static QgsStringMap evaluatePropertiesMap( const QMap<QString, QgsProperty> &propertiesMap, const QgsExpressionContext &context );
 
+    /**
+     * QgsSymbolLayerReference uses QgsSymbolLayer unique uuid identifier since QGIS 3.30, instead of the symbol
+     * key (rule for QgsRuleBasedRenderer for instance) and index path, so this method migrates \a mapLayers old references
+     * to new ones.
+     * \since QGIS 3.30
+     * \deprecated since QGIS 3.30
+     */
+    Q_DECL_DEPRECATED static void fixOldSymbolLayerReferences( const QMap<QString, QgsMapLayer *> &mapLayers );
```
Comment (nyalldawson) [inline src/core/symbology/qgssymbollayerutils.h:908]: Maybe QgsProjectFileTransform is a better place for this function to live?

File: src/core/symbology/qgsfillsymbollayer.cpp (hunk 13 above)
Comment (troopa81) [reply src/core/symbology/qgsfillsymbollayer.cpp:2581]: I moved install/remove masks after the comment and completed it a bit to remove ambiguity

File: tests/src/python/test_selective_masking.py (hunk 6 above)
Comment (troopa81) [reply tests/src/python/test_selective_masking.py:1246]: Done

File: tests/src/python/test_selective_masking.py (hunk 7 above)
Comment (troopa81) [reply tests/src/python/test_selective_masking.py:1316]: Done

File: src/core/symbology/qgssymbollayerutils.h (hunk 16 above)
Comment (troopa81) [reply src/core/symbology/qgssymbollayerutils.h:908]: Yes :+1:

**Comment by troopa81** [comment]
@nyalldawson I took care of all your comments, thank you for reviewing! 

mingw is failing but I don't think it's related (there is no clear reason of why it fails)

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
@troopa81 can you rebase and fix the merge conflicts, then we're good to merge this one :+1:

**Comment by troopa81** [comment]
> @troopa81 can you rebase and fix the merge conflicts, then we're good to merge this one

Done, thanks @nyalldawson

**Comment by thymaro** [comment]
Just for my understanding, does this mean that line pattern fills can be masked, now?

**Comment by troopa81** [comment]
> Just for my understanding, does this mean that line pattern fills can be masked, now?

Yes. It's available only in master and will be in 3.32
