### PR TITLE
Fix #47810 - zoom last and next with rotated map looses scale

### LINKED ISSUE #47810: Zoom Last zooms out further than the previous scale, rather than to the exact scale in scale history (ROTATED MAPS ONLY)
### What is the bug or the crash?

"Zoom Last" **should** go back to the exact scale in the scale history.

I'm manually digitizing features on 12,000 square miles of land from satellite imagery. On my computer I can visually scan an area scaled to 1:6500, but I often need a closer look when I find a feature. I use the zoom tool to get as close as I need to, digitize the feature, and then click "Zoom Last". At this point, the map zooms out to 1:7151 [see note 2], which makes the satellite imagery too small to scan, and I have to manually re-scale each time, which is an enormous time suck. 

I haven't been able to find any other reports of this issue or workarounds. I even tried to find a way to force predefined scales, but it doesn't seem to be possible. 

**Note 1:** To be clear this bug happens regardless of starting scale, or the method or amount of zooming in one step (e.g. single click vs. drawing a bounding box).

**Note 2:** While typing this bug report, the ending scale was _consistently 1:7151_ every time I started at 1:6500. This was true whether I clicked to zoom, drew a small bounding box, or drew a large bounding box. HOWEVER, when I tested the bug on a new user profile, the ending scale was _consistently 1:7133_. It turns out that this variation is due to the width of the left-docked panels going back to the default width on the new instance of QGIS [see Troubleshooting Tip below].

**Note 3:** After the first instance of incorrect rescaling, if I zoom in again, then "Zoom Last" operates appropriately. But at this point the last scale is incorrect.

**Troubleshooting Tips:**
1. I figured out that the left-docked panel width affects the amount of error, but not in any consistent pattern that I could see.
2. Basically, it seems as though QGIS doesn't like my chosen scale, so it picks something close.

### Steps to reproduce the issue

**UPDATE: Issue only occurs when map rotation is non-zero.** I'm working with the map rotated -3.7 degrees to align the grid of cadastre sections with my monitor and get more imagery on-screen. I checked for the bug with the rotation set to positive, negative, and zero values, and it only occurs when rotation is non-zero. Maddeningly, sometimes the error occurs right after changing the rotation, and other times I have to pan the map after changing the rotation, reset the scale to the preferred value, and try again.

0. Set map rotation to a non-zero value
1. Set scale
2. Use Zoom In tool either with a single click or drawing a box (NOT using scroll wheel or trackpad scrolling gesture)
3. Click "Zoom Last"
4. Denominator of scale is larger than that set in step 1. If not, pan the map a bit and go back to step 1.
5. Repeat step 2 without otherwise rescaling.
6. Click "Zoom Last"
7. Denominator of scale is the same as in step 4

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.4-Białowieża | QGIS code revision | 3f4577ce6e
-- | -- | -- | --
Qt version | 5.14.2
Python version | 3.8.7
GDAL/OGR version | 3.2.1
PROJ version | 6.3.2
EPSG Registry database version | v9.8.6 (2020-01-22)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.31.1
PostgreSQL client version | 12.3
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.4
OS version | macOS 11.6
  |   |   |  
Active Python plugins
lockzoom | 3.0.3
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.5

</body></html>QGIS version
3.22.4-Białowieża
QGIS code revision
[3f4577ce6e](https://github.com/qgis/QGIS/commit/3f4577ce6e)
Qt version
5.14.2
Python version
3.8.7
GDAL/OGR version
3.2.1
PROJ version
6.3.2
EPSG Registry database version
v9.8.6 (2020-01-22)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.31.1
PostgreSQL client version
12.3
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.4
OS version
macOS 11.6

Active Python plugins
lockzoom
3.0.3
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.5

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I have two WMS layers for satellite imagery: Google Satellite and Bing Maps. I also have Open Street Maps loaded as XYZ tiles.

### PR DESCRIPTION
**Pull request by Djedouas**
## Description

Fixes #47810

In QgsMapCanvas, for the extents history, use `mSettings.extent()` instead of `extent()` (which is `mSettings.visibleExtent()`).

In the case of a rotated map the visibleExtent ("Extent" in the picture below) is the bounding box of the zone the user sees ("Canvas" in the picture below).

In the extents history, using the visibleExtent leads to scale errors when rotation is non-zero.

### CODE REVIEW

File: src/gui/qgsmapcanvas.cpp [hunk 1]
```diff
@@ -1457,9 +1457,10 @@ void QgsMapCanvas::setExtent( const QgsRectangle &r, bool magnified )
     mLastExtent.removeAt( i );
   }
 
-  if ( !mLastExtent.isEmpty() && mLastExtent.last() != extent() )
+  QPair <QgsRectangle, double> currExtentScale = QPair( extent(), scale() );
```
Comment (troopa81) [inline src/gui/qgsmapcanvas.cpp:1460]:
```suggestion
  const QPair <QgsRectangle, double> currExtentScale = QPair( extent(), scale() );
```

File: src/gui/qgsmapcanvas.cpp [hunk 2]
```diff
@@ -1576,7 +1577,15 @@ void QgsMapCanvas::zoomToPreviousExtent()
   if ( mLastExtentIndex > 0 )
   {
     mLastExtentIndex--;
-    mSettings.setExtent( mLastExtent[mLastExtentIndex] );
+    QgsRectangle extent = mLastExtent[mLastExtentIndex].first;
+    mSettings.setExtent( extent );
```
Comment (troopa81) [inline src/gui/qgsmapcanvas.cpp:1581]: Wouldn't be better to setExtent once and for all after the if branch ?

File: src/gui/qgsmapcanvas.cpp [hunk 3]
```diff
@@ -1592,7 +1601,15 @@ void QgsMapCanvas::zoomToNextExtent()
   if ( mLastExtentIndex < mLastExtent.size() - 1 )
   {
     mLastExtentIndex++;
-    mSettings.setExtent( mLastExtent[mLastExtentIndex] );
+    QgsRectangle extent = mLastExtent[mLastExtentIndex].first;
+    mSettings.setExtent( extent );
+    if ( rotation() != 0 )
+    {
+      // When map is rotated the extent must be corrected to get the good scale
+      double savedScale = mLastExtent[mLastExtentIndex].second;
```
Comment (troopa81) [inline src/gui/qgsmapcanvas.cpp:1609]:
```suggestion
      const double savedScale = mLastExtent[mLastExtentIndex].second;
```
