### PR TITLE
OAPIF source select: fix missing extra query in collections url

### LINKED ISSUE #46535: OAPIF: api-key not included when requesting `/collections` endpoint
### What is the bug or the crash?

Adding an api-key (or any additional query param) to an OAPIF service is supported as per #38436.

However the additional query param is not used when the `/collections` endpoint is requested.
image

If the service requires the param to be present for the `/collections` endpoint QGIS is not able to load any features from the service at all.

### Steps to reproduce the issue

1) In datasource manager create an OAPIF endpoint and add an extra query param. (In this case it is a demo which requires a token running on localhost)
image

2) Click connect and see the error
image
3) The missing param can be seen in the "Debugging/Developer Tools" panel
image

### Versions

Tested on `3.20.3` and `3.22.1`.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Fix #46535

### CODE REVIEW

File: src/providers/wfs/qgswfssourceselect.cpp [hunk 1]
```diff
@@ -333,6 +333,16 @@ void QgsWFSSourceSelect::oapifLandingPageReplyFinished()
 
   mAvailableCRS.clear();
   QString url( mOAPIFLandingPage->collectionsUrl() );
+
+  // Add back any extra query parameters, see issue GH #46535
+  const QgsWfsConnection connection( cmbConnections->currentText() );
+  const QUrl connectionUrl( connection.uri().param( QStringLiteral( "url" ) ) );
+  if ( ! connectionUrl.query().isEmpty() )
+  {
+    url.append( '?' );
```
Comment (rouault) [inline src/providers/wfs/qgswfssourceselect.cpp:342]: it might be prudent to test if url has already query parameters, and append '&' instead of '?' in that situation

Comment (elpaso) [reply src/providers/wfs/qgswfssourceselect.cpp:342]: I don't think it's necessary, because the url coming from `mOAPIFLandingPage->collectionsUrl()` has already stripped the query string (which was the reason for the bug).

See: https://github.com/qgis/QGIS/pull/47145/files#diff-80852703dcc5dfa32d7ec9d31e4170a03146d6787bf637444e54bf9d18c61362R138

Comment (rouault) [reply src/providers/wfs/qgswfssourceselect.cpp:342]: hum, I'm not sure why we strip off query parameter from the URL. Maybe we should keep them ? There was perhaps a reason for doing that, but of course I've already forgotten...

Comment (elpaso) [reply src/providers/wfs/qgswfssourceselect.cpp:342]: I think it's because the collections url is used a base for appending the individual collection urls, my first attempt was to comment out the query string stripping block but the tests were not passing due to the fact that the individual collections urls were appended after the query string, something like `collections?my_param=xxx/my_collection`. By not altering the url returned from `mOAPIFLandingPage->collectionsUrl()` and appending it here we avoid that problem.

Comment (rouault) [reply src/providers/wfs/qgswfssourceselect.cpp:342]: > I think it's because the collections url is used a base for appending the individual collection urls

ah right

**Review by rouault — APPROVED** [review]
