### PR TITLE
Fix array display in expression builder

### LINKED ISSUE #45290: QGIS expression builder can not resolve PostgreSQL text arrays correctly
### What is the bug or the crash?

I have a PostGIS layer which contains text arrays. At the moment it is not possible to use field values resolved by the expression builder. If the array contains only one item, the field value will be ok, having two or more values within the array, the field value preview returns an empty string
2021-09-28 10_12_12-_edg — QGIS  English
g.

### Steps to reproduce the issue

1) load postgis layer containing text array fields
2) select by expression
3) fields and values
4) values->all unique->only show values in use
5) select entry with two or more values in the array
6) returns an empty string/array

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-Version | 3.20.3-Odense | QGIS-Codeversion | 495fbaec
-- | -- | -- | --
Qt-Version | 5.15.2
Python-Version | 3.9.5
GDAL-Version | 3.3.1
PROJ-Version | 8.1.1
EPSG-Registraturdatenbankversion | v10.028 (2021-07-07)
GEOS-Version | 3.9.1-CAPI-1.14.2
SQLite-Version | 3.35.2
PDAL-Versio | 2.3.0
PostgreSQL-Client-Version | 13.0
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.3
QScintilla2-Version | 2.11.5
BS-Version | Windows 10 Version 2009
  |   |   |  
Aktive Python-Erweiterungen | active_layer_searchGeoCodingpluginbuilder3plugin_reloaderQNEAT3db_managerMetaSearchprocessing

</body></html>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

version
PostgreSQL 11.12 (Debian 11.12-0+deb10u1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
postgis_version 2.5 USE_GEOS=1 USE_PROJ=1 USE_STATS=1

### PR DESCRIPTION
**Pull request by troopa81**
Fixes #45290 
It also fixes the display value when no list formatters have been set

### CODE REVIEW

File: src/core/qgsfield.cpp [hunk 1]
```diff
@@ -342,6 +342,20 @@ QString QgsField::displayString( const QVariant &v ) const
...
   }
+  else if ( d->type == QVariant::StringList || d->type == QVariant::List )
+  {
+    // we return an empty string if the list is empty, not a null string
+    QString result( "" );
+    const QVariantList list = v.toList();
+    for ( const QVariant &var : list )
+    {
+      if ( !result.isEmpty() )
+        result.append( ", " );
```
Comment (elpaso) [inline src/core/qgsfield.cpp:353]:
```suggestion
        result.append( QStringLiteral( ", " ) );
```

File: src/core/qgsfield.cpp [hunk 2]
```diff
@@ -342,6 +342,20 @@ QString QgsField::displayString( const QVariant &v ) const
   {
     return QObject::tr( "BLOB" );
   }
+  else if ( d->type == QVariant::StringList || d->type == QVariant::List )
+  {
+    // we return an empty string if the list is empty, not a null string
+    QString result( "" );
```
Comment (elpaso) [inline src/core/qgsfield.cpp:348]:
```suggestion
    QString result;
```

File: src/gui/qgsexpressionbuilderwidget.cpp [hunk 3]
```diff
@@ -542,15 +542,30 @@ void QgsExpressionBuilderWidget::fillFieldValues( const QString &fieldName, int
...
     else if ( value.type() == QVariant::Int || value.type() == QVariant::Double || value.type() == QVariant::LongLong )
       strValue = value.toString();
+    else if ( value.type() == QVariant::StringList )
+    {
+      QString result;
+      const QStringList strList = value.toStringList();
+      for ( QString str : strList )
+      {
+        if ( !result.isEmpty() )
+          result.append( ", " );
```
Comment (elpaso) [inline src/gui/qgsexpressionbuilderwidget.cpp:557]: literal

File: src/gui/qgsexpressionbuilderwidget.cpp [hunk 4]
```diff
@@ -542,15 +542,30 @@ void QgsExpressionBuilderWidget::fillFieldValues( const QString &fieldName, int
...
+
+        result.append( '\'' + str.replace( '\'', QLatin1String( "''" ) ) + '\'' );
+      }
+      strValue = QString( "array(%1)" ).arg( result );
```
Comment (elpaso) [inline src/gui/qgsexpressionbuilderwidget.cpp:561]:
```suggestion
      strValue = QStringLiteral( "array(%1)" ).arg( result );
```

**Review by elpaso — COMMENTED** [review]
small changes requested

**Comment by troopa81** [comment]
Done, thanks for reviewing @elpaso

**Review by elpaso — APPROVED** [review]
