### PR TITLE
do not explicitly mark source widget as valid as this overrides validation result (fix #52622)

### LINKED ISSUE #52622: 'Add' button for adding XYZ layer through Data Source Manager remains disabled
### What is the bug or the crash?

I want to add an XYZ layer. The way I used to do that is go through the 'Layer' menu, 'Add layer', 'XYZ layer' which takes me to the XYZ section in the Data Source Manager. In 3.30, you no longer have to add the 'connection', you can enter the URL for the server directly if you want to. On my machine, the connection URL (for Google Maps satellite) was correctly imported. But regardless of whether I select a connection in the drop down, or enter the details manually, the 'Add' button remains disabled, without any indication of why. I understand that for some dialog, it's disabled until all required information is filled in, but it's still frustrating not being able to see what is missing. But since 3.30 I can't get the button to be enabled no matter what I do. Tried this on a blank install (i.e., no previous versions present) also, but same problem.

### Steps to reproduce the issue

Go to the Data Source Manager/XYZ section. Put

`http://mt0.google.com/vt/lyrs=s&hl=en&x={x}&y={y}&z={z}`

in the URL bar (or add a saved connection). 'Add' button is never enabled.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.30.1-'s-Hertogenbosch | QGIS code revision | 9035a01e
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.3
PROJ version | 9.2.0
EPSG Registry database version | v10.082 (2023-02-06)
GEOS version | 3.11.2-CAPI-1.17.2
SQLite version | 3.41.1
PDAL version | 2.5.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
autoSaver | 2.6
latlontools | 3.6.9
valuetool | 3.0.15
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.30.1-'s-Hertogenbosch
QGIS code revision
[9035a01e](https://github.com/qgis/QGIS/commit/9035a01e)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.3
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
autoSaver
2.6
latlontools
3.6.9
valuetool
3.0.15
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alexbruy**
## Description
When adding an XYZ layer from the Datasource Manager by enetering an URL directly, the "Add" button remains disabled even if entered URL is valid. It also remains disabled when connection selected from the combobox.

Seems this happens because source widget is validated, but then explicitly marked as a valid overriding validation results and not emiting a signal.

Fixes #52622.

### CODE REVIEW

File: src/providers/wms/qgsxyzsourcewidget.cpp [hunk 1]
```diff
@@ -71,8 +71,6 @@ void QgsXyzSourceWidget::setSourceUri( const QString &uri )
   mAuthSettings->setConfigId( mSourceParts.value( QStringLiteral( "authcfg" ) ).toString() );
 
   setInterpretation( mSourceParts.value( QStringLiteral( "interpretation" ) ).toString() );
-
-  mIsValid = true;
```
Comment (nyalldawson) [inline src/providers/wms/qgsxyzsourcewidget.cpp:75]: shouldn't this be

    validate();

instead? If the uri string is empty then the widget won't be valid, and should emit the validChanged() signal accordingly

Comment (alexbruy) [reply src/providers/wms/qgsxyzsourcewidget.cpp:75]: Validation already happens above in the line 55. When `mEditUrl->setText()` is called this automatically triggers `validate` and all signals are emitted.

This explicit assignment then overrides validation results and does not any signal.

Comment (nyalldawson) [reply src/providers/wms/qgsxyzsourcewidget.cpp:75]: Ok, fair enough!

**Review by nyalldawson — APPROVED** [review]
