### PR TITLE
Remove auxiliary storage table after removing a vector layer from a p…

### LINKED ISSUE #44667: Auxiliary storage and removed layers
### What is the bug or the crash?

When removing a layer from a projet, the associated auxiliary storage is not deleted.

### Steps to reproduce the issue

- Create a new projet
- Add a layer (tested with a GeoJSON / WGS84)
- Add simple label
- Move one label in order to create an auxiliary storage
- Save the project
- Remove the layer
- Save the project
- Unzip the qgz file and look at the QGD -> it still contains the table

### Versions

Tested with 3.16.9 LTR and 3.20.1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pblottiere**
…roject

Fixes https://github.com/qgis/QGIS/issues/44667

### CODE REVIEW

File: src/core/project/qgsproject.h [hunk 1]
```diff
@@ -2173,6 +2173,11 @@ class CORE_EXPORT QgsProject : public QObject, public QgsExpressionContextGenera
      */
     bool addLayer( const QDomElement &layerElem, QList<QDomNode> &brokenNodes, QgsReadWriteContext &context, Qgis::ProjectReadFlags flags = Qgis::ProjectReadFlags() ) SIP_SKIP;
 
+    /**
+     * Remove auxiliary layer thanks to a vector later id.
```
Comment (lbartoletti) [inline src/core/project/qgsproject.h:2177]:
```suggestion
     * Remove auxiliary layer thanks to a vector layer id.
```

**Review by lbartoletti — APPROVED** [review]
lgtm, except a tiny typo.

File: src/core/project/qgsproject.h (hunk 1 above)
Comment (pblottiere) [reply src/core/project/qgsproject.h]: I updated the doc, thanks Loïc.
