### PR TITLE
fix: Data Source Manager doesn't release CSV file after closing dialog

### LINKED ISSUE #60649: Data Source Manager doesn't release CSV file after closing dialog
### What is the bug or the crash?

Hi,

after loading a CSV file into Data Source Manager, and closing dialog without adding a layer to QGIS, QGIS keeps connection to file on disk and doesn't allow any changes.

I haven't tested on Linux, only in Windows.

See short video demo:

[QGIS CSV release bug](https://www.youtube.com/watch?v=rBG850a2dgM "QGIS CSV release bug")

### Steps to reproduce the issue

Start loading a CSV file via `Data Source Manager`.
Exit without adding a layer to project.
Try to rename CSV file on disk. 

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.40.2-Bratislava</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/14826ca1">14826ca1</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.13</td></tr><tr><td>Python version</td><td>3.12.8</td></tr><tr><td>GDAL/OGR version</td><td>3.9.3</td></tr><tr><td>PROJ version</td><td>9.5.0</td></tr><tr><td>EPSG Registry database version</td><td>v11.016 (2024-08-31)</td></tr><tr><td>GEOS version</td><td>3.13.0-CAPI-1.19.0</td></tr><tr><td>SQLite version</td><td>3.46.1</td></tr><tr><td>PDAL version</td><td>2.8.1</td></tr><tr><td>PostgreSQL client version</td><td>16.2</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.3.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Windows 11 Version 2009</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by hxbb00**
fix: #60649

### CODE REVIEW

File: src/providers/delimitedtext/qgsdelimitedtextsourceselect.cpp [hunk 1]
```diff
@@ -537,7 +537,7 @@ void QgsDelimitedTextSourceSelect::updateFieldLists()
   // Run the scan in a separate thread
   cancelScanTask();
 
-  mScanTask = new QgsDelimitedTextFileScanTask( url( /* skip overridden types */ true ) );
+  mScanTask = new QgsDelimitedTextFileScanTask( url( mFile.get(), /* skip overridden types */ true ) );
```
Comment (troopa81) [inline src/providers/delimitedtext/qgsdelimitedtextsourceselect.cpp:540]: there is an issue with clang-tidy, not sure why. Could you call clear() on mScanTask later in the code instead of affecting nullptr and see if it fixes the cland-tidy issue ?

File: src/providers/delimitedtext/qgsdelimitedtextsourceselect.cpp [hunk 2]
```diff
@@ -860,9 +861,9 @@ void QgsDelimitedTextSourceSelect::updateCrsWidgetVisibility()
   textLabelCrs->setVisible( !geomTypeNone->isChecked() );
 }
 
-QString QgsDelimitedTextSourceSelect::url( bool skipOverriddenTypes )
+QString QgsDelimitedTextSourceSelect::url( QgsDelimitedTextFile *file, bool skipOverriddenTypes )
```
Comment (troopa81) [inline src/providers/delimitedtext/qgsdelimitedtextsourceselect.cpp:864]: Can we take a reference instead of pointer so we have no doubt about memory management of file ?

File: src/providers/delimitedtext/qgsdelimitedtextsourceselect.cpp (hunk 1 above)
Comment (hxbb00) [reply src/providers/delimitedtext/qgsdelimitedtextsourceselect.cpp]: call clear() do not fix it!

Comment (hxbb00) [reply src/providers/delimitedtext/qgsdelimitedtextsourceselect.cpp]: https://github.com/qgis/QGIS/actions/runs/13426309074/job/37512897078#step:9:1 it looks pass, but why has errors？

Comment (troopa81) [reply src/providers/delimitedtext/qgsdelimitedtextsourceselect.cpp]: @ptitjano fixed a few things related to clang-tidy. Could you rebase your branch on current master

**Review by troopa81 — APPROVED** [review]
All looks good, let's forget about clang-tidy here, this is not related to your modifications. We'll check this in another PR

**Comment by troopa81** [comment]
> All looks good, let's forget about clang-tidy here, this is not related to your modifications. We'll check this in another PR

forget what I just say, there is a clang-tidy issue. Not sure why

**Comment by troopa81** [comment]
OK, here is the culprit https://github.com/llvm/llvm-project/issues/58820

So, It has been fixed upstream. LGTM
