### PR TITLE
Remove rows when rolling back in transaction mode

### LINKED ISSUE #48171: Aborted inserts in Postgis geometryless tables are saved anyway
### What is the bug or the crash?

Hi,
I have a project with many PostGIS tables, including relations, and I activated the option to automatically create transaction groups in the project properties.  If I start to edit a table without geometry with the intention to insert a new item in it, but then decide to quit the edition mode without saving the changes, the item is nevertheless saved in the table.  I can remove it afterward by editing the table again and deleting it.

AFAIK this does not happen with the "create transaction groups" not activated, or on a layer with a geometry.  

### Steps to reproduce the issue

1. Select a Postgis layer without geometry
2. Open the attribute table
3. Click on the yellow pen
4. Click on the icon to add an entity
5. write something in the required attribute
6. Click on the yellow pen
7. Choose 'Don't save'. 

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Version de QGIS | 3.22.5-Białowieża | Révision du code | 2a0a86f142
-- | -- | -- | --
Version de Qt | 5.14.2
Version de Python | 3.8.7
Version de GDAL/OGR | 3.2.1
Version de Proj | 6.3.2
Version de la base de données du registre EPSG | v9.8.6 (2020-01-22)
Version de GEOS | 3.9.1-CAPI-1.14.2
Version de SQLite | 3.31.1
Version du client PostgreSQL | 12.3
Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.4
Version de QScintilla2 | 2.11.4
Version de l'OS | macOS High Sierra (10.13)
  |   |   |  
Extensions Python actives
SpreadsheetLayers | 2.0.1
save_attributes_processing | 0.1
go2streetview | 8.3
Assisted-MapMatching | 1.1
DataDrivenInputMask | 2.4.3
freehandEditing3 | version 1.1.0
trackable_project_files | v1.2.2
qgis_hats | 1.8
oneatlas-qgis-plugin-1_0_1 | 1.3.0
toggle_labels_widget | 1.0.2
quick_map_services | 0.19.29
track_profile_2_web | 1.3
save_attributes | 0.1
qdraw | 3.0.2
Discovery | 2.5.7
buienradar_plugin | 1.4
GeoCoding | 2.18
ImportPhotos | 3.0.3
MagicWand-master | 1.3.1
pluginbuilder3 | 3.2.1
HCMGIS | 21.8.28
latlontools | 3.6.3
AutomaticBackup-master | 1.0
processing_r | 3.1.1
relation_batchinsert | 0.3.2
Qgis2threejs | 2.7.1
OSMDownloader | 1.0.3
searchlayers | 3.0.7
profiletool-master | 4.1.6
report | 1.0.0
AutoLayoutTool | 1.1
postgis_geoprocessing | 0.9
plugin_reloader | 0.9.1
raster_tracer | 0.3.2
autoSaver | 2.6
mmqgis | 2021.9.10
layerfromclipboard | 0.12
MultiEdit | 1.1
Mergin | 2022.1
nominatim_locator_filter | 0.2.4
InvisibleLayersAndGroups | 2.2
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.5
LoadQSS | 1.4.2

</body></html>Version de QGIS
3.22.5-Białowieża
Révision du code
[2a0a86f142](https://github.com/qgis/QGIS/commit/2a0a86f142)
Version de Qt
5.14.2
Version de Python
3.8.7
Version de GDAL/OGR
3.2.1
Version de Proj
6.3.2
Version de la base de données du registre EPSG
v9.8.6 (2020-01-22)
Version de GEOS
3.9.1-CAPI-1.14.2
Version de SQLite
3.31.1
Version du client PostgreSQL
12.3
Version de SpatiaLite
4.3.0a
Version de QWT
6.1.4
Version de QScintilla2
2.11.4
Version de l'OS
macOS High Sierra (10.13)

Extensions Python actives
SpreadsheetLayers
2.0.1
save_attributes_processing
0.1
go2streetview
8.3
Assisted-MapMatching
1.1
DataDrivenInputMask
2.4.3
freehandEditing3
version 1.1.0
trackable_project_files
v1.2.2
qgis_hats
1.8
oneatlas-qgis-plugin-1_0_1
1.3.0
toggle_labels_widget
1.0.2
quick_map_services
0.19.29
track_profile_2_web
1.3
save_attributes
0.1
qdraw
3.0.2
Discovery
2.5.7
buienradar_plugin
1.4
GeoCoding
2.18
ImportPhotos
3.0.3
MagicWand-master
1.3.1
pluginbuilder3
3.2.1
HCMGIS
21.8.28
latlontools
3.6.3
AutomaticBackup-master
1.0
processing_r
3.1.1
relation_batchinsert
0.3.2
Qgis2threejs
2.7.1
OSMDownloader
1.0.3
searchlayers
3.0.7
profiletool-master
4.1.6
report
1.0.0
AutoLayoutTool
1.1
postgis_geoprocessing
0.9
plugin_reloader
0.9.1
raster_tracer
0.3.2
autoSaver
2.6
mmqgis
2021.9.10
layerfromclipboard
0.12
MultiEdit
1.1
Mergin
2022.1
nominatim_locator_filter
0.2.4
InvisibleLayersAndGroups
2.2
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.5
LoadQSS
1.4.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

### Additional context

It is the same with QGIS 3.24.1

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #48171

Or, more precisely, fixes the behavior described in the
comment:
https://github.com/qgis/QGIS/issues/48171#issuecomment-1132709901

Given the spaghetti-code of the the attribute table I would not recommend backporting for now.

### CODE REVIEW

File: src/gui/attributetable/qgsattributetablemodel.cpp [hunk 1]
```diff
@@ -74,7 +74,12 @@ QgsAttributeTableModel::QgsAttributeTableModel( QgsVectorLayerCache *layerCache,
 
   connect( mLayer, &QgsVectorLayer::editCommandStarted, this, &QgsAttributeTableModel::bulkEditCommandStarted );
   connect( mLayer, &QgsVectorLayer::beforeRollBack, this,  &QgsAttributeTableModel::bulkEditCommandStarted );
-  connect( mLayer, &QgsVectorLayer::afterRollBack, this, &QgsAttributeTableModel::bulkEditCommandEnded );
+  connect( mLayer, &QgsVectorLayer::afterRollBack, this, [ = ]
+  {
+    mIsRollingBack = true;
```
Comment (strk) [inline src/gui/attributetable/qgsattributetablemodel.cpp:79]: Should this be set to true when the ::beforeRollBack signal is received ? Would it make more sense ?

File: src/gui/attributetable/qgsattributetablemodel.h [hunk 2]
```diff
@@ -395,6 +395,12 @@ class GUI_EXPORT QgsAttributeTableModel: public QAbstractTableModel
     //! Changed attribute values within a bulk edit command
     QMap<QPair<QgsFeatureId, int>, QVariant> mAttributeValueChanges;
 
+    //! Inserted feature IDs within a bulk edit command
+    QList<QgsFeatureId> mInsertedRowsChanges;
+
+    //! TRUE if triggered by afterRollback()
+    bool mIsRollingBack = false;
```
Comment (strk) [inline src/gui/attributetable/qgsattributetablemodel.h:402]: The naming of this variable is not intuitive. "is rolling back" means we're in the middle of a rollback, so calling it from a signal which is sent *after* rolling back makes it counter-intuitive.

**Review by strk — COMMENTED** [review]
Any chance to see a testcase for the reported bug ?

File: src/gui/attributetable/qgsattributetablemodel.cpp (hunk 1 above)
Comment (elpaso) [reply src/gui/attributetable/qgsattributetablemodel.cpp]: I think that it's fine here, it's only used for this case and it is immediately clear that it is set right before and unset right after the call to bulkEditCommandEnded();

**Comment by elpaso** [comment]
> 

I'll have a look, but if I've not already wrote a test for it there are reasons:

1. could quite of an effort because it involves a few classes and requires a transactional DB (not sure if OGR-based spatialite or GPKG would be sufficient to trigger the issue)
2. it's GUI and tests for GUI are not required 
 
I agree a test never hurts but there are probably more urgent matters to address given the limited time and resources that we have.

File: src/gui/attributetable/qgsattributetablemodel.cpp (hunk 1 above)
Comment (strk) [reply src/gui/attributetable/qgsattributetablemodel.cpp]: > > 
> 
> I'll have a look, but if I've not already wrote a test for it there are reasons:
> 
>     1. could quite of an effort because it involves a few classes and requires a transactional DB (not sure if OGR-based spatialite or GPKG would be sufficient to trigger the issue)
> 
>     2. it's GUI and tests for GUI are not required
> 
> 
> I agree a test never hurts but there are probably more urgent matters to address given the limited time and resources that we have.

Personally I think simplifying the writing and running of tests is the most urgent matter, in QGIS.
PostgreSQL is transactional, having a way for tests to ONLY RUN IF an accessible PostgreSQL cluster is available (time to make it a FIXTURE ?) would be great.
Is there currently NO test at all for QGIS GUIs ? I see a tests/src/gui/ directory.

Comment (strk) [reply src/gui/attributetable/qgsattributetablemodel.cpp]: I do understand it is out-of-scope with the specific work of fixing *this* bug but maybe spending some time to do some research for tools helping with GUI testing will pay in the long run. I've found (but not tested) this project which looks interesting: http://pedromateo.github.io/openhmitester/

Comment (strk) [reply src/gui/attributetable/qgsattributetablemodel.cpp]: I've added the link to this new wiki page I created:
https://github.com/qgis/QGIS-Enhancement-Proposals/wiki/Testing-frameworks

Comment (elpaso) [reply src/gui/attributetable/qgsattributetablemodel.cpp]: You have to create an issue: https://github.com/qgis/QGIS-Enhancement-Proposals/issues
Anyway, QT already has a decent GUI testing framework.

**Comment by elpaso** [comment]
> Any chance to see a testcase for the reported bug ?

Test added

**Review by strk — APPROVED** [review]
Thank you for the test !

File: src/gui/attributetable/qgsattributetablemodel.cpp (hunk 1 above)
Comment (strk) [reply src/gui/attributetable/qgsattributetablemodel.cpp]: Yeah, I was going to do that but I realized I don't know the *existing* framework good enough to tell if we need something better. In any case a GUI based test *generator* like the one linked above would seem to make it very easy to create test for user reported bugs like this one, where the user uploaded a screencast of what is done to trigger a crash. Will probably create a lot of bloat but could be an effective way to guard after some fixes (maybe a separate repository for those kind of tests would be advisible)
