### PR TITLE
[Browser] Reorder the buttons position in the Browser SQL editor and only execute the selected SQL text

### LINKED ISSUE #57202: SQL console in QGIS Browser can't run just the selected part of an SQL statement (unlike DB Manager SQL console)
### What is the bug or the crash?

Title says it all. Also notice that the "clear" and "execute" buttons are not placed where expected... I find myself all the time pressing "clear" instead of "execute", and the damn thing does not even support undo (when pressing "clear").

### Steps to reproduce the issue

Title says it all.

### Versions

3.34.5

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by agiudiceandrea**
## Description

This PR:
- reorders the buttons position in the Browser SQL editor dialog window
- allows to only execute the selected SQL text as using the DB Manger

Video_2024-04-24_072947

***

Old description
This PR:
- swaps the "Execute" and "Clear" buttons position in the Browser SQL editor dialog window in order to make it more similar to the DB Manger SQL editor dialog window
before
image
after
image
@gioman, is it OK for you?

- allows to only execute the selected SQL text as using the DB Manger

Not sure if this should be considered a bug fix (and thus be backported) or a feature.

Fixes https://github.com/qgis/QGIS/issues/57202.

PS: @DelazJ, it looks like a description of the Browser SQL editor dialog window is missing in the docs. Doesn't it?

### CODE REVIEW

File: src/gui/qgsqueryresultwidget.cpp [hunk 1]
```diff
@@ -172,7 +172,7 @@ void QgsQueryResultWidget::executeQuery()
   cancelRunningQuery();
   if ( mConnection )
   {
-    const QString sql { mSqlEditor->text( ) };
+    const QString sql = mSqlEditor->selectedText().length() > 0 ? mSqlEditor->selectedText() : mSqlEditor->text();
```
Comment (agiudiceandrea) [inline src/gui/qgsqueryresultwidget.cpp:175]: I've used `selectedText().length() > 0` instead of `hasSelectedText()` after looking at https://github.com/qgis/QGIS/commit/c3d9f10cbe10dafb928d5e6416af832c94c9fc37 and https://web.archive.org/web/20230324055015/https://issues.qgis.org/issues/12193. Maybe it is no longer needed now...

**Comment by nyalldawson** [comment]
I can't find the discussion now, but I vaguely recall some past conversation where the "run only selected text" change was controversial. @elpaso does this ring any bells?

**Comment by elpaso** [comment]
@agiudiceandrea for what it worth I think it is more intuitive having the execution related buttons grouped together (execute and stop) while the clear button is editing related, having the stop button right aside the execute button may also help in case a user wanted to quickly halt the execution right after pushing execute. But I have no strong opinions (in other words: I don't care).

@nyalldawson it does but I can't find the old discussion now.
About the "execute selected" if IIRC the proposal was to make it explicit by adding an "Execute selected" button which is disabled if there is no selection. It would be even better if the SQL parser could detect a valid query before enabling the button (see: QgsSQLStatement).

**Comment by gioman** [comment]
@agiudiceandrea much better thanks! I don't have a string opinion in general too, but to stay consistent with DB manager is very important: I lost a complex query that took hours to refine because I hit "clear" instead of "execute" just because I'm used (we are) to how buttons are ordered in DB manager, and to find also that "undo" is not supported (I apologized for my harsh comment here https://github.com/qgis/QGIS/issues/57202#issuecomment-2068850370 but as you can imagine that was very very annoying to say the least).

**Comment by elpaso** [comment]
> @agiudiceandrea much better thanks! I don't have a string opinion in general too, but to stay consistent with DB manager is very important: I lost a complex query that took hours to refine because I hit "clear" instead of "execute" just because I'm used (we are) to how buttons are ordered in DB manager, and to find also that "undo" is not supported (I apologized for my harsh comment here [#57202 (comment)](https://github.com/qgis/QGIS/issues/57202#issuecomment-2068850370) but as you can imagine that was very very annoying to say the least).

While I can sympathize with you for your difficulties to adapt to a different interface, I don't think that copying the DB manager interface is a good enough strategy. 
The question here is what makes more sense from a UX point of view (which may well be the DB-manager solution).

About the attitude, I strongly advice you to soften your tones: it is usually much more effective to use a gentle and polite approach when asking people to volunteer their time to do something for you.

**Comment by gioman** [comment]
> I can't find the discussion now, but I vaguely recall some past conversation where the "run only selected text" change was controversial. @elpaso does this ring any bells?

I found strange to be controversial: I think is pretty common for final users (at least for me) to use the SQL console (any SQL console) as a place where to build by steps queries (plural) and not only where to run a final one written elsewhere. This makes really necessary the possibility to run just selected rows (as seen also in any other SQL console I have used like pgadmin4). A "execute only selected" would clearly address this but also maybe not necessary if we assume that running only selected rows is what anyone expects anyway.

**Comment by gioman** [comment]
> About the attitude, I strongly advice you to soften your tones: it is usually much more effective to use a gentle and polite approach when asking people to volunteer their time to do something for you.

@elpaso I apologized before this reply from you, This was unnecessary as it was my comment. I know well how things work and you know I know. I was just irritated and I know you understand what I mean.

**Comment by DelazJ** [comment]
> PS: @DelazJ, it looks like a description of the Browser SQL editor dialog window is missing in the docs. Doesn't it?

Indeed!
> swaps the "Execute" and "Clear" buttons position in the Browser SQL editor dialog window in order to make it more similar to the DB Manger SQL editor dialog window

from [developer guides](https://docs.qgis.org/testing/en/docs/developers_guide/hig.html)
> Keep harmful actions away from harmless ones: If you have actions for ‘delete’, ‘remove’ etc, try to impose adequate space between the harmful action and innocuous actions so that the users is less likely to inadvertently click on the harmful action.

and in this case I would consider "clear" button as a harmful button, compared to the others.

**Comment by gioman** [comment]
> While I can sympathize with you for your difficulties to adapt to a different interface,

As a long time and heavy db manager user I have the execute button imprinted in my brain, and probably I'm not alone.

> I don't think that copying the DB manager interface is a good enough strategy.
> The question here is what makes more sense from a UX point of view (which may well be the DB-manager solution).

Fair enough.

**Comment by agiudiceandrea** [comment]
Thanks for all your comments and suggestions!
I've found the previous discussion at https://github.com/qgis/QGIS/pull/55200.

I agree with @elpaso https://github.com/qgis/QGIS/pull/57211#issuecomment-2068620105 about the position of the "Stop" button and with @nyalldawson https://github.com/qgis/QGIS/pull/55200#issuecomment-1802786765 about the "Execute" / "Execute Selection" button.

Please see a PoC with the new buttons design:
Video_2024-04-24_072947

**Comment by elpaso** [comment]
> Please see a PoC with the new behaviour and buttons design: 

Looks good to me.

**Comment by Gustry** [comment]
Thanks for check @agiudiceandrea 

This POC looks good as well. It makes it clear.

**Comment by nyalldawson** [comment]
@agiudiceandrea the proof of concept looks good to me! Will you update this pr to match?

**Comment by agiudiceandrea** [comment]
> @agiudiceandrea the proof of concept looks good to me! Will you update this pr to match?

I apologize for the delay. I've force-pushed the updates as in the PoC and I've also updated the PR title and description accordingly.

I've not implemented the suggestions made by @Gustry in comment https://github.com/qgis/QGIS/pull/55200#issuecomment-1801392085, since I've not found a not ugly way to make such behaviour clear in the GUI and I'm also not completely convinced it should be the correct behaviour (nor I'm convinced the current behaviour is totally correct).

**Review by nyalldawson — APPROVED** [review]
