### PR TITLE
fix broken voronoi polygon algorithm when source attributes are not copied (fix #55450)

### LINKED ISSUE #55450: Unchecking "Copy attributes from input features" in Voronoi Polygons alg generates an empty layer
### What is the bug or the crash?

Running the new version of the "Voronoi polygons" alg, if you uncheck the "Copy attributes from input features" parameter, you might get an empty layer

### Steps to reproduce the issue

https://github.com/qgis/QGIS/assets/7983394/e59d1e16-3bde-4c88-9b21-092cd9392559

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.1-Prizren | QGIS code revision | 133927424d9
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 13.6
  |   |   |  
Active Python plugins
changeDataSource | 3.1
qtribu | 0.14.2
bdtopo_importer | 0.2
MemoryLayerSaver | 4.0.4
MapsPrinter | 0.9
lizmap | 3.8.3
StreetView | 3.2
processing | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alexbruy**
## Description

Fix broken Voronoi polygon algorithm when source attributes are not copied to the output layer.

Fixes #55450.

### CODE REVIEW

File: src/analysis/processing/qgsalgorithmvoronoipolygons.cpp [hunk 1]
```diff
@@ -204,11 +204,38 @@ QString QgsVoronoiPolygonsAlgorithm::voronoiWithoutAttributes( const QVariantMap
   if ( !sink )
     throw QgsProcessingException( invalidSinkError( parameters, QStringLiteral( "OUTPUT" ) ) );
 
+  QgsGeometry allPoints;
```
Comment (nyalldawson) [inline src/analysis/processing/qgsalgorithmvoronoipolygons.cpp:207]: It'd be more efficient to make this a `std::unique_ptr< QgsMultiPoint > ` instead, and call addGeometry on the multipoint directly instead of calling QgsGeometry::addPart (which has a LOT of extra stuff going on!).

Comment (alexbruy) [reply src/analysis/processing/qgsalgorithmvoronoipolygons.cpp]: Should be fixed, thanks.

**Review by nyalldawson — APPROVED** [review]
