### PR TITLE
suggest to fix topological mesh error when starting mesh editing

### LINKED ISSUE #50041: No obvious way to fix a broken mesh layer
### What is the bug or the crash?

 I got a crash while I had some mesh layers in edit mode. When I reopened the project I was unable to toggle one of them to edit mode again (`WARNING    Mesh editing : Unable to start mesh editing for layer "basetest"`). Reason I could find in the Log --> General tab is `Unable to start editing of mesh layer "basetest": Face 1824 is flat`. Great! But as far as I know, there is no way to find that 1824th face without going to edit mode...

### Steps to reproduce the issue

Sorry I no longer have the data

### Versions

QGIS 3.27 on Ubuntu 22.04

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vcloarec**
fix #50041 and #50062

It may happen that an editable mesh has topological errors that could prevent entering edit mode. The worst case is when the user edits a mesh, QGIS crashes and when he tries to restart editing, a topological error appeared and the user is unable to
modify the mesh... I didn't identify the reason because there is a check before saving the mesh, but apparently it happened. This leads to losing all the work on the mesh, even the saved work.

So, with this PR, when a topological prevents to enter editing mode, the following message box appears:
(here we can see a "manifold face", that is a face that cover another one, a quad).

image

If the user clicks "Yes", the mesh is fixed:

image

### CODE REVIEW

**Review by DelazJ — COMMENTED** [review]
Just some text fixes

File: src/core/mesh/qgsmesheditor.h [hunk 1]
```diff
@@ -82,9 +82,25 @@ class CORE_EXPORT QgsMeshEditor : public QObject
...
+     *  \since QGIS 3.28
+     */
+    QgsMeshEditingError initializeWithErrorsFix();
+
+    /**
+     * Tries to fix the topological \a error in the mesh. Returns false if the fix fails
+     *
+     * \since QGIS 3.28
+     */
+
```
Comment (uclaros) [inline src/core/mesh/qgsmesheditor.h:101]:
```suggestion
```

**Review by uclaros — APPROVED** [review]
Looks good, minor docstring changes.

It might be useful to add some reporting on the changes made by `QgsMeshEditor::fixError()`, like `x faces removed`/`y vertices removed`
