### PR TITLE
[processing][ui] When adding multiple layers via 'add directory', skip sidecar DBF files of shapefile datasets

### LINKED ISSUE #56010: Merge vector layers also adds dbf files using Add Directory
### What is the bug or the crash?

The Merge vector layers processing algorithm also adds dbf files when the Add Directory... option is used and the directory contains shapefiles.

image

the problem does not occur if I first loaded all the shapefiles into QGIS, in the list of files to merge I only find the shapefile files.

### Steps to reproduce the issue

1. launch QGIS
2. start Merge vector layers algorithm
3. click on the three dots in Input layers;
4. click on Add Directory...
5. Select a folder full of shapefiles
6. the dbf file is also present in the list of added files
7. the presence of the dbf file will duplicate the merged characteristic

## OSGeo4W 64b win 10 pro / QGIS 3.28.15 LTR Firenze e master

Versione di QGIS
3.28.15-Firenze
Revisione codice QGIS
252ad49ddc
Versione Qt
5.15.3
Versione Python
3.9.18
Versione GDAL/OGR
3.8.3
Versione PROJ
9.3.1
Versione database del Registro EPSG
v10.098 (2023-11-24)
Versione GEOS
3.12.1-CAPI-1.18.1
Versione SQLite
3.41.1
Versione PDAL
2.6.0
Versione client PostgreSQL
unknown
Versione SpatiaLite
5.1.0
Versione QWT
6.1.6
Versione QScintilla2
2.13.4
Versione SO
Windows 10 Version 2009

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

## the problem is present in QGIS 3.28.15, 3.34.3 and master

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This PR fixes  #56010 by adding some logic to avoid adding sidecar files to datasets in the processing multiple input panel widget's addDirectory() function.

Without the PR:
image

With the PR:
image

### CODE REVIEW

**Comment by agiudiceandrea** [comment]
I think the fix is also need in 3.34.

**Review by alexbruy — APPROVED** [review]

File: src/gui/processing/qgsprocessingmultipleselectiondialog.cpp [hunk 1]
```diff
@@ -395,6 +395,21 @@ void QgsProcessingMultipleInputPanelWidget::addDirectory()
...
+    {
+      if ( QFileInfo::exists( QStringLiteral( "%1.shp" ).arg( fullPath.chopped( 4 ) ) ) ||
+           QFileInfo::exists( QStringLiteral( "%1.SHP" ).arg( fullPath.chopped( 4 ) ) ) )
+      {
+        // Skip DBFs that are sidecar files to a Shapefile
+        continue;
+      }
+    }
+    else if ( fullPath.endsWith( QLatin1String( ".aux.xml" ), Qt::CaseInsensitive ) ||
+              fullPath.endsWith( QLatin1String( "shp.xml" ), Qt::CaseInsensitive ) )
```
Comment (rouault) [inline src/gui/processing/qgsprocessingmultipleselectiondialog.cpp:408]: maybe with a leading dot for consistency with above line ?
```suggestion
              fullPath.endsWith( QLatin1String( ".shp.xml" ), Qt::CaseInsensitive ) )
```

**Review by rouault — APPROVED** [review]

**Comment by pigreco** [comment]
Please is it possible to backport to 3.28 too

A thousand thanks
