### PR TITLE
Fix value relation QLR loading bug

### LINKED ISSUE #43978: ValueRelation in Attribute form wrong loaded from layer definition file (qlr)
**Describe the bug**

Value Relations are not correct loaded from a layerdefinition file as there is a filter set to a strange value like "_069acc1f_d4e7_49ce_b4bf_da8fbee8fbca". The result is that the dropdown in the form will be empty. 

**How to Reproduce**

1. new project
2. load attached qlr
3. layerproperties layer BA_DAT -> forms
4. field: BA_ART_LAT as one example

**QGIS and OS versions**
Windows 10, 64 bit, 3.18 and 3.20 / in 3.16 the qlr file is loaded correctly

**Additional context**

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #43978

### CODE REVIEW

File: tests/src/core/testqgslayerdefinition.cpp [hunk 1]
```diff
@@ -21,6 +21,7 @@
 
 #include <qgsapplication.h>
 #include <qgsproject.h>
+#include <qgsvectorlayer.h>
```
Comment (nyalldawson) [inline tests/src/core/testqgslayerdefinition.cpp:24]: Just a heads up -- this file is in the skip list for Travis, so your new test is basically a noop...

Comment (elpaso) [reply tests/src/core/testqgslayerdefinition.cpp]: Right, I moved the test.
