### PR TITLE
Fix issue with DD widget visibility in D&D forms

### LINKED ISSUE #53031: Attribute form widgets are not disabled when "Editable" state is data-defined and layer is not in edit mode
### What is the bug or the crash?

If the form widget of a field is made editable through a data-defined override, the widget will not be disabled although the layer is not in edit mode. 

This can be observed by opening the feature form through the "View feature form" action of the identify tool or by switching to form view in the attribute table. However, in the attribute table, the widget is only enabled for the first feature that is viewed in the form view.

### Steps to reproduce the issue

1. Add a vector layer with at least one field to a new QGIS project
2. Open its vector layer properties, go to the "Attributes Form" tab
3. Select a field widget, expand the `General` group of the widget configuration if necessary
4. Set a data-defined override for `Editable` so that the field will (always) be editable, e.g. enter `TRUE` in the expression builder
5. Apply the changes and close the properties window
6. Make sure the layer is not in edit mode
7. Activate the identify tool, click on a feature
8. In the Identify Results panel, open the context menu and click on `View feature form`

https://user-images.githubusercontent.com/78353871/236670097-f4520cb2-40d6-46d1-8191-daa4a52dcd2c.mp4

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.30.2-'s-Hertogenbosch | QGIS code revision | 0992b533
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.4
PROJ version | 9.2.0
EPSG Registry database version | v10.082 (2023-02-06)
GEOS version | 3.11.2-CAPI-1.17.2
SQLite version | 3.41.1
PDAL version | 2.5.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Fix #53031

### CODE REVIEW

File: src/gui/qgsattributeform.cpp [hunk 1]
```diff
@@ -1238,7 +1238,7 @@ void QgsAttributeForm::updateEditableState()
       {
         QWidget *w { it.key() };
         bool ok;
-        const bool isEditable { it->valueAsBool( context, true, &ok ) };
+        const bool isEditable { it->valueAsBool( context, true, &ok ) &&mLayer &&mLayer->isEditable() };
```
Comment (nyalldawson) [inline src/gui/qgsattributeform.cpp:1241]: Some weird formatting here!

**Review by nyalldawson — APPROVED** [review]

File: src/gui/qgsattributeform.cpp (hunk 1 above)
Comment (elpaso) [reply src/gui/qgsattributeform.cpp:1241]: blame astyle.
