### PR TITLE
[Postgres] Remove listener wait condition

### LINKED ISSUE #54260: Activating notify/listen feature crash QGIS
### What is the bug or the crash?

Activating "actualize layer on notification" in rendering tab or activating  "execute if message is ..." in python action, will freeze QGIS when applying. Need to crach QGIS to restart it. 

### Steps to reproduce the issue

1. Open new project
2. Load postgres layer
3. Got to rendering tab in layer property 
4. Activate "actualize layer on notification" 
5. Click "apply" or saving the project
6. QGIS Freeze

Follow the same steps on 
step 4 got to Action tab, set a python action, type a message in "Execute if message is "

### Versions

3.28.9 and 3.32

Version de QGIS | 3.28.9-Firenze | Révision du code | 66f4d63ad4
Version de Qt | 5.15.3
Version de Python | 3.10.6
Version de GDAL/OGR | 3.4.1
Version de Proj | 8.2.1
Version de la base de données du registre EPSG | v10.041 (2021-12-03)
Version de GEOS | 3.10.2-CAPI-1.16.0
Version de SQLite | 3.37.2
Version de PDAL | 2.3.0
Version du client PostgreSQL | unknown
Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.4
Version de QScintilla2 | 2.11.6
Version de l'OS | Ubuntu 22.04.3 LTS

Extensions Python actives
SpreadsheetLayers | 2.1.0
ImportPhotos | 3.0.5
refFunctions | 1.6
pickLayer | 3.9.6
EasyCustomLabeling | 2.1
qfieldsync | v4.5.0
MemoryLayerSaver | 5.0.1
openlayers_plugin | 2.0.0
attributePainter | 5.3
processing | 2.12.99
db_manager | 0.1.20
sagaprovider | 2.12.99
grassprovider | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Tested on Windows 10 and Ubuntu 22.04.3 LTS

### PR DESCRIPTION
**Pull request by troopa81**
Fixes #54260

The issue was because of 2 things:
- credential were requested though it was not necessary (auth configuration needed to be extended)
- Display the credential dialog was not possible because of the main thread blocking waitCondition 

This PR propose to create the connection and execute the listen request in the main thread and then doing the listening on the thread. This way, we still can garantee listening is set when setListening() ends and not block UI if credentials dialog need to popup.

I also reworked code a bit to use a plain QgsPostgresConn and log the listen connection.

### CODE REVIEW

**Comment by troopa81** [comment]
@elpaso Do you mind reviewing this PR please ?

**Comment by troopa81** [comment]
@strk Do you mind reviewing this PR ?

**Comment by strk** [comment]
Had you tried adding a testcase showing the crash ? I'd start there. I see fixes but I would prefer to see the crash first, and doing it with a test ensures it won't happen again in the future.

**Comment by troopa81** [comment]
> Had you tried adding a testcase showing the crash ? I'd start there. I see fixes but I would prefer to see the crash first, and doing it with a test ensures it won't happen again in the future.

You can do what is described in #54260 but you have to have a configuration authentication for the database layer.  That's the main reason of the crash.

**Comment by strk** [comment]
> You can do what is described in #54260 but you have to have a
> configuration authentication for the database layer.  That's the main
> reason of the crash.

I meant an automated test, one that is run as part of `make check`
and that can be run in isolation with a `ctest` invocation.

Can you try to write such test ?

**Comment by troopa81** [comment]
> Can you try to write such test ?

I thought about it but there is thread and UI synchronization involved, it's a mess to test and would be very hard to make a non-flaky test about it

File: src/providers/postgres/qgspostgreslistener.cpp [hunk 1]
```diff
@@ -37,17 +36,27 @@ std::unique_ptr< QgsPostgresListener > QgsPostgresListener::create( const QStrin
...
+
+    QgsPostgresResult result( mConn->LoggedPQexec( "QgsPostgresListener", QStringLiteral( "LISTEN qgis" ) ) );
+    if ( result.PQresultStatus() != PGRES_COMMAND_OK )
+    {
+      QgsDebugError( QStringLiteral( "error in listen" ) );
+
+      mConn->unref();
+      mConn = nullptr;
+    }
+  }
```
Comment (elpaso) [inline src/providers/postgres/qgspostgreslistener.cpp:59]: Should you log or handle the error in case mConn is nullptr?

Comment (elpaso) [reply src/providers/postgres/qgspostgreslistener.cpp:59]: Ok, I see it's handled later in run()

File: src/providers/postgres/qgspostgreslistener.cpp [hunk 2]
```diff
@@ -56,73 +65,27 @@ QgsPostgresListener::~QgsPostgresListener()
...
+  const int sock = PQsocket( mConn->pgConnection() );
   if ( sock < 0 )
   {
     QgsDebugError( QStringLiteral( "error in socket" ) );
-    PQfinish( conn );
     return;
   }
 
+  PGconn *pgconn = mConn->pgConnection();
   forever
```
Comment (elpaso) [inline src/providers/postgres/qgspostgreslistener.cpp:89]: I had to google this one :)

**Review by elpaso — APPROVED** [review]

**Comment by troopa81** [comment]
Thanks for the review @elpaso
