### PR TITLE
ogrprovider remove useless resetreading

### LINKED ISSUE #39178: setting a field to NULL via field calculator freezes qgis when "Automatic Creation of Transaction Group" is enabled
**How to Reproduce**
Try to set the tsize field of labs layer to NULL via field calculator .

related:
https://issues.qgis.org/issues/11422
[subdiv.zip](https://github.com/qgis/QGIS/files/5330575/subdiv.zip)

### PR DESCRIPTION
**Pull request by elpaso**
Followup to https://github.com/qgis/QGIS/pull/39244

Fixes #39178

### CODE REVIEW

File: src/core/providers/ogr/qgsogrfeatureiterator.cpp [hunk 1]
```diff
@@ -85,7 +95,7 @@ QgsOgrFeatureIterator::QgsOgrFeatureIterator( QgsOgrFeatureSource *source, bool
       return;
     }
 
-    if ( !mSource->mSubsetString.isEmpty() )
+    if ( ! mDoNotResetReading && !mSource->mSubsetString.isEmpty() )
```
Comment (rouault) [inline src/core/providers/ogr/qgsogrfeatureiterator.cpp:98]: to avoid the double negation, if we changed the variable to be mResetReadingAllowed that could make things slightly more obvious

File: src/core/providers/ogr/qgsogrfeatureiterator.cpp [hunk 2]
```diff
@@ -52,10 +52,10 @@ QgsOgrFeatureIterator::QgsOgrFeatureIterator( QgsOgrFeatureSource *source, bool
    * (see GH #39178) so we need to skip all calls that might reset the reading (rewind) to avoid an endless loop in the
    * outer fetching iterator that uses the same connection.
    */
-  mDoNotResetReading = transaction &&
-                       ( source->mDriverName == QLatin1String( "GPKG" ) || source->mDriverName == QLatin1String( "SQLite" ) ) &&
-                       ( mRequest.filterType() == QgsFeatureRequest::FilterType::FilterFid
-                         || mRequest.filterType() == QgsFeatureRequest::FilterType::FilterFids );
+  mAllowResetReading = ! transaction ||
+                       ( source->mDriverName != QLatin1String( "GPKG" ) & source->mDriverName != QLatin1String( "SQLite" ) ) ||
```
Comment (rouault) [inline src/core/providers/ogr/qgsogrfeatureiterator.cpp:56]:
```suggestion
                       ( source->mDriverName != QLatin1String( "GPKG" ) && source->mDriverName != QLatin1String( "SQLite" ) ) ||
```

**Comment by elpaso** [comment]
@rouault the test is not passing in Travis, is there any chance that GDAL 2.2.3 (that's the one in Travis) is doing some more calls to ResetReading? I checked GDAL code only with current master.

**Comment by rouault** [comment]
> is there any chance that GDAL 2.2.3 (that's the one in Travis) is doing some more calls to ResetReading?

yes, the GetFeature() implementation in the GPKG driver issued a ResetReading() before GDAL 2.3 . See https://github.com/qgis/QGIS/pull/39257/commits/d3d88e2df8ea77e6ed8b3e70c84aaf64ee769ba4#diff-f9f4ba686cf9f9a126d8c0364dcf0a06R2309

**Comment by elpaso** [comment]
@rouault so I guess the best we can do is to skip the test on GDAL < 2.3

**Comment by elpaso** [comment]
@rouault are you ok to merge and give this a try?

**Comment by rouault** [comment]
That looks good to me. Not sure I've more to bring on the testing side. Feel free to merge.

**Comment by Et7f3** [comment]
Hello, I still see the hang. I test only the added case.

```sh
$ python3.10 ../tests/src/python/test_provider_ogr_gpkg.py -v TestPyQgsOGRProviderGpkg.testTransactionGroupIterator
```

Do you know something that can help you in debugging ? Add some std::cout ? some log files ? my PYThONPATH ? I prefer to confirm it is a regression before opening an issue.

I have version `3.28.2` and `3.22.14`
