### PR TITLE
[bug] lazy vector extent not stored in the project

### LINKED ISSUE #61181: missing extent in .qgs maplayer definition for vector layers
### What is the bug or the crash?

Dear Developers,

in QGIS 3.40 and also in 3.28 it seems that the extent parameter in the maplayer definition of the QGIS project file does exist but without content for vector layer. It is not the case for raster layers or OWS.

Is this a bug or where is the maplayer extent gone and when was this change added?

Thanks a lot for any hint.

Kind regards
Otto

### Steps to reproduce the issue

I testet with QGIS 3.40 and 3.28. See sample project for 3.40 (extent.qgs) with a simple gpkg layer attached. The extent parameter in the .qgs file is added like this:

**a) vector layer**

```
<maplayer ... >
        [...]
        <extent/>
        [...]
</maplayer>
```

There is no <extent> or <wgs84extent> defined for the maplayer.

**b) raster layer**

```
<maplayer ... >
        [...]
      <extent>
        <xmin>-20037508.34278924390673637</xmin>
        <ymin>-20037508.34278924763202667</ymin>
        <xmax>20037508.34278924390673637</xmax>
        <ymax>20037508.34278924763202667</ymax>
      </extent>
      <wgs84extent>
        <xmin>-180</xmin>
        <ymin>-85.05112877980660357</ymin>
        <xmax>180</xmax>
        <ymax>85.05112877980660357</ymax>
      </wgs84extent>        
        [...]
</maplayer>
```
 
[maplayer_extent.zip](https://github.com/user-attachments/files/19447760/maplayer_extent.zip)

### Versions

tested with 3.28 and latest 3.40

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Fix #61181

When lazily set, if the project was stored without any call to QgsVectorLayer::extent() the QgsMapLayer::mExtent2D was null and not stored in the project.

### CODE REVIEW

File: src/core/qgsmaplayer.cpp [hunk 1]
```diff
@@ -755,8 +755,15 @@ bool QgsMapLayer::writeLayerXml( QDomElement &layerElement, QDomDocument &docume
...
     layerElement.appendChild( QgsXmlUtils::writeBox3D( mExtent3D, document ) );
-  else if ( !mExtent2D.isNull() )
-    layerElement.appendChild( QgsXmlUtils::writeRectangle( mExtent2D, document ) );
+  else
+  {
+    // Extent might be null because lazily set
+    const QgsRectangle extent2D { mExtent2D.isNull() ? extent() : mExtent2D };
+    if ( !extent2D.isNull() )
+    {
+      layerElement.appendChild( QgsXmlUtils::writeRectangle( mExtent2D, document ) );
```
Comment (rouault) [inline src/core/qgsmaplayer.cpp:764]: shouldn' that be ?
```suggestion
      layerElement.appendChild( QgsXmlUtils::writeRectangle( extent2D, document ) );
```

Comment (elpaso) [reply src/core/qgsmaplayer.cpp]: Actually the outcome is the same because when calling `extent()` the lazy evaluation of the extent is triggered and the mExtent2D is updated with the actual extent. But it's definitely clearer this way.

**Review by rouault — APPROVED** [review]
