### PR TITLE
Pyamids save as options

### LINKED ISSUE #47434: Overview creation options in "Save raster layer as..." takes too much space
### What is the bug or the crash?

image

### Steps to reproduce the issue

See screen

### Versions

3.22.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### LINKED ISSUE #49562: The "Pyramids" section in "Save raster as" dialog does not look nice
### What is the bug or the crash?

In Save raster as dialog, the "Pyramids" looks odd in QGIS widget styling, with : 
* an abuse of line separators
* a single line text box to enter the "create options": hard to read and edit, with all that blank space around. I wonder why this not relying on the same widget as the one in the upper "Create options group box"...

image
image

### Steps to reproduce the issue

See above

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.27.0-Master | QGIS code revision | 54240fa58c
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.4
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.1 LTS
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### LINKED ISSUE #49563: Collapse or hide the Pyramids section if not accessible
### What is the bug or the crash?

Depending on the layer, the "Save raster as" dialog can look like this
image

Since Pyramids is inaccessible, it shouldn't take all that space. Collapse it by default or hide it. The VRT group box for example is hidden if you are not creating VRT. So probably should be the same, then! --> HIDE!

### Steps to reproduce the issue

See above

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.27.0-Master | QGIS code revision | 54240fa58c
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.4
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.1 LTS
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by YoannQDQ**
- Fixes #49563
- Fixes #49562
- Fixes #47434

## Description

Fixes several bugs:
- Disabled groupboxes in the _save as..._ raster dialog (`QgsRasterLayerSaveAsDialog`) are expanded, and uncollapsible since they're disabled. Auto collapse them
- Buggy right click menu on the `QgsRasterFormatSaveOptionsWidget`, to switch between Tabke and LineEdit mode. Fix it.
- QgsRasterFormatSaveOptionsWidget takes as much space in LineEdit mode as in Table mode. Fix it.

### CODE REVIEW

File: src/gui/qgsrasterformatsaveoptionswidget.cpp [hunk 1]
```diff
@@ -98,10 +100,24 @@ QgsRasterFormatSaveOptionsWidget::QgsRasterFormatSaveOptionsWidget( QWidget *par
...
+  // Use a Custom Context menu for the widget to swap between modes (table / lineedit)
+  setContextMenuPolicy( Qt::CustomContextMenu );
+  connect( this, &QWidget::customContextMenuRequested, this, [this]( QPoint pos )
+  {
+    QMenu menu( this );
+    QString text;
+    if ( mTableWidget->isVisible() )
+      text = tr( "Use simple interface" );
+    else
+      text = tr( "Use table interface" );
```
Comment (nyalldawson) [inline src/gui/qgsrasterformatsaveoptionswidget.cpp:115]: I realise this isn't introduced here, but let's fix the action capitalization too:

```suggestion
      text = tr( "Use Simple Interface" );
    else
      text = tr( "Use Table Interface" );
```

File: src/gui/qgsrasterformatsaveoptionswidget.cpp [hunk 2]
```diff
@@ -567,31 +568,19 @@ void QgsRasterFormatSaveOptionsWidget::updateControls()
...
-      connect( action, &QAction::triggered, this, &QgsRasterFormatSaveOptionsWidget::swapOptionsUI );
-      menu->exec( mouseEvent->globalPos() );
-      delete menu;
-      return true;
-    }
+    QContextMenuEvent *contextEvent = static_cast<QContextMenuEvent *>( event );
+    QMenu *menu = nullptr;
+    menu = mOptionsLineEdit->createStandardContextMenu();
+    menu->addSeparator();
+    QAction *action = new QAction( tr( "Use table interface" ), menu );
```
Comment (nyalldawson) [inline src/gui/qgsrasterformatsaveoptionswidget.cpp:577]:
```suggestion
    QAction *action = new QAction( tr( "Use Table Interface" ), menu );
```

**Review by nyalldawson — APPROVED** [review]
