### PR TITLE
Fix glitchy table layout + easy option to copy versions information

### LINKED ISSUE #49054: Versions information copied from QGIS to GitHub issue has broken rendering
### What is the bug or the crash?

When filing a bug we are instructed to "In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here."

If I do that, the result is what's between the two OOOOOOOOOOOOOOOOOOOOOO lines below:

OOOOOOOOOOOOOOOOOOOOOO

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.3-Tisler | QGIS code revision | cf22b74e01
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.10 (Ubuntu 12.10-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.4 LTS
  |   |   |  
Active Python plugins
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
MetaSearch | 0.3.6
db_manager | 0.1.20

</body></html>QGIS version
3.24.3-Tisler
QGIS code revision
[cf22b74e01](https://github.com/qgis/QGIS/commit/cf22b74e01)
Qt version
5.12.8
Python version
3.8.10
GDAL/OGR version
3.0.4
PROJ version
6.3.1
EPSG Registry database version
v9.8.6 (2020-01-22)
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
SQLite version
3.31.1
PDAL version
2.0.1
PostgreSQL client version
12.10 (Ubuntu 12.10-0ubuntu0.20.04.1)
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.2
OS version
Ubuntu 20.04.4 LTS

Active Python plugins
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
MetaSearch
0.3.6
db_manager
0.1.20

OOOOOOOOOOOOOOOOOOOOOO

The table has broken columns (I presume), a false header, some inline CSS shown as code, and the text appearing again as list below.

### Steps to reproduce the issue

1. Help -> About
2. Click in table
3. Ctrl-A, Ctrl-C
4. Paste to GitHub

### Versions

QGIS version
3.24.3-Tisler
QGIS code revision
cf22b74e01
Qt version
5.12.8
Python version
3.8.10
GDAL/OGR version
3.0.4
PROJ version
6.3.1
EPSG Registry database version
v9.8.6 (2020-01-22)
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
SQLite version
3.31.1
PDAL version
2.0.1
PostgreSQL client version
12.10 (Ubuntu 12.10-0ubuntu0.20.04.1)
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.2
OS version
Ubuntu 20.04.4 LTS

Active Python plugins
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
MetaSearch
0.3.6
db_manager
0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Also happening on uptodate Archlinux IIRC. Also this is not a new bug but has been happening for many months (or more) already.

### PR DESCRIPTION
**Pull request by fiddlersfan**
## Description

Fixes the glitchy table layout and adds a button in the about page to copy the version information more easily as suggested in https://github.com/qgis/QGIS/issues/43739#issuecomment-916951618. The version information in the clipboard is available in a Github-friendly format.

Fixes #49054 

Before and after PR:
about-page
github-page

### CODE REVIEW

**Comment by agiudiceandrea** [comment]
Hi @fiddlersfan, I would suggest to also address https://github.com/qgis/QGIS/issues/42797 if possible.

File: src/app/qgsabout.cpp [hunk 1]
```diff
@@ -271,6 +274,12 @@ void QgsAbout::setPluginInfo()
   txtProviders->setText( myString );
 }
 
+void QgsAbout::btnCopyToClipboard_clicked()
+{
+  const QString versionString = QgisApp::instance()->getVersionString();
+  QGuiApplication::clipboard()->setText( versionString );
+}
```
Comment (nyalldawson) [inline src/app/qgsabout.cpp:281]: Instead of the back and forth between generating the string in QgisApp, setting it for the dialog via the call QgsAbout::setVersion from app, and then here calling BACK to QgisApp to get the string again, I'd suggest we instead store the raw string in a QString member variable in QgsAbout, and set its value directly in QgsAbout::setVersion

That'd avoid a bit of spaghetti logic :+1:

**Comment by fiddlersfan** [comment]
> Hi @fiddlersfan, I would suggest to also address #42797 if possible.

@agiudiceandrea IMHO that would exceed the scope of this PR. Maybe this is something for a follow-up.

File: src/app/qgsabout.cpp (hunk 1 above)
Comment (fiddlersfan) [reply src/app/qgsabout.cpp]: Sounds good to me, done  👍

**Comment by fiddlersfan** [comment]
@nyalldawson I have thought about integrating another change for the case of differing versions between compiling and running. My idea was to use a two-column layout here too. What do you think?

Current behavior:


Two-column layout:

**Comment by nyalldawson** [comment]
@fiddlersfan 
>  My idea was to use a two-column layout here too. What do you think?

That looks good to me!

**Comment by fiddlersfan** [comment]
> That looks good to me!

@nyalldawson Done, thanks for the review! When the latest version is released we should adjust the issue template. https://github.com/qgis/QGIS/blob/ec89b388536da3f5dca4e1028c72425f12b88c71/.github/ISSUE_TEMPLATE/10_bug_report.yml?plain=1#L40-L42

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
Thanks @fiddlersfan !

**Comment by agiudiceandrea** [comment]
@fiddlersfan, see https://github.com/qgis/QGIS/pull/61632.

**Comment by fiddlersfan** [comment]
Thanks @agiudiceandrea!
