### PR TITLE
[labeling] Remove empty inner rings when preparing label geometries to avoid crashes

### LINKED ISSUE #58570: QGIS (3.38.1) crashes when trying to show layer labels. QGIS died on signal 11.
### What is the bug or the crash?

I have got a simple vector layer with 2 objects. When I try to show their labels QGIS crashes with an error "QGIS died on signal 11".
If i zoom to only a single object, labels works as expected.

System info:
```
OS: Manjaro 24.0.8 Wynsdey
Kernel: x86_64 Linux 6.6.47-1-MANJARO 
DE: Xfce4 
WM: Xfwm4
CPU: Intel Core i3-8130U @ 4x 3.4GHz [41.0°C]
GPU: Intel Corporation UHD Graphics 620 (rev 07)
RAM: 2699MiB / 7851MiB
```

### Steps to reproduce the issue

Example project: [test.zip](https://github.com/user-attachments/files/16868779/test.zip)

1. Download and unpack "test.zip".
2. Open QGIS project "test_proj.qgz". It looks like this:
Снимок экрана_2024-09-04_13-30-39
3. Right click on the layer and click "Show labels" element. 
Screen-2024-09-04_13-33-33
4. BANG!! QGIS crashes.
Screen-2024-09-04_13-36-17

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Версия QGIS | 3.38.1-Grenoble | Кодовая ветка QGIS | Release 3.38
-- | -- | -- | --
Версия Qt | 5.15.14
Версия Python при сборке | 3.12.4 | Текущая версия Python | 3.12.5
Версия GDAL/OGR | 3.9.1
Версия PROJ | 9.4.1
Версия базы данных реестра EPSG | v11.006 (2024-03-13)
Версия GEOS | 3.12.2-CAPI-1.18.2
Версия SQLite при сборке | 3.46.0 | Текущая версия SQLite | 3.46.1
Версия PDAL | 2.7.2
Версия PostgreSQL | 16.3
Версия SpatiaLite | 5.1.0
Версия QWT | 6.3.0
Версия QScintilla2 | 2.14.1
Версия ОС | Manjaro Linux
  |   |   |  
Включённые модули Python
OSMDownloader | 1.0.3
SRTM-Downloader | 3.2.2
quick_map_services | 0.19.34
processing_saga_nextgen | 1.0.0
Group_and_Sort_Layers | 1.2
osminfo | 0.8.1
processing_r | 4.1.0
QuickOSM | 2.2.3
valuetool | 3.0.19
processing | 2.12.99
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6

</body></html>Версия QGIS
3.38.1-Grenoble
Кодовая ветка QGIS
[Release 3.38](https://github.com/qgis/QGIS/tree/release-3_38)
Версия Qt
5.15.14
Версия Python при сборке
3.12.4
Текущая версия Python
3.12.5
Версия GDAL/OGR
3.9.1
Версия PROJ
9.4.1
Версия базы данных реестра EPSG
v11.006 (2024-03-13)
Версия GEOS
3.12.2-CAPI-1.18.2
Версия SQLite при сборке
3.46.0
Текущая версия SQLite
3.46.1
Версия PDAL
2.7.2
Версия PostgreSQL
16.3
Версия SpatiaLite
5.1.0
Версия QWT
6.3.0
Версия QScintilla2
2.14.1
Версия ОС
Manjaro Linux

Включённые модули Python
OSMDownloader
1.0.3
SRTM-Downloader
3.2.2
quick_map_services
0.19.34
processing_saga_nextgen
1.0.0
Group_and_Sort_Layers
1.2
osminfo
0.8.1
processing_r
4.1.0
QuickOSM
2.2.3
valuetool
3.0.19
processing
2.12.99
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

As I once said (https://github.com/qgis/QGIS/issues/57298) even the basic QGIS functionality becomes unstable and unusable.

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This PR fixes https://github.com/qgis/QGIS/issues/58570 , whereas invalid polygons with empty interior ring(s) will crash QGIS when trying to label them.

The crash is caused by the assumption in the PAL logic that there will not be an interior ring with 0 coordinates. When such a bad ring occurs, we crash here: https://github.com/qgis/QGIS/blob/master/src/core/pal/feature.cpp#L142

Simply guarding from bad interior rings here (https://github.com/qgis/QGIS/blob/master/src/core/pal/feature.cpp#L107) is not enough as we then hit a GEOS crashes around here (https://github.com/libgeos/geos/blob/1c0840a47ac3c189baff87ca46b105d108363e31/src/algorithm/Centroid.cpp#L108).

The fix here proposes that we _guarantee_ non-empty interior rings when preparing label features in QgsPalLayerSettings::registerFeatureWithDetails.

### CODE REVIEW

**Comment by agiudiceandrea** [comment]
I suggest to backport this PR to both 3.38 and 3.34 branches.

File: src/core/qgis.h [hunk 1]
```diff
@@ -1885,6 +1885,26 @@ class CORE_EXPORT Qgis
...
     Q_ENUM( JoinStyle )
 
+    /**
+     * Flags which control geos geometry creation behavior.
+     *
+     * \since QGIS 3.40
+     */
+    enum class GeosCreationFlag : int SIP_ENUM_BASETYPE( IntFlag )
+    {
+      DontAllowInvalidSubGeom = 1 << 0,  //!< Don't allow invalid sub-geometries to be created
```
Comment (nyalldawson) [inline src/core/qgis.h:1895]: How about:

```suggestion
      SkipInvalidSubGeometry = 1 << 0,  //!< Don't allow invalid sub-geometries to be created
```

or maybe "Prevent"? "DontAllow" sounds rather clunky to me.

File: src/core/geometry/qgsgeos.h [hunk 2]
```diff
@@ -141,9 +141,10 @@ class CORE_EXPORT QgsGeos: public QgsGeometryEngine
      * GEOS geometry engine constructor
      * \param geometry The geometry
      * \param precision The precision of the grid to which to snap the geometry vertices. If 0, no snapping is performed.
-     * \param allowInvalidSubGeom Whether invalid sub-geometries should be skipped without error (since QGIS 3.38)
+     * \param flags Geos creation flags (since QGIS 3.40)
```
Comment (nyalldawson) [inline src/core/geometry/qgsgeos.h:144]:
```suggestion
     * \param flags GEOS creation flags (since QGIS 3.40)
```

File: src/core/qgis.h (hunk 1 above)
Comment (nirvn) [reply src/core/qgis.h:1895]: It can't be SkipInvalidSubGeometry as it does the exact opposite (i.e., by default code will skip invalid sub geometry, and with this flag it will bail out and returns and empty geom). 

RejectInvalidSubGeometry ?

**Comment by nirvn** [comment]
@nyalldawson , review addressed, thanks.

File: src/core/qgis.h [hunk 3]
```diff
@@ -1885,6 +1885,26 @@ class CORE_EXPORT Qgis
...
     Q_ENUM( JoinStyle )
 
+    /**
+     * Flags which control geos geometry creation behavior.
+     *
+     * \since QGIS 3.40
+     */
+    enum class GeosCreationFlag : int SIP_ENUM_BASETYPE( IntFlag )
+    {
+      RejectOnInvalidSubGeometry = 1 << 0,  //!< Don't allow invalid sub-geometries to be created
```
Comment (nyalldawson) [inline src/core/qgis.h:1895]:
```suggestion
      RejectOnInvalidSubGeometry = 1 << 0,  //!< Don't allow geometries with invalid sub-geometries to be created
```

Comment (nirvn) [reply src/core/qgis.h:1895]: @nyalldawson , much better!

**Review by nyalldawson — APPROVED** [review]
