### PR TITLE
Georeferencer preview point fixes

### LINKED ISSUE #44986: Georeferencer temporary gcp markers are moved when zoominig/panning
### What is the bug or the crash?

In the georeferencer, when adding a GCP to the canvas, a temporary green marker is displayed until the corresponding coordinates are entered and the final red marker is displayed.
Panning/zooming the canvas cause the temporary green marker to appear on the same screen location instead of the same canvas location which is confusing.

### Steps to reproduce the issue

1. Load a raster on the georeferencer
2. Click on the canvas to add a GCP
3. Before entering coordinates, pan or zoom on the georeference canvas
4. See the green marker at a new location

### Versions

e6b665bde4 on Debian bullseye

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

When the gcp is finally added, the correct initial location is used for the red marker.

### LINKED ISSUE #44987: Georeferencer temporary gcp markers can be added without a raster
### What is the bug or the crash?

In the georeferencer, a green temporary GCP marker can be added to the canvas if clicked without having a raster loaded

### Steps to reproduce the issue

1. Open the georeferencer
2. Click on the canvas to add a GCP without having a raster loaded
3. A green marker is added to the canvas

### Versions

e6b665b on Debian bullseye

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### LINKED ISSUE #44988: Georeferencer temporary gcp marker's tooltip is confusing
### What is the bug or the crash?

In the georeferencer, when adding a GCP to the canvas, a temporary green marker is displayed until the corresponding coordinates are entered and the final red marker is displayed.
If the GCP tooltips are enabled, then the temporary marker has a tooltip showing `-1` for the ID and `X 0.000000, Y 0.000000`. Displaying those values may be confusing.
The tooltip should be either completely skipped or only display the new ID number.

### Steps to reproduce the issue

1. Load a raster on the georeferencer
2. Go to settings > configure georeferencer > enable Show IDs and Show coordinates 
3. Click on the canvas to add a GCP
4. Before entering coordinates, see the temporary marker's tooltip

### Versions

e6b665b on Debian bullseye

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by uclaros**
## Description
- Preview points cannot be added before a layer is loaded
- Preview points do not display a point tip
- Preview points are correctly displayed when zooming/panning the canvases
- Last clicked preview point is actually used if georef canvas is clicked again while coords dialog is open

Fixes #44986
Fixes #44987
Fixes #44988

Also fixes old unreported regression: residual bars are now updated while moving GCPs

### CODE REVIEW

File: src/app/georeferencer/qgsgeorefdatapoint.cpp [hunk 1]
```diff
@@ -92,13 +92,18 @@ void QgsGeorefDataPoint::setEnabled( bool enabled )
 
 void QgsGeorefDataPoint::setId( int id )
 {
+  const bool noLongerTemporary = mId < 0 && id >= 0;
```
Comment (roya0045) [inline src/app/georeferencer/qgsgeorefdatapoint.cpp:95]: Variable name doesn't seem optimal, maybe "isValid" or "isPermanent"?

Comment (uclaros) [reply src/app/georeferencer/qgsgeorefdatapoint.cpp:95]: We only want to change the color if this call changes the point form a temporary ( < 0 ) to a permanent, hence the _noLonger_ in the name

**Review by nyalldawson — APPROVED** [review]
