### PR TITLE
Fix paste style categories on rasters

### LINKED ISSUE #63346: Selective pasting style does not change the ‘Automatically insert into print layout legend elements’ setting in raster layers
### What is the bug or the crash?

If I try to transfer the property "Include automatically in print layout legend items" #62876 from one raster layer to another, the property is not transferred.

### Steps to reproduce the issue

1. Add two raster layers
2. Uncheck "Include automatically in print layout legend items" in properties of raster layer 1
3. _Right click -> Styles -> Copy Style -> Legend Settings_ on raster layer 1
4. Paste the style via _Right click -> Styles -> Paste Style -> Legend Settings_ into raster layer 2
5. Open layer properties of layer 2, the Checkbox is still checked

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.99.0-Master</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/bcc5422e187">bcc5422e187</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.13</td></tr><tr><td>Python version</td><td>3.12.11</td></tr><tr><td>GDAL version</td><td>3.12.0dev-0679485d86 (Compiled)<br/>3.12.0dev-fa69f606a4 (Running)</td></tr><tr><td>PROJ version</td><td>9.6.2</td></tr><tr><td>EPSG Registry database version</td><td>v12.013 (2025-05-26)</td></tr><tr><td>GEOS version</td><td>3.13.1-CAPI-1.19.2</td></tr><tr><td>SQLite version</td><td>3.50.4</td></tr><tr><td>PDAL version</td><td>2.9.0</td></tr><tr><td>PostgreSQL client version</td><td>17.3</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.3.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Windows 10 Version 2009</td></tr><tr><td colspan="2"><i>This copy of QGIS writes debugging output.</i></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Sidenote: It works correctly when I copy  _All Style Categories_  and paste only the _Legend Settings_

### PR DESCRIPTION
**Pull request by elpaso**
Fix paste style categories on rasters.

Pasting raster categories other than symbology was a no-op

Fix https://github.com/qgis/QGIS/issues/63346

### CODE REVIEW

**Comment by fiddlersfan** [comment]
@elpaso Thank you very much for taking a look and for the quick fix. Unfortunately, this does not seem to have solved the entire problem:

"Property" in the following paragraphs refers to the checkbox "Include automatically in print layout legend items"

Initial situation 1:
Raster 1: Unchecked Property
Raster 2: Checked Property
Copy from R1 -> Paste it to R2 
Raster 2 property is unchecked -> Works fine!

Initial situation 2:
Raster 1: Checked Property
Raster 2: Unchecked Property
Copy from R1 -> Paste it to R2 
Raster 2 property remains unchecked -> So it doesn't work...

I'm not particularly familiar with the mechanisms of copy/pasting styles, but could the behaviour above be due to the property "excludeByDefault" not being included? Here is the plain text of the copies from R1 to R2

Initial situation 1:
```
<!DOCTYPE qgis PUBLIC 'http://mrcc.com/qgis.dtd' 'SYSTEM'>
<qgis layerType="Raster" styleCategories="Legend" version="3.99.0-Master">
 <legend excludeByDefault="1"/>
</qgis>
```

Initial situation 2:
```
<!DOCTYPE qgis PUBLIC 'http://mrcc.com/qgis.dtd' 'SYSTEM'>
<qgis layerType="Raster" styleCategories="Legend" version="3.99.0-Master"/>
```

**Comment by elpaso** [comment]
> property "excludeByDefault" not being included? 

Yes, that's it, good catch. I've added a test case for the second scenario and it's failing. Working on the fix.

**Comment by fiddlersfan** [comment]
I just tested it and it works now as expected. Thank you very much @elpaso !

File: src/app/qgisapp.cpp [hunk 1]
```diff
@@ -10421,9 +10421,11 @@ void QgisApp::pasteStyle( QgsMapLayer *destinationLayer, QgsMapLayer::StyleCateg
         return;
       }
 
-      bool isVectorStyle = doc.elementsByTagName( QStringLiteral( "pipe" ) ).isEmpty();
-      if ( ( selectionLayer->type() == Qgis::LayerType::Raster && isVectorStyle ) || ( selectionLayer->type() == Qgis::LayerType::Vector && !isVectorStyle ) )
+      const QDomElement rootElement { doc.firstChildElement( QStringLiteral( "qgis" ) ) };
+      const Qgis::LayerType styleOriginType { qgsEnumKeyToValue( rootElement.attribute( QStringLiteral( "layerType" ) ), Qgis::LayerType::Vector ) };
+      if ( selectionLayer->type() != styleOriginType )
       {
+        visibleMessageBar()->pushMessage( tr( "Cannot paste style to layer '%1' because the type doesn't match (%2 → %3)" ).arg( selectionLayer->name(), qgsEnumValueToKey( styleOriginType ), qgsEnumValueToKey( selectionLayer->type() ) ), errorMsg, Qgis::MessageLevel::Warning );
```
Comment (nyalldawson) [inline src/app/qgisapp.cpp]: I think we should use a (new) `QString QgsMapLayerUtils::translateLayerType( Qgis::LayerType )` function here instead of qgsEnumValueToKey. The enum keys are a bit ugly ("VectorTile" as opposed to "Vector Tile"), and definitely won't be useful for non-english speakers.

File: src/core/qgsmaplayerlegend.cpp [hunk 2]
```diff
@@ -42,17 +42,14 @@ QgsMapLayerLegend::QgsMapLayerLegend( QObject *parent )
...
 
 QDomElement QgsMapLayerLegend::writeXml( QDomDocument &doc, const QgsReadWriteContext & ) const
 {
   QDomElement elem = doc.createElement( QStringLiteral( "legend" ) );
-
-  if ( mFlags.testFlag( Qgis::MapLayerLegendFlag::ExcludeByDefault ) )
-    elem.setAttribute( QStringLiteral( "excludeByDefault" ), QStringLiteral( "1" ) );
-
-  return elem.attributes().isEmpty() ? QDomElement() : elem;
+  elem.setAttribute( QStringLiteral( "excludeByDefault" ), mFlags.testFlag( Qgis::MapLayerLegendFlag::ExcludeByDefault ) ? QStringLiteral( "1" ) : QStringLiteral( "0" ) );
```
Comment (nyalldawson) [inline src/core/qgsmaplayerlegend.cpp]: Is this change actually needed? The original intent was to avoid bloating the XML when there's no need to write this element.

Comment (elpaso) [reply src/core/qgsmaplayerlegend.cpp]: > Is this change actually needed? The original intent was to avoid bloating the XML when there's no need to write this element.

yes, it's needed because of the check for null  in https://github.com/qgis/QGIS/blame/master/src/core/raster/qgsrasterlayer.cpp#L2287

Comment (elpaso) [reply src/core/qgsmaplayerlegend.cpp]: Well, I guess we can just return and empty legend element instead.

File: src/app/qgisapp.cpp (hunk 1 above)
Comment (elpaso) [reply src/app/qgisapp.cpp]: done

File: src/core/qgsmaplayerutils.h [hunk 3]
```diff
@@ -104,6 +104,13 @@ class CORE_EXPORT QgsMapLayerUtils
      */
     static bool isOpenStreetMapLayer( QgsMapLayer *layer );
 
+    /**
+     * Returns the translated name of the type for a given layer type.
+     *
+     * \since QGIS 4.0
+     */
+    static QString translateLayerType( const Qgis::LayerType &type );
```
Comment (nyalldawson) [inline src/core/qgsmaplayerutils.h]:
```suggestion
    static QString translateLayerType( Qgis::LayerType type );
```

File: src/app/qgisapp.cpp (hunk 1 above)
Comment (nyalldawson) [inline src/app/qgisapp.cpp]:
```suggestion
        visibleMessageBar()->pushMessage( tr( "Cannot paste style to layer '%1' because the type doesn't match (%2 → %3)" ).arg( selectionLayer->name(), QgsMapLayerUtils::translateLayerType( styleOriginType ), QgsMapLayerUtils::translateLayerType( selectionLayer->type() ) ), errorMsg, Qgis::MessageLevel::Warning );
```

File: src/app/qgisapp.cpp [hunk 4]
```diff
@@ -74,6 +74,7 @@
 #include <QWindow>
 #include <QActionGroup>
 
+#include "qgsmaplayerutils.cpp"
```
Comment (fiddlersfan) [inline src/app/qgisapp.cpp]: @elpaso My C++ skills are absolutely basic, but shouldn't it be qgsmaplayerutils.h instead of qgsmaplayerutils.cpp here?

Comment (elpaso) [reply src/app/qgisapp.cpp]: of course, thanks for noticing.

File: src/core/qgsmaplayerutils.h [hunk 5]
```diff
@@ -104,6 +104,13 @@ class CORE_EXPORT QgsMapLayerUtils
      */
     static bool isOpenStreetMapLayer( QgsMapLayer *layer );
 
+    /**
+     * Returns the translated name of the type for a given layer type.
+     *
+     * \since QGIS 4.0
+     */
+    static QString translateLayerType( Qgis::LayerType type );
```
Comment (nirvn) [inline src/core/qgsmaplayerutils.h]: That's a nice polishing. What about matching the function name with what we have in say QgsUnitTypes (i.e. layerTypeToString( ... ) ?

Comment (elpaso) [reply src/core/qgsmaplayerutils.h]: @nirvn this request actually came from @nyalldawson https://github.com/qgis/QGIS/pull/63430#discussion_r2430896477 I am happy to follow your advice if you can find an agreement but IMHO it's good to know from the function name that it returns a localized string instead of an untranslated string representation.

**Comment by elpaso** [comment]
@nirvn can I beg for an approval here?

**Review by jef-n — APPROVED** [review]

**Comment by elpaso** [comment]
@jef-n thanks :)
