### PR TITLE
Don't allow non-polygon avoid intersection layers

### LINKED ISSUE #59067: Extra vertices form from line intersections when avoiding overlaps
### What is the bug or the crash?

It is possible to add line layers to `avoidIntersectionsLayers`. This has unwanted effects when using topological editing with "Follow advanced configuration" avoid overlapping setting. As seen in the animation, when both layers are set in `avoidIntersectionsLayers`, extra vertex is formed in polygon in the line intersection. 

avoid_overlap_with_line_layers

  Maybe it should not be allowed to add line layers as avoid intersection layers? Avoid overlap setting is not even visible for line layers in the project snapping settings.

### Steps to reproduce the issue

1. Open [overlap_test_data.zip](https://github.com/user-attachments/files/17360762/overlap_test_data.zip) project (open from - geopackage)
2. Enable editing for polygon layer
3. Make sure topological editing is enabled
4. Make sure snapping on segment and all layers is enabled
5. Make sure avoid overlapping setting is set to "Follow Advanced Configuration"
6. Digitize new feature for polygon layer

Extra vertex appears on line intersection.

The problem does not occur if the line layer is not in `avoidIntersectionsLayers` (by selecting polygon as an active layer and running `QgsProject.instance().setAvoidIntersectionsLayers([iface.activeLayer()])`).

### Versions

<details>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.39.0-Master
-- | --
QGIS code revision | 666983c678b
 
Libraries
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 14.10 (Ubuntu 14.10-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.3 LTS
This copy of QGIS writes debugging output.
 
Active Python plugins
plugin_reloader | 0.14
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99
grassprovider | 2.12.99

</body></html>QGIS version
3.39.0-Master
QGIS code revision
[666983c678b](https://github.com/qgis/QGIS/commit/666983c678b)
 
Libraries
Qt version
5.15.3
Python version
3.10.12
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
14.10 (Ubuntu 14.10-0ubuntu0.22.04.1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.3 LTS
This copy of QGIS writes debugging output.
 
Active Python plugins
plugin_reloader
0.14
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99
grassprovider
2.12.99

</details>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JuhoErvasti**
Disallow adding line and point layers to avoid intersections layers. This mainly concerns PyQGIS - setting avoid intersections layers through the GUI for non-polygon layers is already not possible.

Fixes #59067

### CODE REVIEW

File: src/core/project/qgsproject.h [hunk 1]
```diff
@@ -1113,6 +1113,7 @@ class CORE_EXPORT QgsProject : public QObject, public QgsExpressionContextGenera
     /**
      * Sets the list of layers with which intersections should be avoided.
      * Only used if the avoid intersection mode is set to advanced.
+     * Line and point layers will not be added.
```
Comment (nyalldawson) [inline src/core/project/qgsproject.h:1116]:
```suggestion
     * Sets the list of layers with which intersections should be avoided.
     *
     * \note Only used if the avoid intersection mode is set to advanced.
     *
     * \note Any line or point layers will be ignored.
```

**Review by nyalldawson — APPROVED** [review]

**Review by lbartoletti — APPROVED** [review]
