### PR TITLE
Correctly split 3D feature

### LINKED ISSUE #52145: Splitfeatures function
### What is the bug or the crash?

Before update I use version 3.24
I can use "splitfeatures" function to split 3Dpolyline and 3Dpolygon with z value created with result.
After update to 3.30, I split 3Dpolyline and 3Dpolygon, i get "0" z value with vertex i splited.
Can anyone help to fix it?

### Steps to reproduce the issue

No

### Versions

After3.24

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by troopa81**
Fixes #52145 : When we split a feature with Z values, we need to do it with a splitting line without Z, so geos correctly assign the new intersecting point Z value with the interpolated Z value of adjacent vertices. If not it would compute the mean value with the default Z value.

### CODE REVIEW

File: src/core/geometry/qgsgeos.cpp [hunk 1]
```diff
@@ -976,17 +976,16 @@ bool QgsGeos::topologicalTestPointsSplit( const GEOSGeometry *splitLine, QgsPoin
...
       const GEOSCoordSequence *lineSequence = GEOSGeom_getCoordSeq_r( geosinit()->ctxt, currentIntersectGeom );
       unsigned int sequenceSize = 0;
-      double x, y;
+      double x, y, z;
       if ( GEOSCoordSeq_getSize_r( geosinit()->ctxt, lineSequence, &sequenceSize ) != 0 )
       {
         for ( unsigned int i = 0; i < sequenceSize; ++i )
         {
-          if ( GEOSCoordSeq_getX_r( geosinit()->ctxt, lineSequence, i, &x ) != 0 )
+          if ( GEOSCoordSeq_getX_r( geosinit()->ctxt, lineSequence, i, &x ) != 0
```
Comment (nyalldawson) [inline src/core/geometry/qgsgeos.cpp:984]: This should use GEOSCoordSeq_getXYZ_r where available -- it'll be much faster

File: src/app/qgsmaptoolsplitfeatures.cpp [hunk 2]
```diff
@@ -113,7 +113,14 @@ void QgsMapToolSplitFeatures::cadCanvasReleaseEvent( QgsMapMouseEvent *e )
     const bool topologicalEditing = QgsProject::instance()->topologicalEditing();
     QgsPointSequence topologyTestPoints;
     vlayer->beginEditCommand( tr( "Features split" ) );
-    const Qgis::GeometryOperationResult returnCode = vlayer->splitFeatures( captureCurve(), topologyTestPoints, true, topologicalEditing );
+
+    // we need to drop Z value to properly split 3D feature in 2D. If not, generated vertices Z value
+    // will be assigned with the mean value between the interpolated Z values of the intersecting point
+    // and the default Z value, which is not what we want
+    QgsCompoundCurve *curve = captureCurve()->clone();
```
Comment (nyalldawson) [inline src/app/qgsmaptoolsplitfeatures.cpp:120]: There's a leak here:
```suggestion
    std::unique_ptr< QgsCompoundCurve > curve( captureCurve()->clone() );
```

**Comment by troopa81** [comment]
@nyalldawson I take care about all your comments, thanks for the review

**Review by nyalldawson — APPROVED** [review]
