### PR TITLE
Check file existance in QgsFileWidget - Fixes #46077

### LINKED ISSUE #46077: Attachment widget: "default path" is completely ignored
### What is the bug or the crash?

The "default path" in the attachment widget (maybe also others) is said to:

`"When not empty, always open the file selector at the root of this path for searching new files. If empty, the last used path of this editor widget will be used. If this editor widget has never been used by the user, the project path will be used."`

but nothing of the above happens, and when clicking the button to look for a file it always default to some folder that is OS dependent.

### Steps to reproduce the issue

Local scenario

postgis geometryless table

text field, with "attachment" widget.

### Versions

QGIS 3.16.13 and 3.22.0 on Win10.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Djedouas**
## Description

This MR fixes #46077 

---

Currently the behavior of the QgsFileWidget browse button depends on the text already in the file text zone :

- If the text is an existing file, the browse window opens 
  - in the file directory, the file is selected
- If the text is empty, the browse windows opens
  - in the default root path if the default root path is specified
  - in the last browsed path if it's not the first time the browse window is opened
  - in the project directory if it's the first time the browse window is opened
- if the text is not an existing file but still something, the browser opens
  - in a system-dependent default path (decided by QFileDialog.getOpenFileName method)

This MR aims to handle the following cases:
- if the QgsFileWidget text is not empty and not an existing directory/file --> treat as if the text is empty

### CODE REVIEW

File: src/gui/qgsfilewidget.cpp [hunk 1]
```diff
@@ -281,7 +281,7 @@ void QgsFileWidget::openFileDialog()
 
   // if we use a relative path option, we need to obtain the full path
   // first choice is the current file path, if one is entered
-  if ( !mFilePath.isEmpty() )
+  if ( !mFilePath.isEmpty() && QFile( mFilePath ).exists() )
```
Comment (nyalldawson) [inline src/gui/qgsfilewidget.cpp:284]:
```suggestion
  if ( !mFilePath.isEmpty() && QFile::exists( mFilePath ) )
```

(the static QFile::exists() method is more efficient vs constructing a QFile object)

**Review by nyalldawson — APPROVED** [review]
