### PR TITLE
Handle copy of vextex tool table into clipboard

### LINKED ISSUE #46407: Can't copy to clipboard vertex editor table
### What is the bug or the crash?

Title is pretty mush everything.

I'm able to copy 1 cell but not the entire table.

### Steps to reproduce the issue

1. Create a dummy polygon 
2. Enable vertex edit mode
3. Right click on your polygon
4. Select all the table
5. CTRL-C
6. Try to paste somewhere else, nothing.

### Versions

Qgis 3.22.1 OSGeo4W v2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Djedouas**
## Description

When selecting rows in the vertex editor table panel, and hitting `Ctrl+C`, only the cell which was first clicked with the pointer during selection is copied into the clipboard.

This MR enables all the selected rows to be copied into the clipboard.

I chose to use a comma as a column separator, as I didn't find a global QgsSetting for a value separator.

fixes #46407

### CODE REVIEW

File: src/app/vertextool/qgsvertexeditor.cpp [hunk 1]
```diff
@@ -457,6 +459,20 @@ void QgsVertexEditor::keyPressEvent( QKeyEvent *e )
...
+  else if ( e->matches( QKeySequence::Copy ) )
+  {
+    QString text;
+    QItemSelectionRange range = mTableView->selectionModel()->selection().first();
+    for ( auto i = range.top(); i <= range.bottom(); ++i )
+    {
+      QStringList rowContents;
+      for ( auto j = range.left(); j <= range.right(); ++j )
+        rowContents << mVertexModel->index( i, j ).data().toString();
+      text += rowContents.join( "," );
```
Comment (m-kuhn) [inline src/app/vertextool/qgsvertexeditor.cpp:471]:
```suggestion
      text += rowContents.join( ',' );
```

File: src/app/vertextool/qgsvertexeditor.cpp [hunk 2]
```diff
@@ -457,6 +459,20 @@ void QgsVertexEditor::keyPressEvent( QKeyEvent *e )
...
     e->ignore();
   }
+  else if ( e->matches( QKeySequence::Copy ) )
+  {
+    QString text;
+    QItemSelectionRange range = mTableView->selectionModel()->selection().first();
+    for ( auto i = range.top(); i <= range.bottom(); ++i )
+    {
+      QStringList rowContents;
+      for ( auto j = range.left(); j <= range.right(); ++j )
```
Comment (m-kuhn) [inline src/app/vertextool/qgsvertexeditor.cpp:469]:
```suggestion
    for ( int i = range.top(); i <= range.bottom(); ++i )
    {
      QStringList rowContents;
      for ( int j = range.left(); j <= range.right(); ++j )
```

**Review by m-kuhn — COMMENTED** [review]
Looking good, thank you

File: src/app/vertextool/qgsvertexeditor.cpp [hunk 3]
```diff
@@ -457,6 +459,20 @@ void QgsVertexEditor::keyPressEvent( QKeyEvent *e )
     // Override default shortcut management in MapCanvas
     e->ignore();
   }
+  else if ( e->matches( QKeySequence::Copy ) )
+  {
+    QString text;
+    QItemSelectionRange range = mTableView->selectionModel()->selection().first();
```
Comment (nyalldawson) [inline src/app/vertextool/qgsvertexeditor.cpp:465]: better check that the selection is not empty first, or calling .first() will crash

**Comment by Djedouas** [comment]
Thanks for the review @m-kuhn @nyalldawson !

I pushed the suggested changes

**Review by m-kuhn — APPROVED** [review]

File: src/app/vertextool/qgsvertexeditor.cpp [hunk 4]
```diff
@@ -457,6 +459,22 @@ void QgsVertexEditor::keyPressEvent( QKeyEvent *e )
...
+    if ( !mTableView->selectionModel()->hasSelection() )
+      return;
+    QString text;
+    QItemSelectionRange range = mTableView->selectionModel()->selection().first();
+    for ( int i = range.top(); i <= range.bottom(); ++i )
+    {
+      QStringList rowContents;
+      for ( int j = range.left(); j <= range.right(); ++j )
+        rowContents << mVertexModel->index( i, j ).data().toString();
+      text += rowContents.join( ',' );
```
Comment (uclaros) [inline src/app/vertextool/qgsvertexeditor.cpp:473]: A tab separator would be more appropriate here, as the comma will be confusing in locales that use it as a decimal separator.

**Review by uclaros — APPROVED** [review]

**Comment by SrNetoChan** [comment]
I would suggest the use of semi-colon(;) instead of the comma as field separator. If possible, the copied decimal values should respect the user's locale decimal separator.

**Comment by m-kuhn** [comment]
> I would suggest the use of semi-colon(;) instead of the comma as field separator. If possible, the copied decimal values should respect the user's locale decimal separator.

See https://github.com/qgis/QGIS/pull/46536#discussion_r772671651 this has been taken care of

**Comment by nicogodet** [comment]
Thanks @Djedouas !

Can this fix be backported to 3.22 at least ?
