### PR TITLE
Fix histogram bindings

### LINKED ISSUE #29700: Crash when calling QgsRasterHistogram.histogramVector
Author Name: **Anita Graser** (@anitagraser)
Original Redmine Issue: [21885](https://issues.qgis.org/issues/21885)
Affected QGIS version: 3.7(master)
Redmine category:rasters

---
## User Feedback

To reproduce, load a raster layer and run:

l = iface.activeLayer()
p = l.dataProvider()
p.initHistogram(QgsRasterHistogram(),1,100)
h=p.histogram(1)
h.histogramVector

## Report Details

*Crash ID*: 83fbcfe1e268fc8a14c5f21189006505dfb05fea

*Stack Trace*
```
PyObject_GenericGetAttrWithDict :
PyObject_GetAttr :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyImport_Import :
PyImport_Import :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_sip :
PyInit_Qsci :
QWidget::event :
QFrame::event :
QAbstractScrollArea::event :
PyInit_Qsci :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processKeyEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.6.1-Noosa
QGIS code revision: 2468226bc9
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

### PR DESCRIPTION
**Pull request by elpaso**
Hopefully fixes #29700

### CODE REVIEW

File: src/core/raster/qgsrasterinterface.h [hunk 1]
```diff
@@ -378,8 +378,8 @@ class CORE_EXPORT QgsRasterInterface
       maximum = PyFloat_AsDouble( a3 );
     }
 
-    QgsRasterHistogram h = sipCpp->histogram( a0, a1, minimum, maximum, *a4, a5, a6, a7 );
-    sipRes = &h;
+    QgsRasterHistogram *h = new QgsRasterHistogram( sipCpp->histogram( a0, a1, minimum, maximum, *a4, a5, a6, a7 ) );
```
Comment (nyalldawson) [inline src/core/raster/qgsrasterinterface.h]: Doesn't this need wrapping in "sipConvertFromType" ?

Comment (elpaso) [reply src/core/raster/qgsrasterinterface.h]: @nyalldawson please have a look to my last commit.

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
Is it worth adding a python test for this method? Is there an existing one? Gut feeling is that there's likely NO tests for this method, it predates the focus on stability.

**Comment by elpaso** [comment]
> Is it worth adding a python test for this method? Is there an existing one? Gut feeling is that there's likely NO tests for this method, it predates the focus on stability.

I'll see what I can do.
