### PR TITLE
Fix regression in rendering polygons with z dimensions

### LINKED ISSUE #49157: Qgis 3.26 geometry display error
### What is the bug or the crash?

When zooming in on geometries, the symbology of the geometries is not displayed correctly.
The same project opened with qgis 3.24 works perfectly.

### Steps to reproduce the issue

here the link of the geopackage
[https://drive.google.com/file/d/1Erw6wO81Zz74-FGleTk43ERr6v8vnigG/view?usp=sharing](url)

Qgis 3 24
Qgis 3 26

### Versions

Versione di QGIS
3.26.0-Buenos Aires
Revisione codice QGIS
0aece2818e
Versione Qt
5.15.3
Versione Python
3.9.5
Versione GDAL/OGR
3.5.0
Versione PROJ
9.0.1
Versione database del Registro EPSG
v10.064 (2022-05-19)
Versione GEOS
3.10.3-CAPI-1.16.1
Versione SQLite
3.38.1
Versione PDAL
2.3.0
Versione client PostgreSQL
unknown
Versione SpatiaLite
5.0.1
Versione QWT
6.1.6
Versione QScintilla2
2.13.1
Versione SO
Windows 10 Version 2009

Plugins Python attivi
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nyalldawson**
Fixes https://github.com/qgis/QGIS/issues/49157

### CODE REVIEW

File: tests/src/core/testqgsclipper.cpp [hunk 1]
```diff
@@ -73,9 +73,15 @@ void TestQgsClipper::basicWithZ()
...
-  QVector< double > y = {20.5, 30.2 };
-  QVector< double > z = {10.0, 20.0 };
+  QVector< double > x;
+  QVector< double > y;
+  QVector< double > z;
+  // check that clipping an empty polygon doesn't crash
+  QgsClipper::trimPolygon( x, y, z, clipRect );
+
+  x = { 10.4, 20.2 };
+  y = {20.5, 30.2 };
```
Comment (nirvn) [inline tests/src/core/testqgsclipper.cpp:83]:
```suggestion
  y = { 20.5, 30.2 };
```

File: tests/src/core/testqgsclipper.cpp [hunk 2]
```diff
@@ -73,9 +73,15 @@ void TestQgsClipper::basicWithZ()
...
+  z = {10.0, 20.0 };
```
Comment (nirvn) [inline tests/src/core/testqgsclipper.cpp:84]:
```suggestion
  z = { 10.0, 20.0 };
```

**Review by nirvn — APPROVED** [review]
