### PR TITLE
[gui] Fix cursor jump when editing row/column width of a cell in the table designer

### LINKED ISSUE #50257: print layout: cursor jumps when changing cell size of fixed table
### What is the bug or the crash?

In print layout when changing the cell size of a fixed table column/row in a fixed table the cursor "jumps" to the right after each single edit.
Example: when i want to change 71.55 into 62.55 i place the cursor behind the 7 > delete 7 and type 6 instead
(cursor jumps after the delete to the right and has to be placed in front of the 1 again to type 6. )
cell_size_jumps

### Steps to reproduce the issue

1. go to print layout
2. insert a fixed table
3. change row or column cell size
4. change for example 71.55 into 62.55 by placing the cursor behind the 7 > delete 7 and type 6 instead
(cursor jumps after the delete to the right and has to be placed in front of the 1 again to type 6. 

### Versions

3.26.2 and 3.22.10  (and older versions)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This PR gets rid of needless clearing and re-setting of value in our QgsSpinBox and QgsDoubleSpinBox when setting a custom clear value (setClearValue) or clear value mode (setClearValueMode).

The improvement fixes #50257 , whereas typing a value in the manual table designer's cell row height / column width spin boxes would have the cursor jump at the end of the line edit at every stroke.

### CODE REVIEW

**Comment by DelazJ** [comment]
backport to 3.28?

**Comment by DelazJ** [comment]
I actually was suggesting @nirvn to remove the label since 3.28 is EOL. Looks like @rouault removed it while I was writing and I didn't pay attention.
> backported for the final 3.28 release

We already have the final 3.28 release, don't we?

**Comment by nyalldawson** [comment]
@nirvn this is a valid test failure

**Comment by nirvn** [comment]
@nyalldawson , fixed.

File: src/gui/editorwidgets/qgsdoublespinbox.cpp [hunk 1]
```diff
@@ -142,6 +147,11 @@ void QgsDoubleSpinBox::setClearValue( double customValue, const QString &special
 
 void QgsDoubleSpinBox::setClearValueMode( QgsDoubleSpinBox::ClearValueMode mode, const QString &clearValueText )
 {
+  if ( mClearValueMode == mode && QAbstractSpinBox::specialValueText() == clearValueText )
```
Comment (nyalldawson) [inline src/gui/editorwidgets/qgsdoublespinbox.cpp:150]: does this also need to check mCustomClearValue != 0 ?

Comment (nirvn) [reply src/gui/editorwidgets/qgsdoublespinbox.cpp]: @nyalldawson , correct.

**Review by nyalldawson — APPROVED** [review]
