### PR TITLE
Use widget value when validating attrs in form

### LINKED ISSUE #46364: Message in form view is misleading/wrong
### What is the bug or the crash?

I have a table of attributes with a form with some fields that have the "not NULL" contraint, 8 are not enforced 1 is enforced.

When adding a new record from the form view in the table of attributes the following message pops up:

image

which is misleading/wrong because actually is just 1 field (not 9) that is blocking the form from being saved/submitted.

### Steps to reproduce the issue

See above.

### Versions

3.16.14 / 3.22.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Also, make sure that non enforced constraints
do not block commits and do not report as violated
constraints (Fix #46364).

Followup #46439 because the constraints were
not checked against the widget value but against
the attribute value.

### CODE REVIEW

File: src/gui/qgsattributeform.h [hunk 1]
```diff
@@ -443,6 +443,7 @@ class GUI_EXPORT QgsAttributeForm : public QWidget
     void updateLabels();
     bool currentFormValuesFeature( QgsFeature &feature );
     bool currentFormValidConstraints( QStringList &invalidFields, QStringList &descriptions );
+    bool currentFormValidHardConstraints( QStringList &invalidFields, QStringList &descriptions );
```
Comment (m-kuhn) [inline src/gui/qgsattributeform.h:446]:
```suggestion
    bool currentFormValidHardConstraints( QStringList &invalidFields, QStringList &descriptions ) const;
```

That could be const?

**Review by m-kuhn — COMMENTED** [review]
The `feature` that is passed into `validateAttribute` does not contain the current widget value if I understand this correctly.
If a constraint uses more than the value from a specific field (something like `"a" > "b"`) is this not affected by the same bug?

I.e. shouldn't we make sure that the feature passed into `validateAttribute` is up-to-date with form values instead of overriding one specific value?

Or am I missing some context here?

**Comment by elpaso** [comment]
> The `feature` that is passed into `validateAttribute` does not contain the current widget value if I understand this correctly. If a constraint uses more than the value from a specific field (something like `"a" > "b"`) is this not affected by the same bug?
> 
> I.e. shouldn't we make sure that the feature passed into `validateAttribute` is up-to-date with form values instead of overriding one specific value?
> 
> Or am I missing some context here?

The fact is that in case of empty selection the feature attribute contains `{}` while the widget value (after #46439 ) correctly returns invalid `QVariant()`, so we want to check the constraints against the widget value and not the feature's attribute.

**Comment by m-kuhn** [comment]
What does `mCurrentFormFeature` contain?
What is the meaning of "invalid" in this situation? I was under the impression it's `NULL` when reviewing, but remember now that the meaning of invalid can be "unchanged" in this context, or you might intend something even different.

**Comment by elpaso** [comment]
> What does `mCurrentFormFeature` contain? What is the meaning of "invalid" in this situation? I was under the impression it's `NULL` when reviewing, but remember now that the meaning of invalid can be "unchanged" in this context, or you might intend something even different.

This is a followup of #46439 that you review recently, the problem was that when `AllowMulti` was set and  `AllowNull` was not set and the widget returned `{}` and the NOT NULL constraint was passing, now the widget checks this case and returns an invalid `QVariant()` instead of an empty array `{}`. But #46439 did not take into account the form validation when editing an existing feature after setting the constraint: in that case the attribute value is `{}` and it was checked instead of the widget value.

**Comment by m-kuhn** [comment]
If we have a form with two attribute widgets for `count` (int) and `categories` (list value relation).

We open the form with `count = 2` and `categories = {}`

We have a constraint `count > 0 AND categories IS NULL` on both fields. It will once validate and once not?

PS: I assume `QVariant()` corresponds to `NULL` in our discussion here

**Comment by elpaso** [comment]
> If we have a form with two attribute widgets for `count` (int) and `categories` (list value relation).
> 
> We open the form with `count = 2` and `categories = {}`
> 
> We have a constraint `count > 0 AND categories IS NULL` on both fields. It will once validate and once not?
> 
> PS: I assume `QVariant()` corresponds to `NULL` in our discussion here

I think it will (wrongly) validate in both cases, you are talking about constraints based on expressions here while what I have fixed with #46439  was the Not NULL checkbox constraint, yours seems a related but different issue to me, I can have a look btw.

**Comment by elpaso** [comment]
> If we have a form with two attribute widgets for `count` (int) and `categories` (list value relation).
> 
> We open the form with `count = 2` and `categories = {}`
> 
> We have a constraint `count > 0 AND categories IS NULL` on both fields. It will once validate and once not?
> 
> PS: I assume `QVariant()` corresponds to `NULL` in our discussion here

@m-kuhn I think I understand what you mean now, checking...

**Comment by elpaso** [comment]
@m-kuhn I think I've found the right solution: returning a NULL list instead of an invalid QVariant makes the form feature correct and there is no need to pass the value anymore (I removed the new function), you were right about checking why the form feature was not correctly populated from the widget values.

**Comment by elpaso** [comment]
Note that the backport needs to be merged after https://github.com/qgis/QGIS/pull/46440

File: src/gui/qgsattributeform.cpp [hunk 2]
```diff
@@ -1258,6 +1258,27 @@ bool QgsAttributeForm::currentFormValidConstraints( QStringList &invalidFields,
   return valid;
 }
 
+bool QgsAttributeForm::currentFormValidHardConstraints( QStringList &invalidFields, QStringList &descriptions ) const
+{
+  bool valid( true );
```
Comment (m-kuhn) [inline src/gui/qgsattributeform.cpp:1263]: We no longer like good old `=`?

**Review by m-kuhn — APPROVED** [review]
Looks good to me.

We really need to get some order into the semantics of invalid and null `QVariant`, probably consistently using `QVariant()` as null and adding some special `QVariant` type for unchanged widget values and also for provider default values but that's a different story.

File: src/gui/qgsattributeform.cpp (hunk 2 above)
Comment (elpaso) [reply src/gui/qgsattributeform.cpp]: Not my code: it's a copy and paste from the pre-existing `bool QgsAttributeForm::currentFormValidConstraints` I would have used brace initializers.
