### PR TITLE
[Oracle] Fix crashes with shared connection among threads

### LINKED ISSUE #36512: Re-Refreshing Oracle connection on browser causes crash
**Describe the bug**

In the browser panel, if one tries to refresh an Oracle connection while it is still being refreshed causes QGIS to crash.

**How to Reproduce**
- Open the browser panel
- Right click on an Oracle connection and hit Refresh
- While the generated task is still running, repeat previous step
- Crash

**QGIS and OS versions**
07e38a2196 on Debian testing, Oracle instant client 19.6

### PR DESCRIPTION
**Pull request by troopa81**
This PR does 2 things:
- regarding db connection API, don't destroy connection while we need it (quite the same as #50194 for mssql)
- Do not share connections between threads

This could potentially fix #36512, #47669, #47225, and #52178

**Funded by Ifremer**

### CODE REVIEW

File: src/providers/oracle/qgsoracleconn.cpp [hunk 1]
```diff
@@ -37,7 +37,9 @@ QMap<QString, QDateTime> QgsOracleConn::sBrokenConnections;
 QgsOracleConn *QgsOracleConn::connectDb( const QgsDataSourceUri &uri, bool transaction )
 {
   const QString conninfo = toPoolName( uri );
-  if ( !transaction )
+  const bool shared = !transaction && QApplication::instance()->thread() == QThread::currentThread();
```
Comment (nyalldawson) [inline src/providers/oracle/qgsoracleconn.cpp:40]: The sql server provider uses a different approach here -- see https://github.com/qgis/QGIS/blob/master/src/providers/mssql/qgsmssqldatabase.cpp#L51 . This allows use of shared connections from the same non-main thread too. Could that approach be utilised here?

Comment (troopa81) [reply src/providers/oracle/qgsoracleconn.cpp]: Yes, but not by patching connection name with thread id because it would not work nicely with QgsConnectionPool in oracle (it's not used mssql). 

But I made the [modifications](https://github.com/qgis/QGIS/pull/53201/commits/80b08ddbe67114e22092977748a7409777c66950) to make it happen

**Review by nyalldawson — APPROVED** [review]
