### PR TITLE
Save original layout item picture mode

### LINKED ISSUE #37804: Layout picture can not change SVG image to Raster image
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

QGIS 3.14 
windows and ubuntu 
Layout 

put picture and set Rater image.
after edit expression picture change SVG image.
when expression is active , picture mode can not change 'Raster image'.

image

expression is active

image

### LINKED ISSUE #38031: Print Layout Picture Box reverting to SVG
Whenever I load a print layout in to QGIS my company logo picture box displays a big red X and the control has turned back to SVG image when had been saved as Raster Image:

image

No matter how many times I revert the picture control back to raster image and save the template - every time it is loaded back from the layout manager the picture has reverted back to SVG.

I should mention that I'm using the latest release 3,14.1

### LINKED ISSUE #47981: Variable raster image source in composer not working
### What is the bug or the crash?

Creating an atlas output with an variable raster image per output file does not work.
The Item Properties of the image switches automatically from "Raster image" to "SVG image" when selecting an attribute field from the file as the image path and it cannot be changed back.

### Steps to reproduce the issue

Prerequisites:
A point layer with features for creating an atlas which contains an attribute field with a file path which points to an image related to this feature. (Actually it doesn't matter at this point, if this is a valid path to an image, since QGIS does not check if the images exists at this stage of the workflow)

Steps to reproduce:

1. Create a new print layout
2. Select Atlas > Atlas Settings
3. In the Atlas Settings select your point layer as coverage layer
4. Add a picture element to the layout
5. Select Raster Image for this element
6. For the source of the image choose the Attribute Field with the image path
7. Now the selection automatically switches from Raster image to SVG image and when trying to export the atlas files the error message "Picture source is missing or corrupt" appears and it is impossible to export them

### Versions

Tested with 3.22.1, 3.24.0 and 3.24.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### LINKED ISSUE #49165: Layout - expression for raster image keeps setting radiobutton to SVG image
### What is the bug or the crash?

When creating an expression for dynamically loading raster images in a QGIS from a local folder, on clicking OK, the radiobutton jumps to .SVG image and the raster image will not load.

### Steps to reproduce the issue

Insert placeholder for raster image.
Data defined override expression: concat(@project_folder, '\\H_ALIGNMENT\\' ,"plotboxID", '_MBES.png').
 Expression is valid 
Press OK
Radiobutton Raster image has now jumped to SVG image

### Versions

QGIS version
3.24.0-Tisler
QGIS code revision
6b44a42058
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
BezierEditing
version 1.3.2
DeepLearningTools
0.2.0
league_tools
0.1
openlayers_plugin
2.0.0
ParallelLineConstruction
0.2
plugin_reloader
0.9.1
pointsamplingtool
0.5.3
qchainage
3.0.1
slyr_community
4.0.1
SplitPolygonShowingAreas
0.13
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by troopa81**
Supersedes #49615

This PR propose to add an original mode different than the one computed by QgsLayoutItemPicture (which could be equal to FormatUnknown if the given picture is missing/invalid), to use it in the UI and save it in the project

I set the since doxy tag to 3.22 because I would like to backport it. 

Fixes https://github.com/qgis/QGIS/issues/49165 (stale and close)
Fixes https://github.com/qgis/QGIS/issues/47981
Fixes https://github.com/qgis/QGIS/issues/38031
Fixes https://github.com/qgis/QGIS/issues/37804

cc @nicogodet

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]
Good approach 👍

**Comment by nicogodet** [comment]
Sweeeeettttt !
Did a quick test and it seems fine

File: src/core/layout/qgslayoutitempicture.h [hunk 1]
```diff
@@ -229,11 +229,20 @@ class CORE_EXPORT QgsLayoutItemPicture: public QgsLayoutItem
...
+     * picture format is unknown
+     * \see setMode() originalMode()
      */
     Format mode() const { return mMode; }
 
+    /**
+     * Returns the original set picture mode (image format).
+     * It could differ from mode() if given picture format is unknown
+     * \see setMode() mode()
+     * \since 3.22
```
Comment (nicogodet) [inline src/core/layout/qgslayoutitempicture.h:242]: Shouldn't it be 3.28 here ?
And change since in backport PR ?

Comment (troopa81) [reply src/core/layout/qgslayoutitempicture.h:242]: Not completely sure, but I would say that the since need to be consistent (the same) between version to be sure when the API has changed. And since I plan to backport, the API will have changed in 3.22.
