### PR TITLE
exitQgis(): do not run GDAL termination if there are still opened datasets

### LINKED ISSUE #58724: qgis/gdal garbage collection causes segfault
### What is the bug or the crash?

When opening a dataset with gdal, and not explicitly dereferencing it, a segmentation fault will happen when QGIS terminates. 

I had an email correspondence with @rouault  where he explained the following:

> that's a bad interaction between QGIS, GDAL and Python "garbage collection".
> 
> The issue is that in this situation QGIS runs its termination before the
> "dataset" object is released, and QGIS termination calls the GDAL
> termination logic, the GDAL termination logic will force closed still
> opened datasets, so when Python garbage collects dataset and run
> GDALClose() on it, this results in a double free attempt and a crash.
> 
> A workaround is to explicitly drop the reference to the GDAL dataset
> with "del dataset" or "dataset = None" before the Python function exits.

I asked if this was to be considered a bug and he responded:

> Maybe when using startApp() from Python, QGIS should set some flag to prevent the 2 below lines to be run:
> https://github.com/qgis/QGIS/blob/b0b3736085fa5c48318786688d2774b25911636c/src/core/qgsapplication.cpp#L1638-L1639
> 
> Running GDAL termination is not strictly needed. It just nicer when running under memory analyzers that could otherwise point to unreleased memory, but in a Python testing use case, we probably don't care about that.
> 
> Maybe there's a better solution, but can't think of it right now.

### Steps to reproduce the issue

Create a Python script with the following code, and run as a stand alone. 

```
#!/usr/bin/env python3
# segfault.py
from osgeo import gdal
from osgeo.gdalconst import GA_ReadOnly
from qgis.testing import start_app

start_app()
dataset = gdal.Open('/home/velle/a/QGIS/tests/testdata/raster/rgb_with_mask.tif', GA_ReadOnly)
print('the end')
```
This gives:

    the end
    Segmentation fault

If both of these lines are left, it gives segfault: 
 - start_app()
 - gdal.Open(...)

If any of them are commented out, the segfault disappears. 

I tried with a few different tif, and the result is the same. 

If changing the order of the two lines, some times it results in segfault, and sometimes it results in the following fatal error:

    the end
    double free or corruption (!prev)
    Aborted

The print line is always executed before the fatal error occurs. 

### Versions

qgis master (Sep 13 2024)
gdal 3.4.1

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rouault**
otherwise if they are still reference in Python code this can cause to double free/crashes issues

Fixes #58724

### CODE REVIEW

**Comment by ViperMiniQ** [comment]
@DelazJ, I think this could solve the Documentation CI failing.

File: src/core/qgsapplication.cpp [hunk 1]
```diff
@@ -1657,9 +1655,17 @@ void QgsApplication::exitQgis()
 
   QgsStyle::cleanDefaultStyle();
 
-  // tear-down GDAL/OGR
-  OGRCleanupAll();
-  GDALDestroyDriverManager();
+  // tear-down GDAL/OGR, but only if there are no remaining opened
+  // datasets (cf https://github.com/qgis/QGIS/issues/58724)
+  // Outputting to stdin is obviously absurd, but intended here, since
+  // we are just interested in the count of still openeded dataset.
```
Comment (nyalldawson) [inline src/core/qgsapplication.cpp]:
```suggestion
  // we are just interested in the count of still open datasets
```

File: src/core/qgsapplication.cpp [hunk 2]
```diff
@@ -1657,9 +1655,17 @@ void QgsApplication::exitQgis()
...
+  if ( GDALDumpOpenDatasets( stdin ) == 0 )
```
Comment (nyalldawson) [inline src/core/qgsapplication.cpp:1662]: (not directly related, but the gdal docs don't mention anywhere what the return value from this function indicates)

**Review by nyalldawson — APPROVED** [review]
