### PR TITLE
Restore default metadata from DB

### LINKED ISSUE #55726: Metadata: "restore default" always returns "Metadata not found in database" when some metadata is actually stored in the "default" location
### What is the bug or the crash?

I hope I didn't got wrong the docs here 

https://docs.qgis.org/3.28/en/docs/user_manual/introduction/general_tools.html#metadata

but if "save as default" means saving the metadata to the "default" location depending on the datasource, then I would expect "restore default" to load the same metadata from the same datasource. 

Using a PGSQL datasource "save as default"  works as expected, so loading a specific layer in a new project will automatically load also the metadata, but if for some reason the metadata are changed in the layer properties, then clicking "restore default" to discard such changes, will always return "Metadata not found in database".

### Steps to reproduce the issue

Add a postgresql layer from a connection with "Allow saving/loading QGIS layer metadata in the database" enabled

Open its properties and fill some meatadata

Save metadata using "save as default"

Change/edit some of the metadata

Try discard such changes by loading previously saved metadata using "restore default", result is always "Metadata not found in database".

Metadata is actually stored in the DB because loading the layer in the same or another project will retrieve correctly the previously saved metadata.

### Versions

Tested on 3.28, 3.34 and master

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.13-Firenze | QGIS code revision | 3b4db4f561
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.8.1
PROJ version | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.41.1
PDAL version | 2.6.0
PostgreSQL client version | unknown
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.4
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
cigeoe_merge_lines | 1
export_to_sql_server | 0.4
getools | 1.0.0
layout_loader | 1.1
lizmap | 4.1.1
merge_selected_features | 0.1
multiqml | 0.6.0
qfieldsync | v4.6.3
quick_map_services | 0.19.34
raster_tracer | 0.3.3
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.28.13-Firenze
QGIS code revision
[3b4db4f561](https://github.com/qgis/QGIS/commit/3b4db4f561)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.8.1
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
cigeoe_merge_lines
1
export_to_sql_server
0.4
getools
1.0.0
layout_loader
1.1
lizmap
4.1.1
merge_selected_features
0.1
multiqml
0.6.0
qfieldsync
v4.6.3
quick_map_services
0.19.34
raster_tracer
0.3.3
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Fix #55726

### CODE REVIEW

File: src/core/qgsmaplayer.cpp [hunk 1]
```diff
@@ -1301,6 +1301,28 @@ QString QgsMapLayer::loadDefaultMetadata( bool &resultFlag )
...
+        if ( resultFlag )
+        {
+          mMetadata = metadata;
+          return tr( "Successfully loaded default layer metadata" );
+        }
+      }
+      catch ( QgsNotSupportedException &e )
+      {
+        resultFlag = false;
+        return e.what();
```
Comment (nyalldawson) [inline src/core/qgsmaplayer.cpp:1321]: shouldn't this cause a fallback to  loadNamedMetadata( metadataUri(), resultFlag ); ?

File: src/core/providers/ogr/qgsogrprovidermetadata.cpp [hunk 2]
```diff
@@ -654,6 +655,117 @@ bool QgsOgrProviderMetadata::saveLayerMetadata( const QString &uri, const QgsLay
...
+  if ( !path.isEmpty() && QFileInfo::exists( path ) )
+  {
+    const QFileInfo fi( path );
+    // if it is a gpkg, try reading metadata
+    if ( fi.suffix().compare( QLatin1String( "gpkg" ), Qt::CaseInsensitive ) == 0 )
+    {
+      const QString layerName = parts.value( QStringLiteral( "layerName" ) ).toString();
+      QgsOgrLayerUniquePtr userLayer;
+      userLayer = QgsOgrProviderUtils::getLayer( path, true, QStringList(), layerName, errorMessage, true );
+      if ( userLayer )
```
Comment (nyalldawson) [inline src/core/providers/ogr/qgsogrprovidermetadata.cpp:675]: Is there a test covering this already?

Comment (elpaso) [reply src/core/providers/ogr/qgsogrprovidermetadata.cpp:675]: Yes, I have added the test to the base test class in order to test all the implementations: https://github.com/qgis/QGIS/pull/55924/files#diff-3871ec4c64f2c18a6dbd113550e1c7250c488f3d939238053904714b544cfe77R144

File: src/core/qgsmaplayer.cpp (hunk 1 above)
Comment (elpaso) [reply src/core/qgsmaplayer.cpp:1321]: I don't think so: if the provider does not support loading metadata we take the other branch which calls loadNamedMetadata on line 1326, this branch is taken by the multi-format providers (OGR) which in general advertises support for loading metadata but it may raise in case it doesn't for a particular format.

Comment (elpaso) [reply src/core/qgsmaplayer.cpp:1321]: @nyalldawson I am having second thoughts: you are right and it need to fallback. I'll change it.

**Comment by nyalldawson** [comment]
@elpaso this has broken some geopackage functionality badly -- eg when saving processing outputs to a new geopackage I now get errors like:

ERROR 1: In ExecuteSQL(): sqlite3_prepare_v2(SELECT metadata FROM gpkg_metadata LEFT JOIN gpkg_metadata_reference ON (gpkg_metadata_reference.table_name = 'output' AND gpkg_metadata.id = gpkg_metadata_reference.md_file_id) WHERE md_standard_uri = 'http://mrcc.com/qgis.dtd' and reference_scope = 'table'):
  no such table: gpkg_metadata

Can we revert for today's release please?

**Comment by nyalldawson** [comment]
Actually I'll revert now, it's too close to release to test a fix properly
