### PR TITLE
Fix inconcequent use of DPI at generating the WMS legend

### LINKED ISSUE #50366: WMS legend symbol missing for "Meters at Scale" symbology and projected CRS
### What is the bug or the crash?

The legend symbol of a vector layer having a meters at scale symbology and rendered as WMS via QGIS Server is missing if using a projected CRS. 

A workaround has been found when setting Project Properties > QGIS Server > WMS Capabilities > Default scale for legend as > 1, like 10:1. In that case, the legend symbol of the WMS layer is shown. 

Is this supposed to be normal behaviour? Standard scales that can be chosen from the dropdown do not include scales >1:1, so I guess it's not normal.

For WGS84, it's "Default map units per mm in legend" that can be defined. Is it possible that even when it's saying "Default scale for legend" for other CRS, the value entered is still translated as _map units per mm_? 

Screenshot 2022-09-27 at 10 59 12

### Steps to reproduce the issue

1. Open a new QGIS project with CRS = EPSG:2056
2. Add a vector layer (e.g. lines)
3. Draw a feature
4. Define Symbology > Stroke width = 5, Meters at Scale
5. Go to Project properties > QGIS Server > WMS capabilities, set Default scale for legend to 1:1000 or something else 1:>1
6. Run a local QGIS server (e.g. with docker)  
7. Open another QGIS project and add WMS layer from your project on the local server, add the line layer 
8. See that there is no legend symbol

Redo the same from point 5 on, setting the Default scale for legend to something >1:1

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.4-Białowieża | QGIS code revision | 3f4577ce6e
-- | -- | -- | --
Qt version | 5.14.2
Python version | 3.8.7
GDAL/OGR version | 3.2.1
PROJ version | 6.3.2
EPSG Registry database version | v9.8.6 (2020-01-22)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.31.1
PostgreSQL client version | 12.3
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.4
OS version | macOS 12.6
  |   |   |  
Active Python plugins
numericalDigitize | 0.4.7
firstaid | 2.1.5
lrs | 1.2.2
precipitation_plugin | dev
DataPlotly | master
quick_map_services | 0.19.29
vertex_compare | 0.0.1
linking_relation_editor | v1.0.0
QgisModelBaker | v7.1.7
HCMGIS | 22.9.9
qfieldsync | v4.1.1
swissgeodownloader | 2.0
document_management_system | 0.3.1
PointConnector | 2.0
qgis_resource_sharing | 0.16.0
plugin_reloader | 0.9.1
swiss_locator | 2.0.0
coordinate_capture | 0.2
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.5

</body></html>QGIS version
3.22.4-Białowieża
QGIS code revision
[3f4577ce6e](https://github.com/qgis/QGIS/commit/3f4577ce6e)
Qt version
5.14.2
Python version
3.8.7
GDAL/OGR version
3.2.1
PROJ version
6.3.2
EPSG Registry database version
v9.8.6 (2020-01-22)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.31.1
PostgreSQL client version
12.3
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.4
OS version
macOS 12.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by signedav**
- Consider DPI of QgsWmsRenderContext what is the OGC default (0.28 mm per pixel) or the passed WMS parameter - this is done by creating the QgsRenderContext by the mapSettings (with BBOX) or applying the dotsPerMm to the scaleFactor.
- Additionally the image size needs to be calculated according to the QgsRenderContext now, what means it needs to be generated before.

- Distance area when using defaultMapUnitsPerMm to consider the correct CRS and care about meter based crs. This fixes #50366

Replaces #51772

### CODE REVIEW

File: src/server/services/wms/qgswmsrenderer.cpp [hunk 1]
```diff
@@ -186,6 +208,18 @@ namespace QgsWms
     QgsLegendSettings settings = legendSettings();
     QgsLayerTreeModelLegendNode::ItemContext ctx;
     ctx.painter = painter.get();
+
+    // create context
+    QgsRenderContext context = QgsRenderContext::fromQPainter( painter.get() );
```
Comment (m-kuhn) [inline src/server/services/wms/qgswmsrenderer.cpp:213]: This block is identical to the one above?
Can it be deduplicated?

Comment (signedav) [reply src/server/services/wms/qgswmsrenderer.cpp:213]: I thought about that. Would you make a new method just for that? I decided against it, but would be fine for me.

Comment (m-kuhn) [reply src/server/services/wms/qgswmsrenderer.cpp:213]: There's a certain risk of forgetting upgrades in the future. I would.

**Comment by signedav** [comment]
I need to replace a bunch of control_images now. What is the appropriated way with `variants` and `masks`?

**Comment by nyalldawson** [comment]
> need to replace a bunch of control_images now

If they are changes that are permanent and not platform specific, just replace the existing reference images directly and don't add variants or masks.

I don't know if you've capacity for it, but all the server legend tests are broken in that they don't use the correct standard qgis test font and use tiny font sizes. They are really fragile as a result. If you're going to replace all the reference images and can find the time to do so, also changing the font to the standard test font in bold at least size 12 point would be a massive improvement.

**Comment by signedav** [comment]
You mean by adding those parameters LAYERFONTBOLD, LAYERFONTSIZE, LAYERFONTFAMILY (and same ITEM) to the request of every test case? @nyalldawson?

Yes. I can do that.

File: src/server/services/wms/qgswmsrenderer.h [hunk 2]
```diff
@@ -195,6 +195,12 @@ namespace QgsWms
        */
       void configureMapSettings( const QPaintDevice *paintDevice, QgsMapSettings &mapSettings, bool mandatoryCrsParam = true );
 
+      /**
+       * Configures QgsRenderContext according to the WMS parameters and default settings. Used, for example, when no mapSettings are available.
+       * \param context render context keeping info about the scale
+       */
+      void configureDefaultRenderContext( QgsRenderContext &context );
```
Comment (m-kuhn) [inline src/server/services/wms/qgswmsrenderer.h:202]: Could this be changed as follows, I think it would be more intuitive to use?

```suggestion
      QgsRenderContext configureDefaultRenderContext( QPainter *painter );
```

**Review by m-kuhn — APPROVED** [review]
One minor change request left

File: src/server/services/wms/qgswmsrenderer.h (hunk 2 above)
Comment (signedav) [reply src/server/services/wms/qgswmsrenderer.h:202]: Why having the painter here? Would call `QgsRenderContext::fromQPainter` in this function? On one of the use cases the painter would be null.

**Comment by signedav** [comment]
This can be merged right? And backported to 3.30..?

**Comment by m-kuhn** [comment]
Yes, I have also tagged it for backport to LTR (remove label if you think it's a bad idea)
