### PR TITLE
[BUG] Fix QgsColorRampShaderWidget

### LINKED ISSUE #33882: Mesh contours color ramp sometimes not populated
1. load https://github.com/lutraconsulting/MDAL/blob/master/tests/data/ugrid/D-Flow1.2/bw_11_zonder_riviergrid_met_1dwtg_clm.nc as mesh layer. Nothing displays because Bed Evelation has all NaNs (no Z values in raw data)
2. click on "flow element center bedlevel (bl)" dataset. .. still nothing (BUG)
3. click on contrours tab, looks like color ramp was not populated (this is populated for other files). when you manually change min or max, the color ramp is created and data is drawn on canvas

### LINKED ISSUE #34962: [Mesh] Problem with styling when changing quantity in mesh tree
QGIS should remember the style when switching between quantities.

### PR DESCRIPTION
**Pull request by vcloarec**
This PR fixes issues related to the `QgsColorRampShaderWidget`:
fix #33882  
fix #34962

It also fixes the 'inf' issue with discrete interpolation : the color ramp tree was sometime populated with inf values.

Raster and mesh layer are concerned by this PR

### CODE REVIEW

**Comment by saberraz** [comment]
Tested the PR and now it works as expected :ok_hand:

File: src/gui/raster/qgscolorrampshaderwidget.cpp [hunk 1]
```diff
@@ -388,7 +388,7 @@ void QgsColorRampShaderWidget::applyColorRamp()
 
       double value = currentItem->text( ValueColumn ).toDouble();
       double position = ( value - mMin ) / ( mMax - mMin );
-      currentItem->setData( ColorColumn, Qt::EditRole, ramp->color( position ) );
+      whileBlocking( static_cast<QgsTreeWidgetItemObject *>( currentItem ) )->setData( ColorColumn, Qt::EditRole, ramp->color( position ) );
```
Comment (PeterPetrik) [inline src/gui/raster/qgscolorrampshaderwidget.cpp]: is `static_cast<QgsTreeWidgetItemObject *>` really needed here?

File: src/gui/raster/qgscolorrampshaderwidget.cpp [hunk 2]
```diff
@@ -645,9 +644,20 @@ void QgsColorRampShaderWidget::mColormapTreeWidget_itemEdited( QTreeWidgetItem *
 
 void QgsColorRampShaderWidget::setFromShader( const QgsColorRampShader &colorRampShader )
 {
+  populateColormapTreeWidget( colorRampShader.colorRampItemList() );
+
+  // Those objects are connected to classify() the color ramp shader if they change, or call widget change
+  // need to block them to avoid to classify and to alter the color ramp, or to call duplicate widget change
+  whileBlocking( mClipCheckBox )->setChecked( colorRampShader.clip() );
+  whileBlocking( mColorInterpolationComboBox )->setCurrentIndex( mColorInterpolationComboBox->findData( colorRampShader.colorRampType() ) );
+  mColorInterpolationComboBox_currentIndexChanged( mColorInterpolationComboBox->currentIndex() );
```
Comment (PeterPetrik) [inline src/gui/raster/qgscolorrampshaderwidget.cpp]: why you block  the signal currentIndexChanged on line above and immediately emits it? isn't is the same as removal of `whileBlocking` line above?

File: src/gui/raster/qgscolorrampshaderwidget.cpp [hunk 3]
```diff
@@ -645,9 +644,20 @@ void QgsColorRampShaderWidget::mColormapTreeWidget_itemEdited( QTreeWidgetItem *
...
+  whileBlocking( mClassificationModeComboBox )->setCurrentIndex( mClassificationModeComboBox->findData( colorRampShader.classificationMode() ) );
+  mClassificationModeComboBox_currentIndexChanged( mClassificationModeComboBox->currentIndex() );
```
Comment (PeterPetrik) [inline src/gui/raster/qgscolorrampshaderwidget.cpp]: why you block  the signal currentIndexChanged on line above and immediately emits it? isn't is the same as removal of `whileBlocking` line above?

File: src/gui/raster/qgscolorrampshaderwidget.cpp (hunk 1 above)
Comment (vcloarec) [reply src/gui/raster/qgscolorrampshaderwidget.cpp]: yes, because `currentItem` is a `QTreeWidgetItem` that is not a `QObject` and do not provide signal/slots. Derived class `QgsTreeWidgetItemObject` is derived too from `QObject`.

File: src/gui/raster/qgscolorrampshaderwidget.cpp (hunk 3 above)
Comment (vcloarec) [reply src/gui/raster/qgscolorrampshaderwidget.cpp]: Blocking to avoid to call the slots `QgsColorRampShaderWidget::classify` that is also connected.

File: src/gui/raster/qgscolorrampshaderwidget.cpp (hunk 2 above)
Comment (vcloarec) [reply src/gui/raster/qgscolorrampshaderwidget.cpp]: Blocking to avoid to call the slots `QgsColorRampShaderWidget::classify` that is also connected.

**Review by PeterPetrik — APPROVED** [review]
