### PR TITLE
main annotation layer should be used as a valid option even if type hint is set to UnknownType (fix #49010)

### LINKED ISSUE #49010: Export Layer(s) Information processing tool suggests unsupported Annotations layer as input
### What is the bug or the crash?

The Export Layer(s) Information processing tool lists the Annotations layer(s?) as potential input for itself.
If one tries to run it on an Annotation layer, it will fail though.

### Steps to reproduce the issue

1. Have a project open
2. Open the Export Layer(s) Information processing tool
3. Click the [...] button to select Input layer(s)
4. Choose the Annotations layer
5. Click run

You get an "Unable to execute algorithm" error dialog with the message "Incorrect parameter value for LAYERS".

image

The tool should not list the Annotations layer(s) as potential input for itself I guess :)

### Versions

master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alexbruy**
## Description

If Processing algorithm uses multiple layers parameter with `Qgis::ProcessingSourceType::MapLayer` type, annotation layers are should be considered as a valid choice. However, this will fail with the main annotation layer which exists in all projects by default. 

The `mapLayerFromString()` method will return `true` only if type hint is explicitly set to `Annotation`. In case of multiple layers input we check parameter value using the `UnknownType` type hint and main annotation layer won't be considered as a valid parameter value.

Fixes #49010.

### CODE REVIEW

File: src/core/processing/qgsprocessingutils.cpp [hunk 1]
```diff
@@ -516,7 +516,7 @@ QgsMapLayer *QgsProcessingUtils::mapLayerFromString( const QString &string, QgsP
     return nullptr;
 
   // prefer project layers
-  if ( context.project() && typeHint == LayerHint::Annotation && string.compare( QLatin1String( "main" ), Qt::CaseInsensitive ) == 0 )
+  if ( context.project() && ( typeHint == LayerHint::Annotation || typeHint == LayerHint::UnknownType ) && string.compare( QLatin1String( "main" ), Qt::CaseInsensitive ) == 0 )
```
Comment (nyalldawson) [inline src/core/processing/qgsprocessingutils.cpp:519]: Wouldn't this break things if the project eg contains a vector layer called "main"?

Comment (alexbruy) [reply src/core/processing/qgsprocessingutils.cpp:519]: Yes, it will break in that case and not only with vector layer but also with other layer types. We probably need to find another way to check validity of main annotation layer here.

Comment (nyalldawson) [reply src/core/processing/qgsprocessingutils.cpp:519]: Ok -- how about splitting this logic then, and leaving the condition where the typeHint is set where it is (ie it gets first preference), and then adding the new logic where typeHint isn't set to just before the "if ( !allowLoadingNewLayers )" check?

That way the named project layer will still get preference when typeHint isn't set.

File: tests/src/analysis/testqgsprocessing.cpp [hunk 2]
```diff
@@ -11474,14 +11474,14 @@ void TestQgsProcessing::parameterAnnotationLayer()
   QCOMPARE( def->valueAsPythonString( QVariant::fromValue( QgsProperty::fromExpression( "\"a\"=1" ) ), context ), QStringLiteral( "QgsProperty.fromExpression('\"a\"=1')" ) );
 
   QCOMPARE( def->valueAsJsonObject( QVariant(), context ), QVariant() );
-  QCOMPARE( def->valueAsJsonObject( QStringLiteral( "main" ), context ), QVariant( QStringLiteral( "main" ) ) );
+  QCOMPARE( def->valueAsJsonObject( QStringLiteral( "main" ), context ), QVariant( context.project()->mainAnnotationLayer()->id() ) );
```
Comment (nyalldawson) [inline tests/src/analysis/testqgsprocessing.cpp:11477]: I think this should still return "main", so that the json is compatible across different projects. Is that possible to do?

Comment (alexbruy) [reply tests/src/analysis/testqgsprocessing.cpp]: I have changed `QgsProcessingUtils::layerToStringIdentifier()` to check for main annotation layer. Hope this is acceptable approach.

File: src/core/processing/qgsprocessingutils.cpp [hunk 3]
```diff
@@ -761,6 +766,12 @@ QString QgsProcessingUtils::layerToStringIdentifier( const QgsMapLayer *layer )
 
     return QStringLiteral( "%1://%2" ).arg( provider, source );
   }
+
+  if ( layer->dataProvider()->name() == QLatin1String( "annotation" ) && layerName.compare( QLatin1String( "main" ), Qt::CaseInsensitive ) == 0 )
```
Comment (nyalldawson) [inline src/core/processing/qgsprocessingutils.cpp:770]: This could potentially crash on some broken layers (dataProvider() will be nullptr):

```suggestion
  if ( layer->type() == Qgis::LayerType::Annotation && layerName.compare( QLatin1String( "main" ), Qt::CaseInsensitive ) == 0 )
```

**Review by nyalldawson — APPROVED** [review]

**Comment by kannes** [comment]
Thank you @alexbruy !
