### PR TITLE
[pyqgis] fix calling QgsGeometry.splitGeometry with QgsPoint or QgsPointXY

### LINKED ISSUE #37821: Cannot run the non deprecated QgsGeometry.splitGeometry method from python
**Describe the bug**
`QgsGeometry.splitGeometry` has two variants, one accepting iterable with  `QgsPointXY`s (deprecated) and one accepting iterable with `QgsPoint`s.
While calling `QgsGeometry().splitGeometry()` the returning error shows that there are two overloaded methods, when passing an iterable with `QgsPoints` we get an `TypeError: index 0 has type 'QgsPoint' but 'QgsPointXY' is expected`

**How to Reproduce**
On a python console run `QgsGeometry().splitGeometry([QgsPoint()],False)`

or

run the sample code from the docs:
```
geometry = QgsGeometry.fromWkt('CompoundCurveZ ((2749546.2003820720128715 1262904.45356595050543547 100, 2749557.82053794478997588 1262920.05570670193992555 200))')
split_line = [QgsPoint(2749544.19, 1262914.79), QgsPoint(2749557.64, 1262897.30)]
result, new_geometries, point_xy = geometry.splitGeometry(split_line, False)
```

**QGIS and OS versions**
master on Debian testing

### PR DESCRIPTION
**Pull request by 3nids**
fix #37821

### CODE REVIEW

File: src/core/geometry/qgsgeometry.h [hunk 1]
```diff
@@ -1015,7 +1015,107 @@ class CORE_EXPORT QgsGeometry
...
+        if ( sipCanConvertToType( p0, sipType_QgsPointXY, SIP_NOT_NONE ) &&
+             sipCanConvertToType( a0, sipType_QVector_0100QgsPointXY, SIP_NOT_NONE ) )
+        {
+          QVector<QgsGeometry> newGeometries;
+          QVector<QgsPointXY> topologyTestPoints;
+
+          QVector<QgsPointXY> *splitLine = reinterpret_cast<QVector<QgsPointXY> *>( sipConvertToType( a0, sipType_QVector_0100QgsPointXY, 0, SIP_NOT_NONE, &state, &sipIsErr ) );
+          if ( sipIsErr )
+          {
+            sipReleaseType( splitLine, sipType_QVector_0100QgsPointXY, state );
```
Comment (nyalldawson) [inline src/core/geometry/qgsgeometry.h:1065]: Will `sipRes` need freeing in these error paths too? Might be safer to defer the call to PyTuple_New until we've checked all the possible errors

**Comment by nyalldawson** [comment]
Nice fix @3nids, very elegant!

**Comment by 3nids** [comment]
thanks for the review! I've adapted the code.

**Review by nyalldawson — APPROVED** [review]
