### PR TITLE
Use GEOS backend for 2d tessellation wherever available

### LINKED ISSUE #54065: QGIS Crashes Upon Exporting Layout to PDF when Using Random Point Fill Symbology
### What is the bug or the crash?

I've built a basic layout with a single map and no other elements. 

It has census block polygons for the state of Wisconsin, symbolized with the random point fill option. I've tried both 10 points per polygon and 1, as well as my original goal which was expression based.

### Steps to reproduce the issue

add a layer >> symbolize as random point fill >> create a layout >> export to pdf. 

I think I've seen in some cases, if the layout extent is smaller, the crash does not happen. I am not certain about this. 

Exporting to png does not crash QGIS so far. 

I've tried this on both 3.28.9 and 3.32.1 with the same result.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.28.9-Firenze | QGIS code revision | 66f4d63ad4
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.1
PROJ version | 9.2.1
EPSG Registry database version | v10.088 (2023-05-13)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.41.1
PDAL version | 2.5.5
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.28.9-Firenze
QGIS code revision
[66f4d63ad4](https://github.com/qgis/QGIS/commit/66f4d63ad4)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

data source here https://www.dropbox.com/s/9wyuyrsz9zyvvjp/20230803_data.gpkg?dl=0

qgis file here: https://www.dropbox.com/s/4ydy6vgrnt9cb9q/20230804_demo_rebuild.qgz?dl=0

### LINKED ISSUE #54652: Bug: Tessellate processing tool discarding parts of valid source polygon layer
### What is the bug or the crash?

We are having an issue with the tesselate algorithm. On some of our extractions, big chunks of road network as polygons are deleted after the tesselate. There is no error in log.

Altough all geometries are valid under "fix geometries" and "check validity" tools, I personnaly suspect the source data to having some kind of invalid geometry, causing this bug. A hint to support this theory is that I encounter similar bugs with other processing tools down the line: https://github.com/NRCan/geo_sim_processing/issues/21.

1. Source polygons
image

2. Tesselation
image

Zoomed out before:
2023-09-18 10_52_22-_Untitled Project — QGIS

Zoomed out after:
image

Log (no errors):
image

### Steps to reproduce the issue

Sample vector data causing problems (all geometries are valid under "fix geometries" and "check validity" tools in QGIS):
[QC_SaintJeanSurRichelieu_WV02_20210524-017162145010_01_P001-WV02_ROAI_raw_clipped.zip](https://github.com/NRCan/geo_sim_processing/files/12613280/QC_SaintJeanSurRichelieu_WV02_20210524-017162145010_01_P001-WV02_ROAI_raw_clipped.zip)

1. Open "Tesselate" processing tool
2.  Choose attached file as source layer
3. Run

### Versions

QGIS version
3.30.2-'s-Hertogenbosch
QGIS code branch
Release 3.30
Qt version
5.15.3
Python version
3.10.6
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.2 LTS

Active Python plugins
MetaSearch
0.3.6
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

*** ALSO TESTED WITH: ***

QGIS version
3.26.3-Buenos Aires
QGIS code revision
65e4edfdada
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
geoml-stac-browser-master
1.0.0
geo_sim_processing-Dan-Eli-master
0.6.1
go2streetview
8.6
HCMGIS
23.7.19
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nyalldawson**
Notable this addresses two data corruption/crashing bugs:

- Updates the logic in the Tessellate algorithm so that if using a recent enough GEOS (>=3.11) and the input geometries
are 2d, then GEOS constrained Delaunay Triangulation implementation is used instead of poly2tri. The GEOS method is much more robust for spatial geometry objects, eg handling gracefully valid situations like interior holes which touch the exterior ring of polygons. It's also better supported and slightly faster. The quality of the triangulation is comparable to poly2tri. Fixes https://github.com/qgis/QGIS/issues/54652
- Use GEOS constrainedDelaunayTriangulation for random points in polygon backend where available, instead of poly2tri. This is more stable. Fixes https://github.com/qgis/QGIS/issues/54065

### CODE REVIEW

File: src/core/geometry/qgsgeometrycollection.h [hunk 1]
```diff
@@ -390,6 +390,21 @@ class CORE_EXPORT QgsGeometryCollection: public QgsAbstractGeometry
...
+     * which match the specified WKB \a type.
+     *
+     * For instance, if \a type is Qgis::WkbType::Polygon, then the returned object will be a QgsMultiPolygon
+     * object containing just the polygons from this collection.
+     *
+     * If \a useFlatType is TRUE, then the WKB types of component geometries from this collection will
+     * be flattened prior to comparing with \a type. (I.e. the presence of Z / M dimensions will be ignored
+     * when comparing against \a type).
+     *
+     * \since QGIS 3.36
```
Comment (lbartoletti) [inline src/core/geometry/qgsgeometrycollection.h:404]:
```suggestion
     * \since QGIS 3.38
```

File: src/core/geometry/qgsgeometry.h [hunk 2]
```diff
@@ -1829,10 +1829,26 @@ class CORE_EXPORT QgsGeometry
...
+     * Returns a constrained Delaunay triangulation for the vertices of the geometry.
+     *
+     * An empty geometry will be returned if the triangulation could not be calculated.
+     *
+     * This method requires a QGIS build based on GEOS 3.11 or later.
+     *
+     * \throws QgsNotSupportedException on QGIS builds based on GEOS 3.10 or earlier.
+     * \see delaunayTriangulation()
+     *
+     * \since QGIS 3.36
```
Comment (lbartoletti) [inline src/core/geometry/qgsgeometry.h:1848]:
```suggestion
     * \since QGIS 3.38
```

File: src/3d/processing/qgsalgorithmtessellate.cpp [hunk 3]
```diff
@@ -88,41 +89,76 @@ QgsFeatureList QgsTessellateAlgorithm::processFeature( const QgsFeature &feature
...
       {
-        if ( !t.error().isEmpty() )
+        // 3D case, or 2D case with unsupported GEOS version -- use less stable poly2tri backend
+        const QgsRectangle bounds = f.geometry().boundingBox();
+        QgsTessellator t( bounds, false );
+
+        if ( f.geometry().isMultipart() )
         {
-          feedback->reportError( QObject::tr( "Feature ID %1 was only partially tessellated: %2" ).arg( f.id() ).arg( t.error() ) );
+          const QgsMultiSurface *ms = qgsgeometry_cast< const QgsMultiSurface * >( f.geometry().constGet() );
```
Comment (lbartoletti) [inline src/3d/processing/qgsalgorithmtessellate.cpp:128]: Why don't use smart ptr here?

File: tests/src/python/test_qgsgeometrycollection.py [hunk 4]
```diff
@@ -105,6 +115,309 @@ def testFuzzyComparisons(self):
...
+            'MultiPoint EMPTY'
+        )
+        self.assertEqual(
+            empty_collection.extractPartsByType(
+                Qgis.WkbType.MultiPoint).asWkt(),
+            'MultiPoint EMPTY'
+        )
+        self.assertEqual(
+            empty_collection.extractPartsByType(
+                Qgis.WkbType.MultiPointZ).asWkt(),
```
Comment (lbartoletti) [inline tests/src/python/test_qgsgeometrycollection.py:135]: Please, insert a test for MultiPointM

File: src/core/geometry/qgsgeos.h [hunk 5]
```diff
@@ -547,10 +547,25 @@ class CORE_EXPORT QgsGeos: public QgsGeometryEngine
...
+     * Returns a constrained Delaunay triangulation for the vertices of the geometry.
+     *
+     * An empty geometry will be returned if the triangulation could not be calculated.
+     *
+     * This method requires a QGIS build based on GEOS 3.11 or later.
+     *
+     * \throws QgsNotSupportedException on QGIS builds based on GEOS 3.10 or earlier.
+     * \see delaunayTriangulation()
+     *
+     * \since QGIS 3.36
```
[the remark this answers is not in the document]
Comment (nyalldawson) [reply src/core/geometry/qgsgeos.h:565]: I want to get this in for release and backport -- it fixes a crash and silent data loss issue

File: src/3d/processing/qgsalgorithmtessellate.cpp (hunk 3 above)
Comment (nyalldawson) [reply src/3d/processing/qgsalgorithmtessellate.cpp:128]: It's non owned

File: tests/src/python/test_qgsgeometrycollection.py (hunk 4 above)
Comment (nyalldawson) [reply tests/src/python/test_qgsgeometrycollection.py:135]: Done!

File: src/3d/processing/qgsalgorithmtessellate.cpp [hunk 6]
```diff
@@ -88,41 +89,76 @@ QgsFeatureList QgsTessellateAlgorithm::processFeature( const QgsFeature &feature
...
+        // for 2D triangulation, as it's more stable and tolerant to situations like polygon
+        // holes touching an exterior ring vs the poly2tri based tessellation
+        const QgsGeometry triangulation = inputGeometry.constrainedDelaunayTriangulation();
+        if ( triangulation.isEmpty() && !inputGeometry.isEmpty() )
         {
-          const std::unique_ptr< QgsPolygon > p( qgsgeometry_cast< QgsPolygon * >( ms->geometryN( i )->segmentize() ) );
-          t.addPolygon( *p, 0 );
+          if ( !triangulation.lastError().isEmpty() )
+          {
+            feedback->reportError( QObject::tr( "Feature ID %1 could not be tessellated: %2" ).arg( f.id() ).arg( triangulation.lastError() ) );
```
Comment (nirvn) [inline src/3d/processing/qgsalgorithmtessellate.cpp:105]: Out of curiosity, do you see scenarios when geos would fail but poly2tri would not? I'm wondering whether it'd be worth having a failed geos triangulation fallback to poly2tri here.

**Review by nirvn — APPROVED** [review]
Nice, quite happy to be moving away from poly2tri when it comes to 2D symbology (i.e. random marker). One question, but otherwise code looks good

File: src/core/geometry/qgsgeos.h (hunk 5 above)
[the remark this answers is not in the document]
Comment (lbartoletti) [reply src/core/geometry/qgsgeos.h:565]: Mmmh ok, I hadn't read the ticket description, if it fixes crashes then OK for 3.36. Even though I've done it before, and it was allowed, I always prefer to avoid adding new methods in backports. Especially as there are several of them here, and not small ones. Anyway, they seem quite limited to this case, well tested, and, again, if it can improve QGIS behavior, that's fine with me. Nevertheless, would it be possible to do some manual testing before the merge of backport 3.34?

[the remark this answers is not in the document]
Comment (nyalldawson) [reply src/core/geometry/qgsgeos.h:565]: Ultimately, I trust geos much more here vs poly2tri. You can see on that library's tracker that there's many known issues, and basically zero upstream maintainence happening. In contrast geos is very well supported, thoroughly tested, it's robust, and very actively maintained. If we find an issue I'm confident upstream will address promptly. 

I'd say given this the reward of backporting far outweighs the risk. (Especially because we already know if fixes at least two serious issues on the qgis side)

[the remark this answers is not in the document]
Comment (nyalldawson) [reply src/core/geometry/qgsgeos.h:565]: Also worth pointing out that the complex looking new code for random points is identical to the existing poly2tri branch, just adapted to call geos for the tesselation and to adapt to the data structure returned by geos. The actual logic is unchanged.

File: src/3d/processing/qgsalgorithmtessellate.cpp (hunk 6 above)
Comment (nyalldawson) [reply src/3d/processing/qgsalgorithmtessellate.cpp:105]: > Out of curiosity, do you see scenarios when geos would fail but poly2tri would not

I don't. Poly2tri has been designed with much simpler geometries in mind vs typical spatial data. And geos is definitely designed and tested on those types of data! 🤣
