### PR TITLE
[ogr] Fix SQL layers filter

### LINKED ISSUE #62542: Using "Subset filter" from the "Execute SQL" dialog is not applied
### What is the bug or the crash?

1. Take a shapefile (I also tested with a gpkg)
2. Right-click, "Execute SQL..."
3. Fill an SQL expression, execute
4. In "Load layer" section, add a where-like statement in the "Subset Filter"
5. Load the layer
6. Watch its properties, the where statement is removed from the SQL query, and of course, filter is not applied.

### Steps to reproduce the issue

There might be better screencats in the world but... I try to show different combination of using that "subset filter" and it doesn't work.

https://github.com/user-attachments/assets/8fac1e83-e05c-47c9-b6fc-19d0bc081447

### Versions

Report is on macOS but I observed this already on Windows
<table width='100%' align='center'><tr><td>QGIS version</td><td>3.99.0-Master</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/e59a7c0a">e59a7c0a</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>6.8.3</td></tr><tr><td>Python version</td><td>3.11.10</td></tr><tr><td>GDAL version</td><td>3.11.0 — <i>Eganville</i></td></tr><tr><td>PROJ version</td><td>9.6.2</td></tr><tr><td>EPSG Registry database version</td><td>v12.013 (2025-05-26)</td></tr><tr><td>GEOS version</td><td>3.13.0-CAPI-1.19.0</td></tr><tr><td>SQLite version</td><td>3.49.2</td></tr><tr><td>PDAL version</td><td>2.9.0</td></tr><tr><td>PostgreSQL client version</td><td>16.9</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.3.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>macOS Sequoia (15.5)</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>MapsPrinter</td><td>1.0</td></tr><tr><td>plugin_reloader</td><td>0.17</td></tr><tr><td>processing</td><td>2.12.99</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr></table>

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Fix #62542

### CODE REVIEW

File: src/core/providers/ogr/qgsogrproviderconnection.cpp [hunk 1]
```diff
@@ -292,7 +293,33 @@ QgsVectorLayer *QgsOgrProviderConnection::createSqlVectorLayer( const QgsAbstrac
...
+
+  // We have two options here: if the original SQL is a plain SELECT * FROM table [WHERE ...] statement,
+  // we could turn this into a normal layer with a subset filter but this would be a bit inconsistent from a UX
+  // perspective because the SQL update menu would not be available, let's keep it a SQL layer always.
+
+  if ( !options.filter.isEmpty() )
+  {
+    if ( ! where.isEmpty() )
+    {
+      decoded[ QStringLiteral( "subset" ) ] = QStringLiteral( R"sql(%1 AND ( %2 ))sql" ).arg( sanitizeSqlForQueryLayer( options.sql ), options.filter );
```
Comment (rouault) [inline src/core/providers/ogr/qgsogrproviderconnection.cpp]: I believe there could be an issue if the options.sql is something like "SELECT * from table WHERE a OR b"
It would become "SELECT * from table WHERE a OR b AND (filter)" wheras it should be  "SELECT * from table WHERE (a OR b) AND (options.filter)"

Comment (elpaso) [reply src/core/providers/ogr/qgsogrproviderconnection.cpp]: Thank you: fixed and test added.

**Review by rouault — APPROVED** [review]
