### PR TITLE
[server][wms] Fix GFI respect form config in XML output format

### LINKED ISSUE #59355: QGIS Server OGC: Ignoring "Use attribute form settings in GetFeatureInfo response" in GML output
### What is the bug or the crash?

If QGIS server option "Use attribute form settings in GetFeatureInfo response" is enabled, GML output for GetFeatureInfo is returning all attributes. Excepted behavior is to return just configured attributes.

Option is enabled:

image

Drag and drop attributes:

image

GML feature member response with more attributes then expected - cl_label, cl_owner etc. (GetFeatureInfo with INFO_FORMAT=application/vnd.ogc.gml).

```xml
<gml:featureMember>
  <qgs:closure_df66a4aa_cf33_497e_b134_aa157ea885df fid="closure_df66a4aa_cf33_497e_b134_aa157ea885df.339">
   <gml:boundedBy>
    <gml:Box srsName="EPSG:3857">
     <gml:coordinates cs="," ts=" ">-111 -111</gml:coordinates>
    </gml:Box>
   </gml:boundedBy>
   <qgs:geometry>
    <gml:Point srsName="EPSG:3857">
     <gml:coordinates cs="," ts=" ">-111,111</gml:coordinates>
    </gml:Point>
   </qgs:geometry>
   <qgs:fid>339</qgs:fid>
   <qgs:cl_id>106</qgs:cl_id>
   <qgs:cl_label>Item 339</qgs:cl_label>
   <qgs:cl_owner>Blahblah</qgs:cl_owner>
   <qgs:cl_network>(NULL)</qgs:cl_network>
   <qgs:cl_logical>Something</qgs:cl_logical>
   <qgs:cl_splices>0</qgs:cl_splices>
   <qgs:Techpoint>(0)</qgs:Techpoint>
   <qgs:no_prop>0</qgs:no_prop>
   <qgs:notes_link>{f64f44da-f074-4ca6-aac0-497cd666fef6}</qgs:notes_link>
   <qgs:photos_link>{f54ba2b7-72db-4f03-83f4-e228798c4743}</qgs:photos_link>
  </qgs:closure_df66a4aa_cf33_497e_b134_aa157ea885df>
 </gml:featureMember>
``` 

Json is following discussed option properly.

Another issue with ```application/vnd.ogc.gml``` is that format returns XML encoded in Base64. I'm not sure if it's ok.

### Steps to reproduce the issue

1. Enable discussed parameter in QGIS server
2. Try to run GetFeatureInfo with ```application/vnd.ogc.gml``` INFO_FORMAT

### Versions

3.34.12-Prizren

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Fix #59355

### CODE REVIEW

File: src/server/services/wms/qgswmsrenderer.cpp [hunk 1]
```diff
@@ -2980,6 +2981,9 @@ namespace QgsWms
       expressionContext << QgsExpressionContextUtils::layerScope( layer );
     expressionContext.setFeature( *feat );
 
+    QgsEditFormConfig editConfig { layer ? layer->editFormConfig() : QgsEditFormConfig() };
+    const bool honorFormConfig { layer && QgsServerProjectUtils::wmsFeatureInfoUseAttributeFormSettings( *mProject ) && editConfig.layout() == Qgis::AttributeFormLayout::DragAndDrop };
```
Comment (rouault) [inline src/server/services/wms/qgswmsrenderer.cpp:2985]: genuinely naive question. It feels odd to test something that sounds like a purely view/UI detail "DragAndDrop" in a non-UI context. Perhaps that's just an odd naming. But looking at the enumeration it contains and the code below, I'm wondering if the code below couldn't also make sense for the AutoGenerated or UiFile case, since it is not obvious to me that QgsAttributeEditorContainer is correlated with DragAndDrop. Hope that makes sense... Anyway, feel free to ignore if that should make sense for readers familiar with those bits of code.

Comment (elpaso) [reply src/server/services/wms/qgswmsrenderer.cpp:2985]: @rouault QGIS server uses QGIS desktop to generate the project files (qgs/qgz) and QGIS desktop allow to store the fields configuration in a few different ways (drag and drop is one of those), not all these configuration options are available/implemented in the server (for instance the .ui file is not, probably because it is really very tied to a GUI context)   I don't know what we can do about it but yes, I agree it can look odd.
