### PR TITLE
[Fix] Matrix parameter export to Python

### LINKED ISSUE #45693: Graphic Modeler Export to Python for Matrix Parameter Giving Incorrect Syntax
### What is the bug or the crash?

If your graphic model has a Matrix Parameter and you export it to python you get incorrect code for Matrix Parameter. See screenshot below

image

On export to python, it is giving this.

```python
self.addParameter(QgsProcessingParameterMatrix('outputs', 'Outputs', numberRows=, hasFixedNumberRows=, headers=['Name','Output? [Y/N]'], defaultValue=[Runoff,Y,Lead,N,Nitrogen,N,Phosphorus,N,Zinc,N,TSS,N]))
```
If you run the code with the above line it will give you an error. The fix that worked for me is given below

```python
self.addParameter(QgsProcessingParameterMatrix('outputs', 'Outputs', headers=['Name','Output? [Y/N]'], defaultValue=['Runoff','Y','Lead','N','Nitrogen','N','Phosphorus','N','Zinc','N','TSS','N']))
```

### Steps to reproduce the issue

Create a graphic model with matrix input.
Export model to python.
Run python script.

### Versions

Checked on 3.16 and 3.22.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Koyaani**
## Description

Fixes #45693, the export to python script of matrix parameters. There are 2 problems, the export of the default value and some parameters.

For the default value, I wrapped each matrix item with the method `stringToPythonLiteral`. All values are transformed into strings (even numbers). It seems to work but I can't be sure that it doesn't break anything.

For the parameters, I added the markers that were missing.

### CODE REVIEW

File: src/core/processing/qgsprocessingparameters.cpp [hunk 1]
```diff
@@ -3597,7 +3597,7 @@ QString QgsProcessingParameterMatrix::valueAsPythonString( const QVariant &value
         else if ( v2.toString().isEmpty() )
           parts2 << QStringLiteral( "''" );
         else
-          parts2 << v2.toString();
+          parts2 << QgsProcessingUtils::stringToPythonLiteral( v2.toString() );
```
Comment (nyalldawson) [inline src/core/processing/qgsprocessingparameters.cpp:3600]: I think this should be variantToPythonLiteral instead, to avoid the forced string conversions

**Comment by Koyaani** [comment]
@nyalldawson It simplifies the code a lot by using `variantToPythonLiteral` but I'm not sure if it is clean enough... I don't know how to check correctly if a `QString` represents a number or not.

**Comment by nyalldawson** [comment]
This looks good to me, thanks!

**Review by nyalldawson — APPROVED** [review]
