### PR TITLE
Project Translation considers descriptions of Value Map Widget

### LINKED ISSUE #56089: Value maps definition in attribute widget are not translated
### What is the bug or the crash?

the original dev of the translation of project: https://github.com/qgis/QGIS/pull/7456

I would expect the description entries of the value map definition of an attribute to be translated.

### Steps to reproduce the issue

-

### Versions

3.28

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by signedav**
Value Map descriptions can now be translated as well.

| This loaded with EN settings    | ...becomes this loaded with DE settings|
| -------- | ------- |
|image| image |

The values are of course the same.

This fixes #56089

Additionally I included missing tests for the Value Relation value translation.
The ts file is committed as well, so the tests can be extended in future with low effort.

This handles only value maps stored as QLists (means after this implementation #6091 and > 3.4)

### CODE REVIEW

**Review by 3nids — APPROVED** [review]
LGTM!

File: src/core/project/qgsproject.cpp [hunk 1]
```diff
@@ -685,11 +685,14 @@ void QgsProject::registerTranslatableObjects( QgsTranslationContext *translation
         }
         if ( field.editorWidgetSetup().type() == QStringLiteral( "ValueMap" ) )
         {
-          const QList<QVariant> valueList = field.editorWidgetSetup().config().value( QStringLiteral( "map" ) ).toList();
-
-          for ( int i = 0, row = 0; i < valueList.count(); i++, row++ )
+          if ( field.editorWidgetSetup().config().value( QStringLiteral( "map" ) ).canConvert<QList<QVariant>>() )
```
Comment (signedav) [inline src/core/project/qgsproject.cpp:688]: Beside using QList<QVariant> consequently I added this line. Otherwise it would just had returned an empty list, but with this it's cleaner...

**Comment by signedav** [comment]
Thanks @3nids
