### PR TITLE
[RuleBasedRendering] Keep rule key while cloning when needed

### LINKED ISSUE #46402: Masking labels doesn't work with rule based labeling
### What is the bug or the crash?

Simple... I've any masking for labels even enabling the mask in label and selecting the masking options in layer properties

### Steps to reproduce the issue

1. create a line layer
2. create a label and enable the masking option
3. in the layer properties select both check box to enable the masking

### Versions

Versione di QGIS
3.16.6-Hannover
Revisione codice QGIS
bfd36fddc9
Compilato con Qt
5.11.2
Esecuzione con Qt
5.11.2
Compilato con GDAL/OGR
3.1.4
Esecuzione con GDAL/OGR
3.1.4
Compilato con GEOS
3.8.1-CAPI-1.13.3
Esecuzione con GEOS
3.8.1-CAPI-1.13.3
Compilato su SQLite
3.29.0
In esecuzione su SQLite
3.29.0
Versione client PostgreSQL
11.5
Versione SpatiaLite
4.3.0
Versione QWT
6.1.3
Versione QScintilla2
2.10.8
Compilato con PROJ
6.3.2
Esecuzione con PROJ
Rel. 6.3.2, May 1st, 2020
Versione SO
Windows 10 (10.0)
Attiva python plugin
AzimuthDistanceCalculator; 
batch_hillshader-master; 
clipper; 
coordinates_converter; 
DigitizingTools; 
latlontools; 
map-coords-plugin; 
points2one; 
profiletool; 
Qgis2threejs; 
zoom_level; 
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by troopa81**
rule key is used by other object as reference (masking for instance)

Fixes #46402 (completely I hope this time)

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]

File: tests/src/gui/testqgslabelingwidget.cpp [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+{
+}
+
+void TestQgsLabelingWidget::cleanup()
+{
+}
+
+void TestQgsLabelingWidget::testRuleKeyPreserved()
+{
+  // test that rule keys are preserved and not resetted when editing labels with a rule based rendering
```
Comment (nyalldawson) [inline tests/src/gui/testqgslabelingwidget.cpp:57]:
```suggestion
  // test that rule keys are preserved and not reset when editing labels with a rule based rendering
```
