### PR TITLE
GEOMETRY: fix regression on split multipart

### LINKED ISSUE #54155: Splitting MultiLineStrings gives awkward results
### What is the bug or the crash?

Using the _Split Features_ tool on a MultiLineString with several disjoint parts eventually splits more parts than those intersected.

Peek 2023-08-09 09-57

### Steps to reproduce the issue

1. Get a layer with several non intersecting lines 
2. Generate a MultiLineString using _Dissolve_ processing algorithm
3. Use the _Split Features_ tool to split one of the MultiLineString's segments
4. Other segments are also split

### Versions

479d66ab

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

@ghtmtt Is this what you described on the mailing list?

### PR DESCRIPTION
**Pull request by elpaso**
Fix #54155

With "new" split logic introduced a few months ago, the split point was re-snapped (so to say) to the closest segment, but this did not work with multi parts because not only the intersected part was split but all parts!

A new test cover the issue (both Python and C++).

### CODE REVIEW

File: src/core/geometry/qgsgeos.cpp [hunk 1]
```diff
@@ -1056,14 +1056,23 @@ geos::unique_ptr QgsGeos::linePointDifference( GEOSGeometry *GEOSsplitPoint ) co
...
+
       QgsPoint segmentPoint2D;
       QgsVertexId nextVertex;
       // With closestSegment we only get a 2D point so we need to interpolate if we
       // don't want to lose Z data
       line->closestSegment( *intersectionPoint, segmentPoint2D, nextVertex );
+
+      // The intersection might belong to another part, skip it
+      // Note: cannot test for equality because of Z
+      if ( intersectionPoint->x() != segmentPoint2D.x() || intersectionPoint->y() != segmentPoint2D.y() )
```
Comment (nyalldawson) [inline src/core/geometry/qgsgeos.cpp:1071]:
```suggestion
      if ( !qgsDoubleNear( intersectionPoint->x(), segmentPoint2D.x() ) || !qgsDoubleNear( intersectionPoint->y(), segmentPoint2D.y() ) )
```

**Review by nyalldawson — APPROVED** [review]
