### PR TITLE
Several improvements of annotation layer styling

### LINKED ISSUE #50110: No Undo/Redo history populated for layer annotations
### What is the bug or the crash?

While there is a History tab available in Layer Styling panel for annotations layer, it is always empty, making it impossible to undo/redo latest actions

### Steps to reproduce the issue

From the annotations toolbar, create an annotation element
Select it and edit its symbology properties in the styling layer panel
Switch to the "History" tab, the single entry you have states `<empty>`
Well... Try to use the Undo/Redo button at the bottom of the panel. Still nothing

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.0-Buenos Aires | QGIS code revision | 0aece2818e
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 12.5
  |   |   |  
Active Python plugins
plugin_reloader | 0.9.1
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### LINKED ISSUE #50113: Reference to Main annotation layer is kept across projects opening until QGIS is closed
### What is the bug or the crash?

Once you played with the main annotation layer, a reference is kept to it in the subsequent projects you open until you close QGIS.

### Steps to reproduce the issue

Open a QGIS project
Play with the annotations layer
Close the project, **not QGIS**.
Watch the Layer styling panel; the annotation layer is still displayed
Open another project, the annotation layer is still displayed in the Layer styling drop-down layers list. Despite that project has never been used with Annotation.
The only way to not have that layer in the list anymore is to reopen QGIS.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.0-Buenos Aires | QGIS code revision | 0aece2818e
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 12.5
  |   |   |  
Active Python plugins
plugin_reloader | 0.9.1
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### LINKED ISSUE #50117: Annotations features with no annotation layer attached
### What is the bug or the crash?

If you start adding annotations layer features without having created the layer itself, you may end up with features with no properties displayed.

### Steps to reproduce the issue

1. Open QGIS, empty project
2. Enable the "Annotations" toolbar
3. Select an annotation layer tool and add an annotation element
4. Select it and give a look to the Layer styling panel: you have no properties, no annotations layer in drop down menu

I think adding a layer annotation feature in this case should trigger creation of the main annotation layer and display it in the Layer styling panel 

Capture d’écran 2022-09-06 à 17 13 13

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.0-Buenos Aires | QGIS code revision | 0aece2818e
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 12.5
  |   |   |  
Active Python plugins
plugin_reloader | 0.9.1
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### LINKED ISSUE #50118: Annotations from the main annotations layer do not display if no other layer in the project
### What is the bug or the crash?

Main annotations layer requires another layer in the project before it displays symbology tab for features customization.

### Steps to reproduce the issue

1. Open QGIS, empty project
2. Enable the "Annotations" toolbar
3. (optional) Select an annotation layer tool and add an annotation element
4. (optional) Select it and give a look to the Layer styling panel: you have no properties, no annotations layer in drop down menu (--> #50117)
5. Open the "Main annotation layer properties" and apply: the Annotations layer is displayed in the Layer Styling panel, with the Undo/Redo tab displayed
6. Add a new annotation element, select it and watch the Layer styling panel: still no symbology panel
7. Add a "new annotation layer" or load a conventional layer
8. Select the annotations you previously drew: they now show a symbology tab, allowing customization

https://user-images.githubusercontent.com/7983394/188675944-5a04f25b-efb1-4e1d-8e1c-614cc87b8621.mov

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.0-Buenos Aires | QGIS code revision | 0aece2818e
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 12.5
  |   |   |  
Active Python plugins
plugin_reloader | 0.9.1
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by CodeBardian**
This PR addresses multiple issues related to the styling panel of annotation layers.

Here is the breakdown of what each commit does:

- `1873329e`: fixes #50118 and fixes #50117
	- annotation items of the main annotation layer could not be modified without another layer in the project
	- this is solved by registering the map layer property factories before creating the `QgsLayerStylingWidget`. Otherwise the styling widget does not know what contents to show for the main annotation layer.

- `55fd355b`: fixes #50110
	- layer styling history was not being populated for changes on annotation layer items
	- solved by adding missing `widgetChanged` signal to inform styling widget of changes

- `7d29f602` and `7c752bd7`: fixes #50113
	- the layer styling panel always showed properties and history of the main annotation layer of a previously opened project
	- fixed by clearing the undo stack on reset of a annotation layer and removing the reference to the layer on closing a project

- `23bc1cef`: 
	- the layer styling history on annotation layers has never been working because annotation layers did not have `writeStyle`/`readStyle` methods which are required to apply the changes from the undo stack (e.g. in `QgsMapLayerStyleCommand::undo()`). This resulted in the base class implementation of `QgsMapLayer::readStyle` or `QgsMapLayer::writeStyle` being called which do nothing. 
	- solved by adding the mentioned methods 

---
Screencast: https://imgur.com/a/s8VL1b7

### CODE REVIEW

File: src/app/qgslayerstylingwidget.cpp [hunk 1]
```diff
@@ -743,6 +743,7 @@ void QgsLayerStylingWidget::setAnnotationItem( QgsAnnotationLayer *layer, const
   mContext.setAnnotationId( itemId );
   if ( layer )
     setLayer( layer );
+  mStackedWidget->setCurrentIndex(1);
```
Comment (nyalldawson) [inline src/app/qgslayerstylingwidget.cpp]: Shouldn't this always be triggered by the setLayer command above? What's the sequence of events leading to layer being nullptr but a valid annotation item being selected?

Comment (CodeBardian) [reply src/app/qgslayerstylingwidget.cpp]: > Shouldn't this always be triggered by the setLayer command above?

the `setLayer` function often does not reach `mStackedWidget->setCurrentIndex( 1 );` Consider the following sequence:

- layer styling widget is created, `mCurrentLayer` is set to the main annotation layer (the only layer in a newly opened project)
- now create an annotation item 
- `setAnnotationItem` is called which also calls `setLayer`, but `setLayer` immediately returns because layer equals `mCurrentLayer` (both reference main annotation layer)
-> this results in the fact that you could not edit annotation items of the main annotation layer, because it would always stay on the 'notSupportedPage'

-- 
But I agree that `mStackedWidget->setCurrentIndex( 1 );` should probably be within the if-statement. It does not make sense to show the layer page if layer is null.

**Review by nyalldawson — APPROVED** [review]
