### PR TITLE
[raster][rat] COG: suggest IGNORE_COG_LAYOUT_BREAK=YES

### LINKED ISSUE #65040: Bands get cleared after attribute table creation fails, causing rendering issues and crashes
### What is the bug or the crash?

When creating an attribute table that's managed by the data provider on a COG raster layer, it fails with the message "GDAL error saving raster attribute table, raster attribute table could not be saved." (this might not be true of all COG layers, but that's a separate issue). This causes the list of bands to be reset, and occasionally logs the error "ERROR 10: Pointer 'hBand' is NULL in 'GDALSetDefaultRAT'." to the console. More importantly, it causes the layer to render extremely strangely, and almost looks to be reading image data from somewhere else in the program memory. See attached video for an example.

I also encountered a crash in `QgsRasterLayerProperties::sync` after the bands were reset,  but I can't seem to reproduce it.
It's also worth noting that this does not happen with GeoTIFF layers, only COG layers.

MRE COG file:
[cog_vat_bug_sample.tif](https://github.com/user-attachments/files/25474658/cog_vat_bug_sample.tif)

Video:
https://github.com/user-attachments/assets/43d4475f-a652-4652-8f45-dcc03dd9e25b

### Steps to reproduce the issue

1. Create a raster layer from a COG TIFF file
2. Open the properties, go to "Attribute Tables", and click "New attribute table from current symbology"
3. Observe the GDAL error, and click OK
4. Try to create the attribute table again, this time using a sidecar VAT.DBF file
5. This should work, now click OK
6. Observe that the band list is now empty, and panning/zooming the map causes weird artifacts and visible corruption/memory issues

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.44.7-Solothurn</td></tr><tr><td>QGIS code branch</td><td><a href="https://github.com/qgis/QGIS/tree/release-3_44">Release 3.44</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.18</td></tr><tr><td>Python version</td><td>3.14.2</td></tr><tr><td>GDAL version</td><td>3.11.5 — <i>Eganville</i></td></tr><tr><td>PROJ version</td><td>9.6.2</td></tr><tr><td>EPSG Registry database version</td><td>v12.013 (2025-05-26)</td></tr><tr><td>GEOS version</td><td>3.14.1-CAPI-1.20.5</td></tr><tr><td>SQLite version</td><td>3.50.2</td></tr><tr><td>PDAL version</td><td>2.9.3</td></tr><tr><td>PostgreSQL client version</td><td>18.0</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.2.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Fedora Linux 43 (KDE Plasma Desktop Edition)</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>loadthemall</td><td>3.4</td></tr><tr><td>advanced_map_downloader</td><td>1.0.0</td></tr><tr><td>xyz_tiles_basemap_loader</td><td>0.1</td></tr><tr><td>ee_plugin</td><td>0.1.7</td></tr><tr><td>vrtbuilderplugin</td><td>0.9.20210222T174536.master</td></tr><tr><td>shapefile_encoding_fixer</td><td>0.7.1</td></tr><tr><td>processing_saga_nextgen</td><td>1.1.0</td></tr><tr><td>wbt_for_qgis</td><td>1.0.9</td></tr><tr><td>a00_qpip</td><td>1.4.2</td></tr><tr><td>qraster_merge</td><td>1.0.1</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I could reproduce this on both the Wayland and X11 QT platforms

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #65040

Suggest to set IGNORE_COG_LAYOUT_BREAK=YES when
an internal RAT cannot be saved (and more in general when a request to open in RW mode is made on a COG).

### CODE REVIEW

File: src/core/providers/gdal/qgsgdalprovider.cpp [hunk 1]
```diff
@@ -4492,11 +4513,22 @@ bool QgsGdalProvider::setEditable( bool enabled )
     QThread::msleep( 100 );
   }
 
+#if GDAL_VERSION_NUM >= GDAL_COMPUTE_VERSION(3,8,0)
+  // Check if this is a GTiff with COG layout because otherwise it won't open in update mode.
+  if ( mDriverName == "GTiff"_L1 && GDALGetMetadataItem( mGdalBaseDataset, "LAYOUT", "IMAGE_STRUCTURE" ) == "COG"_L1 && !dataSourceUri().contains( "IGNORE_COG_LAYOUT_BREAK=YES"_L1, Qt::CaseSensitivity::CaseInsensitive ) )
```
Comment (rouault) [inline src/core/providers/gdal/qgsgdalprovider.cpp]: is this safe if GDALGetMetadataItem() returns null ? (which it will for a non COG file)

Comment (elpaso) [reply src/core/providers/gdal/qgsgdalprovider.cpp]: I think so, it is also tested with the other test cases and I manually tested it without issues, but better safe than sorry, I will add a check.

**Review by alexbruy — APPROVED** [review]
