### PR TITLE
[ux] Fix labeling small font size freeze

### LINKED ISSUE #57336: setting labeling font size to less than 0.3 freezes qgis with meters units
### What is the bug or the crash?

In a new project, add a vector layer from a geopackage and label with a Text field. Then try to set the font Size to 0.3 when units is either "Map Units" (my crs is in meters) or "Meters at Scale". It should work fine if it is set to 0.4. But as soon as I enter a value equal or less than 0.3 QGIS freezes! I either have to wait for 5 min or force close QGIS. If I wait for the GUI to set it to 0.3, once I want to show the Properties page of the layer, it then freezes QGIS.

### Steps to reproduce the issue

create a new project and a new geopackage with vector layer and a Text field. add the layer to the map and label the Text field and set the font Size to 0.3 and the units to Meters at Scale

### Versions

3.34.6-Prizren

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Also tested with linestring.

Fix #57336

I cannot say I really understand the deep reason of the issue, but this apparently fixes it. 
It actually makes sense because for non-linestring layers that part of the GUI is hidden.

### CODE REVIEW

File: src/gui/qgstextformatwidget.cpp [hunk 1]
```diff
@@ -1294,8 +1294,11 @@ void QgsTextFormatWidget::updateFont( const QFont &font )
   // NOTE: QgsFontUtils::fontMatchOnSystem may fail here, just crosscheck family
   mFontMissingLabel->setVisible( !QgsFontUtils::fontFamilyMatchOnSystem( mRefFont.family() ) );
 
-  mDirectSymbLeftLineEdit->setFont( mRefFont );
-  mDirectSymbRightLineEdit->setFont( mRefFont );
+  if ( mDirectSymbolsFrame->isVisible() )
```
Comment (nyalldawson) [inline src/gui/qgstextformatwidget.cpp:1297]: I'd probably go with this:

   // use actual font family for left/right direction symbol editors, in case user is using a symbol font
   // and we want to show them an accurate representation of the symbols they'll get.
   // While we use the font family, we reset the size to the standard font size used by this widget -- we don't
   // want the line edit fonts to change size to match the label size.
   QFont symbolFont = mRefFont;
   symbolFont.setPointSize( font().pointSize() );
   mDirectSymbLeftLineEdit->setFont( symbolFont );
   mDirectSymbRightLineEdit->setFont( symbolFont );

Comment (elpaso) [reply src/gui/qgstextformatwidget.cpp:1297]: done

**Review by nyalldawson — APPROVED** [review]
