### PR TITLE
webconnections saving as .xml: add a xmlns:x=y attribute when the http-header: prefix is used

### LINKED ISSUE #60242: webconnections xml is invalid due to missing namespace prefix
### What is the bug or the crash?

From the QGIS browser, you can export the webconnections (e.g. xyz tiles, wm(t)s connection etc) to an xml file. However, this xml file is not valid xml because the http-header prefix is unbound/not defined. The result is that without preprocessing, tools like Python don't accept this xml.

```xml
<!DOCTYPE connections>
<qgsXYZTilesConnections version="1.0">
    <xyztiles username="" zmax="18" name="OSMq" password="" tilePixelRatio="0" zmin="0" authcfg="" url="https://tile.openstreetmap.org/{z}/{x}/{y}.png" referer="" http-header:referer=""/>
</qgsXYZTilesConnections>

``` 

### Steps to reproduce the issue

1. Add https://tile.openstreetmap.org/{z}/{x}/{y}.png as XYZ tileserver connection in the QGIS browser
2. Export the connection as xml

### Versions

QGIS-versie
3.34.14-Prizren
QGIS code revisie
0cdaf6d9
Qt versie
5.15.13
Python versie
3.12.8
GDAL/OGR versie
3.9.3
PROJ versie
9.5.0
EPSG-register databaseversie
v11.016 (2024-08-31)
GEOS versie
3.13.0-CAPI-1.19.0
SQLite versie
3.46.1
PDAL versie
2.8.1
PostgreSQL client versie
16.2
SpatiaLite versie
5.1.0
QWT versie
6.3.0
QScintilla2 versie
2.14.1
OS versie
Windows 10 Version 2009

Actieve Python plug-ins
pdokservicesplugin
5.1.1
db_manager
0.1.20
DDB_plugin
1.0.0
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
tauw_flagdotmap_plugin
1.0.0

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rouault**
Fixes #60242

### CODE REVIEW

File: src/core/network/qgshttpheaders.h [hunk 1]
```diff
@@ -126,13 +126,26 @@ class CORE_EXPORT QgsHttpHeaders
...
+     * \brief Updates a DOM element by adding all the HTTP headers
      *
      * KEY_REFERER value will be available at attribute "KEY_PREFIX+KEY_REFERER" and attribute "KEY_REFERER" (for backward compatibility)
      *
+     * \param el DOM element
+     * \param[out] namespaceDeclarations Map of (prefix, URI) tuples for namespaces used by el.
      * \return TRUE if the update succeed
      */
-    bool updateDomElement( QDomElement &el ) const;
+    bool updateDomElement2( QDomElement &el, QMap<QString, QString> &namespaceDeclarations SIP_OUT ) const;
```
Comment (rouault) [inline src/core/network/qgshttpheaders.h:148]: The naming with a '2' suffix is obviously a bit silly, but we can't have an override with the same name and a out parameter without breaking the Python API

Comment (rouault) [reply src/core/network/qgshttpheaders.h:148]: One could argue this stuff is probably not very useful in the Python API...

Comment (nyalldawson) [reply src/core/network/qgshttpheaders.h:148]: Why don't we make the new version private, and then just mark the old as deprecated "will be removed in QGIS 4"?

Comment (rouault) [reply src/core/network/qgshttpheaders.h]: done

File: src/core/network/qgshttpheaders.h [hunk 2]
```diff
@@ -126,13 +126,26 @@ class CORE_EXPORT QgsHttpHeaders
...
-     * \brief Updates a \a map by adding all the HTTP headers
+     * \brief Updates a DOM element by adding all the HTTP headers
+     *
+     * KEY_REFERER value will be available at attribute "KEY_PREFIX+KEY_REFERER" and attribute "KEY_REFERER" (for backward compatibility)
+     *
+     * \param el DOM element
+     * \return TRUE if the update succeed
+     * \deprecated QGIS 3.42. Will be removed in QGIS 4.0.
+     */
+    Q_DECL_DEPRECATED bool updateDomElement( QDomElement &el ) const;
```
Comment (nyalldawson) [inline src/core/network/qgshttpheaders.h:137]:
```suggestion
    Q_DECL_DEPRECATED bool updateDomElement( QDomElement &el ) const SIP_DEPRECATED;
```

**Comment by rouault** [comment]
all green now

**Review by nyalldawson — APPROVED** [review]
