### PR TITLE
provide default value when reading output folder setting to generate destination path in Processing (fix #61965)

### LINKED ISSUE #61965: Processing "Output folder" parameter seems unreliable if left to default value
### What is the bug or the crash?

In Settings --> Options --> Processing --> General, there is an option "[Output folder](https://docs.qgis.org/3.40/fr/docs/user_manual/processing/configuration.html#general)" that is meant to store output files when filled in the output widget without specifying a path. This defaults to "processing/outputs" folder in the active user profile folder.
If left to its default value:
- on macOS, it fails to create the output
    > Could not create layer ./mycentre.shp: Creation of layer failed (OGR error: Failed to create file mycentre.shp: Read-only file system)
Execution failed after 0.51 seconds
- on Windows, it creates an output stored at ./mycentre.shp that I'm unable to find on the drive; it isn't in the expected folder in any case.

If modified to a writable folder, no issue to find the output in the set folder.

### Steps to reproduce the issue

1. Open Settings --> Options --> Processing --> General, and check the value of "Output folder" is the default one
2. Run on your data any alg that allows outputting files on drive, and fill the output parameter with just the filename.extension
3. watch the execution output. Should either fail or create a file not stored in the expected folder
4. Modify the "output folder" parameter to a common place and try again. Should work now.

### Versions

Tested on Windows 10 osgeo4w, 3.43
<table width='100%' align='center'><tr><td>QGIS version</td><td>3.43.0-Master</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/2366440f66">2366440f66</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>6.8.1</td></tr><tr><td>Python version</td><td>3.12.10</td></tr><tr><td>GDAL version</td><td>3.12.0dev-f126431479</td></tr><tr><td>PROJ version</td><td>9.6.0</td></tr><tr><td>EPSG Registry database version</td><td>v12.004 (2025-03-02)</td></tr><tr><td>GEOS version</td><td>3.13.1-CAPI-1.19.2</td></tr><tr><td>SQLite version</td><td>3.46.1</td></tr><tr><td>PDAL version</td><td>2.8.3</td></tr><tr><td>PostgreSQL client version</td><td>17.3</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.3.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Windows 10 Version 22H2</td></tr><tr><td colspan="2"><i>This copy of QGIS writes debugging output.</i></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>plugin_reloader</td><td>0.17</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>               
			   
tested also on macos 3.42
<table width='100%' align='center'><tr><td>QGIS version</td><td>3.42.0-Münster</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/8f66da66788">8f66da66788</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.2</td></tr><tr><td>Python version</td><td>3.9.5</td></tr><tr><td>GDAL version</td><td>3.3.2</td></tr><tr><td>PROJ version</td><td>8.1.1</td></tr><tr><td>EPSG Registry database version</td><td>v10.028 (2021-07-07)</td></tr><tr><td>GEOS version</td><td>3.9.1-CAPI-1.14.2</td></tr><tr><td>SQLite version</td><td>3.35.2</td></tr><tr><td>PDAL version</td><td>2.3.0</td></tr><tr><td>PostgreSQL client version</td><td>12.3</td></tr><tr><td>SpatiaLite version</td><td>5.0.1</td></td></tr><tr><td>QWT version</td><td>6.1.6</td></tr><tr><td>QScintilla2 version</td><td>2.11.5</td></tr><tr><td>OS version</td><td>macOS 15.4</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>QuickOSM</td><td>2.2.3</td></tr><tr><td>search_and_replace_in_projects</td><td>1.3</td></tr><tr><td>changeDataSource</td><td>3.1</td></tr><tr><td>On-the-Fly-Shortest-Path</td><td>1.3.1</td></tr><tr><td>processing_r</td><td>4.1.0</td></tr><tr><td>Qgis2threejs</td><td>2.8</td></tr><tr><td>MemoryLayerSaver</td><td>5.0.2</td></tr><tr><td>MapsPrinter</td><td>0.9</td></tr><tr><td>lizmap</td><td>4.3.19</td></tr><tr><td>processing</td><td>2.12.99</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr></table>

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alexbruy**
## Description

If output folder setting in Processing is set to default (and as a result is not saved in the settings file), retrieving value from the `QgsProcessingLayerOutputDestinationWidget` will result in an incorrect path because `settings.value()` call lacks fallback value.

Fixes #61965.

### CODE REVIEW

**Comment by alexbruy** [comment]
I wonder if we should change default output path to something less hidden?

**Comment by nyalldawson** [comment]
@alexbruy 

> I wonder if we should change default output path to something less hidden?

How about QDir::homePath()? It's pretty obnoxious, but I can't think of any other location which makes sense.

**Comment by alexbruy** [comment]
@nyalldawson 

> How about QDir::homePath()? It's pretty obnoxious, but I can't think of any other location which makes sense.

Yes, I was thinking about similar approach. Maybe not in the root, but in the subdirectory, e.g. ` QDir::homePath()/processing-outputs`.

**Comment by alexbruy** [comment]
I have changed default output folder to `$HOME/processing`.

File: src/gui/processing/qgsprocessingoutputdestinationwidget.cpp [hunk 1]
```diff
@@ -175,7 +176,7 @@ QVariant QgsProcessingLayerOutputDestinationWidget::value() const
     if ( folder == '.' )
     {
       // output name does not include a folder - use default
-      QString defaultFolder = settings.value( QStringLiteral( "/Processing/Configuration/OUTPUTS_FOLDER" ) ).toString();
+      QString defaultFolder = settings.value( QStringLiteral( "/Processing/Configuration/OUTPUTS_FOLDER" ), QStringLiteral( "%1/processing" ).arg( QDir : homePath() ) ).toString();
```
Comment (nyalldawson) [inline src/gui/processing/qgsprocessingoutputdestinationwidget.cpp]:
```suggestion
      QString defaultFolder = settings.value( QStringLiteral( "/Processing/Configuration/OUTPUTS_FOLDER" ), QStringLiteral( "%1/processing" ).arg( QDir::homePath() ) ).toString();
```

**Review by nyalldawson — APPROVED** [review]

**Comment by benoitdm-oslandia** [comment]
@alexbruy Hi I come a bit too late on this PR and may be I should have filled an issue instead! 

Here is my issue: I have now another directory in my home directory with this name `processing` and it is confusing me. 

My question: why did not you put that folder inside the `$HOME/.local/share/QGIS/` or `%APPDATA%/QGIS`?

**Comment by alexbruy** [comment]
@benoitdm-oslandia because this directory is used for outputs created by Processing algorithms and having them in a location which is quite hidden for a normal users is not user-friendly. Hidden directories are not easily accessible from QGIS Browser or open datasource dialogs.

**Comment by benoitdm-oslandia** [comment]
> @benoitdm-oslandia because this directory is used for outputs created by Processing algorithms and having them in a location which is quite hidden for a normal users is not user-friendly. Hidden directories are not easily accessible from QGIS Browser or open datasource dialogs.

I agree, but this not-user-friendly directory are the best fallback solution as they are not "polluting" the home directory. I  have not checked the code base but is there any env var or qgis setting to handle this output directory? If not it will be nice, IMHO, to have this kind of configuration solution.

**Comment by alexbruy** [comment]
You can change it in the settings.

**Comment by benoitdm-oslandia** [comment]
> You can change it in the settings.

Ok but I would have preferred the folder to be created only when the setting is not set. In my case, the setting is set but I still have the folder create in my home directory. Is there anything you can do?
