### PR TITLE
Fix select by expression

### LINKED ISSUE #62231: [Processing] "Select by Expression" doesn't works with some expressions
### What is the bug or the crash?

Having a point layer and running the "Select by Expression" (`qgis:selectbyexpression`) processing algorithm to select the 10 points having the smallest X coordinate value using the expression `array_find( array_agg( $x, order_by:=$x ), $x ) < 10`, no point feature is selected.

### Steps to reproduce the issue

1. add the layer [random_points.zip](https://github.com/user-attachments/files/20673175/random_points.zip) to a blank new project (EPSG:4326)
2. execute the "Select by expression" processing algorithm with the expression `array_find( array_agg( $x, order_by:=$x ), $x ) < 10`
3. observe that no feature is selected.

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.43.0-Master</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/94f24bb5eb4">94f24bb5eb4</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.13</td></tr><tr><td>Python version</td><td>3.12.10</td></tr><tr><td>GDAL version</td><td>3.12.0dev-1acfddd843</td></tr><tr><td>PROJ version</td><td>9.6.0</td></tr><tr><td>EPSG Registry database version</td><td>v12.004 (2025-03-02)</td></tr><tr><td>GEOS version</td><td>3.13.1-CAPI-1.19.2</td></tr><tr><td>SQLite version</td><td>3.46.1</td></tr><tr><td>PDAL version</td><td>2.8.3</td></tr><tr><td>PostgreSQL client version</td><td>17.3</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.3.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Windows 10 Version 1903</td></tr><tr><td colspan="2"><i>This copy of QGIS writes debugging output.</i></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

The same expression works well with the "Select Features by Expression" map tool and the "Extract by Expression" (`native:extratbyexpression`) processing algorithm.

### PR DESCRIPTION
**Pull request by elpaso**
Layer scope was missing from the expression context

Fix #62231

### CODE REVIEW

**Comment by agiudiceandrea** [comment]
It looks like also changing:

```python
        layer = self.parameterAsVectorLayer(parameters, self.INPUT, context)
[...]
        expression_context = self.createExpressionContext(parameters, context)
```
to:
```python
        layer = self.parameterAsVectorLayer(parameters, self.INPUT, context)
[...]
        expression_context = self.createExpressionContext(parameters, context)
        expression_context.appendScope(layer.createExpressionContextScope())
```

or
```python
        layer = self.parameterAsVectorLayer(parameters, self.INPUT, context)
[...]
        expression_context = self.createExpressionContext(parameters, context)
```
to:
```python
        layer = self.parameterAsVectorLayer(parameters, self.INPUT, context)
        source = self.parameterAsSource(parameters, self.INPUT, context)
[...]
        expression_context = self.createExpressionContext(parameters, context, source)
```

in the processAlgorithm function of the algorithm fixes the issue.

It looks like there are some (C++ and Python) algorithms that use `createExpressionContext(parameters, context)` and other ones that use` createExpressionContext(parameters, context, source)`. Some of the former subsequently add the layer context scope. to the expression context.

Anyway the fix should be backported to release-3_40 branch.

**Comment by elpaso** [comment]
> It looks like also changing:
> 
> ```python
>         layer = self.parameterAsVectorLayer(parameters, self.INPUT, context)
> [...]
>         expression_context = self.createExpressionContext(parameters, context)
> ```
> 
> to:
> 
> ```python
>         layer = self.parameterAsVectorLayer(parameters, self.INPUT, context)
> [...]
>         expression_context = self.createExpressionContext(parameters, context)
>         expression_context.appendScope(layer.createExpressionContextScope())
> ```
> 
> or
> 
> ```python
>         layer = self.parameterAsVectorLayer(parameters, self.INPUT, context)
> [...]
>         expression_context = self.createExpressionContext(parameters, context)
> ```
> 
> to:
> 
> ```python
>         layer = self.parameterAsVectorLayer(parameters, self.INPUT, context)
>         source = self.parameterAsSource(parameters, self.INPUT, context)
> [...]
>         expression_context = self.createExpressionContext(parameters, context, source)
> ```
> 
> in the processAlgorithm function of the algorithm fixes the issue.
> 
> It looks like there are some (C++ and Python) algorithms that use `createExpressionContext(parameters, context)` and other ones that use` createExpressionContext(parameters, context, source)`. Some of the former subsequently add the layer context scope. to the expression context.
> 
> Anyway the fix should be backported to release-3_40 branch.

Yes, I considered the option to add the layer to the context from the algorithm, but in this case I think it's better that QgsVectorLayer adds itself because because there is no use case for client code doing anything different and this also eliminates any risk of errors.

File: src/core/vector/qgsvectorlayer.cpp [hunk 1]
```diff
@@ -572,13 +572,22 @@ void QgsVectorLayer::selectByExpression( const QString &expression, Qgis::Select
...
+  exp.prepare( context );
 
   if ( behavior == Qgis::SelectBehavior::SetSelection || behavior == Qgis::SelectBehavior::AddToSelection )
   {
     QgsFeatureRequest request = QgsFeatureRequest().setFilterExpression( expression )
-                                .setExpressionContext( *context )
-                                .setFlags( Qgis::FeatureRequestFlag::NoGeometry )
-                                .setNoAttributes();
+                                .setExpressionContext( *context );
+    request.setSubsetOfAttributes( exp.referencedColumns(), fields() );
```
Comment (signedav) [inline src/core/vector/qgsvectorlayer.cpp:587]: Is this an additional improvement or needed for the fix?

**Review by signedav — COMMENTED** [review]
Beside the one change I don't understand completely, this makes sense and code looks good.

**Review by nyalldawson — APPROVED** [review]
