### PR TITLE
Fix crash when convertng a curved geometry to curves

### LINKED ISSUE #48045: converttocurves algorithm crashes if fed already curved polygons
### What is the bug or the crash?

The native:converttocurves algorithm crashes if fed already curved polygons

### Steps to reproduce the issue

1. Create a curved feature on a curved polygon.
2. Run the convert to curves algorithm
3. See the crash

Here's a minimal script that does exatly that
```
WKT = 'CurvePolygon (CompoundCurve (CircularString (2613627 1178798, 2613639 1178805, 2613648 1178794),(2613648 1178794, 2613627 1178798)))'

# Create a feature
f = QgsFeature()
f.setGeometry(QgsGeometry.fromWkt(WKT))

# Add it to a memory layer
vl = QgsVectorLayer("CurvePolygon?crs=epsg:2056", "temp", "memory")
vl.dataProvider().addFeature(f)

# Run the algorithm
processing.runAndLoadResults(
    "native:converttocurves",
    {"INPUT": vl, "DISTANCE": 1e-6, "ANGLE": 1e-6, "OUTPUT": "memory:output"}
)
```

### Versions

Happens on both 3.22.5 and 3.24.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Stack trace (3.22)
```
Crash ID: [ffc5f2890057b6ef24820e31ef351f62da962daa](https://github.com/qgis/QGIS/search?q=ffc5f2890057b6ef24820e31ef351f62da962daa&type=Issues)


Stack Trace


QgsLineString::pointN qgslinestring.cpp:974
lineToCurve qgsinternalgeometryengine.cpp:1399
convertGeometryToCurves qgsinternalgeometryengine.cpp:1531
QgsInternalGeometryEngine::convertToCurves qgsinternalgeometryengine.cpp:1575
QgsGeometry::convertToCurves qgsgeometry.cpp:2250
QgsConvertToCurvesAlgorithm::processFeature qgsalgorithmconverttocurves.cpp:115
QgsProcessingFeatureBasedAlgorithm::processAlgorithm qgsprocessingalgorithm.cpp:1039
QgsProcessingAlgorithm::runPrepared qgsprocessingalgorithm.cpp:533
QgsProcessingAlgorithm::run qgsprocessingalgorithm.cpp:462
PyInit__core :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyEval_GetBuiltins :
PyEval_GetBuiltins :
PyEval_EvalFrameDefault :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit__gui :
QWidget::event :
QFrame::event :
QAbstractScrollArea::event :
PyInit__gui :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:514
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:514
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processKeyEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1667
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.22.5-Bia?owie?a
QGIS code revision: c27231782f
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.2
Running against GDAL: 3.4.2



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043
```

Stack trace (3.24)
```
Python Stack Trace
Windows fatal exception: access violation

Current thread 0x00003f48 (most recent call first):
  File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\gui\AlgorithmExecutor.py", line 72 in execute
    results, ok = alg.run(parameters, context, feedback, {}, False)
  File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\core\Processing.py", line 187 in runAlgorithm
    ret, results = execute(alg, parameters, context, feedback, catch_exceptions=False)
  File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\tools\general.py", line 151 in runAndLoadResults
    return Processing.runAlgorithm(alg, parameters=parameters, onFinish=handleAlgorithmResults, feedback=feedback,
  File "C:\OSGeo4W\apps\Python39\lib\code.py", line 90 in runcode
    exec(code, self.locals)
  File "C:\OSGeo4W\apps\Python39\lib\code.py", line 74 in runsource
    self.runcode(code)
  File "C:\OSGeo4W/apps/qgis/./python\console\console_sci.py", line 559 in runsource
    return super(ShellScintilla, self).runsource(source, filename, symbol)
  File "C:\OSGeo4W/apps/qgis/./python\console\console_sci.py", line 526 in runCommand
    more = self.runsource(src)
  File "C:\OSGeo4W/apps/qgis/./python\console\console_sci.py", line 506 in entered
    self.runCommand(self.text())
  File "C:\OSGeo4W/apps/qgis/./python\console\console_sci.py", line 344 in keyPressEvent
    self.entered()


Stack Trace
No stack trace is available.


QGIS Info
QGIS Version: 3.24.1-Tisler
QGIS code revision: 5709b82461
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.2
Running against GDAL: 3.4.2



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

```

### PR DESCRIPTION
**Pull request by nyalldawson**
Also cleanup outputs of conversion to curve

Fixes #48045

### CODE REVIEW

**Review by alexbruy — APPROVED** [review]

**Review by lbartoletti — APPROVED** [review]

File: src/core/geometry/qgsinternalgeometryengine.cpp [hunk 1]
```diff
@@ -1332,208 +1332,252 @@ QVector<QgsPointXY> QgsInternalGeometryEngine::randomPointsInPolygon( const QgsG
...
+    std::unique_ptr< QgsCompoundCurve > out = std::make_unique< QgsCompoundCurve >();
+    const QgsCompoundCurve *in = qgsgeometry_cast< const QgsCompoundCurve * >( curve );
+    for ( int i = 0; i < in->nCurves(); i ++ )
+    {
+      std::unique_ptr< QgsCurve > processed = lineToCurve( in->curveAt( i ), distanceTolerance, pointSpacingAngleTolerance );
+      if ( processed )
+      {
+        if ( QgsWkbTypes::flatType( processed->simplifiedTypeRef()->wkbType() ) == QgsWkbTypes::LineString )
+        {
+          // don't add compound curve as a component of compound curve
```
Comment (rouault) [inline src/core/geometry/qgsinternalgeometryengine.cpp:1356]: the comment doesn't seem right, or the above test isn't right

**Review by rouault — COMMENTED** [review]
perhaps add a test case representative of the bug report ?

**Comment by nyalldawson** [comment]
@rouault 
> perhaps add a test case representative of the bug report ?

There's one copied straight from the ticket :laughing:

**Review by rouault — APPROVED** [review]
