### PR TITLE
[3d] Tessellator fixes + culling mode configuration for 3D polygons

### LINKED ISSUE #17619: Processing in a standalone QGIS app
Author Name: **Joshua Arnott** (@snorfalorpagus)
Original Redmine Issue: [8955](https://issues.qgis.org/issues/8955)

Redmine category:processing/core
Assignee: Victor Olaya

---
Currently it is not possible to use the processing module in a standalone QGIS application/script.

This is due in part to a dependence on the iface object, which is only available when running as a plugin within QGIS. In addition to this there will be issues with calling external programs/scripts using subprocess.Popen related to paths.

I've attached an example script (processing_standalone.py) which uses a mock iface object to allow the plugin to load. This can be used to run the 'qgis:*' algorithms, as they don't have any external dependencies. More work is needed to get things working with GRASS and SAGA, etc.

---

- [processing_standalone.py](https://issues.qgis.org/attachments/download/6411/processing_standalone.py) (Joshua Arnott)

### PR DESCRIPTION
**Pull request by wonder-sk**
- missing vertical walls since a recent tessellator crash fix (fixes #17604)
- choice of the culling mode - no culling / back face / front face (fixes #17619)
- more unit tests for tessellator

### CODE REVIEW

File: src/3d/qgs3dutils.cpp [hunk 1]
```diff
@@ -82,6 +82,30 @@ AltitudeBinding Qgs3DUtils::altBindingFromString( const QString &str )
...
 
+QString Qgs3DUtils::cullingModeToString( Qt3DRender::QCullFace::CullingMode mode )
+{
+  switch ( mode )
+  {
+    case Qt3DRender::QCullFace::NoCulling: return QStringLiteral( "no-culling" );
+    case Qt3DRender::QCullFace::Front: return QStringLiteral( "front" );
+    case Qt3DRender::QCullFace::Back: return QStringLiteral( "back" );
+    case Qt3DRender::QCullFace::FrontAndBack: return QStringLiteral( "front-and-back" );
+    default: return QString();
```
Comment (nyalldawson) [inline src/3d/qgs3dutils.cpp]: Can we drop this default and return QString() outside the switch? I think we should avoid using defaults wherever possible so that we get the compiler warnings when the enum changes.

File: src/3d/symbols/qgspolygon3dsymbol_p.cpp [hunk 2]
```diff
@@ -103,9 +106,24 @@ void QgsPolygon3DSymbolEntity::addEntityForNotSelectedPolygons( const Qgs3DMapSe
...
 }
 
+
 Qt3DExtras::QPhongMaterial *QgsPolygon3DSymbolEntity::material( const QgsPolygon3DSymbol &symbol ) const
 {
   Qt3DExtras::QPhongMaterial *material = new Qt3DExtras::QPhongMaterial;
+
+  // front/back side culling
+  auto techniques = material->effect()->techniques();
+  for ( auto tit = techniques.begin(); tit != techniques.end(); ++tit )
```
Comment (nyalldawson) [inline src/3d/symbols/qgspolygon3dsymbol_p.cpp]: constBegin/constEnd
