### PR TITLE
Fix missing rubber bands when measuring

### LINKED ISSUE #34630: No rubber band using 3D measurement tool
**Describe the bug**
When using 3D measurement tool, rubber band which represents a path from the last point you snapped to the current position doesn't appear. 

**How to Reproduce**

3d

**QGIS and OS versions**

QGIS version
3.12.0-București
QGIS code revision
cd141490ec
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.1
Running against PROJ
Rel. 6.3.1, February 10th, 2020
OS Version
Windows 10 (10.0)
Active python plugins
openlayers_plugin; 
pluginbuilder3; 
QuickOSM; 
QuickWKT; 
db_manager; 
MetaSearch; 
processing

### PR DESCRIPTION
**Pull request by wonder-sk**
Fixes #34630

This fix also introduces a helper class QgsRubberBand3D to handle rubber bands in 3D, similar to how QgsRubberBand is used in 2D map canvas.

Avoids addition of a temporary vector layer only used for measurement purposes, which was confusing. Also fixes unreported crash when user removed the measurement layer after it was added and the tool was used again.

### CODE REVIEW

File: src/3d/qgsrubberband3d.cpp [hunk 1]
```diff
@@ -0,0 +1,121 @@
...
+  mGeomRenderer->setGeometry( mGeometry );
+  mGeomRenderer->setPrimitiveRestartEnabled( true );
+  mGeomRenderer->setRestartIndexValue( 0 );
+
+  mEntity->addComponent( mGeomRenderer );
+
+  mLineMaterial = new QgsLineMaterial;
+  mLineMaterial->setLineWidth( 3 );
+  mLineMaterial->setLineColor( Qt::red );
+  mLineMaterial->setViewportSize( QSize( 200, 200 ) ); // TODO: based on viewport size!
```
Comment (nyalldawson) [inline src/3d/qgsrubberband3d.cpp:60]: is this a TODO before merge?

**Review by nyalldawson — APPROVED** [review]
Great move, that temporary layer was certainly not great UX!

File: src/3d/qgsrubberband3d.cpp (hunk 1 above)
Comment (wonder-sk) [reply src/3d/qgsrubberband3d.cpp]: yea, addressed in a64ba95
