### PR TITLE
Measure tool copy coordinates

### LINKED ISSUE #50292: Measure tool - copy coordinates
### Feature description

I want to find the coordinates of a bunch of points using measurements on a georeferenced image. For instance, 13.3 m due north of a corner of a road. I can use the measure tool to find the spot, and see the coordinates along the bottom of the QGIS window. But I can't then move the mouse to enter the coordinates in a spreadsheet without changing the coordinates. I can't use the right-click feature to copy coordinates because the measure tool is active. Do I really have to hand-write the coordinates on paper then type them into the spreadsheet?  I'd like a mouse button or Ctrl-key that copies the coordinates into the clipboard while using the measure tool.

### Additional context

I'm using QGIS 3.22.4-Biatowieza on Linux Mint 23.

### LINKED ISSUE #52532: Measure dialog discards data points when changing projection
### What is the bug or the crash?

When the user switches from Cartesian to Ellipsoid mode, or if they change the CRS, the Measure Dialog discards the last clicked point.

missingPoints

### Steps to reproduce the issue

- Activate the measure tool (Distance mode)
- Click on two points (The dialog displays two point + the temporary one)
- Switch from Cartesian to Ellipsoid (or vice versa)
- The last clicked point dissapears

### Versions

QGIS version | 3.31.0-Master | QGIS code revision | ecce061fb5
-- | -- | -- | -- 
Qt version | 5.15.3
Python version | 3.10.6
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.1 LTS
  |    
This copy of QGIS writes debugging output.
  |  
Active Python plugins
quick_map_services | 0.19.33
MemoryLayerSaver | 4.0.4
MetaSearch | 0.3.6
processing | 2.12.99
db_manager | 0.1.20
grassprovider | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by YoannQDQ**
- Fixes #50292
- Fixes #52532

## Description

This PR extend the `QgsMeasureDialog` with X and Y coordinates.
- Adds X an Y columns
- Adds a first row in the table that contains only the coordinates (no distance)
- Display a message when the copy has succeeded
- Adds the `Copy all` action in a context menu in the table
- Fixes some bugs when changing settings while measuring

new_measure_tool

Additional settings (separator, include header) control the "Copy All" button behavior. This can be used to copy the data (X, Y and dist) to a raw csv, to an excel table etc.

measure_tool_copy_settings

### CODE REVIEW

**Comment by nyalldawson** [comment]
@YoannQDQ what do you think about removing the "show coordinates" check and just **always** showing these? 

I'd love your thoughts too @nirvn

**Comment by nirvn** [comment]
+1 to always show, we have the empty space available at all time, we might as well make use of it.

File: src/app/options/qgsoptions.cpp [hunk 1]
```diff
@@ -642,16 +642,33 @@ QgsOptions::QgsOptions( QWidget *parent, Qt::WindowFlags fl, const QList<QgsOpti
...
-  {
-    mKeepBaseUnitCheckBox->setChecked( true );
-  }
+  mKeepBaseUnitCheckBox->setChecked( baseUnit );
+
+  mPlanimetricMeasurementsComboBox->setChecked( mSettings->value( QStringLiteral( "measure/planimetric" ), false, QgsSettings::Core ).toBool() );
+
+  // set the measure tool copy settings
+  connect( mSeparatorOther, &QRadioButton::toggled, mSeparatorCustom, &QLineEdit::setEnabled );
+  bool includeHeader = mSettings->value( QStringLiteral( "qgis/measure/clipboard_header" ), false ).toBool();
```
Comment (nirvn) [inline src/app/options/qgsoptions.cpp:651]: Could you make sure that all settings you are introducing here rely on the new settings framework (here's an example: https://github.com/qgis/QGIS/blob/master/src/app/qgsidentifyresultsdialog.cpp#L102)

File: src/app/qgsmeasuredialog.cpp [hunk 2]
```diff
@@ -56,9 +57,15 @@ QgsMeasureDialog::QgsMeasureDialog( QgsMeasureTool *tool, Qt::WindowFlags f )
 
   if ( !mMeasureArea )
   {
+    QAction *copyAction = new QAction( tr( "Copy &All" ), this );
```
Comment (nirvn) [inline src/app/qgsmeasuredialog.cpp:60]: Why not calling it "copy" since there are not alternatives to copying all. Makes the button narrower and fits a bit better alongside the other 1-word buttons.

Comment (YoannQDQ) [reply src/app/qgsmeasuredialog.cpp:60]: Good point. Will do!

File: src/app/options/qgsoptions.cpp (hunk 1 above)
Comment (YoannQDQ) [reply src/app/options/qgsoptions.cpp:651]: Sure.

Comment (YoannQDQ) [reply src/app/options/qgsoptions.cpp:651]: Actually `qgis/measure/xxx` keys are used all over the place, so I think it might be out of scope for this PR. The example you gave is really QWebView-oriented.

IIUC, the new settings framework, introduced by @3nids relies on declaring settings entries as `QgsSettingsEntryBool|String|Whatever` 
https://github.com/qgis/QGIS/blob/47d88e94871bac8deaa2026aa6d0057fd862ff81/src/app/elevation/qgselevationprofilewidget.cpp#L59-L61

Comment (nirvn) [reply src/app/options/qgsoptions.cpp:652]: @YoannQDQ , I'm not suggesting you migrate the pre-existing settings keys in this PR :) however I do think any *newly introduced* settings should use the new framework (e.g. src/app/gps makes use of strings, booleans, etc.).

If we keep adding old style settings in new code, we're just increasing the migration burden down the road :)

Comment (YoannQDQ) [reply src/app/options/qgsoptions.cpp:652]: Fair enough. I'll do it.

Comment (3nids) [reply src/app/options/qgsoptions.cpp:652]: yes, please.
@YoannQDQ can you create a new node directly in QgsSettingsTree, call it `measure` maybe? (having things in `qgis` is not really meaningful). Also, as written in docs, please use kebab-case. Cheers

Comment (YoannQDQ) [reply src/app/options/qgsoptions.cpp]: Done

**Review by nirvn — APPROVED** [review]
Thanks, good work and super useful.

**Comment by agiudiceandrea** [comment]
Hi @YoannQDQ, please see https://github.com/qgis/QGIS/issues/57138.
