### PR TITLE
"Sticky" Decorations

### LINKED ISSUE #48518: Decorations (Scale bar, Title Label, etc.) are not sticking but move with chart on zooming/panning
### What is the bug or the crash?

When zoom in/out or panning the map, decorations are moving with the chart and QGIS needs to redraw them in the original position every single time.

### Steps to reproduce the issue

Use _View > Decorations > Tile Label_ to create a title which is permanently displayed on the map canvas. 

### Versions

Version 3.24.x and earlier

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by YoannQDQ**
- Fixes #48518

## Description

- Add a `hasFixedMapPosition` member function to `QgsMapDecoration`
- "Non Fixed" decorations are no longer rendered directly on the map canvas, but are instead rendered on a transparent overlay

### Demonstration

decorations

_Note: A similar approach could be applied to #25290_

### CODE REVIEW

File: src/app/decorations/qgsdecorationoverlay.cpp [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+  QgsRenderContext context = QgsRenderContext::fromMapSettings( QgisApp::instance()->mapCanvas()->mapSettings() );
+  context.setPainter( &p );
+
+  for ( QgsMapDecoration *item : QgisApp::instance()->activeDecorations() )
+  {
+    // Do not render decorations with fixed map positionn they are rendered directly on the map canvas
+    if ( item->hasFixedMapPosition() )
+      continue;
+    item->render( QgisApp::instance()->mapCanvas()->mapSettings(), context );
+  }
```
Comment (nyalldawson) [inline src/app/decorations/qgsdecorationoverlay.cpp:53]: Let's save some unnecessary work when no decorations are around:

```suggestion
  const QList< QgsMapDecoration* > decorations = QgisApp::instance()->activeDecorations();
  if ( decorations.empty() )
    return;
    
  QPainter p( this );

  QgsRenderContext context = QgsRenderContext::fromMapSettings( QgisApp::instance()->mapCanvas()->mapSettings() );
  context.setPainter( &p );

  for ( QgsMapDecoration *item : decorations )
  {
    // Do not render decorations with fixed map positionn they are rendered directly on the map canvas
    if ( item->hasFixedMapPosition() )
      continue;
    item->render( QgisApp::instance()->mapCanvas()->mapSettings(), context );
  }
```

**Review by nyalldawson — COMMENTED** [review]
Nice approach!

**Review by nyalldawson — APPROVED** [review]
