### PR TITLE
Fix bookmarks manager model signals emitted twice

### LINKED ISSUE #56493: Spatial Bookmark Manager crash
### What is the bug or the crash?

A crash happened when using Spatial Bookmark Manager.

## User Feedback

1 open  Spatial Bookmark Manager,
2 then,add 6 bookmarks,
3 after that, delete the 4 and 5 bookmarks at the same time,
4 then, add a new bookmark.
5 oops, may cause a crash!

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00006738 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QSortFilterProxyModel::parent :
QSortFilterProxyModel::mapToSource :
QSortFilterProxyModel::flags :
QModelIndex::flags :
QAbstractItemView::focusInEvent :
QWidget::event :
QFrame::event :
QAbstractScrollArea::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::setFocusWidget :
QWidget::setFocus :
QApplication::setActiveWindow :
QApplicationPrivate::notifyActiveWindowChange :
QGuiApplicationPrivate::processActivatedEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.4-Firenze
QGIS code revision: fd0fb72ab3
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Versions

**QGIS Info**
QGIS Version: 3.28.4-Firenze
QGIS code revision: fd0fb72ab3
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
rows inserted/added was fired twice (once by the manager and once by the model), confusing the proxy model.

Also count was wrong by 1 in beginInsertRows( parent, oldCount, oldCount + count ) and beginRemoveRows, but now these two calls have been removed completely.

Fix #56493

### CODE REVIEW

File: src/core/qgsbookmarkmodel.cpp [hunk 1]
```diff
@@ -236,14 +234,11 @@ bool QgsBookmarkManagerModel::insertRows( int, int count, const QModelIndex &par
...
     result &= res;
   }
-  endInsertRows();
   return result;
 }
 
-bool QgsBookmarkManagerModel::removeRows( int row, int count, const QModelIndex &parent )
+bool QgsBookmarkManagerModel::removeRows( int row, int count, const QModelIndex & )
 {
-  beginRemoveRows( parent, row, row + count );
```
Comment (nyalldawson) [inline src/core/qgsbookmarkmodel.cpp:245]: I don't understand this change, doesn't it break the model?

Comment (elpaso) [reply src/core/qgsbookmarkmodel.cpp:245]: On the contrary it fixes it: beginRemoveRows and all other mandatory signals are already called by 
https://github.com/qgis/QGIS/blob/master/src/core/qgsbookmarkmodel.cpp#L29
https://github.com/qgis/QGIS/blob/master/src/core/qgsbookmarkmanager.cpp#L169
https://github.com/qgis/QGIS/blob/master/src/core/qgsbookmarkmodel.cpp#L294
https://github.com/qgis/QGIS/blob/master/src/core/qgsbookmarkmanager.cpp#L169

The issue here was that beingRemoveRows was called twice before calling (twice again) endRemoveRows, the same happened to the other signals.

Comment (nyalldawson) [reply src/core/qgsbookmarkmodel.cpp:245]: Ah, fair enough!

**Review by nyalldawson — APPROVED** [review]
