### PR TITLE
DXF export: fix crash on some MultiPolygon geometries when offset != 0 (fixes #46245)

### LINKED ISSUE #46245: Crash exporting dxf using "Symbol layer symbology"
[Crash.zip](https://github.com/qgis/QGIS/files/7685281/Crash.zip)
### What is the bug or the crash?

I'm trying exporting dxf. If I do with a small vieport size (200mx200m) everything goes well. If I try with a bigger size (2km by 2km) qgis crashes and the dxf has been created is corrupt and you cannot open.

I see that if I export a big data Qgis can have some problem, but alert on exporting, like a warning, would be better, in order to reduce the dimension. It ould be interesting unsterstand if it is issue of RAM, processor, or whatever.

**Please find attached source file with data.**

### Steps to reproduce the issue

1. File
2. Export as dxf
3. crashes

### Versions

Versione di QGIS
3.16.14-Hannover
Revisione codice QGIS
42791986
Compilato con Qt
5.15.2
Esecuzione con Qt
5.15.2
Compilato con GDAL/OGR
3.4.0
Esecuzione con GDAL/OGR
3.4.0
Compilato con GEOS
3.10.0-CAPI-1.16.0
Esecuzione con GEOS
3.10.0-CAPI-1.16.0
Compilato su SQLite
3.35.2
In esecuzione su SQLite
3.35.2
Versione client PostgreSQL
13.0
Versione SpatiaLite
5.0.1
Versione QWT
6.1.3
Versione QScintilla2
2.11.5
Compilato con PROJ
8.2.0
Esecuzione con PROJ
Rel. 8.2.0, November 1st, 2021
Versione SO
Windows 10 Version 2009
Attiva python plugin
autoSaver; 
BivariateLegend; 
changeDataSource; 
clusterpoints; 
concavehull; 
DataPlotly; 
EasyCustomLabeling; 
FeatureGridCreator; 
FreehandRasterGeoreferencer; 
GeoCoding; 
GroupStats; 
HCMGIS; 
isochrones; 
LAStools; 
layertilesmapcanvas; 
localmaxfilter; 
lockzoom; 
mmqgis; 
MultipleLayerSelection; 
ntv2_transformations; 
numericalDigitize; 
OnlineRoutingMapper; 
PointConnector; 
processing_wbt; 
qgis-maptiler-plugin; 
Qgis2threejs; 
QNEAT3; 
QPackage; 
qProf; 
quick_map_services; 
realcentroid; 
shapefile_encoding_fixer; 
shapetools; 
spatial_query_with_values; 
spline; 
SpreadsheetLayers; 
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

File: src/core/dxf/qgsdxfexport.cpp [hunk 1]
```diff
@@ -1682,39 +1668,31 @@ void QgsDxfExport::addFeature( QgsSymbolRenderContext &ctx, const QgsCoordinateT
...
-          for ( int j = 0; j < polygon->numInteriorRings(); j++ )
-            writePolyline( *polygon->interiorRing( j ), layer, lineStyleName, penColor, width );
+              writePolyline( *polygon->exteriorRing(), layer, lineStyleName, penColor, width );
+              for ( int j = 0; j < polygon->numInteriorRings(); j++ )
+                writePolyline( *polygon->interiorRing( j ), layer, lineStyleName, penColor, width );
+            }
+          }
+          else
+          {
+            Q_ASSERT( gc );
```
Comment (m-kuhn) [inline src/core/dxf/qgsdxfexport.cpp:1694]: That will always fail (so is equal to the previous check directly after the cast?

Comment (rouault) [reply src/core/dxf/qgsdxfexport.cpp]: I've moved it just after the cast

File: src/core/dxf/qgsdxfexport.cpp [hunk 2]
```diff
@@ -1682,39 +1667,28 @@ void QgsDxfExport::addFeature( QgsSymbolRenderContext &ctx, const QgsCoordinateT
...
-        Q_ASSERT( gc );
-
-        for ( int i = 0; i < gc->numGeometries(); i++ )
+        else
         {
-          const QgsCurvePolygon *polygon = dynamic_cast<const QgsCurvePolygon *>( gc->geometryN( i ) );
-          Q_ASSERT( polygon );
+          const QgsGeometryCollection *gc = dynamic_cast<const QgsGeometryCollection *>( sourceGeom );
+          Q_ASSERT( gc );
+          if ( gc )
```
Comment (m-kuhn) [inline src/core/dxf/qgsdxfexport.cpp:1680]: So ... now I'm wondering if we need this check at all, at this point we *should* be sure we have a gc

Comment (rouault) [reply src/core/dxf/qgsdxfexport.cpp:1680]: > at this point we should be sure we have a gc

I think so, but can't swear :-)  The current code should be safe enough: not crashing in production builds, and asserting in debug builds so we can investigate what's going on

Comment (m-kuhn) [reply src/core/dxf/qgsdxfexport.cpp:1680]: Makes sense. I always lived by the rule after an assert ub is allowed in prod. But not sure that's a common understanding 🤪

**Review by m-kuhn — APPROVED** [review]
Thanks
