### PR TITLE
Handle conditional visibility of data defined size legend nodes

### LINKED ISSUE #50301: Map Composer - Legend does not display my layer (when using Only show items inside linked map with Data-defined Size Legend)
### What is the bug or the crash?

When using a point layer with the point size defined by attributes (to make proportional circles), if I use the `Only show items inside linked map` option, my layer disappear from the legend even if the layer is displayed on the map.

Before checking `Only show items inside linked map`

image

After checking `Only show items inside linked map`

image

### Steps to reproduce the issue

1. Add a point layer 
2. Specify a style for the point layer where the size is defined by attributes (using the assistant)
3. In map Composer add a map and a legend
4. Check Only show items inside linked map

### Versions

3.26.3.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by uclaros**
## Description
This PR Fixes #50301

~The solution is a little hacky.~

~Would it make more sense to have `QgsDataDefinedSizeLegendNode` class also handle the rendering of the data defined size label and also individual classes, instead of having separate `QgsSymbolLegendNode`s for them?~
 
Solution is no longer hacky, https://github.com/qgis/QGIS/pull/57461#discussion_r1609284374 was implemented

### CODE REVIEW

File: src/core/qgsdatadefinedsizelegend.cpp [hunk 1]
```diff
@@ -126,7 +126,8 @@ QgsLegendSymbolList QgsDataDefinedSizeLegend::legendSymbolList() const
   QgsLegendSymbolList lst;
   if ( !mTitleLabel.isEmpty() )
   {
-    QgsLegendSymbolItem title( nullptr, mTitleLabel, QString() );
+    // we're abusing the ruleKey field here so we can later identify the resulting legend nodes as data defined size related
+    QgsLegendSymbolItem title( nullptr, mTitleLabel, QStringLiteral( "data-defined-size" ) );
```
Comment (nyalldawson) [inline src/core/qgsdatadefinedsizelegend.cpp:130]: instead of the abuse, how about we add a QMap< int, QVariant > userData to QgsLegendSymbolItem, and adapt QgsSymbolLegendNode::data to return those values for unknown roles.

Comment (uclaros) [reply src/core/qgsdatadefinedsizelegend.cpp:130]: We could have a new role in `QgsLayerTreeModelLegendNode::CustomRole` for that.
But, why a `QMap< int, QVariant >`?  What would you store there (in this case and/or in future uses of it)?

Comment (nyalldawson) [reply src/core/qgsdatadefinedsizelegend.cpp:130]: > We could have a new role in QgsLayerTreeModelLegendNode::CustomRole for that, instead of handling all unknown roles.

That also works. I was just thinking ahead if allowing custom roles in QgsLegendSymbolItem would also be useful in future.

> But, why a QMap< int, QVariant >? What would you store there (in this case and/or in future uses of it)?

The int keys would correspond to a role from QgsLayerTreeModelLegendNode (either public or private). I'd find a QMap approach slightly preferable to having separate members for every property we decide to add in future.

**Review by wonder-sk — APPROVED** [review]
