### PR TITLE
Fix various issues with application of raster styles from QML-files

### LINKED ISSUE #26701: 2.18 Raster Style qml's not applying correctly in QGIS 3.4
Author Name: **Sarah Popov** (@popovs)
Original Redmine Issue: [18869](https://issues.qgis.org/issues/18869)
Affected QGIS version: 3.4.0
Redmine category:symbology

---
New Description: After loading a .qml raster layer style in QGIS 3.0,3.2,3.4 that was created in 2.18, the raster style changes. However, upon clicking "Apply" or "OK", raster style reverts to the default color ramp loaded. See attached gif for this behavior. However if before you press apply you change your min/max value settings to user defined it will work. Also if the .qml's classificationMinMaxOrigin= is edited from "MinMaxFullExtentEstimated" or "CumulativeCutFullExtentEstimated"
to "Unknown" the resulting .qml works.

Old Description:
After loading a premade .qml raster layer style, the raster style changes. However, upon clicking "Apply" or "OK", raster style reverts to the default color ramp loaded. See attached gif for this behavior. 

---

- [raster styles bug.gif](https://issues.qgis.org/attachments/download/12653/raster%20styles%20bug.gif) (Sarah Popov)
- [raster style issue.JPG](https://issues.qgis.org/attachments/download/13640/raster%20style%20issue.JPG) (Bas wein)
- [Broken-Slope_Classes_Soil_Survey.qml](https://issues.qgis.org/attachments/download/13643/Broken-Slope_Classes_Soil_Survey.qml) (Bas wein)
- [Fixed-Slope_Classes_Soil_Survey.qml](https://issues.qgis.org/attachments/download/13644/Fixed-Slope_Classes_Soil_Survey.qml) (Bas wein)

### LINKED ISSUE #28229: Error on  apply qml style for a raster layer in 3.4.1 and Master 0ea86bf0a5
Author Name: **Antonio Viscomi** (@Antoviscomi)
Original Redmine Issue: [20409](https://issues.qgis.org/issues/20409)
Affected QGIS version: 3.4.1
Redmine category:symbology

---
*New description:*

After loading a saved QML style, this changes to a different one when clicking on "apply". Data, style and screencast attached.

*Old description:*
in 2.18.25 it works fine with the same data and qml
in 3.4.1 and Master 0ea86bf0a5 it don't works
I attach a screencast, data and qml file

---

- [qml_style.7z](https://issues.qgis.org/attachments/download/13712/qml_style.7z) (Antonio Viscomi)
- [qml_style2.avi](https://issues.qgis.org/attachments/download/13715/qml_style2.avi) (Antonio Viscomi)
- [sl_raster_rec_350.qml](https://issues.qgis.org/attachments/download/13716/sl_raster_rec_350.qml) (Antonio Viscomi)

### LINKED ISSUE #28926: Pseudocolour classification from QGIS 2.x qml is deleted by the 3.x layer properties dialog
Author Name: **Alister Hood** (@AlisterH)
Original Redmine Issue: [21108](https://issues.qgis.org/issues/21108)
Affected QGIS version: 3.4.4
Redmine category:symbology

---
Load the layer Matteo posted at #26046.
The symbology is applied correctly.
Open layer properties (you don't even have to go to the symbology tab) and click apply or OK, and the symbology will be lost!
Load the qml again from layer properties>symbology.  The symbology is loaded correctly, but lost on apply or OK.
Load the qml again from layer properties>symbology, then edit one of the values (you don't have to actually change it, just click it to edit, then click out of it).  The symbology is not lost on apply or OK.  (Save as a new qml and that won't have the same issues - woohoo - a workaround!).

Yes, this issue is relatively minor, but I imagine it'll cause a lot more headaches as LTS users start to move to 3.x.
It occurs in QGIS 3.4.4 and I believe all earlier versions of 3.x.

### LINKED ISSUE #29427: QGIS fails to apply style file to rasters
Author Name: **Luís de Sousa** (Luís de Sousa)
Original Redmine Issue: [21611](https://issues.qgis.org/issues/21611)
Affected QGIS version: 3.6.1
Redmine category:symbology

---
I need have a number of .qml style files that I need to apply on raster maps. These .qml files were created with QGis itself, here is an example:
https://files.isric.org/soilgrids/legends/ORCDRC.qml

In QGis 3.4 I apply this style by accessing the layer context menu, then following _Properties_ -> _Symbology_ -> _Style_ and selecting the correct .qml file. While the _Properties_ menu is still on the map canvas shows the style correctly applied (Figure 1). But when I click OK and the _Properties_ dialogue closes the layer disappears (F1gure 2). If I open the _Properties_ dialogue again no style is displayed. 

Any cartograms (layouts) created with this layer are also affected.

---

- [QGis_Styles02.png](https://issues.qgis.org/attachments/download/14619/QGis_Styles02.png) (Luís de Sousa)
- [QGis_Styles01.png](https://issues.qgis.org/attachments/download/14620/QGis_Styles01.png) (Luís de Sousa)

---

Related issue(s): #29695 (duplicates)
Redmine related issue(s): [21880](https://issues.qgis.org/issues/21880)

---

### PR DESCRIPTION
**Pull request by iona5**
## Description

This PR fixes various issues with the application of styles from QML-files  to raster layers. The general behavior is that a style is loaded from a QML with a colormap. Then this style seems to be show up OK in the canvas, but the actual color map assignment is sometimes wrong, and when you hit apply a wrong style is actually applied or the color scheme reverts back to a default one.

An example of this behavior (using ESACCI-LC data from http://maps.elie.ucl.ac.be/CCI/viewer/download.php)

rasterstyle_issue

This behavior is described in issues
* #29427
* #26701
* #28229
* #28926

Two major reasons for this behavior are probably the culprits:

### applying a color ramp overwrites an already set colormap

When the QgsColorRampShaderwidget is populated by data from a QgsColorRampShader, the colormapTreeWidget is filled first (containing specific value->color assignments). After that it is checked if the shader has a colorramp and if it has none the default colorramp is applied. The problem is that this in the end emits colorRampChanged() which in turn repopulates the colorrampTreeWidget with new colors from the set colorramp (in this case the default one) overwriting the ones from the applied shader. 

**Fix:** populate the colormap *after* the color ramp is applied. (7368e7f7ec)

### QgsColorRampShaderWidget::applyColorRamp() relies on valid mMin and mMax

A second problem is that the function QgsColorRampShaderWidget::applyColorRamp() assumes that the member variables mMin and mMax are already set when calculating new colors for the colormap. This is not necessarily the case as when a QgsSingleBandPseudoColorRendererWidget is populated by a QgsSingleBandPseudoColorRenderer the min/max form fields are set *after* the color ramp shader is applied. Then the colors for all the entries in the colormap are picked with a nan-value.

**Fix:**
  * populate the min/and max fields in QgsSingleBandPseudoColorRendererWidget before applying the color ramp (5b817145ca)
  * to prevent future problems with unset mMin/mMax in QgsColorRampShaderWidget, as a fallback the color map is created by the min and max values of the actual values in the color map if mMin or mMax are nan (2d986f6)

This PR 

 - Fixes #28229
 - Fixes #28926
 - Fixes #29427
 - May also fix #26701

### CODE REVIEW

File: src/gui/raster/qgscolorrampshaderwidget.h [hunk 1]
```diff
@@ -102,6 +102,8 @@ class GUI_EXPORT QgsColorRampShaderWidget: public QWidget, protected Ui::QgsColo
   protected:
     //! Populates color ramp tree from ramp items
     void populateColormapTreeWidget( const QList<QgsColorRampShader::ColorRampItem> &colorRampItems );
+    //! Extracts the minimal and maximal value from the colormapTreeWidget
+    void colormapMinMax( double &min, double &max ) const SIP_SKIP;
```
Comment (m-kuhn) [inline src/gui/raster/qgscolorrampshaderwidget.h:106]: Can you move this to private?

**Comment by m-kuhn** [comment]
Only one comment and it should be ready to merge. Thank you very much!

**Comment by iona5** [comment]
> 
> 
> Only one comment and it should be ready to merge. Thank you very much!

thanks, will do! :)

**Review by m-kuhn — APPROVED** [review]
