### PR TITLE
PG views: be tolerant for unsupported field type ...

### LINKED ISSUE #31799: UI: PostGIS layer error message not helpful, disappears and shouldn't happen
Trying to generate a slow postgis layer to reproduce #31635.

In PostGIS-enabled DB:
```
create table test_table as (select (ST_DumpPoints(ST_GeneratePoints(ST_Expand('SRID=4326;POINT(0 0)'::geometry,90),10))).geom, random());  
create view test_view as (select geom, random+coalesce(pg_sleep(0.1)::int,0)  g from test_table);  

15:13:11 [gis] > select * from test_view ;
┌────────────────────────────────────────────────────┬─────────────────────┐
│                        geom                        │          g          │
├────────────────────────────────────────────────────┼─────────────────────┤
│ 0101000020E610000000E474FFFFA941C05DE2B4AF24D142C0 │  0.6291001356093986 │
│ 0101000020E610000026BD30DC220734C04F03C2ADB6B141C0 │  0.5626557368133867 │
│ 0101000020E61000003766CF73210846C080D87D9EDF1A34C0 │ 0.09838422078965436 │
│ 0101000020E61000000ECC1C6F5AA8534070661A75CD331440 │ 0.16004865906309007 │
│ 0101000020E610000000DFEFDF588A0240CB3D3A67B7DA5240 │  0.3205073746002043 │
│ 0101000020E6100000A077D1AD2CF9FEBF382B10F522E22D40 │ 0.23407737790354943 │
│ 0101000020E6100000F20B3DABC02E40C08FC8DF2C55A84F40 │  0.9812978427793695 │
│ 0101000020E6100000C91FCDD123744140DE96041BCEEB4340 │  0.6411738976976515 │
│ 0101000020E6100000CA5754AEFFFB524000FAFBCCCC5556C0 │  0.5346711048059873 │
│ 0101000020E610000056C4D34ACA234FC0F800CA54E0DE4AC0 │  0.8792077187687006 │
└────────────────────────────────────────────────────┴─────────────────────┘
(10 rows)

Time: 1012,931 ms (00:01,013)
```
Geometry looks good, accessing the value sleeps 0.1s per row.

I try to add the layer in QGIS. It's seen well in PostGIS tree:
image

Try to drag it into map. Wait expected 1s. Get unhelpful error message:
image

 - Reason is empty.
 - Message disappears before I finish reading it. A layer that loads more time than it and then fails will be lost, as I won't be at the computer in case it loads 1minute+.
 - It should just work. Adding test_table of same structure works.

### PR DESCRIPTION
**Pull request by elpaso**
... if it's in URI key

Fixes #31799

### CODE REVIEW

**Comment by elpaso** [comment]
@jef-n I'd like to hear your opinion on this one.

File: src/providers/postgres/qgspostgresprovider.cpp [hunk 1]
```diff
@@ -1049,8 +1049,19 @@ bool QgsPostgresProvider::loadFields()
       }
       else
       {
-        QgsMessageLog::logMessage( tr( "Field %1 ignored, because of unsupported type %2" ).arg( fieldName, fieldTypeName ), tr( "PostGIS" ) );
-        continue;
+        // be tolerant in case of views: this might be a field used as a key
+        const QgsPostgresProvider::Relkind type = relkind();
+        if ( ( type == Relkind::View || type == Relkind::MaterializedView ) && parseUriKey(mUri.keyColumn()).contains(fieldName) )
```
Comment (elpaso) [inline src/providers/postgres/qgspostgresprovider.cpp]:
```suggestion
        if ( ( type == Relkind::View || type == Relkind::MaterializedView ) && parseUriKey( mUri.keyColumn( ) ).contains( fieldName ) )
```

**Comment by elpaso** [comment]
@jef-n thanks!
