### PR TITLE
Handle referenced geometries when converting to string

### LINKED ISSUE #51580: "Join by nearest" regression on 3.28 (from 3.22) when multiple geometry colums are present
### What is the bug or the crash?

Having a nodes layer with multiple geometries I usually did on 3.22 LTR the join by nearest algorithm to find out nodes that are closer than 0.003 m.

With 3.28.2 there's an error now:
```
Feature could not be written to Joined_layer_.....: Could not store attribute "geometry_alt1": Could not convert value "" to target type "string"
Could not write feature into OUTPUT
Execution failed after 0.11 seconds
```

### Steps to reproduce the issue

1. Add the following SQL to your PostgreSQL database:

```
CREATE TABLE public.nodes (
    id integer NOT NULL,
    fk_district integer,
    fk_pressurezone integer,
    fk_printmap integer[],
    fk_precision integer,
    fk_precisionalti integer,
    fk_object_reference integer,
    altitude numeric(10,3) DEFAULT NULL::numeric,
    _printmaps text,
    _geometry_alt1_used boolean,
    _geometry_alt2_used boolean,
    _pipe_orientation double precision DEFAULT 0,
    _pipe_schema_visible boolean DEFAULT false,
    geometry public.geometry(PointZ,3844) NOT NULL,
    geometry_alt1 public.geometry(PointZ,3844),
    geometry_alt2 public.geometry(PointZ,3844)
);

INSERT INTO public.nodes VALUES (58957, NULL, NULL, '{}', 101, 101, 101, NULL, NULL, false, false, -8.627881391886133, true, '01010000A0040F00000000000018451B4100000000044018410000000000000000', NULL, NULL);
INSERT INTO public.nodes VALUES (58971, NULL, NULL, '{}', 101, 101, 101, NULL, NULL, false, false, -18.95382931168005, true, '01010000A0040F00000000000018451B4100000000084018410000000000000000', NULL, NULL);

ALTER TABLE ONLY public.nodes
    ADD CONSTRAINT node_pkey PRIMARY KEY (id);


CREATE INDEX node_geoidx ON public.nodes USING gist (geometry);


CREATE INDEX node_geoidx_alt1 ON public.nodes USING gist (geometry_alt1);

CREATE INDEX node_geoidx_alt2 ON public.nodes USING gist (geometry_alt2);
```

2. Run the join by nearest algo:

image

3. The error is shown:
```
Feature could not be written to Joined_layer_.....: Could not store attribute "geometry_alt1": Could not convert value "" to target type "string"
Could not write feature into OUTPUT
Execution failed after 0.11 seconds
```

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.2-Firenze | QGIS code revision | d33b8750f3
-- | -- | -- | --
Qt version | 5.15.8
Python version | 3.11.1
GDAL/OGR version | 3.5.2
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.11.0-CAPI-1.17.0
SQLite version | 3.40.0
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.5
QScintilla2 version | 2.13.0
OS version | Fedora Linux 37 (Thirty Seven)
  |   |   |  
Active Python plugins
slyr_community | 4.0.6
QuickWKT | 3.1
project_export_inspire | 1.0.0
water_topology | 0.1
plugin_reloader | 0.9.3
db_manager | 0.1.20
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
MetaSearch | 0.3.6

</body></html>QGIS version
3.28.2-Firenze
QGIS code revision
[d33b8750f3](https://github.com/qgis/QGIS/commit/d33b8750f3)
Qt version
5.15.8
Python version
3.11.1
GDAL/OGR version
3.5.2
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.11.0-CAPI-1.17.0
SQLite version
3.40.0
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.5
QScintilla2 version
2.13.0
OS version
Fedora Linux 37 (Thirty Seven)

Active Python plugins
slyr_community
4.0.6
QuickWKT
3.1
project_export_inspire
1.0.0
water_topology
0.1
plugin_reloader
0.9.3
db_manager
0.1.20
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Fix #51580

### CODE REVIEW

**Comment by MorriganR** [comment]
https://github.com/qgis/QGIS/pull/50592

File: src/core/qgsfield.cpp [hunk 1]
```diff
@@ -589,6 +589,29 @@ bool QgsField::convertCompatible( QVariant &v, QString *errorMessage ) const
     return false;
   }
 
+  // Handle referenced geometries (e.g. from additional geometry fields)
+  if ( d->type == QVariant::String && v.type() == QVariant::UserType && v.canConvert<QgsReferencedGeometry>( ) )
```
Comment (nyalldawson) [inline src/core/qgsfield.cpp:593]:
```suggestion
  if ( d->type == QVariant::String && v.userType() == QMetaType::type( "QgsReferencedGeometry" ) )
```

QVariant::canConvert will return true here for ANY qvariant type under qt 6. The meaning of canConvert has changed subtly from "is this a variant which stores a QgsReferencedGeometry" to "is it possible to construct a QgsReferencedGeometry from the value stored in the variant". And since QgsReferencedGeometry has a default constructor, the answer will ALWAYS be true.

File: src/core/qgsfield.cpp [hunk 2]
```diff
@@ -589,6 +589,29 @@ bool QgsField::convertCompatible( QVariant &v, QString *errorMessage ) const
...
+  {
+    const QgsReferencedGeometry geom { v.value<QgsReferencedGeometry>( ) };
+    if ( geom.isNull() )
+    {
+      v = QVariant( d->type );
+    }
+    else
+    {
+      // EWKT only if authid is EPSG, not sure if it makes sense otherwise
+      if ( geom.crs().authid().startsWith( QStringLiteral( "EPSG:" ) ) )
```
Comment (nyalldawson) [inline src/core/qgsfield.cpp:603]: We should move this to QgsReferencedGeometry. Maybe something like:

    /**
      * Returns the geometry converted to a EWKT string.
      *
      * \param precision decimal precision to use for WKT coordinates
      * \param ok TRUE if geometry can be represented as a EWKT string, FALSE otherwise
      * \returns geometry as a EWKT string.
    */
    QString asEWkt( int precision = 17, bool* ok = nullptr SIP_OUT ) const;

**Comment by nyalldawson** [comment]
Ideally we'd also add support for geometry/referenced geometry columns in the memory provider too, as by design the memory provider must be the lossless superset of the functionality of all other data providers. I'm happy to do this if you'd like.

**Comment by nyalldawson** [comment]
@elpaso I believe https://github.com/qgis/QGIS/pull/51845 is also needed

File: src/core/qgsfield.cpp (hunk 2 above)
Comment (elpaso) [reply src/core/qgsfield.cpp]: @nyalldawson  I've removed the E from WKT as we discussed, I guess there is no need for this method anymore.

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
See https://github.com/qgis/QGIS/pull/51863
