### PR TITLE
Merge features: immediately update widgets for attributes with a provider default value

### LINKED ISSUE #59494: DB default values override actual values in merge selected features tool
### What is the bug or the crash?

When using database level default values, Merge Selected Features tool displays this default value in merge row. Also the header column is set to Manual Value. The correct behavior would be to select value of the first feature as in other columns. 

default_overrides_merge

This bug occurs at least with GPKG and PostGIS. QGIS form default values do not change the behavior.

### Steps to reproduce the issue

To reproduce the bug I prepared a [merge.zip](https://github.com/user-attachments/files/17814203/merge.zip) containing merge.gpkg which has line layer with two fields "code" and "field2". "code" field has a default value of 1 set at the table level (`ALTER TABLE line ADD COLUMN code int default 1`). 

1. Download and extract [merge.zip](https://github.com/user-attachments/files/17814203/merge.zip)
2. Start QGIS and open project from that geopackage
3. Start editing line layer
4. Select both features and click Merge Selected Features tool
5. See how the header of column "code" is set to Manual Value and the Merge cell is set to 1

### Versions

<details>

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.40.0-Bratislava</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/b56115d874">b56115d874</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.13</td></tr><tr><td>Python version</td><td>3.12.7</td></tr><tr><td>GDAL/OGR version</td><td>3.9.3</td></tr><tr><td>PROJ version</td><td>9.5.0</td></tr><tr><td>EPSG Registry database version</td><td>v11.016 (2024-08-31)</td></tr><tr><td>GEOS version</td><td>3.13.0-CAPI-1.19.0</td></tr><tr><td>SQLite version</td><td>3.46.1</td></tr><tr><td>PDAL version</td><td>2.8.1</td></tr><tr><td>PostgreSQL client version</td><td>unknown</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.3.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Windows 10 Version 2009</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

</details>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

If Value Map or relation reference is used, the default value is displayed without mapping. Only when user clicks the cell, the mapped value is displayed.

default_overrides_value_map

### PR DESCRIPTION
**Pull request by JuhoErvasti**
Apply for widgets which show a key/description instead of the actual values. Addresses part of #59494 (the additional context part, the main part AFAIK is the intended behavior and is meant to be addressed with a "merge policy" feature)

Backport to 3.40 requested.

before:
before

after:
after

### CODE REVIEW

File: src/app/qgsmergeattributesdialog.cpp [hunk 1]
```diff
@@ -267,6 +267,15 @@ void QgsMergeAttributesDialog::createTableWidgetContents()
         currentComboBox->setCurrentIndex( currentComboBox->findData( QStringLiteral( "manual" ) ) );
         currentComboBox->blockSignals( false );
       }
+
+      const QString widgetType = QgsGui::editorWidgetRegistry()->findBest( mVectorLayer, mFields.at( idx ).name() ).type();
+
+      const QStringList updateWidgetFor = QStringList() << QStringLiteral( "ValueMap" )
```
Comment (m-kuhn) [inline src/app/qgsmergeattributesdialog.cpp:273]: What is the reason for this hardcoded list of qidget types?

Comment (JuhoErvasti) [reply src/app/qgsmergeattributesdialog.cpp:273]: @m-kuhn Apologies for taking so long to respond! My thinking was that these are the widgets where you can have a situation where the default value should be displayed differently, whereas for others such as text edit / range widget it doesn't necessarily matter.

Should I change it so that the widget gets updated regardless of its type?

**Comment by JuhoErvasti** [comment]
@m-kuhn
I pushed an update if you can/want to take a look, it should address both your comments. I explained my initial reasoning for using the list of widgets but thinking about it more I don't think it makes sense to only update certain types of widgets.

**Comment by m-kuhn** [comment]
@JuhoErvasti thanks, looks good now.

If we have hardcoded lists like this, it's good to have a comment that explains the why. Or often it is better to bring this knowledge into the widget registry or widget wrapper, so if someone implements a new widget in a plugin, they can define how it should behave. Just FYI, as this seems to be no longer an issue now.

**Comment by JuhoErvasti** [comment]
@m-kuhn thank you, I'll keep that in mind. 

If it's okay now, could this change be backported to 3.40 as well?

**Review by m-kuhn — APPROVED** [review]
