### PR TITLE
[wms] Add bounding boxes for all linked title matrixes to get proper WMTS layer extent

### LINKED ISSUE #51857: WMTS layer has wrong extents when multiple tilesets are available
### What is the bug or the crash?

When a WMTS layer has multiple tilesets available, and `TileMatrixSet` specifies its extents via a `BoundingBox` element, QGIS seems to ~~prefer using 3857~~ use randomly one of the tileset bounds in the provider metadata listing, and will use those bounds for all the different tilesets. QT_HASH_SEED (which affects XML element ordering) seems to have effect on which tileset bounds gets selected.

When the layer is added to a project with a different (ie. not 3857) tileset its extents are read from the 3857 tileset instead of the extents of its own tileset, if QGIS picked the 3857 to represent the layer extents. This will result in the "zoom to layer" action panning/zooming the canvas extents (and if its the first layer added to the project, initial extents) to a wrong location.

In the example capabilities tilesets, 3857 extents cover whole world, and 3067 extents are around Finland. When 3857 extents are chosen and used when 3067 layer is added to the project, canvas will fit the 3857 extents. Metadata will list only one extent for the layers, and the extens of the layer are generated from that value, transformed to the layer CRS:

image
image

### Steps to reproduce the issue

- set QT_HASH_SEED=0 before launching QGIS
- Add OpenStreetMap xyz layer to an empty project (for visualization purposes only)
- Add WMTS connection from capabilities url: `https://gist.githubusercontent.com/komima/d74ab9397e71e2df69e2570726416f11/raw/959ee5518cd50e35f67d7af5135786954570a7d5/WMTSCapabilities.xml`
- Add the `Multiple tilesets / ETRS-TM35FIN` layer to the project
- Press "Zoom to layer(s)" on that layer
- User will be shown a map canvas that covers the whole world, instead of something close to Finland (as would be approriate for the tileset extents)
- Close QGIS, set QT_HASH_SEED=1, reopen and add the layers again
- Press "Zoom to layer(s)" on the WTMS layer
- User will be shown a map canvas close to Finland (as is appropriate)

No extent issues for single tileset layers:
- Add the `Single 3067 tileset` layer to the project
- Press "Zoom to layer(s)" on that layer
- User will be shown a map canvas close to Finland (as is appropriate)

### Versions

QGIS 3.22.16 (from OSGeo4W network installer) on Windows 10

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This PR fixes  #51857 , whereas the WM[T]S provider failed to add all bounding boxes details when parsing WMTS capabilities XML. By only adding one (random) bounding box, it would cause a WMTS layer having multiple tile layer matrix to pick the wrong bounding box if the randomly chosen tile matrix set wasn't the one linked to the layer.

### CODE REVIEW

File: src/providers/wms/qgswmscapabilities.cpp [hunk 1]
```diff
@@ -2395,42 +2395,44 @@ bool QgsWmsCapabilities::detectTileLayerBoundingBox( QgsWmtsTileLayer &tileLayer
...
+    QgsRectangle extent( tm.topLeft, bottomRight );
+    extent.normalize();
 
-  QgsWmsBoundingBoxProperty boundingBoxProperty;
-  boundingBoxProperty.box = extent;
-  boundingBoxProperty.crs = crs.authid();
-  tileLayer.boundingBoxes << boundingBoxProperty;
+    QgsWmsBoundingBoxProperty boundingBoxProperty;
+    boundingBoxProperty.box = extent;
+    boundingBoxProperty.crs = crs.authid();
```
Comment (3nids) [inline src/providers/wms/qgswmscapabilities.cpp:2431]: what happens if the CRS is not constant? (is this possible?)

Comment (nirvn) [reply src/providers/wms/qgswmscapabilities.cpp:2431]: I don't think it's possible. One tile matrix set has one crs declared for the whole set.

**Review by 3nids — APPROVED** [review]
