### PR TITLE
Fix GPKG delete from browser stored connection

### LINKED ISSUE #36930: Unable to delete a stored geopackage connection from browser
On Linux and Windows

qgis-bug-delete-gpkg

Related to https://github.com/qgis/QGIS/issues/36832

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #36930 - also delete from stored connections
before refresh.

### CODE REVIEW

File: src/gui/providers/ogr/qgsgeopackageitemguiprovider.cpp [hunk 1]
```diff
@@ -171,6 +173,13 @@ void QgsGeoPackageItemGuiProvider::deleteGpkg()
       else
       {
         QMessageBox::information( nullptr, title, tr( "GeoPackage deleted successfully." ) );
+        // If the deleted file was a stored connection, remove it too
+        if ( ! name.isEmpty() )
+        {
+          QgsProviderMetadata *md { QgsProviderRegistry::instance()->providerMetadata( QStringLiteral( "ogr" ) ) };
+          std::unique_ptr<QgsAbstractProviderConnection> conn { md->createConnection( name ) };
+          conn->remove( name );
```
Comment (nyalldawson) [inline src/gui/providers/ogr/qgsgeopackageitemguiprovider.cpp:181]: Can't we just do

    md->deleteConnection( name );

instead?

Comment (elpaso) [reply src/gui/providers/ogr/qgsgeopackageitemguiprovider.cpp:181]: yeah, cleaner.
