### PR TITLE
Convert DD labels to destination type

### LINKED ISSUE #42022: Error updating PostGIS table when using data driven label position and integer columns
I use two integer fields 'x' and 'y' in postgis table to store label postion.
Qgis 3.14 and lower worked fine, but since version 3.16 any saving layer operation after label moving causes postgis error
 ```
PostGIS error while changing attributes: Error: wrong value for integer "2825.086389414024"
 LINE 1: UPDATE work.zones SET "x"='2825.086389414024',"y"='5391.8...
```

QGIS version | 3.18.0-Zürich | QGIS code revision | bdef9fb328
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | db_manager; MetaSearch; processing

gis=# select postgis_version();
            postgis_version
---------------------------------------
 2.2 USE_GEOS=1 USE_PROJ=1 USE_STATS=1

gis=# select version();
                                             version
-------------------------------------------------------------------------------------------------
 PostgreSQL 9.5.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2, 64-bit

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #42022

### CODE REVIEW

File: src/app/labeling/qgsmaptoolmovelabel.cpp [hunk 1]
```diff
@@ -293,8 +293,30 @@ void QgsMapToolMoveLabel::cadCanvasPressEvent( QgsMapMouseEvent *e )
...
-        bool success = vlayer->changeAttributeValue( featureId, xCol, xPosNew );
-        success = vlayer->changeAttributeValue( featureId, yCol, yPosNew ) && success;
+
+        // Try to convert to the destination field type
+        QVariant xNewPos( xPosNew );
+        QVariant yNewPos( yPosNew );
+
+        if ( xCol < vlayer->fields().count() )
+        {
+          if ( ! xNewPos.convert( vlayer->fields().at( xCol ).type() ) )
```
Comment (nyalldawson) [inline src/app/labeling/qgsmaptoolmovelabel.cpp:303]: Shouldn't this use QgsField::convertCompatible?

Comment (elpaso) [reply src/app/labeling/qgsmaptoolmovelabel.cpp]: done

**Review by nyalldawson — APPROVED** [review]
