### PR TITLE
Bugfix wfs 2.0 typenames esri bug

### LINKED ISSUE #41087: Wrong WFS 2.0.0 request returns duplicate features
**Describe the bug**

The WFS 2.0.0 prvoider will send out requests with double TYPENAME(S) like this :  `&TYPENAMES=Seattle_Downtown_Features:Zoning&TYPENAME=Seattle_Downtown_Features:Zoning`, which results in features beeing doubled in the response (at least by an ArcGIS Server). In the example below the layer holds 97 features and they are sent back twice in the response.

For the same layer and server, in WFS 1.1.0 the request has only `&TYPENAME=Seattle_Downtown_Features:Zoning` and works.
Also if I remove the additional `&TYPENAME=Seattle_Downtown_Features:Zoning` from the WFS 2.0.0 request, the duplicates will be gone.

ArcGISServer could deal better with this and unduplicate the request, but QGIS seems to be making the mistake first.
I understand from various issues that the compatibility between different WFS versions and different client and servers is a challenge, and I guess that QGIS aimed at keeping both TYPENAME(S) for backward compatibility. It seems to be complicated to keep everyone happy !

I guess the best solution would be to unduplicate TYPENAME(S) keys in QGIS before sending the request - but am not knowledgeable enough to submit a PR.

I wouldn't want to finish without a big Thank You and Bravo for the excellent work !

**How to Reproduce**

1. Add a WFS 2.0.0 layer with the URL :  `https://dservices2.arcgis.com/ZQgQTuoyBrtmoGdP/arcgis/services/Seattle_Downtown_Features/WFSServer?SERVICE=WFS`
2. Connect to the server and add the Zoning layer which holds 97 features (currently)
3. With the network debugging panel (F12) fetch one of the request and it should show something like :  
```https://dservices2.arcgis.com/ZQgQTuoyBrtmoGdP/arcgis/services/Seattle_Downtown_Features/WFSServer?SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&TYPENAMES=Seattle_Downtown_Features:Zoning&TYPENAME=Seattle_Downtown_Features:Zoning&STARTINDEX=0&COUNT=300&SRSNAME=urn:ogc:def:crs:EPSG::3857```
I tweeked the STARTINDEX to zero and set a large COUNT to see all the response. This request in my browser shows twice the 97 features.
4. Delete the `&TYPENAME=Seattle_Downtown_Features:Zoning` (and leave the TYPENAMES one) and send again. Now we only have 97 features.

**QGIS and OS versions**

Version de QGIS | 3.16.3-Hannover | Révision du code | 94ac9f21b8
-- | -- | -- | --
Compilé avec Qt | 5.11.2 | Utilisant Qt | 5.11.2
Compilé avec GDAL/OGR | 3.1.4 | Utilisé avec GDAL/OGR | 3.1.4
Compilé avec GEOS | 3.8.1-CAPI-1.13.3 | Utilisé avec GEOS | 3.8.1-CAPI-1.13.3
Compilé avec SQLite | 3.29.0 | Fonctionne avec SQLite | 3.29.0
Version du client PostgreSQL | 11.5 | Version de SpatiaLite | 4.3.0
Version de QWT | 6.1.3 | Version de QScintilla2 | 2.10.8
Compilé avec PROJ | 6.3.2 | Fonctionne avec PROJ | Rel. 6.3.2, May 1st, 2020
Version de l'OS | Windows 10 (10.0)
Extensions Python actives | Generalizer3; Go2NextFeature3; go2streetview; Highlighter; openlayers_plugin; PluginLoadTimes; plugin_reloader; qfieldsync; db_manager; processing

**Additional context**

I found quite some information here when digging into this problem : https://issues.qgis.org/issues/17872

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #41087

Leave both forms for describeFeatureType, fix tests

### CODE REVIEW

File: src/providers/wfs/qgswfsdescribefeaturetype.cpp [hunk 1]
```diff
@@ -40,6 +40,8 @@ bool QgsWFSDescribeFeatureType::requestFeatureType( const QString &WFSVersion,
     }
   }
 
+  // Always add singular form for broken servers (ESRI)
```
Comment (rouault) [inline src/providers/wfs/qgswfsdescribefeaturetype.cpp:43]: I don't think the comment is exact. ESRI supports plural form. This is other servers that don't support the plural form

Comment (elpaso) [reply src/providers/wfs/qgswfsdescribefeaturetype.cpp:43]:
```suggestion
  // Always add singular form for broken servers
```

**Comment by palmerj** [comment]
LGTM. Cheers!
