### PR TITLE
Fixes Shortcuts prevent inputs with AltGr  #29021

### LINKED ISSUE #29021: ']' keyboard (alt-gr + '+' ) not working on QGis 3.4.4 with Spanish or Italian keyboard - Windows
Author Name: **Javier Becerra Elcinto** (Javier Becerra Elcinto)
Original Redmine Issue: [21203](https://issues.qgis.org/issues/21203)
Affected QGIS version: 3.4.4
Redmine category:gui

---
Running QGis 3.4.4, in a Windows 8.1 setup in Spanish, with Spanish es-es keyboard (Qwerty with '[' being alt-gr+'`' and ']' alt-gr+'+'), I can properly type '[' (alt-gr+'`') but nothing happens when I try to type ']' (alt-gr+'+').
This happens in Python Console (quite annoying actually), on Python Console's text editor or when changing a layer's name (right-click on the layer tree view on bottom left of the screen), but it works properly on dialogs shown in independent windows (i.e. open file dialog/save as...).

---

Related issue(s): #28820 (duplicates), #29800 (duplicates)
Redmine related issue(s): [21001](https://issues.qgis.org/issues/21001), [21985](https://issues.qgis.org/issues/21985)

---

### PR DESCRIPTION
**Pull request by YoannQDQ**
Fixes #29021

## Description 
A long standing bug in QGIS is the inability to enter some characters (`}`, `|`, ...) on windows, with keyboard layouts that use the AltGr key (Spanish, French...). This is particularly annoying within the python console.

The reason is that Qt considers by default the AltGr key to be a shortcut for Ctrl+Alt, which causes some QGIS global shortcuts to be fired instead of entering the character.

There has been some discussion about this on PR #38608.
This is not specific to QGIS, as it happens in other Qt applications (see https://bugreports.qt.io/browse/QTBUG-73247)

Setting the environment variable `QT_QPA_PLATFORM=windows:altgr` before creating the QgsApplication on windows builds could neatly solve the issue. (cf. https://doc.qt.io/qt-6/qguiapplication.html#platform-specific-arguments)

### CODE REVIEW

**Comment by YoannQDQ** [comment]
I'm not sure this is the right way to do it, but it seems to work (at least for the portable version on Windows)

**Comment by DelazJ** [comment]
@YoannQDQ Can you add a more verbose and explicit title to the pull request, please? Thanks

File: src/app/main.cpp [hunk 1]
```diff
@@ -891,6 +891,16 @@ int main( int argc, char *argv[] )
   // Initialize the application and the translation stuff
   /////////////////////////////////////////////////////////////////////
 
+
+#if defined(Q_OS_WIN)
+  // FIXES #29021
+  // Prevent Qt from treating the AltGr key as  Ctrl+Alt on Windows,
+  // which causes shortcuts to be fired instead of entering some characters (eg "}", "|")
+  // on some keyboard layouts
+  qputenv( "QT_QPA_PLATFORM", "windows:altgr" );
```
Comment (nyalldawson) [inline src/app/main.cpp:900]: Can you add a note to check eg https://doc.qt.io/qt-6/qguiapplication.html for the documentation for this setting?

**Comment by nyalldawson** [comment]
Looks good to me, I'd love a second opinion though!

**Comment by YoannQDQ** [comment]
Huh. Pipeline failed, but if I understand the logs correctly, it's not on me. Could someone trigger another run?

**Comment by roya0045** [comment]
Strange, I never had any issues with key modifiers.

**Comment by roya0045** [comment]
> > Strange, I never had any issues with key modifiers.
> 
> Which OS/keyboard layout do you use? On Windows 10, AZERTY french layout, I just can't enter } or | unless I disable some shortcuts.

Qwerty with can-fr or can-multilingual layout.  Win10

**Comment by agiudiceandrea** [comment]
@roya0045, the issue also occurs using the Italian and Spanish keyboard layouts (as reported in the issue report).
On Windows, with every keyboard that maps to a char any AltGr key combination also mapped by default in QGIS as an Ctrl+Alt key combination, it is impossible to type such char in the Python console.
For the Italian and Spanish keyboard layouts the issue is with the `]` char (AltGr++ / Ctrl+Alt++ Zoom In).

File: src/app/main.cpp [hunk 2]
```diff
@@ -891,6 +891,16 @@ int main( int argc, char *argv[] )
   // Initialize the application and the translation stuff
   /////////////////////////////////////////////////////////////////////
 
+
+#if defined(Q_OS_WIN)
```
Comment (uclaros) [inline src/app/main.cpp:895]: Just curious, is `Q_OS_WIN` referring to the host at compile time or the build target?
