### PR TITLE
advanced digitizing papercuts

### LINKED ISSUE #61587: Advanced Digitizing: Floater not working correctly
### What is the bug or the crash?

Several issues with the Advanced Digitizing Floater:

1.) Initially, the x,y coordinates are always shown, even though not enabled. Only when actively selecting them and then deslecting them do they disappear

2.) The Bearing is not working. In my setting I configured it for 0° to 360° with one digit but the Floater is showing something else

3.) The distance is not accurate.

Please see linked screencast video to see for yourself that there are several issues with the Floater. 

https://www.veed.io/view/89e2e548-bc32-40b3-9115-b5ed54ee7a91?panel=share

The result should be reproducable on your end.

### Steps to reproduce the issue

Start QGIS fresh.
In a new project file (EPSG: 3857) create a scratch layer for LineStrings (EPSG: 4326).
Enable Advanced Digitizing and play around with the settings for the Floater

### Versions

QGIS version
3.40.5-Bratislava
QGIS code revision
8d6d1b5448
 
Libraries
Qt version
5.15.13
Python version
3.12.9
GDAL version
3.10.2
PROJ version
9.6.0 (Compiled)
9.5.0 (Running)
EPSG Registry database version
v12.004 (2025-03-02)
GEOS version
3.13.1-CAPI-1.19.2
SQLite version
3.46.1
PDAL version
2.8.3
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.3.0
QScintilla2 version
2.14.1
OS version
Windows 11 Version 2009
 
Active Python plugins
latlontools
3.7.4
quick_map_services
0.21.2
shapetools
3.5.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

The screencast video is too big so I can only share the link to video with you:

https://www.veed.io/view/89e2e548-bc32-40b3-9115-b5ed54ee7a91?panel=share

### PR DESCRIPTION
**Pull request by elpaso**
Fix #61587

The a.m. issue is really three issues:

1. show XY settings not always honored (same for other settings really)
2. bearing not updated
3. inaccurate distance

This PR is an attempt to fix the first two issues: I couldn't reproduce the third.

### CODE REVIEW

File: src/gui/qgsadvanceddigitizingdockwidget.cpp [hunk 1]
```diff
@@ -1440,7 +1478,7 @@ void QgsAdvancedDigitizingDockWidget::updateUnlockedConstraintValues( const QgsP
   const QgsPoint penultimatePt = penultimatePointV2( &penulPointExist );
 
   // --- angle
-  if ( !mAngleConstraint->isLocked() && previousPointExist )
+  if ( previousPointExist )
```
Comment (nyalldawson) [inline src/gui/qgsadvanceddigitizingdockwidget.cpp:1481]: Would be good to get a test covering these changes

**Review by nyalldawson — APPROVED** [review]
