### PR TITLE
fix mesh legend

### LINKED ISSUE #41317: Missing drop-down option and legend for mesh layer
**Describe the bug**
While working with an imported mesh layer, there is no option to use 'drop-down' icon to excess the legend for the chosen dataset (as it works with the raster layers). It results in not being able to view the legend and add it to the map layout.
This feature is available in QGIS 3.12 version.

**How to Reproduce**
Example of the desired result:

QGIS_3_12_mesh_layer_symbology
QGIS_3_12_mesh_legend

**QGIS and OS versions**

QGIS-Version
3.14.16-Pi
QGIS-Codeversion
df27394552
Kompiliert gegen Qt
5.11.2
Laufendes Qt
5.11.2
Kompiliert mit GDAL/OGR
3.0.4
Läuft mit GDAL/OGR
3.0.4
Kompiliert mit GEOS
3.8.1-CAPI-1.13.3
Läuft mit GEOS
3.8.1-CAPI-1.13.3
Kompiliert mit SQLite
3.29.0
Läuft mit SQLite
3.29.0
PostgreSQL-Client-Version
11.5
SpatiaLite-Version
4.3.0
QWT-Version
6.1.3
QScintilla2-Version
2.10.8
Kompiliert mit PROJ
6.3.2
Läuft mit PROJ
Rel. 6.3.2, May 1st, 2020
BS-Version
Windows 10 (10.0)
Aktive Python-Erweiterungen
crayfish; 
db_manager; 
MetaSearch; 
processing

**Additional context**

### PR DESCRIPTION
**Pull request by vcloarec**
When an existing project with a mesh layer is open, the legend is not here anymore. This PR fixes this issue.
could fix https://github.com/qgis/QGIS/issues/41317

### CODE REVIEW

File: src/core/mesh/qgsmeshlayer.cpp [hunk 1]
```diff
@@ -63,9 +63,9 @@ QgsMeshLayer::QgsMeshLayer( const QString &meshLayerPath,
     ok = setDataProvider( providerKey, providerOptions, flags );
   }
 
+  setLegend( QgsMapLayerLegend::defaultMeshLegend( this ) );
   if ( ok )
   {
-    setLegend( QgsMapLayerLegend::defaultMeshLegend( this ) );
```
Comment (PeterPetrik) [inline src/core/mesh/qgsmeshlayer.cpp:68]: I am not sure, if you open existing project, why would `setDataProvider` return false? isnt the problem somewhere else (like read/write of qgis project xml?)

Comment (vcloarec) [reply src/core/mesh/qgsmeshlayer.cpp:68]: when opening a project and the layer is created, the layer is not valid, it become valid later when read XML:
https://github.com/qgis/QGIS/blob/d2937653c3d7277540232e071f9a333f73f16607/src/core/project/qgsproject.cpp#L1189
and
https://github.com/qgis/QGIS/blob/d2937653c3d7277540232e071f9a333f73f16607/src/core/project/qgsproject.cpp#L1232

Comment (nyalldawson) [reply src/core/mesh/qgsmeshlayer.cpp:68]: It matches the other layer type's behavior, too

**Review by nyalldawson — APPROVED** [review]
