### PR TITLE
fix copying urls/json to clipboard from identify results

### LINKED ISSUE #26899: Copy attribute / Copy feature attributes doesn't return value if value is URI
Author Name: **James Passmore** (@nmtoken)
Original Redmine Issue: [19069](https://issues.qgis.org/issues/19069)
Affected QGIS version: 3.0.3
Redmine category:unknown

---
When using the identify tool, and looking at the values of a feature in the Identify Results window, I can right click and copy the attribute value when the value is plain text or a number, but not when the value is an URI.  Similarly when I right click and select Copy feature attributes, I get all attribute names, but no values that are URIs.

For example, if I do a Copy feature attributes on the following feature (image)

I only get the following text:

```
fid: 52
identifier: #M4EU.CO_264675
commodity: TREO
commodityRank: 
commodityImportance: 
mineralOccurrenceName: Aksu Diamas
commodityClassifier_uri: 
mineralOccurrence_uri: 
specification_uri: 
endusepotential: 
representativeCommodity_uri: 
mineralOccurrenceType_uri: 
inspire: GB.BGS.EURARE
country: TR

```

---

- [copy-attributes.png](https://issues.qgis.org/attachments/download/12759/copy-attributes.png) (James Passmore)

### PR DESCRIPTION
**Pull request by uclaros**
## Description
The tree view in identify results panel uses different widgets for urls and json objects making their contents non-copyable.
With this PR we use `UserRole + 2` to store and retrieve the copyable text for all fields.

Fix #26899

### CODE REVIEW

File: src/app/qgsidentifyresultsdialog.cpp [hunk 1]
```diff
@@ -737,6 +737,9 @@ QgsIdentifyResultsFeatureItem *QgsIdentifyResultsDialog::createFeatureItem( QgsV
     const QString representedValue = representValue( vlayer, setup, fields.at( i ).name(), attrs.at( i ) );
     attrItem->setSortData( 1, representedValue );
     attrItem->setToolTip( 1, representedValue );
+    // To make sure we can copy to clipboard even when an alternate widget is used (json/url),
+    // we store the representedValue to UserRole + 2 and read from that when copying to clipboard
+    attrItem->setData( 1, Qt::UserRole + 2, representedValue );
```
Comment (rouault) [inline src/app/qgsidentifyresultsdialog.cpp:742]: it would be test to have the following declaration at top of file and user it wherever Qt::UserRole + 2 is used
```
constexpr int ROLE_REPRESENTED_VALUE = Qt::UserRole + 2;
```

Comment (uclaros) [reply src/app/qgsidentifyresultsdialog.cpp]: Done, this is indeed cleaner!

**Review by nyalldawson — APPROVED** [review]
