### PR TITLE
don't recycle rulekeys when copy pasting rules in the rule-based render widget

### LINKED ISSUE #47915: Duplicate ruleKey issues with copied rule-based symbols
### What is the bug or the crash?

When copy-pasting symbols in the rule-based widget, there seems to be issues arising with the connection to the QgsLayterTtree.

Copying a symbol and reusing it will lead some instances of the copied element to a single symbol whereas others will not be linked. The rule-based widget shows and toggles the proper symbols, but as the layertree is the main interface to access symbols this can be problematic for multiple elements, such as themes.

### Steps to reproduce the issue

Here is a sample project showcasing this [test_layertree_idx.zip](https://github.com/qgis/QGIS/files/8326822/test_layertree_idx.zip)
Simply toggle the symbols in the layertree and in the renderer, the outer line is not toggle-able other than in the renderer directly.

To recreate manually:

1. Creata a symbol in the rule-based renderer widget
2. copy-paste that symbol a few times
3. modify the copied symbols to make them unique
4. (optional) create and toggle themes 

### Versions

Tried on 3.19 on windows and 3.24 also on windows

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by roya0045**
## Description

 Fixes #47915

This changes create a new Uuid for a pasted rule instead of reusing the rulekey of the origin rule.

This prevent weird issues when toggling copied rules in the layertree. This is not problematic when copy pasting rules in the layer styling panel as it uses a totally different path to create copied rule and doesn't reuse this id.

### CODE REVIEW

**Comment by roya0045** [comment]
test failure is a segfault in ept, unrelated to proposed changes.

**Comment by roya0045** [comment]
works fine.

**Comment by nyalldawson** [comment]
@roya0045 i think you'll need to handle this in the rule "paste" code instead

**Comment by roya0045** [comment]
@nyalldawson yup, found the proper spot, just slow due to old laptop. All good now and #51422 is not happening.

File: src/gui/symbology/qgsrulebasedrendererwidget.cpp [hunk 1]
```diff
@@ -1260,7 +1260,7 @@ bool QgsRuleBasedRendererModel::dropMimeData( const QMimeData *data,
     QDomElement ruleElem = rootElem.firstChildElement( QStringLiteral( "rule" ) );
     if ( rootElem.attribute( QStringLiteral( "type" ) ) == QLatin1String( "labeling" ) )
       _labeling2rendererRules( ruleElem );
-    QgsRuleBasedRenderer::Rule *rule = QgsRuleBasedRenderer::Rule::create( ruleElem, symbolMap );
+    QgsRuleBasedRenderer::Rule *rule = QgsRuleBasedRenderer::Rule::create( ruleElem, symbolMap )->clone();
```
Comment (nyalldawson) [inline src/gui/symbology/qgsrulebasedrendererwidget.cpp:1263]: This leaks, because ::create returns a new object which is never cleaned up. I'd suggest instead adding a `bool regenerateNewKey = false` argument to  QgsRuleBasedRenderer::Rule::create and setting it to true here instead.

Also note that the same changes will need to be made to QgsRuleBasedLabelingModel::dropMimeData

**Comment by nyalldawson** [comment]
@roya0045 are you able to port this fix to rule based labelling too please?

File: src/core/symbology/qgsrulebasedrenderer.h [hunk 2]
```diff
@@ -383,10 +383,11 @@ class CORE_EXPORT QgsRuleBasedRenderer : public QgsFeatureRenderer
          *
          * \param ruleElem  The XML rule element
          * \param symbolMap Symbol map
+         * \param reuseId TRUE to create a copy of the symbol, FALSE to create a disctinct rule. Default is TRUE
```
Comment (nyalldawson) [inline src/core/symbology/qgsrulebasedrenderer.h:386]:
```suggestion
         * \param reuseId set to TRUE to create an exact copy of the original symbol or FALSE to create a new rule with the same parameters as the original but a new unique ruleKey(). (Since QGIS 3.30)
```

**Comment by roya0045** [comment]
> @roya0045 are you able to port this fix to rule based labelling too please?

Sure thing, I'll try to do it this weekend (I don't have much time on weekdays to open my VM and test changes).

**Review by nyalldawson — APPROVED** [review]
