### PR TITLE
Reverse wheel zoom

### LINKED ISSUE #30940: Allow inverting mouse wheel
**Set wheel factor "bug"**
iface.mapCanvas().setWheelFactor(0.5)

This will revert the zoom in/ zoom out behavior. Not only wheel behavior but all zoom in / zoom out tools applied to that map canvas. For example zoom in tool will work as zoom out when clicked on map canvas.

**How to reproduce**
1. Open QGIS and load any layer you can zoom with, zoom in/out with wheel
2. Open python console - Plugins/Python console (Ctrl+Alt+p)
3. Write there this one line: iface.mapCanvas().setWheelFactor(0.5)
4. Try zoom with wheel to make sure it reverted the wheel behavior
5. Use Zoom In tool (Ctrl+Alt++) and click to zoom in, which should zoom out

QGIS 3.8, Windows

**How to sort out**
I love idea of being able to revert mouse wheel zoom in/out behavior through this (as for many ArcMap users it is desired behavior). The problem is it affects other tools too. Also it is a bit shame this can't be set up in Settings/Options/Map tools/Zooming/Zoom factor as there is minimum limit set to 100%, so you can't do 50% which is same as setWheelFactor(0.5). All these things relate to each other and should be thought through.

### PR DESCRIPTION
**Pull request by YoannQDQ**
Fixes #30940

## Description

Add a setting to reverse wheel zoom (scrolling forwards zooms out)

reverse-zoom

This affects wheel zooms
- in the map canvas (`QgsMapCanvas`)
- in the map overview (`QgsMapOverviewCanvas`)
- in the layout view (`QgsLayoutView`)
- in the map items int the layouts when the "move item content" tool is active (`QgsLayoutViewToolMoveItemContent`)
- in the Elevation profile canvas (`QgsElevationProfileCanvas`)
- In the model editor graphic view (`QgsModelGraphicsView`)

### CODE REVIEW

File: src/gui/qgsmapcanvas.cpp [hunk 1]
```diff
@@ -2621,7 +2624,7 @@ void QgsMapCanvas::wheelEvent( QWheelEvent *e )
 
 void QgsMapCanvas::setWheelFactor( double factor )
 {
-  mWheelZoomFactor = factor;
+  mWheelZoomFactor = std::max( factor, 1.01 );
```
Comment (m-kuhn) [inline src/gui/qgsmapcanvas.cpp:2627]: What is the reason for this?

**Review by m-kuhn — APPROVED** [review]
Lgtm

File: src/gui/qgsmapcanvas.cpp (hunk 1 above)
Comment (YoannQDQ) [reply src/gui/qgsmapcanvas.cpp:2627]: When you set a zoom factor < 1, clicking on the map canvas with the zoom in tool activated actually zooms out and vice versa. 1.01 is already the min value when you set it from the settings page, this only ensures that you cannot set it programmatically to less than 1
