### PR TITLE
Fix copy/paste of Forms Style

### LINKED ISSUE #37702: Copy and paste style for forms ignores edit widget type
It preserves grouping but ignores edit widget type.

### PR DESCRIPTION
**Pull request by troopa81**
## Description

Fixes #37702 : move Forms style import/export under the right category code part

### CODE REVIEW

**Comment by nyalldawson** [comment]
@3nids is this ok for you?

File: src/core/qgsvectorlayer.cpp [hunk 1]
```diff
@@ -2362,8 +2339,33 @@ bool QgsVectorLayer::readSymbology( const QDomNode &layerNode, QString &errorMes
...
+    // Load editor widget configuration
+    QDomElement widgetsElem = layerNode.namedItem( QStringLiteral( "fieldConfiguration" ) ).toElement();
+    QDomNodeList fieldConfigurationElementList = widgetsElem.elementsByTagName( QStringLiteral( "field" ) );
+    for ( int i = 0; i < fieldConfigurationElementList.size(); ++i )
+    {
+      const QDomElement fieldConfigElement = fieldConfigurationElementList.at( i ).toElement();
+      const QDomElement fieldWidgetElement = fieldConfigElement.elementsByTagName( QStringLiteral( "editWidget" ) ).at( 0 ).toElement();
+
+      QString fieldName = fieldConfigElement.attribute( QStringLiteral( "name" ) );
+      mFieldConfigurationFlags[fieldName] = qgsFlagKeysToValue( fieldConfigElement.attribute( QStringLiteral( "configurationFlags" ) ), QgsField::ConfigurationFlag::None );
```
Comment (3nids) [inline src/core/qgsvectorlayer.cpp:2354]: this is not part of the form category but part of the fields.

File: src/core/qgsvectorlayer.cpp [hunk 2]
```diff
@@ -2746,7 +2721,36 @@ bool QgsVectorLayer::writeSymbology( QDomNode &node, QDomDocument &doc, QString
...
+  {
+    QDomElement fieldConfigurationElement = doc.createElement( QStringLiteral( "fieldConfiguration" ) );
+    node.appendChild( fieldConfigurationElement );
+
+    int index = 0;
+    for ( const QgsField &field : qgis::as_const( mFields ) )
+    {
+      QDomElement fieldElement = doc.createElement( QStringLiteral( "field" ) );
+      fieldElement.setAttribute( QStringLiteral( "name" ), field.name() );
+      fieldElement.setAttribute( QStringLiteral( "configurationFlags" ), qgsFlagValueToKeys( field.configurationFlags() ) );
```
Comment (3nids) [inline src/core/qgsvectorlayer.cpp:2733]: same here.

File: src/core/qgsvectorlayer.cpp (hunk 1 above)
Comment (troopa81) [reply src/core/qgsvectorlayer.cpp:2354]: @3nids You configure this in *Forms* properties tab, but when user wants to copy/paste this configuration he has to select *Fields* (or now *Field and Widget configuration* since it has been renamed in  #38786) and not *Forms*. I find it a little bit confusing, like said in the issue  #37702. 

Am I missing something here?

Comment (3nids) [reply src/core/qgsvectorlayer.cpp:2354]: The configuration flags are defined in the fields tab.

The widgets config is also part of "fields and widget config" as rewritten in https://github.com/qgis/QGIS/pull/38786/files

Forms is only about the layout/UI.

So, I think you moved this to the wrong section.

Comment (troopa81) [reply src/core/qgsvectorlayer.cpp:2354]: I agree for the configuration flags, it should be in fields part.

Still, for the widget configuration, my proposal was to move them in Forms so when user copy/paste *Forms* it's exactly what you configure in *Forms* properties tab. No more, no less. 

Wouldn't be better than rename the items?

Comment (3nids) [reply src/core/qgsvectorlayer.cpp:2354]: No strong opinion
So you would revert https://github.com/qgis/QGIS/pull/38786 ?

Comment (troopa81) [reply src/core/qgsvectorlayer.cpp:2354]: If no one is against, yes

Comment (3nids) [reply src/core/qgsvectorlayer.cpp:2354]: ping @nyalldawson

Comment (nyalldawson) [reply src/core/qgsvectorlayer.cpp:2354]: No objection here

**Comment by 3nids** [comment]
so, to merge, it needs to 
* revert #38786
* move the configuration flags to the field section

works for you @troopa81  ?

**Comment by troopa81** [comment]
@3nids yes, I'm going to update my PR accordingly

**Comment by troopa81** [comment]
@3nids done
