### PR TITLE
Fix missing representation of layer's custom property list in the info page (HtmlMetadata)

### LINKED ISSUE #57334: Custom properties variableNames and variableValues are cleared when more than one layer custom variable exist
### What is the bug or the crash?

Layer properties --> Information tab has a custom properties section.
Among the predefined custom properties, we have variableNames and variableValues. Given their pluralized name, I assume they are supposed to return a list of the custom variables name and value. No idea for the expected formatting.

The issue here is that when you have ONE custom variable, it is displayed correctly but when they are more than one, the fields are turned empty

### Steps to reproduce the issue

https://github.com/qgis/QGIS/assets/7983394/5c27c27f-4a6c-42f2-a8e2-2973be2c2d44

### Versions

Tested on 3.36.0

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by signedav**
This covers lists and in only one level deepness. 

Other types that cannot be converted to a string or a stringlist are not represented (by the text *value cannot be displayed*).

image

("weirdoType" is manually added with type "Map")

It probably makes sense to have a more powerful representation, but then I suggest to go deeper into the content like proposed here https://github.com/qgis/QGIS/issues/57335 But this is IMHO an extension and not scope of this small "fix" here.

This fixes #57334

### CODE REVIEW

**Comment by signedav** [comment]
Is this what you imagine @DelazJ ?
Does the implementation make sense for you @jadsilva ?

**Comment by DelazJ** [comment]
> Is this what you imagine @DelazJ ?

Yes because now the variables are all displayed so the bug is fixed. Thanks @signedav 
No 😄 because the matching variable name <-> value is not necessarily obvious, and assuming I understood [your suggestion](https://github.com/qgis/QGIS/issues/57335#issuecomment-2119808791), displaying the variables name/value next to each other in a table would provide a better user experience. For the next step?

**Comment by signedav** [comment]
> displaying the variables name/value next to each other in a table would provide a better user experience. For the next step?

Yes exactly, I think it would make sense to improve the UX there in another (independent) step, but I would like to have this here as a fix of the bug, that the values are not displayed at all...

File: src/core/qgsmaplayer.cpp [hunk 1]
```diff
@@ -3253,7 +3253,24 @@ QString QgsMapLayer::generalHtmlMetadata() const
         continue;
 
       const QVariant propValue = customProperty( key );
-      metadata += QStringLiteral( "<tr><td class=\"highlight\">%1</td><td>%2</td></tr>" ).arg( key.toHtmlEscaped(), propValue.toString().toHtmlEscaped() );
+      QString stringValue = QString();
```
Comment (nyalldawson) [inline src/core/qgsmaplayer.cpp:3256]:
```suggestion
      QString stringValue;
```

File: src/core/qgsmaplayer.cpp [hunk 2]
```diff
@@ -3253,7 +3253,24 @@ QString QgsMapLayer::generalHtmlMetadata() const
...
+      if ( propValue.canConvert<QStringList>() && propValue.toStringList().count() > 1 )
```
Comment (nyalldawson) [inline src/core/qgsmaplayer.cpp:3257]: We shouldn't use canConvert anymore -- the meaning of this changed in Qt 6, to mean "is there anyway i can possibly create a string list from this object", and the answer will always be yes, because it CAN create an empty list :man_shrugging: 

Instead, you need to explicitly check the variant metatype to determine whether it contains a list value.

File: src/core/qgsmaplayer.cpp [hunk 3]
```diff
@@ -3253,7 +3253,24 @@ QString QgsMapLayer::generalHtmlMetadata() const
...
+      {
+        for ( const QString &s : propValue.toStringList() )
+        {
+          stringValue += s.toHtmlEscaped() + QStringLiteral( "<br>" );
+        }
+      }
+      else if ( propValue.canConvert<QString>() || propValue.isNull() )
```
Comment (nyalldawson) [inline src/core/qgsmaplayer.cpp:3264]: Similarly, don't use canConvert here.

Also, we shouldn't use QVariant::isNull to test for null, rather QgsVariantUtils::isNull, or you'll get unpredictable results on Qt 6 builds.

**Comment by signedav** [comment]
Thanks @nyalldawson No it evaluates the QMetaType according to the Qt version and makes the conversion according to it.

File: src/core/qgsmaplayer.cpp [hunk 4]
```diff
@@ -3253,7 +3253,32 @@ QString QgsMapLayer::generalHtmlMetadata() const
...
+      const QMetaType::Type propType = propValue.metaType();
+#endif
+      if ( propType == QMetaType::QVariantList || propType == QMetaType::QStringList )
+      {
+        const QStringList &stringList = propValue.toStringList();
+        for ( const QString &s : stringList )
+        {
+          stringValue += s.toHtmlEscaped();
+          if ( &s != &stringList.back() )
+            stringValue += QStringLiteral( "<br>" );
```
Comment (jadsilva) [inline src/core/qgsmaplayer.cpp:3269]: Maybe using `<p>` simplify the code

Comment (signedav) [reply src/core/qgsmaplayer.cpp]: You are right. Thanks.

**Review by nyalldawson — APPROVED** [review]

File: src/core/qgsmaplayer.cpp [hunk 5]
```diff
@@ -3253,7 +3253,29 @@ QString QgsMapLayer::generalHtmlMetadata() const
...
 
       const QVariant propValue = customProperty( key );
-      metadata += QStringLiteral( "<tr><td class=\"highlight\">%1</td><td>%2</td></tr>" ).arg( key.toHtmlEscaped(), propValue.toString().toHtmlEscaped() );
+      QString stringValue;
+#if QT_VERSION < QT_VERSION_CHECK(6, 0, 0)
+      const QMetaType::Type propType = QgsVariantUtils::variantTypeToMetaType( propValue.type() );
+#else
+      const QMetaType::Type propType = propValue.metaType();
+#endif
+      if ( propType == QMetaType::QVariantList || propType == QMetaType::QStringList )
```
Comment (nyalldawson) [inline src/core/qgsmaplayer.cpp:3262]:
```suggestion
      if ( propValue.type() == QVariant::List || propValue.type() == QVariant::StringList )
```

Comment (signedav) [reply src/core/qgsmaplayer.cpp]: Thanks a lot.

Btw. how do we consider the Qt-version situation? Are such version-checks not appropriated generally or just in this fix?
