### PR TITLE
Various fixes pan and zoom on rotated map canvas

### LINKED ISSUE #43275: Panning in a rotated map view with a locked scale changes the magnification factor
**Describe the bug**

When a map view's scale is locked and it has a rotation set, panning the map zooms in.

Also happens with a fresh profile without plugins.

**How to Reproduce**

1. Open New Project
2. Type "world" into coordinate text field in the status bar
3. Zoom in to scale <10.000.000
4. Lock the scale with the padlock icon
5. Set Rotation to 5°
6. Pan the map

**QGIS and OS versions**
QGIS version: 3.18.3-Zürich
QGIS code revision: 735cc85be9
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL/OGR: 3.1.4
Running against GDAL/OGR: 3.1.4
Compiled against GEOS: 3.8.1-CAPI-1.13.3
Running against GEOS: 3.8.1-CAPI-1.13.3
Compiled against SQLite: 3.29.0
Running against SQLite: 3.29.0
PostgreSQL Client Version: 11.5
SpatiaLite Version: 4.3.0
QWT Version: 6.1.3
QScintilla2 Version: 2.10.8
Compiled against PROJ: 6.3.2
Running against PROJ: Rel. 6.3.2, May 1st, 2020
OS Version: Windows 10 (10.0)
Active python plugins: 
AnotherDXF2Shape; 
FOEA; 
GroupStats; 
kbs-group-selected; 
layertilesmapcanvas; 
monokaiprospectrum; 
NNJoin; 
pathfinder; 
pluginbuilder3; 
plugin_reloader; 
QuickOSM; 
SpreadsheetLayers; 
db_manager; 
MetaSearch; 
processing

**Additional context**

Short video showcasing the bug: https://youtu.be/Cis7YtGzczA

### LINKED ISSUE #46775: Zoom level of "Zoom to layer" does not adapt when canva is rotated
### What is the bug or the crash?

When viewing a vector layer and using zoom to layer's feature (either manually or with a python command) the layer is correctly zoomed in when the rotation of the canva is 0° (See fig 1). 

Rot0_Zoom

However, when rotation is applied and Zoom to layer's is applied once more, the zoom level stays the same instead of adapting to the new view extent of the layer (See fig 2).
Rot76_Zoom

Is there a way to fix this or is it a bug?

### Steps to reproduce the issue

1. Open a vector layer with an assymetrical extent.
2. Zoom to layer
3. Change canva's roation (bottom left)
4. Zoom to layer

### Versions

3.22.2.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### LINKED ISSUE #48246: Scale Lock Ignored on Zoom to Full
### What is the bug or the crash?

When you have scale locked, and select the zoom to full option 
image
instead of zooming, it changes the scale.

Seems zoom features of any kind should affect just the zoom, and not the scale when the scale is locked.

### Steps to reproduce the issue

1. Lock scale
2. Zoom to Full

### Versions

3.22.5-Białowieża

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

https://github.com/qgis/QGIS/issues/38417
https://github.com/qgis/QGIS/pull/38954
https://github.com/qgis/QGIS/issues/48245

### LINKED ISSUE #52062: Zoom in tool does not work as expected when canvas is rotated
### What is the bug or the crash?

Zoom in with clicks does not work as expected when the view is rotated.

zoom

When the canvas is much wider that it is tall, zooming in actually zooms OUT.

### Steps to reproduce the issue

- Rotate the view
- Use the Zoom In tool (magnifier glass with a plus sign)
- Resize the window to get an aspect ratio where width >> height
- Zoom in using clicks (zooming by drawing a rect works fine)

### Versions

QGIS version
3.29.0-Master
QGIS code revision
994da50a64
Qt version
5.15.3
Python version
3.9.5
Compiled against GDAL/OGR
3.7.0dev-986b841325
Running against GDAL/OGR
3.7.0dev-a828b2b5a9
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

This copy of QGIS writes debugging output.

Active Python plugins
MemoryLayerSaver
4.0.4
multilayerselect
1.4.1
quick_map_services
0.19.19
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by YoannQDQ**
- Fix #52062 
- Fix #48246
- Fix #43275

## Description

Various fixes on panning/zooming when the map canvas is rotated

### CODE REVIEW

File: src/gui/qgsmapcanvas.h [hunk 1]
```diff
@@ -866,6 +869,13 @@ class GUI_EXPORT QgsMapCanvas : public QGraphicsView, public QgsExpressionContex
      */
     bool allowInteraction( QgsMapCanvasInteractionBlocker::Interaction interaction ) const;
 
+    /**
+     * Compute the actual extent needed to fully display the \a extent rotated by \a rotation.
+     *
+     * \since QGIS 3.30
+     */
+    QgsRectangle computeExtentForRotation( const QgsRectangle &extent, double rotation ) const;
```
Comment (nyalldawson) [inline src/gui/qgsmapcanvas.h:877]: This method could be static, right? QgsMapCanvasUtils might be a better fit for it.

File: src/gui/qgsmapcanvas.cpp [hunk 2]
```diff
@@ -3627,3 +3629,37 @@ double QgsMapCanvas::zoomOutFactor() const
...
+QgsRectangle QgsMapCanvas::computeExtentForRotation( const QgsRectangle &extent, double rotation ) const
+{
+  if ( extent.isEmpty() || qgsDoubleNear( rotation, 0.0 ) )
+  {
+    return extent;
+  }
+  // Compute the oriented bounding box of the extent
+  QgsGeometry geom = QgsGeometry::fromRect( extent );
+  geom.rotate( rotation, geom.centroid().asPoint() );
+  const QgsRectangle oob = geom.boundingBox();
```
Comment (nyalldawson) [inline src/gui/qgsmapcanvas.cpp:3642]: This could be made considerably more efficient -- eg by using something like https://codereview.stackexchange.com/a/267876 (maybe as a method in QgsGeometryUtils, or in QgsRectangle directly)

The current approach involves GEOS to determine the centroid, which means we have conversions from QgsGeometry -> GEOS -> back involved.

File: src/gui/qgsmapcanvas.h (hunk 1 above)
Comment (YoannQDQ) [reply src/gui/qgsmapcanvas.h:877]: It could, but I'd have to add a QSize parameter (or height and width) since the computed extent relies on the canvas current aspect ratio.

File: src/gui/qgsmapcanvas.cpp (hunk 2 above)
Comment (YoannQDQ) [reply src/gui/qgsmapcanvas.cpp:3642]: Yeah you're right, we just need a simple rect rotation, so we shouldn't call GEOS at all. I'll fix it.

**Comment by YoannQDQ** [comment]
Reduced the scope of this PR to include only small bugfixes. `setExtent` refacto will come back in a later PR

**Review by nyalldawson — APPROVED** [review]

**Comment by strk** [comment]
Good catch @YoannQDQ thank you ! I'm not seeing an automated testcase for this, while I suspect the code path is very fragile because the rotation feature has been added a long time ago and I'm pretty sure it used to work back then. Reading the code changes they seem so subtle that maybe some comments as for why extent() is different from mapSetting().extent() could be helpful for the next one looking at that code (for example I wonder: do they really need to be different?).

Looking forward to your refactoring, feel free to ping me to get more annoying comments from me :-P
