### PR TITLE
no GDAL resampling with unknown data type

### LINKED ISSUE #53176: Incompatible layer set as "elevation surface" causes "Global Map Shading" to crash QGIS
### What is the bug or the crash?

"Global map shading" causes QGIS to crash if an unsuitable layer has `elevationProperties` enabled.

### Steps to reproduce the issue

1. Add a layer to QGIS using Quick Map Services plugin (this is simply a convenient way to get an unsuitable layer to reproduce the crash - the plugin itself is not necessary to cause the crash).
2. In the Elevation tab in the layer properties, enable "Represents Elevation Surface".  This could also be done programmatically, perhaps even in a plugin.
3. With the web map layer turned on, select any layer and in the layer styling panel click on the Shading Renderer tab:
image
4. Enable "Global Map Shading".
5. QGIS will crash.

Alternatively, with the web map layer turned off, enable "Global Map Shading", then turn the layer on and it will crash.

### Versions

QGIS version
3.30.2-'s-Hertogenbosch
QGIS code revision
0992b533
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.4
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
annotationManager
0.5
annotation_labels
1.0.1
AnotherDXF2Shape
1.2.7
changeDataSource
3.1
coveragebuilder
version 0.5.0
Equal_area_slope_QGIS_Plugin
0.1
file_management
0.1
geometry_paster
0.2
joinmultiplelines
Version 0.4.1
layout_panel-main
0.3
MemoryLayerSaver
4.0.4
nominatim
1.4.5
pathfinder
version 0.4.2
plugin_reloader
0.9.3
precisioncursor4qgis-main
0.2E
QCopycanvas
0.7
qgis_resource_sharing
1.0.0
valuetool
3.0.15
workbench
0.0.4
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
civilplan
1.0
quick_map_services
0.19.33

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

```
Python Stack Trace
Windows fatal exception: access violation

Thread 0x00005714 (most recent call first):



Stack Trace


CPLODBCDriverInstaller::RemoveDriver :
CPLODBCDriverInstaller::RemoveDriver :
CPLODBCDriverInstaller::RemoveDriver :
CPLODBCDriverInstaller::RemoveDriver :
resampleSingleBandRasterStatic qgsgdalutils.cpp:278
QgsGdalUtils::resampleSingleBandRaster qgsgdalutils.cpp:305
QgsRasterLayerRenderer::drawElevationMap qgsrasterlayerrenderer.cpp:520
QgsRasterLayerRenderer::render qgsrasterlayerrenderer.cpp:372
QgsMapRendererParallelJob::renderLayerStatic qgsmaprendererparalleljob.cpp:373
QtConcurrent::MapKernel > > > >,QtConcurrent::FunctionWrapper1QtConcurrent::MapKernel > >,QtConcurrent::FunctionWrapper1 >::runIterations qtconcurrentmapkernel.h:78
QtConcurrent::IterateKernel > >,void>::threadFunction qtconcurrentiteratekernel.h:217
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.30.2-'s-Hertogenbosch
QGIS code revision: 0992b533
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.4
Running against GDAL: 3.6.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045
```

### PR DESCRIPTION
**Pull request by vcloarec**
Fix #53176 
Crash coming from GDAL resampling of unknown data type.
More generally, this fix also secures the resample operation by breaking it if `GDALWarpOperation` returns an error during initialization.

### CODE REVIEW

File: src/core/qgsgdalutils.cpp [hunk 1]
```diff
@@ -272,10 +272,11 @@ static bool resampleSingleBandRasterStatic( GDALDatasetH hSrcDS, GDALDatasetH hD
   psWarpOptions->papszWarpOptions = CSLSetNameValue( psWarpOptions-> papszWarpOptions, "INIT_DEST", "NO_DATA" );
 
   // Initialize and execute the warp operation.
+  bool retVal = false;
   GDALWarpOperation oOperation;
-  oOperation.Initialize( psWarpOptions.get() );
-
-  const bool retVal { oOperation.ChunkAndWarpImage( 0, 0, GDALGetRasterXSize( hDstDS ), GDALGetRasterYSize( hDstDS ) ) == CE_None };
+  CPLErr initResult = oOperation.Initialize( psWarpOptions.get() );
+  if ( initResult != CE_Failure  && initResult != CE_Fatal )
```
Comment (rouault) [inline src/core/qgsgdalutils.cpp:278]: testing for CE_Fatal is not necessary. CE_Fatal will never been seen by QGIS as they will abort() the process before.
```suggestion
  if ( initResult != CE_Failure )
```

**Review by rouault — APPROVED** [review]

File: src/core/raster/qgsrasterlayerrenderer.cpp [hunk 2]
```diff
@@ -483,45 +483,48 @@ void QgsRasterLayerRenderer::drawElevationMap()
...
-
-      // For coordinate transformation, we try to obtain a coordinate operation string from the transform context.
-      // Depending of the CRS, if we can't we use GDAL transformation directly from the source and destination CRS
-      QString coordinateOperation;
-      const QgsCoordinateTransformContext &transformContext = renderContext()->transformContext();
-      if ( transformContext.mustReverseCoordinateOperation( mRasterViewPort->mDestCRS, mRasterViewPort->mSrcCRS ) )
-        coordinateOperation = transformContext.calculateCoordinateOperation( mRasterViewPort->mSrcCRS, mRasterViewPort->mDestCRS );
-      else
-        coordinateOperation = transformContext.calculateCoordinateOperation( mRasterViewPort->mDestCRS, mRasterViewPort->mSrcCRS );
+      if ( dataType != Qgis::DataType::UnknownDataType ) // resampling data by GDAL is not coptible with unknown data type
```
Comment (nyalldawson) [inline src/core/raster/qgsrasterlayerrenderer.cpp:486]:
```suggestion
      if ( dataType != Qgis::DataType::UnknownDataType ) // resampling data by GDAL is not compatible with unknown data type
```
