### PR TITLE
[PyQGIS] : Fix QgsFeatureFilterModel SIP interface

### LINKED ISSUE #42488: Cannot instantiate QgsFeatureFilterModel using PyQGIS
When I try to create new instance of QgsFeatureFilterModel using Python (plugin or in console) i get this:

```
>>>model = QgsFeatureFilterModel()
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.18\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
TypeError: qgis._core.QgsFeatureFilterModel represents a C++ abstract class and cannot be instantiated
```
It works flawlessly in QGIS 3.12. Starts to complain after upgrade to 3.14

### PR DESCRIPTION
**Pull request by troopa81**
Fixes #42488 : private methods are not part of SIP files and *requestToReloadCurrentFeature* needs to be known by SIP so it doesn't consider QgsFeatureFilterModel abstract.

### CODE REVIEW

File: src/core/qgsfeaturefiltermodel.h [hunk 1]
```diff
@@ -107,11 +107,14 @@ class CORE_EXPORT QgsFeatureFilterModel : public QgsFeaturePickerModelBase
      */
     void extraIdentifierValuesChanged();
 
-  private:
-    QgsFeatureExpressionValuesGatherer *createValuesGatherer( const QgsFeatureRequest &request ) const override;
+  protected:
 
     void requestToReloadCurrentFeature( QgsFeatureRequest &request ) override;
```
Comment (nyalldawson) [inline src/core/qgsfeaturefiltermodel.h:113]: Why not re-add the private tag here?

Comment (troopa81) [reply src/core/qgsfeaturefiltermodel.h]: I was not aware of the SIP_FORCE macro, I changed my PR

**Review by nyalldawson — APPROVED** [review]
