### PR TITLE
Fixed dropping PostgreSQL materialized views.

### LINKED ISSUE #36164: Cannot remove materialized views from QGIS Browser
QGIS master on Ubuntu 18.04

```
Unable to delete view "public"."xxx": 
ERROR:  "xxx" is not a view
HINT:  Use DROP MATERIALIZED VIEW to remove a materialized view
```

### PR DESCRIPTION
**Pull request by espinafre**
By default, the PostgreSQL provider allows the user to drop database
objects from the Browser tree; however, the PostgreSQL syntax for
dropping materialized views is different from dropping ordinary views.
This fixes it, and adds the keyword "MATERIALIZED" accordingly.

Fixes #36164

There is no unit test, as this is a purely interactive action by the user:
image

It will be great if this is backported to 3.12 and 3.10.

### CODE REVIEW

File: src/providers/postgres/qgspostgresdataitems.cpp [hunk 1]
```diff
@@ -59,7 +59,7 @@ bool QgsPostgresUtils::deleteLayer( const QString &uri, QString &errCause )
   QString type = resViewCheck.PQgetvalue( 0, 0 );
   if ( type == QLatin1String( "v" ) || type == QLatin1String( "m" ) )
   {
-    QString sql = QString( "DROP VIEW %1" ).arg( schemaTableName );
+    QString sql = QString( "DROP %1VIEW %2" ).arg( type == QLatin1String( "m" ) ? "MATERIALIZED " : QString(), schemaTableName );
```
Comment (m-kuhn) [inline src/providers/postgres/qgspostgresdataitems.cpp:62]:
```suggestion
    QString sql = QStringLiteral( "DROP %1VIEW %2" ).arg( type == QLatin1String( "m" ) ? QStringLiteral( "MATERIALIZED " ) : QString(), schemaTableName );
```

**Review by m-kuhn — APPROVED** [review]

File: src/providers/postgres/qgspostgresdataitems.cpp (hunk 1 above)
Comment (espinafre) [reply src/providers/postgres/qgspostgresdataitems.cpp]: Commit da42f4c incorporate these changes. Thank you!

Comment (m-kuhn) [reply src/providers/postgres/qgspostgresdataitems.cpp]: I got a notification when you pushed it. Thanks. Will merge when green.

**Comment by espinafre** [comment]
@m-kuhn , all green here :+1:
