### PR TITLE
[SelectiveMasking] When masking, set dpi for new allocated image

### LINKED ISSUE #44426: Label masking causes layout vector & raster to be mis-aligned
### What is the bug or the crash?

It seems that if label masking is enabled, when viewing the map layout, raster and vector layers appear mis-aligned on the layout. If printing, or exporting to PDF, or exporting to raster the output is correct.

Disable masking, and the layout is then correctly displayed.

I have attached a QGIS project file with data. Description as follows:
 QGIS Project file
 Layout with two identical map windows, one with masking one without.  Its easy to see that when looking at the screen one is not correctly aligned.
 PDF output (correct)
 Screen shot (alignment issues clear to see)

Tested on both 3.20.0 and 3.20.1
Not an issue on versions prior to 3.20

Regards
Tony
[QGIS-3.20-Masking-Issues.zip](https://github.com/qgis/QGIS/files/6896055/QGIS-3.20-Masking-Issues.zip)

### Steps to reproduce the issue

As above

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.20.1-Odense | QGIS code revision | 1c3c5cd6
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.1
PROJ version | 8.1.0
EPSG Registry database version | v10.018 (2021-04-02)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins | ClipMultipleLayersDataPlotlygisquick-qgis-pluginImportPhotoslinz-data-importerMerginprofiletoolqgis2webqgiscloudqgis_resource_sharingQPackageQuickOSMquick_map_servicesSentinelHubsplitmultipartSplitPolygonShowingAreasdb_managerprocessing

</body></html>

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by troopa81**
Fixes #44426 : When we render whith a different dpi target and there is selective masking involved (which is the case when we preview render of layout), we need to set the dpi of the new allocated image. If not, raster layer would be scaled.

I also needed to update the way we compute dpi in *QgsRasterLayerRenderer()* because when parallel renderering, painter is null at the moment of the constructor call.

### CODE REVIEW

File: src/core/maprenderer/qgsmaprendererjob.cpp [hunk 1]
```diff
@@ -374,6 +374,8 @@ QImage *QgsMapRendererJob::allocateImage( QString layerId )
   QImage *image = new QImage( mSettings.deviceOutputSize(),
                               mSettings.outputImageFormat() );
   image->setDevicePixelRatio( static_cast<qreal>( mSettings.devicePixelRatio() ) );
+  image->setDotsPerMeterX( 1000 * mSettings.outputDpi() / 25.4 );
```
Comment (nyalldawson) [inline src/core/maprenderer/qgsmaprendererjob.cpp:377]: Doesn't this also need
 
```
    1000 * mSettings.outputDpi() / 25.4 * mSettings.devicePixelRatio()
```

? (as per qgsmaprenderersequentialjob.cpp:32)

Comment (troopa81) [reply src/core/maprenderer/qgsmaprendererjob.cpp]: Yes, right!

**Review by nyalldawson — APPROVED** [review]
