### PR TITLE
[BlankSegment] Fix snapping when selecting feature

### LINKED ISSUE #65149: Blank segments tool bugs
### What is the bug or the crash?

- Eye icon on my latest master doesnt match as shown in the [screencast](https://github.com/qgis/QGIS-Documentation/issues/10569).
- Interaction in the map canvas only possible from Layer Styling panel, Layer properties dialog doesnt allow blank segments creation.
- QGIS says no feature was detected even though I already clicked on exact position, zoomed in as much as possible and enhanced the search tolerance.
- Overall, I couldnt replicate the same process as displayed on the screencast.
- Access the test layer [here](https://github.com/user-attachments/files/25673651/test.layer.blank.segments.zip)

Image

working on [docs](https://github.com/qgis/QGIS-Documentation/pull/10709)

### Steps to reproduce the issue

Load the layer > configure symbology > set symbol layer type as marker line >  clicked marker line on the listed type > scroll down to find blank segment group > enable the data-defined property to store the blank segment distances (using either an existing field or an auxiliary storage field) > click on the tool (eye icon) to activate

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.99.0-Master</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/cea2252c89e">cea2252c89e</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>6.8.1</td></tr><tr><td>Python version</td><td>3.12.12</td></tr><tr><td>GDAL version</td><td>3.13.0dev-e9fdd2949d (Compiled)<br/>3.13.0dev-26b6211104 (Running)</td></tr><tr><td>PROJ version</td><td>9.7.1</td></tr><tr><td>EPSG Registry database version</td><td>v12.029 (2025-10-03)</td></tr><tr><td>GEOS version</td><td>3.14.1-CAPI-1.20.5</td></tr><tr><td>SFCGAL version</td><td>No support</td></tr><tr><td>GeographicLib version</td><td>2.7.0</td></tr><tr><td>SQLite version</td><td>3.50.4</td></tr><tr><td>PDAL version</td><td>2.10.0</td></tr><tr><td>PostgreSQL client version</td><td>17.3</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.3.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Windows 11 Version 25H2</td></tr><tr><td colspan="2"><i>This copy of QGIS writes debugging output.</i></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by troopa81**
And improve tooltip and disable state

Fix #65149

## AI tool usage

No

**Funded by Stadt Frankfurt am Main and Oslandia**

### CODE REVIEW

File: src/gui/maptools/qgsmaptooleditblanksegments.cpp [hunk 1]
```diff
@@ -449,7 +449,7 @@ void QgsMapToolEditBlankSegmentsBase::canvasPressEvent( QgsMapMouseEvent *e )
     case State::SelectFeature:
     {
       //find the closest feature to the pressed position
-      const QgsPointLocator::Match m = mCanvas->snappingUtils()->snapToCurrentLayer( e->pos(), QgsPointLocator::Area );
+      const QgsPointLocator::Match m = mCanvas->snappingUtils()->snapToCurrentLayer( e->pos(), QgsPointLocator::All );
```
Comment (uclaros) [inline src/gui/maptools/qgsmaptooleditblanksegments.cpp]: I think setting this to `Edge` only would be better here. You don't really care if it's a middle of segment, vertex or area, you only care about the feature. And Area/Centroid may pick the "wrong" (unwanted) fid when features are overlapping.

Comment (troopa81) [reply src/gui/maptools/qgsmaptooleditblanksegments.cpp]: I changed it to Edge and Area because this feature can apply to polygons also, and I imagine that user would expect to click on the whole polygon area to select it, not just the line, don't you think?

Comment (uclaros) [reply src/gui/maptools/qgsmaptooleditblanksegments.cpp]: Since this feature is about the symbology on the _perimeter_ of a polygon, I would expect that users will try to click on that. I suspect that a common use case would even be for polygons with no fill symbol, but only linear symbology.
`Area` could work too, as long as it does not get prioritized when there are `Edge` hits on overlapping features.

Comment (troopa81) [reply src/gui/maptools/qgsmaptooleditblanksegments.cpp]: That makes sense, I restricted to Edge, thanks for the input

**Comment by troopa81** [comment]
@uclaros Is it ok to approve/merge this one ?

**Comment by uclaros** [comment]
Sorry, I hadn't checked the rest of the code.

`vectorLayer()` can be `nullptr`, for example when editing a style in the style manager, so it should be checked. This applies to existing code too, not only this PR.

The QMainWindow cast check feels a little hacky, but I can't think of a better solution, so :+1:

**Comment by troopa81** [comment]
> vectorLayer() can be nullptr, for example when editing a style in the style manager, so it should be checked. This applies to existing code too, not only this PR.

Done, within the scope of this PR

> The QMainWindow cast check feels a little hacky, but I can't think of a better solution, so 👍

Agreed, but that the best I manage to come up with :man_shrugging:

File: src/gui/symbology/qgssymbollayerwidget.cpp [hunk 2]
```diff
@@ -2412,10 +2374,26 @@ void QgsTemplatedLineSymbolLayerWidget::updateBlankSegmentsWidget()
       break;
   }
 
-  if ( !mEditBlankSegmentsBtn->isEnabled() )
+  if ( !qobject_cast<QMainWindow *>( QApplication::activeWindow() ) )
```
Comment (nyalldawson) [inline src/gui/symbology/qgssymbollayerwidget.cpp]: You could possibly use QgsPanelWidget::findParentPanel( this ) here, to detect if the widget is being shown in a panel widget stack (ie -- not in the dialog)

Comment (troopa81) [reply src/gui/symbology/qgssymbollayerwidget.cpp]: I thought about that (or something alike, I wasn't aware of this method) but at the initialization the parent is null, it would be parented later.

Comment (nyalldawson) [reply src/gui/symbology/qgssymbollayerwidget.cpp]: What if that logic was moved to a showevent?

Comment (troopa81) [reply src/gui/symbology/qgssymbollayerwidget.cpp]: Thanks for the proposal! Done 5be33adf1df

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
Thanks @troopa81 -- that's much cleaner!
