### PR TITLE
Fix shapefile extent not shrinking

### LINKED ISSUE #23661: Wrong "Zoom to layer" extent on a shapefile layer with logically deleted records
Author Name: **Alessandro Sarretta** (@alesarrett)
Original Redmine Issue: [15739](https://issues.qgis.org/issues/15739)
Affected QGIS version: 3.4.4
Redmine category:unknown

---
When clicking on the "Zoom to layer" function on a shapefile with logically-deleted records in the DBF, the zoom wrongly considers also the logically deleted features.
Opening the attributes table for the layer correctly omits the logically-deleted records.

Test file can be found attached to this PostGIS ticket:
https://trac.osgeo.org/postgis/ticket/3645

---

Related issue(s): #23657 (relates), #23662 (relates)
Redmine related issue(s): [15735](https://issues.qgis.org/issues/15735), [15740](https://issues.qgis.org/issues/15740)

---

### PR DESCRIPTION
**Pull request by tarot231**
Upstream states that when updating existing features in a shapefile, the extent will not be correct and then recomputation must be forced.
https://gdal.org/drivers/vector/shapefile.html#spatial-extent

With this fix, the attached script will return the correct extent without uncommenting.
https://github.com/qgis/QGIS/files/13325893/bug_extent_of_shapefile.py.txt

Fixes #23661, #13985

### CODE REVIEW

**Comment by rouault** [comment]
> With this fix, the attached script will return the correct extent without uncommenting.

I've strong suspicion this fix will have transient effect only as the recomputated extent will not be serialized as far as I can see. QgsOgrProvider::extent() should also be changed to extend https://github.com/qgis/QGIS/blob/461a3158d01f9651af434df8f8b18717d76a0d59/src/core/providers/ogr/qgsogrprovider.cpp#L1131 to the shapefile driver.
And we'd need a test for that in /home/even/qgis/qgis/tests/src/python/test_provider_shapefile.py

**Comment by tarot231** [comment]
Thanks for the review. Fixed.

File: src/core/providers/ogr/qgsogrprovider.cpp [hunk 1]
```diff
@@ -1128,7 +1128,10 @@ QgsRectangle QgsOgrProvider::extent() const
     // get the extent_ (envelope) of the layer
     QgsDebugMsgLevel( QStringLiteral( "Starting get extent" ), 3 );
 
-    if ( mForceRecomputeExtent && mValid && mGDALDriverName == QLatin1String( "GPKG" ) && mOgrOrigLayer )
+    if ( mForceRecomputeExtent && mValid &&
+         ( mGDALDriverName == QLatin1String( "GPKG" ) ||
+           ( mGDALDriverName == QLatin1String( "ESRI Shapefile" ) && mWriteAccess) ) &&
```
Comment (rouault) [inline src/core/providers/ogr/qgsogrprovider.cpp:1133]: why the mWriteAccess test is just for shapefile ? It should also apply to GPKG

File: tests/src/python/test_provider_shapefile.py [hunk 2]
```diff
@@ -1142,6 +1142,18 @@ def testFilterWithComment(self):
...
+    def testRecomputeExtent(self):
+        """Test shrink extent correctly"""
+
+        vl = self.getEditableLayer()
+        extent_area = vl.extent().area()
+        vl.startEditing()
+        for fet in vl.getFeatures():
+            vl.translateFeature(fet.id(), -1, -1)
+        vl.commitChanges()
+        self.assertEqual(vl.extent().area(), extent_area)
```
Comment (rouault) [inline tests/src/python/test_provider_shapefile.py:1154]: This test isn't super convincing. You should really test that the extent has been updated (if it hasn't been updated, the area will also be preserved). And it should also test that the extent is OK after closing and re-opening the dataset

File: src/core/providers/ogr/qgsogrprovider.cpp (hunk 1 above)
Comment (tarot231) [reply src/core/providers/ogr/qgsogrprovider.cpp]: This is because when I tried bug_extent_of_shapefile.py without mWriteAccess test, only ESRI Shapefile had following error:

ERROR 6: RecomputeExtent : unsupported operation on a read-only datasource.

I didn't add the code for GPKG because it didn't have the error originally.
I'll add the test for GPKG in the next commit.

File: tests/src/python/test_provider_shapefile.py (hunk 2 above)
Comment (tarot231) [reply tests/src/python/test_provider_shapefile.py]: Thank you for pointing this out.

**Review by rouault — APPROVED** [review]

**Comment by agiudiceandrea** [comment]
Since the issue also occurs using QGIS 3.28, shouldn't this PR be backported to the release-3_28 branch?

**Comment by rouault** [comment]
> shouldn't this PR be backported to the release-3_28 branch?

That doesn't seem a critical enough issue to me to do so
